### ISSUE TITLE
addPlugin not working

### ISSUE THREAD

**Issue by tobq** [eslint/eslint#10207] opened 2018-04-12 15:21 UTC
**Tell us about your environment**

* **ESLint Version:** 5.6
* **Node Version:** 9
* **npm Version:** 5.8

**What parser (default, Babel-ESLint, etc.) are you using?** 

**Please show your full configuration:**
config:

```js

    cli = new eslint.CLIEngine({
        //useEslintrc: true,
        "plugins": ["react"],
        "parserOptions": {
            "ecmaVersion": 6,
            "sourceType": "module",
            "ecmaFeatures": {
                "jsx": true,
                'impliedStrict': true
            }
        },
        "env": {
            "es6": true,
            "browser": true,
            "node": true
        },
        "extends": [
            "react"
        ],
        "rules": {
        }
    });
cli.addPlugin("react"); // error: addplugin is not a function


```

**Comment by tobq** [comment] 2018-04-12 15:25
When the call for addPlugin is removed, I get 

`129:17: Unexpected token <` from `cli.executeOnText(JSXsourcecode)`

**Comment by not-an-aardvark** [comment] 2018-04-12 17:43
Hi, thanks for the report. What version of ESLint are you using? I notice that you listed "5.6" as the ESLint version, but no such version exists.

**Comment by tobq** [comment] 2018-04-13 08:16
node 9.9 - eslintn 5.0.0 alpha.
when I got home i tested with node 9.6 which installed eslint 4.19 and things were working nicely.

the alpha needs work..

**Comment by not-an-aardvark** [comment] 2018-04-13 16:09
When I ran your code on v5.0.0-alpha, I did not get an error that "addplugin is not a function". However, I did get another error (`TypeError: Cannot read property 'environments' of undefined`). 

The issue is that you need to provide the plugin as the second argument to the `addPlugin` call. `addPlugin` processes a given plugin, but does not load plugins by name from the filesystem. For example, you could do something like this:

```js
cli.addPlugin("react", require("eslint-plugin-react"));
```

**Comment by Aladdin-ADD** [comment] 2018-07-22 08:07
Closing as it seems working as intended. Please feel free to comment here or stop by our [Gitter chat](https://gitter.im/eslint/eslint) if you have any further questions. Thanks!

**Closed by Aladdin-ADD** 2018-07-22 08:07 UTC
Labels: works as intended
