### ISSUE TITLE
Fix max-statements-per-line automatically

### ISSUE THREAD

**Issue by bokub** [eslint/eslint#9063] opened 2017-08-02 15:16 UTC
**Tell us about your environment**

* **ESLint Version:** 3.18.0
* **Node Version:** v8.1.2
* **npm Version:** 5.0.3

**Configuration**

```js
max-statements-per-line: error
```

**JS code**
```js
const i = 0; console.log(i);
```

**Command used**
```sh
eslint --fix
```

**Expected output**
Code fixed, i.e on two different lines

**Actual output**
Error:  `max-statements-per-line`

**Comment by gyandeeps** [comment] 2017-08-02 15:40
This rule is not auto-fixable. Not sure if its a good idea to make it like that... maybe it is...

**Comment by bokub** [comment] 2017-08-02 16:47
In the case of a `max-statements-per-line` equal to 1, I think it would be a great idea.

You could transform a minified js file into a beautifully formatted file without the use of an external beautifier!

[Prettier](https://github.com/prettier/prettier#how-does-it-compare-to-eslint-or-tslint-stylelint) does that by "reprinting the entire program from scratch in a consistent way"

**Comment by not-an-aardvark** [comment] 2017-08-02 17:05
> You could transform a minified js file into a beautifully formatted file without the use of an external beautifier!
>
> [Prettier](https://github.com/prettier/prettier#how-does-it-compare-to-eslint-or-tslint-stylelint) does that by "reprinting the entire program from scratch in a consistent way"

Just to make sure we're discussing the same goals here -- reprinting the entire program from scratch is a nice feature of Prettier as a code formatter, but it's slightly different from the typical use case of a linter, which is to point out and correct individual problems in a file rather than rewriting the whole thing. Personally I think being able to beautify minified files with ESLint would be nice, but it's not really the main goal of ESLint rules. If you're trying to beautify files, using external beautifiers is probably the best way to go, because they are designed for that purpose.

Having said that, I wouldn't mind adding autofixing to this rule. One slight concern I have is that we might only be able to autofix `max-statements-per-line: 1`, since it would be difficult to guess how the user intended to split lines for different configurations.

**Comment by bokub** [comment] 2017-08-02 17:14
Yeah, I wasn't suggesting to do the same as Prettier does, just showing their way of dealing with it.

I guess we're discussing the same goals then, fixing automatically the `max-statements-per-line` error when the rule is "one statement per line".

**Comment by not-an-aardvark** [comment] 2018-01-19 15:56
Thanks for your interest in improving ESLint. Unfortunately, it looks like this issue didn't get consensus from the team, so I'm closing it. We define [consensus](http://eslint.org/docs/maintainer-guide/issues.html#consensus) as having three :+1:s from team members, as well as a team member willing to champion the proposal. This is a high bar by design -- we can't realistically accept and maintain every feature request in the long term, so we only accept feature requests which are useful enough that there is consensus among the team that they're worth adding.

Since ESLint is pluggable and can load custom rules at runtime, the lack of consensus among the ESLint team doesn't need to be a blocker for you using this in your project, if you'd find it useful. It just means that you would need to [implement the rule](http://eslint.org/docs/developer-guide/working-with-rules) yourself, rather than using a bundled rule that is packaged with ESLint.

**Closed by not-an-aardvark** 2018-01-19 15:56 UTC
Labels: enhancement, evaluating, rule
