### ISSUE TITLE
New optional flags for arrow-body-style

### ISSUE THREAD

**Issue by chimericdream** [eslint/eslint#10331] opened 2018-05-10 14:28 UTC
The general idea with this proposed change is that we'd like to have more flexibility around when to use the shorthand arrow syntax vs when to require braces around the function body.

The biggest side effect of this proposal is that the `--fix` option on the command line would not easily be able to auto-fix code which mixes body styles. So users who enable one or more of the new flags will give up the automatic fixing of problems reported by this rule. This would not affect users who continue to use the current behavior, however.

**What rule do you want to change?**
`arrow-body-style`

**Does this change cause the rule to produce more or fewer warnings?**
Fewer

**How will the change be implemented? (New option, new default behavior, etc.)?**
* New boolean flag for `always`
  * 'allowSingleLine': Don't require braces around the body of simple, single-line arrow functions (default: false ==> current behavior)
* New boolean flags for `as-needed` and `never`
  * 'ignoreMultiline': If the body of the method is a single expression which spans multiple lines (e.g. a function call or object with many properties), allow braces around the body for readability (default: false ==> current behavior)
  * 'ignoreNested': If the body of the method is another arrow function, allow braces (and a `return` statement) for readability (default: false ==> current behavior)

**Please provide some example code that this change will affect:**

#### Current behavior
```js
/*eslint arrow-body-style: ["error", "always"]*/
/*eslint-env es6*/

const performComplexTask = data => {
    // do something with data
    // ...
    // no return value
};


// error
let add = (a, b) => a + b;

// valid, but more verbose than necessary
let add = (a, b) => {
    return a + b;
};


// error
let makeSimpleThing = (a, b, c) => ({a, b, c});

// valid, but more verbose than necessary
let makeSimpleThing = (a, b, c) => {
    return {a, b, c};
};


// valid
let makeComplexThing = simpleThing => {
    return {
        ...simpleThing,
        propA: 'val a'
        propB: 'val b'
        propC: 'val c'
        propD: 'val d'
        propE: 'val e'
        propF: 'val f'
        propG: 'val g'
        propH: 'val h'
        propI: 'val i'
    };
};


// valid
let someFunc = foo => {
    return bar => {
        return {foo, bar};
    };
};


// valid
// easy to see that performComplexTask() does not return a value
let someOtherFunc = baz => {
    performComplexTask(innerFunc({
        prop: 'value',
        otherProp: 'other value',
        oneMore: 'yet another value',
        complexProp: someFunc(baz)
    }));
};
```

```js
/*eslint arrow-body-style: ["error", "never"]*/
/*eslint-env es6*/

const performComplexTask = data => {
    // do something with data
    // ...
    // no return value
};


// error
let add = (a, b) => {
    return a + b;
};

// valid
let add = (a, b) => a + b;


// valid
let makeSimpleThing = (a, b, c) => ({a, b, c});


// valid, but could be confusing at first glance
let makeComplexThing = simpleThing => ({
    ...simpleThing,
    propA: 'val a'
    propB: 'val b'
    propC: 'val c'
    propD: 'val d'
    propE: 'val e'
    propG: 'val g'
    propF: 'val f'
    propH: 'val h'
    propI: 'val i'
});


// valid, but slightly difficult to parse
let someFunc = foo => bar => ({foo, bar});


// valid
// difficult to infer that performComplexTask() does not return a value
let someOtherFunc = baz => performComplexTask(innerFunc({
    prop: 'value',
    otherProp: 'other value',
    oneMore: 'yet another value',
    complexProp: someFunc(baz)
}));
```

#### Proposed behavior
```js
/*eslint arrow-body-style: ["error", "always", {"allowSingleLine": true}]*/
/*eslint-env es6*/

const performComplexTask = data => {
    // do something with data
    // ...
    // no return value
};


// valid
let add = (a, b) => a + b;


// valid, but more verbose than necessary
let makeSimpleThing = (a, b, c) => {
    return {a, b, c};
};

// valid
let makeSimpleThing = (a, b, c) => ({a, b, c});


// valid
let makeComplexThing = simpleThing => {
    return {
        ...simpleThing,
        propA: 'val a'
        propB: 'val b'
        propC: 'val c'
        propD: 'val d'
        propE: 'val e'
        propG: 'val g'
        propF: 'val f'
        propH: 'val h'
        propI: 'val i'
    };
};


// valid, but slightly difficult to parse
let someFunc = foo => bar => ({foo, bar});

// valid, easier to read
let someFunc = foo => {
    return bar => ({foo, bar});
};


// valid
// easy to see that performComplexTask() does not return a value
let someOtherFunc = baz => {
    performComplexTask(innerFunc({
        prop: bat,
        otherProp: 'other value',
        oneMore: 'yet another value',
        complexProp: someFunc(baz)
    }));
};
```

```js
/*eslint arrow-body-style: ["error", "never", {"ignoreMultiline": true, "ignoreNested": true}]*/
/*eslint-env es6*/

const performComplexTask = data => {
    // do something with data
    // ...
    // no return value
};


// valid
let add = (a, b) => a + b;


// valid
let makeSimpleThing = (a, b, c) => ({a, b, c});


// valid, but could be confusing at first glance
let makeComplexThing = simpleThing => ({
    ...simpleThing,
    propA: 'val a'
    propB: 'val b'
    propC: 'val c'
    propD: 'val d'
    propE: 'val e'
    propG: 'val g'
    propF: 'val f'
    propH: 'val h'
    propI: 'val i'
});

// valid, clearer
let makeComplexThing = simpleThing => {
    return {
        ...simpleThing,
        propA: 'val a'
        propB: 'val b'
        propC: 'val c'
        propD: 'val d'
        propE: 'val e'
        propG: 'val g'
        propF: 'val f'
        propH: 'val h'
        propI: 'val i'
    };
};


// valid, but slightly difficult to parse
let someFunc = foo => bar => ({foo, bar});

// valid, easier to read
let someFunc = foo => {
    return bar => ({foo, bar});
};


// valid, but hard to read at a glance
// difficult to infer that performComplexTask() does not return a value
let someOtherFunc = baz => performComplexTask(innerFunc({
    prop: 'value',
    otherProp: 'other value',
    oneMore: 'yet another value',
    complexProp: someFunc(baz)
}));

// valid
// easy to see that performComplexTask() does not return a value
let someOtherFunc = baz => {
    performComplexTask(innerFunc({
        prop: 'value',
        otherProp: 'other value',
        oneMore: 'yet another value',
        complexProp: someFunc(baz)
    }));
};
```

**What does the rule currently do for this code?**
It requires that you choose a particular brace style.

**What will the rule do after it's changed?**
It will allow for more flexibility in arrow function style, increasing overall legibility.

**Comment by not-an-aardvark** [comment] 2018-07-22 07:04
Thanks for creating an issue and for your interest in improving ESLint. Unfortunately, it looks like this issue didn't get consensus from the team, so I'm closing it. We define [consensus](http://eslint.org/docs/maintainer-guide/issues.html#consensus) as having three :+1:s from team members, as well as a team member willing to champion the proposal. This is a high bar by design -- we can't realistically accept and maintain every feature request in the long term, so we only accept feature requests which are useful enough that there is consensus among the team that they're worth adding.

Since ESLint is pluggable and can load custom rules at runtime, the lack of consensus among the ESLint team doesn't need to be a blocker for you using this in your project, if you'd find it useful. It just means that you would need to [implement the rule](http://eslint.org/docs/developer-guide/working-with-rules) yourself, rather than using a bundled rule that is packaged with ESLint.

**Closed by not-an-aardvark** 2018-07-22 07:04 UTC
Labels: enhancement, evaluating, rule
