### ISSUE TITLE
Bug: (fill in) misinformation no shadow

### ISSUE THREAD

**Issue by kaocong** [eslint/eslint#15935] opened 2022-05-29 16:37 UTC
### Environment

Node version:  v14.19.3

npm version:  6.14.17

Local ESLint version:  7.32.0
Global ESLint version: 
Operating System:  window

### What parser are you using?

Default (Espree)

### What did you do?

<details>
<summary>Configuration</summary>

```
'no-shadow-restricted-names': 'error',
```
</details>

```js
function getOptionByCallType (params) {
  if (params.length <= 2) {
    const [
      message,
      options = {}
    ] = params;

    return {
      message,
      ...options,
    };
  }

  const [
    message,
    title = '',
    options = {}
  ] = params;

  return {
    message,
    title,
    ...options,
  };
}
```

### What did you expect to happen?

no error  with first const message and options

### What actually happened?

ESLint: 'message' is already declared in the upper scope on line 227 column 5.(no-shadow)

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by mdjermanovic** [comment] 2022-05-29 20:14
Hi @kaocong, thanks for the issue!

Can you please share your configuration for the `no-shadow` rule?

(the one you provided is for `no-shadow-restricted-names`, which is a different rule)

**Comment by kaocong** [comment] 2022-05-30 06:10
> 你好@kaocong，谢谢你的问题！
> 
> 你能分享一下你的`no-shadow`规则配置吗？
> 
> （您提供的那个是为了`no-shadow-restricted-names`，这是一个不同的规则）

'no-shadow-restricted-names': 'error',

**Comment by kaocong** [comment] 2022-05-30 06:16
> 你好@kaocong，谢谢你的问题！
> 
> 你能分享一下你的`no-shadow`规则配置吗？
> 
> （您提供的那个是为了`no-shadow-restricted-names`，这是一个不同的规则）

sorry, i wrote it wrong

``` js
    'no-shadow': [
      'error',
      {
        builtinGlobals: false,
        hoist: 'all',
      }
    ],
```

**Comment by kaocong** [comment] 2022-05-30 06:34
i also use rule 'no-else-return'.
if i use "hoist: never", It will not report errors.

I think it's a choice between a code  block of and return.
but, i prefer no else return, it's more concise


![image](https://user-images.githubusercontent.com/50489475/170930096-f7cb1a97-5ab7-4e8e-97e2-339d3c008181.png)


Don't know if this is a usage issue or a bug

**Comment by mdjermanovic** [comment] 2022-05-30 11:11
This works as intended since the variables are indeed declared in an upper scope and you have `hoist: 'all'` so the rule reports shadowing regardless of whether the declarations in the upper scope appear in the source code before or after the declarations in the inner scope.

If you prefer `if { /*...*/ return; }  /*...*/ ` over `if { /*...*/ return; } else { /*...*/ }`, then you'll need to rename variables to avoid shadowing (as `hoist: 'all'` disallows all shadowing), or reconfigure the `no-shadow` rule to `hoist: 'never'` (or `hoist: 'functions'`) to allow variables declared inside `if { }` to shadow variables declared after `if { }` in the upper scope.

**Comment by mdjermanovic** [comment] 2022-05-30 12:30
> Don't know if this is a usage issue or a bug

This isn't a bug, since `hoist: 'all'` works as intended, but it can be argued that it is too restrictive. Some of the problems that may occur due to shadowing, for example when the inner variable declaration is removed (or renamed) and then unintentionally its references become references to the outer variable, might be less important if the inner variable was used only while the outer variable is in TDZ, because those references would throw runtime errors and the bug could be noticed right away. However, this cannot always be statically determined, so a new option (or a modifier for `hoist: 'all'`) may end up with a lot of false positives.

Since this is a bug report, I'll mark it as "work as intended" and close the issue. If you have an idea for a new option that would have a different behavior than `hoist: 'all'`, feel free to open a rule change proposal.

**Closed by mdjermanovic** 2022-05-30 12:30 UTC
Labels: works as intended
