### ISSUE TITLE
space-in-brackets error when using es6 import to load a module but not import anything

### ISSUE THREAD

**Issue by aruberto** [eslint/eslint#2404] opened 2015-04-28 13:43 UTC
Using eslint@0.20.0

I have the following file and eslintrc:

```javascript
// app.js
import 'react';
```
```javascript
// .eslintrc
{
  "plugins": [
    "react"
  ],
  "ecmaFeatures": {
    "jsx": true,
    "modules": true,
    "spread": true,
    "globalReturn": false
  },
  "env": {
    "browser": true,
    "node": true,
    "mocha": true,
    "es6": true
  },
  "rules": {
    "space-in-brackets": [2, "never"]
  }
}
```

When running eslint, the following error in thrown:

```javascript
.\node_modules\.bin\eslint.cmd .\src\app.js
.\node_modules\eslint\lib\rules\space-in-brackets.js:233
            if (firstSpecifier.type === "ImportSpecifier" && lastSpecifier.typ
                              ^
TypeError: Cannot read property 'type' of undefined
    at EventEmitter.ImportDeclaration (.\node_modules\eslint\lib\rules\space-in-brackets.js:233:31)
    at emitOne (events.js:82:20)
    at EventEmitter.emit (events.js:166:7)
    at Controller.controller.traverse.enter (.\node_modules\eslint\lib\eslint.js:726:25)
    at Controller.__execute (.\node_modules\eslint\node_modules\estraverse\estraverse.js:393:31)
    at Controller.traverse (.\node_modules\eslint\node_modules\estraverse\estraverse.js:491:28)
    at EventEmitter.module.exports.api.verify (.\node_modules\eslint\lib\eslint.js:719:24)
    at processFile (.\node_modules\eslint\lib\cli-engine.js:197:27)
    at .\node_modules\eslint\lib\cli-engine.js:299:26
    at walk (.\node_modules\eslint\lib\util\traverse.js:81:9)
```

**Comment by gyandeeps** [comment] 2015-04-28 13:47
Duplicate of https://github.com/eslint/eslint/issues/2378
It has been fixed but not yet released.

**Closed** 2015-04-28 16:13 UTC
Labels: question
