### ISSUE TITLE
Rule suggestion: Avoid modifying object references

### ISSUE THREAD

**Issue by lxanders** [eslint/eslint#1600] opened 2014-12-22 16:07 UTC
In my opinion it is generally dangerous to change the input parameter of a function if it is not a primitive type. It could e.g. result in side effects that are hard to debug because the referenced object is changed in the function.

While I think we won't be able to detect every possible fault, I suggest creating a rule that at least catches the simple case:

```js
// These cases could be an error or a warning if the rule is enabled
function foo1 (bar) {
    bar.thisPropertyAlreadyExisted = somethingElse;
}

function foo2 (bar) {
    delete bar.thisPropertyAlreadyExisted;
}

// This is most likely to hard to implement
function foo3 (bar) {
    var temp = bar.thisPropertyAlreadyExisted;
    temp.deepProperty = somethingElse;
}
```

What do you think about this?

**Comment by nzakas** [comment] 2015-06-18 01:39
From @sindresorhus:

I don't have a concrete solution for this, but I'm going to elaborate on the problem.

## Problem

I make a node module. The main export takes an input and some options as an object:

```js
module.exports = function (input, options) {
  return options.foo == 'unicorn' ? input.split('/') : input;
};
```

The module does something with the input based on these options.

The problem is when the module matures and gets more functionality:

```js
module.exports = function (input, options) {
  options.foo = options.bar === true ? 'unicorn' : 'cake';
  return options.foo ? input.split('/') : input;
};
```

As you might notice, we're now suddenly modifying the user supplied object. The change looks harmless, but what if the user uses the same object for multiple invocations.

It's an easy mistake to make, but can result in some really hard to track down bugs.

I've seen this mistake made in countless of modules and code. Even just [today](https://github.com/kevva/screenshot-stream/commit/97e6a6dc4af1a5a5a7c2f495dd0866f06fc08e5a).


## Correct way

The correct solution here is using some kind of extend method like [`Object.assign()`](https://github.com/sindresorhus/object-assign):

```js
var objectAssign = require('object-assign');

module.exports = function (input, options) {
  options = objectAssign({}, options);
  options.foo = options.bar === true ? 'unicorn' : 'cake';
  return options.foo ? input.split('/') : input;
};
```


## Discuss

I was hoping we could discuss what ESLint can do to help with this.

**Comment by mysticatea** [comment] 2015-07-18 22:04
I will work on this.

I will add an option to `no-param-reassign` to disallow assigning to properties of parameters.

```json
{
    "no-param-reassign": [2, {"props": true}]
}
```

To start, I will not support the following pattern:

```js
function foo3 (bar) {
    var temp = bar.thisPropertyAlreadyExisted;
    temp.deepProperty = somethingElse;
}
```

This pattern needs execution path analysis...

How is this thought?

**Comment by gyandeeps** [comment] 2015-07-18 22:17
@nzakas above post from @sindresorhus , the correct solution doesn't actually solve the problem since its a shallow copy.
I think `Object.assign` repo should say that so that the consumers are not confused. I bet very few people know this.

**Comment by mysticatea** [comment] 2015-07-18 22:22
In short...

```js
function foo(a) {
    var b = Object.assign({}, a);
    b.c = 0; // Valid.
    b.d.push(0); // Invalid.
    b.e.f = 0; // Invalid.
}
```

Is this?

**Comment by mysticatea** [comment] 2015-07-19 15:01
Yup, it looks a seed of a rule, but I guess very difficult to make...

**Comment by nzakas** [comment] 2015-07-19 16:10
I'd say don't worry about anything that needs path analysis. Just doing a basic check is good enough to start.

**Closed** 2015-07-23 15:42 UTC
Labels: accepted, enhancement, rule

**Comment by feross** [comment] 2015-07-28 20:33
Is there any way to get the `{ props: true }` behavior without enabling `no-param-reassign`?
