### ISSUE TITLE
Odd thing with certain rules apparently not having a definition unless they are set to off

### ISSUE THREAD

**Issue by TJDoesCode** [eslint/eslint#8869] opened 2017-07-03 03:19 UTC
Okay so I know I just had another issue, but this is a different thing. I'm getting a strange error for certain rules if I don't set them to off. This wasn't that much of an issue for the other rules it happened with because I don't want them, but this is the `for-direction` rule, something I really want. I can't get it to think it has a definition unless I set it to `off`, but it's in my config. I think this is me doing something stupid, but I'm stumped. The only thing I can think of doing to fix this is to disable the next line, but that's not something I really want to do to every file, and I think that there's an underlying cause to this that should make me not really want to do that. I'd much rather fix this properly then ignore it and do a botch to shut it up.

**Environment:**

* **ESLint Version:** v4.1.1
* **Node Version:** v8.1.2
* **npm Version:** v5.0.4

**Parser:** default

**Full configuration:**
```module.exports = {
  "env": {
    "es6": true,
    "node": true
  },
  "extends": "eslint:recommended",
  "parserOptions": {
    "sourceType": "module",
    "ecmaVersion": "2017"
  },
  "rules": {
    "accessor-pairs": "error",
    "array-bracket-newline": "off",
    "array-bracket-spacing": [
      "error",
      "never"
    ],
    "array-callback-return": "error",
    "array-element-newline": "off",
    "arrow-body-style": "error",
    "arrow-parens": "off",
    "arrow-spacing": [
      "error",
      {
        "after": true,
        "before": true
      }
    ],
    "block-scoped-var": "error",
    "block-spacing": "error",
    "brace-style": [
      "error",
      "1tbs"
    ],
    "callback-return": "error",
    "camelcase": "error",
    "capitalized-comments": [
      "error",
      "never"
    ],
    "class-methods-use-this": "error",
    "comma-dangle": "error",
    "comma-spacing": [
      "error",
      {
        "after": true,
        "before": false
      }
    ],
    "comma-style": [
      "error",
      "last"
    ],
    "complexity": "off",
    "computed-property-spacing": "error",
    "consistent-return": "off",
    "consistent-this": "error",
    "curly": "off",
    "default-case": "error",
    "dot-location": [
      "error",
      "property",
    ],
    "dot-notation": [
      "error",
      {
        "allowKeywords": true,
      },
    ],
    "eol-last": "error",
    "eqeqeq": "error",
    "for-direction": "warn",
    "func-call-spacing": "error",
    "func-name-matching": "error",
    "func-names": [
      "error",
      "never"
    ],
    "func-style": "off",
    "generator-star-spacing": "error",
    "global-require": "off",
    "guard-for-in": "warn",
    "handle-callback-err": "error",
    "id-blacklist": "error",
    "id-length": "off",
    "id-match": "error",
    "indent": "off",
    "indent-legacy": "off",
    "init-declarations": "off",
    "jsx-quotes": "error",
    "key-spacing": "error",
    "keyword-spacing": [
      "error",
      {
        "after": true,
        "before": true
      }
    ],
    "line-comment-position": "off",
    "linebreak-style": [
      "error",
      "unix"
    ],
    "lines-around-comment": "error",
    "lines-around-directive": "error",
    "max-depth": "error",
    "max-len": "off",
    "max-lines": "off",
    "max-nested-callbacks": "error",
    "max-params": "off",
    "max-statements": 'off',
    "max-statements-per-line": "error",
    "multiline-ternary": [
      "error",
      "never"
    ],
    "new-cap": "error",
    "new-parens": "error",
    "newline-after-var": "off",
    "newline-before-return": "error",
    "newline-per-chained-call": "error",
    "no-alert": "error",
    "no-array-constructor": "error",
    "no-await-in-loop": "error",
    "no-bitwise": "error",
    "no-buffer-constructor": "off",
    "no-caller": "error",
    "no-catch-shadow": "error",
    "no-confusing-arrow": "error",
    "no-console": "off",
    "no-continue": "error",
    "no-div-regex": "error",
    "no-duplicate-imports": "error",
    "no-else-return": "error",
    "no-empty-function": "error",
    "no-eq-null": "error",
    "no-eval": "error",
    "no-extend-native": "error",
    "no-extra-bind": "error",
    "no-extra-label": "error",
    "no-extra-parens": "error",
    "no-floating-decimal": "error",
    "no-implicit-coercion": "error",
    "no-implicit-globals": "error",
    "no-implied-eval": "error",
    "no-inline-comments": "off",
    "no-invalid-this": "error",
    "no-iterator": "error",
    "no-label-var": "error",
    "no-labels": "error",
    "no-lone-blocks": "error",
    "no-lonely-if": "error",
    "no-loop-func": "error",
    "no-magic-numbers": "off",
    "no-mixed-operators": "error",
    "no-mixed-requires": "error",
    "no-multi-assign": "error",
    "no-multi-spaces": "error",
    "no-multi-str": "error",
    "no-multiple-empty-lines": "error",
    "no-native-reassign": "error",
    "no-negated-condition": "error",
    "no-negated-in-lhs": "error",
    "no-nested-ternary": "error",
    "no-new": "error",
    "no-new-func": "error",
    "no-new-object": "error",
    "no-new-require": "error",
    "no-new-wrappers": "error",
    "no-octal-escape": "error",
    "no-param-reassign": "off",
    "no-path-concat": "warn",
    "no-plusplus": "error",
    "no-process-env": "error",
    "no-process-exit": "error",
    "no-proto": "error",
    "no-prototype-builtins": "error",
    "no-restricted-globals": "error",
    "no-restricted-imports": "error",
    "no-restricted-modules": "error",
    "no-restricted-properties": "error",
    "no-restricted-syntax": "error",
    "no-return-assign": "error",
    "no-return-await": "error",
    "no-script-url": "error",
    "no-self-compare": "error",
    "no-sequences": "error",
    "no-shadow": "off",
    "no-shadow-restricted-names": "error",
    "no-spaced-func": "error",
    "no-sync": "error",
    "no-tabs": "off",
    "no-template-curly-in-string": "error",
    "no-ternary": "off",
    "no-throw-literal": "error",
    "no-trailing-spaces": "error",
    "no-undef-init": "error",
    "no-undefined": "error",
    "no-underscore-dangle": "error",
    "no-unmodified-loop-condition": "error",
    "no-unneeded-ternary": "error",
    "no-unused-expressions": "error",
    "no-unused-vars": "warn",
    "no-use-before-define": "warn",
    "no-useless-call": "error",
    "no-useless-computed-key": "error",
    "no-useless-concat": "error",
    "no-useless-constructor": "error",
    "no-useless-rename": "error",
    "no-useless-return": "error",
    "no-var": "error",
    "no-void": "error",
    "no-warning-comments": "error",
    "no-whitespace-before-property": "error",
    "no-with": "error",
    "nonblock-statement-body-position": "error",
    "object-curly-newline": "off",
    "object-curly-spacing": "error",
    "object-property-newline": "error",
    "object-shorthand": "off",
    "one-var": "off",
    "one-var-declaration-per-line": "error",
    "operator-assignment": "error",
    "operator-linebreak": "error",
    "padded-blocks": "off",
    "padding-line-between-statements": "off",
    "prefer-arrow-callback": "off",
    "prefer-const": "off",
    "prefer-numeric-literals": "error",
    "prefer-promise-reject-errors": "error",
    "prefer-reflect": "error",
    "prefer-rest-params": "error",
    "prefer-spread": "error",
    "prefer-template": "off",
    "quote-props": "off",
    "quotes": [
      "error",
      "single"
    ],
    "radix": "off",
    "require-await": "off",
    "require-jsdoc": "off",
    "rest-spread-spacing": "error",
    "semi": "off",
    "semi-spacing": [
      "error",
      {
        "after": false,
        "before": false
      }
    ],
    "semi-style": "off",
    "sort-imports": "error",
    "sort-keys": "off",
    "sort-vars": "error",
    "space-before-blocks": "error",
    "space-before-function-paren": "off",
    "space-in-parens": [
      "error",
      "never"
    ],
    "space-infix-ops": "error",
    "space-unary-ops": "error",
    "spaced-comment": [
      "error",
      "never"
    ],
    "strict": "error",
    "switch-colon-spacing": "off",
    "symbol-description": "error",
    "template-curly-spacing": [
      "error",
      "never"
    ],
    "template-tag-spacing": [
      "error",
      "always"
    ],
    "unicode-bom": [
      "error",
      "never"
    ],
    "unexpected-token": "off",
    "valid-jsdoc": "error",
    "vars-on-top": "error",
    "wrap-iife": "error",
    "wrap-regex": "error",
    "yield-star-spacing": "error",
    "yoda": [
      "error",
      "never"
    ]
  }
};
```

**What did you do? Please include the actual source code causing the issue.**

```js
const commando = require('discord.js-commando');
```

**What did you expect to happen?**
I mean, nothing? This should just be your average, every day, run of the mill, commonJS require.

**What actually happened? Please include the actual, raw output from ESLint.**
Definition for rule 'for-direction' was not found (for-direction)

Thanks again, sorry if I'm getting a little annoying.

**Comment by Aladdin-ADD** [comment] 2017-07-03 18:09
I haven't been able to reproduce. 
however, since the rule for-direction was introduced in eslint@4.0.0-beta.0. so I guess your eslint version may not be v4.1.1, could you check it?

**Comment by Aladdin-ADD** [comment] 2017-07-03 18:12
global installed:
```bash
$ eslint -v
```
local installed:
```bash
$ ./node_modules/.bin/eslint -v
```

**Comment by TJDoesCode** [comment] 2017-07-03 18:18
Because I installed it globally, only `eslint -v` works, and it is indeed v4.1.1.

**Comment by Aladdin-ADD** [comment] 2017-07-03 18:27
how did you get the error?
```bash
$ eslint ${filename}
```
did this works?

**Comment by platinumazure** [comment] 2017-07-03 18:58
Are you using an editor integration or running from the command line?

If you're using an editor integration, it is possible it has its own version of ESLint which is below `4.x`, so the new rules can't be found by the editor integration.

From what I can see, the command line should work if `eslint -v` does indeed resolve to 4.1.1.

In future, please be more clear about how you're running ESLint (whether by command line, NPM script, or editor integration) so we know what questions to ask. :smile:

**Comment by TJDoesCode** [comment] 2017-07-03 19:19
@platinumazure Yeah, that was the problem. I'm using the atom `linter-eslint` package and that is causing the error. Running it from the command line works just fine. Thanks for the help.

**Comment by kaicataldo** [comment] 2017-07-05 01:25
Closing this issue as it looks like the question has been answered. Please feel free to visit us in the [ESLint Gitter](https://gitter.im/eslint/eslint) if you have any other issues!

**Closed by kaicataldo** 2017-07-05 01:25 UTC
Labels: triage
