### ISSUE TITLE
eslint --init: arrow keys not working on git bash

### ISSUE THREAD

**Issue by karlpatrickespiritu** [eslint/eslint#7694] opened 2016-12-04 12:48 UTC
I don't know if this is an eslint specific issue but arrow keys when selecting a setup doesn't seem to work on Git Bash. But when I tried it on ConEmu, it works.

![image](https://cloud.githubusercontent.com/assets/10472504/20866216/b601d824-ba62-11e6-97b0-d06a143c7231.png)

**Tell us about your environment**

* **ESLint Version: 3.11.1**
* **Node Version: 6.6.0**
* **npm Version: 4.0.3**

```
"devDependencies": {
  "eslint": "^3.11.1",
  "nodemon": "^1.11.0"
}
```

**Comment by platinumazure** [comment] 2016-12-04 15:27
Possible workaround: Use number key then Enter to select your choice.

**Comment by not-an-aardvark** [comment] 2016-12-05 06:47
ESLint uses [Inquirer.js](https://github.com/SBoudrias/Inquirer.js) for the `--init` prompts. If there is a bug with arrow keys in a particular terminal, I'm guessing it's due to an issue with Inquirer and not with ESLint itself.

**Comment by davidb555** [comment] 2016-12-05 22:39
I am having the same problem. Have you figured it out yet?

**Comment by not-an-aardvark** [comment] 2016-12-05 22:48
It looks like this is very similar to https://github.com/SBoudrias/Inquirer.js/issues/266

...which was caused by https://github.com/nodejs/node/issues/5384

...which was supposedly fixed in Node 6.2.0, so I'm not completely sure why it's appearing in Node 6.6.0.

**Comment by davidb555** [comment] 2016-12-05 23:20
It seems like the arrow keys do work, but you can't see it.  However, the space bar does not. I am running eslint --init. I cannot select Node for where the code will run in  the fourth question because it requires the use of the space bar to change the default selection. Sorry if this is a noob question, but can I reconfigure the .eslint.js file to run code in node rather than browser? Cheers

**Comment by alberto** [comment] 2017-02-18 12:18
Maybe related to https://github.com/nodejs/node/issues/5620 ?

Closing since it doesn't seem like an eslint issue.

**Closed by alberto** 2017-02-18 12:18 UTC
Labels: blocked, bug, core, evaluating

**Comment by Mytee306** [comment] 2018-01-21 20:31
I've worked around the issue by deleting the options I don't want to pick and pressing enter.
For examle:
> Tabs
   Spaces (delete whole line and press enter)
