### ISSUE TITLE
A `key-spacing` schema inconsistency?

### ISSUE THREAD

**Issue by icylace** [eslint/eslint#9082] opened 2017-08-07 00:14 UTC
**Environment Details**

* **ESLint Version:** 4.4.0
* **Node Version:** 8.2.1
* **npm Version:** I use yarn 0.27.5.
* **What parser (default, Babel-ESLint, etc.) are you using?**: babel-eslint

----

**A Potential Issue...?**

The documentation for `key-spacing` [says](http://eslint.org/docs/rules/key-spacing#options) that the `singleLine` and `multiLine` options can't be used with the top-level options.  If this is the case then shouldn't the [first `anyOf` of its schema](https://github.com/eslint/eslint/blob/b3e4598bb44388a727afeb1cc0bff1ac9788d612/lib/rules/key-spacing.js#L140) instead be `oneOf`?

**UPDATE:**

Found another closely related issue within the `key-spacing` schema:

The [documentation](http://eslint.org/docs/rules/key-spacing#options) for `align` [says](http://eslint.org/docs/rules/key-spacing#align-1) that `align` can be defined as either a string or an object but not both.  So, wouldn't that mean that the schema for `align` should use `oneOf` in place `anyOf` over [here](https://github.com/eslint/eslint/blob/b3e4598bb44388a727afeb1cc0bff1ac9788d612/lib/rules/key-spacing.js#L145) and over [there](https://github.com/eslint/eslint/blob/b3e4598bb44388a727afeb1cc0bff1ac9788d612/lib/rules/key-spacing.js#L203)?

**Comment by not-an-aardvark** [comment] 2017-08-07 06:31
Hi, thanks for the issue.

> The documentation for `key-spacing` [says](http://eslint.org/docs/rules/key-spacing#options) that the `singleLine` and `multiLine` options can't be used with the top-level options.  If this is the case then shouldn't the [first `anyOf` of its schema](https://github.com/eslint/eslint/blob/b3e4598bb44388a727afeb1cc0bff1ac9788d612/lib/rules/key-spacing.js#L140) instead be `oneOf`?

No, I think this is correct as-is. The difference between `anyOf` and `oneOf` is that if an object matches multiple schemas in the list, it will pass with `anyOf` but it will fail with `oneOf`. There are some objects that match both of the schemas in this list (for example, an empty object), so I think `anyOf` is appropriate here.

Note that an object containing both `beforeColon` and `singleLine` (e.g.) would match neither schema. This is because the `beforeColon` property would make the object incompatible with the second schema, and the `singleLine` property would make the object incompatible with the first schema. So an object like that would be invalid, in accordance with what the documentation says.

> The [documentation](http://eslint.org/docs/rules/key-spacing#options) for `align` [says](http://eslint.org/docs/rules/key-spacing#align-1) that `align` can be defined as either a string or an object but not both.  So, wouldn't that mean that the schema for `align` should use `oneOf` in place `anyOf` over [here](https://github.com/eslint/eslint/blob/b3e4598bb44388a727afeb1cc0bff1ac9788d612/lib/rules/key-spacing.js#L145) and over [there](https://github.com/eslint/eslint/blob/b3e4598bb44388a727afeb1cc0bff1ac9788d612/lib/rules/key-spacing.js#L203)?

In this case, the two schemas in the array are mutually exclusive (one of them only matches strings, and one of them only matches objects), so I think `anyOf` and `oneOf` would behave identically.

**Comment by icylace** [comment] 2017-08-08 00:15
Thanks for the response and before I respond I should say I'm someone who's currently creating an ESLint-related developer tool that will be open-sourced.  So, subtle nuances in how JSON Schema is used within ESLint affect how I'm implementing my project.

That said, there are some things to consider.

> There are some objects that match both of the schemas in this list (for example, an empty object), so I think `anyOf` is appropriate here.

Yes, but wouldn't an empty object still validate if `oneOf` was used instead?

I can see a potential argument that the following justifies the use of `anyOf`:

```json
{
  "singleLine": {
    "beforeColon": false
  }
}
```

But even then wouldn't `oneOf` handle it?  I don't see a convincing case to show that the top-level `anyOf` can't be replaced by `oneOf` and I still think the wording of the `key-spacing` documentation favors using `oneOf`.

I looked at some other rules for potential guidance and started noticing that `anyOf` and `oneOf` seem surprisingly interchangeable in the way that they're used.  For example, [the `oneOf` in `no-param-reassign`](https://github.com/eslint/eslint/blob/ddc6350a932a8dfb8a6d6fff8a652c15d295f158/lib/rules/no-param-reassign.js#L23) could technically be replaced by `anyOf`.

The more I looked into this the more I wanted to find discussion about when to use `anyOf` instead of `oneOf` when the choice seems ambiguous.  The JSON Schema spec didn't go into useful [detail](http://json-schema.org/latest/json-schema-validation.html#rfc.section.6.27) about it.  I looked at [Foundations of JSON Schema](http://jreutter.sitios.ing.uc.cl/www16.pdf) which mentions `anyOf` but not `oneOf`, unfortunately.  I looked a bit on StackOverflow and didn't find anything relevant.  I didn't look too deeply, so it's possible I missed a good answer there.

My current reasoning is that if there's an `anyOf` containing subschemas configured in such a way that makes the `anyOf` behave like a `oneOf`, then `oneOf` should be used instead for sake of clarity.  I'll elaborate on this next.

> In this case, the two schemas in the array are mutually exclusive (one of them only matches strings, and one of them only matches objects), so I think `anyOf` and `oneOf` would behave identically.

That may be true, but using `anyOf` like this feels messy because it relies on type discrepancies for it to behave like `oneOf`.  If `oneOf` was used instead not only would the type discrepancies be unnecessary but the intent of the schema would be better expressed.

Another thing to consider is consistency with the other rule definitions.  Consider that the `key-spacing` schema's definition for the `align` property uses an `anyOf` with two subschemas where one is an enum and the other is an object type.  In almost every other rule I've checked, when there are two subschemas where one is an enum and the other is an object type, `oneOf` is the parent schema that's used, not `anyOf`.  [`array-element-newline`](https://github.com/eslint/eslint/blob/7ebd9d6f34b26cd16b478adc8ac7fb2d2c515b11/lib/rules/array-element-newline.js#L24), [`no-unused-vars`](https://github.com/eslint/eslint/blob/9f540fd284dc45c48e5bc0792be34c08b7a41885/lib/rules/no-unused-vars.js#L29), and [`space-before-blocks`](https://github.com/eslint/eslint/blob/c67632259783c9630831bce5f272eb6160ee086c/lib/rules/space-before-blocks.js#L26) are just a few examples and there are many more.

The only exception I could find was [`quotes`](https://github.com/eslint/eslint/blob/cd9b774b4893f9dc53c1e9e9158fbb0d67e93ef5/lib/rules/quotes.js#L92).  I would say that `quotes` should use `oneOf` and `key-spacing` should use `oneOf` (at least in both places where the `align` property is defined) for them to be more consistent with the other rules.

**Comment by not-an-aardvark** [comment] 2017-08-08 01:18
> Yes, but wouldn't an empty object still validate if `oneOf` was used instead?

No. An empty object would match both schemas, and `oneOf` requires exactly one schema to match. So an empty object would fail validation if `oneOf` was used.

> I still think the wording of the `key-spacing` documentation favors using `oneOf`.

The `key-spacing` documentation specifies a set of objects that are allowed, and a set of objects that are disallowed. As long as the rule accepts allowed objects and rejects disallowed objects, the structure of the schema is an implementation detail, so the wording of the documentation is irrelevant. (That said, in this case I still think `oneOf` is more semantically correct, because the rule is intended to allow the intersection of the two schema types.)

>> In this case, the two schemas in the array are mutually exclusive (one of them only matches strings, and one of them only matches objects), so I think `anyOf` and `oneOf` would behave identically.
>
>That may be true, but using `anyOf` like this feels messy because it relies on type discrepancies for it to behave like `oneOf`.  If `oneOf` was used instead not only would the type discrepancies be unnecessary but the intent of the schema would be better expressed.

I don't have a strong opinion on this. To me, it doesn't seem useful to speculate about the "intent of the schema" regarding the intersection of two subschemas when that intersection doesn't actually exist. 

> Another thing to consider is consistency with the other rule definitions.

Correctness is the primary concern here; we should decide what objects we want to allow, and then build the schemas to match that specification. In some cases `oneOf` is more appropriate, and in other cases `anyOf` is more appropriate.

In cases where `anyOf` and `oneOf` are equivalent (i.e. when schemas are mutually exclusive), then I wouldn't mind being consistent across the codebase. But this is an implementation detail, so I'm confused about how this affects the developer tool that you're making.

**Comment by icylace** [comment] 2017-08-08 04:07
> No. An empty object would match both schemas, and `oneOf` requires exactly one schema to match. So an empty object would fail validation if `oneOf` was used.

Ah, yes.  I stand corrected.

> That said, in this case I still think `anyOf` is more semantically correct, because the rule is intended to allow the intersection of the two schema types.

That's debatable because another way of looking at it is the rule is intended to allow only certain groupings of options.  The fact that some groupings appear partially similar to others is a superficial convenience.

> I don't have a strong opinion on this. To me, it doesn't seem useful to speculate about the "intent of the schema" regarding the intersection of two subschemas when that intersection doesn't actually exist.

The `align` property schema is an "either-or" type of schema.  A valid JSON instance can define `align` as either a string from a set of choices or an object with certain keys but it can't be both.  `oneOf` was designed for this type of schema.  `anyOf` can technically work here but it's meant for other things.

A set of checkboxes can be setup to act like a set of radio buttons but, unless there's a good reason, radio buttons should really be used.

> In cases where anyOf and oneOf are equivalent (i.e. when schemas are mutually exclusive), then I wouldn't mind being consistent across the codebase. But again, this is an implementation detail, so I'm confused about how this affects the developer tool that you're making.

I'm making an ESLint configuration wizard web app where each rule along with their particular options are represented and managed through simple widgets.  Since there are well over 200 ESLint rules, automating the creation of these widgets is a natural approach.

The JSON Schema for each rule serves as a useful starting point because it defines almost everything I need to know about a rule.  As I understand it, JSON Schema was designed for validation and not UI rendering.  As such, I've been working on a build process that converts the schema for each rule into a custom format that is more suitable for my type of UI rendering.  I know there are webform generators that convert from JSON Schema but I don't believe any of them are a fit for my project.

Currently, it appears I'll have to gather the default values for each rule manually since they're not encoded in a unified way anywhere, at least as far as I know.  But I digress.

One of my earlier naïve ideas was to represent all `oneOf` options as radio buttons and all `anyOf` options as checkboxes because the JSON Schema spec seemed pretty straightforward as to what each was meant for.  This "1-to-1" mentality has some shortcomings not just from what was discussed in this thread but also in some "structural" cases.

As a quick example of the latter, the schema for [`func-call-spacing` uses `anyOf`](https://github.com/eslint/eslint/blob/acc33015785f3f38384dba3ee823556e987f21c0/lib/rules/func-call-spacing.js#L28) but upon further inspection of what's actually going on with the rule, and checking its documentation, I'm able to develop a conversion process that optimizes away the `anyOf` from this rule and any other rule that is structurally similar.  So, in terms of my custom format we end up with:

```json
[
  {
    "control": "select",
    "choices": ["never", "always"]
  },
  {
    "availability": ["always"],
    "control": "checkbox",
    "label": "allowNewlines"
  }
]
```

**Comment by icylace** [comment] 2017-09-11 14:33
I should also say that while it's true that rule schemas are implementation details, those details are still exposed by ESLint's API through [`Linter#getRules`](https://eslint.org/docs/developer-guide/nodejs-api#lintergetrules).  So, for that reason I think it's beneficial to be able to discuss if improvements could be made to the schemas.

**Comment by not-an-aardvark** [comment] 2017-10-24 08:38
Closing because this is working as intended and there doesn't seem to be much interest from the rest of the team in changing the schemas.

**Closed by not-an-aardvark** 2017-10-24 08:38 UTC
Labels: works as intended
