### ISSUE TITLE
Getting import errors when my import/resolver node extensions are extending from multiple configs

### ISSUE THREAD

**Issue by U-4-E-A** [eslint/eslint#16730] opened 2022-12-31 21:06 UTC
### Environment

Node version: 18.12.0
npm version: 8.1.2
Local ESLint version: "not found" (in node_modules, 8.31.0)
Global ESLint version: not found
Operating System: win32 10.0.19044

If I have all the imports in the main config this like, I don't get any errors: -

```
settings: {
'import/resolver': {
node: {
extensions: ['.js', '.ts', '.tsx']
      }
    }
  }
```

### What parser are you using?

Default (Espree)

### What did you do?

I have a main eslint config package then separate packages for react, TS, next prettier etc.

### What did you expect to happen?

Amalgamation of rules to support all stated file extensions.

### What actually happened?

However, if I spit them up and do multiple extensions, I get an error: -

```
settings: {
'import/resolver': {
node: {
extensions: ['.js']
      }
    }
  }
```

```
settings: {
'import/resolver': {
node: {
extensions: ['.ts', '.tsx']
      }
    }
  }
```

Error message: -

```
Missing file extension for "./blah " eslint(import/extensions)
Unable to resolve path to module './blah ' eslint(import/no-unresolved)
```

I've tested other aspects of the config and it is working correctly, so the extension is valid, no errors. It just seems I cannot merge settings>import/resolver>node>extensions?

Any ideas? Thanks.

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by mdjermanovic** [comment] 2023-01-01 22:13
Hi @U-4-E-A, thanks for the issue!

This works as intended. Merging of `settings` is a generic deep-merging, and by design arrays are not being concatenated. In the current config system, arrays are merged as tuples, so `extensions` after merging will be either `['.ts', '.tsx']` or `['.js', '.tsx']`, depending on the order of config entries. In the [new config system](https://eslint.org/docs/latest/user-guide/configuring/configuration-files-new), arrays overwrite previous values without merging items, so `extensions` after merging will be either `['.ts', '.tsx']` or `['.js']`. Either way, merging will not produce `['.js', '.ts', '.tsx']` or `['.ts', '.tsx', '.js']`. If you need the union of all extensions as the final results, you'll have to specify `extensions: ['.js', '.ts', '.tsx']` in the main config.

**Closed by mdjermanovic** 2023-01-01 22:13 UTC
Labels: works as intended
