### ISSUE TITLE
Crash when attempting to lint a broken symlink

### ISSUE THREAD

**Issue by steabert** [eslint/eslint#10039] opened 2018-03-01 19:17 UTC
**Tell us about your environment**

* **ESLint Version:** 4.18.1
* **Node Version:** 9.5.0
* **yarn Version:** 1.3.2

**What parser (default, Babel-ESLint, etc.) are you using?** default

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
module.exports = {
    "env": {
        "browser": true
    },
    "extends": "eslint:recommended",
    "rules": {
        "indent": [
            "error",
            "tab"
        ],
        "linebreak-style": [
            "error",
            "unix"
        ],
        "quotes": [
            "error",
            "double"
        ],
        "semi": [
            "error",
            "always"
        ]
    }
}
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

To test the issue I had in my own project, I created a new empty directory, and ran:

```
yarn add --dev eslint
yarn eslint --init
ln -s test.js nonExistent.js
```

```bash
yarn eslint --cache .
```

**What did you expect to happen?**

An error message telling me about a broken link or missing file.
I was expecting something similar to when I run eslint without the `--cache` option, then I get:
```
ENOENT: no such file or directory, open '/home/stevenv/test/nonExistent.js'
Error: ENOENT: no such file or directory, open '/home/stevenv/test/nonExistent.js'
    at Object.fs.openSync (fs.js:663:18)
    at Object.fs.readFileSync (fs.js:568:33)
    at processFile (/home/stevenv/test/node_modules/eslint/lib/cli-engine.js:222:21)
    at fileList.map.fileInfo (/home/stevenv/test/node_modules/eslint/lib/cli-engine.js:549:20)
    at Array.map (<anonymous>)
    at CLIEngine.executeOnFiles (/home/stevenv/test/node_modules/eslint/lib/cli-engine.js:518:34)
    at Object.execute (/home/stevenv/test/node_modules/eslint/lib/cli.js:189:111)
    at Object.<anonymous> (/home/stevenv/test/node_modules/eslint/bin/eslint.js:74:28)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
error Command failed with exit code 1.
```

**What actually happened? Please include the actual, raw output from ESLint.**

```
Cannot read property 'hashOfConfig' of undefined
TypeError: Cannot read property 'hashOfConfig' of undefined
    at fileList.map.fileInfo (/home/stevenv/test/node_modules/eslint/lib/cli-engine.js:532:71)
    at Array.map (<anonymous>)
    at CLIEngine.executeOnFiles (/home/stevenv/test/node_modules/eslint/lib/cli-engine.js:518:34)
    at Object.execute (/home/stevenv/test/node_modules/eslint/lib/cli.js:189:111)
    at Object.<anonymous> (/home/stevenv/test/node_modules/eslint/bin/eslint.js:74:28)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
error Command failed with exit code 1.
```

**Comment by not-an-aardvark** [comment] 2018-03-01 23:38
Thanks for the report. It seems like the issue is that we don't handle broken symlinks gracefully -- I would expect them to be handled the same way as nonexistent files.

**Comment by steabert** [comment] 2018-03-04 13:51
I made a work-around for myself, I'll make a pull request of it. I'm not sure it's the most appropriate solution though, as I'm not familiar with the code base or if it's a good idea to just silently ignore non-existing files.

**Comment by not-an-aardvark** [comment] 2018-11-14 17:50
Closing in accordance with https://github.com/eslint/eslint/pull/10056#issuecomment-438755141.

**Closed by not-an-aardvark** 2018-11-14 17:50 UTC
Labels: accepted, bug, core, help wanted
