### ISSUE TITLE
Browserified eslint crashes due to multiple instances of babel-polyfill

### ISSUE THREAD

**Issue by nirsofferg** [eslint/eslint#8818] opened 2017-06-27 10:56 UTC
**Tell us about your environment**

ESLint Version:
v4.0.0
Node Version:
v6.10.3
npm Version:
v3.10.10

**What parser (default, Babel-ESLint, etc.) are you using?**
default

Hi, I've integrated eslint in a project i'm working on.
the eslint code was browserfied using the npm browesrify script included in the eslint source code.
when running the project I get the error from eslint saying:
"Only one instance of babel-polyfill is allowed" cause by the following line in the eslint.js:

`if (global._babelPolyfill) {
  throw new Error("only one instance of babel-polyfill is allowed");
}`

In the node version the babel-polyfill is only a devDependency, why is it included in the output of the browserify script?

Thanks

**Comment by platinumazure** [comment] 2017-06-27 13:28
I don't believe we really officially support a browserified ESLint (even though we do use browserify to generate it for our online demo), so I'm not sure if this would be a priority for investigation. Nonetheless, thanks for reporting the issue. Hopefully the team members who understand this part of our infrastructure will be able to take a look.

**Comment by not-an-aardvark** [comment] 2017-06-28 07:56
Our internal browserify script is only intended to be used for the online demo, not for general use by other tools. We use babelify on our browserify script because it allows us to support older browsers in the demo, so if you're also using babel-polyfill in another place, there's not really any way we would be able to prevent this error.

As a workaround you could remove `babel-polyfill` from your app, or do something hacky like `delete global._babelPolyfill`

If we end up accepting https://github.com/eslint/eslint/issues/8348, then it should be possible to use `eslint.Linter` with browserify directly.

**Comment by not-an-aardvark** [comment] 2017-07-11 02:26
Closing because this is working as intended.

**Closed by not-an-aardvark** 2017-07-11 02:26 UTC
Labels: works as intended
