### ISSUE TITLE
Release on October 14, 2016

### ISSUE THREAD

**Issue by nzakas** [eslint/eslint#7276] opened 2016-09-29 20:51 UTC
The scheduled release on Friday, October 14, 2016 is assigned to:

* @btmills
* @mysticatea

Please use this issue to document how the release went, any problems during the release, and anything the team might want to know about the release process. This issue should be closed after all patch releases have been completed (or there was no patch release needed).

**Comment by kaicataldo** [comment] 2016-10-17 22:35
@btmills @mysticatea It looks like we're all set to start merging PRs as usual, but can you confirm here?

**Comment by platinumazure** [comment] 2016-10-17 23:01
@mysticatea @btmills Don't forget to throw in a quick retrospective when you get a chance! :smile:

**Comment by btmills** [comment] 2016-10-18 02:04
Yep, go ahead and merge semver-minor PRs when they're ready!

As for a retrospective, @mysticatea may have a different perspective than I since he's the one who actually ran the release, but I it went smoothly from my perspective. We held off on merging a few enhancement PRs (I remember @not-an-aardvark had a few specifically) on Friday right before the release even though they were approved and past the waiting period. Obviously I would like to get PRs in sooner rather than later, but I think limiting the scope of PRs merged right before a release is the right call. Does anyone have a different opinion on that?

**Comment by not-an-aardvark** [comment] 2016-10-18 05:14
I agree that not merging those PRs was probably the right call.

**Comment by mysticatea** [comment] 2016-10-18 09:23
It seems no regression report after 3.8.1.

- I thank you for supports and adding descriptions.
- I felt the automation of the release system is much good. 
- I was planning that I review some PRs on the early morning, but I overslept.

**Closed by mysticatea** 2016-10-18 09:23 UTC
Labels: accepted, release

**Comment by nzakas** [comment] 2016-10-18 17:14
When in doubt, don't merge. The worst that can happen is that we wait another two weeks to land whatever it is. 👍
