### ISSUE TITLE
ESLint 6.6.0 does not account for module-hoisting via yarn workspaces when determining path for plugins

### ISSUE THREAD

**Issue by Slapbox** [eslint/eslint#12508] opened 2019-10-29 20:57 UTC
**Tell us about your environment**

Node version: v12.10.0
npm version: v6.2.0
Local ESLint version: Not found -- But it is installed (rolled back to 6.5.1 and it's working fine)
Global ESLint version: v6.5.1 (Currently used)

**What did you expect to happen?**
Upgrading from 6.5.1 to should not break linting (specifically seeing this in Sublime Text)

I get an error for the first plugin, no matter what plugin that is. The message I get is like this:

```
Error: Failed to load plugin 'react' declared in '.eslintrc': ENOENT: no such file or directory, open 'C:\projects\myProject\node_modules\eslint-plugin-react\node_modules\doctrine\lib\doctrine.js'
```

But we're using `yarn workspaces` and `lerna` and the proper location of that file in our environment after upgrading to `6.6.0` is: `C:\projects\myProject\node_modules\doctrine\lib\doctrine.js`

**What actually happened? Please include the actual, raw output from ESLint.**

See error text above.

**Are you willing to submit a pull request to fix this bug?**
Can't help with resolution.

**Comment by kaicataldo** [comment] 2019-10-29 23:11
This looks like it's being caused by the changes to [how ESLint loads shareable configs and plugins](https://eslint.org/docs/user-guide/migrating-to-6.0.0#package-loading-simplification), however, that was released in v6.0.0. Can you share the config file you're using? I don't have a lot of experience with `yarn workspaces` or `lerna`, but maybe someone else who is more familiar can chime in.

**Comment by Slapbox** [comment] 2019-10-30 20:10
Hey @kaicataldo thanks for your response. That sounds like exactly what I'm seeing, only as you mentioned it was implemented in `6.0.0` and also says it was implemented specifically to fix these sorts of issues.

[Here's a gist with my `.eslintrc` config](https://gist.github.com/Slapbox/8c5dd361d7447a70af51723bbe051f13), but I can't imagine that anything in there is directly related.

Just to re-confirm, `6.5.1` works perfectly for me.

**Comment by kaicataldo** [comment] 2019-11-01 21:31
Thanks for the info. I'm not seeing anything that stands out to me, and that's really odd that you're noticing this behavior only in `6.6.0` on. One more possible thing to try: if you have a lockfile, can you try deleting and regenerating it to see if that fixes it?

**Comment by DimaSerhin** [comment] 2019-11-12 02:58
@kaicataldo experiencing the same issue with similar setup: `lerna` and `yarn workspaces`.
I have config deeply nested in project tree which is different from one found at the `.` of project folder.
This config extends config module whose peerDependencies are present in `./node_modules`. When i run `./node_modules/bin/eslint` nested config is used but eslint cannot find any dependencies at the root level `./node_modules`.

Issue is reproduced only with`6.6.0`. Locking version back to `6.5.1` resolves the problem.
Suggested deletion of lockfile and regenerating doesn't help.

**Comment by kaicataldo** [comment] 2019-11-13 06:56
Is there any chance either of you could make a minimal reproduction GitHub repository?

**Comment by Slapbox** [comment] 2019-11-30 20:55
Unfortunately I'll never find the time to make a repro. I can describe the issue to help resolve, but until it's resolved I'll just have to stay on `6.5.1`

Upgrading `Sublime Linter` and the associated Sublime addons didn't help, despite it referencing compatibility with `yarn`, `lerna`, and `eslint6.6` being features of the newest version.

**Comment by kaicataldo** [comment] 2019-11-30 21:55
It's a bit of a wild goose chase at the moment. Sounds like it might be beneficial to file an issue with the Sublime plugin you're using - they might be able to chase this down!

**Comment by fraywing** [comment] 2019-12-02 18:38
I have this same issue after upgrading, but I'm not using Sublime. I don't think this is an issue with an external plugin. I'm having it while using yarn workspaces and Atom.

**Comment by fraywing** [comment] 2019-12-02 18:39
Downgrading stopped the issue, but broke a nested Gatsby app that is in a workspace.

**Comment by Slapbox** [comment] 2019-12-02 20:33
@kaicataldo I understand this might not be resolvable with the currently known information. That said, I feel reasonably, but not entirely, confident that the issue is in ESLint itself.

**Comment by kaicataldo** [comment] 2019-12-04 23:30
Does the most recent patch release fix the issue for folks who are encountering it? It includes the fix for [this issue](https://github.com/eslint/eslint/issues/12604).

**Closed** 2020-01-04 22:43 UTC
Labels: bug, core, evaluating

**Comment by Slapbox** [comment] 2020-06-28 19:05
@kaicataldo, the issue persists with `ESLint@7.3.1`

**Comment by Slapbox** [comment] 2020-06-28 19:17
If I copy the `doctrine` folder from my `node_modules` into the ESLint's `node_modules` folder, I get past that issue, but just meet with another of the same kind:

> SublimeLinter: ERROR: JSON Decode error: We expected JSON from 'eslint', but instead got this:
Error: Failed to load plugin 'compat' declared in '.eslintrc': ENOENT: no such file or directory, open 'C:\projects\myProject\node_modules\eslint-plugin-compat\node_modules\semver\semver.js'

According to SublimeLinter, this failure originates with ESLint. It looks for `node_modules` as child directories of the ESLint and its plugins, rather than in the root level `node_modules`.

If I was running via CLI, I suspect [this comment](https://github.com/eslint/eslint/issues/12604#issuecomment-559801195) about prefixing with `pwd` would resolve my issue, but I'm not running via CLI.

Any thoughts? I feel like I'm trapped in the past.
