### ISSUE TITLE
`no-useless-escape` rule too strict for conditionals in Angular html templates

### ISSUE THREAD

**Issue by marcinowski** [eslint/eslint#14066] opened 2021-02-04 12:44 UTC
**Tell us about your environment**

```
$ ./node_modules/.bin/eslint --env-info
Environment Info:

Node version: v12.16.0
npm version: v6.13.4
Local ESLint version: v7.17.0 (Currently used)
Global ESLint version: Not found
```

**What parser (default, `@babel/eslint-parser`, `@typescript-eslint/parser`, etc.) are you using?**
```
    "@angular-eslint/eslint-plugin": "1.0.0",
    "@angular-eslint/eslint-plugin-template": "1.0.0",
    "@angular-eslint/template-parser": "1.0.0",
    "@typescript-eslint/eslint-plugin": "^4.10.0",
    "@typescript-eslint/experimental-utils": "^4.10.0",
    "@typescript-eslint/parser": "^4.10.0",
    "eslint": "~7.17.0",
    "eslint-config-airbnb-base": "~14.2.1",
    "eslint-config-prettier": "^7.1.0",
    "eslint-import-resolver-typescript": "^2.3.0",
    "eslint-plugin-deprecation": "^1.2.0",
    "eslint-plugin-functional": "^3.2.1",
    "eslint-plugin-import": "~2.22.1",
    "eslint-plugin-jasmine": "~4.1.1",
    "eslint-plugin-local-rules": "^1.0.1",
    "eslint-plugin-piggyback": "~2.0.0",
    "eslint-plugin-prettier": "^3.3.1",
    "eslint-plugin-rxjs": "^2.1.6",
```

**Please show your full configuration:**
Can be reproduced with this [eslint demo](https://eslint.org/demo#eyJ0ZXh0IjoiY29uc3QgdGVtcGxhdGUgPSBgXG5cdDxjb21wb25lbnRcblx0XHRbaW5wdXRdPVwidHJ1ZSA/ICd0ZXN0IGZvciBcXCdAXFwnIGVzY2FwaW5nJyA6ICdmYWxzZSdcIlxuXHQ+PC9jb21wb25lbnQ+XG5gOyIsIm9wdGlvbnMiOnsicGFyc2VyT3B0aW9ucyI6eyJlY21hVmVyc2lvbiI6OSwic291cmNlVHlwZSI6InNjcmlwdCIsImVjbWFGZWF0dXJlcyI6eyJqc3giOnRydWV9fSwicnVsZXMiOnsiY29uc3RydWN0b3Itc3VwZXIiOjIsImZvci1kaXJlY3Rpb24iOjIsImdldHRlci1yZXR1cm4iOjIsIm5vLWFzeW5jLXByb21pc2UtZXhlY3V0b3IiOjIsIm5vLWNhc2UtZGVjbGFyYXRpb25zIjoyLCJuby1jbGFzcy1hc3NpZ24iOjIsIm5vLWNvbXBhcmUtbmVnLXplcm8iOjIsIm5vLWNvbmQtYXNzaWduIjoyLCJuby1jb25zdC1hc3NpZ24iOjIsIm5vLWNvbnN0YW50LWNvbmRpdGlvbiI6Miwibm8tY29udHJvbC1yZWdleCI6Miwibm8tZGVidWdnZXIiOjIsIm5vLWRlbGV0ZS12YXIiOjIsIm5vLWR1cGUtYXJncyI6Miwibm8tZHVwZS1jbGFzcy1tZW1iZXJzIjoyLCJuby1kdXBlLWVsc2UtaWYiOjIsIm5vLWR1cGUta2V5cyI6Miwibm8tZHVwbGljYXRlLWNhc2UiOjIsIm5vLWVtcHR5IjoyLCJuby1lbXB0eS1jaGFyYWN0ZXItY2xhc3MiOjIsIm5vLWVtcHR5LXBhdHRlcm4iOjIsIm5vLWV4LWFzc2lnbiI6Miwibm8tZXh0cmEtYm9vbGVhbi1jYXN0IjoyLCJuby1leHRyYS1zZW1pIjoyLCJuby1mYWxsdGhyb3VnaCI6Miwibm8tZnVuYy1hc3NpZ24iOjIsIm5vLWdsb2JhbC1hc3NpZ24iOjIsIm5vLWltcG9ydC1hc3NpZ24iOjIsIm5vLWlubmVyLWRlY2xhcmF0aW9ucyI6Miwibm8taW52YWxpZC1yZWdleHAiOjIsIm5vLWlycmVndWxhci13aGl0ZXNwYWNlIjoyLCJuby1taXNsZWFkaW5nLWNoYXJhY3Rlci1jbGFzcyI6Miwibm8tbWl4ZWQtc3BhY2VzLWFuZC10YWJzIjoyLCJuby1uZXctc3ltYm9sIjoyLCJuby1vYmotY2FsbHMiOjIsIm5vLW9jdGFsIjoyLCJuby1wcm90b3R5cGUtYnVpbHRpbnMiOjIsIm5vLXJlZGVjbGFyZSI6Miwibm8tcmVnZXgtc3BhY2VzIjoyLCJuby1zZWxmLWFzc2lnbiI6Miwibm8tc2V0dGVyLXJldHVybiI6Miwibm8tc2hhZG93LXJlc3RyaWN0ZWQtbmFtZXMiOjIsIm5vLXNwYXJzZS1hcnJheXMiOjIsIm5vLXRoaXMtYmVmb3JlLXN1cGVyIjoyLCJuby11bmRlZiI6Miwibm8tdW5leHBlY3RlZC1tdWx0aWxpbmUiOjIsIm5vLXVucmVhY2hhYmxlIjoyLCJuby11bnNhZmUtZmluYWxseSI6Miwibm8tdW5zYWZlLW5lZ2F0aW9uIjoyLCJuby11bnVzZWQtbGFiZWxzIjoyLCJuby11bnVzZWQtdmFycyI6Miwibm8tdXNlbGVzcy1jYXRjaCI6Miwibm8tdXNlbGVzcy1lc2NhcGUiOjIsIm5vLXdpdGgiOjIsInJlcXVpcmUteWllbGQiOjIsInVzZS1pc25hbiI6MiwidmFsaWQtdHlwZW9mIjoyfSwiZW52Ijp7fX19)

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

This is the simplest example that causes the `no-useless-escape` to be unnecessarily triggered. It's from an angular inline template which is a part of a normal component definition. You can see that the expected value from `[prop]` is `test for '@' escaping` however it triggers the `no-useless-escape` rule which in this case I think can't be avoided.

```ts
@Component({
  selector: 'app-component',
  template: ``
	<component
		[prop]="true ? 'test for \'@\' escaping' : 'false'"
	></component>
`)};
```

**What did you expect to happen?**
For the rule not to be triggered

**What actually happened? Please include the actual, raw output from ESLint.**
Can be reproduced with this [eslint demo](https://eslint.org/demo#eyJ0ZXh0IjoiY29uc3QgdGVtcGxhdGUgPSBgXG5cdDxjb21wb25lbnRcblx0XHRbaW5wdXRdPVwidHJ1ZSA/ICd0ZXN0IGZvciBcXCdAXFwnIGVzY2FwaW5nJyA6ICdmYWxzZSdcIlxuXHQ+PC9jb21wb25lbnQ+XG5gOyIsIm9wdGlvbnMiOnsicGFyc2VyT3B0aW9ucyI6eyJlY21hVmVyc2lvbiI6OSwic291cmNlVHlwZSI6InNjcmlwdCIsImVjbWFGZWF0dXJlcyI6eyJqc3giOnRydWV9fSwicnVsZXMiOnsiY29uc3RydWN0b3Itc3VwZXIiOjIsImZvci1kaXJlY3Rpb24iOjIsImdldHRlci1yZXR1cm4iOjIsIm5vLWFzeW5jLXByb21pc2UtZXhlY3V0b3IiOjIsIm5vLWNhc2UtZGVjbGFyYXRpb25zIjoyLCJuby1jbGFzcy1hc3NpZ24iOjIsIm5vLWNvbXBhcmUtbmVnLXplcm8iOjIsIm5vLWNvbmQtYXNzaWduIjoyLCJuby1jb25zdC1hc3NpZ24iOjIsIm5vLWNvbnN0YW50LWNvbmRpdGlvbiI6Miwibm8tY29udHJvbC1yZWdleCI6Miwibm8tZGVidWdnZXIiOjIsIm5vLWRlbGV0ZS12YXIiOjIsIm5vLWR1cGUtYXJncyI6Miwibm8tZHVwZS1jbGFzcy1tZW1iZXJzIjoyLCJuby1kdXBlLWVsc2UtaWYiOjIsIm5vLWR1cGUta2V5cyI6Miwibm8tZHVwbGljYXRlLWNhc2UiOjIsIm5vLWVtcHR5IjoyLCJuby1lbXB0eS1jaGFyYWN0ZXItY2xhc3MiOjIsIm5vLWVtcHR5LXBhdHRlcm4iOjIsIm5vLWV4LWFzc2lnbiI6Miwibm8tZXh0cmEtYm9vbGVhbi1jYXN0IjoyLCJuby1leHRyYS1zZW1pIjoyLCJuby1mYWxsdGhyb3VnaCI6Miwibm8tZnVuYy1hc3NpZ24iOjIsIm5vLWdsb2JhbC1hc3NpZ24iOjIsIm5vLWltcG9ydC1hc3NpZ24iOjIsIm5vLWlubmVyLWRlY2xhcmF0aW9ucyI6Miwibm8taW52YWxpZC1yZWdleHAiOjIsIm5vLWlycmVndWxhci13aGl0ZXNwYWNlIjoyLCJuby1taXNsZWFkaW5nLWNoYXJhY3Rlci1jbGFzcyI6Miwibm8tbWl4ZWQtc3BhY2VzLWFuZC10YWJzIjoyLCJuby1uZXctc3ltYm9sIjoyLCJuby1vYmotY2FsbHMiOjIsIm5vLW9jdGFsIjoyLCJuby1wcm90b3R5cGUtYnVpbHRpbnMiOjIsIm5vLXJlZGVjbGFyZSI6Miwibm8tcmVnZXgtc3BhY2VzIjoyLCJuby1zZWxmLWFzc2lnbiI6Miwibm8tc2V0dGVyLXJldHVybiI6Miwibm8tc2hhZG93LXJlc3RyaWN0ZWQtbmFtZXMiOjIsIm5vLXNwYXJzZS1hcnJheXMiOjIsIm5vLXRoaXMtYmVmb3JlLXN1cGVyIjoyLCJuby11bmRlZiI6Miwibm8tdW5leHBlY3RlZC1tdWx0aWxpbmUiOjIsIm5vLXVucmVhY2hhYmxlIjoyLCJuby11bnNhZmUtZmluYWxseSI6Miwibm8tdW5zYWZlLW5lZ2F0aW9uIjoyLCJuby11bnVzZWQtbGFiZWxzIjoyLCJuby11bnVzZWQtdmFycyI6Miwibm8tdXNlbGVzcy1jYXRjaCI6Miwibm8tdXNlbGVzcy1lc2NhcGUiOjIsIm5vLXdpdGgiOjIsInJlcXVpcmUteWllbGQiOjIsInVzZS1pc25hbiI6MiwidmFsaWQtdHlwZW9mIjoyfSwiZW52Ijp7fX19)
![image](https://user-images.githubusercontent.com/17745246/106894454-ebd44380-66e6-11eb-839b-a11a5d55e6b2.png)

```json
[
  {
    "filePath": "my.component.ts",
    "messages": [
      {
        "ruleId": "prettier/prettier",
        "severity": 2,
        "message": "Replace `\\'@\\` with `'@`",
        "line": 160,
        "column": 71,
        "nodeType": null,
        "endLine": 160,
        "endColumn": 75,
        "fix": {
          "range": [
            5051,
            5055
          ],
          "text": "'@"
        }
      },
      {
        "ruleId": "no-useless-escape",
        "severity": 2,
        "message": "Unnecessary escape character: \\'.",
        "line": 160,
        "column": 71,
        "nodeType": "TemplateElement",
        "messageId": "unnecessaryEscape",
        "endLine": 160,
        "endColumn": 72,
        "suggestions": [
          {
            "messageId": "removeEscape",
            "fix": {
              "range": [
                5051,
                5052
              ],
              "text": ""
            },
            "desc": "Remove the `\\`. This maintains the current functionality."
          },
          {
            "messageId": "escapeBackslash",
            "fix": {
              "range": [
                5051,
                5051
              ],
              "text": "\\"
            },
            "desc": "Replace the `\\` with `\\\\` to include the actual backslash character."
          }
        ]
      },
      {
        "ruleId": "no-useless-escape",
        "severity": 2,
        "message": "Unnecessary escape character: \\'.",
        "line": 160,
        "column": 74,
        "nodeType": "TemplateElement",
        "messageId": "unnecessaryEscape",
        "endLine": 160,
        "endColumn": 75,
        "suggestions": [
          {
            "messageId": "removeEscape",
            "fix": {
              "range": [
                5054,
                5055
              ],
              "text": ""
            },
            "desc": "Remove the `\\`. This maintains the current functionality."
          },
          {
            "messageId": "escapeBackslash",
            "fix": {
              "range": [
                5054,
                5054
              ],
              "text": "\\"
            },
            "desc": "Replace the `\\` with `\\\\` to include the actual backslash character."
          }
        ]
      }
    ],
    "errorCount": 3,
    "warningCount": 0,
    "fixableErrorCount": 1,
    "fixableWarningCount": 0,
  }
]
```

**Are you willing to submit a pull request to fix this bug?**
Potentially

**Comment by mdjermanovic** [comment] 2021-02-04 13:31
Hi @marcinowski, thanks for the issue!

The rule works as intended on the demo example. `template` has the same value with or without the unnecessary escapes:

```js
const template1 = `
	<component
		[input]="true ? 'test for \'@\' escaping' : 'false'"
	></component>
`;

const template2 = `
	<component
		[input]="true ? 'test for '@' escaping' : 'false'"
	></component>
`;

template1 === template2; // true
```

> This is the simplest example that causes the `no-useless-escape` to be unnecessarily triggered. It's from an angular inline template which is a part of a normal component definition. You can see that the expected value from `[prop]` is `test for '@' escaping` however it triggers the `no-useless-escape` rule which in this case I think can't be avoided.
> 
> ```ts
> @Component({
>   selector: 'app-component',
>   template: ``
> 	<component
> 		[prop]="true ? 'test for \'@\' escaping' : 'false'"
> 	></component>
> `)};
> ```

I'm not familiar with angular, but I'd guess the correct code would be `\\'@\\'` instead of `\'@\'`

**Comment by marcinowski** [comment] 2021-02-04 16:05
Hi @mdjermanovic ! Thanks for a quick reply and for your suggestions.
I tried the double escape `\\'@\\'` but then I run into another issue which I found already ticketed in angular-eslint https://github.com/angular-eslint/angular-eslint/issues/207 :sweat_smile: 
Doing the non-escape option `'@'` results in the angular JIT compilation error
```
:7766/vendor.js:66720 ERROR Error: Errors during JIT compilation of template for MyComponent: Parser Error: Unexpected token 'Lexer Error: Unexpected character [@] at column 113 in expression [
      true
        ? 'something'
        : 'Test '@' without escaping'
    ]' at column 114 in [{{
      true
        ? 'something the topic'
        : 'Test '@' without escaping'
    }}] in ng:///MyComponent/template.html@73:29 ("eAccessor
    input="[ERROR ->]{{
      true
        ? 'something'
")
```
so all options seem to fail one way or another :(

**Comment by mdjermanovic** [comment] 2021-02-04 17:12
Thanks for the info! Then, this seems to be a problem with `angular-eslint`, double `\\` looks right. The single `\`, which `no-useless-escape` reports, certainly wouldn't help as it has no effect on the produced string value.

**Comment by marcinowski** [comment] 2021-02-09 11:40
Thanks for you help @mdjermanovic! I'll add a comment to that issue on `angular-eslint`.

**Comment by nzakas** [comment] 2021-02-09 19:36
Resolved, so closing.

**Closed by nzakas** 2021-02-09 19:36 UTC
Labels: works as intended
