### ISSUE TITLE
operator-linebreak rule config does not match documentation

### ISSUE THREAD

**Issue by theetrain** [eslint/eslint#9197] opened 2017-09-01 22:02 UTC
**Tell us about your environment**

* **ESLint Version: 4.5.0**
* **Node Version: 8.2.1**
* **npm Version: 5.3.0**

**What parser (default, Babel-ESLint, etc.) are you using? > eslint**

<details>
<summary>Configuration</summary>

```js
{
  "rules": {
    "operator-linebreak": "after"
  }
}
```

</details>

**What did you do? Please include the actual source code causing the issue.**

```js
const subtract = (a, b) => {
  return a
         - b
}
```

**What did you expect to happen?**
I expected eslint to fix my formatting when running `eslint ./ --fix` and then yield:

```js
const subtract = (a, b) => {
  return a -
         b
}
```

**What actually happened? Please include the actual, raw output from ESLint.**

Eslint outputted:
```bash
$ eslint test.js
~/eslint-config/index.js:
        Configuration for rule "operator-linebreak" is invalid:
        Severity should be one of the following: 0 = off, 1 = warn, 2 = error (you passed '"after"').
```

This is inconsistent with the options documented in https://eslint.org/docs/rules/operator-linebreak

**Comment by not-an-aardvark** [comment] 2017-09-02 22:32
Thanks for the report; however, this is working as intended. All ESLint rules are configured with a *severity* indicating how problems with the rule should affect the exit code. All of the options for a rule are placed in an array after the severity value. (You can find more information on how to configure rules [here](https://eslint.org/docs/user-guide/configuring#configuring-rules).

In your case, you should use a configuration like this:

```json
{
  "rules": {
    "operator-linebreak": ["error", "after"]
  }
}
```

**Comment by not-an-aardvark** [comment] 2017-09-05 20:39
Closing because this is working as intended.

**Closed by not-an-aardvark** 2017-09-05 20:39 UTC
Labels: works as intended
