### ISSUE TITLE
Automatic Configuration failed.  No files were able to be parsed

### ISSUE THREAD

**Issue by arun-bs** [eslint/eslint#8826] opened 2017-06-28 06:55 UTC
**Tell us about your environment**

* **ESLint Version: v4.0.0-rc.0**
* **Node Version: v6.10.3**
* **npm Version: 3.10.10**

**What parser (default, Babel-ESLint, etc.) are you using? **
default
**Please show your full configuration:**
Did these steps 
1. npm install eslint --save-dev
2. navigated to this path and did ./node_modules/.bin/eslint --init

**What did you do? Please include the actual source code causing the issue.**

```js

\proj\node_modules\.bin>eslint --init
? How would you like to configure ESLint? Inspect your JavaScript file(s)
? Which file(s), path(s), or glob(s) should be examined? **/*.js
? What format do you want your config file to be in? JavaScript
? Are you using ECMAScript 6 features? No
? Where will your code run? Browser, Node
? Do you use CommonJS? Yes
? Do you use JSX? Yes
? Do you use React? No
Determining Config: 0% [------------------------------] 0.0s elapsed, eta 0.0s

Automatic Configuration failed.  No files were able to be parsed.
Error: Automatic Configuration failed.  No files were able to be parsed.
    at configureRules (\projnode_modules\eslint\lib\config\config-initializer.js:144:15)
    at processAnswers (\proj\node_modules\eslint\lib\config\config-initializer.js:252:18)
    at inquirer.prompt.err [as completed] (\proj\node_modules\eslint\lib\config\config-initializer.js:422:30)
    at PromptUI.onCompletion (\proj\node_modules\inquirer\lib\ui\prompt.js:57:10)
    at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.completed (\proj\node_modules\rx-lite\rx.lite.js:1550:12)
    at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (\proj\node_modules\rx-lite\rx.lite.js:1489:14)
    at Subject.onCompleted (\proj\node_modules\rx-lite\rx.lite.js:5871:19)
    at Subject.tryCatcher (\proj\node_modules\rx-lite\rx.lite.js:63:31)
    at AutoDetachObserverPrototype.completed (\proj\node_modules\rx-lite\rx.lite.js:5796:56)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (\proj\node_modules\rx-lite\rx.lite.js:1489:14)

\proj\node_modules\.bin>



```

**What did you expect to happen?**
I'm looking to find and remove the extra spaces and lines in my javascript files through ESLint
**What actually happened? Please include the actual, raw output from ESLint.**
Throwing this Error - Automatic Configuration failed.  No files were able to be parsed.

**Comment by mysticatea** [comment] 2017-06-28 18:57
> \proj\node_modules\.bin>eslint --init

By the your log, the current working directory is `\proj\node_modules\.bin`.
To make sure, do you have source code files which are matched to `**/*.js` in the directory?

**Comment by arun-bs** [comment] 2017-06-29 03:54
\proj\node_modules.bin has enlint file
And
\proj\www\js path has all my js mfiles.

So do i have to nagivate to perform eslint --init? or so how is it?

**Comment by kaicataldo** [comment] 2017-06-29 04:25
Have you tried running it from the root directory of your project (the directory with the package.json file for the whole project). From there, you can point it to `\proj\www\js` with your glob.

**Comment by arun-bs** [comment] 2017-06-29 04:43
Yes.. i have tried from the `\proj\www\js` i could able to run successfully..

![eslint2](https://user-images.githubusercontent.com/29727571/27671654-dc129808-5cb2-11e7-953f-c446aca7b168.PNG)

Enabled 102 out of 251 rules based on 228 files

Is eslint formatting is done?, how do i know extra spaces and tabs are removed?

There are rules in .eslintrc.js

`"rules": {
        "accessor-pairs": "error",        
        "array-element-newline": "off",
        "arrow-body-style": "error",
        "arrow-parens": "error",
        "arrow-spacing": "error",
        "block-scoped-var": "off",
        "block-spacing": "off",
        "brace-style": "off",
        "callback-return": "off",
        "camelcase": "off",
        "capitalized-comments": "off"
         "no-constant-condition": [
            "error",
            {
                "checkLoops": false
            }
        ],`

Is it defined or its have to be defined? how do i see if extra spaces and tabs still exists?
`

**Comment by kaicataldo** [comment] 2017-06-29 04:53
I'll try to answer all the questions I can. Please bear with me.

> Is eslint formatting is done?
ESLint can do some fixing of errors it finds (based on your configuration), but it needs to be run with the `--fix` flag to do so.

> how do i know extra spaces and tabs are removed?/how do i see if extra spaces and tabs still exists?
I would recommend version control for tracking changes.

> Is it defined or its have to be defined? 
Would you mind clarifying this question for me? I'm unfortunately not sure what you're asking.

**Comment by kaicataldo** [comment] 2017-06-29 04:55
Here are [some more resources](http://eslint.org/docs/user-guide/getting-started) for some more information on getting started and running ESLint.

**Comment by arun-bs** [comment] 2017-06-29 06:14
Thanks for the clarification. 

eslint --init is just the configuration with certain set of rules.
Next i have to set rules in `.eslintrc` which i can enable and disable.
After this i have enabled in my project in my package.json
Next i went to my specific js file or required file and did `eslint myfile.js` and i'm getting this error

`\proj\www\folder\>eslint myfile.js

Oops! Something went wrong! :(

ESLint couldn't find the plugin "eslint-plugin-promise". This can happen for a couple different reasons:

1. If ESLint is installed globally, then make sure eslint-plugin-promise is also installed globally. A globally-installed ESLint cannot find a locally-installed plugin.

2. If ESLint is installed locally, then it's likely that the plugin isn't installed correctly. Try reinstalling by running the following:

    npm i eslint-plugin-promise@latest --save-dev

If you still can't figure out the problem, please stop by https://gitter.im/eslint/eslint to chat with the team.`

Even though i did `npm i eslint-plugin-promise@latest --save-dev`, i'm getting the same error

**Comment by kaicataldo** [comment] 2017-06-29 21:24
Running `eslint myfile.js` will invoke a global installation of ESLint. Since eslint-plugin-promise is installed locally, it won't be able to find it. Running `./node_modules/.bin/eslint myfile.js` will invoke the local installation.

**Comment by not-an-aardvark** [comment] 2017-07-11 02:26
Closing because this is working as intended.

**Closed by not-an-aardvark** 2017-07-11 02:26 UTC
Labels: question
