### ISSUE TITLE
Cannot set property 'hasAwait' of null

### ISSUE THREAD

**Issue by lll000111** [eslint/eslint#12283] opened 2019-09-18 16:04 UTC
* **ESLint Version: v6.4.0**
* **Node Version: v12.10.0**
* **npm Version: 6.10.3**

**What parser (default, Babel-ESLint, etc.) are you using?**

@typescript-eslint/parser

**Please show your full configuration:**
[eslintrc](https://github.com/eslint/eslint/files/3627349/eslintrc.txt)

```
$ eslint  --ext .ts --ext .tsx src/
TypeError: Cannot set property 'hasAwait' of null
Occurred while linting /home/mha/Projects/chat/src/components/ChatMessage.tsx:127
    at AwaitExpression (/home/mha/Projects/chat/node_modules/eslint/lib/rules/require-await.js:95:36)
    at /home/mha/Projects/chat/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/home/mha/Projects/chat/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/home/mha/Projects/chat/node_modules/eslint/lib/linter/node-event-generator.js:253:26)
    at NodeEventGenerator.applySelectors (/home/mha/Projects/chat/node_modules/eslint/lib/linter/node-event-generator.js:282:22)
    at NodeEventGenerator.enterNode (/home/mha/Projects/chat/node_modules/eslint/lib/linter/node-event-generator.js:296:14)
    at CodePathAnalyzer.enterNode (/home/mha/Projects/chat/node_modules/eslint/lib/linter/code-path-analysis/code-path-analyzer.js:646:23)
    at /home/mha/Projects/chat/node_modules/eslint/lib/linter/linter.js:936:32
    at Array.forEach (<anonymous>)
```

**Comment by lll000111** [comment] 2019-09-18 16:06
Closing because I saw that function had pretty obvious issues &mdash; so, sorry, never mind.

**Comment by lll000111** [comment] 2019-09-18 16:15
Actually, _maybe_ you want to let this not crash at least?

The problem was that the function (`render()`, React project) did is not `async` but somebody used `await` in the function body. Clearly an error of course, but maybe it should not crash eslint completely.

**Comment by kaicataldo** [comment] 2019-09-18 18:38
This isn't currently handled by the rule because this is a parser error in the default parser and in Babel's parser (see [demo](https://eslint.org/demo#eyJ0ZXh0IjoiY2xhc3MgQ29tcG9uZW50IGV4dGVuZHMgUmVhY3QuQ29tcG9uZW50IHtcbiAgICByZW5kZXIoKSB7XG4gICAgICAgIGNvbnN0IGRhdGEgPSBhd2FpdCBnZXREYXRhKCk7XG4gICAgICBcdHJldHVybiA8U3ViY29tcG9uZW50IGRhdGE9e2RhdGF9IC8+O1xuICAgIH1cbn0iLCJvcHRpb25zIjp7InBhcnNlck9wdGlvbnMiOnsiZWNtYVZlcnNpb24iOjExLCJzb3VyY2VUeXBlIjoic2NyaXB0IiwiZWNtYUZlYXR1cmVzIjp7ImpzeCI6dHJ1ZX19LCJydWxlcyI6eyJjb25zdHJ1Y3Rvci1zdXBlciI6MiwiZm9yLWRpcmVjdGlvbiI6MiwiZ2V0dGVyLXJldHVybiI6Miwibm8tYXN5bmMtcHJvbWlzZS1leGVjdXRvciI6Miwibm8tY2FzZS1kZWNsYXJhdGlvbnMiOjIsIm5vLWNsYXNzLWFzc2lnbiI6Miwibm8tY29tcGFyZS1uZWctemVybyI6Miwibm8tY29uZC1hc3NpZ24iOjIsIm5vLWNvbnN0LWFzc2lnbiI6Miwibm8tY29uc3RhbnQtY29uZGl0aW9uIjoyLCJuby1jb250cm9sLXJlZ2V4IjoyLCJuby1kZWJ1Z2dlciI6Miwibm8tZGVsZXRlLXZhciI6Miwibm8tZHVwZS1hcmdzIjoyLCJuby1kdXBlLWNsYXNzLW1lbWJlcnMiOjIsIm5vLWR1cGUta2V5cyI6Miwibm8tZHVwbGljYXRlLWNhc2UiOjIsIm5vLWVtcHR5IjoyLCJuby1lbXB0eS1jaGFyYWN0ZXItY2xhc3MiOjIsIm5vLWVtcHR5LXBhdHRlcm4iOjIsIm5vLWV4LWFzc2lnbiI6Miwibm8tZXh0cmEtYm9vbGVhbi1jYXN0IjoyLCJuby1leHRyYS1zZW1pIjoyLCJuby1mYWxsdGhyb3VnaCI6Miwibm8tZnVuYy1hc3NpZ24iOjIsIm5vLWdsb2JhbC1hc3NpZ24iOjIsIm5vLWlubmVyLWRlY2xhcmF0aW9ucyI6Miwibm8taW52YWxpZC1yZWdleHAiOjIsIm5vLWlycmVndWxhci13aGl0ZXNwYWNlIjoyLCJuby1taXNsZWFkaW5nLWNoYXJhY3Rlci1jbGFzcyI6Miwibm8tbWl4ZWQtc3BhY2VzLWFuZC10YWJzIjoyLCJuby1uZXctc3ltYm9sIjoyLCJuby1vYmotY2FsbHMiOjIsIm5vLW9jdGFsIjoyLCJuby1wcm90b3R5cGUtYnVpbHRpbnMiOjIsIm5vLXJlZGVjbGFyZSI6Miwibm8tcmVnZXgtc3BhY2VzIjoyLCJuby1zZWxmLWFzc2lnbiI6Miwibm8tc2hhZG93LXJlc3RyaWN0ZWQtbmFtZXMiOjIsIm5vLXNwYXJzZS1hcnJheXMiOjIsIm5vLXRoaXMtYmVmb3JlLXN1cGVyIjoyLCJuby11bmV4cGVjdGVkLW11bHRpbGluZSI6Miwibm8tdW5yZWFjaGFibGUiOjIsIm5vLXVuc2FmZS1maW5hbGx5IjoyLCJuby11bnNhZmUtbmVnYXRpb24iOjIsIm5vLXVudXNlZC1sYWJlbHMiOjIsIm5vLXVudXNlZC12YXJzIjoyLCJuby11c2VsZXNzLWNhdGNoIjoyLCJuby11c2VsZXNzLWVzY2FwZSI6Miwibm8td2l0aCI6MiwicmVxdWlyZS1hdG9taWMtdXBkYXRlcyI6MiwicmVxdWlyZS15aWVsZCI6MiwidXNlLWlzbmFuIjoyLCJ2YWxpZC10eXBlb2YiOjIsImluZGVudCI6Mn0sImVudiI6e319fQ==)). I don't think it would be a bad thing to update the rule to not crash here, but I think the real fix should be that @typescript-eslint/parser should throw a parser error here.

**Comment by mdjermanovic** [comment] 2019-09-18 19:44
An interesting thing is that it seems that the rule in question `require-await` can survive the described scenario (`await` in a non-async function) and even work well for the rest of the same file.

The rule can crash on a top-level `await`, though. If this isn't an `await` outside of any functions, then it might be a completely broken AST.

**Comment by kaicataldo** [comment] 2019-09-18 20:23
@lll000111 Do you mind sharing the code (or a minimal repro case) that is causing this on your end?

**Comment by lll000111** [comment] 2019-09-18 21:05
Here's the complete file. I'm not the author, I merely observe the project, and it is being transitioned to TypeScript. The crash was reported coming from line 127.

```js
import React, {PureComponent, ReactElement} from 'react';
import {abToURL, download} from '../dom';
import * as types from '@OneCoreTypes';
import {ChatMessageProps} from '../propsTypes';
import {uGetObjectByHash} from '../one/worker/WorkerBridge';
import {Attachment} from '@OneCoreTypes';

/**
 *
 */
export function renderAttachment(
    attachments: Array<types.Attachment>,
    idx: number
): ReactElement | HTMLElement | any {
    if (attachments) {
        return attachments.map((attachment: types.Attachment, idx2: number) => {
            attachment.objUrl = abToURL(attachment.data.type);

            switch (attachment.dataType) {
                case 'video': {
                    return (
                        <video width={320} height={240} controls key={'a' + idx + idx2}>
                            <source src={attachment.objUrl} />
                        </video>
                    );
                }
                case 'image': {
                    return (
                        <img src={attachment.objUrl} alt="" height={300} key={'a' + idx + idx2} />
                    );
                }
                case 'audio': {
                    return (
                        <audio controls key={idx + idx2}>
                            <source src={attachment.objUrl} />
                        </audio>
                    );
                }
                default: {
                    return (
                        <a // eslint-disable-line
                            href="#"
                            onClick={() =>
                                download(
                                    attachment.data.type,
                                    attachment.filename,
                                    attachment.dataType
                                )
                            }
                            key={'a' + idx + idx2}
                        >
                            {attachment.filename}
                        </a>
                    );
                }
            }
        });
    }

    return;
}

export class ChatMessage extends PureComponent<ChatMessageProps> {
    renderMessage(): JSX.Element[] {
        const {message} = this.props.message;
        const {emojiMap, showEmoji} = this.props;
        const rgx = new RegExp('\\((\\w+)\\)', 'g');
        let start = 0;
        let match;
        let key = 0;
        const elems = [];

        while ((match = rgx.exec(message)) !== null) {
            elems.push(<span key={key++}>{message.substring(start, match.index)}</span>);

            const name = match[1];
            const emoji = emojiMap.get(name);

            if (emoji) {
                elems.push(
                    <img
                        key={key++}
                        src={emoji.smallImage}
                        alt={`${name} emoji`}
                        onClick={() => showEmoji(emoji)}
                        style={{height: '1.2em'}}
                    />
                );
            } else {
                elems.push(<span key={key++}>{match[0]}</span>);
            }
            start = rgx.lastIndex;
        }
        elems.push(<span key={key++}>{message.substring(start)}</span>);
        return elems;
    }

    render(): ReactElement | HTMLElement | undefined {
        const {message, idx, sourcePersonRes, partnerProfilePerson} = this.props;
        let senderName, me;

        if (partnerProfilePerson) {
            senderName = partnerProfilePerson.name;

            if (message.source === undefined) {
                return;
            }
            me = sourcePersonRes.type.email === message.source.type.email;
        }

        if (message.source) {
            me = sourcePersonRes.type.email === message.source.type.email;
            senderName = message.source.type.name;
        }

        const date = new Date(message.date);
        const now = new Date();
        const today =
            date.getDate() === now.getDate() &&
            date.getMonth() === now.getMonth() &&
            date.getFullYear() === now.getFullYear();
        const dt = today
            ? date.toLocaleTimeString('de-DE').substr(0, 5)
            : date.toLocaleDateString('de-DE');
        const color = me ? '#e91e63' : '#673ab7';

        const attachmentsArray = (await Promise.all(
            (message.attachments || []).map(idHash => uGetObjectByHash(idHash))
        )) as Attachment[];

        return (
            <div
                key={'m' + idx}
                style={{
                    display: 'flex',
                    width: '100%',
                    margin: '10px 0',
                    justifyContent: me ? 'flex-end' : 'flex-start'
                }}
            >
                <div
                    style={{
                        position: 'relative',
                        padding: 10,
                        borderRadius: 5,
                        backgroundColor: me ? '#f8bbd0' : '#d1c4e9',
                        minWidth: 125,
                        maxWidth: '80%'
                    }}
                >
                    <div style={{padding: '7px 0 5px 0'}}>
                        <strong style={{color}}>{me ? 'me' : senderName}</strong>
                        :&nbsp;
                        {this.renderMessage()}
                        <span>{renderAttachment(attachmentsArray, idx)}</span>
                    </div>
                    <span
                        style={{
                            position: 'absolute',
                            top: 0,
                            right: 0,
                            fontSize: '0.8em',
                            padding: '2px 5px',
                            color
                        }}
                    >
                        {dt}
                    </span>
                </div>
            </div>
        );
    }
}
```

**Comment by kaicataldo** [comment] 2019-09-18 21:17
Thanks. I made [an issue](https://github.com/typescript-eslint/typescript-eslint/pull/988) and [PR](https://github.com/typescript-eslint/typescript-eslint/issues/987) in the `typescript-eslint` repo.

**Comment by mdjermanovic** [comment] 2019-09-18 23:34
The project is actually using `@typescript-eslint/require-await` rule, not directly `require-await`. This rule internally uses the core `require-await` and also has some additional logic from the typing information (allows `async` functions without `await` in some cases).

Docs: [@typescript-eslint/require-await.md](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/require-await.md)

Source code: [https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/src/rules/require-await.ts](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/src/rules/require-await.ts)

It doesn't appear in the stack trace because it just returns a reference to `AwaitExpression`. When the line `AwaitExpression: rules.AwaitExpression` in the distribution code is replaced with  something like `AwaitExpression(node){ rules.AwaitExpression(node); }`, it does appear in the stack trace.

While the core rule doesn't crash on this code, the `@typescript-eslint` wrapper does, because it has a bit different selectors - `FunctionExpression[async = true]` instead of just `FunctionExpression`.

**Comment by kaicataldo** [comment] 2019-09-19 00:06
Thanks for the explanation! Sounds like it's indeed an issue for @typescript-eslint.

**Comment by ilyavolodin** [comment] 2019-09-25 01:35
Closing this issue, since the problem is in typescript-eslint

**Closed by ilyavolodin** 2019-09-25 01:35 UTC
Labels: bug, evaluating, rule

**Comment by biolauri** [comment] 2019-11-22 11:48
I just want to link the issue on @typescript-eslint: typescript-eslint/typescript-eslint#1226 for reference and if anyone stumblesupon this.

By the way, the issue is already fixed and will be released on monday, as stated in https://github.com/typescript-eslint/typescript-eslint/issues/1226#issuecomment-556091942.
