### ISSUE TITLE
`Unexpected token ..` in object

### ISSUE THREAD

**Issue by arnarthor** [eslint/eslint#2369] opened 2015-04-24 10:37 UTC
```js
const buttonClass = {
  'CollectionPage__toolHeader__button': true
};
```
```js              
<Button
  className={classNames({
    ...buttonClass,
    'CollectionPage__toolHeader__button--back': true,
  })}
>
```
I have this React JSX code which compiles using Babel. It's not passing linting because of the ...buttonClass spread in the classNames object.

I have `spread` in my eslintrc and I tried to turn on `restParams` as well but it didn't help either.

**Comment by lo1tuma** [comment] 2015-04-24 11:19
Duplicate of #2352.

This is the [spread properties operator](https://github.com/sebmarkbage/ecmascript-rest-spread) which is a proposal for ES7. It is neither a feature of ES6 nor of JSX.

**Comment by arnarthor** [comment] 2015-04-24 11:23
Ok, thanks. Tried looking for this in the issues and didn't come across the one above.

Same issue for me as for the other, this is Reacts recommended way so I thought it was standardized.

**Closed** 2015-04-24 16:37 UTC
Labels: question
