### ISSUE TITLE
`overrides` from config in npm package looks for files in node_modules

### ISSUE THREAD

**Issue by gziolo** [eslint/eslint#12278] opened 2019-09-17 14:23 UTC
**Tell us about your environment**

* **ESLint Version:** 6.1.0
* **Node Version:** 10.16.3
* **npm Version:** 6.11.3

**What parser (default, Babel-ESLint, etc.) are you using?**
babel-eslint

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

I use the config file which is published to npm package when running ESLint.

Config file is located in `node_modules/@wordpress/scripts/config/.eslintrc.js`:
```js
module.exports = {
	root: true,
	extends: [ 'plugin:@wordpress/eslint-plugin/recommended' ],
};
```

The config file used in `extends` contains overrides as shown below:

```js
module.exports = {
	parser: 'babel-eslint',
	extends: [
		require.resolve( './jsx-a11y.js' ),
		require.resolve( './custom.js' ),
		require.resolve( './react.js' ),
		require.resolve( './esnext.js' ),
	],
	env: {
		node: true,
	},
	globals: {
		window: true,
		document: true,
		wp: 'readonly',
	},
	overrides: [
		{
			// Unit test files and their helpers only.
			files: [
				'**/@(test|__tests__)/**/*.js',
				'**/?(*.)test.js',
			],
			extends: [
				require.resolve( './test-unit.js' ),
			],
		},
		{
			// End-to-end test files and their helpers only.
			files: [
				'**/specs/**/*.js',
				'**/?(*.)spec.js',
			],
			extends: [
				require.resolve( './test-e2e.js' ),
			],
		},
	],
};
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

It looks like `overrides` inherits also `basePath` for filtering files from the location of the config file when using `extend` making it not that much useful when consuming config published to npm. Related PR where I discovered it: https://github.com/WordPress/gutenberg-examples/pull/87#issuecomment-526204832

I reported in under https://github.com/eslint/eslint/issues/12032#issuecomment-526237923. It was only partially fixed with #12205.

**What did you expect to happen?**

Overrides in the config file match against my project rather than the folder where the config file is located in `node_modules` subfolder.

**What actually happened? Please include the actual, raw output from ESLint.**

This is the line which sets `basePath` based on the location of the file:
https://github.com/eslint/eslint/blob/00d2c5be9a89efd90135c4368a9589f33df3f7ba/lib/cli-engine/config-array-factory.js#L485

Example of the override:

```
criteria:
     { includes: [Array],
       excludes: null,
       basePath:
        '/Users/gziolo/PhpstormProjects/gutenberg-examples/node_modules/@wordpress/scripts/config' },
```

which obviously can't match any files in the project.

**Are you willing to submit a pull request to fix this bug?**
I'm happy to do it if I get some guidelines what would be the best way to address it.

**Comment by mysticatea** [comment] 2019-09-17 21:39
Thank you for your report.

Would you provide minimal repro steps?
The `basePath` should be the entry file's directory path rather than shareable config's directory path.

**Comment by mysticatea** [comment] 2019-09-17 21:45
Ah, after re-read, it looks intentional behavior. Because you use `node_modules/@wordpress/scripts/config/.eslintrc.js` directly, the `overrides` path will be handled as relative to the `node_modules/@wordpress/scripts/config/.eslintrc.js`.

**Comment by gziolo** [comment] 2019-09-17 22:36
> Ah, after re-read, it looks intentional behavior. Because you use `node_modules/@wordpress/scripts/config/.eslintrc.js` directly, the `overrides` path will be handled as relative to the `node_modules/@wordpress/scripts/config/.eslintrc.js`.

Yes, this is how it works but it prevents you from using a valid config file which happens to be located in the node_modules and uses overrides in nested configs. There should be at least a way to provide the alternative base path for file matchers.

**Comment by mysticatea** [comment] 2019-09-17 22:39
To clarify, is this the same issue as https://github.com/eslint/eslint/issues/11558? (glob-based configuration along with `--config` option?)

**Comment by gziolo** [comment] 2019-09-17 22:58
It seems like you are correct. I can see it as the same issue once I read its full description.

**Comment by mysticatea** [comment] 2019-09-18 01:38
> By the way, .eslintignore is resolved from the root of the project rather than the folder where it is located.

It's a bug because [`.eslintignore` patterns should be resolved from the location of the file](https://eslint.org/docs/user-guide/migrating-to-4.0.0#eslintignore-patterns) since ESLint 4.0.0.

**Comment by mysticatea** [comment] 2019-09-18 01:47
Thank you for confirming. I'm closing this issue as a duplicate of https://github.com/eslint/eslint/issues/11558. It's intentional behavior, but I think we should change the behavior in the next major version.

**Closed by mysticatea** 2019-09-18 01:47 UTC
Labels: bug, core, evaluating

**Comment by gziolo** [comment] 2019-09-19 09:35
> From https://github.com/WordPress/gutenberg/blob/1c35075833c6fba8619ee0dcfe4596e610ceef48/packages/scripts/config/.eslintignore, it's intentional behavior because those patterns don't start with `/`. Those patterns are valid in all directories.

That's very interesting to learn. It looks like a lucky coincidence it works properly then. Thanks for opening eslint/rfcs/pull/37 which should change it to more anticipated behavior.
