### ISSUE TITLE
key-spacing + align: 'value' + jsx objects becomes ugly sometimes

### ISSUE THREAD

**Issue by a-x-** [eslint/eslint#11414] opened 2019-02-19 16:25 UTC
<img width="1440" alt="screenshot 2019-02-19 at 18 51 23" src="https://user-images.githubusercontent.com/6201068/53028310-b097c600-3477-11e9-9fe3-2a222df69e10.png">

<img width="1025" alt="image" src="https://user-images.githubusercontent.com/6201068/53029220-6c0d2a00-3479-11e9-877c-b001a7c6ed44.png">

**👀 Look at the repo with minimal reproducible example (dependencies, config, source):** https://github.com/a-x-/eslint-align-check

<br/><br/>

----

<br/><br/>

**environment**

* **ESLint Version:** latest (5.13.0)
* **Node Version:** latest (11.9.0)
* **npm Version:** latest (6.8.0)

**parser**: Babel-ESLint 

**minimal configuration:** (full config has no sense never : )

```js
{
  "plugins": [
    "react",
  ],
  "rules": {
    "key-spacing": ["warn", {
      "multiLine": {"align": "value"},
    }],
    // some related a bit rules
    "object-curly-newline": ["warn", { "multiline": true, "minProperties": 5 }],
    "object-property-newline": ["warn", {"allowAllPropertiesOnSameLine": true }],
    "object-curly-spacing": ["warn", "always", {
      "arraysInObjects": false,
      "objectsInObjects": false,
    }],
    // ...
  },
}
```

**source and command**

<details><summary>source before eslint --fix ran</summary>

```jsx
function Component () {
      return <div>
        <span style={{ display: 'inline-block', marginRight: '10px' }}>
          <Fa
            icon={ d.icon }
            style={{ marginRight: '4px', color: '#0C090A', opacity: '0.6', fontSize: '18px', verticalAlign: 'middle' }}
          />
          <span style={{ verticalAlign: 'bottom' }}>{ d.title }</span>
        </span>
        <span>
          <Fa
            icon="location-arrow"
            style={{ marginRight: '4px', color: '#0C090A', opacity: '0.6', fontSize: '18px', verticalAlign: 'middle' }}
          />
          <span style={{ verticalAlign: 'bottom' }}>{ this.state.info?.device.app_version }</span>
          <br />
          <span style={{ color: '#999999' }} title="Когда последний раз делал что-то в приложении">
            { this.state.info?.device.last_request_at }
          </span>
        </span>
      </div>;
}
```

</details>

```bash
eslint --fix file.jsx
```

**Expected:** don't re-align objects in jsx curlies.

**PR?** I'm not sure, maybe I can.

**Comment by aladdin-add** [comment] 2019-02-20 14:34
thanks for the issue, I was able to repro it!

**Comment by aladdin-add** [comment] 2019-08-15 08:12
reopen as it is happening in latest eslint and default parser: I've created a mini [demo](https://eslint.org/demo#eyJ0ZXh0IjoiLyplc2xpbnQgXCJrZXktc3BhY2luZ1wiOiBbXCJ3YXJuXCIsIHtcIm11bHRpTGluZVwiOiB7XCJhbGlnblwiOiBcInZhbHVlXCJ9fV0qL1xuXG5zdHlsZT17XG4gbWFyZ2luUmlnaHQ6ICc0cHgnLCBjb2xvcjogJyMwQzA5MEEnLFxufVxuIiwib3B0aW9ucyI6eyJwYXJzZXJPcHRpb25zIjp7ImVjbWFWZXJzaW9uIjoxMCwic291cmNlVHlwZSI6InNjcmlwdCIsImVjbWFGZWF0dXJlcyI6eyJqc3giOnRydWV9fSwicnVsZXMiOnt9LCJlbnYiOnt9fX0=)

**Comment by yeonjuan** [comment] 2019-10-22 13:05
@aladdin-add 
For fixing this issue, 
I thought that `the multiple properties on a single line` should be treated as a single line. And fix it. (#12472) . Am I missing something?
```js
({
   a: 1, b: 3, c:4, // single line.
});
```

**Comment by kaicataldo** [comment] 2019-11-25 03:19
We decided to revert the PR that closed this due to a regression. @yeonjuan We would love to work with you on finding an alternate solution, if you'd like still to work on this!

**Comment by yeonjuan** [comment] 2019-11-25 06:55
@kaicataldo 
I still want to work on this :) 
```js
const obj = {
    key1: "value1", key2: "value2",  // (1)
}
```
The line *(1)* should be checked by a multiline option(`multiLine.beforeColon, multiLine.afterColon`) because the *obj* should be considered as a multi-line object.

But I think the `multiLine.align` is for vertical aligning. What about just not checking a `multiLine.align`option in this case?

**Comment by kaicataldo** [comment] 2019-11-25 19:00
The configuration options for this rule are really confusing 😬 

I think your proposal makes sense and we should ignore aligning a line when it contains multiple properties. 

So these would be correct:

```js
/*eslint "key-spacing": [2, {
    "singleLine": {
        "beforeColon": false,
        "afterColon": true
    },
    "multiLine": {
        "beforeColon": true,
        "afterColon": true,
        "align": "colon"
    }
}]*/
var obj = { one: 1, "two": 2, three: 3 };
var obj2 = {
    "two" : 2,
    three : 3
};
var obj2 = {
    one : 1, "two" : 2, three : 3 
};
```

Curious what other team members also think.

**Closed** 2019-12-20 20:51 UTC
Labels: accepted, autofix, bug, help wanted, rule
