### ISSUE TITLE
ES6 modules: TypeError: Cannot read property 'type' of undefined

### ISSUE THREAD

**Issue by badsyntax** [eslint/eslint#2042] opened 2015-03-15 10:06 UTC
Hi.

I'm using 0.17.0, and I have the following code in a file `test.js`:

```js
import EventEmitter from 'events';
```
I have the following eslint config:

```js
"env": {
  "es6": true
},
"ecmaFeatures": {
  "modules": true
}
```

When running eslint on that file I get the following error: `TypeError: Cannot read property 'type' of undefined`

Exporting or referencing that object fixes the error:

```js
import EventEmitter from 'events';

export default class Base extends EventEmitter {
  method() {
    return 'foo';
  }
}
```

Setting a property now causes a different error `TypeError: Cannot read property 'name' of undefined`:

```js
import EventEmitter from 'events';

export default class Base extends EventEmitter {
  method() {
    this.foo = 'bar';
  }
}
```

**Comment by btmills** [comment] 2015-03-15 19:46
Stack trace for `TypeError: Cannot read property 'type' of undefined` puts the error at [`no-unused-vars` line 43](https://github.com/eslint/eslint/blob/master/lib/rules/no-unused-vars.js#L43), which is `if (definition.type === "VariableDeclarator") {`.

Stack trace for `TypeError: Cannot read property 'name' of undefined` puts the error at [`no-func-assign` line 42](https://github.com/eslint/eslint/blob/master/lib/rules/no-func-assign.js#L42), which is `if (def.name.name === name && def.type === "FunctionName") {`.

**Comment by benmosher** [comment] 2015-03-16 10:11
I'm seeing the `no-func-assign` issue on a number of files that were linting properly with v0.16.x, as well.

**Comment by nzakas** [comment] 2015-03-16 16:19
@benmosher one big report per issue, please.

**Comment by btmills** [comment] 2015-03-16 16:45
Technically #2071 is a duplicate of this issue, though it reports the `no-func-assign` error first, so let's use this issue for `no-unused-vars` and #2071 for `no-func-assign`.

**Comment by btmills** [comment] 2015-03-16 17:06
Working on this.

**Comment by btmills** [comment] 2015-03-16 17:08
The `no-unused-vars` error only occurs when `no-undef` is also enabled.

`config.json`:

```json
{
    "env": {
        "es6": true
    },
    "ecmaFeatures": {
        "modules": true
    },
    "rules": {
        "no-undef": 2,
        "no-unused-vars": [2, {"vars": "all", "args": "after-used"}],
    }
}
```

```js
// test.js
import foo from 'foo';
```

```sh
$ eslint --reset --no-eslintrc -c config.json test.js
~/code/eslint/eslint/lib/rules/no-unused-vars.js:43
            if (definition.type === "VariableDeclarator") {
                          ^
TypeError: Cannot read property 'type' of undefined
    at isExported (~/code/eslint/eslint/lib/rules/no-unused-vars.js:43:27)
    at EventEmitter.Program:exit (~/code/eslint/eslint/lib/rules/no-unused-vars.js:120:70)
    at EventEmitter.emit (events.js:129:20)
    at Controller.controller.traverse.leave (~/code/eslint/eslint/lib/eslint.js:743:25)
    at Controller.__execute (~/code/eslint/eslint/node_modules/estraverse/estraverse.js:393:31)
    at Controller.traverse (~/code/eslint/eslint/node_modules/estraverse/estraverse.js:481:28)
    at EventEmitter.module.exports.api.verify (~/code/eslint/eslint/lib/eslint.js:728:24)
    at processFile (~/code/eslint/eslint/lib/cli-engine.js:193:27)
    at ~/code/eslint/eslint/lib/cli-engine.js:293:26
    at walk (~/code/eslint/eslint/lib/util/traverse.js:81:9)
```

Removing either of the rules from `config.json` will fail to cause the crash.

**Comment by btmills** [comment] 2015-03-16 17:14
The [`fixImport` hack](https://github.com/eslint/eslint/pull/2035/files#diff-ea0b9e946006fda580f880dc50c9a61cR108) temporarily added in #2035 isn't properly cleaning up after itself.

**Closed** 2015-03-16 22:50 UTC
Labels: accepted, bug, rule

**Comment by badsyntax** [comment] 2015-03-18 19:23
Thanks! I've tested this change with 0.17.1 and it's now working as expected :+1:

**Comment by benmosher** [comment] 2015-03-19 12:50
I am also not seeing a crash anymore, but `no-unused-vars` no longer highlights unused import specifiers in 0.17.1. Is this expected, given the escope workaround?

(I thought about opening a new issue, but I'm not clear on whether this is understood behavior.)

**Comment by nzakas** [comment] 2015-03-19 15:14
Please file a new issue and provide sample code plus console output.

**Comment by benmosher** [comment] 2015-03-19 16:07
Done: #2114
