### ISSUE TITLE
require-jsdoc FunctionExpression has additional properties

### ISSUE THREAD

**Issue by simonepri** [eslint/eslint#9825] opened 2018-01-08 09:56 UTC
**Tell us about your environment**

* **ESLint Version:** 4.9.0 (See [here](https://github.com/sindresorhus/xo/blob/master/package.json#L75))
* **Node Version:** 8.2.1
* **npm Version:** 5.5.1

**What parser (default, Babel-ESLint, etc.) are you using?**
[xo](https://github.com/sindresorhus/xo)

**Please show your full configuration:**

```js
"require-jsdoc": [
  "warn", {
    "require": {
      "FunctionExpression": true
    }
  }
]
```

**What did you do?**

```bash
xo
```

**What did you expect to happen?**
xo should lint successfully using ESlint.

**What actually happened?**
It throws an exception:

```bash
> xo

Error: CLI:
	Configuration for rule "require-jsdoc" is invalid:
	Value "data["0"].require.FunctionExpression" has additional properties.

    at Object.validateRuleOptions (~/my-package/node_modules/eslint/lib/config/config-validator.js:109:15)
    at CLIEngine.Object.keys.forEach.name (~/my-package/node_modules/eslint/lib/cli-engine.js:476:19)
    at Array.forEach (native)
    at new CLIEngine (~/my-package/node_modules/eslint/lib/cli-engine.js:475:43)
    at runEslint (~/my-package/node_modules/xo/index.js:107:17)
    at globby.then.paths (~/my-package/node_modules/xo/index.js:74:11)
```

> All the others options of the require-jsdoc rule works. The problem is only with the FunctionExpression one.

**Comment by ilyavolodin** [comment] 2018-01-11 02:44
xo comes bundled with it's own version of ESLint, so if you are executing ESLint through xo, you don't need ESLint as a dependency (at least as far as I understand it, never used xo myself). Please verify that version of xo that you have installed requires at least ESLint 3.9.0, since that's the version when this option was introduced.

**Comment by simonepri** [comment] 2018-01-11 07:20
Hi @ilyavolodin, thank you for the answer!

I've wrote the version that xo uses inside **its**  `packages.json`  (see the link). I don't have ESLint inside **my**  `package.json`.

**Comment by ilyavolodin** [comment] 2018-01-11 13:48
Oh, I see. Sorry, I didn't look closely enough, and thought that the link was to you repository's package.json file. In that case, I'm not really sure what the problem might be. However, ESLint version that xo uses is reasonably old, even if we prove that there was an issue with it, there would be nothing we could address. Could you try running latest version of ESLint stand-along with the config you are using and see if you can reproduce this issue in isolation?

**Comment by simonepri** [comment] 2018-01-11 16:06
I think I've found the problem:
![image](https://user-images.githubusercontent.com/3505087/34833233-3d7e9034-f6ef-11e7-9250-5fd08b62f629.png)
As you said, the problem is related with the fact that xo uses an outdated version of ESLint.

Chaning this:
```json
"xo": "https://github.com/sindresorhus/xo.git"
```
to
```json
"xo": "https://github.com/sindresorhus/xo.git"
```
solves the problem.

It seems that they have updated it recently but not yet released:
https://github.com/sindresorhus/xo/commit/a11e288d7227aa55db6df130d42f3593f8474ded#diff-b9cfc7f2cdf78a7f4b91a753d10865a2

I think we can close the issue.

Thank you!

**Comment by ilyavolodin** [comment] 2018-01-11 20:55
Great. Thanks for the follow up. Closing issue as resolved.

**Closed by ilyavolodin** 2018-01-11 20:55 UTC
Labels: question
