### ISSUE TITLE
"indent" rule --fix issue

### ISSUE THREAD

**Issue by jdb8** [eslint/eslint#3911] opened 2015-09-23 14:03 UTC
**What version are you using?**
v1.5.0

**What did you do?**
Set `"indent": 2` in my config, and ran `eslint --fix` on a file with incorrect indentation:
```
function foo(){
   alert('3 spaces!');
   (function () {
     alert('nested indentation');
   })();
}
```

**What happened?**
Running eslint without `--fix` produces the following, as expected:
```
2:4  error  Expected indentation of 4 space characters but found 3  indent
3:4  error  Expected indentation of 4 space characters but found 3  indent
4:6  error  Expected indentation of 7 space characters but found 5  indent

✖ 3 problems (3 errors, 0 warnings)
```

but running with `--fix` only partially fixed the indentation:
```
function foo(){
    alert('3 spaces!');
    (function () {
       alert('nested indentation');
   })();
}
```

Running eslint again without `--fix` confirms the file still has indentation issues:

```
4:8  error  Expected indentation of 8 space characters but found 7  indent
5:4  error  Expected indentation of 4 space characters but found 3  indent

✖ 2 problems (2 errors, 0 warnings)
```
**What did you expect to happen?**
The file should be fully fixed according to the specified indentation (4 spaces), and further runs of `eslint` on the file should pass cleanly.

Expected file after `eslint --fix`:
```
function foo(){
    alert('3 spaces!');
    (function () {
        alert('nested indentation');
    })();
}
```

**Comment by gyandeeps** [comment] 2015-09-23 14:38
Its not an issue with `fix` but with the rule actually flagging the code with wrong indentation.
Related https://github.com/eslint/eslint/issues/3737

Whats happening here is that the start of the function on line 3 has a wrong indentation, thats why its calculating the indentation of the body incorrectly.
Secondly, same concept applies to the close of the function on line 5. Since in your first run that line was never reported as a n issue that why it dint fix it.

This is a scenario where 2 runs would fix the issue completely. This is not the best case scenario but this is a known limitation of the rule.

I guess we can mention this on our docs.
Thoughts @BYK @nzakas @ilyavolodin

**Comment by jdb8** [comment] 2015-09-23 14:47
@gyandeeps although in this case 2 runs does fix it, with a more complex example it's possible to require more, since as each layer is fixed, the next run identifies new indentation issues.

I haven't looked into the implementation yet, but it seems that the jscs 4-space indentation autofix works as expected.

**Comment by gyandeeps** [comment] 2015-09-23 14:50
Our logic is way different from theirs. I dont want to lay down the comparisons here but with this limitation, the advantage we have is that we cover a lot of scenarios which jscs counter part doesnt.

**Comment by BYK** [comment] 2015-09-23 15:38
Hah, this is very interesting. @gyandeeps I'd rather fix this instead. May be instead of relying on the parent indentation, we should detect the nesting level and calculate the "ideal" indent directly from that.

What do you think?

**Comment by gyandeeps** [comment] 2015-09-23 15:51
Yup, we need to come up with a way to accomplish this.
that why I have an issue for it: #3737 

My guess is this would apply to any kind of node because we always calculate the indentation based on the parents indentation.

**Comment by BYK** [comment] 2015-09-23 16:30
Then we should close this one as a dupe of #3737, right?

**Comment by gyandeeps** [comment] 2015-10-02 20:21
closing for #3772

**Closed by gyandeeps** 2015-10-02 20:21 UTC
Labels: bug, rule
