### ISSUE TITLE
`spaced-comment`: Clarify support for single line comments

### ISSUE THREAD

**Issue by mijelin** [eslint/eslint#13032] opened 2020-03-11 22:37 UTC
**The version of ESLint you are using.**
* **ESLint Version:** 6.8.0
* **Node Version:** 10.15.3
* **npm Version:** 6.11.3

**The problem you want to solve.**
Update [documentation and examples for `spaced-comment` rule](https://eslint.org/docs/rules/spaced-comment).

The existing documentation includes examples such as the following:
```js
/* eslint spaced-comment: ["error", "always", { "exceptions": ["*"] }] */

/****************
 * Comment block
 ****************/
```

```js
/* eslint spaced-comment: ["error", "always", { "line": { "exceptions": ["-"] } }] */

//--------------
// Comment block
//--------------
```

However, it is not clear whether the rule supports something similar for single-line comments:
```js
/////// UTILITIES

/***** Constants *****/
```

or why
```js
/* eslint spaced-comment: ["error", "always", { "exceptions": ["*"] }] */
```

allows for
```js
/***********
 * COMMENT *
 * *********/
```

but not
```js
/***** COMMENT *****/
```

The only way I've found to allow for the single-line examples (I'm trying to apply this rule to an existing codebase) is to abuse the "marker" option:
```
"spaced-comment": [
  "error",
  "always",
  {
    // "exceptions": ["/", "*"] // this does not work
    markers: ["/////", "****"]  // this does work, but I have to specify the exact number of characters
  }
]
```

**Your take on the correct solution to problem.**
For single-line comments:
* If this type of exception is already supported, add additional examples (similar to the above).
* If this is intentionally not supported, make this clear.

If this is currently not supported, but something the team is willing to consider, then I'm happy to convert this to a rule change request. :)

**Are you willing to submit a pull request to implement this change?**
Yes, just not sure what the intended behavior is.

**Comment by mdjermanovic** [comment] 2020-03-12 00:14
Hi @mijelin, thanks for the issue!

I can confirm this is the intended behavior. An exception should start from the beginning of the comment and repeat until the end of the line (or `*/` if it is on the same line):

```js
/* eslint spaced-comment: ["error", "always", { "exceptions": ["-"] }] */

//----

/*----*/

/*----
*/
```

> If this is intentionally not supported, make this clear.

Completely agree, a PR to clarify `"exceptions"` in the documentation is welcome!

> If this is currently not supported, but something the team is willing to consider, then I'm happy to convert this to a rule change request. :)

This would need an additional option, so I think it's good to have two separate issues in this case - one to improve the documentation for the actual behavior, the other to evaluate an enhancement.

Since this one already has a title and form of a documentation issue, I marked it as accepted. Feel free to open another issue for a rule change request :)

**Closed** 2020-04-04 20:10 UTC
Labels: accepted, documentation, rule
