### ISSUE TITLE
4.18.2 - "Cannot read property 'type' of undefined" in no-unused-vars when checking flow type definitions

### ISSUE THREAD

**Issue by tomasz-sodzawiczny** [eslint/eslint#10090] opened 2018-03-15 11:07 UTC
**Tell us about your environment**

* **ESLint Version:** 4.18.2 (it works in 4.18.1)!
* **Node Version:** 9.8.0
* **yarn Version:** 1.5.1

**What parser (default, Babel-ESLint, etc.) are you using?**
`babel-eslint@8.2.2`

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
module.exports = {
  parser: 'babel-eslint',
  rules: {
    'no-unused-vars': 'error'
  }
};
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

The issue only occures for files where a result type is defined for an arrow function:
```js
// @flow

type Type = null;
// Defining result type causes the crash
export const f = (): Type => null;
// This would work
export const f2 = () => null;
```

```bash
eslint source.js
```

**What actually happened? Please include the actual, raw output from ESLint.**
```
Cannot read property 'type' of undefined
TypeError: Cannot read property 'type' of undefined
    at isForInRef (/Users/tgs/projects/brainly/brainly-frontend/node_modules/eslint/lib/rules/no-unused-vars.js:406:24)
    at variable.references.some.ref (/Users/tgs/projects/brainly/brainly-frontend/node_modules/eslint/lib/rules/no-unused-vars.js:443:21)
    at Array.some (<anonymous>)
    at isUsedVariable (/Users/tgs/projects/brainly/brainly-frontend/node_modules/eslint/lib/rules/no-unused-vars.js:442:40)
    at collectUnusedVariables (/Users/tgs/projects/brainly/brainly-frontend/node_modules/eslint/lib/rules/no-unused-vars.js:565:26)
    at collectUnusedVariables (/Users/tgs/projects/brainly/brainly-frontend/node_modules/eslint/lib/rules/no-unused-vars.js:572:17)
    at Program:exit (/Users/tgs/projects/brainly/brainly-frontend/node_modules/eslint/lib/rules/no-unused-vars.js:617:36)
    at listeners.(anonymous function).forEach.listener (/Users/tgs/projects/brainly/brainly-frontend/node_modules/eslint/lib/util/safe-emitter.js:47:58)
    at Array.forEach (<anonymous>)
    at Object.emit (/Users/tgs/projects/brainly/brainly-frontend/node_modules/eslint/lib/util/safe-emitter.js:47:38)
```

**It works correctly in `4.18.1`!**

**Comment by ilyavolodin** [comment] 2018-03-19 14:30
When you tested it with 4.18.1 did you use the same version of `babel-eslint`? Because the last change to no-unused-vars rule (the one that's failing), was done in 4.18.0, so if that change is the cause of the issue, 4.18.1 should also be failing as well.

**Comment by not-an-aardvark** [comment] 2018-03-19 14:36
@ilyavolodin If I had to guess, this was caised by the refactoring in core that wemt into 4.18.2. It might have changed something about how scope analysis is resolved.

**Comment by platinumazure** [comment] 2018-03-19 14:44
Incidentally, this seems to be the same error that redux is showing in eslint-canary.

I'm going to do a quick bisect to try to learn more.

**Comment by platinumazure** [comment] 2018-03-19 15:43
@tomasz-sodzawiczny I can't reproduce on my machine. Am I doing something wrong?

I created a subdirectory in the eslint repo and created these files:

* .eslintrc.json (N.B. `root: true` is to avoid pulling in ancestor eslint config files and should not affect test):
  ```json
  {
      "parser": "babel-eslint",
      "rules": {
          "no-unused-vars": "error"
      },
      "root": true
  }
  ```
* file.js:
  ```js
  // @flow
  
  type Type = null;
  
  export const f = (): Type => null;
  ```
* test.sh:
  ```bash
  #!/bin/bash
  
  echo "Running npm install..."
  npm install --quiet
  
  echo "Installing babel-eslint..."
  npm install babel-eslint@8.2.2 --quiet
  
  echo "Linting the test file..."
  
  if node ../bin/eslint.js ./file.js; then
      echo "Linting successful!"
  else
      echo "Linting failed!"
  fi
  ```

The last is intended to be a script for bisecting, run after checking out a commit. I've run it on both latest master and on the v4.18.2 tag, with the expectation that linting should fail/crash. Just in case my bash skills are rusty, I've also run ESLint directly, outside the script (using the same `node ../bin/eslint.js ./file.js` input) and also saw no linting errors in both latest master and v4.18.2 tag.

Have I missed something?

**Comment by not-an-aardvark** [comment] 2018-03-19 16:37
> Incidentally, this seems to be the same error that redux is showing in eslint-canary.

This is also the error that was occurring in https://github.com/eslint/eslint/issues/9762 (where scope analysis with `babel-eslint` was incorrect when we added the ability to use custom scope analysis). However, aside from this issue I'm not aware of a case where this occurs when using the latest version of `babel-eslint`.

**Comment by tomasz-sodzawiczny** [comment] 2018-03-19 16:57
@platinumazure @not-an-aardvark Ugh, OK, I tried to reproduce that in an isolated setup and I found the issue - it's not with eslint, it's problem with yarn workspaces, false alarm.

In case some has the same thing: it seems when using yarn workspaces eslint binary might run against a different `babel-eslint` than the one defined in your package. Yuck.

Sorry I wasted your time. :(

**Comment by platinumazure** [comment] 2018-03-19 18:03
I've created #10100 to add some extra debugging output that might come in handy in similar situations in the future.

**Comment by not-an-aardvark** [comment] 2018-03-19 21:52
Closing this issue since it turned out to not be a bug. Thanks for the report regardless -- I think we have room for improvement in helping the user debug this type of issue.

**Closed by not-an-aardvark** 2018-03-19 21:52 UTC
Labels: bug, core, evaluating
