### ISSUE TITLE
Error in valid-jsdoc.js

### ISSUE THREAD

**Issue by readme42** [eslint/eslint#2270] opened 2015-04-09 15:41 UTC
```
TypeError: Cannot call method 'indexOf' of undefined
    at C:\Users\Cornelius\Documents\GitHub\red\node_modules\eslint\lib\rules\valid-jsdoc.js:107:45
```

Kind regards, 
Cornelius

**Comment by nzakas** [comment] 2015-04-09 16:04
Thanks file filing an issue. In order to investigate, we will need the following information:

1. What version of ESLint are you using?
2. What source code are you linting? Please give exact code if possible.
3. How do you have this rule configured?

**Comment by lo1tuma** [comment] 2015-04-09 18:58
4.Do you use the default parser?

**Comment by readme42** [comment] 2015-04-10 06:57
1. ESLint 10.0.0
2. This obviously incorrect comment should reproduce the exception
```javascript
        /**
         * @param fields [Array]
         */
        function crashIt() {
            return "";
        }
```
3. "valid-jsdoc": 1,
4. yes

**Comment by readme42** [comment] 2015-04-24 15:56
To give it an update, it still exists in 0.19.0

**Comment by nzakas** [comment] 2015-04-24 16:41
Yup, the issue is still open so it hasn't been dealt with yet.

**Comment by gyandeeps** [comment] 2015-05-17 19:43
I think this syntax is incorrect, with that being said It should flag as an syntax error rather than error out. After investigating more I found out the library `doctrine` doesnt thow an syntax error.
I have opened an issue with them asking the question here : https://github.com/Constellation/doctrine/issues/106
If they fix this on their side (ideally they should) then we dont need to make any change, if not then we need to handle this.

**Comment by nzakas** [comment] 2015-05-18 01:18
It's not a syntax error - that's valid JSDoc (the type is not required). This is a bug in our rule that should be fixed.

**Comment by gyandeeps** [comment] 2015-05-18 01:21
but its an syntax error if you do the same for `returns` tag.
That's why I thought this might be a bad syntax.

**Comment by nzakas** [comment] 2015-05-18 01:36
I'm not sure about `returns`, but I know `param` definitely doesn't require a type. We are probably throwing an error because we are assuming a type will be there.

**Comment by gyandeeps** [comment] 2015-05-18 01:43
what should be expected when this rule is applied on this code (for sure the rule code should not error)

```js
        /**
         * @param fields [Array]
         */
        function crashIt() {
            return "";
        }
```

**Comment by nzakas** [comment] 2015-05-18 16:06
Ah, yeah, that's definitely a parser bug.

**Comment by andreas-marschke** [comment] 2015-07-13 10:21
Problem appears when tag.name hasn't been parsed by `doctrine` fix is in the PR #2983

**Comment by gyandeeps** [comment] 2015-08-27 20:38
@Constellation any feedback here?

**Comment by nzakas** [comment] 2015-09-21 19:48
Can someone check this with Doctrine 0.7.0?

**Comment by gyandeeps** [comment] 2015-09-22 02:00
for the code:
```js
        /**
         * @param fields [Array]
         */
        function crashIt() {
            return "";
        }
```

The rule code doesnt crashes and it gives out warning as expected.

**Closed** 2015-09-22 16:03 UTC
Labels: accepted, bug, rule
