### ISSUE TITLE
TypeError: Cannot read property 'type' of undefined

### ISSUE THREAD

**Issue by feross** [eslint/eslint#5662] opened 2016-03-24 08:02 UTC
**What version of ESLint are you using?** 2.4.0

**What parser (default, Babel-ESLint, etc.) are you using?** default

**Please show your full configuration:** 

```json
{
  "no-useless-constructor": 2
}
```

**What did you do? Please include the actual source code causing the issue.**

```js
class MyClass extends Error {
  constructor () {
    this.n = 0
  }
}
```

**What did you expect to happen?**

Eslint should not crash.

**What actually happened? Please include the actual, raw output from ESLint.**

Crashed with this error:

```
TypeError: Cannot read property 'type' of undefined
    at isRedundantSuperCall (/Users/feross/code/standard-stuff/standard/node_modules/eslint/lib/rules/no-useless-constructor.js:24:38)
    at EventEmitter.checkForConstructor (/Users/feross/code/standard-stuff/standard/node_modules/eslint/lib/rules/no-useless-constructor.js:79:46)
    at emitOne (events.js:82:20)
    at EventEmitter.emit (events.js:169:7)
    at NodeEventGenerator.enterNode (/Users/feross/code/standard-stuff/standard/node_modules/eslint/lib/util/node-event-generator.js:42:22)
    at CodePathAnalyzer.enterNode (/Users/feross/code/standard-stuff/standard/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:591:23)
    at CommentEventGenerator.enterNode (/Users/feross/code/standard-stuff/standard/node_modules/eslint/lib/util/comment-event-generator.js:98:23)
    at Controller.traverser.traverse.enter (/Users/feross/code/standard-stuff/standard/node_modules/eslint/lib/eslint.js:843:36)
    at Controller.__execute (/Users/feross/code/standard-stuff/standard/node_modules/eslint/node_modules/estraverse/estraverse.js:397:31)
    at Controller.traverse (/Users/feross/code/standard-stuff/standard/node_modules/eslint/node_modules/estraverse/estraverse.js:501:28)
```

**Comment by mysticatea** [comment] 2016-03-24 08:08
Thank you for this issue.

I believe this is a duplicate of #5573.
This has been fixed on master.

**Closed by mysticatea** 2016-03-24 08:08 UTC
Labels: bug, duplicate, rule

**Comment by feross** [comment] 2016-03-24 08:11
@mysticatea Thank you.
