### ISSUE TITLE
Cannot read property 'type' of undefined: looksLikeExport

### ISSUE THREAD

**Issue by honorabel** [eslint/eslint#9297] opened 2017-09-13 15:48 UTC
**Tell us about your environment**

* **ESLint Version:** 4.5.0 (tried with 4.6.* as well)
* **Node Version:** 6.10.0
* **npm Version:** 3.10.10

**What parser (default, Babel-ESLint, etc.) are you using?**
babel-eslint

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
{
    "rules": {
        "block-scoped-var": "error",
        "block-spacing": "error",
        "camelcase": ["error", {"properties": "never"}],
        "comma-dangle": ["error", "always-multiline"],
        "curly": "error",
        "dot-location": ["error", "property"],
        "indent": "off",
        "indent-legacy": ["error", 4, {"SwitchCase": 1}],
        "init-declarations": ["error", "always"],
        "jsx-quotes": ["error", "prefer-double"],
        "keyword-spacing": ["error", {"before": true, "after": true}],
        "linebreak-style": ["error", "unix"],
        "max-len": ["error", 100, 4],
        "no-alert": "error",
        "no-caller": "error",
        "no-console": 0,
        "no-const-assign": "error",
        "no-delete-var": "error",
        "no-empty-pattern": "error",
        "no-eval": "error",
        "no-lonely-if": "error",
        "no-loop-func": "error",
        "no-multi-spaces": "error",
        "no-multiple-empty-lines": ["error", {"max": 1}],
        "no-nested-ternary": "error",
        "no-new": "error",
        "no-new-wrappers": "error",
        "no-redeclare": "error",
        "no-script-url": "error",
        "no-self-compare": "error",
        "no-sequences": "error",
        "no-shadow": "error",
        "no-spaced-func": "error",
        "no-trailing-spaces": "error",
        "no-undef-init": "error",
        "no-unneeded-ternary": ["error", {"defaultAssignment": false}],
        "no-unused-vars": ["error", {"vars": "all", "args": "none"}],
        "no-var": "error",
        "no-with": "error",
        "object-shorthand": ["error", "methods"],
        "padded-blocks": ["error", "never"],
        "prefer-const": "error",
        "quotes": ["error", "single"],
        "radix": "error",
        "react/jsx-boolean-value": ["error", "always"],
        "react/jsx-closing-bracket-location": ["error", {"location": "after-props"}],
        "react/jsx-curly-spacing": "error",
        "react/jsx-equals-spacing": "error",
        "react/jsx-no-bind": ["error", {
            "allowArrowFunctions": true
        }],
        "react/jsx-no-duplicate-props": "error",
        "react/jsx-no-undef": "error",
        "react/jsx-tag-spacing": "error",
        "react/jsx-uses-react": "error",
        "react/jsx-uses-vars": "error",
        "react/no-danger": "error",
        "react/no-deprecated": "error",
        "react/no-did-update-set-state": "error",
        "react/no-direct-mutation-state": "error",
        "react/no-redundant-should-component-update": "error",
        "react/no-typos": "error",
        "react/no-unknown-property": "error",
        "react/no-unused-prop-types": "error",
        "react/no-unused-state": "error",
        "react/prefer-es6-class": ["error", "always"],
        "react/prop-types": "error",
        "react/react-in-jsx-scope": "error",
        "react/require-render-return": "error",
        "react/self-closing-comp": "error",
        "require-await": "error",
        "semi": ["error", "always"],
        "semi-spacing": ["error", {"before": false, "after": true}],
        "space-before-function-paren": ["error", {
            "anonymous": "never",
            "named": "never",
            "asyncArrow": "always"
        }],
        "space-in-parens": "error",
        "space-infix-ops": "error",
        "space-unary-ops": "error",
        "spaced-comment": "error"
    },
    "env": {
        "es6": true,
        "browser": true,
        "mocha": true
    },
    "extends": "eslint:recommended",
    "parser": "babel-eslint",
    "parserOptions": {
        "sourceType": "module",
        "ecmaFeatures": {
            "experimentalObjectRestSpread": true,
            "jsx": true,
            "classes": true
        }
    },
    "plugins": [
        "react"
    ],
    "globals": {
        "Stripe": true,
        "assert": true,
        "expect": true,
        "global": true,
        "google": true,
        "module": true,
        "sinon": true,
        "chai": true,
        "process": true
    },
    "root": true
}
```

</details>

**What did you expect to happen?**
Successful lint, or for it to output lint errors

**What actually happened? Please include the actual, raw output from ESLint.**
```
Cannot read property 'type' of undefined
TypeError: Cannot read property 'type' of undefined
    at looksLikeExport (/Users/abelallison/Workspace/honor/external-web/node_modules/eslint/lib/util/source-code.js:78:19)
    at SourceCode.getJSDocComment (/Users/abelallison/Workspace/honor/external-web/node_modules/eslint/lib/util/source-code.js:311:21)
    at Object.isExplicitComponent (/Users/abelallison/Workspace/honor/external-web/node_modules/eslint-plugin-react/lib/util/Components.js:218:34)
    at Object.isES6Component (/Users/abelallison/Workspace/honor/external-web/node_modules/eslint-plugin-react/lib/util/Components.js:201:17)
    at Linter.MemberExpression (/Users/abelallison/Workspace/honor/external-web/node_modules/eslint-plugin-react/lib/rules/no-typos.js:73:18)
    at emitOne (events.js:101:20)
    at Linter.emit (events.js:188:7)
    at NodeEventGenerator.applySelector (/Users/abelallison/Workspace/honor/external-web/node_modules/eslint/lib/util/node-event-generator.js:265:26)
    at NodeEventGenerator.applySelectors (/Users/abelallison/Workspace/honor/external-web/node_modules/eslint/lib/util/node-event-generator.js:294:22)
    at NodeEventGenerator.enterNode (/Users/abelallison/Workspace/honor/external-web/node_modules/eslint/lib/util/node-event-generator.js:308:14)
    at CodePathAnalyzer.enterNode (/Users/abelallison/Workspace/honor/external-web/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:602:23)
    at Traverser.enter (/Users/abelallison/Workspace/honor/external-web/node_modules/eslint/lib/linter.js:925:36)
```

**Comment by honorabel** [comment] 2017-09-13 16:03
Solved my issue.  My file had a few functions defined, followed by a class definition.  One or two of the functions were calling a static method of the class.  Moving the class definition above that of the functions solved the error.

**Comment by not-an-aardvark** [comment] 2017-09-13 16:09
Thanks for the report. As you mentioned, I think this is a duplicate of https://github.com/eslint/eslint/issues/9101.

**Closed by not-an-aardvark** 2017-09-13 16:09 UTC
Labels: triage
