### ISSUE TITLE
prefer-template rule adds unnecessary spaces when using --fix

### ISSUE THREAD

**Issue by lanmonster** [eslint/eslint#8967] opened 2017-07-19 18:50 UTC
**Tell us about your environment**

* **ESLint Version:** 4.2.0
* **Node Version:** 6.11.0
* **npm Version:** 5.3.0

**What parser (default, Babel-ESLint, etc.) are you using?**
default

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
{
    "env": {
        "es6": true
    },
    "rules": {
        "prefer-template": "error"
    }
}
```

</details>

**What did you do? Please include the actual source code causing the issue.**
I wrote the code below, and then ran `eslint **/*.js --fix`

```js
function foo (bar, baz, blah) {
    return foo + ' test ' + bar + ' test ' + blah;
}
```

**What did you expect to happen?**
```js
function foo (bar, baz, blah) {
    return `${foo} test ${bar} test ${blah}`;
}
```
**What actually happened? Please include the actual, raw output from ESLint.**
```js
function foo (bar, baz, blah) {
    return `${foo  } test ${  bar  } test ${  blah}`;
}
```

**Comment by not-an-aardvark** [comment] 2017-07-19 18:54
Closing as a duplicate of https://github.com/eslint/eslint/issues/8520

**Closed by not-an-aardvark** 2017-07-19 18:54 UTC
Labels: triage
