### ISSUE TITLE
Broken flatTernaryExpressions when conditions and values on alternating lines

### ISSUE THREAD

**Issue by hleumas** [eslint/eslint#11437] opened 2019-02-25 02:49 UTC
**Tell us about your environment**

* **ESLint Version: 5.14.1**

```js
conditionA
  ? valueC
  : conditionB
  ? valueA
  : valueB
```

**What did you expect to happen?**
I would expect this to be valid indenting with `flatTernaryExpressions`, but it's not.
Eric Eliot uses it too:
https://medium.com/javascript-scene/nested-ternaries-are-great-361bddd0f340

**Are you willing to submit a pull request to fix this bug?**
No.

**Comment by mysticatea** [comment] 2019-02-25 03:28
Thank you for this issue.

However, this is a duplicate of #11397.

> By design, `flatTernaryExpressions:true` option affects only when a condition and that result are on the same line. I.e.
> 
> ```js
> var a =
>   foo ? bar :
>   baz ? qux :
>   boop
> ```
> 
> The option is to support the style like [Conditional Types](https://www.typescriptlang.org/docs/handbook/advanced-types.html#conditional-types).
> 
> ```ts
> type TypeName<T> =
>     T extends string ? "string" :
>     T extends number ? "number" :
>     T extends boolean ? "boolean" :
>     T extends undefined ? "undefined" :
>     T extends Function ? "function" :
>     "object";
> ```

**Closed by mysticatea** 2019-02-25 03:28 UTC
Labels: bug, triage

**Comment by hleumas** [comment] 2019-02-25 03:37
Thank you and sorry for creating a duplicate issue.
