### ISSUE TITLE
Forbid properties assignment when these are not declared in the class constructor

### ISSUE THREAD

**Issue by eTorAken** [eslint/eslint#8538] opened 2017-05-03 15:24 UTC
**Please describe what the rule should do:**
It should forbid to assign properties with a static identifier to `this` if they did not have been assigned in the class constructor.

**What category of rule is this? (place an "X" next to just one item)**
[ ] Enforces code style
[ ] Warns about a potential error
[ ] Suggests an alternate way of doing something
[X] Other (please specify:) Performance mostly: this bad habit cause object reshaping which is not recommanded for V8 optimization and CPU usage.

**Provide 2-3 code examples that this rule will warn about:**
 ```jsx
class myClass {
  constructor() {
    this.myDeclaredProp = null;
  }

  myClassMethod {
    this.myDeclaredProp = 'I can change that'; // => ok
    this.myUndeclaredProp = 'This breaks V8 fast-path'; // => error
  }
};
```
 ```jsx
class myClass {
  constructor() {
    this.myDeclaredProp = {};
  }

  myClassMethod {
    this.myDeclaredProp.itsSubProp = 'I can change that'; // => ok
    this.myUndeclaredProp = 'This breaks V8 fast-path'; // => error
  }
};
```

**Why should this rule be included in ESLint (instead of a plugin)?**
Really I don't know. I think all JavaScript core features and understandings (even performance issues) should be in native ESLint.

**Comment by platinumazure** [comment] 2017-05-03 15:29
Hi @eTorAken, thanks for the issue.

I can get behind this for both performance reasons (as you have cited) and readability (always good to have one place to look for declarations, where possible). I'll :+1: this, but we'll see what the rest of the team thinks.

If the team decides this should not be a core rule, I would encourage finding or creating a plugin for this rule-- it does seem pretty useful!

**Comment by eTorAken** [comment] 2017-05-03 15:40
Thanks @platinumazure, I look forward your team's decision.

**Comment by not-an-aardvark** [comment] 2017-05-03 16:44
I like this idea, but it's worth noting that it could have false positives:

```js
class Foo {
  constructor(options) {
    Object.assign(this, { foo: 1 }, options);
  }
  bar() {
    // an error will be reported here, even though
    // the foo property was assigned in the constructor
    this.foo;
  }
}
```

**Comment by not-an-aardvark** [comment] 2017-11-03 20:58
Thanks for your interest in improving ESLint. Unfortunately, it looks like this issue didn't get consensus from the team, so I'm closing it. We define [consensus](http://eslint.org/docs/maintainer-guide/issues.html#consensus) as having three :+1:s from team members, as well as a team member willing to champion the proposal. This is a high bar by design -- we can't realistically accept and maintain every feature request in the long term, so we only accept feature requests which are useful enough that there is consensus among the team that they're worth adding.

Since ESLint is pluggable and can load custom rules at runtime, the lack of consensus among the ESLint team doesn't need to be a blocker for you using this in your project, if you'd find it useful. It just means that you would need to [implement the rule](http://eslint.org/docs/developer-guide/working-with-rules) yourself, rather than using a bundled rule that is packaged with ESLint.

**Closed by not-an-aardvark** 2017-11-03 20:58 UTC
Labels: evaluating, feature, rule
