### ISSUE TITLE
require-jsdoc rule should enforce JSDoc on exported (public) API

### ISSUE THREAD

**Issue by AMorgaut** [eslint/eslint#9708] opened 2017-12-11 12:12 UTC
**What version are you using?**

4.13

**What did you do?**

Looked at the [require-jsdoc](https://eslint.org/docs/rules/require-jsdoc) documentation & code

**What happened?**

Didn't found any distinction between private & public API

**What did you expect to happen?**

I expected to be able to configure "require-jsdoc" for mandatory documentation on public API
Where public API would be identified as:
- **ES6** exported API via the "[export](https://developer.mozilla.org/en-US/docs/web/javascript/reference/statements/export)" statement
- **CommonJS** / **node.js** exported API via "exports" ([CJS](http://wiki.commonjs.org/wiki/Modules/1.1.1#Module_Context), [node](https://nodejs.org/api/modules.html#modules_exports_shortcut))
- **node.js** exported API via "[module.exports](https://nodejs.org/api/modules.html#modules_module_exports)"
- **AMD** exported API via ["define" factory](https://github.com/amdjs/amdjs-api/blob/master/AMD.md#user-content-factory-)

If a class or an object is exported, I would expect at least all their methods to be documented, and at best with their properties and events

So, the *second option* I would have expected is "**with-properties**" (default false)

The third option I would have expected is "**with-privates**" (default false)
Making distinction between public & private properties/methods based on convention patterns (start with "_") where such pattern could be customized (ex: "with-private": "__{2}.*")

*I started a implementation for the ES6 modules export support* that I may push as a pull request soon
It is the easiest one, and it is done without breaking change by adding a "publicAPI" boolean option
It could be a first step.
I may then work on nodejs "exports" API support. I have few ideas but for sure the rule implementation would become more complex.

If you want to keep this rule as is, it might be implemented via another rule (ex: "require-public-api-jsdoc")
but
1. it is really what I initially expected for "require-jsdoc"
2. **Current options are really not useful as is in real project** ("FunctionDeclaration", "ClassDeclaration", "MethodDefinition", "ArrowFunctionExpression", "FunctionExpression"). They are just an easy technical filters, but project rarely need documentation based on such type.

**Comment by platinumazure** [comment] 2017-12-11 23:49
I'd be curious to see if there would be interest for being able to iterate over "public API functions" (using the definitions above) and enforce more than just JSDoc requirements on them.

@AMorgaut You might be able to implement this now as a custom rule by creating a rule in [`eslint-rule-composer`](https://github.com/not-an-aardvark/eslint-rule-composer) which takes the require-jsdoc rule (with all possible warnings enabled) and then filters the error messages by whether or not the JSDoc comments in question are attached to a "public API function".

**Comment by AMorgaut** [comment] 2017-12-12 20:29
@platinumazure 

My company has its own SDK for which it is mandatory to provide an API documentation.
Everything its modules expose is by definition part of the public API

Current filters are not usable as is for us.
We have legacy modules which methods are written as function expressions. This is the worst situation ever as if we activate the 'FunctionExpression' option, it requires to provide JSDoc comments for callbacks... (the project migrated to ES6 modules but doesn't yet handle arrow functions)

Of course it's hard to find the perfect criteria and I'm open to listen any other potential consensus or option :-)

Still I think it can fit with many npm packages which, with the right JSDoc, could provide even better hints from IDEs.

**Comment by not-an-aardvark** [comment] 2018-01-19 15:59
Thanks for your interest in improving ESLint. Unfortunately, it looks like this issue didn't get consensus from the team, so I'm closing it. We define [consensus](http://eslint.org/docs/maintainer-guide/issues.html#consensus) as having three :+1:s from team members, as well as a team member willing to champion the proposal. This is a high bar by design -- we can't realistically accept and maintain every feature request in the long term, so we only accept feature requests which are useful enough that there is consensus among the team that they're worth adding.

Since ESLint is pluggable and can load custom rules at runtime, the lack of consensus among the ESLint team doesn't need to be a blocker for you using this in your project, if you'd find it useful. It just means that you would need to [implement the rule](http://eslint.org/docs/developer-guide/working-with-rules) yourself, rather than using a bundled rule that is packaged with ESLint.

**Closed by not-an-aardvark** 2018-01-19 15:59 UTC
Labels: enhancement, evaluating, rule
