### ISSUE TITLE
one-var rule doesn't work properly with separateRequires and const

### ISSUE THREAD

**Issue by korneliakobiela** [eslint/eslint#11312] opened 2019-01-24 07:09 UTC
**Tell us about your environment** 

* **ESLint Version:** 5.12.1
* **Node Version:** v10.15.0
* **npm Version:** 6.5.0
* **operating system:** Ubuntu 18.04

**What parser (default, Babel-ESLint, etc.) are you using?** default

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```json
{
    "env": {
        "browser": true,
        "commonjs": true,
        "es6": true,
        "node": true
    },
    "extends": "eslint:recommended",
    "parserOptions": {
        "ecmaVersion": 2018
    },
    "rules": {
        "indent": [
            "error",
            4
        ],
        "linebreak-style": [
            "error",
            "unix"
        ],
        "quotes": [
            "error",
            "single"
        ],
        "semi": [
            "error",
            "always"
        ],
        "no-var": "error",
        "one-var": [
            "error",
            {
                "separateRequires": true,
                "const": "always"
            }
        ]   
    }
}
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**
I would like to attach my [Gitlab repo](https://gitlab.com/korneliakobiela/eslint-one-var-demo) with some demo about this issue.

```js
const path = require('path');
const fs = require('fs');

fs.readFile(path.join(__dirname, 'package.json'), 'utf8', (err, data) => {
    if (err) {
        throw err;
    }
    const welcome = 'Hello';
    const devDependencies = JSON.parse(data).devDependencies;

    for (const dependency in devDependencies.devDependencies) {
        if (devDependencies.hasOwnProperty(dependency)) {
            const element = devDependencies[dependency];
            /* eslint-disable no-alert, no-console */
            console.log(`${welcome}, ${element}!`);
        }
    }
    
});
```

```bash
 ./node_modules/.bin/eslint index.js
```

**What did you expect to happen?**
One problem (error) into the eslint output

` 9:5  error  Combine this with the previous 'const' statement  one-var `
**What actually happened? Please include the actual, raw output from ESLint.**
```
/home/kornelia/test/index.js
  2:1  error  Combine this with the previous 'const' statement  one-var
  9:5  error  Combine this with the previous 'const' statement  one-var

✖ 2 problems (2 errors, 0 warnings)
  2 errors and 0 warnings potentially fixable with the `--fix` option.
```

**Are you willing to submit a pull request to fix this bug?**
Yes, but I am not even started coding it :)

**Comment by g-plane** [comment] 2019-01-24 07:44
Duplicate of #10179

**Closed by g-plane** 2019-01-24 07:44 UTC
Labels: bug, triage
