### ISSUE TITLE
no-unused-vars works incorrectly with rested arrays 

### ISSUE THREAD

**Issue by deser** [eslint/eslint#10788] opened 2018-08-22 13:33 UTC
![image](https://user-images.githubusercontent.com/3010698/44466432-f38ff280-a628-11e8-9b21-39805c8a2b77.png)

First item is unused, I cant' skip it. Rule `after-used` should be applied here I believe

Eslint version: 4.5.0

**Comment by ilyavolodin** [comment] 2018-08-22 14:09
You can skip it by doing:
```
const [, idMaps] = changeScreenLikeItemsId(screen);
```

This is working as intended.

**Comment by deser** [comment] 2018-08-22 14:20
Btw, wouldn't sparce array rule blame that?

**Comment by ilyavolodin** [comment] 2018-08-22 15:29
Left-hand side is not an array. It's a spread, so `no-sparse-arrays` will not flag it.

**Comment by kaicataldo** [comment] 2018-08-31 14:59
Just a quick clarification: the left-hand side is actually a destructuring assignment, not a spread.

**Comment by kaicataldo** [comment] 2018-08-31 14:59
Closing this issue as it looks like the question has been answered. Please feel free to visit us in the [ESLint Gitter](https://gitter.im/eslint/eslint) if you have any other issues!

**Closed by kaicataldo** 2018-08-31 14:59 UTC
Labels: question, rule, works as intended
