### ISSUE TITLE
Decouple eslint from debug

### ISSUE THREAD

**Issue by Download** [eslint/eslint#13876] opened 2020-11-23 08:21 UTC
**The version of ESLint you are using.**
Latest

**The problem you want to solve.**
Eliminate high coupling to `debug`

**Your take on the correct solution to problem.**
Implement logging via a facade

**Are you willing to submit a pull request to implement this change?**
Yes

### Subject of the feature

Reduce coupling and footprint of minified file by using `anylogger` i.s.o `debug`

### Problem

Currently, this library has [a dependency](https://github.com/eslint/eslint/blob/v7.14.0/package.json#L54) on [`debug`](https://npmjs.com/package/debug). Though that is an excellent library, this dependency has 2 major drawbacks:

* This library is now forcing `debug` onto all developers that use this library (high coupling)
* `debug` is 3.1kB minified and gzipped, directly adding 3.1kB to the minimum footprint of this library

### Alternatives

Please have a look at [`anylogger`](https://npmjs.com/package/anylogger). It's a logging facade specifically designed for libraries. It achieves these goals:

* Decouple the library from the underlying logging framework
* Reduce the minimal bundle footprint. Anylogger is only 370 bytes.

The decoupling is achieved by only including the minimal facade to allow client code to do logging and using adapters to back that facade with an actual logging framework. The minimal footprint follows naturally from this decoupling as the bulk of the code lives in the adapter or logging library.

There are already adapters for some popular logging frameworks and more adapters can easily be created:

* [`anylogger-console`](https://npmjs.com/package/anylogger-console) (to use the console i.s.o some logging framework)
* [`anylogger-debug`](https://npmjs.com/package/anylogger-debug)
* [`anylogger-loglevel`](https://npmjs.com/package/anylogger-loglevel)
* [`anylogger-log4js`](https://npmjs.com/package/anylogger-log4js)
* [`ulog`](https://npmjs.com/package/ulog) (logger with native anylogger support)

If this library were to switch to `anylogger`, you could still install `debug` as a dev-dependency and then `require('anylogger-debug')` in your tests to have your tests work exactly as they always did, with `debug` as the logging framework, while still decoupling it from `debug` for all clients.

> *Disclaimer*: `anylogger` was written by me so I'm self-advertising here. However I do honestly believe it is the best solution in this situation and `anylogger` was written specifically to decrease coupling between libraries and logging frameworks because for any large application, devs typically end up with multiple loggers in their application because some libraries depend on `debug`, others on `loglevel`, yet others on `log4js` and so on. This hurts bundle size badly as we add multiple kB of logging libraries to it.

**Comment by nzakas** [comment] 2020-11-27 18:12
Thanks for the suggestion. We don't just use `debug` in development, it's also used to support the `--debug` flag to help users figure out the root cause of problems they're having. So, one way or another we'd still end up with the `debug` package being installed for end users.

So at the moment, I'm not seeing a big advantage to making a switch. Is there something else I'm missing?

**Comment by Download** [comment] 2020-12-03 14:37
The `--debug` flag is part of the CLI right? 
I think the library part should be decoupled. The CLI is an application of it's own and coupling with a logger is ok I think.

The way I look at it is this. Most code doing logging is just generic log client code that calls e.g. `debug('message')` or `log.info(`message`)` or something. And then some much more rare code will do some config stuff, like maybe call `debug.enable('logger')`. It pays off to decouple the normal log client code from any specific logger. This allows this code to be used with other loggers than `debug` seamlessly. That's what `anylogger` is about: allowing libraries to decouple from any specific logger and allow them to be used with any logger, including `debug`. I would think you do something like call `debug.enable()` in your CLI code. But most probably in most other files you will just be doing `debug('message')`. So that code can be decoupled easily. And then other projects using the eslint library (but not necesarily the CLI) could choose a different logger and the eslint code would just use that.

Maybe I could prepare a draft PR of how I would go about decoupling eslint from `debug` as much as possible without actually changing any functionality it currently has? So you can have a look at it?

**Comment by btmills** [comment] 2020-12-09 05:56
`anylogger` looks like any elegant library, nice work on it! However, I think it's overkill for our current situation. We haven't had any user requests to decouple `debug`, so for now that's one less moving part to maintain. If we do start getting those requests in the future, then `anylogger` looks like a strong solution.

**Comment by Download** [comment] 2020-12-09 10:02
@btmills Thank you, much appreciated!
And yes I see why you don't want to fix something that isn't broken :)

**Comment by nzakas** [comment] 2020-12-11 01:20
Thanks for the discussion. We won’t be moving forward with this, so closing.

**Closed by nzakas** 2020-12-11 01:20 UTC
Labels: core, enhancement, evaluating
