### ISSUE TITLE
Cannot catch unused params in the function

### ISSUE THREAD

**Issue by eLeontev** [eslint/eslint#10063] opened 2018-03-06 10:40 UTC
environment:
eslint: 4.18.2
lint-cinfig: default, recommended, es6
node: 8.1.3

lint doensn't catch unused variable which is passed like an argument into the function which doesn't handled arguments.

expected result: variable (userName) which is passed in the function but not used in its should be mark as unused variable

See the screen for more detailes.

![lint](https://user-images.githubusercontent.com/15786916/37027752-474a2672-2143-11e8-8873-a3fee72cadb2.JPG)

**Comment by ljharb** [comment] 2018-03-06 19:59
The variable is "used" though; the only time eslint could know if `getUserName` actually uses the variable is if it's in the same file, if it has no named arg in that position, and if it's either an arrow function or it doesn't reference `arguments`.

**Comment by not-an-aardvark** [comment] 2018-03-06 22:07
Thanks for the report. As @ljharb described, this is working as intended.

(That said, it seems like it could be useful to have a rule to lint for passing the wrong number of arguments to a locally-declared function.)

**Comment by eLeontev** [comment] 2018-03-07 09:18
Does it mean that this rule may be implemented in the future releases?

**Comment by not-an-aardvark** [comment] 2018-03-25 23:59
Closing because this is working as intended.

@eLeontev It's a possibility, but if this is something you'd like to see added, I would recommend creating a separate issue for it.

**Closed by not-an-aardvark** 2018-03-25 23:59 UTC
Labels: works as intended
