### ISSUE TITLE
eslint not detecting no-undef if variable name is 'name'

### ISSUE THREAD

**Issue by yinonby** [eslint/eslint#14113] opened 2021-02-14 12:39 UTC
**Tell us about your environment**

* **ESLint Version:**
* **Node Version:**
* **npm Version:**

**What parser (default, `@babel/eslint-parser`, `@typescript-eslint/parser`, etc.) are you using?**

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js

```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js

```

```bash

```

**What did you expect to happen?**

**What actually happened? Please include the actual, raw output from ESLint.**

**Comment by mdjermanovic** [comment] 2021-02-14 19:49
By the title, this looks like a duplicate of https://github.com/eslint/eslint/issues/14114.

**Closed by mdjermanovic** 2021-02-14 19:49 UTC
Labels: triage
