### ISSUE TITLE
Add option to --init for shareable configs

### ISSUE THREAD

**Issue by jsejcksn** [eslint/eslint#7488] opened 2016-10-30 12:15 UTC
**What version are you using?** 3.9.0

**What did you do?** Try to add an already installed shareable config after installing (during `--init`)

**What happened?** I couldn't

**What did you expect to happen?** To be able to

Here's more detail:

I mainly use ESLint with the [linter-eslint Atom plugin](https://atom.io/packages/linter-eslint), and I created a shareable config so I wouldn't have to manually sort that part out for each new project. So now I just run `$ npm install eslint @jsejcksn/eslint-config --save-dev` in the beginning, but I still need a `.eslintrc.*` file, which I have to create manually. Right? Am I missing something?

It seems natural that after running `./node_modules/.bin/eslint --init`, one of the main menu options should be to specify an already installed shareable config (and not just "the most popular ones")—in my case, I would enter `@jsejcksn`. (I couldn't find this in the docs, but I did find [this comment](https://github.com/eslint/eslint/issues/3123#issuecomment-123752646) in an issue.

And that would produce the `.eslintrc.*` file with the following:

``` json
{ "extends": "@jsejcksn" }
```

I am still pretty new to ESLint, so maybe I am missing an easier option that doesn't require copying from another project or manually creating my `.eslintrc.json` file myself in order to have ESLint use my shareable config.

**Comment by nzakas** [comment] 2016-10-30 16:43
That's an interesting idea. We really only intended `--init` to be used by people without prior ESLint experience with the thinking that more experienced users would probably just copy-paste their config over. That said, I'm not opposed to this.

How would you envision it working? 

(FWIW, I'm not sure we can really show a list of installed shareable configs because there's no guaranteed location where shareable configs are installed nor do we have any transparency into whether or not the shareable config package contains multiple configs.)

**Comment by jsejcksn** [comment] 2016-11-03 04:48
@nzakas As I said before, I'm new to ESLint, so I'm not exactly sure how the init process works. Originally I had thought that it would just add a shareable config that was already installed, but maybe it can download the shareable config by the npm address, just like it does for "Use a popular style guide".

The new menu entry would go below the three that are already there, and would read something like `Type the name of a shareable config to import it`. The user would select it and then be able to type the name of the shareable config on npm. For my case, I would type `@jsejcksn/eslint-config` and then press enter, and it would install the package and then create a `.eslintrc.json` file with `{ "extends": "@jsejcksn" }` as the content.

**Comment by nzakas** [comment] 2016-11-03 19:11
Gotcha. That's an interesting idea, though I'm a bit concerned that some configs require dependencies to be manually installed to work properly. We currently special case the style guides we support in `--init` so we take care of installing the extra dependencies, but we wouldn't be able to do that dynamically.

Let's see what others think.

**Comment by jsejcksn** [comment] 2016-11-04 05:05
@nzakas I didn't realize that it was a special-case implementation for the popular ones—I thought it was just automated (but with hardcoded package names). Now that I've gone back and experimented a bit, it seems that, when using `--init` with "a popular style guide", ESLint is taking the liberty of adding itself and the config's dependencies as developer dependencies in my `package.json` file. That leads me to believe that it's installing them via `$ npm install shareable-config --save-dev`. Is there documentation on how this works?

**Comment by nzakas** [comment] 2016-11-04 18:39
There's no documentation on how it works, but here's the code:
https://github.com/eslint/eslint/blob/master/lib/config/config-initializer.js#L262

**Comment by vitorbal** [comment] 2016-11-06 18:40
I think this issue could be a good enhancement after something like this is implemented: https://github.com/eslint/eslint/issues/7338#issuecomment-252931101
I actually have a branch where I almost got it to work. Only need to get to adding some more tests and fixing existing ones.

**Comment by kaicataldo** [comment] 2017-01-10 03:13
This is a really interesting idea - seems worth exploring further (maybe after https://github.com/eslint/eslint/issues/7338#issuecomment-252931101) has been finalized.

**Comment by dinoboff** [comment] 2017-02-02 12:18
eslint could add flags to skip some prompt:

- `eslint --init`: all prompt.
- `eslint --init --init-config=xo`: skip style prompt, install "eslint-config-xo" and use it as based config.
- `eslint --init --init-format=yaml`: skip format prompt and create .eslintrc.yaml.

A shortcut would be nice to: `eslint --init-with=xo,yaml`.

**Comment by not-an-aardvark** [comment] 2017-11-03 20:49
Thanks for your interest in improving ESLint. Unfortunately, it looks like this issue didn't get consensus from the team, so I'm closing it. We define [consensus](http://eslint.org/docs/maintainer-guide/issues.html#consensus) as having three :+1:s from team members, as well as a team member willing to champion the proposal. This is a high bar by design -- we can't realistically accept and maintain every feature request in the long term, so we only accept feature requests which are useful enough that there is consensus among the team that they're worth adding.

**Closed by not-an-aardvark** 2017-11-03 20:49 UTC
Labels: core, enhancement, evaluating, needs bikeshedding

**Comment by jsejcksn** [comment] 2017-11-05 20:24
I'm sad about that, but I understand because you explained it well. Thanks, @not-an-aardvark.
