### ISSUE TITLE
missing rule: validate line breaks 

### ISSUE THREAD

**Issue by feross** [eslint/eslint#1882] opened 2015-02-26 15:44 UTC
http://catatron.com/node-jscs/rules/validate-line-breaks/

**Comment by lo1tuma** [comment] 2015-02-26 15:48
Duplicate of #1255

**Comment by nzakas** [comment] 2015-02-26 15:48
Please also be sure to read our [contribution guidelines](http://eslint.org/docs/developer-guide/contributing.html) for website is expected in issue descriptions. Simply pasting in a URL is not acceptable.

**Closed by nzakas** 2015-02-26 15:48 UTC
