### ISSUE TITLE
Can't override a rule in package.json loaded from module

### ISSUE THREAD

**Issue by geuis** [eslint/eslint#9053] opened 2017-07-31 20:44 UTC
**Tell us about your environment**

* **ESLint Version:**
^4.3.0
* **Node Version:**
node v8.1.2
* **npm Version:**

**What parser (default, Babel-ESLint, etc.) are you using?**
none

**Please show your full configuration:**
```
{
  "devDependencies": {
    "eslint": "^4.3.0",
    "base-lint": "^2.0.1"
  },
  "eslintConfig": {
    "env": {
      "browser": true,
      "node": true
    },
    "rules": {
      "no-console": "off"
    }
  }
}
```

In our base-lint, we have `no-console: 2` configured.

I'm trying to override that in package.json for a particular sub project that used all of the other base configs, except the `no-console` rule isn't being overridden.

I've also tried setting the config in a local .eslintrc but still it doesn't get overridden.

**Comment by not-an-aardvark** [comment] 2017-08-01 02:44
I can't reproduce this issue. How are you using `base-lint`?

**Comment by not-an-aardvark** [comment] 2017-08-10 18:58
Closing because I couldn't reproduce the issue.

**Closed by not-an-aardvark** 2017-08-10 18:58 UTC
Labels: bug, core, evaluating
