### ISSUE TITLE
 Is no-irregular-whitespace fixable?

### ISSUE THREAD

**Issue by wottpal** [eslint/eslint#14073] opened 2021-02-06 08:23 UTC
Reopening #12846

> I recently came across an issue in VS Code.
I have no-irregular-whitespace enabled through "extends": "eslint:recommended".

> When writing functions, I often come across AltGr + Space, which results in an irregular whitespace. It is nice to get a warning about it, but I was curious if it is an issue that can be fixed automatically by this rule - meaning when found, replace the irregular whitespace character with a regular one - or there is a good reason it is not implemented?
image

> What rule do you want to change?
> no-irregular-whitespace
> Does this change cause the rule to produce more or fewer warnings?
I am not sure, I guess after fixing the problem, it will cause ESLint to produce fewer warnings.
How will the change be implemented? (New option, new default behavior, etc.)?
If I understand it correctly, one has to add a fixable property to the meta object in the Rule Definition, and probably implement some code.
Please provide some example code that this change will affect:

>function foo()/*irregular whitespace here*/{}
// after fix ->
function foo() {}
What does the rule currently do for this code?
It reports the problem, but do not fix it automatically

>What will the rule do after it's changed?
If configured, it will report AND fix the problem, meaning replacing any irregular whitespace character with a regular space character.
Are you willing to submit a pull request to implement this change?
I am afraid I don't have a knowledge by myself, but If I get some support, and it is something that CAN be fixed, I am willing/happy to try.

**Comment by mdjermanovic** [comment] 2021-02-08 11:48
Hi @wottpal, thanks for the issue!

Can you please fill out our [rule change request template](https://github.com/eslint/eslint/blob/master/.github/ISSUE_TEMPLATE/RULE_CHANGE.md)?

I think the question is do we know what would be the correct fix for each of the [irregular whitespace characters](https://eslint.org/docs/rules/no-irregular-whitespace#rule-details) that this rule disallows.

Also, the rule probably shouldn't auto-fix any characters in string literals, template literals, and regular expression literals.

**Comment by nzakas** [comment] 2021-04-08 00:53
Not enough info, so closing.

**Closed by nzakas** 2021-04-08 00:53 UTC
Labels: autofix, enhancement, needs info, rule

**Comment by tchakabam** [comment] 2021-05-24 11:13
Hi Eslint devs @nzakas & @mdjermanovic 
there is a very popular VSCode plugin that does this job. 

if the rule auto-fix would just do what this plugin does, 

I think it addresses all concerns/issues and works just fine for a lot of people already.

Should be easy to re-use the code from this plugin for writing the fixing functionality ?

**Comment by MohamedLamineAllal** [comment] 2021-05-24 12:32
There isn't much code to it! The list and regex matching can be reused! Otherwise it's about accepting making a fix for it!
I can make it! I've seen that there is a concern that not all want the irregular white spaces gone! Mainly we don't want them in code level! Except for strings! So we can add an option for the rule (it get passed in the array format)! Where string support get ignored or not! If there is other concern! One can even use directly the AST node types to exclude passed as array! In short there is no reason to not make a fix for it! Then even without exclusion options! Still it's useful to a lot of people! Rare are the one that have intended irregular white spaces on there code! I would appreciate any notes or remarks or directions! Otherwise i can make a fix pretty well! And i'm willing! I'm currently making a nodejs library for treating this! And having it part of eslint will be great for the community! And more flexible for javascript projects!

**Comment by MohamedLamineAllal** [comment] 2021-05-24 16:39
# Question

The node as per this [Line (L162)](https://github.com/eslint/eslint/blob/master/lib/rules/no-irregular-whitespace.js#L162)
Is the Program node! The whole code source node!

My question is for fixing! And the multiple run of fixes! Does that pose problems with others fixes! How are the different fixes of different rules compared to each other! Is it by Range! Or by node!
If by range then it's not a problem to apply fixes directly using fixer.replaceTextByRange()! But if it's by node! We can select the deeper node by range index (getNodeByRangeIndex();)!  As like the many other rules are use in it ([example](https://github.com/eslint/eslint/blob/master/lib/rules/no-inline-comments.js#L80))! Now Looking through the code !
I can see that the deprecation is handled for it as per [here](https://github.com/eslint/eslint/blob/master/lib/linter/linter.js#L785)! They will be always available!

**So is it ok! To just replace text by range! That will not screw other rules fixes! If not! What about the usage of sourceCode.getNodeByRangeIndex() !?**

**Comment by mdjermanovic** [comment] 2021-05-24 16:46
This issue is closed. If anyone has a concrete proposal on how this autofix should work, in particular which of the regular whitespace characters should be used as replacements for each of the irregular ones, please feel free to open a new issue (Rule change request).

**Comment by MohamedLamineAllal** [comment] 2021-05-24 17:56
@mdjermanovic 

I'm working a fix! And trying it out!

For irregular white spaces => Normal white space!

For end line delimeter => There is only two => we make it optional (meaning they can provided as a second param (first param is for skipping object)! If not provided! One can deduce it from one of the lines of the code source! Or just use the os command for the new line! I can simply implement it all!

What do you think ??
 
After it i'll fill a new issue with a proposal PR! 

Can you comment about what i said !
(i'm mostly finished with the direct fix! left for the note above! I need to know what you think!

**Comment by tchakabam** [comment] 2021-05-25 22:27
Hey @MohamedLamineAllal , i guess in this case a few lines of code will say more than a 1000 words. To be honest, I could only fly over your text, most of it was TLDR.

If I may suggest though, as an interested user of the feature and happy to guide you a bit, you probably could proceed with:

1. Submit their "Rule change request" as @mdjermanovic suggested -> https://github.com/eslint/eslint/blob/master/.github/ISSUE_TEMPLATE/RULE_CHANGE.md

2. Write a patch against the current rule code to add your auto-fix proposal, as based on what your VSCode plugin does.

Other than that, I don't think any "stand-alone" CLI tool is necessary here, if this becomes part of ESlint this way.  

But, if you feel like writing an own tool for this, why not as well. Maybe just try to address what will be most helpful to most people first, before you think too much about all the possibilities here. In this case, my guts tell me most people would want to use this via ESlint. Also, you will probably have to write less boiler-plate on your own, if you use what ESlint already has as scaffold to solve this.

Did you consider though to make this an ESlint plugin rather?

**Comment by MohamedLamineAllal** [comment] 2021-05-25 22:48
Don't worry hhh! The PR will comes soon! However a friend of mine will make it! We went for it both! We had a challenge! I completed a working version that does it well! But i'm not willing to write the tests! And may be add some extra customization! My friend too did! Will finish her work soon! She will send a PR!

Otherwise i resumed and shared the different points through the analysis of the code! Who will to try to understand or work on it! The above gonna be too helpful! Even though no need! The problem is already tackled and well! the PR will comes in a day or two!

We will create a new issue! We may extends too the options object! To be even more flexible while compatible with what's already done!
