### ISSUE TITLE
Expose true filename to rules

### ISSUE THREAD

**Issue by Conduitry** [eslint/eslint#11989] opened 2019-07-15 02:28 UTC
**The version of ESLint you are using.**

6.0.1

**The problem you want to solve.**

[This.](https://github.com/benmosher/eslint-plugin-import/issues/1415) Some rules, like eslint-plugin-import's no-unresolved, need to know the true path of the current file, not a path that's been potentially assembled using a processor's named code block.

**Your take on the correct solution to problem.**

I'm not entirely sure, but perhaps a new option to `context.getFilename()` to return the true path rather than the one potentially created from a processor's named code blocks.

**Are you willing to submit a pull request to implement this change?**

Yes.

**Comment by platinumazure** [comment] 2019-07-15 02:40
@mysticatea @not-an-aardvark @nzakas Any thoughts on this use case?

**Comment by not-an-aardvark** [comment] 2019-07-15 02:53
Could you elaborate on how the virtual filenames cause problems? I read https://github.com/benmosher/eslint-plugin-import/issues/1415 but it's not clear to me why relative paths would be broken, since it seems like resolving paths relative to the virtual filename would have the same result as resolving relative to the real filename (since the virtual filename has the same directory).

**Comment by Conduitry** [comment] 2019-07-15 02:59
The virtual filename is down one level from the real filename - https://github.com/eslint/eslint/blob/1fb362093a65b99456a11029967d9ee0c31fd697/lib/linter/linter.js#L1207

**Comment by platinumazure** [comment] 2019-07-15 03:01
@not-an-aardvark Is that the case? My understanding was that for a physical file (say, `path/to/foo.html`), the virtual files were added on to the full file path (say, `path/to/foo.html/0.js`). But maybe I'm mistaken.

**Comment by not-an-aardvark** [comment] 2019-07-15 03:07
Oh I see, thanks for clarifying.

**Comment by ljharb** [comment] 2019-07-15 03:35
An alternative fix might be to not alter the implied cwd for named block filenames, but instead use a query string or an extension or something?

**Comment by mysticatea** [comment] 2019-07-15 18:31
Sounds reasonable request.

**Comment by Conduitry** [comment] 2019-08-05 18:27
What's next here?

I don't know how much of the way the virtual preprocessed block's filename is constructed is part of the API contract. Using a query string or appending some other string that doesn't contain a forward slash would be tidier (and would probably remove the need for an option to control which filename we wanted), but it does seem to contradict what's in the docs: https://eslint.org/docs/user-guide/configuring#specifying-processor

Something to consider. I don't feel qualified to have an opinion about this. But I do think that whatever is decided to be done here, the docs should be made to be more explicit about how the filename is constructed. The current `/[index]_[name].[extension]` isn't mentioned at all. It may or may not be too late to also take this opportunity to change it. I don't know how well-used named blocks are.

**Comment by mysticatea** [comment] 2019-08-23 11:02
I'm sorry for my late response.

As a fact, `context.getFilename()` doesn't guarantee to return a real path. For example, people can give an arbitrary string as a filename.

```js
const { CLIEngine } = require("eslint");
const engine = new CLIEngine();

engine.executeOnText("console.log('hello')", "a-dummy-filename.js")
```

In that case, ESLint doesn't check if the file path is valid or not.

Also, `eslint` command supports piping and `context.getFilename()` returns `"<input>"` if piped.

Additionally, processors may make dummy filenames for each code block. It must be a path that people can distinguish between code blocks and files by glob patterns because people often use different settings for code blocks. By design, it's like the child file of the original file. (for example, yes, https://eslint.org/docs/user-guide/configuring#specifying-processor.)

----

I feel that this is related to #12133. If we added `context.getRealFilename()`, should it guarantee that the returned path exists as a file?

**Comment by ljharb** [comment] 2019-09-23 15:08
This should be reopened; it affects the plugin ecosystem.

**Comment by ljharb** [comment] 2019-10-24 22:58
Ping again; this should remain open because it affects the plugin ecosystem.

**Comment by ljharb** [comment] 2019-11-25 22:48
Ping again :-) can this get a label that prevents collateral damage?

**Comment by kaicataldo** [comment] 2019-11-26 04:40
Is there an RFC for this?

**Comment by GitGangGuy** [comment] 2020-03-07 17:56
I'm getting interested in this as well. If eslint is able to fix the current issue with the no-unresolved rule, this would provide a greater experience with svelte development.

**Comment by JounQin** [comment] 2021-03-11 17:37
related https://github.com/prettier/eslint-plugin-prettier/issues/393

**Comment by JounQin** [comment] 2021-03-12 07:09
I have another problem on this issue.

[`eslint-mdx`](https://github.com/mdx-js/eslint-mdx) is able to lint the whole file and code blocks at the same time, so I want to use preprocessor like following:

```js
module.exports = {
  preprocess(text, filename) {
    return [
      // the original whole file
      {
        text,
        filename,
      },
      // code blocks like `eslint-plugin-markdown`
      {
        // ...
      },
    ]
  },
}
```

But the following ESLint source code breaks this usage.

https://github.com/eslint/eslint/blob/master/lib/linter/linter.js#L1303

```log
Oops! Something went wrong! :(

ESLint: 7.21.0

Error: ENOTDIR: not a directory, stat '/Users/JounQin/Workspaces/GitHub/eslint-mdx/test/fixtures/code-block.md/0_/Users/JounQin/Workspaces/GitHub/eslint-mdx/test/fixtures/code-block.md'
Occurred while linting /Users/JounQin/Workspaces/GitHub/eslint-mdx/test/fixtures/code-block.md/0_/Users/JounQin/Workspaces/GitHub/eslint-mdx/test/fixtures/code-block.md:1
    at Object.statSync (fs.js:1016:3)
    at isTypeSync (/Users/JounQin/Workspaces/GitHub/eslint-mdx/node_modules/prettier/third-party.js:9748:46)
    at getDirectorySync (/Users/JounQin/Workspaces/GitHub/eslint-mdx/node_modules/prettier/third-party.js:9802:62)
    at ExplorerSync.searchSync (/Users/JounQin/Workspaces/GitHub/eslint-mdx/node_modules/prettier/third-party.js:9950:66)
    at _resolveConfig (/Users/JounQin/Workspaces/GitHub/eslint-mdx/node_modules/prettier/index.js:25592:50)
    at Function.resolveConfig.sync (/Users/JounQin/Workspaces/GitHub/eslint-mdx/node_modules/prettier/index.js:25621:42)
    at Program (/Users/JounQin/Workspaces/GitHub/eslint-mdx/node_modules/eslint-plugin-prettier/eslint-plugin-prettier.js:167:40)
    at /Users/JounQin/Workspaces/GitHub/eslint-mdx/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/Users/JounQin/Workspaces/GitHub/eslint-mdx/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
```

**Comment by JounQin** [comment] 2021-03-16 18:02
@mdjermanovic I'd like a proposal like add `context.getFilename(truePath?: boolean)` support and fallback to previous behavior not in code block or we don't know the real path for rules.

**Comment by nzakas** [comment] 2021-03-19 00:50
I think there are a few ways we could go here.

We could add an argument to getFilename(), as suggested, although I’m not a big fan of Boolean arguments because it’s hard to understand what “true” means without context. The upside to this is that it’s not a breaking change.

We could also change the format of the string returned so that it uses a # between the physical filename and the code block name. That would at least allow people to check for the # to know if they are dealing with a code block. This is likely a breaking change but probably won’t break many real world cases.

Another option is to add a new context.filename property that is always the physical filename and a context.codeBlock property that has the code block identifier. Downside here is that people might think context.filename is unique when it can be duplicated.

**Comment by btmills** [comment] 2021-03-28 22:57
I could get on board with any of those three solutions. For the `#` idea, that aligns with early discussions around [inline module fragments](https://github.com/littledan/proposal-module-fragments/) as a possible future syntax addition. If those move forward, configuring those would likely be similar to configuring processors today. Aligning our processor block filenames with that syntax could solve two problems with one change. I expect to get an update on that discussion this week, so I'll report back here with any new information.

**Comment by ljharb** [comment] 2021-03-29 02:27
Inline module fragment won’t likely end up being able to use #, since node already ascribes it a meaning.

**Comment by nzakas** [comment] 2021-03-30 00:56
@btmills i was thinking of # as more analogous to URLs than anything else.

**Comment by btmills** [comment] 2021-04-11 22:59
We've tentatively accepted this as a change for the v8.0.0 release if we go with the `#` proposal since that would be a breaking change. If we end up choosing one of the other options, we wouldn't have to do this in a major release.

**Comment by JounQin** [comment] 2021-04-12 06:15
I still think we should provide an util method like `getFilename(true)` personally, so that plugin authors won't need to write the same logic repeatedly.

**Comment by nzakas** [comment] 2021-04-16 00:33
@JounQin which logic are you referring to?

**Comment by Conduitry** [comment] 2021-04-16 00:51
I assume that's referring to the logic of stripping the `#` and everything after it when any plugin needs the real path of the file.

**Comment by nzakas** [comment] 2021-04-17 00:25
That’s just `filename.split(“#”)[0]`.

**Comment by ljharb** [comment] 2021-04-17 01:21
Filenames can contain # tho, no?

**Comment by btmills** [comment] 2021-04-21 04:51
If we're unable to change the filename string, our remaining options are, in descending order of personal preference:

1. Add `context.filename` and `context.codeBlock`. In the case of nested code blocks, would `codeBlock` continue to use `/` as the separator?
2. Instead of adding an arg, add a new `getPhysicalFilename()` method for this use case.
3. Add an argument to `getFilename()`. I dislike Boolean args as well, but an options object feels like overkill.
4. Change `getFilename()` to always return the physical filename, and add a new `getVirtualFilename()` method that returns the virtual filename in the case of a code block. This would be a breaking change.

That's everything that I saw suggested already plus a couple variations. Are there any other ideas?

Unless we go with the fourth option, this is no longer a breaking change and can be removed from the v8.0.0 project to be solved in any minor release.

**Comment by nzakas** [comment] 2021-04-22 00:28
We can’t do option 4 because some rules rely on the return value to be unique (this is why we changed it to return filename plus code block in the first place).

Options 1 or 2 seem the most viable. Option 1 feels cleaner and would seem to better match expectations but I do worry that people would forget to check codeBlock when using the filename as a cache key. So, I think I’ve talked myself into option 2.

Also, removing from v8.0.0 since none of these options are breaking.

**Comment by btmills** [comment] 2021-04-22 00:41
Option 2 works for me.

**Comment by nzakas** [comment] 2021-04-23 00:34
Summary: we will add a new `getPhysicalFilename()` method to the rule context object. This method will return the full path of the file on disk without any code block information. This is simple enough that we don’t need an RFC.

**Comment by snitin315** [comment] 2021-04-23 00:41
Can I work on this issue?

**Comment by nzakas** [comment] 2021-04-24 00:36
Let’s wait a week to see if any first-time contributors would like to take this on. If no one else steps up, then it’s all yours.

**Comment by harsha0609** [comment] 2021-04-24 12:36
Hi @nzakas, I would like to volunteer to work on this issue.

**Comment by nzakas** [comment] 2021-04-26 19:02
@harsha0609 awesome! We'd love to have you work on this issue. Please let us know if you need any help.

**Comment by pmcelhaney** [comment] 2021-05-01 01:23
Until the issue is fixed, here's a work-around to disable affected rules for these bogus filenames. 

```js
       {
            overrides: [
                { // Can remove after this issue is fixed: https://github.com/eslint/eslint/issues/11989
                    files: ['**/*.md/*_*.js'],
                    rules: {
                        'import/no-unresolved': 'off',
                    },
                },
       }
```

Note that I'm specifically concerned about the `import/no-unresolved` rule in Markdown (`.md`) files. You may need to tweak to suit your needs.

**Comment by nzakas** [comment] 2021-05-03 18:09
@harsha0609 just checking in to see if you're still planning on working on this? No worries if not, we just want to give you the time to dig in if you want.

**Comment by harsha0609** [comment] 2021-05-03 18:58
Sorry for the delay @nzakas, was caught up with some work stuff, so yeah I still would love to work on this, would please help out with the rule context object definition for this?

> Summary: we will add a new `getPhysicalFilename()` method to the rule context object. This method will return the full path of the file on disk without any code block information. This is simple enough that we don’t need an RFC.

**Comment by pmcelhaney** [comment] 2021-05-03 22:31
Hi @harsha0609, looks like the object is defined here:

https://github.com/eslint/eslint/blob/41b3570b6c014c534bb3208ed00050fd99842101/lib/linter/linter.js#L861

You'll want to add a `getPhysicalFilename()` method to that object. If you search for `getFilename()` you can also find the places where the tests and documentation will need to be updated.

**Comment by nzakas** [comment] 2021-05-04 00:20
Thanks @pmcelhaney!

@harsha0609 you’ll also likely need to pass another argument to this function:

https://github.com/eslint/eslint/blob/41b3570b6c014c534bb3208ed00050fd99842101/lib/linter/linter.js#L833

**Comment by harsha0609** [comment] 2021-05-04 17:58
@nzakas went through the code, guess won't be able to work on this. Sorry for the inconvenience.

**Comment by pmcelhaney** [comment] 2021-05-04 19:45
I'll wait to see if anyone else wants to claim it, but I have a pretty good idea how to move forward, so I'll go ahead and share my thoughts.

There's an options object where the filename is replaced by "blockName".

https://github.com/eslint/eslint/blob/41b3570b6c014c534bb3208ed00050fd99842101/lib/linter/linter.js#L1303-L1326

We would need to put a copy of the original filename in the options object in a key called `physicalFilename`. 

Then pass `options.physicalFilename` in a new argument to the function @nzakas mentioned.

**Comment by nzakas** [comment] 2021-05-05 00:39
That looks like a good approach 👍

**Comment by snitin315** [comment] 2021-05-19 00:44
Hi @pmcelhaney, are you still working on it? If not I would like to work on this one.

**Comment by pmcelhaney** [comment] 2021-05-22 15:40
@snitin315 Yes, go ahead! Thank you!

**Closed** 2021-06-04 15:48 UTC
Labels: accepted, core, enhancement, good first issue
