### ISSUE TITLE
not working introduced in version 9.x

### ISSUE THREAD

**Issue by kireerik** [eslint/eslint#18342] opened 2024-04-15 14:31 UTC
### Environment

Node version: 21.7.3
Local ESLint version: 9.0.0
Operating System: Windows (10)

### What parser are you using?

Default (Espree)

### What did you do?

> Configurations are in the `package.json` files under the `eslintConfig` properties.

### What did you expect to happen?

Works just like it does in version 8.x.

### What actually happened?

I am getting the following error:
```
Oops! Something went wrong! :(

ESLint: 9.0.0

Error: Could not find config file.
    at locateConfigFileToUse (...\node_modules\.pnpm\eslint@9.0.0\node_modules\eslint\lib\eslint\eslint.js:349:21)
    at async calculateConfigArray (...\node_modules\.pnpm\eslint@9.0.0\node_modules\eslint\lib\eslint\eslint.js:384:49)
    at async ESLint.lintFiles (...\node_modules\.pnpm\eslint@9.0.0\node_modules\eslint\lib\eslint\eslint.js:814:25)
    at async Object.execute (...\node_modules\.pnpm\eslint@9.0.0\node_modules\eslint\lib\cli.js:461:23)
    at async main (...\node_modules\.pnpm\eslint@9.0.0\node_modules\eslint\bin\eslint.js:165:22)
```

### Link to Minimal Reproducible Example

⠀

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by aladdin-add** [comment] 2024-04-15 16:09
Duplicate of #18308

**Closed by aladdin-add** 2024-04-15 16:09 UTC
Labels: question

**Comment by kireerik** [comment] 2024-04-16 17:49
To me the referenced issue looks like a different one. I would expect the `eslintConfig` property in the `package.json` to be respected.

**Comment by kireerik** [comment] 2024-04-26 08:48
Yes. This is not a duplicate of #18308.

Looks like in the meantime despite the premature closure this was resolved in (https://github.com/eslint/eslint/releases/tag/v9.1.0):
- #18305
