### ISSUE TITLE
Consider nullish coalescing in code path analyzer

### ISSUE THREAD

**Issue by gaearon** [eslint/eslint#13237] opened 2020-04-30 00:46 UTC
We [use](https://github.com/facebook/react/blob/dd7f0deb947f836170cd1019dbbc2e44d30a21ce/packages/eslint-plugin-react-hooks/src/RulesOfHooks.js#L121-L132) the code path analyzer for `react-plugin-react-hooks/rules-of-hooks`.

Currently, it understands `foo || useHook()` is a conditional function call, but it doesn't understand that for nullish coalescing `foo ?? useHook()`. We have some bugs creeping into the codebase because of that missing coverage.

Now that `??` is Stage 4, would it be possible to teach the code path analyzer to handle it?

The last relevant change I know of was https://github.com/eslint/eslint/pull/10476, but that just made it so that the code does not crash altogether. We're happy to lend a hand with a fix (although someone who knows the codebase might be able to do that better than me).

**Comment by aladdin-add** [comment] 2020-04-30 02:55
related #12642

**Comment by kaicataldo** [comment] 2020-04-30 05:32
Thanks for the issue. Now that [this PR](https://github.com/acornjs/acorn/pull/890) has been merged, we should be able to add support when Acorn publishes its next release.

For some more context around why we don’t support this yet, it’s been difficult to nail down the AST spec for optional chaining and nullish coalescing operator syntax [in ESTree](https://github.com/estree/estree/pull/204), and since we use Acorn as the underlying parser and Acorn follows the ESTree spec, we unfortunately have been blocked. The two proposals were eventually split into two separate issues, and consensus has been reached on the nullish coalescing operator.

**Comment by mysticatea** [comment] 2020-05-06 05:41
I'm closing this issue as a duplicate of #12642.

New syntax support needs time because we need to work on upstream that there are many stakeholders. Please check https://github.com/eslint/eslint/pull/13196 for progress.

**Closed by mysticatea** 2020-05-06 05:41 UTC
Labels: accepted, core, enhancement, new syntax
