### ISSUE TITLE
Overriding a rule doesn't reset options, unless you pass an empty object

### ISSUE THREAD

**Issue by callumlocke** [eslint/eslint#6955] opened 2016-08-22 11:17 UTC
**What version of ESLint are you using?**

3.3.1

**What parser (default, Babel-ESLint, etc.) are you using?**

babel-eslint

**Please show your full configuration:**

```yaml
root: true
extends: airbnb
parser: babel-eslint
rules:
  no-console: 0
  import/no-extraneous-dependencies: 2
```

**What did you do? Please include the actual source code causing the issue.**

I added `import/no-extraneous-dependencies: 2` to my config.

**What did you expect to happen?**

I thought this would override the default setting from airbnb, which is `[2, { devDependencies: false }]`.

I assumed my `2` would receive the [default options](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/no-extraneous-dependencies.md), which include `devDependencies: true`.

**What actually happened? Please include the actual, raw output from ESLint.**

Instead, the original options from the eslint-config-airbnb were retained. ESLint behaved as if I had set `devDependencies: false`.

I found it's necessary to pass an empty object just to get the defaults back:

```yaml
  import/no-extraneous-dependencies: [2, {}]
```

**Notes**

I guess it might be by design, but I think it's very surprising that `2` behaves completely differently from `[2, {}]`.

Before I worked out the root cause, I posted [this issue on eslint-plugin-import](https://github.com/benmosher/eslint-plugin-import/issues/469), and a few people commented saying they'd had exactly the same problem. So it seems like a lot of people are confused by this behaviour.

**Comment by mysticatea** [comment] 2016-08-22 11:54
Thank you for this issue.

I think this is intentional behavior.
This is duplicate of #6144 and #6361.

**Comment by callumlocke** [comment] 2016-08-22 12:12
OK. I think it could be worth revising. It's evidently a very weird, surprising behaviour. In [this issue](https://github.com/benmosher/eslint-plugin-import/issues/469) it's only on revisiting it a third time that I eventually traced the problem to eslint's own behaviour. Several others also made the same assumption as me: that there's no way in hell eslint would work like that, so it must be a problem with the plugin we were using.

If I override a rule in my local config, and it's not working correctly, I go and look at that rule's documentation to see what its options (and defaults) are. But it turns out it doesn't work like that, instead eslint assembles a mixture of my severity level with the other options from the other config – _unless_ I pass in an empty object (wtf!). It's very confusing for virtually zero convenience (letting me set a severity but magically importing the other options from the other config?). I'd understand if eslint's behaviour was to _merge_ my options over those from the other config, but it doesn't do that either. It uses the other config's options if I provide _nothing_, but not if I provide an empty object. It's very un-idiomatic.

**Closed** 2016-08-22 12:14 UTC
Labels: triage

**Comment by platinumazure** [comment] 2016-08-22 13:18
I've said before that I don't like this behavior and think it should be changed. Can we reopen this and consider it a breaking but worthwhile change?

**Comment by jfo84** [comment] 2016-12-27 17:32
Seconded @platinumazure
