### ISSUE TITLE
Upgrade to Ajv version 8

### ISSUE THREAD

**Issue by epoberezkin** [eslint/eslint#13888] opened 2020-11-28 12:41 UTC
**The version of ESLint you are using.**

7.14

**The problem you want to solve.**

Migrate eslint to Ajv version 7 at the time it is released in December as the main version, to ensure that the users migrating to Ajv v7 and using eslint (that depends on Ajv version 6) do not have any version conflicts.

**Your take on the correct solution to problem.**

Upgrade in eslint: 
- Ajv and other related dependencies versions (e.g. ajv-keywords)
- any Ajv API/options changes
- JSON Schema to draft-07 - Ajv v7 removed support for draft-04 (which is 4 versions old), the change logs are here: https://github.com/ajv-validator/ajv/releases

My concern that any plugins that rely on JSON Schema draft-04 specific features may need to be upgraded too, but nothing has been reported so far; although not too many users started using Ajv v7 beta, it is growing judging by ajv-formats downloads that was split from Ajv in v7: https://www.npmjs.com/package/ajv-formats

Either way, it most likely should be a major version change in eslint too to avoid any issues for the users - do you agree?

I am planning a release candidate version 7.0.0-rc.0 some time next week, and the main version release within a couple of weeks this year; I think I should  make a PR to eslint once 7.0.0-rc.0 is released.

Let me know if you have any concerns / comments / questions

**Are you willing to submit a pull request to implement this change?**

Yes

**Comment by aladdin-add** [comment] 2020-11-30 14:40
> Either way, it most likely should be a major version change in eslint too to avoid any issues for the users - do you agree?

would it be possible to release in a minor version (if no breaking changes introduced 😄 )? -- it will take a long while before releasing a major version, as we are working on some big features (e.g. https://github.com/eslint/eslint/issues/13481).

**Comment by J-Vin** [comment] 2020-11-30 14:52
I have no clue if this helps... runkit.com/j-vin/runkit-npm-ajv-formats

**Comment by epoberezkin** [comment] 2020-12-01 12:54
@aladdin-add thank you. There shouldn’t be any breaking changes in eslint for the end users, but I’m not sure how configuration validation implemented in plugins - do they do it independently or do they depend on eslint? I’ll probably see it as I do the PR - but if the latter they may need to be upgraded too - that’s why I thought it might have to be a major version... I will comment as I make some progress.

**Comment by drtyh2o** [comment] 2021-02-05 18:45
This is causing problems for one of my TypeScript + yarn workspaces projects. The issue is that ESLint's dependency of `ajv@6` gets installed in the root `/node-modules` folder and all of my packages get a copy of `ajv@7` which causes TypeScript errors because the module references are different. Is it possible to either upgrade the eslint dependency to `ajv@7` or make `ajv` a peer dependency? I am currently working around this by using "resolutions" in our package.json, but having a devDependency dictating how dependency versions are resolved for my project is suboptimal.

**Comment by epoberezkin** [comment] 2021-02-05 21:05
yarn indeed seems to be worse at managing the dependency tree than npm. There was some period when yarn was faster and less error prone, but it seems no longer to be the case to be honest.

I suggest switching back to npm - at least it seems to always make clean installations correctly, with some occasional errors happening when dependencies are added to the existing tree.

**Comment by mdjermanovic** [comment] 2021-02-23 13:51
This change needs a [RFC](https://github.com/eslint/rfcs).

We can easily update everything that needs to be updated in ESLint's core and built-in rules, but the possible breakage of plugins discussed in #13911 presents a problem that should be addressed in the RFC.

**Comment by drtyh2o** [comment] 2021-02-23 14:41
> I suggest switching back to npm - at least it seems to always make clean installations correctly, with some occasional errors happening when dependencies are added to the existing tree.

I resolved the dependency hoisting issue by switching from `yarn` to [pnpm](https://pnpm.js.org/).

**Comment by epoberezkin** [comment] 2021-02-23 15:01
@mdjermanovic happy to support with any comments / feedback / suggestions. If you want me to lead it I might be able do it (not a promise:) after v8 is released (which is about a month and half).

Either way, it may be better to hold off migrating till v8 is out - it won't have radical changes but it would consolidate and stabilise the changes in v7, and there would still be some minor breaking changes.

**Comment by mdjermanovic** [comment] 2021-02-23 15:35
> Either way, it may be better to hold off migrating till v8 is out - it won't have radical changes but it would consolidate and stabilise the changes in v7, and there would still be some minor breaking changes.

Makes sense to wait for v8 if it's going to be released in a month and a half, so we could have all the new details to analyze in the RFC.

The main concern with waiting is that support for v6 ends soon, though it's stable and I don't think we've ever had any issues related to Ajv.

**Comment by epoberezkin** [comment] 2021-03-06 09:16
> The main concern with waiting is that support for v6 ends soon, though it's stable and I don't think we've ever had any issues related to Ajv.

v6 is no longer actively developed and existing limitations will not be addressed, but security related issues (and any major bugs without workarounds) would still be fixed at least until the end of June - already promised it to fastify.

So no problem with migrating to v8 and skipping v7, but up to you - the incompatible changes from v7 to v8 will be minor, so v7 -> v8 migration will be much simpler.

**Comment by btmills** [comment] 2021-04-12 03:26
We’ve accepted this change for ESLint v8.0.0, and we’re fine going straight to Ajv v8 since that’ll be the latest version.

**Comment by epoberezkin** [comment] 2021-04-12 10:23
Great - v8 is already released.

**Comment by nzakas** [comment] 2021-05-06 20:22
Hi everyone, in order to move forward with this, we are going to need an RFC.

What we are looking for in the RFC:

1. A description of the schema changes that are likely to break in plugin rules (lots of discussion around this on https://github.com/eslint/eslint/pull/13911)
2. An approach as to how we can upgrade with causing as few issues for the ecosystem as possible. We can always upgrade core rules, but plugin rules may take a while to upgrade and we don't want to break a large part of the ecosystem with the next release.
3. An analysis of some of the top plugins to see which would be affected and how we might work with them to fix issues ahead of time.

@epoberezkin @aladdin-add do either of you want to take this on?

**Comment by epoberezkin** [comment] 2021-05-10 21:17
@aladdin-add - you probably know more about eslint to make the first draft and to propose how to make the transition easier… I’m happy to support with comments / any JSON schema related details.

Upgrading Ajv API is quite straightforward (I’ve made PR to v7, v8 is nearly the same), the main complexities are:
- JSON Schema draft 4 to draft 7 migration (or maybe we want to consider draft 2019/2020 but it’s a much bigger change, and 2020 is very incompatible with changed items…)
- Incorrect schemas that now will be flagged, as I mentioned above. We probably should just log it.

We probably should consider splitting config validation from eslint, like we pack did, so different plugins can depend on different variants of schema and of Ajv  - that would make future migrations much easier. What do you think @nzakas @aladdin-add

**Comment by nzakas** [comment] 2021-05-11 01:07
Here’s my concern: I don’t want to have to keep updating schema formats. If we get better error checking, that’s good, but other types of changes are bad for the ecosystem. 

I’m still not clear on what benefit ESLint gets from upgrading Ajv right now. I don’t know that the latest version of JSON schema provides us with any advantage over the one we are using.

What is the downside of us ESLint not upgrading? I understand Ajv 6 won’t be maintained, but if it’s working fine right now for us, I’m not sure if that should be a concern.

@epoberezkin I think this is a question you may need to think about: while I’m sure you always want to support the latest JSON schema version that you can, is it worth disrupting existing users by removing old versions?

**Comment by epoberezkin** [comment] 2021-05-11 05:53
> I’m sure you always want to support the latest JSON schema version that you can

@nzakas Actually, I am not too happy with the pace of change in JSON Schema that sometimes introduces quite radical changes (e.g. draft-2020-12) without clear benefits, and the resulting pressure from the users who actually do want to use the latest JSON Schema version - there were some epic exchanges in ajv issue tracker.

> is it worth disrupting existing users by removing old versions?

The reason to drop draft-04 was that it is very different from draft-07 and ajv v6 has quite an extensive support of it (that most people don't need), and executing the re-write I did without removing draft-04 would have been very difficult - stripping it out was the first thing I did in August last year.

Now that v8 is stable, it is quite doable actually to implement draft-04 support as an extension - I could do it with ajv v8.4 (the next one) as `@ajv-validator/json-schema-draft-04` npm package. Ajv change is still needed to support different $id syntax (it's plain `id` in draft-04). Things that will be lost (comparing with Ajv v6) will have zero impact on most users who still need draft-04, eslint definitely doesn't use these:
- supporting draft-04 and draft-07 schemas in the same Ajv instance (e.g. in v6 you can have draft-07 schema depend on draft-04 and vice versa).
- supporting $data reference (you don't use it) in exclusiveMaximum/Minimum keywords.

So the migration of eslint to v8.4 should be painless, with zero impact on plugins (we will opt out of strict mode, or we could make them warnings - probably still helpful) and no JSON Schema version change.

If this plan works, I can do it over the weekend and update the PR here - I don't think it requires RFC - I'm quite confident it'll be ok.

**Comment by aladdin-add** [comment] 2021-05-16 17:38
sounds good! I think we can remove it in [v8.0 project](https://github.com/eslint/eslint/projects/8) - as it's no longer a breaking change, and can be landed in later releases.

**Comment by epoberezkin** [comment] 2021-05-16 21:09
Great!

> can be landed in later releases.

You probably mean in earlier?

**Comment by aladdin-add** [comment] 2021-05-16 23:08
earlier/later 😄

**Comment by btmills** [comment] 2021-05-19 05:04
Now that this doesn't have to be a breaking change anymore, I've removed the "breaking" label and removed this issue from the v8.0.0 project so that we can land it whenever it's ready. @epoberezkin thanks for your work on ajv and figuring out how to eliminate breakage in ESLint's plugin ecosystem!

**Comment by epoberezkin** [comment] 2021-05-19 20:03
You're welcome! I will probably release ajv 8.5 and the draft-04 support by the [ajv event tomorrow](https://us02web.zoom.us/webinar/register/2716192553618/WN_erJ_t4ICTHOnGC1SOybNnw) (a promotion :) - will mention it then.

**Comment by epoberezkin** [comment] 2021-05-20 16:45
Draft-04 support is released: https://github.com/ajv-validator/ajv-draft-04 (it'll be 1.0.0 when it lands here).

Will update this PR over the weekend.

**Comment by mdjermanovic** [comment] 2021-07-01 22:38
In today's TSC meeting, we have decided to stay on Ajv 6.

The additional validations in Ajv 8 are a very nice feature, but Ajv 8 brings many other changes and it's difficult to predict the overall impact on the ESLint ecosystem of plugins.

As for the maintenance concerns, Ajv 6 seems very stable and works perfectly well for ESLint's use case. ESLint has been using Ajv 6 for years and we've never had any Ajv-related issues.

For all these reasons, we have come to the conclusion that in this case risks outweigh the benefits, so I'm closing this issue per the TSC decision.

**Closed by mdjermanovic** 2021-07-01 22:38 UTC
Labels: accepted, breaking, core, enhancement

**Comment by fisker** [comment] 2021-08-08 08:28
Do we need to update this https://eslint.org/blog/2021/06/whats-coming-in-eslint-8.0.0#stricter-rule-schema-validation ?
