### ISSUE TITLE
Support block/function scoped inline configuration comments

### ISSUE THREAD

**Issue by dantman** [eslint/eslint#2832] opened 2015-06-24 08:26 UTC
ESlint's inline configuration comments don't appear to do any scoping. So any time you want to change configuration for one function. You need to configure it at the top, and reset it at the bottom of the function with another comment to avoid it leaking.

Which to be honest. Doing that while writing code for node/browserify in ES6 and JSX/React just feels wrong.

jshint block scoped its inline configuration comments, which really made sense.

I understand eslint can't suddenly make all the `/* eslint */` comments suddenly block/function scoped. So considering eslint doesn't support single line `// eslint ...` style configuration, I like using single line inline configuration when I'm writing scoped stuff. I suggest we add support for `// eslint ...`, `// eslint-env ...`, ... as block or function scoped inline configuration.

If anyone is worried about people mistaking `//` rules for the non-scoped rules you can wrap around a small piece of code. Then we could add the requirement that scoped rules must be declared at the top of their scope and consider use elsewhere to be a linter error.

**Comment by lo1tuma** [comment] 2015-06-24 08:38
Duplicate of #1766

**Closed** 2015-06-24 16:55 UTC
