### ISSUE TITLE
Problem fixing indentation with Allman style

### ISSUE THREAD

**Issue by domolicious** [eslint/eslint#8601] opened 2017-05-15 10:08 UTC
* **ESLint Version:v3.19.0**
* **Node Version:v7.9.0**
* **npm Version:4.2.0**

**What did you do? Please include the actual source code causing the issue.**
```sh
echo "function run() { if(true) { console.log(true); } }" > test.js
eslint --no-eslintrc --rule "indent: [error,tab]" --rule "brace-style: [error,allman]" test.js  --fix
```

**What did you expect to happen?**
```js
function run() 
{
	if(true) 
	{
		console.log(true); 
	} 
}
```

**What actually happened? Please include the actual, raw output from ESLint.**
```js
function run() 
{
	if(true) 
{
		console.log(true); 
	} 
}
```

This is true for every opening brace and whether you use tabs or spaces for indentation. The indentation is lost.

**Comment by platinumazure** [comment] 2017-05-15 14:47
@not-an-aardvark Is this fixed in the new indent rule?

**Comment by not-an-aardvark** [comment] 2017-05-15 15:33
Yes, this is a duplicate of https://github.com/eslint/eslint/issues/7662.

**Closed by not-an-aardvark** 2017-05-15 15:33 UTC
Labels: bug, evaluating, indent, rule
