### ISSUE TITLE
Yoda lint triggered on a range within a function argument.

### ISSUE THREAD

**Issue by Mark-Simulacrum** [eslint/eslint#5621] opened 2016-03-19 19:04 UTC
**What version of ESLint are you using?**

2.4.0

**What parser (default, Babel-ESLint, etc.) are you using?**

babel-eslint

**Please show your full configuration:**

```json
{
    "parser": "babel-eslint",
    "env": {
        "node": true,
        "es6": true,
    },
    "extends": "eslint:recommended",
    "rules": {
        "curly": 0,
        "eol-last": 2,
        "no-trailing-spaces": 2,
        "no-unused-vars": 2,

        "no-use-before-define": 2,
        "no-underscore-dangle": 0,
        "new-cap": 0,
        "yoda": [2, "never", { "exceptRange": true }],
        "quotes": 0,
        "comma-dangle": 0,
        "space-infix-ops": 0,
        "no-console": 0,

        "no-alert": 2,
        "no-array-constructor": 2,
        "no-caller": 2,
        "no-catch-shadow": 2,
        "no-eval": 2,
        "no-extend-native": 2,
        "no-extra-bind": 2,
        "no-implied-eval": 2,
        "no-iterator": 2,
        "no-label-var": 2,
        "no-labels": 2,
        "no-lone-blocks": 2,
        "no-loop-func": 2,
        "no-multi-spaces": 2,
        "no-multi-str": 2,
        "no-native-reassign": 2,
        "no-new": 2,
        "no-new-func": 2,
        "no-new-object": 2,
        "no-new-wrappers": 2,
        "no-octal-escape": 2,
        "no-process-exit": 2,
        "no-proto": 2,
        "no-return-assign": 2,
        "no-script-url": 2,
        "no-sequences": 2,
        "no-shadow": 2,
        "no-shadow-restricted-names": 2,
        "no-spaced-func": 2,
        "no-undef-init": 2,
        "no-unused-expressions": 2,
        "no-with": 2,
        "camelcase": 2,
        "comma-spacing": 2,
        "consistent-return": 2,
        "dot-notation": [2, { "allowKeywords": true }],
        "no-extra-parens": [2, "functions"],
        "eqeqeq": 2,
        "key-spacing": [2, { "beforeColon": false, "afterColon": true }],
        "new-parens": 2,
        "semi": 2,
        "semi-spacing": [2, {"before": false, "after": true}],
        "keyword-spacing": 2,
        "space-unary-ops": [2, { "words": true, "nonwords": false }],
    }
}
```

**What did you do? Please include the actual source code causing the issue.**

`assert(0 <= port && port <= 65535, "port is out of range");`

causes the "yoda" lint to fire (`Expected literal to be on the right side of <=  yoda`).

**What did you expect to happen?**

I expected the yoda lint to not be triggered due to the `exceptRange` option being set.

The problem vanishes when the input is changed to `assert(0 <= port && port <= 65535);` because now the range is within parentheses, but I would expect a function call argument to be considered enough.

`assert(0 <= port && port <= 65535, "port is out of range");` is much better than `assert((0 <= port && port <= 65535), "port is out of range");`.

Please tell me if you need anything else.

**Comment by platinumazure** [comment] 2016-03-19 19:41
There's discussion going on elsewhere (issue #5575) about whether yoda exceptRange should require parentheses around its range check. I believe it shouldn't, but there's still a few things to iron out.

Can't repro in online demo due to insufficient configuration support, but I'll try to repro in my local repository later today unless someone beats me to it. But I'm 99% sure this is reproducible and I would say it's a bug.

**Comment by kaicataldo** [comment] 2016-08-25 20:25
Closing as there has been no movement on this issue in months.

**Closed by kaicataldo** 2016-08-25 20:25 UTC
Labels: bug, evaluating, rule
