### ISSUE TITLE
Bug: ESLint crashes when formatting a file contains emoji in filename on Windows (Node.js 20 only)

### ISSUE THREAD

**Issue by fisker** [eslint/eslint#17886] opened 2023-12-20 16:18 UTC
### Environment

Node version: 20.10.0
npm version: N/A
Local ESLint version: 8.56.0
Global ESLint version: N/A
Operating System: Windows

### What parser are you using?

Default (Espree)

### What did you do?

Lint files.

### What did you expect to happen?

Lint file without error.

### What actually happened?

```
Oops! Something went wrong! :(

ESLint: 8.56.0

Error: ENOENT: no such file or directory, open
    at open (node:internal/fs/promises:604:19)
    at Object.readFile (node:internal/fs/promises:1071:20)
    at D:\a\eslint-flat-config-emoji-file-name-bug\eslint-flat-config-emoji-file-name-bug\node_modules\eslint\lib\eslint\flat-eslint.js:846:[27](https://github.com/fisker/eslint-flat-config-emoji-file-name-bug/actions/runs/7277977845/job/19831193348#step:4:28)
    at Array.map (<anonymous>)
    at FlatESLint.lintFiles (D:\a\eslint-flat-config-emoji-file-name-bug\eslint-flat-config-emoji-file-name-bug\node_modules\eslint\lib\eslint\flat-eslint.js:789:23)
    at async Object.execute (D:\a\eslint-flat-config-emoji-file-name-bug\eslint-flat-config-emoji-file-name-bug\node_modules\eslint\lib\cli.js:421:23)
    at async main (D:\a\eslint-flat-config-emoji-file-name-bug\eslint-flat-config-emoji-file-name-bug\node_modules\eslint\bin\eslint.js:152:22)
```

See the reproduction repo CI log.

https://github.com/fisker/eslint-flat-config-emoji-file-name-bug/actions/runs/7277977845/job/19831193348#step:4:24

### Link to Minimal Reproducible Example

https://github.com/fisker/eslint-flat-config-emoji-file-name-bug/

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by mdjermanovic** [comment] 2023-12-20 20:19
I can reproduce this, but it seems to be an issue in Node.js: https://github.com/nodejs/node/issues/48673

**Comment by mdjermanovic** [comment] 2023-12-20 20:22
I first found one with emojis: https://github.com/nodejs/node/issues/49042, but it was closed as a duplicate of https://github.com/nodejs/node/issues/48673.

**Comment by nzakas** [comment] 2023-12-22 00:34
Closing, as this is a Node.js issue and not an ESLint issue.

**Closed by nzakas** 2023-12-22 00:34 UTC
Labels: bug, core, repro:yes
