### ISSUE TITLE
object-curly-newline --fix violates max-len

### ISSUE THREAD

**Issue by freshp86** [eslint/eslint#8483] opened 2017-04-19 23:13 UTC
ESLint Version: v3.19.0
Node Version: v7.9.0

```js
module.exports = {
  'env': {
    'browser': true,
    'es6': true
  },
  'extends': 'eslint:recommended',
  'rules': {
    'object-curly-newline': ['error', {multiline: true}],
    'max-len': ['error', 80],
  }
```

**Before**
```js
/** some loooooooooooooooooooooooooooooong comment goes here */ var foo = {
  a: true
};
```

**After invoking ESLint with the --fix flag the file is modified as follows**
```js
/** some loooooooooooooooooooooooooooooong comment goes here */ var foo = {a: true};
```
And there is an error reported
```
  1:1  error  Line 1 exceeds the maximum line length of 80  max-len
✖ 1 problem (1 error, 0 warnings)
```

**What did you expect to happen?**
Fixing object-curly-newline violation should not ignore max-len rule.

**What actually happened?**
ESLint fixed object-curly-newline violation, but now it violates max-len rule.

Ideally I would like ESLint to allow new line characters within object literals that have a single property, but that seems to be tracked by https://github.com/eslint/eslint/issues/7609.

**Comment by not-an-aardvark** [comment] 2017-04-19 23:23
Thanks for the report. However, this is working as intended -- autofixers for rules such as `object-curly-newline` don't make any guarantees about how other rules will respond to a given autofix.

**Comment by freshp86** [comment] 2017-04-19 23:31
Given that max-len is not autofixable, is there a workaround? Are there any plans to make max-len autofixable? Or perhaps this could be one more reason that fixing https://github.com/eslint/eslint/issues/7609 would be worth it (it would sidestep this problem).

**Comment by not-an-aardvark** [comment] 2017-04-20 01:48
The workaround is to run eslint with the `--fix` flag, and then modify your code as appropriate to keep it within the maximum line length. Making `max-len` autofixable isn't out of the question, but it would be difficult for the `max-len` autofixer to determine where to put a linebreak because other rules like `object-curly-newline` might impose restrictions that would prevent linebreaks from being inserted in certain places.

**Comment by not-an-aardvark** [comment] 2017-04-26 22:40
Closing because this is working as intended.

**Closed by not-an-aardvark** 2017-04-26 22:40 UTC
Labels: works as intended
