### ISSUE TITLE
Discussion: Per-rule autofixing

### ISSUE THREAD

**Issue by kaicataldo** [eslint/eslint#8018] opened 2017-02-02 22:02 UTC
We have autofixers that, if run on unfinished code, can be unsafe. A prime example of this is someone using an editor integration that fixes on save. This issue is for discussing how we could give consumers a way to run per-rule autofixing. 

@eslint/eslint-team

Edit: Just to be clear, this issue was created as part of the resolution of [this discussion](https://github.com/eslint/tsc-meetings/blob/master/notes/2017/2017-02-02.md#httpsgithubcomeslinteslintpull7841) at the last TSC meeting.

**Comment by ilyavolodin** [comment] 2017-02-02 22:26
I have a few suggestions. First of all, we already discussed the need to add new rule states, something like `fixOrError`/`fixOrWarn` here: https://github.com/eslint/eslint/issues/5329#issuecomment-185991487
We also mark fixable rules in the metadata. We currently only mark rules with either `whitespace` or `code`. I suggest we add one more category: `unsafe` or `editor unsafe` and mark any rule that can potentially result in unexpected behavior in the editor with that category.
We should provide a hook point from our API that would allow consumers to filter the list of fixes before they are applied to the code. This would provide a way for editor integrations to filter out `unsafe` rules automatically.

**Comment by mysticatea** [comment] 2017-02-02 22:30
I'd like to use different settings between fixOnSave and executeFixCommand.
The former's target might be incomplete code (I press `ctrl+s` frequently), but the latter is explicitly I do autofix.

So I think my editor should have those settings as editor's setting. 
I think it's possible with the current ESLint if editors support it. For example:

```js
// setting.json
{
    "eslint.options": {
    },
    "eslint.autoFixOnSave": {
        "enabled": true,
        "options": {
            "rules": {
                "prefer-const": "off"
            }
        }
    }
}
```

So this might be "group disabling feature" (unsafe group?) actually.

**Comment by alberto** [comment] 2017-02-02 22:34
Since this seems targeted mainly at editor integrations, I think we should try to involve plugin authors here. AFAIK atom's plugin doesn't use the API.

**Comment by mysticatea** [comment] 2017-02-02 22:42
`vscode-eslint` is using CLIEngine then it applies `fix` properties of the report to editor's buffer manually. (I wrote the first version of the autofix feature)

**Comment by not-an-aardvark** [comment] 2017-02-02 22:45
I like the idea of allowing per-rule autofixing, but I'm a bit concerned about whether we would be able to accurately describe whether something is "editor-unsafe". Depending on where the user's cursor is, wouldn't almost any fix be editor-unsafe?

For example, suppose I'm in the middle of typing a string:

```js
/* eslint quotes: [error, "single", {"avoidEscape": true}] */

var foo = "this string is still in progress "
```

The autofixer will change the quotes to single quotes. But it's possible I meant to use

```js
/* eslint quotes: [error, "single", {"avoidEscape": true}] */

var foo = "this string is still in progress and now it's done"
```

...which requires double quotes.

---

I think the main thing that determines whether a fix is "editor-safe" is the *range* of code that the rule takes into account. For example, with the `avoidEscape` option enabled, the `quotes` rule takes into account the range starting at the beginning of the string, and ending at the end of the string.

If the user's cursor is in this range, then the fix is "editor-unsafe", because the user might edit something that affects the fix. On the other hand, if the user's cursor is outside this range, the fix is "editor-safe", because nothing the user types will affect the validity of the fix.

With the `avoidEscape` option disabled, the rule's "checking range" is only a single character: the quote character at the start of the string. So a fix is always safe in that case. If the checking range for a rule is ever more than a single character, a fix might not be editor-safe if the user is editing that range.

ESLint doesn't know where the user's cursor is. So if we wanted to mark fixes as unsafe, our only option would be to consider all rules that have a "checking range" of more than a single character. I haven't looked into how many rules only check for the presence of a single character, but I suspect this would require us to mark the majority of fixes as editor-unsafe.

On the other hand, editor plugins can tell where the user's cursor is, which allows them to make more intelligent judgements about whether a fix gets in the way of what the user is doing. So I think providing a hook to filter fixes is the best option here.

**Comment by ilyavolodin** [comment] 2017-02-02 23:09
Good point @not-an-aardvark on cursor positioning. In that case I think we should drop `unsafe` group and go with two other suggestions. If editors are using our API, they can hook into filtering function, and remove fixes that they might consider unsafe. If they are using CLI, they can create a temporary config with some of the rules without autofixes.

**Comment by alberto** [comment] 2017-02-02 23:35
ping @Arcanemagus @roadhump @lcd047 @natesilva @angelozerr @idok @dbaeumer

**Comment by lydell** [comment] 2017-02-03 22:28
I’ve only recently started to use `eslint --fix` as part of my editing workflow, so I guess I haven’t run into any problems just yet – which makes me curious. Other than @not-an-aardvark’s quotes examples, could somebody provide a few good examples of unwanted fixing while editing? :)

**Comment by nzakas** [comment] 2017-02-05 17:56
To pop the stack a moment, I'm not sure that the problem (editor integrations) necessarily maps directly to the proposed solution (per-rule fixes). Before going down the road of a significant change to ESLint, are we sure this is the only solution to the problem?

**Comment by Arcanemagus** [comment] 2017-02-07 22:59
Personally I don't think this is a problem that needs fixing.

If somebody is asking for ESLint to fix issues with their code, then they are _expecting_ it to make (sometimes significant) changes to the code. The fact that this can have unexpected results on unfinished code is the main secondary reason that the "fix on save" functionality is disabled by default in the Atom package (the primary being we don't want it running for people not expecting it).

This means that if somebody has enabled that option, they are explicitly asking for their code to be modified on every save. If somebody is saving quite often while working on code, and the fix on save functionality is messing up the code it might be a good idea for them to simply re-disable that option as it isn't a very good fit for them. I personally only run the fix command manually as I tend to save often and don't want changes while I'm in the middle of working on it.

So... to me this sounds like both wanting ESLint to modify the code, but at the same time _not_, which is a bit silly. That being said, this is obviously something at least some people want, so it can definitely be worked in if the "checking range" is exposed as @not-an-aardvark suggested earlier.

**Comment by IanVS** [comment] 2017-02-08 01:15
Getting back to the original question posted by @kaicataldo,

>This issue is for discussing how we could give consumers a way to run per-rule autofixing.

Technically, that already exists, right?  If a user wants to avoid auto-fixing a particular rule, they can use:

```
eslint somedir --fix --rule "somerule: 0"
```

Or, if they want to whitelist a set of rules, they can use `--no-eslintrc` and specify rules directly or use `--config` and point to a particular config that they want to use for fixes.

All-in-all, I'm :-1: for adding any more complexity to ESLint to support a use case that frankly doesn't seem all that compelling, and is already largely supported anyway.

**Comment by ljharb** [comment] 2017-02-08 01:22
This is a very important use case for me. Autofixes always have to have human review, and it's much easier to review a PR that make a sweeping change across the codebase for a single rule, rather than one that makes autofixes to warnings too, and whatever other errors might exist.

Using `--no-eslintrc` doesn't help because i *need* most of the config in there. However, if there was a `--disable-all-rules` switch (which would trump all inline comments and config files), I could use that, plus `--rule blah --fix`, and that would give me what I need. Is that something that would be OK to add?

**Comment by IanVS** [comment] 2017-02-08 04:09
FWIW, I made a proposal (https://github.com/eslint/eslint/issues/8039) which I think would address the use case raised by @ljharb (fixing one rule at a time), with the possibility for editors to control how fixes are applied as well (if they are using `CLIEngine`, at least).

**Comment by nzakas** [comment] 2017-02-09 18:22
> However, if there was a --disable-all-rules switch (which would trump all inline comments and config files), I could use that, plus --rule blah --fix, and that would give me what I need. Is that something that would be OK to add?

That seems pretty confusing. 

If the use case we want to solve is "how do I apply only some fixes?" then I'd be more apt to suggest letting the `--fix` option accept a comma-delimited list of rules that should be fixed. That solves the use case but does not solve the editor integration problem mentioned originally. 

It still seems like the percentage of potential unwanted fixes vs. wanted fixes in quite small, so my vote would still be just to try to fix the individual rules and circumstances under which the unwanted fixes occur rather than making any big change.

**Comment by ljharb** [comment] 2017-02-09 18:31
In particular, I'd be content with the combination of `--fix=errors` and `--rule`, since "fixing warnings" is the reason we never are able to use autofixing (we only ever want warnings fixed manually).

**Comment by alberto** [comment] 2017-03-11 19:01
Thanks for your interest in improving eslint. Unfortunately, it looks like this issue didn't get enough support from the team and so I'm closing it. While we wish we'd be able to accommodate everyone's requests, we do need to prioritize. We've found that issues failing to reach consensus after 21 days tend to never do it, and as such, we close those issues. This doesn't mean the idea isn't interesting, just that it's not something the team can commit to.

**Closed by alberto** 2017-03-11 19:01 UTC
Labels: core, evaluating, needs bikeshedding

**Comment by ljharb** [comment] 2017-03-11 19:25
@alberto this issue was created by a core team member, as a result of a TSC decision - does it fall under the standard 21 day policy?

**Comment by IanVS** [comment] 2017-03-12 14:17
@ljharb https://github.com/eslint/eslint/issues/8039 was accepted, and I plan to work on it today.  It will give a way to control which rules are fixed, at least when `CLIEngine` is used.  Hopefully that will meet at least some of the needs which this issue was discussing.
