### ISSUE TITLE
Dynamic Imports and BigInt have arrived at Stage 4 🎉

### ISSUE THREAD

**Issue by mysticatea** [eslint/eslint#11803] opened 2019-06-04 13:11 UTC
> - https://github.com/tc39/proposals/commit/b04295ff4af51c143c62df62947ae7cb25759691
> - https://github.com/tc39/proposals/pull/217 ( [Stage 4 acceptance (pending editor signoff on PR)](https://github.com/rwaldron/tc39-notes/blob/master/meetings/2019-06/june-4.md#bigint-to-stage-4) )

Dynamic Imports and BigInt have arrived at Stage 4.
This is the tracking issue to support the new syntaxes.

- [x] https://github.com/estree/estree/pull/198 ESTree Spec Update
- [x] https://github.com/acornjs/acorn/pull/844 Acorn Update
- [x] https://github.com/eslint/eslint-visitor-keys/pull/8 `eslint-visitor-keys` Update
- [x] https://github.com/eslint/espree/pull/415 `espree` Update
- [x] ESLint Update 1: the following stuff look like to need update.
    - #11983 envs should have new globals (`BigInt`, `BigInt64Array`, and `BigUint64Array`)
    - #11983 `CodePathAnalyzer`: should recognize `ImportExpression` node as a throwable node.
    - #11983 `astUtils.getPrecedence(node)`: should recognize `ImportExpression` literals.
    - #11983 `astUtils.isNullLiteral(node)`: should recognize BigInt literals.
    - #11983 `func-call-spacing` rule: should recognize `ImportExpression` node. (or new rule?)
    - #11983 `function-paren-newline` rule: should recognize `ImportExpression` node. (or new rule?)
    - #11983 `indent` rule: should recognize `ImportExpression` node.
    - #11983 `new-cap` rule: should recognize `BigInt` function.
    - #11983 `no-extra-parens` rule: should recognize `ImportExpression` node.
    - #11802 `valid-typeof` rule: should recognize BigInt type.
- [ ] ESLint Update 2: the following stuff look like to need update, but breaking changes.
    - ~~`no-compare-neg-zero` rule: should recognize BigInt literals.~~
    - #12701 `no-extend-native` rule: should recognize `BigInt` function.
    - #12701 `no-magic-number` rule: should recognize BigInt literals.
    - #12701 `yoda` rule: should recognize BigInt literals.

**Comment by g-plane** [comment] 2019-06-04 13:20
I have opened an issue at Acorn's repo: https://github.com/acornjs/acorn/issues/833 .

**Comment by mercmobily** [comment] 2019-06-09 12:06
While this gets implemented (thank you!), is there a way to get around it with an ignore?
At the moment, if you have:

    import(resolvedPageUrl)

you get:

    Parsing error: 'import' and 'export' may only appear at the top level

The problem is that this is a parsing error... so the file doesn't get linted at all.
Is there a workaround while we wait for this to actually land? (It looks like it may be a little while!)

**Comment by g-plane** [comment] 2019-06-09 12:42
You can use `babel-eslint` as parser.

**Comment by dandv** [comment] 2019-06-27 02:54
> You can use `babel-eslint` as parser.

I'm trying to be babel-free.

Please revisit #11189 as well.

**Comment by g-plane** [comment] 2019-06-27 02:56
Don't worry. Dynamic imports will be supported by ESLint itself finally. However, this is still in progress, so you need `babel-eslint` at present.

**Comment by mysticatea** [comment] 2019-06-27 04:23
Yeah, it's working in progress. As the issue description says, we are awaiting ESTree spec to be determined because we cannot implement it until the spec gets stable.

**Comment by mdjermanovic** [comment] 2019-07-14 04:22
I guess `no-octal` doesn't need any changes, apart from a couple of test cases perhaps?

`typeof node.value === "number"` condition will ignore bigints in all environments.

This rule disallows `017`, not `0o17`, so `0o17n` should be fine.

`017n` should be already a syntax error,

**Comment by mysticatea** [comment] 2019-07-14 05:01
Oh, you are right.

**Comment by mysticatea** [comment] 2019-08-12 11:21
We are still awaiting ESTree's decide. I'm wondering that we should fork the AST spec because that PR has been inactive since two months ago.

**Comment by mysticatea** [comment] 2019-08-12 12:29
Yay, that PR has been merged!

**Comment by mercmobily** [comment] 2019-08-12 21:00
acornjs/acorn#844 has been merged too

**Comment by mercmobily** [comment] 2019-08-12 21:01
#11802 has also been merged

**Comment by abdonrd** [comment] 2019-08-13 11:52
https://github.com/eslint/eslint-visitor-keys/pull/8 has also been merged!

**Comment by NemoStein** [comment] 2019-08-16 16:10
Now that we have https://github.com/estree/estree/commit/9a38106c285853370ebf94fed05dccaa05b3f936 in ESTree spec, what is the status of this issue?

**Comment by platinumazure** [comment] 2019-08-16 18:00
@NemoStein Please look at the task list in the initial post. At this point, we have updated espree and just need to release espree and consume in ESLint, and then we can review and merge PRs like #11983.

I'm hoping we can make big strides in this area for our users with the upcoming ESLint minor release sometime this weekend. But I can't promise anything. :smile:

**Comment by jesperkristensen** [comment] 2019-09-01 07:12
I noticed today that dynamic imports now works with the latest eslint release, even though this issue has not been updated.

**Comment by mercmobily** [comment] 2019-09-01 07:16
Hi,

Do they? From master, or npm?

Merc.

**Comment by mysticatea** [comment] 2019-09-01 07:22
This issue is updated. See the issue description; we have not done the last item "ESLint Update 2: the following stuff look like to need update, but breaking changes.", we will do it on 7.0.0 release.

The syntax support is not completed, but you can use `ecmaVersion:2020` since ESLint 6.2.0.
See https://eslint.org/blog/2019/08/eslint-v6.2.0-released

**Comment by jesperkristensen** [comment] 2019-09-01 07:31
Oh, the issue was updated, it's just GitHub that only sends notifications when a new comment is added, but not when a comment is edited.

**Comment by mercmobily** [comment] 2019-09-01 10:59
Question: is everything except "ESLint Update 2: the following stuff look like to need update, but breaking changes." been released in the NPM distributed package?

**Comment by mysticatea** [comment] 2019-09-01 11:43
Yes. Those are in 6.2.0.

**Comment by tituswoo** [comment] 2019-09-24 22:26
👋 Hey folks! I've been trying to get dynamic imports working with eslint 6.4.0 but haven't had luck getting it to work. It's my understanding from the conversation and [v6.2.0 changelog](https://eslint.org/blog/2019/08/eslint-v6.2.0-released#enhancements) that dynamic imports should be working as of eslint 6.2, right? However eslint v6.4.0 is still throwing the following error for me whenever I attempt to use a dynamic import 😭 

```
0:0 error  Parsing error: Invalid ecmaVersion
```

Also, @mysticatea I'm probably missing something really obvious, 😅 but in my `.eslintrc.json`, eslint is complaining about `2020` not being a valid `ecmaVersion`:

```
"parserOptions": {
    "sourceType": "module",
    "ecmaVersion": 2020
},
```

> This issue is updated. See the issue description; we have not done the last item "ESLint Update 2: the following stuff look like to need update, but breaking changes.", we will do it on 7.0.0 release.
> 
> The syntax support is not completed, but you can use `ecmaVersion:2020` since ESLint 6.2.0.
> See https://eslint.org/blog/2019/08/eslint-v6.2.0-released

Thanks for the help! 🙏

**Comment by mysticatea** [comment] 2019-09-24 22:29
You are looking using old ESLint or at least old parser. Please open a new issue with our issue template.

**Comment by mdjermanovic** [comment] 2019-12-10 01:45
> no-compare-neg-zero rule: should recognize BigInt literals.

BigInt type doesn't have negative zero value?

```js
Object.is(-0n, 0n); // true
```

So perhaps `no-compare-neg-zero` shouldn't report bigint literals? Or maybe it still should, for the case if user might be unaware of this fact. But then it could be useful to report any occurrence of  `-0n` in the code  (not just comparisons), maybe behind an option or in a new rule?

> no-extend-native rule: should recognize BigInt function.

This seems to already work by itself:

* [Demo with /* eslint-env es2020 */](https://eslint.org/demo#eyJ0ZXh0IjoiLyogZXNsaW50IG5vLWV4dGVuZC1uYXRpdmU6IGVycm9yICovXG4vKiBlc2xpbnQtZW52IGVzMjAyMCAqL1xuXG5CaWdJbnQucHJvdG90eXBlLmZvbyA9IDE7XG4iLCJvcHRpb25zIjp7InBhcnNlck9wdGlvbnMiOnsiZWNtYVZlcnNpb24iOjExLCJzb3VyY2VUeXBlIjoic2NyaXB0IiwiZWNtYUZlYXR1cmVzIjp7fX0sInJ1bGVzIjp7fSwiZW52Ijp7fX19)

* [Demo with /* global BigInt */](https://eslint.org/demo#eyJ0ZXh0IjoiLyogZXNsaW50IG5vLWV4dGVuZC1uYXRpdmU6IGVycm9yICovXG4vKiBnbG9iYWwgQmlnSW50ICovXG5cbkJpZ0ludC5wcm90b3R5cGUuZm9vID0gMTtcbiIsIm9wdGlvbnMiOnsicGFyc2VyT3B0aW9ucyI6eyJlY21hVmVyc2lvbiI6MTEsInNvdXJjZVR5cGUiOiJzY3JpcHQiLCJlY21hRmVhdHVyZXMiOnt9fSwicnVsZXMiOnt9LCJlbnYiOnt9fX0=)

I guess it works with a manually added `BigInt` ESLint global since v11.6.0 of the `globals` package.

**Comment by ljharb** [comment] 2019-12-10 01:48
It should probably warn on any occurrence if -0n

**Closed** 2020-01-17 15:55 UTC
Labels: accepted, core, feature, new syntax, rule
