### ISSUE TITLE
Changes to make for v1.0.0

### ISSUE THREAD

**Issue by btmills** [eslint/eslint#1898] opened 2015-02-28 04:16 UTC
The following rules are deprecated and should be removed in v1.0.0:

- [ ] `generator-star`
- [ ] `global-strict`
- [ ] `no-comma-dangle`
- [ ] `no-empty-class`
- [ ] `no-extra-strict`
- [ ] `no-space-before-semi`
- [ ] `no-wrap-func`
- [ ] `space-after-function-name`
- [ ] `space-before-function-parentheses`
- [ ] `space-in-brackets`
- [ ] `space-unary-word-ops`
- [ ] `spaced-line-comment`

To remove a rule:

1. Update the deprecation notice in `docs/rules/{rule-name}.md` to indicate removal.
1. Delete `lib/rules/{rule-name}.js`.
1. Delete `tests/lib/rules/{rule-name}.js`.
1. Remove the rule's default setting in `conf/eslint.json` and any environments in `conf/environments.js`.
1. Move the rule's entry in `docs/rules/README.md` to the Removed section.

In addition, the following behaviors are deprecated and need to be changed for v1.0.0:

- [ ] The existing default behavior for `strict` with no mode option should be removed. The new default when the rule is enabled without any options should be `"function"`. This change should be reflected in the rule's [documentation](http://eslint.org/docs/rules/strict#deprecated-mode-default).

- [ ] In `lib/api.js`, stop exporting `cli`.

**Comment by btmills** [comment] 2015-02-28 04:20
This issue combines #1692, #1861, and #1889. @nzakas those three can be closed once you're satisfied everything from those is present here.

> The existing default behavior for strict with no mode option should be removed and the default should be changed to one of "never", "global", or "function".

I'm in favor of `"function"` as the new default since it's most similar to the existing default. Thoughts?

**Comment by nzakas** [comment] 2015-02-28 04:22
Yup, function by default and global in the node environment.

**Comment by btmills** [comment] 2015-02-28 04:25
> Yup, function by default and global in the node environment.

I've updated the issue description.

**Comment by ilyavolodin** [comment] 2015-02-28 04:52
I would suggest not deleting documentation for rules, and instead marking them as no longer supported with a link to the new rule. Some people might stick with the older version of ESLint for a while.

**Comment by nzakas** [comment] 2015-02-28 15:59
That's a good idea.

**Comment by btmills** [comment] 2015-02-28 22:53
I like it. The `gensite` target in `Makefile.js` should still work with version added stamps since it's based on the documentation files. Might we want to do something similar for the version in which a rule was removed?

**Comment by lo1tuma** [comment] 2015-03-06 16:26
I’ve added `no-comma-dangle` to the list of rules which should be removed with ESLint 1.0.

**Comment by btmills** [comment] 2015-03-26 22:14
Added `generator-star` as per #1987 and `space-before-function-parentheses` as per #2050.

**Comment by nzakas** [comment] 2015-03-27 00:36
:+1:

**Comment by btmills** [comment] 2015-04-03 03:34
Based on [#2180 (comment)](https://github.com/eslint/eslint/issues/2180#issuecomment-87722150), will the `--rulesdir` option be removed in v1.0?

**Comment by btmills** [comment] 2015-04-03 03:39
The [Node.js API docs](http://eslint.org/docs/developer-guide/nodejs-api#deprecated-apis) state:

> the `cli` object has been deprecated in favor of `CLIEngine`. It will be removed at some point in the future.

Will this be removed as part of v1.0?

**Comment by nzakas** [comment] 2015-04-03 16:25
I think we need to keep `--rulesdir` for now, probably remove in 2.0.0. 

We should stop exporting `cli` for 1.0.0

**Comment by ilyavolodin** [comment] 2015-05-13 02:55
`no-empty-class` should be removed in 1.0.0 as well. It's being replaced by `no-empty-character-class`

**Comment by btmills** [comment] 2015-05-13 16:50
Updated to include `no-empty-character-class`.

**Comment by xjamundx** [comment] 2015-05-14 23:04
@btmills `no-empty-class` should be removed, not `no-empty-character-class` :)

**Comment by btmills** [comment] 2015-05-15 00:29
@xjamundx ...usually I can read. Fixed!

**Comment by gyandeeps** [comment] 2015-06-03 03:07
@btmills Please add `spaced-line-comment` to the deprecate rule list.

**Comment by btmills** [comment] 2015-06-03 14:07
@gyandeeps Updated to include `spaced-line-comment`.

**Comment by IanVS** [comment] 2015-06-29 20:33
Has anyone done work on this so far?  It seems pretty straight-forward, if I'm not missing something.  I'm happy to start working on it if the issue is ready and accepted.

**Comment by btmills** [comment] 2015-06-29 20:48
I'm on my phone now, but I'll go through in the next day or so and make sure this includes everything, then ask for a couple :+1: confirmations.

**Comment by btmills** [comment] 2015-06-30 03:08
1. Since we're no longer turning rules on by default, I changed the task for `strict` to say that it should default to `"function"` when it is enabled without specifying a mode. (Previously it was to be `"function"` in `conf/eslint.json`.)
2. I updated removal instructions to preserve documentation with a removal notice per @ilyavolodin's [comment](https://github.com/eslint/eslint/issues/1898#issuecomment-76510589).
3. Added a note to stop exporting `cli` per @nzakas' [comment](https://github.com/eslint/eslint/issues/1898#issuecomment-89343239).
4. `space-in-brackets` and `spaced-line-comment` are both marked as deprecated in `docs/rules/README.md`, but their documentation includes no deprecation notice. Are we still removing them? (/cc @xjamundx for `space-in-brackets` and @gyandeeps for `spaced-line-comment`, it looks like you would each be most familiar with those respective rules.) The current list of twelve rules matches all of those marked as deprecated in the rules index.

@eslint/eslint-committers pending answers to (4), does this cover everything? As a matter of procedure, I know I'd find it much easier to review changes if we asked for one PR per checkbox, but I'll do my best if I'm overruled.

**Comment by gyandeeps** [comment] 2015-06-30 03:13
Yes we are removing spaced-line-comment rule.

**Comment by lo1tuma** [comment] 2015-06-30 06:38
I think it would be useful to document the version number of eslint where the rule was removed. 

Can you check if the documentation generation still works. Especially adding the link to the rule source code and adding the version number.

**Comment by nzakas** [comment] 2015-06-30 19:36
These are the last tasks after the other 1.0.0 ones are complete.

Agree it would be nice to document when rules were removed. We will need to keep the docs for those rules up for a while to help those who are using older versions.

**Comment by ilyavolodin** [comment] 2015-07-01 22:25
One more task, just noticed in documentation for `strict` rule there's a paragraph that is saying that "default" option will be deprecated in 1.0.0. Here's the link: http://eslint.org/docs/rules/strict#deprecated-mode-default

**Comment by btmills** [comment] 2015-07-01 22:56
@ilyavolodin I added that link to the `strict` task.

> These are the last tasks after the other 1.0.0 ones are complete.

@nzakas So that I can prioritize, what order are you planning for the 1.0 tasks?

**Comment by nzakas** [comment] 2015-07-02 15:28
This issue is last as it's the most destructive. We also need the warning system fit missing rules to be complete before we do this.

Otherwise, everything is roughly equal in priority.

**Comment by IanVS** [comment] 2015-07-02 18:43
I don't see any issues with a `v1.0.0` milestone for a missing rule warning system.  (Nor any issue at all for it, but I haven't sifted through all 100+).  

It sounds like this should be the last task that is merged.  Does that mean it is also the last which should be worked on?  I would love to contribute to v1.0.0 in some way, and this seems like a task I could handle and start creating a PR for.

**Comment by gyandeeps** [comment] 2015-07-02 18:45
@IanVS I think this is what you are looking for https://github.com/eslint/eslint/issues/1549

**Comment by nzakas** [comment] 2015-07-02 19:32
@IanVS Yes, this would be the last merged as it's the most destructive. It does also rely on #1549 as a way to mark rules as removed. 

@gyandeeps are you still working on #1549 and #2736? Either of those might be good for @ianvs to take a look at.

**Comment by gyandeeps** [comment] 2015-07-02 19:39
@IanVS Feel free to pick anyone.

**Comment by nzakas** [comment] 2015-07-03 18:29
@ianvs do you want to look at #2736?

**Comment by IanVS** [comment] 2015-07-04 21:56
@nzakas Sure, should have a PR ready shortly.

**Comment by IanVS** [comment] 2015-07-09 02:35
It seems that coverage reports in `coverage/lcov-report/lib/rules/` are not cleaned out when a rule is removed and tests are rerun.  Is that possible?

**Comment by IanVS** [comment] 2015-07-10 02:30
I have a PR ready to go as soon as this is accepted.

**Comment by nzakas** [comment] 2015-07-10 15:17
Ready!

**Closed** 2015-07-14 14:51 UTC
Labels: accepted, breaking, core
