### ISSUE TITLE
SyntaxError: Unexpected token - } catch {

### ISSUE THREAD

**Issue by martinoppitz** [eslint/eslint#13838] opened 2020-11-12 09:43 UTC
https://github.com/eslint/eslint/blob/4255f360a9e107dd34fb7bf4f4e0e6a8d340abb6/bin/eslint.js#L93

**Comment by yeonjuan** [comment] 2020-11-12 13:13
Hi :) @martinoppitz 
What node version did you use? ESLint is supporting node version "^10.12.0 || >=12.0.0". Please check your node version.

**Comment by nguyenj** [comment] 2020-11-12 17:12
I'm also getting this error. Here's what I have:

bash output:
```sh
$ npm run lint
> eslint . --ext .js

/Users/user/code/project/node_modules/eslint/bin/eslint.js:93
        } catch {
                ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
```

npm log:
```log
info it worked if it ends with ok
verbose cli [ '/Users/john/n/bin/node', '/usr/local/bin/npm', 'run', 'lint' ]
info using npm@6.14.8
info using node@v12.13.0
verbose run-script [ 'prelint', 'lint', 'postlint' ]
verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
verbose stack     at EventEmitter.emit (events.js:210:5)
verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
verbose stack     at ChildProcess.emit (events.js:210:5)
verbose stack     at maybeClose (internal/child_process.js:1021:16)
verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
verbose Darwin 19.6.0
verbose argv "/Users/john/n/bin/node" "/usr/local/bin/npm" "run" "lint"
verbose node v12.13.0
verbose npm  v6.14.8
```

package.json:
```package.json
{
  "scripts": {
    "lint": "eslint . --ext .js"
  }
}
```

**Comment by btmills** [comment] 2020-11-15 03:47
Thanks for the additional info @nguyenj. Node 12.13.0 [should support](https://node.green/#ES2019-misc-optional-catch-binding) optional `catch` bindings, so I'm not sure what's going on. I tried to reproduce the exception by running ESLint on Node 12.13.0, but everything worked normally. Does the exception reproduce if you run ESLint in a test project without any plugins? I wouldn't think that should matter, but at least it removes some variables. If it does, pushing it up as an example repository that we could clone and run would help.

**Comment by nguyenj** [comment] 2020-11-24 02:05
@btmills I found the issue, a dependency package was causing an issue. Thank you for responding!

**Comment by btmills** [comment] 2020-11-24 02:11
Glad you figured it out @nguyenj. @martinoppitz do you have any more info here?

**Comment by btmills** [comment] 2020-11-30 00:34
Closing for now since at least one case has been resolved and we have no information on the original. @martinoppitz if you have more information for us we'd be happy to take a look!

**Closed by btmills** 2020-11-30 00:34 UTC
Labels: needs info, triage

**Comment by prototypicalpro** [comment] 2020-12-04 18:52
Hello! I was able to reproduce this issue using the [latest version of ESLint (v7.14.0) on the demo page](https://eslint.org/demo#eyJ0ZXh0IjoidHJ5IHtcbiAgdHJ1ZTtcbn0gY2F0Y2gge1xufVxuIiwib3B0aW9ucyI6eyJwYXJzZXJPcHRpb25zIjp7ImVjbWFWZXJzaW9uIjo1LCJzb3VyY2VUeXBlIjoic2NyaXB0IiwiZWNtYUZlYXR1cmVzIjp7fX0sInJ1bGVzIjp7ImNvbnN0cnVjdG9yLXN1cGVyIjoyLCJmb3ItZGlyZWN0aW9uIjoyLCJnZXR0ZXItcmV0dXJuIjoyLCJuby1hc3luYy1wcm9taXNlLWV4ZWN1dG9yIjoyLCJuby1jYXNlLWRlY2xhcmF0aW9ucyI6Miwibm8tY2xhc3MtYXNzaWduIjoyLCJuby1jb21wYXJlLW5lZy16ZXJvIjoyLCJuby1jb25kLWFzc2lnbiI6Miwibm8tY29uc3QtYXNzaWduIjoyLCJuby1jb25zdGFudC1jb25kaXRpb24iOjIsIm5vLWNvbnRyb2wtcmVnZXgiOjIsIm5vLWRlYnVnZ2VyIjoyLCJuby1kZWxldGUtdmFyIjoyLCJuby1kdXBlLWFyZ3MiOjIsIm5vLWR1cGUtY2xhc3MtbWVtYmVycyI6Miwibm8tZHVwZS1lbHNlLWlmIjoyLCJuby1kdXBlLWtleXMiOjIsIm5vLWR1cGxpY2F0ZS1jYXNlIjoyLCJuby1lbXB0eSI6Miwibm8tZW1wdHktY2hhcmFjdGVyLWNsYXNzIjoyLCJuby1lbXB0eS1wYXR0ZXJuIjoyLCJuby1leC1hc3NpZ24iOjIsIm5vLWV4dHJhLWJvb2xlYW4tY2FzdCI6Miwibm8tZXh0cmEtc2VtaSI6Miwibm8tZmFsbHRocm91Z2giOjIsIm5vLWZ1bmMtYXNzaWduIjoyLCJuby1nbG9iYWwtYXNzaWduIjoyLCJuby1pbXBvcnQtYXNzaWduIjoyLCJuby1pbm5lci1kZWNsYXJhdGlvbnMiOjIsIm5vLWludmFsaWQtcmVnZXhwIjoyLCJuby1pcnJlZ3VsYXItd2hpdGVzcGFjZSI6Miwibm8tbWlzbGVhZGluZy1jaGFyYWN0ZXItY2xhc3MiOjIsIm5vLW1peGVkLXNwYWNlcy1hbmQtdGFicyI6Miwibm8tbmV3LXN5bWJvbCI6Miwibm8tb2JqLWNhbGxzIjoyLCJuby1vY3RhbCI6Miwibm8tcHJvdG90eXBlLWJ1aWx0aW5zIjoyLCJuby1yZWRlY2xhcmUiOjIsIm5vLXJlZ2V4LXNwYWNlcyI6Miwibm8tc2VsZi1hc3NpZ24iOjIsIm5vLXNldHRlci1yZXR1cm4iOjIsIm5vLXNoYWRvdy1yZXN0cmljdGVkLW5hbWVzIjoyLCJuby1zcGFyc2UtYXJyYXlzIjoyLCJuby10aGlzLWJlZm9yZS1zdXBlciI6Miwibm8tdW5kZWYiOjIsIm5vLXVuZXhwZWN0ZWQtbXVsdGlsaW5lIjoyLCJuby11bnJlYWNoYWJsZSI6Miwibm8tdW5zYWZlLWZpbmFsbHkiOjIsIm5vLXVuc2FmZS1uZWdhdGlvbiI6Miwibm8tdW51c2VkLWxhYmVscyI6Miwibm8tdW51c2VkLXZhcnMiOjIsIm5vLXVzZWxlc3MtY2F0Y2giOjIsIm5vLXVzZWxlc3MtZXNjYXBlIjoyLCJuby13aXRoIjoyLCJyZXF1aXJlLXlpZWxkIjoyLCJ1c2UtaXNuYW4iOjIsInZhbGlkLXR5cGVvZiI6Mn0sImVudiI6e319fQ==). As a result, I think this issue should be reopened (I can also open a new issue if that would be preferred).

**Comment by btmills** [comment] 2020-12-04 18:57
Hi @prototypicalpro, [optional `catch` binding is an ES2019 feature](https://github.com/tc39/proposals/blob/master/finished-proposals.md). Your demo link was using `ecmaVersion: 5`. If you set `ecmaVersion: 2019`, it [works fine](https://eslint.org/demo#eyJ0ZXh0IjoidHJ5IHtcbiAgdHJ1ZTtcbn0gY2F0Y2gge1xufVxuIiwib3B0aW9ucyI6eyJwYXJzZXJPcHRpb25zIjp7ImVjbWFWZXJzaW9uIjoxMCwic291cmNlVHlwZSI6InNjcmlwdCIsImVjbWFGZWF0dXJlcyI6e319LCJydWxlcyI6eyJjb25zdHJ1Y3Rvci1zdXBlciI6MiwiZm9yLWRpcmVjdGlvbiI6MiwiZ2V0dGVyLXJldHVybiI6Miwibm8tYXN5bmMtcHJvbWlzZS1leGVjdXRvciI6Miwibm8tY2FzZS1kZWNsYXJhdGlvbnMiOjIsIm5vLWNsYXNzLWFzc2lnbiI6Miwibm8tY29tcGFyZS1uZWctemVybyI6Miwibm8tY29uZC1hc3NpZ24iOjIsIm5vLWNvbnN0LWFzc2lnbiI6Miwibm8tY29uc3RhbnQtY29uZGl0aW9uIjoyLCJuby1jb250cm9sLXJlZ2V4IjoyLCJuby1kZWJ1Z2dlciI6Miwibm8tZGVsZXRlLXZhciI6Miwibm8tZHVwZS1hcmdzIjoyLCJuby1kdXBlLWNsYXNzLW1lbWJlcnMiOjIsIm5vLWR1cGUtZWxzZS1pZiI6Miwibm8tZHVwZS1rZXlzIjoyLCJuby1kdXBsaWNhdGUtY2FzZSI6Miwibm8tZW1wdHkiOjIsIm5vLWVtcHR5LWNoYXJhY3Rlci1jbGFzcyI6Miwibm8tZW1wdHktcGF0dGVybiI6Miwibm8tZXgtYXNzaWduIjoyLCJuby1leHRyYS1ib29sZWFuLWNhc3QiOjIsIm5vLWV4dHJhLXNlbWkiOjIsIm5vLWZhbGx0aHJvdWdoIjoyLCJuby1mdW5jLWFzc2lnbiI6Miwibm8tZ2xvYmFsLWFzc2lnbiI6Miwibm8taW1wb3J0LWFzc2lnbiI6Miwibm8taW5uZXItZGVjbGFyYXRpb25zIjoyLCJuby1pbnZhbGlkLXJlZ2V4cCI6Miwibm8taXJyZWd1bGFyLXdoaXRlc3BhY2UiOjIsIm5vLW1pc2xlYWRpbmctY2hhcmFjdGVyLWNsYXNzIjoyLCJuby1taXhlZC1zcGFjZXMtYW5kLXRhYnMiOjIsIm5vLW5ldy1zeW1ib2wiOjIsIm5vLW9iai1jYWxscyI6Miwibm8tb2N0YWwiOjIsIm5vLXByb3RvdHlwZS1idWlsdGlucyI6Miwibm8tcmVkZWNsYXJlIjoyLCJuby1yZWdleC1zcGFjZXMiOjIsIm5vLXNlbGYtYXNzaWduIjoyLCJuby1zZXR0ZXItcmV0dXJuIjoyLCJuby1zaGFkb3ctcmVzdHJpY3RlZC1uYW1lcyI6Miwibm8tc3BhcnNlLWFycmF5cyI6Miwibm8tdGhpcy1iZWZvcmUtc3VwZXIiOjIsIm5vLXVuZGVmIjoyLCJuby11bmV4cGVjdGVkLW11bHRpbGluZSI6Miwibm8tdW5yZWFjaGFibGUiOjIsIm5vLXVuc2FmZS1maW5hbGx5IjoyLCJuby11bnNhZmUtbmVnYXRpb24iOjIsIm5vLXVudXNlZC1sYWJlbHMiOjIsIm5vLXVudXNlZC12YXJzIjoyLCJuby11c2VsZXNzLWNhdGNoIjoyLCJuby11c2VsZXNzLWVzY2FwZSI6Miwibm8td2l0aCI6MiwicmVxdWlyZS15aWVsZCI6MiwidXNlLWlzbmFuIjoyLCJ2YWxpZC10eXBlb2YiOjJ9LCJlbnYiOnt9fX0=).

**Comment by jadamgreen1010** [comment] 2021-01-24 22:20
I also had this issue using SublimeLinter-eslint. I included my finding here https://github.com/SublimeLinter/SublimeLinter-eslint/issues/301

tl;dr sublime may be mapping to the wrong node version, try reinstalling nvm

**Comment by fjaxyu** [comment] 2021-01-25 22:58
This same issue occurred for me when I updated and started using a new nvm node version. Quitting terminal and re-opening stopped the error from occurring anymore, I didn't need to re-install nvm though.
