### ISSUE TITLE
object-curly-newline `[2, 'always']` complains of Flow type annotation in function parameters

### ISSUE THREAD

**Issue by ADagen** [eslint/eslint#9577] opened 2017-11-03 14:37 UTC
**Tell us about your environment**

* **ESLint Version:** 4.10.0
* **Node Version:** 8.4.0
* **npm Version:** 5.4.2

**What parser (default, Babel-ESLint, etc.) are you using?** babel-eslint@8.0.1

**Please show your full configuration:**
<details>
<summary>Configuration</summary>

```js
{
  "extends": "airbnb",
  "env": {
    "browser": true,
    "jest": true,
    "jasmine": true,
    "serviceworker": true,
    "shared-node-browser": true
  },
  "parser": "babel-eslint",
  "parserOptions": {
    "ecmaVersion": 6,
    "esversion": 6,
    "sourceType": "module",
    "ecmaFeatures": {
      "jsx": true
    }
  },
  "plugins": [
    "filenames",
    "babel",
    "flowtype"
  ],
  "globals": {
    "$": true,
    "Raven": true,
    "angular": true
    "__DEV__": true
  },
  "rules": {
    "jsx-a11y/no-static-element-interactions": [0],

    "class-methods-use-this" : [0],

    // trailing commas only for multiline object literals
    "comma-dangle": [2, "always-multiline"],

    "complexity": [2, { "max": 8 }],

    "semi": [1, "never"],

    "key-spacing": ["error", { "mode": "strict" }],

    "no-multi-spaces": [0],

    "space-before-function-paren": ["error", "never"],

    "padded-blocks": [0],

    "no-return-assign": [0],

    "max-len": ["error", {
      "code": 100,
      "comments" : 120,
      "ignoreUrls": true
    }],

    // for es6 modules
    "strict": [0],

    // filenaming convention
    "filenames/match-regex": [0],
    "filenames/match-exported": [0],

    // es2016 и es proposal/strawman support
    // with disabling original rules
    "generator-star-spacing": [1],
    "new-cap": [0],
    "array-bracket-spacing": [1],
    "object-curly-spacing": [0],
    "object-shorthand": [1],
    "arrow-parens": [0],
    "no-await-in-loop": [1],
    "flow-object-type": [0],

    "react/jsx-filename-extension":  [2, { "extensions": [".js"] }],
    "react/no-string-refs": [1],
    "react/no-render-return-value": [0],

    "import/no-unresolved" : [0],

    "import/no-extraneous-dependencies":[0],

    "babel/new-cap": [1],
    "babel/object-curly-spacing": [0],
    "babel/arrow-parens": [0],

    "flowtype/object-type-delimiter": [1],
    "flowtype/define-flow-type": 1,
    "flowtype/use-flow-type": 1,

    "require-jsdoc": [1,
      {
        "require": {
          "FunctionDeclaration": true,
          "MethodDefinition": true,
          "ClassDeclaration": true
        }
      }
    ],

    "valid-jsdoc": [1, {
      "prefer": {
        "arg": "param",
        "argument": "param",
        "class": "class",
        "return": "returns",
        "virtual": "abstract"
      },
      "preferType": {
        "Boolean": "boolean",
        "Number": "number",
        "object": "Object",
        "String": "string"
      },
      "requireReturn": true,
      "requireReturnType": false,
      "requireReturnDescription": false
    }],

    "babel/new-cap" : [0],
    "new-cap": [2, { "capIsNewExceptions": ["express.Router"] }],

    "indent": [1, 2],

    "react/no-unused-prop-types": [0],
    "react/require-default-props": [0],

    "object-curly-newline": ["error", "always"]
  },
}

```

</details>  
  
  
**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
export const getSomeData = ({
  property1,
  property2,
}: ArgumentType): ResultType => {
  ...
}
```

```bash
npm run eslint src
```

**What did you expect to happen?**
No errors

**What actually happened? Please include the actual, raw output from ESLint.**
A lot of errors in every file with flow annotations.
```bash
   29:39  error    Expected a line break after this opening brace   object-curly-newline
   29:57  error    Expected a line break before this closing brace  object-curly-newline
   50:64  error    Expected a line break after this opening brace   object-curly-newline
   50:83  error    Expected a line break before this closing brace  object-curly-newline
   ...
  133:9   error    Expected a line break after this opening brace   object-curly-newline
  133:16  error    Expected a line break before this closing brace  object-curly-newline
  143:52  error    Expected a line break after this opening brace   object-curly-newline
  143:61  error    Expected a line break before this closing brace  object-curly-newline
```

There are some kind of workarounds:
1) remove ArgumentType from source code (wat?!)
2) temporarily set `"object-curly-newline": 0`
But both of them does not make sense

**Comment by not-an-aardvark** [comment] 2017-11-03 20:07
Closing as a duplicate of https://github.com/eslint/eslint/pull/9458

**Closed by not-an-aardvark** 2017-11-03 20:07 UTC
Labels: triage
