### ISSUE TITLE
--fix doesn't add spaces around colon of conditional operator

### ISSUE THREAD

**Issue by adius** [eslint/eslint#5976] opened 2016-04-27 10:05 UTC
In the latest version of eslint `--fix` in combination with `space-infix-ops: error` doesn't add
spaces around the colon of the conditional operator.

So `isValid?'yes':'no'` becomes `isValid ? 'yes':'no'` instead of `isValid ? 'yes' : 'no'`

**Comment by alberto** [comment] 2016-04-27 17:53
Working on this

**Comment by nzakas** [comment] 2016-04-28 01:31
@adius in the future, please be sure to use our default issue template. It really helps us with issue triage. Thanks!

**Comment by gyandeeps** [comment] 2016-04-28 02:08
With multiple fix runs, we would fix both the issue so I dont think we need a change here.
FYI, this rule only reports one error at a time so technically in first eslint run it will report the error arounf `?` and no error for `:` this. For more details: https://github.com/eslint/eslint/issues/3761

**Comment by alberto** [comment] 2016-04-28 06:41
@gyandeeps Is there a reason why this rule can't report both errors, even if it is a single operator? It's not clear to me from the linked issue.

**Comment by adius** [comment] 2016-04-28 09:22
@nzakas I did. I read it and deleted all useless noise and it seems like everybody understands what I'm talking about.
So why do you want me to paste some useless boilerplate text, which doesn't help at all for the issue at hand? ^^

**Comment by nzakas** [comment] 2016-04-28 16:15
@adius because we have to triage a lot of issues and the template helps us do that. It isn't useless to us, and we'd really appreciate your help in making what is a time-consuming part of managing this project easier.

**Comment by alberto** [comment] 2016-04-28 21:38
@adius it's important because we cannot always reproduce the issue and then we have to start guessing what is going on, come back and ask again

**Comment by kaicataldo** [comment] 2016-06-06 04:02
Just tested this locally, and as @gyandeeps mentioned, I'm seeing all the errors being fixed by multipass autofix :tada: Going to go ahead and close this.

**Closed by kaicataldo** 2016-06-06 04:02 UTC
Labels: bug, evaluating, rule

**Comment by platinumazure** [comment] 2016-06-06 04:27
Still wondering if we could improve the lint reporting, for those who aren't using auto-fix? Right now we're not providing enough information (we have a false negative on the colon when the question mark is warned).

**Comment by kaicataldo** [comment] 2016-06-06 05:22
My vote is to create a new issue that focuses on that. And yeah, looking at the code, doesn't seem like a big deal to add better error reporting in. I'd be happy to do it.
