### ISSUE TITLE
Eslint raising error 'import/no-unresolved' for system modules on node v6

### ISSUE THREAD

**Issue by ken210** [eslint/eslint#5981] opened 2016-04-27 13:12 UTC
- ESLint v2.8.0
- Run lint on node v6
- Expected same result as node v5
- Raising errors for system modules `'path'`

Test case: https://github.com/ken210/eslint-node-6-bug-report

Works on node v5
```
$ nvm use 5
Now using node v5.7.0 (npm v3.6.0)
$ node -v
v5.7.0
$ ./node_modules/.bin/eslint test.js
```

On node v6
```
$ nvm use 6
Now using node v6.0.0 (npm v3.8.8)
$ node -v
v6.0.0
$ ./node_modules/.bin/eslint test.js

/opt/eduk/eslint-node-6-bug-report/test.js
  1:0   error  Resolve error: Path must be a string. Received null  import/no-unresolved
  1:22  error  Unable to resolve path to module 'path'              import/no-unresolved

✖ 2 problems (2 errors, 0 warnings)

```

**Comment by jrmull** [comment] 2016-04-27 14:00
I upgraded to node v6 this morning and noticed that my linting stopped working.  Seems like it might be related.

```
TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.extname (path.js:887:5)
    at processText (C:\Users\user\AppData\Roaming\npm\node_modules\standard\node_modules\eslint\lib\cli-engine.js:144:30)
    at CLIEngine.executeOnText (C:\Users\user\AppData\Roaming\npm\node_modules\standard\node_modules\eslint\lib\cli-engine.js:671:26)
    at Linter.lintText (C:\Users\user\AppData\Roaming\npm\node_modules\standard\node_modules\standard-engine\index.js:65:59)
    at C:\Users\user\AppData\Roaming\npm\node_modules\standard\node_modules\standard-engine\bin\cmd.js:112:16
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

**Comment by alberto** [comment] 2016-04-27 16:47
Probably related to https://github.com/nodejs/node/pull/5348

**Comment by alberto** [comment] 2016-04-27 17:26
Looks like an issue with https://github.com/benmosher/eslint-plugin-import/issues/272

**Comment by nzakas** [comment] 2016-04-28 00:54
@alberto can we close this?

**Comment by alberto** [comment] 2016-04-28 06:27
Yes, I think so. 

@jrmull yours looks like a different issue, it might be caused by `standard`. If it is not the case, please provide us something we can reproduce.

**Closed by alberto** 2016-04-28 06:27 UTC
Labels: bug, core, evaluating
