### ISSUE TITLE
eslint does not invalidate cache when updating a plugin

### ISSUE THREAD

**Issue by doberkofler** [eslint/eslint#12828] opened 2020-01-25 09:22 UTC
**The version of ESLint you are using.**
6.8.0

**The problem you want to solve.**
When updating an plugin, it seems as if the eslint cache would not be invalidated.

**Your take on the correct solution to problem.**
I believe that when eslint itself or any pluggeable component of eslint changes in version, the eslint cache should be invalidated. 

**Are you willing to submit a pull request to implement this change?**
I would love to but this is far to complex for my knowledge of eslint

**Comment by kaicataldo** [comment] 2020-01-27 21:56
Dupe of https://github.com/eslint/eslint/issues/12578. As mentioned [here](https://github.com/eslint/eslint/issues/12578#issuecomment-571873564), we'd love to evaluate an RFC for this feature.

**Closed** 2020-02-27 22:43 UTC
Labels: core, enhancement, evaluating
