### ISSUE TITLE
Eslint brace-style --fix fixes the issue, but returns error regardless

### ISSUE THREAD

**Issue by MichaelSila** [eslint/eslint#9722] opened 2017-12-15 17:04 UTC
**Tell us about your environment**

* **ESLint Version:**
v4.18.1
* **Node Version:**
v9.2.0
* **npm Version:**
v5.5.1
**What parser (default, Babel-ESLint, etc.) are you using?**
default
**Please show your full configuration:**
```json
{
	"env": {
		"es6": true
	},
	"rules": {
		"curly": ["error", "all"],
		"quotes": ["error", "single"],
		"indent": ["error", 4],
		"array-bracket-spacing":["error","always"],
		"block-spacing":["error","always"],
		"comma-dangle":"error",
		"comma-spacing":["error",{"before":false,"after":true}],
		"comma-style":["error","last"],
		"computed-property-spacing":["error","never"],
		"eol-last":["error","always"],
		"func-call-spacing":["error","never"],
		"function-paren-newline":["error","multiline"],
		"implicit-arrow-linebreak":["error","beside"],
		"key-spacing":"error",
		"keyword-spacing":"error",
		"lines-between-class-members":["error","always"],
		"new-parens":"error",
		"no-multiple-empty-lines":"error",
		"no-trailing-spaces":"error",
		"no-whitespace-before-property":"error",
		"object-curly-newline":["error",{"multiline":true}],
		"object-curly-spacing":["error","always"],
		"operator-linebreak":["error","before"],
		"padded-blocks":["error","never"],
		"quote-props":["error","always"],
		"semi-spacing":"error",
		"semi-style":["error","last"],
		"space-before-blocks":"error",
		"space-in-parens":["error","never"],
		"switch-colon-spacing":"error",
		"brace-style":"error"
	}
}
```

<summary>Configuration</summary>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

I
```js
                            if (notNull(scope.editingValue) && isValueArray(scope) && scope.editingValue.indexOf(',') !== -1) {
                                scope.editingValue = scope.editingValue.slice(0, scope.editingValue.lastIndexOf(',') + 1) + item.value;
                            } //clear last (partial) entry and replace it with selected
                            else {
                                scope.editingValue = item.value;
                            }



```

```bash
eslint -c eslint.format.json --ignore-path files.ignore '**/*.js' --fix --quiet --debug
```

**What did you expect to happen?**
Eslint to fix the issue, and exit with a successful status

**What actually happened? Please include the actual, raw output from ESLint.**

Eslint fixed the issue, but with an error status
```
editableText.directive.js
  65:29  error  Closing curly brace does not appear on the same line as the subsequent block  brace-style
```
This is, I believe, due to the comment present on the page.

**Comment by platinumazure** [comment] 2017-12-15 17:36
Hi @MichaelSila, thanks for the issue!

Can you please include the code you were linting, as well as both the fixed code and the lint messages you saw after running ESLint? Thanks!

**Comment by j-f1** [comment] 2017-12-15 17:37
@platinumazure That info is under the “Configuration” section.

**Comment by MichaelSila** [comment] 2017-12-15 17:45
Sorry for the bad formatting. The, code, before it was formatted, was

```js
                            if (notNull(scope.editingValue) && isValueArray(scope) && scope.editingValue.indexOf(',') !== -1)
 {  scope.editingValue = scope.editingValue.slice(0, scope.editingValue.lastIndexOf(',') + 1) + item.value;} //clear last (partial) entry and replace it with selected
                            else { scope.editingValue = item.value;  }

**Comment by not-an-aardvark** [comment] 2017-12-19 22:57
Hi,

This is working as intended. ESLint isn't able to fix all of the reported problems because you have a line comment after the `if` statement. Instead, ESLint fixes the problems that can be fixed, and reports the remaining problems.

**Comment by MichaelSila** [comment] 2017-12-22 18:34
That's fine. I realized that I wanted less "linting" and more formatting, so I switched my setup to js-beautify. 

Keep up the good work!

**Comment by not-an-aardvark** [comment] 2018-01-19 15:33
Closing because this is working as intended.

**Closed by not-an-aardvark** 2018-01-19 15:33 UTC
Labels: works as intended
