### ISSUE TITLE
eslint --fix maintains superfluous tabs

### ISSUE THREAD

**Issue by bardware** [eslint/eslint#8043] opened 2017-02-08 14:32 UTC
**Tell us about your environment**
Win10, 64 bit

* **ESLint Version:**
3.15.0

* **Node Version:**
v6.0.1

* **npm Version:**
3.10.8

**Please show your full configuration:**

```
		"brace-style" : [ "error", "1tbs", {} ],
```

**What did you do? Please include the actual source code causing the issue.**
I called `eslint --fix my.js`; The brace style was corrected; tabs were maintained.

```js
						if( time1.length > 1 )
						{
							hh1 = time1[ 0 ];
							mm1 = time1[ 1 ];
						}
						else
						{
							hh1 = time1[ 0 ];
							mm1 = 0;
						}
```

**What did you expect to happen?**
I expect there's one space between the round closing brace and the curly brace on the line with the ìf`

**What actually happened? Please include the actual, raw output from ESLint.**
eslint maintains the tabs from the superfluous line that contained only the curly brace.
```js
						if( time1.length > 1 )						{
							hh1 = time1[ 0 ];
							mm1 = time1[ 1 ];
						}						else						{
							hh1 = time1[ 0 ];
							mm1 = 0;
						}
```

**Comment by not-an-aardvark** [comment] 2017-02-09 04:08
Thanks for the report. I think this is technically working as intended -- the `brace-style` autofixer only handles brace styling, on the assumption that the user can configure other stylistic rules if they have a preference for how the resulting code should look. That said, I agree that the resulting code looks very strange, and there currently isn't a core stylistic rule to fix this when tabs are used for indentation.

If we end up implementing https://github.com/eslint/eslint/issues/7621, this issue will be fixed.

**Comment by not-an-aardvark** [comment] 2017-04-22 07:22
Closing this as a duplicate of https://github.com/eslint/eslint/issues/7621.

**Closed by not-an-aardvark** 2017-04-22 07:22 UTC
Labels: triage
