### ISSUE TITLE
feature: ability to disable autofix for specific rules

### ISSUE THREAD

**Issue by andreineculau** [eslint/eslint#8935] opened 2017-07-12 19:15 UTC
I cannot find anything in issues, but apologies in advance if this topic has already been touched on.

What I'm aiming for is to have my eslint config specify that I want `eslint --fix` to fix any errors/warnings **except** the ones for rules A and B.

The reasoning behind this goal is that rules may not be comprehensive enough to fix the styling as intended, yet they might still offer value with level `warn`. That is to say, I would like to get warnings in my editor "hey, this doesn't look alright", but I cannot let specific rules' fixers run and possibly make the style worse than it actually is in its original form.

**Comment by not-an-aardvark** [comment] 2017-07-12 19:17
Closing as a duplicate of https://github.com/eslint/eslint/issues/7549 and https://github.com/eslint/eslint/issues/8018.

**Closed by not-an-aardvark** 2017-07-12 19:17 UTC
Labels: triage

**Comment by ljharb** [comment] 2017-07-15 07:24
@not-an-aardvark in my experience, `--fix --quiet` still fixes warnings, it just doesn't output them. Is that change new in eslint v4?

**Comment by not-an-aardvark** [comment] 2017-07-15 07:26
Yes, this was fixed in https://github.com/eslint/eslint/commit/f00854e068b5d453c99139daf216221eb920a9cb.
