### ISSUE TITLE
[feat] autofix for maxLen rule

### ISSUE THREAD

**Issue by xHyroM** [eslint/eslint#15787] opened 2022-04-18 14:03 UTC
### What rule do you want to change?

maxLen (max-length)

### What change to do you want to make?

Implement autofix

### How do you think the change should be implemented?

A new default behavior

### Example code

```ts
/**
 * Object of all basic messages if a problem occurs.
 *
 * However, you can customize these messages using the [@gcommands/plugin-language](https://github.com/Garlic-Team/gcommands-addons/tree/master/packages/plugin-language) plugin.
 *
 * @see {@link Responses}
 */
public responses: Record<string, string> = Responses;
```

### What does the rule currently do for this code?

```ts
/**
 * Object of all basic messages if a problem occurs.
 *
 * However, you can customize these messages using the
 * [@gcommands/plugin-language](https://github.com/Garlic-Team/gcommands-addons/tree/master/packages/plugin-language)
 * plugin.
 *
 * @see {@link Responses}
 */
public responses: Record<string, string> = Responses;
```

### What will the rule do after it's changed?

It would automatically split the line into multiple parts, as `deno fmt` already does, for example

### Participation

- [ ] I am willing to submit a pull request to implement this change.

### Additional comments

There was already one pull request on this topic, but it was not resolved and was finally closed with the reason "age".
Original PR: https://github.com/eslint/eslint/issues/11325

**Comment by nzakas** [comment] 2022-04-19 00:33
This is too complex for ESLint. 

Duplicate of https://github.com/eslint/eslint/issues/15588

**Closed by nzakas** 2022-04-19 00:33 UTC
Labels: enhancement, rule
