### ISSUE TITLE
i use --stdin and pipe and can't use --fix. Using --fix-dry-run but it doesn't fix the code just emits errors

### ISSUE THREAD

**Issue by liesislukas** [eslint/eslint#12741] opened 2020-01-04 14:01 UTC
Environment Info:

- Node version: v12.6.0
- npm version: v6.13.4
- Local ESLint version: v6.8.0
- Global ESLint version: v6.6.0 (Currently used)

**What parser (default, Babel-ESLint, etc.) are you using?**
none, only eslint

![image](https://user-images.githubusercontent.com/2733862/71766669-039d2f00-2f0b-11ea-8b91-00e94513b49a.png)

**What did you expect to happen?**

when using pipe i expect to get output of fixed code. But i get only eslint errors which should be fixed. Error says to use `--fix` flag while i can't use that because of `--stdin` flag

eslint config:

<details>

```js
module.exports = exports = {
  // don't look for any other eslint config
  root: true,
  plugins: [
    'react',
  ],
  extends: [
    'eslint:recommended',
    'plugin:react/recommended',
  ],
  env: {
    browser: true,
    serviceworker: true,
    es6: true,
  },
  parserOptions: {
    ecmaFeatures: {
      jsx: true,
      modules: true,
      spread: true,
      restParams: true,
    },
    sourceType: 'module',
  },
  settings: {
    'react': {
      'pragma': 'React',  // Pragma to use, default to "React"
      'version': '16.12',
    },
  },
  rules: {
    // https://eslint.org/docs/rules/
    'curly': 'error',
    'dot-location': ['error', 'property'],
    'eqeqeq': ['error', 'always'],
    'no-div-regex': 'error',
    'no-else-return': 'error',
    'no-extra-bind': 'error',
    'no-floating-decimal': 'error',
    'no-implicit-coercion': 'error',
    'no-multi-spaces': 'error',
    'no-useless-return': 'error',
    'wrap-iife': 'error',
    'yoda': 'error',
    'array-bracket-newline': ['error', {'multiline': true}],
    'array-bracket-spacing': ['error', 'never'],
    'array-element-newline': ['error', {'multiline': true}],
    'block-spacing': ['error', 'always'],
    'brace-style': ['error', '1tbs'],
    'comma-dangle': ['error', 'always'],
    'comma-spacing': ['error', {'before': false, 'after': true}],
    'comma-style': ['error', 'last'],
    'computed-property-spacing': ['error', 'never'],
    'eol-last': ['error', 'always'],
    'func-call-spacing': ['error', 'never'],
    'function-call-argument-newline': ['error', 'consistent'],
    'function-paren-newline': ['error', 'multiline'],
    'implicit-arrow-linebreak': ['error', 'beside'],
    'indent': ['error', 2],
    'jsx-quotes': ['error', 'prefer-single'],
    'key-spacing': 'error',
    'keyword-spacing': 'error',
    'linebreak-style': 'error',
    'lines-around-comment': 'error',
    'lines-between-class-members': 'error',
    'multiline-comment-style': 'error',
    'new-parens': 'error',
    'newline-per-chained-call': 'error',
    'no-lonely-if': 'error',
    'no-multiple-empty-lines': 'error',
    'no-trailing-spaces': 'error',
    'no-unneeded-ternary': 'error',
    'no-whitespace-before-property': 'error',
    'nonblock-statement-body-position': 'error',
    'object-curly-newline': 'error',
    'object-curly-spacing': 'error',
    'object-property-newline': 'error',
    'one-var': ['error', 'never'],
    'one-var-declaration-per-line': ['error', 'always'],
    'operator-assignment': ['error', 'never'],
    'operator-linebreak': ['error', 'after', {'overrides': {'?': 'before', ':': 'before'}}],
    'padded-blocks': ['error', 'never'],
    'padding-line-between-statements': ['error'],
    'prefer-object-spread': 'error',
    'quote-props': ['error', 'consistent-as-needed'],
    'quotes': ['error', 'single', {'avoidEscape': true}],
    'semi': ['error', 'always'],
    'semi-spacing': ['error', {'before': false, 'after': true}],
    'semi-style': ['error', 'last'],
    'sort-vars': ['error', {'ignoreCase': true}],
    'space-before-blocks': ['error', 'always'],
    'space-before-function-paren': ['error', {'anonymous': 'always', 'named': 'never', 'asyncArrow': 'always'}],
    'space-in-parens': ['error', 'never'],
    'space-infix-ops': ['error', {'int32Hint': false}],
    'space-unary-ops': ['error', {'words': true, 'nonwords': false}],
    'spaced-comment': ['error', 'always', {'exceptions': ['-', '+', '*']}],
    'switch-colon-spacing': ['error', {'after': true, 'before': false}],
    'template-tag-spacing': ['error', 'always'],
    'unicode-bom': ['error', 'always'],
    'wrap-regex': 'error',
    'arrow-body-style': ['error', 'as-needed'],
    'arrow-parens': ['error', 'always'],
    'arrow-spacing': ['error', {'before': true, 'after': true}],
    'generator-star-spacing': ['error', {'before': true, 'after': false}],
    'no-confusing-arrow': 'error',
    'no-useless-computed-key': 'error',
    'no-useless-rename': 'error',
    'no-var': 'error',
    'object-shorthand': ['error', 'consistent'],
    'prefer-arrow-callback': ['error'],
    'prefer-const': 'error',
    'prefer-destructuring': ['error', {'object': false, 'array': false}],
    'prefer-numeric-literals': 'error',
    'prefer-template': 'error',
    'rest-spread-spacing': ['error', 'never'],
    'template-curly-spacing': ['error', 'never'],
    'yield-star-spacing': ['error', {'before': true, 'after': false}],

    // ReactJS & JSX:
    // https://github.com/yannickcr/eslint-plugin-react
    'react/no-unknown-property': ['off'],
    'react/self-closing-comp': ['error', {'component': true, 'html': true}],
    'react/jsx-boolean-value': ['error', 'always'],
    'react/jsx-closing-bracket-location': ['error', {selfClosing: 'line-aligned', nonEmpty: 'line-aligned'}],
    'react/jsx-closing-tag-location': ['error'],
    'react/jsx-curly-newline': ['error', 'consistent'],
    'react/jsx-curly-spacing': ['error', {'when': 'never'}],
    'react/jsx-equals-spacing': ['error', 'never'],
    'react/jsx-first-prop-new-line': ['error', 'multiline-multiprop'],
    'react/jsx-indent': ['error', 2],
    'react/jsx-indent-props': ['error', 2],
    'react/jsx-max-props-per-line': ['error', {'maximum': 1, 'when': 'multiline'}],
    'react/jsx-no-useless-fragment': ['error'],
    'react/jsx-props-no-multi-spaces': ['error'],
    'react/jsx-sort-props': ['error', {
      'callbacksLast': false,
      'shorthandFirst': true,
      'ignoreCase': true,
      'noSortAlphabetically': false,
      'reservedFirst': true,
    }],
    'react/jsx-tag-spacing': ['error', {
      'closingSlash': 'never',
      'beforeSelfClosing': 'always',
      'afterOpening': 'never',
      'beforeClosing': 'allow',
    }],
    'react/jsx-wrap-multilines': ['error', {
      'declaration': 'parens',
      'assignment': 'parens',
      'return': 'parens',
      'arrow': 'parens',
      'condition': 'ignore',
      'logical': 'ignore',
      'prop': 'ignore',
    }],
  },
};
```

</details>

**Comment by platinumazure** [comment] 2020-01-05 00:16
Hi @liesislukas, thanks for the issue.

These flags are all working as intended. When ESLint receives input from stdin, it has no idea what file the input text is associated with, so it has no way to write the fixed file back to disk. (There is an `stdin-filename` CLI flag, but this accepts any string and only uses it to generate a file name in the lint results; it does not attempt to validate that the file corresponds to an existing file on the filesystem.)

The `--fix-dry-run` is designed to show what fixes are needed, but not write the fixes back to the file on disk. This can be used to preview fixes without actually applying them, as well as to use the ESLint output to apply the fixes elsewhere. (The flag was originally written for editor integrations that have to use stdin due to limitations in the editor's API.)

In your case, you need to either use `--fix` without `--stdin`, or use `--fix-dry-run` and use the results to apply fixes yourself (or delegate to some other process that can do the same).

If you believe this is insufficient for your use case, please provide more detail about exactly what problem you're trying to solve and your idea of how it should be solved, and we will be happy to discuss.

**Comment by kaicataldo** [comment] 2020-01-09 22:03
Closing this issue since it looks like the question has been answered.

**Closed by kaicataldo** 2020-01-09 22:03 UTC
Labels: question, works as intended
