### ISSUE TITLE
space-in-parens does not offer option for consistent spacing

### ISSUE THREAD

**Issue by ThaJay** [eslint/eslint#8732] opened 2017-06-14 11:59 UTC
my current .eslintrc.js rule:
```js
rules = {
  "space-in-parens": [
    "error", "never", {"exceptions": ["()"]}
  ]
}
```
The following code is parsed as correct with the above rule:
```js
functionCall(someArray.map(key => getFromStorage(key) ) )
```
The rule I propose:
```js
rules = {
  "space-in-parens": ["error", "consistent"]
}
```
So we can write it like this:
(and the first example would be flagged as inconsistent)
```js
// consistent (space at opening and closing paren)
functionCall(someArray.map( key => getFromStorage(key) ))

// current errors:
// There should be no spaces inside this paren. (space-in-parens)
// There must be a space inside this paren. (space-in-parens)
```
I have turned the rule off for now, to be able to choose where to use (consistent) spacing.

* **ESLint Version:** 3.19.0
* **Node Version:** v6.11.0
* **npm Version:** 3.10.10

**What parser (default, Babel-ESLint, etc.) are you using?**
```
  "standard": {
    "parser": "babel-eslint"
  }
```

**Comment by kaicataldo** [comment] 2017-06-14 20:32
I believe I understand what you're proposing, but would you mind adding labels to each section to make it clearer for everyone?

**Comment by ThaJay** [comment] 2017-06-15 10:20
Yes will do, I'm sorry for being unclear

**Comment by kaicataldo** [comment] 2017-06-15 18:30
Thanks for updating the original comment. This seems like a reasonable enhancement to me. I'm not sure how I feel about allowing the `exceptions` option with `"consistent"` - seems like it might make things more confusing than anything to me with very little benefit (this could also be added later in a further enhancement if there are more requests for it).

**Comment by not-an-aardvark** [comment] 2018-01-19 16:12
Thanks for your interest in improving ESLint. Unfortunately, it looks like this issue didn't get consensus from the team, so I'm closing it. We define [consensus](http://eslint.org/docs/maintainer-guide/issues.html#consensus) as having three :+1:s from team members, as well as a team member willing to champion the proposal. This is a high bar by design -- we can't realistically accept and maintain every feature request in the long term, so we only accept feature requests which are useful enough that there is consensus among the team that they're worth adding.

Since ESLint is pluggable and can load custom rules at runtime, the lack of consensus among the ESLint team doesn't need to be a blocker for you using this in your project, if you'd find it useful. It just means that you would need to [implement the rule](http://eslint.org/docs/developer-guide/working-with-rules) yourself, rather than using a bundled rule that is packaged with ESLint.

**Closed by not-an-aardvark** 2018-01-19 16:12 UTC
Labels: enhancement, evaluating, rule
