### ISSUE TITLE
Parsing error: Unexpected character '@' with eslint 2.10.1 and babel-eslint

### ISSUE THREAD

**Issue by ssbiswal1987** [eslint/eslint#6197] opened 2016-05-16 18:30 UTC
Eslint complains usage of decorators with babel-eslint, when updated to 2.10.1.

It seemed to work well with eslint 2.9.0

**Comment by platinumazure** [comment] 2016-05-16 19:03
CLIEngine is currently not respecting custom parser and is attempting to parse with espree. Duplicate of many issues. Please downgrade to ESLint version 2.9 as a workaround. We hope to fix this soon. Thanks!

**Closed by platinumazure** 2016-05-16 19:03 UTC
Labels: triage

**Comment by Hosar** [comment] 2016-11-11 05:55
I'm using the following versions but still I'm getting the same error. I did the downgrade (2.9) but it did not work. Could I do something else?
"eslint": "^3.9.1",
"babel-eslint": "^6.0.4"

`5:1  error  Parsing error: Unexpected character '@'`

**Comment by not-an-aardvark** [comment] 2016-11-11 06:10
@Hosar Could you please create a new issue?
