### ISSUE TITLE
Support Dynamic Import

### ISSUE THREAD

**Issue by mikesherov** [eslint/eslint#11486] opened 2019-03-06 23:23 UTC
**The version of ESLint you are using.**
Latest

**The problem you want to solve.**
I want to use ESLint and Webpack without babel-ESLint, but due to the lack of support for dynamic import, which Webpack uses to determine where to split code, I must use babel-eslint where I would otherwise be happy without transpiling.

**Your take on the correct solution to problem.**
According to 
https://github.com/eslint/eslint#what-about-experimental-features, it states:
> ESLint's parser only officially supports the latest final ECMAScript standard. We will make changes to core rules in order to avoid crashes on stage 3 ECMAScript syntax proposals (as long as they are implemented using the correct experimental ESTree syntax)

I believe this is a case that warrants an exception to this rule given the prominence of `import` in otherwise bland es5 code due to Webpack. `import` is stage 3, fully 262 tested, battle tested in all browsers, mandated by the html standard and firmly ensconced in the bundling ecosystem.

The proposed fix is to support dynamic support in ESLint now ahead of stage 4, especially considering it has an unknown timeline to advance to stage 4.

**Are you willing to submit a pull request to implement this change?**
Yes :-)

**Comment by nzakas** [comment] 2019-03-07 02:39
Thanks @mikesherov for opening this issue. The idea of supporting stage < 4 features has been discussed multiple times in this project, and I don't believe anything significant has changed since we [created the policy](https://github.com/eslint/eslint/issues/9804). (Specifically, please read [my comments](https://github.com/eslint/eslint/issues/9804#issuecomment-359255034) for a history of `ecmaFeatures` vs. `ecmaVersion`.)

The problem is that everyone has a favorite ECMAScript proposal that they believe is really important and therefore should be an exception to our policy (see also https://github.com/eslint/espree/issues/409). The reason we finally formalized our policy about stage 4 features is so we wouldn't need to re-argue this point for every new proposal that people are excited about. (`async` and `await` were another hot one that we [waited on](https://github.com/eslint/eslint/issues/1657).)

All that being said, it sounds like what you need is a parser that doesn't transpile and supports dynamic `import`. Because ESLint lets you specify any parser you want, I think you have a few other options available to you:

1. It looks like Esprima has [implemented dynamic `import`](https://github.com/jquery/esprima/issues/1728) even though the code hasn't been published, so you could pull it yourself or request a release. 
1. You could also fork Espree and create your own local copy (no need to publish a package) that has dynamic `import` implemented. There is an [Acorn plugin](https://github.com/kesne/acorn-dynamic-import) for that, so you'd just need to enable that inside of Espree.
1. Maybe there's a way to ask `babel-eslint` to simply parse without transpiling? (I have no idea. I actually thought it would have no need to transpile because we just need the AST, but I also don't have the energy to dig in and see what it's really doing.)

So, I'd encourage you to find an ecosystem-based solution to the problem as it seems like one, and maybe more, already exist.

**Comment by mikesherov** [comment] 2019-03-07 03:09
I don’t see how supporting dynamic import is out of line with the policy as stated:
> We will make changes to core rules in order to avoid crashes on stage 3 ECMAScript syntax proposals
You link to a top level await issue, which is stage 2. I agree that’s too early. I think `import` qualifies under the stated policy. 

I will say that `import` is not just a favorite future proposal, but it’s also the recommended way to do code splitting according to Webpack, parcel, rollup, etc. I don’t need any rules around it, I just don’t want to have to use Babel just because I’m using a bundler to achieve code splitting.

I won’t bother you with further comments on this. If it’s final that it won’t hsppen until it’s stage 4, so be it, but I believe it’s in the spirit of the policy to address this.

Keep up the great work on ESLint.

**Comment by nzakas** [comment] 2019-03-07 17:56
> We will make changes to core rules in order to avoid crashes on stage 3 ECMAScript syntax proposals

I can see how this would be confusing. A rule crash means that the ESLint process exits and the lint results are not displayed. We want to avoid that situation at all costs. If we can update a rule in some way to make sure a crash doesn't happen, then we do that. However, dynamic `import` does not cause an ESLint crash, you get a notice that there is a syntax error. This would also require a change to the parser, not to a single rule, and so doesn't fall under this policy.

**Comment by ilyavolodin** [comment] 2019-03-08 17:44
I'm with @nzakas on this. While somebody might consider dynamic import to be very important, others will consider some other proposal as very important. There's really no way to please everyone when it comes to different proposals support. There's only two options, either support everything or do not support it until it's set in stone (and we chose the latter, since we don't have enough manpower to support former).

**Comment by ljharb** [comment] 2019-03-08 18:10
The difference, however, is that this one is shipped in almost all the browsers, which imo makes it objectively, not subjectively, important.

**Comment by platinumazure** [comment] 2019-03-08 20:00
Remember, babel-eslint is an option here. It's not like ESLint is leaving dynamic import users stuck here. This is just a request to change espree so that it can support dynamic import automatically, which makes things a little more convenient to users.

I agree with @nzakas and @ilyavolodin. This could set a precedent we don't want to set (and that we had tried before), and I don't want to go back to that. This request, by itself, is fairly reasonable, but the problem is the many more that will follow.

If this is really shipped in a lot of browsers and ready to go, then TC39 should standardize it at some point. We can support it in espree at that point.

**Comment by ljharb** [comment] 2019-03-09 00:35
It certainly will be defacto web reality at some point, at which point the implementations are the spec, and it will be added - but since all of those match the stage 3 proposal, that’s as standard as it gets.

I don’t think that espree supporting “things that are shipped in > 50% of web browsers” is an unreasonable line to draw, and needn’t necessarily be the same thing as opening the door to more stage < 4 proposals.

**Comment by kaicataldo** [comment] 2019-03-09 04:43
Two quick notes to add to this discussion: 
* For more context, there have been past discussions around this topic in the Espree repo (see https://github.com/eslint/espree/issues/344).
* As of `babel-eslint` v11 ([currently in beta](https://github.com/babel/babel-eslint/releases/tag/v11.0.0-beta.0)), `babel-eslint` will start requiring `@babel/core` as a peer dependency and as a result will require that the project has a correctly configured Babel installation. This is a bit of a philosophical shift from previous versions in that `babel-eslint`'s purposes will expressly be to parse files that are being transformed with Babel rather than just being a generic ES Next parser (with all experimental syntax on all the time). For more context around that discussion, please see https://github.com/babel/babel-eslint/issues/573. Because of this change, there is the potential that folks who aren't using Babel but are using dynamic imports for code-splitting with bundlers might not have an easy solution for parsing their code with ESLint.

**Comment by ljharb** [comment] 2019-03-09 04:58
I should also note that even tho dynamic import isn’t yet stage 4, the HTML spec mandates its inclusion: https://github.com/whatwg/html/commit/d4d1704f9c0efbeed78b885d566af17545b8b5fe

So from a browser standpoint, it is fully standardized.

**Comment by klebba** [comment] 2019-03-13 23:55
The misalignment between the development targets (Node, Chrome, Firefox, Safari) and ESLint is increasingly frustrating. ESLint's policy means that I can't even ignore the unsupported syntax:

```
// eslint-disable-next-line
const module = import('./foo.js');
```

This does nothing; instead linting will choke on the parsing error and the whole file won't be analyzed. It seems totally reasonable to adopt only Stage 4 features, but on balance it seems completely unreasonable to not actually ignore this line. ESLint should consider a less pure solution that strikes a balance here. Folding in a transpile step to make sure this ignore happens is not a good option. Ultimately I don't care if this line is skipped, but to have all the proximal code become collateral damage is a bummer.

**Comment by not-an-aardvark** [comment] 2019-03-14 00:14
@klebba For architectural reasons, ESLint needs to be able to parse your file before it can run linting rules on it. As a result, `eslint-disable-line` can't be used to suppress parsing errors in general, including for dynamic import.

**Comment by klebba** [comment] 2019-03-14 18:17
@not-an-aardvark I understand that today this is the case; perhaps this should change in order to address my comment. ESLint could instead analyze my code for exclusion rules and then parse what remains. This would be the expected _ignore_ behavior IMO, and not require a policy debate.

**Comment by platinumazure** [comment] 2019-03-14 20:12
@klebba Could we extract the discussion about handling non-parseable code to a separate issue? That way, we can keep this discussion focused on dynamic import in particular, per the issue title.

I'll note again that using babel-eslint gives users a way forward here.

**Comment by nzakas** [comment] 2019-03-15 15:49
I agree with @platinumazure. What @klebba is suggesting would be a separate discussion about a proposed new feature, and that deserves its own issue.

I'm going to close this issue now, as we aren't going to change our policy about supporting ES stages differently. Thanks for the discussion.

**Closed by nzakas** 2019-03-15 15:49 UTC
Labels: core, enhancement, evaluating

**Comment by ljharb** [comment] 2019-03-15 15:55
@nzakas so eslint has no plans to ever support any language feature that’s not stage 4, even if a browser is mandated to implement it, and every browser does? Web reality is a much stronger indication of “this feature will never go away” than the Ecma stage.

**Comment by klebba** [comment] 2019-03-15 18:50
@nzakas @platinumazure I opened #11514 -- thanks :)

**Comment by aladdin-add** [comment] 2019-06-04 12:47
`import()` has reached stage-4, seems we can support it now!
