### ISSUE TITLE
Proposal to add a rule to hide the File ignored because of a matching ignore pattern. Use --no-ignore to override error

### ISSUE THREAD

**Issue by kumarharsh** [eslint/eslint#7159] opened 2016-09-15 08:45 UTC
**Tell us about your environment**

* **ESLint Version:** ALL
* **Node Version:** ALL
* **npm Version:** ALL

**What parser (default, Babel-ESLint, etc.) are you using?** ANY

**Please show your full configuration:** Doesn't Matter

**What did you do? Please include the actual source code causing the issue.** Refer to this issue: https://github.com/eslint/eslint/issues/5623

**What did you expect to happen?** A way to hide this warning `File ignored because of a matching ignore pattern. Use --no-ignore to override` from showing on ignored files

**What actually happened? Please include the actual, raw output from ESLint.**
![Image](https://cloud.githubusercontent.com/assets/449321/15560603/c065d7d6-22b2-11e6-9b09-2bad49c164b2.png) (credits @jhliberty)

**Comment by mysticatea** [comment] 2016-09-15 12:09
Thank you for this issue.

That warning is shown if you specify **one file** to lint it and if the file is ignored.
Someone intended to check the file but it was ignored. ESLint should show that the file was ignored.
So I don't think hiding the warning is reasonable.

Also, ESLint Node.js API does not return that warning by default. ([cli-engine.js#L732](https://github.com/eslint/eslint/blob/cd09c965f0031301451345c1f3d25b7f013a71a4/lib/cli-engine.js#L732), `warnIgnored` parameter is falsy by default.)
I guess there may be an issue in `linter-eslint` of Atom.

---

By the way,

> - ESLint Version: ALL
> - Node Version: ALL

This feature has been introduced since v2.10.0. ESLint 3 does not work on Node.js@<4.
Those are not ALL :smile:

**Comment by kumarharsh** [comment] 2016-09-15 12:36
haha, sorry @mysticatea . Didn't really mean "ALL" all, but I've been seeing the issue for a long time, and didn't know (or didn't bother) where to check when this issue started coming.

Thank you for the clarification that the issue might lie with the plugin. I'll have a look in vscode-eslint's internals then. I guess this issue can be closed?

**Comment by mysticatea** [comment] 2016-09-16 10:38
Weird.
I am a VSCode user, too. But my VSCode does not show that warning.
Could you ensure to use the latest versions of eslint/vscode-eslint? Especially, both local-installed eslint and global-installed eslint.

**Comment by kumarharsh** [comment] 2016-09-18 18:04
Yes, I'm using everything latest. I'm getting it in my project, but not in a new repository with a few files and same settings... Maybe something is wrong somewhere in one of the eslint plugins, I'll investigate.

**Comment by vitorbal** [comment] 2016-10-03 18:22
Hi @kumarharsh, thanks again for reaching out! Any chance you had a moment to verify if the problem is caused by one of your eslint plugins?

**Comment by kumarharsh** [comment] 2016-10-03 20:12
@vitorbal updating my eslint to 3.x has *seemingly* fixed this error. I'm sorry, but I'm short of time to debug  the exact source of the problem. Perhaps you can close it, and if I (or someone else) does run into this problem again, this issue can be reopened?

**Comment by vitorbal** [comment] 2016-10-03 22:52
Thanks for the update! Since the error doesn't occur anymore, I'll close this issue. If someone else has the same error or a similar problem in the future, we can open a new one.

**Closed by vitorbal** 2016-10-03 22:52 UTC
Labels: question
