### ISSUE TITLE
error in newline-after-var parsing

### ISSUE THREAD

**Issue by jbcpollak** [eslint/eslint#7568] opened 2016-11-09 17:33 UTC
**Tell us about your environment**

* **ESLint Version:** 3.9.1
* **Node Version:** 6.2.1
* **npm Version:** 3.10.5

**What parser (default, Babel-ESLint, etc.) are you using?**
>    "eslint": "3.2.2",
>    "eslint-config-angular": "0.5.0",
>    "eslint-config-defaults": "9.0.0",
>    "eslint-loader": "1.6.1",
>    "eslint-plugin-angular": "1.4.1",
>    "eslint-plugin-babel": "3.3.0",

**Please show your full configuration:**

```
// Based on the awesome config from walmart labs:
//https://github.com/walmartlabs/eslint-config-defaults
{
	"extends": [
		"defaults/configurations/google",
		"angular"
	],
	"rules": {
		"max-len": [2, 110, 2],
		"indent": [2, "tab"],
		"dot-location": [2, "property"],
		"no-mixed-spaces-and-tabs": [2, "smart-tabs"],
		"babel/generator-star-spacing": 1,
		"babel/new-cap": 1,
		"babel/object-curly-spacing": 1,
		"babel/object-shorthand": 1,
		"babel/arrow-parens": 1,
		"babel/no-await-in-loop": 1,
		"generator-star-spacing": 0,
		"new-cap": 0,
		"object-curly-spacing": 0,
		"object-shorthand": 0,
		"arrow-parens": 0,
		"no-await-in-loop": 0,
		"no-invalid-this": 0,
		"angular/module-setter": 0,
		"angular/module-getter": 0,
		"eqeqeq": "error"
	},
	"env": {
		"browser": true,
		"node": true,
		"es6": true
	},
	"ecmaFeatures": {
        "modules": true,
        "classes": true,
        "arrowFunctions": true,
        "blockBindings": true,
        "templateStrings": true
	},
	"globals": {
		"angular": false
	},
	"plugins": [
		"babel"
	],
	"parser": "babel-eslint"
}
```

**What did you do? Please include the actual source code causing the issue.**

The latest eslint is throwing an `newline-after-var` error with a multi-line variable definition like the code below. This did not happen with the previous version of eslint we were using (3.2.2):

```js
let mod = angular
	.module('app.constant', [])
	.constant('CONFIG', config)
	.run(function(CONFIG, $log) {
		$log.debug('@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@');
		$log.debug('Using configuration:', config);
		$log.debug('@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@');
	})
       ;

export default mod = mod.name;
```

**What did you expect to happen?**

There should be no error.

**What actually happened? Please include the actual, raw output from ESLint.**

```
/Users/jpollak/src/graphical_interface/lib/constant.js
  10:1  error  Expected blank line after variable declarations  newline-after-var

✖ 1 problem (1 error, 0 warnings)
```

**Comment by jbcpollak** [comment] 2016-11-09 17:37
I just noticed this problem goes away if I move the trailing ; up to the previous line:

```
let mod = angular
	.module('app.constant', [])
	.constant('CONFIG', config)
	.run(function(CONFIG, $log) {
		$log.debug('@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@');
		$log.debug('Using configuration:', config);
		$log.debug('@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@');
	});

export default mod = mod.name;
```

It seems eslint doesn't recognize the ; as terminating the previous statement - and maybe because of ASI it really doesn't?

Is this a bug, or should some other lint rule should be enabled to catch this?

**Comment by not-an-aardvark** [comment] 2016-11-09 17:46
Thanks for the report; I was able to reproduce the issue. It looks like a bug to me.

**Comment by not-an-aardvark** [comment] 2016-11-09 17:50
Actually, looking at it again, I think this might be intended behavior. If a semicolon is on a different line, the rule considers it to be separate from the initial `var` declaration. This allows the correct behavior in cases like this with semicolon-less style:

```js
var foo = 1

; [1, 2, 3].map(bar);
```

**Comment by jbcpollak** [comment] 2016-11-09 18:15
Yeah, I came to that conclusion too. I guess there is no way for eslint to
warn about ASI within other rules, is there?

**Comment by not-an-aardvark** [comment] 2016-11-09 18:17
I'm not sure I understand the question, could you clarify?

You can use [`semi`](http://eslint.org/docs/rules/semi) and [`no-unexpected-multiline`](http://eslint.org/docs/rules/no-unexpected-multiline) to warn about ASI-related issues.

**Comment by jbcpollak** [comment] 2016-11-09 19:03
I guess what I was thinking is it would be nice for `newline-after-var` to be able to detect if it is failing due to ASI and emit a different error in those cases. The rationale is that you might not explicitly ban ASI, so you might not realize a construct like the one above violates the rule.

Something like this would have been helpful:

```
/Users/jpollak/src/graphical_interface/lib/constant.js
  10:1  error  Expected blank line after variable declarations  newline-after-var
               (found ; after ASI-terminated variable statement)

✖ 1 problem (1 error, 0 warnings)
```

I realize that might not be something you want to implement or support, but I could see it being useful to developers who aren't on the lookout for ASI issues

**Comment by not-an-aardvark** [comment] 2016-11-09 19:07
I'm confused about what you mean by "failing due to ASI". If there is a semicolon on the next line, there is no ASI because a semicolon is already present.

**Comment by jbcpollak** [comment] 2016-11-09 19:11
Maybe I am confused, but my understanding of this situation is that I wrote this code:

```
let mod = angular
	.module('app.constant', [])
	.constant('CONFIG', config)
	.run(function(CONFIG, $log) {
		$log.debug('@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@');
		$log.debug('Using configuration:', config);
		$log.debug('@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@');
	})
       ;
```

But the parser sees:

```
let mod = angular
	.module('app.constant', [])
	.constant('CONFIG', config)
	.run(function(CONFIG, $log) {
		$log.debug('@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@');
		$log.debug('Using configuration:', config);
		$log.debug('@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@');
	});
       ;
```

Which is newline-after-var is failing (because there is an empty/blank statement after the `let`).

Assuming my understanding is correct, what I'm asking is if there is any way for eslint to call that out as the reason for the line violating the rule? Developers who are in the habit of putting semi's after every line are not going to be thinking about ASI, so they won't notice this is what is triggering the rule.

**Comment by not-an-aardvark** [comment] 2016-11-09 19:23
That's not quite right; when you write this code:

```js
let mod = foo()
    .bar()
       ;
```

The *parser* correctly considers it equivalent to this:

```js
let mod = foo()
    .bar();
```

However, there is special logic in `newline-after-var` to consider a semicolon on a different line as if it was part of a different statement. This allows the rule to work as expected on code that intentionally uses semicolons at the beginning of some lines.

**Comment by jbcpollak** [comment] 2016-11-09 23:42
> However, there is special logic in newline-after-var to consider a semicolon on a different line as if it was part of a different statement. This allows the rule to work as expected on code that intentionally uses semicolons at the beginning of some lines.

Ah that's interesting. In that case - I'd argue that code shouldn't be enabled unless the developer specifically says they want to allow ; at the beginning of lines?

Or, perhaps the rule shouldn't complain if the `;` is the only thing on the line.

So this should be ok:

```
let mod = foo()
    .bar()
       ;
```

But this should be an error:

```
let mod = foo()
    .bar()
       ; [1, 2, 3].map(baz)
```

**Comment by not-an-aardvark** [comment] 2017-04-22 06:14
Closing this since there hasn't been any discussion in quite a while and progress on the issue has stalled. While we wish we could accommodate all requests, we have limited resources and do need to prioritize. 

Feel free to open a new issue with a proposal to continue this discussion if this is something you would like to continue advocating for. Also, remember that you can always create an updated version of this rule for yourself and distribute it as a plugin.

**Closed by not-an-aardvark** 2017-04-22 06:14 UTC
Labels: bug, evaluating, rule
