### ISSUE TITLE
sort-keys could sort shorthand properties separately

### ISSUE THREAD

**Issue by mitchellsimoens** [eslint/eslint#9039] opened 2017-07-29 19:02 UTC
This is a feature request.

Currently, `sort-keys` sorts keys altogether but if you have any shorthand properties, they are expected to be sorted with non-shorthand properties.

This is invalid:

    const foo = 1;
    const z = 4;
    const obj = {
        foo, z,
        bar : 2,
        m : 3
    };

It expects this:

    const foo = 1;
    const obj = {
        bar : 2,
        foo,
        m : 3,
        z
    };

There should be an option to sort these shorthand properties separately and place them above or below non-shorthand properties.

Example of having shorthand properties before non-shorthand:

    "sort-keys" : [
        "warn",
        "asc",
        {
            "separateShorthand" : "before"
        }
    ]

This would be valid:

    const foo = 1;
    const z = 4;
    const obj = {
        foo, z,
        bar : 2,
        m : 3
    };

Example of having shorthand properties after non-shorthand:

    "sort-keys" : [
        "warn",
        "asc",
        {
            "separateShorthand" : "after"
        }
    ]

This would be valid:

    const foo = 1;
    const z = 4;
    const obj = {
        bar : 2,
        m : 3,
        foo, z
    };

This would still take `caseSensitive` into account.

This is similar to #9038 so a common API could be setup.

**Comment by not-an-aardvark** [comment] 2017-07-30 01:14
Thanks for the proposal, this seems reasonable to me.

Also, note that this was previously discussed in https://github.com/eslint/eslint/issues/7543.

**Comment by not-an-aardvark** [comment] 2018-01-19 16:05
Thanks for your interest in improving ESLint. Unfortunately, it looks like this issue didn't get consensus from the team, so I'm closing it. We define [consensus](http://eslint.org/docs/maintainer-guide/issues.html#consensus) as having three :+1:s from team members, as well as a team member willing to champion the proposal. This is a high bar by design -- we can't realistically accept and maintain every feature request in the long term, so we only accept feature requests which are useful enough that there is consensus among the team that they're worth adding.

Since ESLint is pluggable and can load custom rules at runtime, the lack of consensus among the ESLint team doesn't need to be a blocker for you using this in your project, if you'd find it useful. It just means that you would need to [implement the rule](http://eslint.org/docs/developer-guide/working-with-rules) yourself, rather than using a bundled rule that is packaged with ESLint.

**Closed by not-an-aardvark** 2018-01-19 16:05 UTC
Labels: enhancement, evaluating, rule
