### ISSUE TITLE
Indention error on nested unordered lists

### ISSUE THREAD

**Issue by poorpaddy** [eslint/eslint#9999] opened 2018-02-21 16:33 UTC
**Tell us about your environment**

* **ESLint Version:** 4.18.1
* **Node Version:** 8.9.1
* **npm Version:** 5.6.0

**What parser (default, Babel-ESLint, etc.) are you using?**
babel-eslint: 8.2.2

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js

{
  "extends": [
    "eslint-config-semistandard",
    "plugin:jsx-a11y/recommended"
  ],
  "plugins": [
    "react",
    "chai-friendly",
    "jsx-a11y",
    "jasmine"
  ],
  "parser": "babel-eslint",
  "parserOptions": {
    "ecmaVersion": 6,
    "sourceType": "module",
    "ecmaFeatures": {
      "jsx": true,
      "classes": true,
      "es6": true
    }
  },
  "rules": {
    "no-unused-expressions": 0,
    "chai-friendly/no-unused-expressions": 2,
    "react/jsx-uses-vars": 2,
    "react/jsx-filename-extension": [
      1, { "extensions": [".js", ".jsx"] }
    ],
    "react/jsx-uses-react": 1
  },
  "globals": {
    "localStorage": true,
    "describe": true,
    "browser": true,
    "expect": true,
    "retryDescribe": true,
    "it": true,
    "beforeEach": true,
    "afterEach": true,
    "NODE_ENV": true,
    "IMG_CDN": true
  }
}

```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
/* Not the actual indentions from error */
<li>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut eu nunc eget dolor pharetra mollis.
  <ul>
    <li>Curabitur aliquam nibh mi, at molestie nunc elementum non. Nunc nunc elit, varius sed cursus ut, dictum at odio. Sed cursus dui a dolor interdum, facilisis cursus lorem iaculis.</li>
    <li>Fusce a volutpat augue. Integer condimentum nulla ipsum, sit amet placerat sapien euismod et. Integer quis purus gravida, maximus erat et, accumsan erat.</li>
  </ul>
</li>
```

```bash
yarn lint
```

**What did you expect to happen?**
Linting to pass

**What actually happened? Please include the actual, raw output from ESLint.**
```bash
http://eslint.org/docs/rules/indent  Expected indentation of 14 spaces but found 16
  src/pages/faq/components/free-credit-score/index.jsx:16:1
                  <ul>
```

Error on nested `<ul>`. Linter wants the `<ul>` nested at same place as the parent `<li>` rather than indented 2 spaces.

**Comment by not-an-aardvark** [comment] 2018-02-21 17:32
Closing as a duplicate of https://github.com/eslint/eslint/issues/9878

**Closed by not-an-aardvark** 2018-02-21 17:32 UTC
Labels: triage
