### ISSUE TITLE
Template string: Cannot read property 'range' of null

### ISSUE THREAD

**Issue by jacargentina** [eslint/eslint#10043] opened 2018-03-02 11:12 UTC
**Tell us about your environment**

* **ESLint Version:** v4.18.1
* **Node Version:** 9.6.1
* **npm Version:** 5.6.0

**What parser (default, Babel-ESLint, etc.) are you using?**
babel-eslint
**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
var path = require('path');

module.exports = {
  parser: 'babel-eslint',
  env: {
    browser: true,
    commonjs: true,
    es6: true,
    node: true
  },
  extends: [
    'eslint:recommended',
    'plugin:react/recommended',
    'plugin:import/errors',
    'plugin:import/warnings'
  ],
  parserOptions: {
    ecmaFeatures: {
      experimentalObjectRestSpread: true,
      jsx: true
    },
    sourceType: 'module'
  },
  plugins: ['react', 'import'],
  settings: {
    'import/resolver': {
      webpack: {
        config: path.join(__dirname, '/webpack.config.js')
      }
    }
  },
  rules: {
    strict: 0,
    'react/prop-types': 'off',
    'no-unused-vars': 'warn',
    indent: [2, 2, { SwitchCase: 1 }],
    'linebreak-style': ['error', 'unix'],
    semi: ['error', 'always']
  }
};
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
class A {
  method() {
    return `Hello ${me}`;
  }
}
```

```bash
eslint test.js
```

**What did you expect to happen?**
Run just fine
**What actually happened? Please include the actual, raw output from ESLint.**

```
Cannot read property 'range' of null
TypeError: Cannot read property 'range' of null
    at OffsetStorage.setDesiredOffset (/Users/javiercastro/git/react-manager/node_modules/eslint/lib/rules/indent.js:335:45)
    at TemplateLiteral.node.expressions.forEach (/Users/javiercastro/git/react-manager/node_modules/eslint/lib/rules/indent.js:1305:29)
    at Array.forEach (<anonymous>)
    at Object.TemplateLiteral [as listener] (/Users/javiercastro/git/react-manager/node_modules/eslint/lib/rules/indent.js:1299:34)
    at Program:exit.listenerCallQueue.filter.forEach.nodeInfo (/Users/javiercastro/git/react-manager/node_modules/eslint/lib/rules/indent.js:1474:55)
    at Array.forEach (<anonymous>)
    at Program:exit (/Users/javiercastro/git/react-manager/node_modules/eslint/lib/rules/indent.js:1474:26)
    at listeners.(anonymous function).forEach.listener (/Users/javiercastro/git/react-manager/node_modules/eslint/lib/util/safe-emitter.js:47:58)
    at Array.forEach (<anonymous>)
    at Object.emit (/Users/javiercastro/git/react-manager/node_modules/eslint/lib/util/safe-emitter.js:47:38)
```

**Comment by jacargentina** [comment] 2018-03-02 11:26
I'm thinking it could be a babel-eslint issue....

**Comment by VidarLiu** [comment] 2018-04-26 05:56
clear between text and ${} space or change single quotes and plus sign connect text

**Comment by not-an-aardvark** [comment] 2018-06-07 07:52
Closing as a duplicate of https://github.com/eslint/eslint/issues/9872

**Closed by not-an-aardvark** 2018-06-07 07:52 UTC
Labels: bug, evaluating, rule
