### ISSUE TITLE
Cannot read property 'type' of undefined (destructuring props)

### ISSUE THREAD

**Issue by Baukaalm** [eslint/eslint#12343] opened 2019-09-30 15:43 UTC
```
const NextComposed = React.forwardRef((props, ref) => {
  const { as, href, prefetch, ...other } = props;
```
Cannot read property 'type' of undefined Occurred while linting 

```  
"extends": ["airbnb"],
  "parser": "babel-eslint",
  "env": {
    "node": true,
    "es6": true
  },
  "parserOptions": {
    "ecmaVersion": 9,
    "sourceType": "module",
    "ecmaFeatures": {
      "experimentalObjectRestSpread": true
    }
```

eslint v6.4.0

in vscode window at eslint plugin
```
Parsing error: Unexpected token
  23 | 
  24 | const NextComposed = React.forwardRef((props, ref) => {
> 25 |   const { as, href, prefetch, .other } = props;
     |                               ^
  26 |   return (
```

**Comment by Pegase745** [comment] 2019-09-30 16:18
The linting crashes with `eslint@6.5.0` anytime in a destructuration we want the rest ( `{stuff, ...rest}`). 
See `property.key` that is undefined in https://github.com/eslint/eslint/blob/master/lib/rules/no-useless-rename.js#L104

**Comment by sackeyjason** [comment] 2019-09-30 16:22
Here's a workaround: disable the no-useless-rename rule. From my package.json:

```
"no-useless-rename": [
  "error",
    {
      "ignoreDestructuring": true
    }
  ]
```

**Comment by kaicataldo** [comment] 2019-09-30 20:05
There are two different errors being reported here. The first one looks like a duplicate of https://github.com/eslint/eslint/issues/12335, while the second one looks like a correct syntax error (identifiers can’t begin with a `.` character).

**Comment by finom** [comment] 2019-09-30 21:01
Also getting the same error with `({...foo}) => "bar";`

**Comment by mdjermanovic** [comment] 2019-10-01 00:39
> Also getting the same error with `({...foo}) => "bar";`

This is also same as #12335. 

Tried `babel-eslint` and it generates `ExperimentalRestProperty` node in this case, too.

**Closed** 2019-11-01 22:43 UTC
Labels: bug, needs info
