### ISSUE TITLE
ES6 Module Issues

### ISSUE THREAD

**Issue by wavded** [eslint/eslint#2071] opened 2015-03-16 16:17 UTC
Using 0.17, given this code (with es6 env and modules turned on):

```js
import auth from 'basic-auth'
var foo = {}
var creds = auth(foo)
foo.creds = {
  username: creds.name,
  password: creds.pass
}
```

Gives this error:

```
/Users/wavded/.nvm/versions/io.js/v1.5.1/lib/node_modules/eslint/lib/rules/no-func-assign.js:42
                if (def.name.name === name && def.type === "FunctionName") {
                            ^
TypeError: Cannot read property 'name' of undefined
    at checkIfIdentifierIsFunction (/Users/wavded/.nvm/versions/io.js/v1.5.1/lib/node_modules/eslint/lib/rules/no-func-assign.js:42:29)
    at EventEmitter.AssignmentExpression (/Users/wavded/.nvm/versions/io.js/v1.5.1/lib/node_modules/eslint/lib/rules/no-func-assign.js:73:17)
    at emitOne (events.js:82:20)
    at EventEmitter.emit (events.js:166:7)
    at Controller.controller.traverse.enter (/Users/wavded/.nvm/versions/io.js/v1.5.1/lib/node_modules/eslint/lib/eslint.js:735:25)
    at Controller.__execute (/Users/wavded/.nvm/versions/io.js/v1.5.1/lib/node_modules/eslint/node_modules/estraverse/estraverse.js:393:31)
    at Controller.traverse (/Users/wavded/.nvm/versions/io.js/v1.5.1/lib/node_modules/eslint/node_modules/estraverse/estraverse.js:491:28)
    at EventEmitter.module.exports.api.verify (/Users/wavded/.nvm/versions/io.js/v1.5.1/lib/node_modules/eslint/lib/eslint.js:728:24)
    at processFile (/Users/wavded/.nvm/versions/io.js/v1.5.1/lib/node_modules/eslint/lib/cli-engine.js:193:27)
    at /Users/wavded/.nvm/versions/io.js/v1.5.1/lib/node_modules/eslint/lib/cli-engine.js:293:26
```

Another one is this code:

```js
import auth from 'basic-auth'
```

Gives this error:

```
/Users/wavded/.nvm/versions/io.js/v1.5.1/lib/node_modules/eslint/lib/rules/no-unused-vars.js:43
            if (definition.type === "VariableDeclarator") {
                          ^
TypeError: Cannot read property 'type' of undefined
    at isExported (/Users/wavded/.nvm/versions/io.js/v1.5.1/lib/node_modules/eslint/lib/rules/no-unused-vars.js:43:27)
    at EventEmitter.Program:exit (/Users/wavded/.nvm/versions/io.js/v1.5.1/lib/node_modules/eslint/lib/rules/no-unused-vars.js:120:70)
    at emitOne (events.js:82:20)
    at EventEmitter.emit (events.js:166:7)
    at Controller.controller.traverse.leave (/Users/wavded/.nvm/versions/io.js/v1.5.1/lib/node_modules/eslint/lib/eslint.js:743:25)
    at Controller.__execute (/Users/wavded/.nvm/versions/io.js/v1.5.1/lib/node_modules/eslint/node_modules/estraverse/estraverse.js:393:31)
    at Controller.traverse (/Users/wavded/.nvm/versions/io.js/v1.5.1/lib/node_modules/eslint/node_modules/estraverse/estraverse.js:481:28)
    at EventEmitter.module.exports.api.verify (/Users/wavded/.nvm/versions/io.js/v1.5.1/lib/node_modules/eslint/lib/eslint.js:728:24)
    at processFile (/Users/wavded/.nvm/versions/io.js/v1.5.1/lib/node_modules/eslint/lib/cli-engine.js:193:27)
    at /Users/wavded/.nvm/versions/io.js/v1.5.1/lib/node_modules/eslint/lib/cli-engine.js:293:26
```

**Comment by btmills** [comment] 2015-03-16 16:46
This is a duplicate of #2042, but since there are actually two bugs here, let's use this issue for the `no-func-assign` error and #2042 for the `no-unused-vars` crash that was reported second here.

**Comment by btmills** [comment] 2015-03-16 16:48
Upon further reading, it appears #2060 also reports the `no-func-assign` issue. #2061 is a PR to fix it. I propose closing this to track in #2060?

**Comment by nzakas** [comment] 2015-03-16 18:44
+1

**Closed by nzakas** 2015-03-16 18:44 UTC
Labels: accepted, bug, rule
