### ISSUE TITLE
INFO level would be nice

### ISSUE THREAD

**Issue by arpadpall21** [eslint/eslint#17078] opened 2023-04-09 09:31 UTC
### Syntax name

"level"

### Syntax proposal URL

{
    "rules": {
        "semi": ["info", "always"],
        "quotes": ["info", "double"]
    }
}

### Example code

```js
{
    "rules": {
        "semi": ["error", "always"],
        "quotes": ["error", "double"]
    }
}
```

### Implementation Checklist

- [ ] Ecma262 update: 
- [ ] ESTree update: 
- [ ] Acorn update: 
- [ ] `eslint-visitor-keys` update: 
- [ ] `espree` update: 
- [ ] `eslint-scope` update: 
- [X] `eslint` update: 

### Participation

- [ ] I am willing to submit a pull request for this change.

### Additional comments

Hello eslint team

It would be great to have a level between "off" and "warn"

Reason:
I only use eslint locally, it does its thing nicely but I find it a bit too aggressive to lint warn or error (VSCode highlights lint errors with yellow or red)
It would be so much better to highlight lint errors with blue (info)

Thank You

**Comment by arpadpall21** [comment] 2023-04-09 09:59
Extra suggestion:
 It would be really nice to limit the highest level for all rules (even if individual rules have higher levels) 
 
Something like:
```
{
    "rules": {
        "semi": ["error", "always"],
        "quotes": ["error", "double"]
    },
    maxSeverity: "info"
}
```

**Comment by Rec0iL99** [comment] 2023-04-09 17:53
Hi @arpadpall21, thanks for the suggestion. Can you please elaborate on what the `info` rule severity would exactly do?

I feel what you are suggesting is similar to the `warn` severity. You don't want linting to fail (`error` severity) but want to just show a warning (`warn` severity) to the user that an ESLint rule has been reported. Am I correct?

I'm quoting the docs here:

> If you don’t want to enforce compliance with a rule but would still like ESLint to report the rule’s violations, set the severity to "warn".

[Docs](https://eslint.org/docs/latest/use/configure/rules#rule-severities)

**Comment by nzakas** [comment] 2023-04-10 18:12
Duplicate of https://github.com/eslint/eslint/issues/6139.

This has been suggested before, but it doesn't actually make sense for ESLint. See the referenced issue above for discussion.

**Closed by nzakas** 2023-04-10 18:12 UTC
Labels: core, new syntax

**Comment by arpadpall21** [comment] 2023-04-11 17:15
Thank You for the explanation 

The idea was that for local development we would not have all these red and yellow warnings in the IDE for highlighting linting errors (those are usually for some syntax errors)
