### ISSUE TITLE
capitalized-comments cannot allow lower case inline comments at start of line

### ISSUE THREAD

**Issue by heimpogo** [eslint/eslint#7901] opened 2017-01-11 16:08 UTC
**What version are you using?**
v3.13.1

**What did you do?**
I set up `capitalized-comments` the following way:

    "capitalized-comments": ["error", "always", {
        line: {
            "ignorePattern": ".*"
        },
        block: {
            "ignoreInlineComments": true
        }
    }]

This leads to a problem when linting the following code with lower-case comments:

    trackEvent(
        /* category */ 'foo',
        /* action */ 'bar',
        /* label */ undefined,
        /* value */ 42);

**What happened?**
The `ignoreInlineComments` option does not match on cases with the comment at the beginning of the line by design. 

**What did you expect to happen?**
I was hoping to find an option to configure this rule to ignore any kind of linline comments - even at the beginning of a line.

**Comment by platinumazure** [comment] 2017-01-11 16:25
Worth noting that according to the [JSCS implementation](https://github.com/jscs-dev/node-jscs/blob/83a16478acbed90ad5b4129897b7b54f491f2037/lib/rules/require-capitalized-comments.js#L208-L217), those wouldn't be inline comments either. So it's currently working as designed.

**Comment by heimpogo** [comment] 2017-01-13 10:54
Yes, I understand, that this is working as intended. The documentation is clear about that. I consider this a feature request.

> By the way-- ESLint has not released a version 19.0.0. Are you using a wrapper?

Oops... I updated the version number.

**Comment by platinumazure** [comment] 2017-02-05 15:54
Ack, I lost track of this. Thanks @alberto for picking this up.

I always found the JSCS definition of "inline" a little weird here. I'm not sure what's more important- preserving that exact definition for compatibility, or augmenting it to something that makes sense without breaking the JSCS cases.

I wouldn't mind expanding that definition to mean, if there's a token before and after within the same immediate statement (or part thereof, for things like if conditions), that it doesn't matter if the tokens are on the same line as the comment.

@mikesherov Can you possibly speak to why requireCapitalizedComments defined inline comments so narrowly?

**Comment by alberto** [comment] 2017-03-11 19:04
Thanks for your interest in improving eslint. Unfortunately, it looks like this issue didn't get enough support from the team and so I'm closing it. While we wish we'd be able to accommodate everyone's requests, we do need to prioritize. We've found that issues failing to reach consensus after 21 days tend to never do it, and as such, we close those issues. This doesn't mean the idea isn't interesting, just that it's not something the team can commit to.

**Closed by alberto** 2017-03-11 19:04 UTC
Labels: enhancement, evaluating, rule
