### ISSUE TITLE
About using eslint with nodejs api

### ISSUE THREAD

**Issue by fylworker** [eslint/eslint#12186] opened 2019-08-30 12:02 UTC
Hey, I am having a problem using eslint in the way of the nodejs api. Here is a detailed description:

**ESLint Version: 5.13.0**
**Node Version: 9.9.0** 
**npm Version: 6.9.0**

**What parser (default, Babel-ESLint, etc.) are you using?**
No

**Full configuration:**
```json
{
  "name": "test-eslint",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "dependencies": {
    "@typescript-eslint/eslint-plugin": "1.4.2",
    "@typescript-eslint/parser": "1.4.2",
    "eslint": "5.13.0",
    "eslint-config-airbnb": "17.1.0",
    "eslint-loader": "2.1.2",
    "eslint-plugin-babel": "5.3.0",
    "eslint-plugin-import": "2.18.2",
    "eslint-plugin-jsx-a11y": "6.2.1",
    "eslint-plugin-react": "7.12.4",
    "typescript": "3.3.3"
  },
  "author": "",
  "license": "ISC"
}

```

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
// index.js
const fs = require('fs')
const eslint = require('eslint')
const config = require('./.eslintrc.js')


const content = fs.readFileSync(`${process.cwd()}/test.ts`).toString()

const { Linter } = eslint
const linter = new Linter()
const code = linter.verifyAndFix(content, config)
console.log(code)

// fs.writeFileSync('./aaa.ts', code.output)


// .eslintrc.js
module.exports = {
  extends: ['airbnb', 'plugin:@typescript-eslint/recommended'],
  parser: '@typescript-eslint/parser',
  env: {
    browser: true,
    node: true, 
  },
  plugins: [
    'react', 'import', 'jsx-a11y', '@typescript-eslint/eslint-plugin',
  ],
  parserOptions: {
    ecmaVersion: 6,
    sourceType: 'module',
    ecmaFeatures: {
      jsx: true,
    },
  },
  rules: {
    indent: ['error', 2, {
      SwitchCase: 1,
    }],
    'max-len': ['error', 200, 2, {
      ignoreComments: true,
    }],
    semi: ['error', 'never'],
    'import/newline-after-import': 'error',
  },
}

// test.ts
var a = 1
 console.log(a)

```

**Paste the command you used to run ESLint:**
```bash
node index.js
```

**What did you expect to happen?**
Output the formatted code.

**What actually happened? Please include the actual, raw output from ESLint.**
```js
{ fixed: true,
  messages:
   [ { ruleId: 'import/newline-after-import',
       severity: 2,
       message: 'Definition for rule \'import/newline-after-import\' was not found',
       line: 1,
       column: 1,
       nodeType: null 
} ],
  output: 'var a = 1\nconsole.log(a)\n' 
}
```

We are expecting a reply.

**Comment by kaicataldo** [comment] 2019-08-30 14:58
This looks like a duplicate of https://github.com/eslint/eslint/issues/12030. Please let us know if you still run into issues!

**Comment by fylworker** [comment] 2019-08-31 03:07
@kaicataldo So, thank you for your answer.

**Comment by ilyavolodin** [comment] 2019-08-31 15:39
Closing this issue as a duplicate of #12030

**Closed by ilyavolodin** 2019-08-31 15:39 UTC
Labels: question
