### ISSUE TITLE
Cannot find module 'eslint-config-google'

### ISSUE THREAD

**Issue by huchim** [eslint/eslint#9757] opened 2017-12-22 16:07 UTC
**Tell us about your environment**

* **ESLint Version:** 4.13.1
* **Node Version:** 8.9.1
* **npm Version:** 5.5.1

**What parser (default, Babel-ESLint, etc.) are you using?**

Default

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```json
{
    "extends": "google"
}
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
var c = 1;
```

```bash
mkdir test
cd test
npm init -y
npm i eslint --save-dev
touch index.js
eslint --init
> Use a popular style guide
>> Google
> What format do you want your config file to be in? (Use arrow keys)
>> JSON
npm update
eslint index.js
```

**What did you expect to happen?**

Show some rules violation...

**What actually happened? Please include the actual, raw output from ESLint.**

```bash
Cannot find module 'eslint-config-google'
Referenced from: /home/huchim/test/.eslintrc.json
Error: Cannot find module 'eslint-config-google'
Referenced from: /home/huchim/test/.eslintrc.json
    at ModuleResolver.resolve (/home/huchim/.nvm/versions/node/v8.9.1/lib/node_modules/eslint/lib/util/module-resolver.js:74:19)
    at resolve (/home/huchim/.nvm/versions/node/v8.9.1/lib/node_modules/eslint/lib/config/config-file.js:471:25)
    at load (/home/huchim/.nvm/versions/node/v8.9.1/lib/node_modules/eslint/lib/config/config-file.js:542:26)
    at configExtends.reduceRight (/home/huchim/.nvm/versions/node/v8.9.1/lib/node_modules/eslint/lib/config/config-file.js:421:36)
    at Array.reduceRight (<anonymous>)
    at applyExtends (/home/huchim/.nvm/versions/node/v8.9.1/lib/node_modules/eslint/lib/config/config-file.js:403:28)
    at loadFromDisk (/home/huchim/.nvm/versions/node/v8.9.1/lib/node_modules/eslint/lib/config/config-file.js:514:22)
    at Object.load (/home/huchim/.nvm/versions/node/v8.9.1/lib/node_modules/eslint/lib/config/config-file.js:550:20)
    at Config.getLocalConfigHierarchy (/home/huchim/.nvm/versions/node/v8.9.1/lib/node_modules/eslint/lib/config.js:228:44)
    at Config.getConfigHierarchy (/home/huchim/.nvm/versions/node/v8.9.1/lib/node_modules/eslint/lib/config.js:180:43)
```

I'm trying to follow the [getting started](https://eslint.org/docs/user-guide/getting-started) instructions, but i receiving the error `Cannot find module 'eslint-config-google'`... 

Thanks in advance!

**Comment by platinumazure** [comment] 2017-12-22 16:11
It looks like you're calling a global installation of ESLint. Try calling a local version so it can find your locally installed plugin.

```bash
$ ./node_modules/.bin/eslint index.is
```

If you create an npm script around ESLint, you can just say "eslint" there because npm will add `./node_modules/.bin` to your PATH. But on the command line, you need to point to the locally installed ESLint binary.

**Comment by huchim** [comment] 2017-12-22 16:25
I am very embarrassed that I didn't mention my previous global installation... and dodn'r read very well the documentation.

> Any plugins or shareable configs that you use must also be installed globally to work with a globally-installed ESLint.

Maybe `eslint --init` must install global or local according my eslint or warn me...

Thanks for your help @platinumazure 

/close

**Comment by platinumazure** [comment] 2017-12-22 19:54
@huchim No worries-- we need to improve the installation/init experience, that's for sure.

**Comment by not-an-aardvark** [comment] 2018-03-05 17:58
Closing because this is working as intended.

**Closed by not-an-aardvark** 2018-03-05 17:58 UTC
Labels: question

**Comment by DedaDev** [comment] 2018-06-01 11:20
Just install `eslint-config-google` globaly `npm install -g eslint eslint-config-google`.
