### ISSUE TITLE
Add native line endings option to linebreak-style

### ISSUE THREAD

**Issue by sholladay** [eslint/eslint#8596] opened 2017-05-14 20:18 UTC
The [linebreak-style](http://eslint.org/docs/rules/linebreak-style) rule is nice in that it ensures all linebreaks are the same. I consider that to always be appropriate.

However, its only available options currently are `unix` and `windows`. Thus, using this rule assumes a singular type of development environment. Neither option is appropriate on all platforms.

In every project I am a part of, we rely upon git to automatically convert the line endings when reading and writing between the object database and the working directory. I want CRLF on Windows and LF on UNIX-y systems and git handles this for us. But because of the `linebreak-style` rule, I cannot make `eslint` pass successfully on every platform, even when things are working as intended. ESLint outputs an error for every line in the project, making the experience pretty unusable for someone (by default, Windows developers).

I would like to see a `native` option added, which would respect the [`os.EOL` constant](https://nodejs.org/api/os.html#os_os_eol). This would work extremely well with git's defaults and improve the linting experience for Windows developers. 

Here is how I solved it in user land: https://github.com/sholladay/eslint-config-tidy/commit/ffe762fedc3d3dbb2f86e75ef88bd72a8694047f

**Comment by gyandeeps** [comment] 2017-05-14 20:25
may I ask whats the value added by such an option? Are you thinking from a windows perspective?

**Comment by sholladay** [comment] 2017-05-14 20:45
Updated to hopefully answer your question. Yes, this is about making it possible to have a cross-platform linting experience. As is, it is not possible to make `eslint` pass on both Windows and non-Windows for the exact same source code checked into git with git's defaults.

**Comment by gyandeeps** [comment] 2017-05-14 20:49
I have seen a lot windows developers use `as-is` git options on windows. This is when you install git on your machine and later you can change inside your global `.gitconfig` file. 
So options like this will not work for all. Where as you fix this issue by making a one time change to your git config.

**Comment by ljharb** [comment] 2017-05-14 21:13
This seems like it might be a duplicate of #7823 (which is still a problem that needs solving).

**Comment by sholladay** [comment] 2017-05-15 00:34
That doesn't look like what I want at all. That's deciding who wins by majority rules, which seems silly to me. What I'm asking for is the OS wins.

**Comment by ljharb** [comment] 2017-05-15 00:44
Gotcha. Certainly `native` would be a better choice than `unix` or `windows` :-).

**Comment by not-an-aardvark** [comment] 2017-05-21 01:00
Closing this issue because there were four :-1:s from team members on the associated PR, so I think it's safe to say that the team is not in favor of this proposal.

**Closed by not-an-aardvark** 2017-05-21 01:00 UTC
Labels: enhancement, evaluating, rule
