### ISSUE TITLE
Change Request: [new config system] Allow async configs

### ISSUE THREAD

**Issue by mdjermanovic** [eslint/eslint#16864] opened 2023-02-06 12:31 UTC
### ESLint version

v8.33.0

### What problem do you want to solve?

https://github.com/eslint/eslint/issues/16580#issuecomment-1332817365

If `eslint.config.js` must be a CJS module because the project is `"type": "commonjs"` (default; i.e., the project does not have `"type": "module"` in its `package.json` file), then it isn't possible to use ESM dependencies in `eslint.config.js` because the only way to load ESM from CJS is by using `import()`, but that returns a Promise.

### What do you think is the correct solution?

Allow async function configs, as proposed in the RFC:

* https://github.com/eslint/rfcs/blob/main/designs/2019-config-simplification/README.md#function-configs
* https://github.com/eslint/rfcs/blob/main/designs/2019-config-simplification/README.md#can-a-config-be-an-async-function
 
so that ESM dependencies can be used like this:

```js
// eslint.config.js
module.exports = async () => {

    const someDependency = await import("some-esm-dependency");

    return [
        // ... use `someDependency` here
    ];

};
```

### Participation

- [X] I am willing to submit a pull request for this change.

**Comment by nzakas** [comment] 2023-02-07 18:19
You can already use `-c eslint.config.mjs` and it will work as expected. It seems like that solves the use case for a CommonJS-only project?

As I've mentioned elsewhere, I just don't think it's a good idea to make concessions for CommonJS at this point in JavaScript's lifecycle. It will be used less and less, as long as we already have a workaround, I don't feel like anything else is needed.

**Comment by sam3k** [comment] 2023-02-10 00:49
Hi @mdjermanovic, based on @nzakas comment, it might make sense to close this issue since there are workarounds. I'll go ahead and close it; but please feel free to reopen if you think otherwise.

**Comment by nzakas** [comment] 2023-02-10 20:31
@sam3k Please meet @mdjermanovic :smile: He's a member of the ESLint team, so we like to leave these open until the team comes to a resolution. You can notice this on issues by the "Member" tag that appears in the upper-right corner of each comment.

In general, when team members open issues, we can just skip them right to "Ready for Dev Team".

**Comment by sam3k** [comment] 2023-02-11 23:22
@nzakas Ah! My bad. Noted. 😄

**Comment by nzakas** [comment] 2023-02-14 20:58
@sam3k no problem at all -- I should have mentioned this to you. Feel free to update the triage docs as we discover little glitches in the system like this.

**Comment by mdjermanovic** [comment] 2023-02-20 15:25
> You can already use `-c eslint.config.mjs` and it will work as expected. It seems like that solves the use case for a CommonJS-only project?

It works on the command line, but requires additional setup in IDEs and therefore doesn't seem like a convenient workaround.

> As I've mentioned elsewhere, I just don't think it's a good idea to make concessions for CommonJS at this point in JavaScript's lifecycle. It will be used less and less, as long as we already have a workaround, I don't feel like anything else is needed.

I think we should provide a way for the ESLint ecosystem to switch to ESM while not dropping support for CommonJS end users. If ESM plugins cannot conveniently be used in CJS projects, that will force plugins (and shareable configs) to stay on CJS or at least provide a CJS export, which means that they cannot use ESM-only dependencies.

**Comment by nzakas** [comment] 2023-02-27 21:32
> I think we should provide a way for the ESLint ecosystem to switch to ESM while not dropping support for CommonJS end users. If ESM plugins cannot conveniently be used in CJS projects, that will force plugins (and shareable configs) to stay on CJS or at least provide a CJS export, which means that they cannot use ESM-only dependencies.

I understand this line of thinking, I just disagree. Plugins can choose to also export CJS entrypoints if they want compatibility; current CommonJS users can stick with `.eslintrc` for probably the next year or two.

I just really don't like the complexity tradeoff to support a shrinking number of users. I also think that nudging more folks towards ESM is arguably a net positive for the ecosystem.

At the least, I think we should defer a decision here until we send out our survey and see what sort of data we get back about CJS vs. ESM.

**Comment by morganney** [comment] 2023-03-20 17:35
> At the least, I think we should defer a decision here until we send out our survey and see what sort of data we get back about CJS vs. ESM.

Why? You already know CJS will be a shrinking population of the user base. Why not stop all future development supporting CJS to some semver and start all future feature development on a different semver that only supports ESM?

**Comment by nzakas** [comment] 2023-03-20 21:37
@morganney As you can tell from this thread, there is disagreement on this approach, and so gathering some data will help to make the decision easier.

**Comment by sxzz** [comment] 2023-03-22 21:12
> You can already use `-c eslint.config.mjs` and it will work as expected. It seems like that solves the use case for a CommonJS-only project?

@nzakas Seems we can't

```
❯ eslint -c eslint.config.mjs

Oops! Something went wrong! :(

ESLint: 8.36.0

Error: ESLint configuration in --config is invalid:
        - Property "" is the wrong type (expected object but got `"import { all } from '@sxzz/eslint-config'\nexport default all"`).

    at ConfigValidator.validateConfigSchema (/path/node_modules/.pnpm/@eslint+eslintrc@2.0.1/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2156:19)
    at ConfigArrayFactory._normalizeConfigData (/path/node_modules/.pnpm/@eslint+eslintrc@2.0.1/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2998:19)
    at ConfigArrayFactory._loadConfigData (/path/node_modules/.pnpm/@eslint+eslintrc@2.0.1/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2963:21)
    at ConfigArrayFactory.loadFile (/path/node_modules/.pnpm/@eslint+eslintrc@2.0.1/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2829:40)
    at createCLIConfigArray (/path/node_modules/.pnpm/@eslint+eslintrc@2.0.1/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3637:35)
    at new CascadingConfigArrayFactory (/path/node_modules/.pnpm/@eslint+eslintrc@2.0.1/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3712:29)
    at new CLIEngine (/path/node_modules/.pnpm/eslint@8.36.0/node_modules/eslint/lib/cli-engine/cli-engine.js:606:36)
    at new ESLint (/path/node_modules/.pnpm/eslint@8.36.0/node_modules/eslint/lib/eslint/eslint.js:430:27)
    at Object.execute (/path/node_modules/.pnpm/eslint@8.36.0/node_modules/eslint/lib/cli.js:408:24)
    at async main (/path/node_modules/.pnpm/eslint@8.36.0/node_modules/eslint/bin/eslint.js:135:24)
```

**Comment by Rec0iL99** [comment] 2023-04-25 02:51
Not stale. Discussion around the issue is going on.

**Comment by fasttime** [comment] 2023-05-24 11:43
It is already possible to use asynchronous code (like dynamic imports) in a CommonJS config file by exporting a promise. For example, to amend the sample config in the original post, one could simply wrap the async function in an IIFE, i.e.

```js
// eslint.config.js
module.exports = (async () => {

    const someDependency = await import("some-esm-dependency");

    return [
        // ... use `someDependency` here
    ];

})();
```

To tell the truth, I've already used this pattern before ([**repro**](https://github.com/origin-1/eslint-plugin-eslint-env/blob/c1d62968a64117310b0be2e18be84dbc5b255913/eslint.config.js)). Now I realize that this usage was not intended.

**Comment by mdjermanovic** [comment] 2023-05-24 16:36
> It is already possible to use asynchronous code (like dynamic imports) in a CommonJS config file by exporting a promise. For example, to amend the sample config in the original post, one could simply wrap the async function in an IIFE, i.e.
> 
> ```js
> // eslint.config.js
> module.exports = (async () => {
> 
>     const someDependency = await import("some-esm-dependency");
> 
>     return [
>         // ... use `someDependency` here
>     ];
> 
> })();
> ```
> 
> To tell the truth, I've already used this pattern before ([**repro**](https://github.com/origin-1/eslint-plugin-eslint-env/blob/c1d62968a64117310b0be2e18be84dbc5b255913/eslint.config.js)). Now I realize that this usage was not intended.

Interesting, this really works in the current version because [`loadFlatConfigFile()`](https://github.com/eslint/eslint/blob/main/lib/eslint/flat-eslint.js#L279) just returns that promise and it ends up being  [`await`-ed](https://github.com/eslint/eslint/blob/5b68d51e3e6bd003d6cf74d3434f7165691b4f4d/lib/eslint/flat-eslint.js#L396) before used as a config object. I think this wouldn't work in versions before https://github.com/eslint/eslint/commit/df7740967ffab2915974c7b310ac76ea2915ac2d.

I'm pretty sure this wasn't intended to work, but perhaps we could make it official by adding tests.

**Comment by fasttime** [comment] 2023-05-25 06:23
> Interesting, this really works in the current version because [`loadFlatConfigFile()`](https://github.com/eslint/eslint/blob/main/lib/eslint/flat-eslint.js#L279) just returns that promise and it ends up being [`await`-ed](https://github.com/eslint/eslint/blob/5b68d51e3e6bd003d6cf74d3434f7165691b4f4d/lib/eslint/flat-eslint.js#L396) before used as a config object. I think this wouldn't work in versions before [df77409](https://github.com/eslint/eslint/commit/df7740967ffab2915974c7b310ac76ea2915ac2d).

This seems to be already working in v8.23.0, hence before that commit.

> I'm pretty sure this wasn't intended to work, but perhaps we could make it official by adding tests.

That seems reasonable. I'd be also not opposed to document the current behavior, rather than keeping it as an Easter egg. We should wait to see what @nzakas thinks.

**Comment by nzakas** [comment] 2023-06-19 17:43
Nice find @fasttime! Given that this has worked for the past eight months, I'm in favor of documenting it as expected functionality and adding tests to verify. :+1:

**Comment by simlu** [comment] 2023-06-19 18:15
Next step is to write a eslintrc.js that imports eslintrc.json and loads all the async dependencies... Then get that into core 🤦

**Closed** 2023-06-22 20:30 UTC
Labels: enhancement, core, accepted
