### ISSUE TITLE
`no-unused-vars` no longer works with `for (const key in keys)` 

### ISSUE THREAD

**Issue by hawkeye64** [eslint/eslint#12126] opened 2019-08-19 16:58 UTC
This code for object keys worked with eslint: 6.1.0 and no longer works with 6.2.0
```js
for (const key in keys) {
  if (key === this.wantedKey) {
    return key
  }
}
```
the error:
```
error   'key' is defined but never used  no-unused-vars
```
This may have been caused by this change:
https://github.com/eslint/eslint/commit/34ccc0cd81f495190e585c6efa8ae233d45bd3ed#diff-870af970159d7449848b5419fa485b96

**Tell us about your environment**

* **ESLint Version:**
6.2.0
* **Node Version:**
8.15.1
* **npm Version:**
6.10.3

**What parser (default, Babel-ESLint, etc.) are you using?**
babel-eslint: 10.0.2

<details>
<summary>Configuration</summary>

```js

```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js

```

```bash

```

**What did you expect to happen?**

**What actually happened? Please include the actual, raw output from ESLint.**

**Are you willing to submit a pull request to fix this bug?**

**Comment by kaicataldo** [comment] 2019-08-19 19:35
Duplicate of https://github.com/eslint/eslint/issues/12117. Closing in favor of that issue.

**Closed by kaicataldo** 2019-08-19 19:35 UTC
Labels: bug, triage
