### ISSUE TITLE
Feature request: rule to disallow unnecessary rule-disabling comments

### ISSUE THREAD

**Issue by emmettnicholas** [eslint/eslint#9332] opened 2017-09-20 03:44 UTC
It'd be nice if there were an eslint rule to disallow unnecessary eslint-rule-disabling comments. (Or, this could just be the default behavior, eliminating the need for a new rule.)

As an example, if I were to write:

```
const foo = 42; // eslint-disable-line no-unused-vars
console.log(foo);
```

It'd be nice to get an error along the lines of:

> error: 'no-unused-vars' rule suppression is unnecessary

As an example of this behavior in another tool, flow automatically errors out when it detects any unused suppressions:, which I've found to very handy:

> If there is no error on the next line (the suppression is unnecessary), an “Unused suppression” error will be shown instead.

https://flow.org/en/docs/config/options/#toc-suppress-comment-regex

**Comment by not-an-aardvark** [comment] 2017-09-20 03:46
Closing as a duplicate of https://github.com/eslint/eslint/issues/9249

**Closed by not-an-aardvark** 2017-09-20 03:46 UTC
Labels: triage
