### ISSUE TITLE
Bug: Performance Regression in ESLint 9.12.0

### ISSUE THREAD

**Issue by sergei-startsev** [eslint/eslint#19025] opened 2024-10-17 14:17 UTC
### Environment

Node version: v20.17.0
npm version: yarn v1.22.22
Local ESLint version: v9.12.0
Global ESLint version: -
Operating System: Ubuntu 22.04

### What parser are you using?

Default (Espree)

### What did you do?

The whole configuration cannot be shared. ESLint is run with the recommended preset and the following plugins:
- "eslint-plugin-css-modules": "^2.12.0"
- "eslint-plugin-import": "^2.31.0",
-  "eslint-plugin-jasmine": "^4.2.2",
-  "eslint-plugin-jest": "^28.8.3",
-  "eslint-plugin-jsx-a11y": "^6.10.0",
-  "eslint-plugin-promise": "^7.1.0",
-  "eslint-plugin-qunit": "^8.1.2",
-  "eslint-plugin-react": "^7.37.1",
-  "eslint-plugin-react-hooks": "^4.6.2",
-  "eslint-plugin-rxjs": "^5.0.3",
-  "eslint-plugin-storybook": "^0.9.0",
-  "eslint-plugin-testing-library": "^6.3.0",

### What did you expect to happen?

Performance remains the same when upgrading ESLint from v9.11.1 to v9.12.0

### What actually happened?

We noticed a significant (+20-30%) performance degradation upgrading ESLint from v9.11.1 to v9.12.0. For our large-scale project (~7M LOC), there's an increase in execution time of about 5-6 min:

![Image](https://github.com/user-attachments/assets/8f06913c-4416-4276-97e6-36cebf92d10f)

### Link to Minimal Reproducible Example

Not available

### Participation

- [ ] I am willing to submit a pull request for this issue.

### Additional comments

A preliminary analysis of the rules execution time hasn't revealed specific rules that could lead to such degradation. Instead, all rules on average work slower, which ultimately leads to an overall increase in execution time.

**Comment by snitin315** [comment] 2024-10-17 15:16
It's somewhat hard to reproduce, sharing the results I'm getting for this repository. 
|  v9.11.1 | v9.12.0   |
|---|---|
|  ![Image](https://github.com/user-attachments/assets/2c99fc7d-0c79-4bfc-a78a-7f6ac7a988cb) |  ![Image](https://github.com/user-attachments/assets/c9ae3023-0e82-411c-87d1-b785f451beb3) |

@sergei-startsev Can you to share a stackblitz link for minimal reproduction? Maybe just a basic project with an ESLint config setup with all those plugins?

**Comment by snitin315** [comment] 2024-10-17 15:43
I suspect https://github.com/eslint/eslint/pull/18742 might be the culprit. However, I see that `npx eslint --flag unstable_config_lookup_from_file .` is relatively faster

 ![Image](https://github.com/user-attachments/assets/a296f629-8ee4-4d98-a120-5774b64b7413)


@sergei-startsev Can you once try running `npx eslint --flag unstable_config_lookup_from_file .` in your project and see if it's still slower?

**Comment by sergei-startsev** [comment] 2024-10-17 16:58
> I suspect [#18742](https://github.com/eslint/eslint/pull/18742) might be the culprit. However, I see that `npx eslint --flag unstable_config_lookup_from_file .` is relatively faster
> [@sergei-startsev](https://github.com/sergei-startsev) Can you once try running `npx eslint --flag unstable_config_lookup_from_file .` in your project and see if it's still slower?

@snitin315 At first glance, it appears that the time has gone back to the results of v9.11.1 with `unstable_config_lookup_from_file` flag. I'll continue monitoring to rule out statistical deviations and will inform you of the results. Thanks!

**Comment by sergei-startsev** [comment] 2024-10-18 15:14
@snitin315 I can confirm that the linting time is back to normal with `unstable_config_lookup_from_file` flag:

![Image](https://github.com/user-attachments/assets/6191404a-b688-4b24-bad8-9dfe6acb63f1)

@nzakas / @mdjermanovic any ideas on how adding the new config loader could cause performance degradation of the current loader?

**Comment by nzakas** [comment] 2024-10-18 15:32
@sergei-startsev No clue. I also can't imagine why the unstable approach would be any faster considering that it does more file system lookups than the current stable approach. 

A couple of followups:

1. How many files do you have in your repo?
2. How are you producing the graph that you're posting? Having repro steps for that would help a lot.
3. Can you verify that you're using the same version of `eslint-plugin-import` in both cases?

**Comment by sergei-startsev** [comment] 2024-10-18 16:50
1. >30K files. The nesting depth is quite large.
2. We use an internal pipeline monitoring system. Simple ways to reproduce the problem haven't been successful. I guess that in order to reproduce the issue, you need to have a relatively large number of deeply nested files.
3. Yes, the same `eslint-plugin-import` version is specified in the lock file.

**Comment by nzakas** [comment] 2024-10-22 15:19
@sergei-startsev how did you generate the graphs that you're showing?

**Comment by mdjermanovic** [comment] 2024-10-22 18:16
@sergei-startsev can you share the command you use to run eslint? Do you pass globs/directories or maybe a list of all files?

I just noticed that when passing a list of files, eslint loads the config file and calculates config array for each file, so that might be the reason for the performance regression you noticed. The culprit would be the way LegacyConfigLoader works with cache in async code.

**Comment by sergei-startsev** [comment] 2024-10-22 19:29
@mdjermanovic You may be right in your guess. We use ESLint Node.js API passing in a list of already _resolved_ file paths:

```js
const eslint = new ESLint(options);
const results = await eslint.lintFiles(files);
```
where `files` is
```
[
 foo/1.js
 foo/2.js
 foo/3.js
 foo/N.js
 foo/bar/N.js
 foo/bar/baz/N.js
 ...
]
```

The array above contains thousands of items (>20K)

**Comment by mdjermanovic** [comment] 2024-10-22 20:17
I'm working on a possible fix.

**Comment by mdjermanovic** [comment] 2024-10-22 21:38
@sergei-startsev I prepared a possible fix: https://github.com/eslint/eslint/pull/19042. Could you test with that branch?

**Comment by sergei-startsev** [comment] 2024-10-23 19:46
@mdjermanovic Based my observations, the job execution time with the patch is either the same or even less than with 9.11.1 version. There may be some minor fluctuations (more data needed), but the resulted time is much less than we had with 9.12.0 (+20%). 

The experiment has been conducted with both enabled and disabled `unstable_config_lookup_from_file` flag. The results are almost the same. It seems to be a bit faster with `unstable_config_lookup_from_file` disabled, but there may be some deviations. I can provide more accurate results after the patch is released.

**Comment by mdjermanovic** [comment] 2024-10-23 21:00
Great, thanks for the info! Since I can reproduce the problem (https://github.com/eslint/eslint/pull/19042#issuecomment-2431900853), marking as accepted.

**Closed** 2024-10-28 12:59 UTC
Labels: bug, core, accepted, repro:yes

**Comment by mdjermanovic** [comment] 2024-11-01 19:34
@sergei-startsev eslint v9.14.0 has been released, and the fix for this issue is included. If and when you have time, please let us know if the performance with v9.14.0 is back to normal (pre-v9.12.0) in your environment.

**Comment by mdjermanovic** [comment] 2024-11-05 17:59
Glad the problem is solved, thanks for the info and help with testing!
