### ISSUE TITLE
Bug with new module feature?

### ISSUE THREAD

**Issue by jasonkuhrt** [eslint/eslint#1972] opened 2015-03-08 16:44 UTC
When I enable `modules: true` I get this error when trying to lint now:

```
λ eslint test-fuzzy/stacks.js                                                                                                                                           master 1f1a22b ●
/usr/local/lib/node_modules/eslint/node_modules/escope/escope.js:73
            throw new Error(text);
                  ^
Error
    at assert (/usr/local/lib/node_modules/eslint/node_modules/escope/escope.js:73:19)
    at Referencer.extend.ImportDeclaration (/usr/local/lib/node_modules/eslint/node_modules/escope/escope.js:1383:13)
    at Referencer.Visitor.visit (/usr/local/lib/node_modules/eslint/node_modules/escope/node_modules/esrecurse/esrecurse.js:109:34)
    at Referencer.Visitor.visitChildren (/usr/local/lib/node_modules/eslint/node_modules/escope/node_modules/esrecurse/esrecurse.js:88:38)
    at Referencer.extend.Program (/usr/local/lib/node_modules/eslint/node_modules/escope/escope.js:1236:18)
    at Referencer.Visitor.visit (/usr/local/lib/node_modules/eslint/node_modules/escope/node_modules/esrecurse/esrecurse.js:109:34)
    at Object.analyze (/usr/local/lib/node_modules/eslint/node_modules/escope/escope.js:1430:20)
    at EventEmitter.module.exports.api.verify (/usr/local/lib/node_modules/eslint/lib/eslint.js:651:35)
    at processFile (/usr/local/lib/node_modules/eslint/lib/cli-engine.js:193:27)
    at /usr/local/lib/node_modules/eslint/lib/cli-engine.js:293:26
```

**Comment by GastonRosso** [comment] 2015-03-08 16:58
Same here, but only happens when used in combination with "jsx": true

**Comment by nzakas** [comment] 2015-03-08 17:01
Duplicate of #1970

**Closed by nzakas** 2015-03-08 17:01 UTC

**Comment by jasonkuhrt** [comment] 2015-03-12 01:00
@nzakas I'm still seeing this issue with mater HEAD. Where is tracking of this issue happening now?
