### ISSUE TITLE
Add auto-fixing to newline-before-return

### ISSUE THREAD

**Issue by kaicataldo** [eslint/eslint#5958] opened 2016-04-25 00:02 UTC
Following @alberto's suit. ~~If accepted, I'd like to implement this.~~ I'll table this for now in favor of JSCS compatibility issues. If anyone else is interested in picking this up, please feel free.

Some interesting challenges I found while doing some initial work on this:
 - Keeping indentation (Not sure if necessary, given multi-pass auto-fixing, but seems like a nice thing to have)
 - If there's a comment between the `return` statement and the previous token, I think that the newline should come after the previous token (but before the comment), as this seemed to me to be the more often used case. This shouldn't be the behavior if the comment is on the same line as the previous token, though (in which case the newline should probably come after the comment).

Alternatively, if we feel like making those decisions is overreaching for a stylistic rule like this, then we can just not auto-fix if there are comments between the `return` statement and the previous token.

**Comment by alberto** [comment] 2016-04-25 06:28
Go for it

**Comment by nzakas** [comment] 2016-04-25 17:18
Just one thing to be aware of: adding a line break means we need to know what the line break style is.

Although, with multipass, that can be fixed on the next pass. Nevermind! :)

**Comment by alberto** [comment] 2016-04-25 19:17
Yes, that's the intention. We don't need to know that anymore. :)

**Comment by kaicataldo** [comment] 2016-04-29 16:32
I'll table this for now in favor of JSCS compat issues. If anyone else is interested in picking this up, please feel free.

**Comment by kaicataldo** [comment] 2016-04-29 16:41
@vitorbal Here's an issue kind of similar to https://github.com/eslint/eslint/issues/5959, if you're interested :)

**Comment by vitorbal** [comment] 2016-04-30 12:01
@kaicataldo thanks for pinging me, I'd certainly be interested :)
Would it be okay if I bug you later with some questions once I have a chance to dig a bit deeper into some existing examples of auto-fixing?

**Comment by kaicataldo** [comment] 2016-04-30 18:17
@vitorbal Any time :)

**Comment by kaicataldo** [comment] 2016-05-29 02:44
@vitorbal Pinging here to see how things are going

**Comment by alberto** [comment] 2016-05-29 06:44
I am not sure if this kind of fixes (assuming the `linebreak-style` rule is enabled) are a good idea anymore :/. What if it is not enabled because the user only develops on windows, so he doesn't think he needs that rule?

**Comment by vitorbal** [comment] 2016-05-29 10:43
Another problem i encountered is that:

If there's a comment on a line just above the return statement, then I dont
know how to determine if the newline should go above the comment or below
it.

**Comment by kaicataldo** [comment] 2016-05-29 17:57
Hm, yeah. The rule has also changed in the mean time, meaning the more clear-cut fix removing extra newlines is no longer necessary. Perhaps we should just close this.

**Comment by vitorbal** [comment] 2016-05-31 12:12
@eslint/eslint-team what do you guys think?

**Comment by mikesherov** [comment] 2016-05-31 12:17
IMO, the newline style, and tab style are both "top level" configuration options. I know we currently don't have this concept yet, but as we delve further and further into autofixing, we're going to see the need for it if we want individual rules to "do the right thing" in the absense of other rules that strictly require knowledge of newline style.

To that effect, I would propose that the internal API we use for autofixing should acquire an `addNewline` method that is aware of the style of newlines in the file (whether those are determined automatically by inspecting the current file or from a top level configuration).

**Comment by zxqfox** [comment] 2016-05-31 12:18
Agree with @mikesherov, would be great if we somehow support this.

**Comment by cristian-sima** [comment] 2016-05-31 13:33
+1 for auto-fix newline-before-return

**Comment by ilyavolodin** [comment] 2016-05-31 14:29
@mikesherov @zxqfox We discussed this before. However, now that we have multi-pass autofixing, I'm not sure we need it anymore. If you replace newline with just `\n`, next pass, `linebreak-style` will flag them as issues and autofix them. So in this particular case, we don't need shared styleguide.

**Comment by mikesherov** [comment] 2016-05-31 15:42
@ilyavolodin that's assuming the user is using the `linebreak-style` rule.

**Comment by ilyavolodin** [comment] 2016-05-31 17:09
Sorry, I wasn't clear. If both `linebreak-style` and `newline-before-return` are on, and you are running ESLint with fix flag, it doesn't matter if `newline-before-return` will insert correct style of the linebreak, because on the second pass, `linebreak-style` will kick in and fix it, if it doesn't match provided configuration. If `linebreak-style` isn't on, then we don't know what's the expected behavior should be. The only edge case I can see is going to happen when we will allow to run `fix` with only specific rules (which we also discussed). But in that case, what would happen is that after `newline-before-return` would insert a new linebreak in the incorrect style, next pass will flag it as an error and notify the user about it. At least they will know that something wrong happened, and can re-run fixer with the right rules turned on.

**Comment by platinumazure** [comment] 2016-05-31 17:14
@illyavolodin The flaw with that argument is very simple: we cannot assume
users will use linebreak-style and rely on that as a way to clean up after
a potentially incorrect auto-fix.

I'm not sure why it is that relying on multiple-pass auto-fix doesn't
strike anyone as a smell...

**Comment by mikesherov** [comment] 2016-05-31 17:16
i agree that the user *could* do that, but why make them work for it? Either way, seems like a generic "detect which new lines are being used* is a good thing regardless of whether it's from user supplied config or not. Anyway, it worked well for me in the past but if the group feels it not worth the effort, I won't advocate for it further.

**Comment by ilyavolodin** [comment] 2016-05-31 17:27
@platinumazure @mikesherov We can move generic discussion about autofixing into #6298 Until some sort of decision could be made and implemented there, we should just rely on existing capabilities, which is to autofix it with `\n` and have `linebreak-style` take care of autofixing linebreaks if it's configured for `windows`.

**Comment by vitorbal** [comment] 2016-05-31 17:52
Thanks for all the feedback everyone! Regardless of the mentioned above, I still don't know how to add autofixing to this rule because of the following:

> If there's a comment on a line just above the return statement, then I dont
> know how to determine if the newline should go above the comment or below
> it.

Any ideas how this could be done?

**Comment by zxqfox** [comment] 2016-05-31 22:01
I'd say, assume that comment is a something meaningful because it's not a whitespace or empty line. Why not to put empty line always after comment?

**Comment by vitorbal** [comment] 2016-06-01 09:04
Because the comment can be directly related to the return statement and some style guides would have them stay together. Take the following example:

```javascript
function foo() {
    var bar = doSomething();
    // return the result
    return bar;
}
```

We can fix it in the following two ways:

```javascript
function foo() {
    var bar = doSomething();

    // return the result
    return bar;
}
```

```javascript
function foo() {
    var bar = doSomething();
    // return the result

    return bar;
}
```

I don't know if it's safe to assume either of them is the correct fix for all cases.

**Comment by zxqfox** [comment] 2016-06-01 09:14
Ah, I though you about this case:
```js
function foo() {
  this.is();
  // The end.
}
```

I've misread issue title. In your case I'd stick comments to the next statement.

Actually, we can add options to tune it up but does it really need someone?

**Comment by nzakas** [comment] 2016-06-01 17:36
The gold standard for rule fixing is this: if the rule would flag the code as a problem, then you can safely fix it. Did the rule currently flag a`return` that has a comment on the previous line?

**Comment by vitorbal** [comment] 2016-06-02 14:18
@nzakas The rule would not flag these:
```javascript
function a() {
    if (b) {
        c();
    }
    //comment

    return b;
}
```

```javascript
function a() {
    if (b) {
        c();
    }

    //comment
    return b;
}
```

But would flag this:

```javascript
function a() {
    if (b) {
        c();
    }
    //comment
    return b;
}
```

**Comment by kaicataldo** [comment] 2016-06-02 15:50
Correct - the rule subtracts the number of comment lines from the total to calculate it, but it doesn't make any assumptions about/enforce a standard for where the line break is

**Comment by cristian-sima** [comment] 2016-06-25 12:06
Is the fix done?

**Comment by vitorbal** [comment] 2016-06-27 08:54
@cristian-sima the fix is unfortunately still not done. We haven't decided what to do regarding the discussion above, and if relying on the multi-pass is good enough.
One alternative would be having some shared repository settings, you can follow that discussion here: https://github.com/eslint/eslint/issues/6298

**Comment by cristian-sima** [comment] 2016-06-27 10:15
I am waiting for this fix to be done

**Comment by nzakas** [comment] 2016-06-28 17:13
@cristian-sima please just subscribe to this issue rather than leaving additional comments. When the fix has been checked in, the issue will be closed and you'll get notified.

**Comment by kaicataldo** [comment] 2016-08-25 21:11
@eslint/eslint-team Doesn't seem like we're really making any progress on this. I know it's accepted, but am wondering if we should close it?

**Comment by vitorbal** [comment] 2016-08-25 21:20
Looking back at my comment [here](https://github.com/eslint/eslint/issues/5958#issuecomment-222935057), do you think it would suffice to assume that inserting the newline *before* the comment is an acceptable fix (the first fixed example in that linked comment)?

Otherwise, I am still not sure how to determine that programmatically.

**Comment by kaicataldo** [comment] 2016-08-25 21:27
@vitorbal That makes sense to me. I think we have to make an assumption one way or another and that seems like the style I see more often

i.e.
```
function fn() {
  if (something) {
    /* 
     * multi-line comment
     */
    return a; 
  }

  // comment
  return b;
}
```

**Comment by platinumazure** [comment] 2016-08-25 21:33
Folks-- don't forget that we can always choose not to emit a fixer on a per-lint error basis if we don't think we can do it safely.

**Comment by vitorbal** [comment] 2016-08-29 13:02
@platinumazure very true! So an alternative would be that we just don't do a fix if we detect a comment just above the return statement.
@kaicataldo what do you think? Probably safer, although I also agree that the example in your last comment is the most obvious style used..

**Comment by kaicataldo** [comment] 2016-08-29 14:06
It's too bad we don't have an auto fix for lines-around-comment, or we could rely on multi pass fixing and just go ahead and fix everything. I could take a look and see if I can implement that as a prerequisite to this issue.

Otherwise, given that we don't have that yet, I think @platinumazure's reminder is a good one and we could just not fix that case. Fixing some things is better than not fixing anything!

**Comment by vitorbal** [comment] 2016-08-31 14:14
Okay, agreed. Thanks for the input everyone! I will work on this most likely during the weekend.

**Comment by vitorbal** [comment] 2016-09-01 11:43
Quick update: I'll probably have a PR for this by the weekend!

**Comment by cristian-sima** [comment] 2016-09-01 12:09
Fantastic!

**Closed** 2016-09-07 13:48 UTC
Labels: accepted, enhancement, rule
