### ISSUE TITLE
Bug: TypeError: Cannot read properties of undefined (reading 'type')

### ISSUE THREAD

**Issue by kodamor** [eslint/eslint#16899] opened 2023-02-16 11:44 UTC
### Environment

Node version: 16.14.2
yarn version: 1.22.19
Local ESLint version: 8.34.0
Global ESLint version: 8.34.0
Operating System: Debian GNU/Linux 10 (buster)

### What parser are you using?

@typescript-eslint/parser

### What did you do?

Everything worked before I did the following commands :  
```
yarn upgrade
eslint ./assets/js --ext .ts,.vue
```
I tried going to the previous version  but it did not resolve my issue

### What did you expect to happen?

I expected ESLint to run as usual

### What actually happened?

I received the following error :  
```
yarn run v1.22.19
$ eslint ./assets/js --ext .ts,.vue

Oops! Something went wrong! :(

ESLint: 8.34.0

TypeError: Cannot read properties of undefined (reading 'type')
Occurred while linting C:\Users\david\PhpstormProjects\interfaceb2b\assets\js\api\Data\ApplicationData.ts:1
    at Array.<anonymous> (C:\Users\david\PhpstormProjects\interfaceb2b\node_modules\eslint\node_modules\esquery\dist\esquery.min.js:1:29469)
    at C:\Users\david\PhpstormProjects\interfaceb2b\node_modules\eslint\node_modules\esquery\dist\esquery.min.js:1:29985
    at C:\Users\david\PhpstormProjects\interfaceb2b\node_modules\eslint\node_modules\esquery\dist\esquery.min.js:1:30512
    at Function.b.matches (C:\Users\david\PhpstormProjects\interfaceb2b\node_modules\eslint\node_modules\esquery\dist\esquery.min.js:1:34848)
    at NodeEventGenerator.applySelector (C:\Users\david\PhpstormProjects\interfaceb2b\node_modules\eslint\lib\linter\node-event-generator.js:296:21)
    at NodeEventGenerator.applySelectors (C:\Users\david\PhpstormProjects\interfaceb2b\node_modules\eslint\lib\linter\node-event-generator.js:324:22)
    at NodeEventGenerator.enterNode (C:\Users\david\PhpstormProjects\interfaceb2b\node_modules\eslint\lib\linter\node-event-generator.js:340:14)
    at CodePathAnalyzer.enterNode (C:\Users\david\PhpstormProjects\interfaceb2b\node_modules\eslint\lib\linter\code-path-analysis\code-path-analyzer.js:795:23)
    at C:\Users\david\PhpstormProjects\interfaceb2b\node_modules\eslint\lib\linter\linter.js:1153:32
    at Array.forEach (<anonymous>)
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Participation

- [ ] I am willing to submit a pull request for this issue.

### Additional comments

My package.json :  
```
    "eslint": "^8.22.0",
    "eslint-config-vue": "^2.0.2",
    "eslint-formatter-gitlab": "^4.0.0",
    "eslint-plugin-unused-imports": "^2.0.0",
    "eslint-plugin-vue": "^9.4.0",
    "eslint-webpack-plugin": "^3.2.0",
    "@typescript-eslint/eslint-plugin": "^5.36.1",
    "@typescript-eslint/parser": "^5.36.1",
    "@vue/eslint-config-typescript": "^11.0.0",
    "vue-eslint-parser": "^9.0.3",
```

**Comment by mdjermanovic** [comment] 2023-02-16 11:55
Duplicate of https://github.com/eslint/eslint/issues/16896

**Closed by mdjermanovic** 2023-02-16 11:55 UTC
Labels: bug, repro:needed
