### ISSUE TITLE
Where should be places sharable config's plugins?

### ISSUE THREAD

**Issue by nkt** [eslint/eslint#6836] opened 2016-08-03 11:08 UTC
Sorry for asking questions here, but I didn't got answer in your gitter channel.
I'm writing my own config and using `react` and `import` plugins. Where should I place these dependencies?
I mean it could be `peerDependencies` or it's ok to use `dependencies` in configuration package?

**Comment by ilyavolodin** [comment] 2016-08-03 13:51
They have to be both `peerDependancies` and `devDependancies`.

**Comment by nkt** [comment] 2016-08-03 15:41
@ilyavolodin it's sad, why I can't place them to just `dependencies`?

**Comment by ilyavolodin** [comment] 2016-08-03 15:57
`dependancies` of your plugin would be 3-rd level `dependancies` for ESLint, so ESLint will not be able to find them.

**Comment by nkt** [comment] 2016-08-03 16:00
@ilyavolodin I understand that, so it is a bug or feature? =)
I guess bug, cause eslint config is a vendor package and I don't specifying plugins, I just using config.

**Comment by ilyavolodin** [comment] 2016-08-03 16:16
@nkt It's neither a bug or a feature. It's just the way ESLint handles plugins/configs. ESLint can easily check config's `node_modules`, but what if plugin that you are using is also relies on some other plugin, and that one relies on something else as well? When do we stop checking nested dependancies? Bottom line, ESLint requires all of the configs/plugins to be top level dependancy. We have other issues opened regarding this problem (for example #3458), but so far we haven't been able to find any good solutions to this problem.

Closing, as the original question has been answered.

**Closed by ilyavolodin** 2016-08-03 16:16 UTC
Labels: question

**Comment by nkt** [comment] 2016-08-03 16:24
@ilyavolodin if one plugin relies to another plugin, this plugin dependencies will be resolved in the same way, recursively.
Ok, I should open another issue with feature-request for this?

**Comment by ilyavolodin** [comment] 2016-08-03 16:43
@nkt As far as I understand #3458 should cover you case, is that correct? If it is, you don't need to open another issue, as it will just be a duplicate of existing issue.

**Comment by nkt** [comment] 2016-08-03 17:39
@ilyavolodin yes, thanks!
