### ISSUE TITLE
Support relative paths in .eslintcache cache file

### ISSUE THREAD

**Issue by aaronabf** [eslint/eslint#16741] opened 2023-01-03 21:32 UTC
### ESLint version

v8.31.0

### What problem do you want to solve?

Currently, the eslint cache stores the absolute path to each file as opposed to the relative project path. The problem with this approach is it makes the file not portable. Why does this matter? Consider the common use-case of running eslint in a testing pipeline. In such a case, you only need to run eslint on modified files. I have seen techniques where a git diff determines which files eslint runs on. However, such a solution goes against best testing principles in which if the mainline branch has failing tests then so should a branch based on top. This would not be upheld if only modified files were considered. The cleanest way to support this is by uploading the eslint cache file on each merge to mainline and referencing this mainline cache file in each PR. Unfortunately, this is not possible if the paths are absolute.

### What do you think is the correct solution?

The cache file should support project-relative files.

### Participation

I am not familiar with the code-base.

**Comment by aaronabf** [comment] 2023-01-03 21:33
Related to [#14565](https://github.com/eslint/eslint/issues/14571).

**Comment by mdjermanovic** [comment] 2023-01-04 07:53
Duplicate of https://github.com/eslint/eslint/issues/16493. I'm closing this so that we don't have two open issues for the same functionality. An [RFC](https://github.com/eslint/rfcs) with details about this change is welcome.

**Closed by mdjermanovic** 2023-01-04 07:53 UTC
Labels: enhancement, triage, core
