### ISSUE TITLE
Rule idea: no function declarations *after* usages

### ISSUE THREAD

**Issue by OliverJAsh** [eslint/eslint#7876] opened 2017-01-06 10:07 UTC
It is currently possible to use ESLint to guarantee that function declarations are defined before usages, using `no-use-before-define`:

``` js
{
    // Function called before definition and assignment
    // Static error: ESLint: no-usage-before-define
    foo()
    const x = 1;
    function foo() { x; }
}
```

I would like to guarantee the opposite: function declarations must be defined *after* usages. This is a common pattern: using hoisting to define usages, and then the details come afterwards (in the hoisted function declarations).

The current solution to this is just to use `no-use-before-define`, but disabling it for function declarations. However, this means that, when reading code, one cannot be sure if the function declaration appears above or below. Asserting order as suggested here would be healthy for readability (functions always appear afterwards).

Here is an example of the suggested rule in use:

``` js
{
    // "no-function-usage-after-define" ensures the function is called before the
    // function is defined
    foo()
    const y = 1;
    // Here the dependency x is a function, so it must be defined after
    // The dependency y is not a function (and thus not hoisted), so must be
    // defined before.
    function foo() { x(); y; }
    function x() { 1; }
}
```

**Comment by ilyavolodin** [comment] 2017-01-06 15:13
Closing as duplicate of #7875

**Closed by ilyavolodin** 2017-01-06 15:13 UTC
Labels: triage
