### ISSUE TITLE
--fix-dry-run output omits errors that are fixable

### ISSUE THREAD

**Issue by cjmaio** [eslint/eslint#9739] opened 2017-12-19 21:22 UTC
**Tell us about your environment**

* **ESLint Version:** 4.13.1
* **Node Version:** 9.3.0
* **npm Version:** 5.6.0

**What parser (default, Babel-ESLint, etc.) are you using?** default

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
{
    "extends": "eslint:recommended",
    "rules": {
        "semi": ["error", "always"]
    }
}
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
var test = 'hello'

```

Control:
```bash
./node_modules/.bin/eslint index.js
```
Dry Run:
```bash
./node_modules/.bin/eslint index.js --fix-dry-run
```

**What did you expect to happen?**
The output would include both errors in the file, and in the case of the missing semicolon, would provide fixed code.

**What actually happened? Please include the actual, raw output from ESLint.**
Control:
```json
[
   {
      "filePath":"/Users/cmaio/Desktop/eslint-issue/index.js",
      "messages":[
         {
            "ruleId":"no-unused-vars",
            "severity":2,
            "message":"'test' is assigned a value but never used.",
            "line":1,
            "column":5,
            "nodeType":"Identifier",
            "source":"var test = 'hello'",
            "endLine":1,
            "endColumn":9
         },
         {
            "ruleId":"semi",
            "severity":2,
            "message":"Missing semicolon.",
            "line":1,
            "column":19,
            "nodeType":"VariableDeclaration",
            "source":"var test = 'hello'",
            "fix":{
               "range":[
                  18,
                  18
               ],
               "text":";"
            }
         }
      ],
      "errorCount":2,
      "warningCount":0,
      "fixableErrorCount":1,
      "fixableWarningCount":0,
      "source":"var test = 'hello'\n"
   }
]

```
Dry Run:
```json
[
   {
      "filePath":"/Users/cmaio/Desktop/eslint-issue/index.js",
      "messages":[
         {
            "ruleId":"no-unused-vars",
            "severity":2,
            "message":"'test' is assigned a value but never used.",
            "line":1,
            "column":5,
            "nodeType":"Identifier",
            "source":"var test = 'hello';",
            "endLine":1,
            "endColumn":9
         }
      ],
      "errorCount":1,
      "warningCount":0,
      "fixableErrorCount":0,
      "fixableWarningCount":0,
      "output":"var test = 'hello';\n"
   }
]
```

I do notice that a regular run now includes the fixes, so this may be a moot point, but if anything, the flag should be removed if it is causing legitimate errors to be dropped from the output... unless I am misinterpreting the purpose of this flag.

**Comment by platinumazure** [comment] 2017-12-19 21:40
Hi @cjmaio, thanks for the issue!

It's a little subtle, but the `output` property of the dry run actually does have the semi fix applied. So that output is different than the same `output` in the control (where it shows no fixes applied at all).

The only difference between `--fix` and `--fix-dry-run` is that the `output` values of the lint results are not written to disk. If you have a CLIEngine instance, you could call its `outputFixes` method to write all the outputs to disk. Or you can take the fixed code and use it some other way (e.g., write to an editor buffer, if you're writing an editor integration).

Hope this helps!

**Comment by cjmaio** [comment] 2017-12-19 21:43
Ahh, okay. I am writing a Phabricator plugin for ESLint and it wants me to provide the original line, and the fixed line, to integrate with the `arcanist` tool they provide. It looks like I may have to take another approach to that, since `--fix-dry-run` works in a different way than I thought.

Thank you for the clarification!

**Comment by platinumazure** [comment] 2017-12-19 21:47
@cjmaio Just the line? Or the source program/fixed program?

**Comment by cjmaio** [comment] 2017-12-19 21:51
In this case, it is just the line for the specific error message. In my simple example, the `arcanist` tool would expect me to pass:

```
Original: var test = 'hello'
Replacement: var text = 'hello';
```

I was trying to figure out a way of getting that output with ESLint, but I am not sure it's possible currently.

**Comment by platinumazure** [comment] 2017-12-19 22:00
@cjmaio Hmm... A simple way to do it would be to track the entire program and the fixed program (`output` property above), split each of them on newlines (`/\r\n|\r|\n|\u2028|\u2029/`), and then index into the resulting array using `line - 1` (IIRC the line is 1-based). But hopefully you can come up with something better!

**Comment by platinumazure** [comment] 2017-12-20 15:17
I'm going to close this since ESLint is working as designed here, but feel free to continue the discussion here or on our [Gitter chat](https://gitter.im/eslint/eslint) if you need any more help with your integration. Thanks!

**Closed by platinumazure** 2017-12-20 15:17 UTC
Labels: question
