### ISSUE TITLE
Better messaging about `^`

### ISSUE THREAD

**Issue by hzoo** [eslint/eslint#6814] opened 2016-08-01 14:47 UTC
Ref #6795
Ref https://github.com/eslint/eslint/pull/6804

Also I was just thinking that `npm install eslint` which also automatically uses `^`.  Just brainstorming, but I think we can maybe add a warning somehow (maybe after install) about using `~` instead of `^`?

Most users will still be surprised since they won't see the README/semver policy (mostly for our sake since we'll probably get a lot of reports unless users know about it)

**Comment by nzakas** [comment] 2016-08-03 17:40
I don't know -- I feel like that's ESlint being a bit too opinionated. Maybe people won't read the docs, but we can always point them to it. I'm not sure we need more than that.

**Comment by hzoo** [comment] 2016-08-04 01:16
Yeah hard to say. Was just exploring what we can do to inform since I think we'll get reports about it whenever there is something like that - given its the default.

**Comment by nzakas** [comment] 2016-08-10 00:23
I'm definitely :-1: on having ESLint check what your `package.json` says when it's running -- some may still want to use `^` and I don't want to nag them about it.

Do you have another recommendation?

**Comment by ljharb** [comment] 2016-08-10 00:24
Is it entirely out of the question to change the semver policy in such a way as more things cause semver-major bumps? There's zero things wrong with being on `v123.4.5` if it comes to that.

**Comment by nzakas** [comment] 2016-08-10 17:34
@ljharb we just formalized the policy, so I don't think it's worthwhile to investigate changing it again. We already had a bunch of discussion around it and there's no new information that I could see leading to a different result.

**Comment by ljharb** [comment] 2016-08-10 17:38
Gotcha, just wanted to throw that one out there.

**Comment by alberto** [comment] 2016-08-26 18:46
@ljharb actually there is an issue with plugins compatibility.

**Comment by ljharb** [comment] 2016-08-26 19:11
@alberto sure, the issue is that plugins would have to release more aggressively.

**Comment by nzakas** [comment] 2016-08-29 19:45
Unfortunately, it looks like consensus couldn't be reached on this issue and so I'm closing it. While we wish we'd be able to accommodate everyone's requests, we do need to prioritize. We've found that issues failing to reach consensus after 21 days tend never to reach consensus, and as such, we close those issues. This doesn't mean the idea isn't interesting, just that it's not something the team can commit to.

**Closed by nzakas** 2016-08-29 19:45 UTC
Labels: core, enhancement, evaluating, needs bikeshedding
