### ISSUE TITLE
missing rule? indentation check

### ISSUE THREAD

**Issue by remitbri** [eslint/eslint#1623] opened 2015-01-04 01:51 UTC
Hi. I've tried to review each and every rule of JSHint, JSCS and ESLint to see if I could entirely "get rid of" the first two in favour of the latter one. As suggested by the owner of the @geteslint twitter account, I'm reporting the JSCS rules I've found actually not covered by ESLint. My apologies: I guess this one is indeed a duplicate.

The possibility to set tabulation or space indentation, with the number of spaces specified if needed. Though if I understand there's the nodeca plugin which does that.
Sure it's formatting, but having such a rule helps when you're working for various clients with various indentations settings… :)

**Comment by lo1tuma** [comment] 2015-01-04 02:02
Duplicate of #1022

**Closed** 2015-01-04 02:06 UTC
