### ISSUE TITLE
Ignore trailing spaces in comments (no-trailing-spaces)

### ISSUE THREAD

**Issue by moll** [eslint/eslint#2810] opened 2015-06-20 21:38 UTC
Hey,

Often, when writing (JSDoc) documentation in block comments, one needs to add two trailing spaces to make a hard linebreak in Markdown. Those get flagged by **no-trailing-spaces**, an otherwise useful rule for code itself. It would be useful to optionally ignore trailing spaces in comments. For added benefit, only in block or documentation-comments (the latter start with two asterisks by convention).

**Comment by lo1tuma** [comment] 2015-06-20 21:43
Duplicate of #1229.

**Closed** 2015-06-22 18:51 UTC
Labels: question
