### ISSUE TITLE
[no-unused-vars] rule reports an error for... in/of

### ISSUE THREAD

**Issue by tichenchen** [eslint/eslint#12455] opened 2019-10-18 03:04 UTC
### The version of eslint
6.5.1
### The details of the problem
`for (const item of items ) { console.log(item)}`
no-unused-vars reports an error to the above code block，What's the reason

**Comment by platinumazure** [comment] 2019-10-18 15:12
Possible duplicate of #12117.

If you're using babel-eslint, please upgrade to latest.

**Comment by g-plane** [comment] 2019-10-19 01:20
Out of this issue, should we pin an issue to issues list to prevent duplicated issues about this problem (which is related to `no-unused-vars` and "babel-eslint")?

**Comment by tichenchen** [comment] 2019-10-21 09:31
It's really because of babel-eslint, Thank you. 
I think it's a good idea to have a list of questions.

**Comment by tichenchen** [comment] 2019-10-21 09:32
> Out of this issue, should we pin an issue to issues list to prevent duplicated issues about this problem (which is related to `no-unused-vars` and "babel-eslint")?

It's really because of babel-eslint, Thank you.
I think it's a good idea to have a list of questions.

**Closed** 2019-10-21 09:32 UTC
Labels: bug, evaluating, rule
