### ISSUE TITLE
[no-unneeded-ternary] add check for duplicates ternary

### ISSUE THREAD

**Issue by Alex-Sokolov** [eslint/eslint#13531] opened 2020-07-27 07:50 UTC
**What rule do you want to change?**
no-unneeded-ternary

**Does this change cause the rule to produce more or fewer warnings?**
More warnings

**How will the change be implemented? (New option, new default behavior, etc.)?**
New code check

**Please provide some example code that this change will affect:**

```js
const themeFromApi = account_settings
        ? account_settings.theme
          ? account_settings.theme
          : null
        : null
```

**Example code after auto-fix:**
```js
const themeFromApi = account_settings
        ? account_settings.theme
        : null
```

**What does the rule currently do for this code?**
Nothing

**What will the rule do after it's changed?**
Check that condition checked two times and that's not needed or something in condition missed/misspelled

**Are you willing to submit a pull request to implement this change?**
No

**Comment by Alex-Sokolov** [comment] 2020-07-27 19:23
@mdjermanovic added to first post!

**Comment by mdjermanovic** [comment] 2020-07-27 19:34
Thanks for clarifying!

However, these two expressions are not equivalent, so it looks like the rule might report a valid code.

For example, if `account_settings.theme` is `undefined`, the original expression evaluates to `null`, but the expression after auto-fix evaluates to `undefined`.

**Comment by Alex-Sokolov** [comment] 2020-07-28 06:11
Maybe then do not do auto-fix for the rule, but offer more explicit checks in such cases.

**Comment by mdjermanovic** [comment] 2020-07-28 18:53
Yes, we can avoid auto-fixing in some cases, but it should be clear (either in the message or in the docs) why is the code reported and how should the changed code look like since this rule is about ["simpler alternatives"](https://eslint.org/docs/rules/no-unneeded-ternary#rule-details) (which implies that the new code should be equivalent).

In this example, an equivalent code would be:

```js
const themeFromApi = account_settings
        ? account_settings.theme || null
        : null
```

so it seems that the rule might just directly detect and report the nested ternary `account_settings.theme ? account_settings.theme : null`, which should be replaced with `account_settings.theme || null`.

In that case, I think this is a duplicate of #13486.

**Comment by mdjermanovic** [comment] 2020-07-28 19:13
An advanced version of this rule might even suggest `const themeFromApi = account_settings && account_settings.theme || null` instead of the both ternaries, but that's out of scope given the [new rules policies](https://eslint.org/blog/2020/05/changes-to-rules-policies).

**Comment by Alex-Sokolov** [comment] 2020-08-08 12:04
What's the best place/plugin where suggest to add that check?

**Comment by mdjermanovic** [comment] 2020-08-08 22:48
> What's the best place/plugin where suggest to add that check?

Some popular plugins are listed here: https://github.com/dustinspecker/awesome-eslint

I can't recommend any specific plugin, but I'd guess this rule might fit some generic plugin, like those in the code quality section.

You can also search for `eslint-plugin` on npm, or make your own plugin.

**Closed** 2020-09-09 00:29 UTC
Labels: enhancement, evaluating, rule
