### ISSUE TITLE
eslint --init does not work with @flow

### ISSUE THREAD

**Issue by kutyel** [eslint/eslint#7586] opened 2016-11-12 13:07 UTC
**Tell us about your environment**
macOS Sierra 10.12.1
* **ESLint Version:**
v3.3.1
* **Node Version:**
v6.9.1
* **npm Version:**
v3.10.8
**What parser (default, Babel-ESLint, etc.) are you using?**
babel-eslint
**Please show your full configuration:**
```json
{
  "devDependencies": {
    "babel-cli": "^6.18.0",
    "babel-eslint": "^7.1.0",
    "babel-jest": "^17.0.0",
    "babel-plugin-transform-flow-strip-types": "^6.18.0",
    "babel-preset-es2015": "^6.18.0",
    "eslint": "^3.9.1",
    "eslint-config-airbnb": "^13.0.0",
    "eslint-plugin-flowtype": "^2.25.0",
    "eslint-plugin-import": "^2.2.0",
    "eslint-plugin-jsx-a11y": "^3.0.1",
    "eslint-plugin-react": "^6.6.0",
    "flow-bin": "^0.34.0",
    "jest": "^17.0.0"
  }
```
**What did you do? Please include the actual source code causing the issue.**
```sh
./node_modules/.bin/eslint --init
```
**What did you expect to happen?**
I have a project with **flow** annotations that I wanted to use as a source for my custom `.eslintrc` file and it breaks.

I guess we have two options:

1. Either we strip the annotations when it is a flow annotated file and then run `eslint --init`...
2. Or we support natively from eslint itself flow annotations (maybe taking them from [eslint-plugin-flowtype](https://github.com/gajus/eslint-plugin-flowtype)?)

Whatever is chosen I would be happy to help and implement the solution! 😄 

**What actually happened? Please include the actual, raw output from ESLint.**
```
Determining Config: 0% [------------------------------] 0.0s elapsed, eta 0.0s 

(/Users/flaviocorpa/WebstormProjects/flow-linq/src/List.js:16:11) Parsing error: Unexpected token <
Error: (/Users/flaviocorpa/WebstormProjects/flow-linq/src/List.js:16:11) Parsing error: Unexpected token <
    at getSourceCodeOfFile (/Users/flaviocorpa/WebstormProjects/flow-linq/node_modules/eslint/lib/util/source-code-util.js:39:15)
    at /Users/flaviocorpa/WebstormProjects/flow-linq/node_modules/eslint/lib/util/source-code-util.js:95:28
    at Array.forEach (native)
    at getSourceCodeOfFiles (/Users/flaviocorpa/WebstormProjects/flow-linq/node_modules/eslint/lib/util/source-code-util.js:94:15)
    at configureRules (/Users/flaviocorpa/WebstormProjects/flow-linq/node_modules/eslint/lib/config/config-initializer.js:131:23)
    at processAnswers (/Users/flaviocorpa/WebstormProjects/flow-linq/node_modules/eslint/lib/config/config-initializer.js:254:18)
    at .completed (/Users/flaviocorpa/WebstormProjects/flow-linq/node_modules/eslint/lib/config/config-initializer.js:414:30)
    at PromptUI.onCompletion (/Users/flaviocorpa/WebstormProjects/flow-linq/node_modules/inquirer/lib/ui/prompt.js:57:10)
    at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.completed (/Users/flaviocorpa/WebstormProjects/flow-linq/node_modules/rx-lite/rx.lite.js:1550:12)
    at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/Users/flaviocorpa/WebstormProjects/flow-linq/node_modules/rx-lite/rx.lite.js:1489:14)
```

I had a look at the code and it breaks when reading the first generic:
```js
class List<T> {
          ^^^
```

Thanks in advance!

**Comment by platinumazure** [comment] 2016-11-12 17:01
Hmm. It seems to me like we might be using the default parser for that mode of `--init`-- maybe we need to ask a question about whether experimental features are used and/or which parser should be used when creating a configuration based on the existing files?

@IanVS, any thoughts on this?

**Comment by platinumazure** [comment] 2016-11-12 17:27
Confirmed, labeling as a bug for now.

It might be that other parsers or experimental features are "not supported", in which case this might turn into an enhancement request. Either way, I think we can improve the experience here.

Thanks for the report!

**Comment by kutyel** [comment] 2016-11-12 17:35
You are welcome 😊

**Comment by IanVS** [comment] 2016-11-12 18:45
@platinumazure yes, it has been on my mind to use custom parsers in the `--init` process, but I haven't seen issues come in for it so I haven't spent the time to work on it.  I believe the thing to do is install and use a custom parser based on responses to the questions we ask.  Babel-eslint would be a good start, but we could also add the TypeScript parser now that it has been released.  I'm not super familiar with the Flow story for ESLint.  Maybe someone else with more experience there can suggest the "right" thing to do, whether to strip them out or add the flow plugin (or another option I don't know about).

**Comment by nzakas** [comment] 2016-12-28 18:58
I don't think we should make a change here. There's no guarantee that core rules work correctly with Flow, TypeScript, or any other dialect other than plain JS. I'm not sure there's much value to most users in going through the process if we can't know whether or not the results will be useful.

**Comment by platinumazure** [comment] 2016-12-28 19:01
[@nzakas' comment](https://github.com/eslint/eslint/issues/7586#issuecomment-269523045) makes a lot of sense. If we choose not to make a change here, though, I would propose we should have either a question or comment show up during `--init` which asks the user to confirm they're using only/mostly standard features (or just mentions that we can't guarantee `--init` will work with nonstandard features), as I can see this continuing to be a point of confusion.

**Comment by not-an-aardvark** [comment] 2016-12-28 19:05
Maybe we could catch the parsing error and ask the user afterwards if they would like to install/use a custom parser?

It's possible new users won't know what parser to select, but it seems better than crashing and aborting immediately.

**Comment by platinumazure** [comment] 2016-12-28 19:08
@not-an-aardvark I have no objection to that proposal except simply to question if it's worth the development/maintainability cost. If nothing else, we could start by documenting the limitation, then revisiting if we get more demand for change.

**Comment by not-an-aardvark** [comment] 2017-07-11 03:46
Thanks for your interest in improving ESLint. Unfortunately, it looks like this issue didn't get enough support from the team and so I'm closing it. While we wish we'd be able to accommodate everyone's requests, we do need to prioritize. We've found that issues failing to reach consensus after a long time tend to never do it, and as such, we close those issues. This doesn't mean the idea isn't interesting, just that it's not something the team can commit to.

**Closed by not-an-aardvark** 2017-07-11 03:46 UTC
Labels: bug, cli, evaluating
