### ISSUE TITLE
RE literal starting with an equals sign not usabe

### ISSUE THREAD

**Issue by danielrentz** [eslint/eslint#6286] opened 2016-05-30 16:43 UTC
**What version of ESLint are you using?**
2.11.0 (via grunt-eslint 18.1.0)

**What parser (default, Babel-ESLint, etc.) are you using?**
default

**Please show your full configuration:**

**What did you do? Please include the actual source code causing the issue.**

**What did you expect to happen?**

**What actually happened? Please include the actual, raw output from ESLint.**
"no-div-regex" and "no-useless-escape" together prevent using RE literals starting with an equals sign:

    /=/
triggers "no-div-regex" rule

    /\=/
triggers "no-useless-escape" rule

**Comment by platinumazure** [comment] 2016-05-30 17:03
We'll need to enhance one of the rules for sure. The question is, which one?

**Comment by danielrentz** [comment] 2016-05-30 17:15
Maybe "no-div-regex" should let pass the RE if it is enclosed in parentheses?
    if ((/=/).test(...)) { ... }

**Comment by michaelficarra** [comment] 2016-05-30 17:17
Duplicate of #6098. See my suggestions for the many ways you can avoid this issue: https://github.com/eslint/eslint/issues/6098#issuecomment-217487031.

**Closed by michaelficarra** 2016-05-30 17:17 UTC
Labels: triage

**Comment by danielrentz** [comment] 2016-05-30 17:27
Hm, do not like so much to be forced by a tool to use some workarounds, but it's a minor issue, so ok with me :)
