### ISSUE TITLE
Replace `eslintConfig` with `eslint` in package.json config

### ISSUE THREAD

**Issue by alexeyraspopov** [eslint/eslint#5735] opened 2016-03-29 22:35 UTC
Hey guys! At first I want to thank you all, who participate in creating this tool. I'm using it everyday and I appreciate the work you're doing.

I'm not that good in contributing and this change request won't be technical. But I hope it will reduce the level of entropy in the world and make the usage more predictable.

**What version of ESLint are you using?**
`2.5.3`

**What parser (default, Babel-ESLint, etc.) are you using?**
`default`

And here is my "pain":
![image](https://cloud.githubusercontent.com/assets/858295/14137115/06b5743c-f66f-11e5-892e-f6f93e1205b9.png)

Yes, I might be too picky about this thing, but I do believe that at some point of time imaginary user will add `eslint` key instead of `eslintConfig` subconsciously, expecting the same result as other tools.

I propose to change this key to `eslint` or at least support both options (`eslint` and `eslintConfig`) untill next major version).

I hope you'll understand me and won't be laughing about probably useless request.

**Comment by nzakas** [comment] 2016-03-30 15:15
Duplicate of https://github.com/eslint/eslint/issues/2670

**Closed by nzakas** 2016-03-30 15:15 UTC
Labels: triage
