### ISSUE TITLE
Indentation for dot-location

### ISSUE THREAD

**Issue by Erid** [eslint/eslint#5327] opened 2016-02-18 20:55 UTC
I was looking for a way to enforce the indentation on chained properties and I found https://stackoverflow.com/questions/33784939/enforcing-indentation-of-properties-with-eslint.

In summary we want a way to enforce (or prevent) indentation like:
```
object
  .property
  .anotherProperty
```

And avoid having:
```
object
.property
.anotherProperty
```

We can probably extend the rule "dot-location" to accept a configuration for indentation, right now it doesn't care where it's indented or aligned.

**Comment by gyandeeps** [comment] 2016-02-18 20:59
Please follow the discussion on https://github.com/eslint/eslint/issues/5073

**Comment by ilyavolodin** [comment] 2016-02-18 21:09
Thanks for the issue. This is a know issue with indentation of multi-line expression. We do not currently have a good solution for it, but we are discussing different options in #5073
Closing as a duplicate of #5073

**Closed by ilyavolodin** 2016-02-18 21:09 UTC
Labels: triage
