### ISSUE TITLE
Fix for brace-style stroustrup adds unneeded whitespace / misalignment

### ISSUE THREAD

**Issue by stefan-schweiger** [eslint/eslint#14233] opened 2021-03-19 11:02 UTC
**Tell us about your environment**

ES Lint v7.22.0

```
brace-style: ["error", "stroustrup"]
```

[ES Lint Demo](https://eslint.org/demo#eyJ0ZXh0IjoiLyplc2xpbnQgYnJhY2Utc3R5bGU6IFtcImVycm9yXCIsIFwic3Ryb3VzdHJ1cFwiXSAqL1xuXG5pZiAodHJ1ZSkge1xuICBjb25zb2xlLmxvZyhcIlRlc3RcIik7XG59IGVsc2Uge1xuICBjb25zb2xlLmxvZyhcIkVsc2VcIik7XG59XG4iLCJvcHRpb25zIjp7InBhcnNlck9wdGlvbnMiOnsiZWNtYVZlcnNpb24iOjExLCJzb3VyY2VUeXBlIjoic2NyaXB0IiwiZWNtYUZlYXR1cmVzIjp7fX0sInJ1bGVzIjp7ImJyYWNlLXN0eWxlIjoyfSwiZW52Ijp7fX19)

**What did you do?**

The automatic fix for brace-style stroustrup adds a whitespace in the next line. This leads to if and else being misaligned.

I've tried to fix this with `keyword-spacing: [ "error", { "overrides": { "else": { "before": false } } }]` but to now avail. So I think this is actually a bug in eslint.

```js
if (true) {
  console.log("Test");
} else {
  console.log("Else");
}
```

**What did you expect to happen?**

```js
if (true) {
  console.log("Test");
}
else {
  console.log("Else");
}
```

**What actually happened?**

```js
if (true) {
  console.log("Test");
}
 else { // "_else {"
  console.log("Else");
}
```

**Comment by mdjermanovic** [comment] 2021-03-19 15:49
Hi @stefan-schweiger, thanks for the issue!

> The automatic fix for brace-style stroustrup adds a whitespace in the next line. This leads to if and else being misaligned.

The fix actually just [adds a linebreak](https://github.com/eslint/eslint/blob/master/lib/rules/brace-style.js#L144) after `}`. The extra space is the space that already existed between `}` and `else`.

In my opinion, this works as intended. Fixers are designed to make as small as possible changes in the source code to satisfy the rule, and let other formatting rules fix the new layout in subsequent iterations.

> I've tried to fix this with keyword-spacing: [ "error", { "overrides": { "else": { "before": false } } }] but to now avail. 

In this case, [indent](https://eslint.org/docs/rules/indent) rule is expected to fix indentation for the new `else` line:

[Online Demo](https://eslint.org/demo#eyJ0ZXh0IjoiLyplc2xpbnQgYnJhY2Utc3R5bGU6IFtcImVycm9yXCIsIFwic3Ryb3VzdHJ1cFwiXSAqL1xuLyplc2xpbnQgaW5kZW50OiBbXCJlcnJvclwiLCAyXSovXG5cbmlmICh0cnVlKSB7XG4gIGNvbnNvbGUubG9nKFwiVGVzdFwiKTtcbn0gZWxzZSB7XG4gIGNvbnNvbGUubG9nKFwiRWxzZVwiKTtcbn1cbiIsIm9wdGlvbnMiOnsicGFyc2VyT3B0aW9ucyI6eyJlY21hVmVyc2lvbiI6MTEsInNvdXJjZVR5cGUiOiJzY3JpcHQiLCJlY21hRmVhdHVyZXMiOnt9fSwicnVsZXMiOnsiYnJhY2Utc3R5bGUiOjJ9LCJlbnYiOnt9fX0=)

We could maybe modify the fixer for `brace-style` to also remove whitespace between `}` and `else`, but that still wouldn't solve indentation for nested blocks ([demo example](https://eslint.org/demo#eyJ0ZXh0IjoiLyplc2xpbnQgYnJhY2Utc3R5bGU6IFtcImVycm9yXCIsIFwic3Ryb3VzdHJ1cFwiXSAqL1xuXG5pZiAodHJ1ZSkge1xuICBpZiAodHJ1ZSkge1xuICAgIGNvbnNvbGUubG9nKFwiVGVzdFwiKTtcbiAgfWVsc2Uge1xuICAgIGNvbnNvbGUubG9nKFwiRWxzZVwiKTtcbiAgfVxufVxuIiwib3B0aW9ucyI6eyJwYXJzZXJPcHRpb25zIjp7ImVjbWFWZXJzaW9uIjoxMSwic291cmNlVHlwZSI6InNjcmlwdCIsImVjbWFGZWF0dXJlcyI6e319LCJydWxlcyI6eyJicmFjZS1zdHlsZSI6Mn0sImVudiI6e319fQ==)).

**Comment by nzakas** [comment] 2021-05-04 00:28
Closing as this is working as intended.

**Closed by nzakas** 2021-05-04 00:28 UTC
Labels: bug
