### ISSUE TITLE
should.js no-unused-expressions

### ISSUE THREAD

**Issue by willin** [eslint/eslint#2129] opened 2015-03-23 05:21 UTC
iojs 1.6.1
eslint 0.17.1
should 5.2.0

**Comment by michaelficarra** [comment] 2015-03-23 13:17
This is one of the worst bug reports I've ever seen. Unfortunately, I know what you're trying to say and it's invalid and duplicate.

**Comment by nzakas** [comment] 2015-03-23 16:21
@willin Please read over our contribution guide to see how to for a proper issue: http://eslint.org/docs/developer-guide/contributing.html

I believe this is a duplicate of #2102

**Closed by nzakas** 2015-03-23 16:21 UTC
