### ISSUE TITLE
support disabling specific rule fixes

### ISSUE THREAD

**Issue by mvolkmann** [eslint/eslint#7549] opened 2016-11-06 13:18 UTC
It would be great if there was a way to opt into the checking done by an ESLint rule, but opt out of the fix it provides if someone finds it undesirable. That way we could get the linting benefit and be able to use the fixes from other rules, just not undesirable ones. Maybe it could look something like this:

````
"some-rule-I-like": ["error", "nofix", {rule-config-goes-here}],
````

**Comment by not-an-aardvark** [comment] 2016-11-06 17:29
Thanks for the suggestion. This was also discussed here: https://github.com/eslint/eslint/issues/5329

Note that as a workaround, you disable the rule from the command line when autofixing:

```
eslint myFile.js --fix --rule 'some-rule-i-like: off'
```

**Comment by alberto** [comment] 2016-11-06 20:42
I proposed this in the past, but I am not so sure anymore it makes sense. I think the only reason to do it would be to disable a buggy fixer, and even then I am not sure that is the right approach.

**Comment by mvolkmann** [comment] 2016-11-06 21:43
I thought of this recently when I saw a proposal to have a fix that transforms "cond ? true: false" to "!!(cond)" or "Boolean(cond)". That's a case where there is no bug in the fix, but I may not want that fix while I would want others.

**Comment by medikoo** [comment] 2017-05-09 09:14
@mvolkmann why exactly this was closed? I have other case where I'd like to turn off fixing for some specific rule.
Specifically `capitalized-comments`, as with fix on save in editor it does undesired changes when I want to temporarily comment the code.

Maybe it'll be good to keep that request open?

**Comment by mvolkmann** [comment] 2017-05-09 12:45
I don't recall closing it. Maybe I did that accidentally. I reopened it.

**Comment by AshtonRoute** [comment] 2017-07-07 09:18
another use case is the rule `no-debugger`. It's so annoying to type:
```javascript
debugger; // eslint-disable-line no-debugger
```

Yes, I can make another config and disable that rule for development, but I want to be notified about it in development, because it's so common to remove `debugger;` the second I used it.

**Comment by isiahmeadows** [comment] 2017-07-10 08:07
Yeah, no-debugger is pretty critical for me. 

I'll note that one of the main driving reasons for this is that:

- A more limited `--fix` is very useful in development (esp. within editors), so you can maintain a certain style *without* having to constantly waste time correcting it. It's very nice having it active within an editor to just fix what's needed.
- A much more liberal `--fix` is useful as a pre-commit hook and/or similar, since it reduces the likelihood dev hacks find their way into the main code base.

So having two different fixing levels and being able to choose which one to use would pretty much rectify this.

**Comment by alberto** [comment] 2017-07-10 08:16
One way you can achieve this now is by changing the rules you don't want fixed to warnings and use `eslint --fix --quiet`, to only fix errors.

**Comment by medikoo** [comment] 2017-07-10 08:34
When I look at the use cases, I have a notion, that what we need is maybe not necessarily an ability to conditionally configure fixing per rule, but have an auto-fixing somehow addressed in those mentioned problematic rules.

The rule that's followed in eslint is that fixing must not change the code outcome in anyway. Having that there are many rules which do not come with auto-fixing while potentially for many scenarios they could.

Here we have cases, where auto fixing doesn't change the code outcome (thinking production run), but affects development flow e.g.:
- Commenting, saving (fixing), and uncommenting the code, produces broken code.
- Saving (fixing) file with `debugger` breakpoints removes the breakpoints.

I'd say that eslint should not welcome auto fix in rules which may affect development flow as described above, or alternatively should require those rules to have an option that allows to turn off autofixing within their scope.

**Comment by not-an-aardvark** [comment] 2017-07-10 08:44
> I'd say that eslint should not welcome auto fix in rules which may affect development flow as described above, or alternatively should require those rules to have an option that allows to turn off autofixing within their scope.

This was discussed in https://github.com/eslint/eslint/issues/8018. There seemed to be consensus (particularly from https://github.com/eslint/eslint/issues/8018#issuecomment-277109137) that the onus is on the editor integration to filter which autofixes to apply, because ESLint can't realistically determine whether any given fix will cause problems if the user is in the process of editing the code.

**Comment by medikoo** [comment] 2017-07-10 08:57
Thanks @not-an-aardvark, still `editor-unsafe` option doesn't sound that good to me e.g. I personally I don't see example of `quotes` problematic (even if I prematurely save the file, I may just write a quote I intended to put, escaped and then after save it'll be again fixed for me).

Now, if e.g. `quotes` and other similar rules will be marked on spot as `editor-unsafe`, which in turn will force editors to not auto-fix them, then I would see it as a problem, as I find auto fixing `quotes` in editor, really, really handy.

I suspect it'll meet the backlash from another group of unsatisfied users (fixing of one problem will introduce another set of issues). Not to mention that discovering why it works in cli but not in editor, will make a lot of headaches (devs may assume that right configuration is not picked up etc.)

**Comment by medikoo** [comment] 2017-07-10 08:59
Situation will be better if `editor-unsafe` will not come with rule as hard-coded, but be something that user may set in conf for any rule. If that's the intention, then this indeed may work :)

**Comment by not-an-aardvark** [comment] 2017-07-10 09:01
To clarify, we don't have plans to specifically mark rules as `editor-unsafe`, largely because that label would apply to many rules like `quotes` which are only unsafe in some cases depending on the user's cursor position.

I think the best solution is to disable autofixing for particular rules like `no-debugger` from your editor integration settings. `linter-eslint` for Atom has an option for this.

**Comment by medikoo** [comment] 2017-07-10 09:07
> I think the best solution is to disable autofixing for particular rules like no-debugger from your editor integration settings. linter-eslint for Atom has an option for this.

Ok, I think I found in VSCode extension request towards that -> https://github.com/Microsoft/vscode-eslint/issues/208
Sounds as good approach

**Comment by rtablada** [comment] 2017-09-13 17:54
While there is some degree of editors supporting fixing vs not fixing certain rules I do think that having 1st party support for this in ESLint is a good idea.

I would agree that determining which rules should/shouldn't autofix is subjective.

But, working on a team, it is useful to have a preference to not autofix but still have warnings (whether using autofix/lint from the CLI or an editor interface).

I'm not sure the best api for this but I would imagine somthing like an option for all rules of `{autofix: false}`.
So in the case of `no-console` statements for instance (which could be autofixed using ASTs but do not currently have an autofix because of the impact to development):

```
{
  'no-console: ['error', { allow: ['warn'], autofix: false }]
}```

Or in the case of `no-debugger` which seems to be the source of alot of discussion over this:

```
{
  'no-debugger: ['error', { autofix: false }]
}```

I think it is sane to have `autofix` default to `true` in all cases to keep things consistent.

Along with this I think it may be helpful to have an `--autofix-all` which overrides the `autofix` configs for your local configuration. This way you can have a more in-depth autofix for pre commit hooks.

**Comment by not-an-aardvark** [comment] 2017-11-03 20:48
Thanks for your interest in improving ESLint. Unfortunately, it looks like this issue didn't get consensus from the team, so I'm closing it. We define [consensus](http://eslint.org/docs/maintainer-guide/issues.html#consensus) as having three :+1:s from team members, as well as a team member willing to champion the proposal. This is a high bar by design -- we can't realistically accept and maintain every feature request in the long term, so we only accept feature requests which are useful enough that there is consensus among the team that they're worth adding.

**Closed by not-an-aardvark** 2017-11-03 20:48 UTC
Labels: core, enhancement, evaluating

**Comment by platinumazure** [comment] 2017-11-03 22:46
I think this can be done by creating a custom rule which uses (e.g.) [eslint-rule-composer](https://github.com/not-an-aardvark/eslint-rule-composer) to modify lint messages such that autofix is or is not run under certain circumstances (or never).

**Comment by revelt** [comment] 2018-04-20 07:06
Sorry to dug out this issue but I believe it is a very-important-one. Any rules in unit tests such as AVA's `ava/no-only-test` or `ava/no-skip-test` get ~fixed~ deleted upon first save:

![ava_eslint](https://user-images.githubusercontent.com/8344688/39035070-9e288e48-4470-11e8-804f-46c9c2ee41b6.gif)

and maintainers indecision on this issue led the problem being offloaded from potentially `eslintrc` to the shoulders of consuming plugins, for example, `linter-eslint`:

![screen shot 2018-04-20 at 07 21 09](https://user-images.githubusercontent.com/8344688/39034727-5adbbcb0-446f-11e8-83e0-bdca7d3a4bd9.png)

However, the ecosystem is expanding, and now Atom+ESLint+Prettier configuration comes into game and while Prettier does reads `eslintrc`'s, its Atom plugins don't have a field to instruct ESLint to skip certain rules from fixing.

Even if `prettier-atom` does implement a new field in Preferences GUI, it will not be portable — every open source contributor will have to set up their machines separately... **Just have a think for a second about that.** If only I could set up fix skipping on `eslintrc`, problem would be solved.

Looking at the higher picture, compare two options:

1. Adding some sort of "nofix" onto ESLint config which every participant of the ecosystem can already consume and understand using `eslitrc`'s. DRY. Single point of reference.
OR
2. Making every participant in the ecosystem design and implement their own barriers to limit what ESLint fixes... A setting in `linter-eslint` GUI, a setting in `prettier-atom` GUI, and so on...

Debug statements and in general anything troubleshooting- or unit-test- related would make use of "nofix" setting, since you can't turn off the rule because you don't want it spilling into production, yet you can't manually turn off and on just to be able to save the file with code intact...

**Comment by not-an-aardvark** [comment] 2018-04-20 07:40
I'm unconvinced that the options you've presented are the only ways to address this problem. I think the best solution in this case would be for `eslint-plugin-ava` to remove the autofixers for `ava/no-only-test` and `ava/no-skip-test`. In general, we [recommend against](https://eslint.org/docs/developer-guide/working-with-rules#applying-fixes) having autofixes that change the runtime behavior of code.

Speaking more generally, I don't think the set of fixes that are useful in editors is necessarily the same as the set of fixes that are useful from the command line. By using a `nofix` option as you're suggesting, users would be improving their editor experience while hurting their command-line experience, with no way to distinguish between the two in a config file. (If a fix is neither useful on the command line nor in an editor, then it would be better to simply remove the autofixing behavior from the rule rather than making users to specify something like `nofix`.)
