### ISSUE TITLE
Null character mistaken for octal literal.

### ISSUE THREAD

**Issue by RebeccaStevens** [eslint/eslint#9941] opened 2018-02-05 00:03 UTC
I have this line in my webpack.dev.js file:

```js
console.log('Building for \033[30m\033[42m DEVELOPMENT \033[0m Environments');
```

I get the error `[eslint] Parsing error: Octal literal in strict mode` on the first `\` character.

I'm pretty sure that `\0` is not an octal literal here, I believe it is the null character (though I'm not 100% sure - I got these string from https://stackoverflow.com/questions/7505623/colors-in-javascript-console#answer-35715575).

Images:
![error](https://user-images.githubusercontent.com/7224206/35783904-bd5d6314-0a74-11e8-9538-2cccc6537b41.png)
![output](https://user-images.githubusercontent.com/7224206/35783905-c0561c96-0a74-11e8-9faf-13a7dbf01333.png)

**Comment by mysticatea** [comment] 2018-02-05 01:23
It's `LegacyOctalEscapeSequence`, Chrome and Firefox disallow at least.

> ![image](https://user-images.githubusercontent.com/1937871/35784759-6fcd8946-0a5e-11e8-9bd9-5e47945c0a87.png)
> Firefox

-

> ![image](https://user-images.githubusercontent.com/1937871/35784768-8645b248-0a5e-11e8-8f86-46bbcb3baee3.png)
> Chrome

**Comment by not-an-aardvark** [comment] 2018-03-05 18:02
Closing because this is working as intended.

**Closed by not-an-aardvark** 2018-03-05 18:02 UTC
Labels: question
