### ISSUE TITLE
Feature request : update the `indent` rule to be able to align chained functions

### ISSUE THREAD

**Issue by AlexandreBonneau** [eslint/eslint#9806] opened 2018-01-04 22:53 UTC
**Tell us about your environment**

* **ESLint Version:** `v4.14.0`
* **Node Version:** `v9.2.1`
* **npm Version:** `v5.5.1`

**What parser (default, Babel-ESLint, etc.) are you using?** babel-eslint `v7.2.3`

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
module.exports = {
    root         : true,
    parser       : 'babel-eslint',
    parserOptions: {
        sourceType: 'module',
        ecmaVersion: 2017,
    },
    env          : {
        es6    : true,
        browser: true,
    },
    globals      : {
        module : true,
        require: true,
    },
    // https://github.com/feross/standard/blob/master/RULES.md#javascript-standard-style
    // extends      : 'standard',
    // required to lint *.vue files
    plugins      : [
        'html',
    ],
    // Custom rules
    rules        : {
        // Basic rules
        indent: "off",
        "indent-legacy"                : [
            "error",
            4,
            {
                "SwitchCase"         : 1,
                "VariableDeclarator" : {
                    "var"  : 1,
                    "let"  : 1,
                    "const": 1,
                },
                "outerIIFEBody"      : 0,
                "MemberExpression"   : 1,
                "FunctionDeclaration": {
                    "parameters": "first",
                },
                "FunctionExpression" : {
                    "parameters": "first",
                },
                "CallExpression"     : {
                    "arguments": "first",
                },
            },
        ],
        "keyword-spacing"              : [
            "error",
            {
                "before": true,
                "after" : true,
            },
        ],
        "brace-style"                  : [
            "error",
            "1tbs",
            {
                "allowSingleLine": true,
            },
        ],
        // Do not use "space-infix-ops": "error", for ternary operators
        "arrow-spacing"                : [
            "error",
            {
                "before": true,
                "after" : true,
            },
        ],
        "arrow-parens"                 : [
            "error",
            "as-needed",
        ],
        "arrow-body-style"             : [
            "error",
            "as-needed",
            {
                requireReturnForObjectLiteral: false,
            },
        ],
        "no-confusing-arrow"           : [
            "error",
            {
                "allowParens": true,
            },
        ],
        "space-before-function-paren"  : [
            "error",
            {
                "anonymous" : "never",
                "named"     : "never",
                "asyncArrow": "always",
            },
        ],
        "space-before-blocks"          : "error",
        "linebreak-style"              : [
            "error",
            "unix",
        ],
        "newline-per-chained-call"     : [
            "error",
            {
                "ignoreChainWithDepth": 2,
            }
        ],
        "object-curly-spacing"         : [
            "error",
            "always",
        ],
        "array-bracket-spacing"        : [
            "error",
            "never",
        ],
        "no-whitespace-before-property": "error",
        "padded-blocks"                : [
            "error",
            "never",
        ],
        "space-in-parens"              : [
            "error",
            "never",
        ],
        "camelcase"                    : [
            "error",
            {
                properties: "always",
            }
        ],
        "new-cap"                      : "error",
        "no-underscore-dangle"         : 0,
        "quotes"                       : [
            "error",
            "single", // Backticks are allowed due to substitution
            {
                "allowTemplateLiterals": true,
                "avoidEscape"          : true,
            },
        ],
        "semi"                         : [
            "error",
            "always",
        ],
        "semi-spacing"                 : "error",
        "curly"                        : [
            "error",
            "multi-line",
            "consistent",
        ],
        "prefer-const"                 : "error",
        "no-const-assign"              : "error",
        "no-var"                       : "error",
        "no-new-object"                : "error",
        "object-shorthand"             : "error",
        "quote-props"                  : [
            "error",
            "as-needed",
        ],
        "no-array-constructor"         : "error",
        "func-style"                   : [
            "error",
            "declaration",
            {
                "allowArrowFunctions": true,
            },
        ],
        "no-loop-func"                 : "error",
        "no-new-func"                  : "error",
        "prefer-spread"                : "error",
        "prefer-arrow-callback"        : "error",
        "no-useless-constructor"       : "error",
        "no-dupe-class-members"        : "error",
        "no-duplicate-imports"         : [
            "error",
            {
                "includeExports": true,
            },
        ],
        "no-func-assign"               : "error",
        "no-class-assign"              : "error",
        "no-iterator"                  : "error",
        "dot-notation"                 : "error",
        "no-undef"                     : "error",
        "one-var"                      : [
            "error",
            "never",
        ],
        "radix"                        : [
            "error",
            "always",
        ],

        // Other misc rules
        "no-unneeded-ternary"   : "error",
        "no-nested-ternary"     : "error",
        "no-unreachable"        : "error",
        "use-isnan"             : "error",
        "no-unsafe-negation"    : "error",
        "no-extra-semi"         : "error",
        "no-sparse-arrays"      : "error",
        "no-eq-null"            : "error",
        "eqeqeq"                : "error",
        "no-eval"               : "error",
        "strict"                : [
            "error",
            "safe",
        ],
        "no-useless-escape"     : "error",
        "prefer-rest-params"    : "error",
        "generator-star-spacing": [
            "error",
            {
                "before": false,
                "after" : true,
            }
        ],
        "no-case-declarations"  : "error",
        "spaced-comment"        : [
            "error",
            "always",
            {
                "line" : {
                    "markers"   : ["/", "TODO", "FIXME", "DEBUG", "XXX"],
                    "exceptions": ["-", "+", "TODO", "FIXME", "DEBUG", "XXX"],
                },
                "block": {
                    "markers"   : ["!"],
                    "exceptions": ["*"],
                    "balanced"  : true,
                }
            }
        ],
        "eol-last"              : [
            "error",
            "always",
        ],
        "comma-style"           : [
            "error",
            "last",
        ],
        "comma-dangle"          : [
            "error",
            "always-multiline",
        ],

        // allow debugger during development
        'no-debugger': (process.env.NODE_ENV === 'production')?2:0,
    }
};
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
// This is what I need to write with my current eslint config:
func1(id, type) {
    return this.foo(id)
        .map(op => `${op.type}: ${op.value}`)
        .join(', ');
},

// This is what I want to be able to write without eslint complaining:
func2(id, type) {
    return this.foo(id)
               .map(op => `${op.type}: ${op.value}`)
               .join(', ');
},
```

I cannot manage to find in the [indent documentation page](https://eslint.org/docs/rules/indent) how to align the chained function calls.
For this to works, it would need the user to only use spaces (since you likely do not want to mix tabs and spaces).

**Comment by not-an-aardvark** [comment] 2018-01-04 22:54
Closing as a duplicate of https://github.com/eslint/eslint/issues/9383

**Closed by not-an-aardvark** 2018-01-04 22:54 UTC
Labels: triage
