### ISSUE TITLE
compile error on new machine

### ISSUE THREAD

**Issue by James2516** [eslint/eslint#8794] opened 2017-06-24 15:33 UTC
**Tell us about your environment**

* **ESLint Version:** 4.0.0
* **Node Version:** v6.11.0
* **npm Version:** 3.10.10

**What parser (default, Babel-ESLint, etc.) are you using?** babel-eslint

**Please show your full configuration:**

```
  "dependencies": {
    "bootstrap": "^3.3.7",
    "prop-types": "^15.5.10",
    "react": "^15.5.4",
    "react-bootstrap": "^0.31.0",
    "react-dom": "^15.5.4"
  },
  "devDependencies": {
    "babel-eslint": "^7.2.3",
    "babel-plugin-transform-class-properties": "^6.24.1",
    "eslint": "^4.0.0",
    "eslint-config-airbnb": "^15.0.1",
    "eslint-plugin-import": "^2.2.0",
    "eslint-plugin-jsx-a11y": "^5.0.1",
    "eslint-plugin-react": "^7.1.0",
    "gh-pages": "^1.0.0",
    "react-scripts": "^1.0.7"
  },
```

**What did you do? Please include the actual source code causing the issue.**

index.js:
```
import React from 'react';
import ReactDOM from 'react-dom';
import App from './App';
import registerServiceWorker from './registerServiceWorker';
import '../node_modules/bootstrap/dist/css/bootstrap.min.css';
import './index.css';

ReactDOM.render(<App />, document.getElementById('root'));
registerServiceWorker();
```
Run `npm start`

**What did you expect to happen?**
Web app works fine on another machine, am i missing some dependency?

**What actually happened? Please include the actual, raw output from ESLint.**
![](http://i.imgur.com/WM4cBSw.png)

**Comment by ilyavolodin** [comment] 2017-06-24 15:59
This is the same error that we are tracking here: https://github.com/eslint/eslint/issues/8791
It looks like you are using baseConfig with extends. I'm assuming you are using create-react-app?

**Comment by James2516** [comment] 2017-06-24 16:01
Yes!

**Comment by ilyavolodin** [comment] 2017-06-24 17:06
We are working on fixing this issue. I'm going to close this as a duplicate of #8791

**Closed by ilyavolodin** 2017-06-24 17:06 UTC
Labels: triage
