### ISSUE TITLE
"indent" rule settings.

### ISSUE THREAD

**Issue by the-spyke** [eslint/eslint#7635] opened 2016-11-22 09:09 UTC
**Tell us about your environment**

Ubuntu 16.04.1 LTS x64

* **ESLint Version:** 3.10.2
* **Node Version:** 6.9.1
* **npm Version:** 3.10.9

**What parser (default, Babel-ESLint, etc.) are you using?**

default

**Please show your full configuration:**

```
{
    "env": {
        "browser": true,
        "commonjs": true,
        "es6": true
    },
    "extends": [
        "eslint:recommended"
    ],
    "installedESLint": true,
    "parserOptions": {
        "ecmaVersion": 6
    },
    "root": true,
    "rules": {
        "arrow-spacing": "error",
        "block-scoped-var": "error",
        "block-spacing": "error",
        "brace-style": [
            "error",
            "1tbs",
            {
                "allowSingleLine": true
            }
        ],
        "comma-spacing": "error",
        "comma-style": "error",
        "consistent-this": [
            "error",
            "me"
        ],
        "curly": "error",
        "indent": [
            "error",
            4,
            {
                "SwitchCase": 1,
                "MemberExpression": 1,
                "CallExpression": { "arguments": 1 }
            }
        ],
        "key-spacing": "error",
        "keyword-spacing": "error",
        "linebreak-style": "error",
        "lines-around-directive": "error",
        "no-caller": "error",
        "no-empty-function": "error",
        "no-global-assign": "error",
        "no-trailing-spaces": "error",
        "no-whitespace-before-property": "error",
        "no-with": "error",
        "operator-linebreak": "error",
        "quotes": "error",
        "radix": "error",
        "semi": "error",
        "space-before-blocks": "error",
        "space-before-function-paren": [
            "error",
            "never"
        ],
        "space-in-parens": "error",
        "space-infix-ops": "error",
        "space-unary-ops": "error",
        "strict": "error",
        "valid-jsdoc": "error",
        "vars-on-top": "error",
        "wrap-iife": [
            "error",
            "inside"
        ]
    }
}
```

**What did you do? Please include the actual source code causing the issue.**

**What did you expect to happen?**

![eslint-indentation-issues](https://cloud.githubusercontent.com/assets/3014095/20517403/f8a2555c-b0ab-11e6-9514-18b144601887.png)

These two errors are from the "indent" rule.
I've expected "render" to be without indentation errors and "render2" to have some.
In "render3" there are some inconsistency in braces too.

**What actually happened? Please include the actual, raw output from ESLint.**

Something seems wrong with indentation validation.

**Comment by not-an-aardvark** [comment] 2016-11-22 09:16
Hi, thanks for the issue. However, I think this is intended behavior. See https://github.com/eslint/eslint/issues/4081, https://github.com/eslint/eslint/issues/6890, and https://github.com/eslint/eslint/issues/6990 for more information (all of them discuss this behavior).

**Comment by the-spyke** [comment] 2016-11-22 11:02
Thanks. #4081 is a little bit different. But #6890 and #6990 look similar. I can agree, that "render3" has intended behavior, but "render2" without errors is totally wrong. As for "render", this is the way, that JSFormat for Sublime Text formats the code (an some other formatters too).

**Comment by not-an-aardvark** [comment] 2016-11-29 06:38
I'm going to close this as a duplicate of the issues that I mentioned above, but feel free to continue the discussion on those issues.

**Closed by not-an-aardvark** 2016-11-29 06:38 UTC
Labels: question
