### ISSUE TITLE
Eslint tells me that I have fixable issues, refuses to fix them, ignores `--fix`

### ISSUE THREAD

**Issue by EdwardDrapkin** [eslint/eslint#10004] opened 2018-02-23 16:24 UTC
Hey there,

I'm invoking eslint like so `node_modules/.bin/eslint --fix src`.

Here's the output:

```
*snip*
✖ 27 problems (22 errors, 5 warnings)
  8 errors, 0 warnings potentially fixable with the `--fix` option.
```

And my .eslintrc:

```
{
    "extends": [
        "plugin:flowtype/recommended",
        "plugin:react/recommended",
        "plugin:jest/recommended"
    ],
    "parser": "babel-eslint",
    "plugins": [
        "flowtype",
        "jest",
        "react"
    ],
    "rules": {
        "react/jsx-no-bind": "warn",
        "react/jsx-boolean-value": [
            "error",
            "never"
        ],
        "react/jsx-closing-bracket-location": "error",
        "react/jsx-closing-tag-location": "error",
        "react/jsx-equals-spacing": [
            "error",
            "never"
        ],
        "react/jsx-first-prop-new-line": [
            "error",
            "multiline-multiprop"
        ],
        "react/jsx-tag-spacing": [
            "error",
            {
                "beforeSelfClosing": "never",
                "beforeClosing": "never"
            }
        ],
        "react/jsx-pascal-case": "error",

        "strict": "off",
        "class-methods-use-this": [
            "error",
            {
                "exceptMethods": [
                    "render",
                    "getInitialState",
                    "getDef --aultProps",
                    "componentWillMount",
                    "componentDidMount",
                    "componentWillReceiveProps",
                    "shouldComponentUpdate",
                    "componentWillUpdate",
                    "componentDidUpdate",
                    "componentWillUnmount"
                ]
            }
        ]
    },
    "parserOptions": {
        "sourceType": "module",
        "ecmaFeatures": {
            "jsx": true
        }
    },
    "settings": {
        "flowtype": {
            "onlyFilesWithFlowAnnotation": true
        },
        "import/resolver": {
            "node": {
                "moduleDirectory": [
                    "node_modules",
                    "src/"
                ]
            }
        }
    }
}
```

**Comment by not-an-aardvark** [comment] 2018-02-23 17:28
It's hard to tell what's going on without seeing your source code, but note that the message says "potentially fixable". Not all fixes are guaranteed to be applied on any given run.

**Comment by Slapbox** [comment] 2018-02-23 20:01
@not-an-aardvark I'm having the same issue. I understand this isn't necessarily a bug, but how can we determine which errors/if the errors should actually be fixed automatically?

In my case I have thousands a of errors and hundreds of "potentially fixable" ones which are not fixed. Thousands of errors were automatically fixed though. Thank god for you and this tool!

**Comment by not-an-aardvark** [comment] 2018-02-23 20:23
Generally, if you run `--fix`, ESLint will try to fix as many problems as it can (and it will do multiple passes over the source code). If it reports any problems afterwards, those problems were unable to get fixed automatically.

**Comment by Slapbox** [comment] 2018-02-23 20:25
Thanks for that. Is there any (relatively easy) way of determining which errors were potentially fixable and why they weren't fixed? I know there's a `--debug` flag, but that's a bit verbose.

**Comment by not-an-aardvark** [comment] 2018-02-23 20:29
No, unfortunately not. That said, I think an error is considered "potentially fixable" if it is reported by a rule which supports autofixing in any case, even if the rule does not support autofixing in the particular case that it is reporting (or with the particular set of options that you're using). So it's common to see many "potentially fixable" errors which in fact are not fixable.

**Comment by not-an-aardvark** [comment] 2018-02-23 20:35
You could use the `--format json` flag to get a JSON representation of the list of problems, and with that you could check which problems have a `fix` property. (However, this would be even more verbose than `--debug`, so I would recommend parsing it and querying it from the Node REPL or something.)

**Comment by Slapbox** [comment] 2018-02-23 20:49
Great info! I'll play with it again soon and see what I can get. Thanks very much!

**Comment by not-an-aardvark** [comment] 2018-03-05 17:38
Closing because this is working as intended.

**Closed by not-an-aardvark** 2018-03-05 17:38 UTC
Labels: works as intended
