### ISSUE TITLE
Linting doesn't work on Windows when node_modules is present in folder

### ISSUE THREAD

**Issue by filipesilva** [eslint/eslint#5780] opened 2016-04-04 11:54 UTC
**What version of ESLint are you using?**
v2.6.0
**What parser (default, Babel-ESLint, etc.) are you using?**
default
**Please show your full configuration:**
```
{
    "rules": {
        "semi": [
            2,
            "always"
        ]
    }
}
```
**What did you do? Please include the actual source code causing the issue.**
```
filipe.silva@DESKTOP-7ND6T3R MINGW64 /E/sandbox/eslint-test
$ node -v
v4.2.1

filipe.silva@DESKTOP-7ND6T3R MINGW64 /E/sandbox/eslint-test
$ npm -v
2.14.7

filipe.silva@DESKTOP-7ND6T3R MINGW64 /E/sandbox/eslint-test
$ eslint -v
v2.6.0

filipe.silva@DESKTOP-7ND6T3R MINGW64 /E/sandbox/eslint-test
$ ls -la
total 10
drwxr-xr-x 1 filipe.silva filipe.silva  0 Apr  4 12:50 ./
drwxr-xr-x 1 filipe.silva filipe.silva  0 Apr  4 12:36 ../
-rw-r--r-- 1 filipe.silva filipe.silva 89 Apr  4 12:37 .eslintrc.json
-rw-r--r-- 1 filipe.silva filipe.silva 11 Apr  4 12:38 test.js

filipe.silva@DESKTOP-7ND6T3R MINGW64 /E/sandbox/eslint-test
$ cat .eslintrc.json
{
    "rules": {
        "semi": [
            2,
            "always"
        ]
    }
}

filipe.silva@DESKTOP-7ND6T3R MINGW64 /E/sandbox/eslint-test
$ cat test.js
var a = 1

filipe.silva@DESKTOP-7ND6T3R MINGW64 /E/sandbox/eslint-test
$ eslint ./**/*.js

E:\sandbox\eslint-test\test.js
  1:10  error  Missing semicolon  semi

✖ 1 problem (1 error, 0 warnings)


filipe.silva@DESKTOP-7ND6T3R MINGW64 /E/sandbox/eslint-test
$ mkdir node_modules

filipe.silva@DESKTOP-7ND6T3R MINGW64 /E/sandbox/eslint-test
$ cp test.js node_modules/test.js

filipe.silva@DESKTOP-7ND6T3R MINGW64 /E/sandbox/eslint-test
$ eslint ./**/*.js

filipe.silva@DESKTOP-7ND6T3R MINGW64 /E/sandbox/eslint-test
$
```
**What did you expect to happen?**
I expected that running `eslint ./**/*.js` the second time would show the same result as the first time.
**What actually happened? Please include the actual, raw output from ESLint.**
Nothing was shown when running the command a second time.

This was run on a win10 machine using githbash.

**Comment by ilyavolodin** [comment] 2016-04-04 12:50
`node_modules` and `bower_components` are ignored by default by ESLint. If you would like to lint those, you need to un-ignore them in `.eslintignore` files. Take a look at this issue https://github.com/eslint/eslint/issues/5410 for more information.

**Comment by filipesilva** [comment] 2016-04-04 12:52
I understand that happens, but in my case I still had a file with lint errors *outside* the `node_modules` directory, I simply made a copy and put it inside the dir. Linting should still have shown the errors for the original file.

**Comment by ilyavolodin** [comment] 2016-04-04 12:56
Ah. I see. Sorry, I didn't notice `cp`. I'm not 100% sure if `./**/*.js` should include `./test.js`. Theoretically `./**/` means any directory in the current folder, and as `./tests.js` is not in the directory, it might be bypassed by globbing. @alberto @IanVS is this behaving correctly?

**Comment by filipesilva** [comment] 2016-04-04 12:57
I suppose it should, because initially the same command caught errors in it:

```
filipe.silva@DESKTOP-7ND6T3R MINGW64 /E/sandbox/eslint-test
$ cat test.js
var a = 1

filipe.silva@DESKTOP-7ND6T3R MINGW64 /E/sandbox/eslint-test
$ eslint ./**/*.js

E:\sandbox\eslint-test\test.js
  1:10  error  Missing semicolon  semi

✖ 1 problem (1 error, 0 warnings)
```

**Comment by alberto** [comment] 2016-04-04 15:05
Thanks @filipesilva for the detailed report!

I was able to reproduce this on a mac too.

It's not directly related to `node_modules` I think:
```
mv node_modules foo

$ eslint ./**/*.js

/Users/alberto/projects/oss/sandbox-5780/foo/test.js
  1:10  error  Missing semicolon  semi

✖ 1 problem (1 error, 0 warnings)
```
Note it's erroring for `foo/test.js` but not for `./test.js`

**Comment by alberto** [comment] 2016-04-04 15:10
Also note `eslint .` produces the expected output (also with a `node_modules` folder):

```
$ eslint .

/Users/alberto/projects/oss/sandbox-5780/foo/test.js
  1:10  error  Missing semicolon  semi

/Users/alberto/projects/oss/sandbox-5780/test.js
  1:10  error  Missing semicolon  semi

✖ 2 problems (2 errors, 0 warnings)
```

**Comment by platinumazure** [comment] 2016-04-04 15:15
I think the correct glob syntax is `**/*.js` (I believe we replace `.` with `**/*.js` somewhere in CLIEngine).

**Comment by alberto** [comment] 2016-04-04 15:22
@platinumazure I tried that and it doesn't work either.

**Comment by filipesilva** [comment] 2016-04-04 15:23
I can confirm that `estlint .` gives the expected result. This pattern doesn't allow me to filter for only `.js` files though.

I tried with `eslint **/*.js` and did not get anything.

**Comment by platinumazure** [comment] 2016-04-04 15:24
@alberto @filipesilva My mistake, then. It seems pretty likely that we have a bug.

**Comment by alberto** [comment] 2016-04-04 15:24
@filipesilva eslint filters for `.js` file extension by default.

**Comment by filipesilva** [comment] 2016-04-04 15:30
Ah that is great to hear! I tried using `eslint .` with a well configured `.eslintignore` on the main project I had issues in, and that worked well.

Thank you!

**Comment by ilyavolodin** [comment] 2016-04-04 15:39
Are we handling patterns starting with `.` correctly now? I think there used to be a bug in `--init` where anything starting with dot would be ignored. Since we merged logic for glob unwrapping between `init` and CLI, maybe we have that bug in CLI now?

**Comment by IanVS** [comment] 2016-04-04 15:44
@ilyavolodin the bug in `--init` should be fixed.  Are you referring to https://github.com/eslint/eslint/issues/4828#issuecomment-203714300 perhaps?

**Comment by IanVS** [comment] 2016-04-04 15:46
I think I see where you're going with this, and it's totally possible.  Maybe [this line](https://github.com/eslint/eslint/blob/master/lib/ignored-paths.js#L118) needs to be changed to:

```js
addPattern(this.ig.default, [".*", "!../", "!./"]);
```

**Comment by ilyavolodin** [comment] 2016-04-04 15:50
@IanVS That sounds like a possible fix. @alberto Since you were able to reproduce this issue, could you try and see if the fix that @IanVS suggested corrects this issue?

**Comment by alberto** [comment] 2016-04-05 06:47
@ilyavolodin @IanVS It doesn't

**Comment by alberto** [comment] 2016-04-05 16:53
Ok, after digging into this, I don't think it is a bug.

If you use a glob in the command line, it turns out [the shell with expand the globs](http://wiki.bash-hackers.org/syntax/expansion/globs) (at least on UNIX).

So `eslint ./**/*.js` generates this `process.argv`:
```
[ '/Users/alberto/.nvm/versions/node/v5.9.1/bin/node',
  '/Users/alberto/.nvm/versions/node/v5.9.1/bin/eslint',
  './foo/test.js' ]
```
Note this differs from node's `glob` expansion, in that it will only look match js files in one-level-deep directories (it won't match `./test.js` nor `foo/bar/test.js`).

The proper way to pass an unexpanded glob in the commandline is by quoting it:
```
$ eslint '**/*.js'

/Users/alberto/projects/oss/sandbox/issue5780/foo/test.js
  1:10  error  Missing semicolon  semi

/Users/alberto/projects/oss/sandbox/issue5780/test.js
  1:10  error  Missing semicolon  semi

✖ 2 problems (2 errors, 0 warnings)```

**Comment by platinumazure** [comment] 2016-04-05 16:57
I assume the reason you're using single quotes is to ensure the shell won't
interpret the quotes, so that a glob strong with quotes is passed to node
glob?

**Comment by alberto** [comment] 2016-04-05 17:06
Yes, by quoting it, the argument is passed as a literal.

```
$ eslint '**/*.js'
[ '/Users/alberto/.nvm/versions/node/v5.9.1/bin/node',
  '/Users/alberto/.nvm/versions/node/v5.9.1/bin/eslint',
  '**/*.js' ]
```

**Closed** 2016-04-05 20:24 UTC
Labels: bug, cli, evaluating

**Comment by filipesilva** [comment] 2016-04-05 23:20
Would just like to say thanks for all the help all. You found a solution for my issue, got to the bottom of it and even added docs. Very cool. Cheers!
