### ISSUE TITLE
Bug: fixable error on line causes eslint-disable-next-line to be unused

### ISSUE THREAD

**Issue by kkmuffme** [eslint/eslint#16673] opened 2022-12-16 15:36 UTC
### Environment

Playground

### What parser are you using?

Default (Espree)

### What did you do?

<details>
<summary>Configuration</summary>

```
"reportUnusedDisableDirectives": true,
"rules": {
"camelcase": ["error",{"properties":"always","ignoreDestructuring":false,"ignoreImports":false,"ignoreGlobals":false}],
"quote-props": "error"
}
```
</details>

```js
const foo = {
	// eslint-disable-next-line camelcase
	'foo_bar': ''
};
```

### What did you expect to happen?

quote-props to be auto-fixed and no other errors

### What actually happened?

quote-props was auto-fixed, but eslint-disable-next-line comment was removed, because this error didn't exist before the auto-fix.

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by mdjermanovic** [comment] 2022-12-16 18:04
Hi @kkmuffme, thanks for the issue!

Just to be sure that we understand the problem, did you mean `"quote-props": ["error", "as-needed"]`?

The problem is that eslint removes a disable directive for a problem that doesn't exist in the original code, but is anticipated to appear after other problems are fixed?

**Comment by mdjermanovic** [comment] 2022-12-19 18:48
Thanks for clarifying! I can reproduce this behavior with `"quote-props": ["error", "as-needed"]`. We could try to address this by updating the autofix algorithm to fix directives separately from other problems, in the last pass, so that they are only removed when they're unused after all other fixable problems have been fixed.

However, I'm not sure if this behavior is always desirable, because the directive is really unused in the original code and we can't know if it was added by mistake, and should therefore be removed because it could suppress lint problems that it wasn't supposed to suppress, or intentionally anticipating lint problems that are yet to appear which looks like an unusual workflow to me. Curious what other team members think about this.

**Comment by Rec0iL99** [comment] 2023-02-14 07:02
Waiting for feedback. Don't close.

**Comment by Rec0iL99** [comment] 2023-04-24 21:04
@eslint/eslint-team folks, this issue needs feedback. Thanks

**Comment by fasttime** [comment] 2023-04-25 09:15
I don't think I understand the implications of this issue. If the quotes around `'foo_bar'` are expected to be removed, then why are they there in the first place? An if they are not expected to be removed, then why is there a disable directive on top? Is this about formatting autogenerated code with ESLint?

**Comment by mdjermanovic** [comment] 2023-04-25 14:15
In my opinion, as explained in my previous comment, the current behavior is correct because the directive is unused in the original code. Since this issue has been open for a long time and no one from the team has expressed a different opinion, I think we can close it.

**Closed by mdjermanovic** 2023-04-25 14:15 UTC
Labels: works as intended
