### ISSUE TITLE
About `Missing semicolon`.

### ISSUE THREAD

**Issue by poppinlp** [eslint/eslint#9399] opened 2017-10-08 09:00 UTC
**Tell us about your environment**

* **ESLint Version:** 4.8.0
* **Node Version:** 8.6.0
* **npm Version:** 5.5.0

**What parser (default, Babel-ESLint, etc.) are you using?**
esprima

**Please show your full configuration:**

I use [eslint-config-handsome](https://github.com/poppinlp/eslint-config-handsome/blob/master/.eslintrc.yaml)

<details>
<summary>Configuration</summary>

```yml
extends: handsome
```

</details>

**What did you do? Please include the actual source code causing the issue.**

I make a [repo](https://github.com/poppinlp/vscode-eslint-issue-demo) to show this issue. You could clone it and install dependencies. Then run `npm test` you'll see this:

![screenshot from 2017-10-08 16-56-25](https://user-images.githubusercontent.com/1970625/31315363-e1275914-ac49-11e7-8430-af9ed114e85d.png)

But there is a semi for sure. And i have tried eslint autofix which will add one more semi there and this error is still there.

Here's what in code.js:

```js
export default async () => {
	const api = () => new Promise(resolve => resolve());
	const res = await api();

	return res;
};
```

**What did you expect to happen?**

No error there.

**What actually happened? Please include the actual, raw output from ESLint.**

See screenshot above.

Need some help. Thanks.

**Comment by Aladdin-ADD** [comment] 2017-10-08 13:27
thanks for reporting, I can repro this!

**Comment by poppinlp** [comment] 2017-10-09 02:40
Thanks. I have tried espree which works well. 👍 
So...what should i deal with this issue? Goes to esprima repo?

**Comment by platinumazure** [comment] 2017-10-09 03:03
This is a tough one. esprima probably won't fix an issue just because "ESLint doesn't work"; on the other hand, if we can figure out *why* esprima isn't working correctly here and we can prove that the issue is with their parse output, then we could create an issue that they would accept and fix.

One possible way to do this is to parse the code example with both espree and esprima and maybe do a diff of their `JSON.stringify`'d outputs. Maybe somewhere in there, we might see that their output data (such as node or token locations) is different, possibly wrong.

I'm going to close this issue because there's no change for ESLint, but please feel free to keep using this space to document any findings. I for one will be interested to see what you find!

**Closed by platinumazure** 2017-10-09 03:03 UTC
Labels: triage

**Comment by poppinlp** [comment] 2017-10-09 11:46
@platinumazure  HI

I add a file named [parse.js](https://github.com/poppinlp/vscode-eslint-issue-demo/blob/master/parse.js) in that [repo](https://github.com/poppinlp/vscode-eslint-issue-demo) which could reproduce the issue. That file is for check the AST output by esprima and espree. And i got this:

![image](https://user-images.githubusercontent.com/1970625/31336590-1b6fb9ae-acbd-11e7-8a94-e149d8afef31.png)

Seems there's an extra empty node at the end of esprima's output AST. So maybe that's the reason esprima always think there lack of a semi.
