### ISSUE TITLE
Feature Request: "Enforce/Override Global Rule Severity" CLI Option

### ISSUE THREAD

**Issue by ashrafhadden** [eslint/eslint#10346] opened 2018-05-12 23:51 UTC
**The version of ESLint you are using.**
4.19.1

**The problem you want to solve.**
Most ESLint Shared Configs (ex. [AirBnB](https://github.com/airbnb/javascript/tree/master/packages/eslint-config-airbnb), [StandardJS](https://github.com/standard/eslint-config-standard)) use "error" as their default rule severity. I use ESLint through VSCode and prefer to have all of my ESLint problems show up as warnings since they are almost all style-related. This allows me to keep all of my _actual_ error problems (ex. syntax errors) separate from my style problems. Currently I have to find and replace all "error" with "warn" in my eslint-config's or maintain massive .eslintrc files to override all the "error"'s.

**Your take on the correct solution to problem.**
Add a "Global Severity" option in the ESLint CLI that overrides all other rule severities.

**Comment by not-an-aardvark** [comment] 2018-05-13 00:14
Hi, thanks for the proposal. My gut reaction to this is that I'm not sure ESLint is the right place to make this change.

If I'm understanding correctly, you want VSCode to display ESLint's reports as warnings to provide a visual distinction with reports from other tools. The current state is that ESLint has two measures of severity (errors and warnings), and VSCode also has two measures of severity (errors and warnings), so VSCode is displaying problems form ESLint with "error" severity as VSCode "errors". But there's no reason VSCode needs to have this one-to-one mapping; in theory, it could display all problems from ESLint as VSCode "warnings", regardless of what ESLint says a problem's severity is.

Conceptually, since ESLint is just providing data and VSCode is deciding how to display it, I think it would make more sense to add an option to VSCode (along the lines of "set a maximum severity for all problems from this tool") rather than adding an option to ESLint for the purpose of changing how the problem is displayed by VSCode.

**Comment by ilyavolodin** [comment] 2018-05-13 02:44
Sorry, but I think this is really a very rare edge case. This also can be accomplished by using `.eslintrc.js` file, which can import AirBnB config and loop through all of the rules and change them from error to warning.

**Comment by ashrafhadden** [comment] 2018-05-13 14:56
@not-an-aardvark Thanks for the quick and informative feedback 🙏 Perhaps this would be better suited for VSCode's repo or ESLint for VSCode's repo.

@ilyavolodin Is there a way to actually "loop" through each rule using programming logic? Currently I am simply having to explicitly list every single rule in my eslint-config's, of which there are many.

**Comment by ljharb** [comment] 2018-05-13 14:58
“Almost all style-related” is also not even accurate for either of those configs.

The airbnb config is JS, so you can just require it and change whatever you want.

**Comment by not-an-aardvark** [comment] 2018-05-13 17:15
As a sidenote, I'm not sure looping through a config would work well when it contains relative `extends` paths, because they would be resolved from a different location in the wrapper config.

**Comment by platinumazure** [comment] 2018-05-13 17:26
One thing I've thought about is, maybe we could support JS configurations exporting a function. If we see the function, we would call it with the resolved configuration up to this point and the JS config file could modify as desired. But I'm worried about cost/benefit.

**Comment by ljharb** [comment] 2018-05-13 17:40
That wouldn’t address the need to take a config object and flatten out all the extends items, tho.

**Comment by not-an-aardvark** [comment] 2018-07-22 07:03
Thanks for your interest in improving ESLint. Unfortunately, it looks like this issue didn't get consensus from the team, so I'm closing it. We define [consensus](http://eslint.org/docs/maintainer-guide/issues.html#consensus) as having three :+1:s from team members, as well as a team member willing to champion the proposal. This is a high bar by design -- we can't realistically accept and maintain every feature request in the long term, so we only accept feature requests which are useful enough that there is consensus among the team that they're worth adding.

**Closed by not-an-aardvark** 2018-07-22 07:03 UTC
Labels: core, enhancement, evaluating
