### ISSUE TITLE
Bug: Assigned value not used undetected

### ISSUE THREAD

**Issue by MoonE** [eslint/eslint#15825] opened 2022-05-01 01:16 UTC
### Environment

Local ESLint version: 8.14.0
Operating System: https://eslint.org/demo

### What parser are you using?

Default (Espree)

### What did you do?

```js
let x = 0;
if (x === 5) {
    x = 6;
}
```
[Demo](https://eslint.org/demo#eyJ0ZXh0IjoibGV0IHggPSAwO1xuaWYgKHggPT09IDUpIHtcbiAgICB4ID0gNjtcbn1cbiIsIm9wdGlvbnMiOnsicGFyc2VyT3B0aW9ucyI6eyJlY21hVmVyc2lvbiI6MTIsInNvdXJjZVR5cGUiOiJzY3JpcHQiLCJlY21hRmVhdHVyZXMiOnt9fSwicnVsZXMiOnsiYWNjZXNzb3ItcGFpcnMiOjIsImFycmF5LWJyYWNrZXQtbmV3bGluZSI6MiwiYXJyYXktYnJhY2tldC1zcGFjaW5nIjoyLCJhcnJheS1jYWxsYmFjay1yZXR1cm4iOjIsImFycmF5LWVsZW1lbnQtbmV3bGluZSI6MiwiYXJyb3ctYm9keS1zdHlsZSI6MiwiYXJyb3ctcGFyZW5zIjoyLCJhcnJvdy1zcGFjaW5nIjoyLCJibG9jay1zY29wZWQtdmFyIjoyLCJibG9jay1zcGFjaW5nIjoyLCJicmFjZS1zdHlsZSI6MiwiY2FtZWxjYXNlIjoyLCJjYXBpdGFsaXplZC1jb21tZW50cyI6MiwiY2xhc3MtbWV0aG9kcy11c2UtdGhpcyI6MiwiY29tbWEtZGFuZ2xlIjoyLCJjb21tYS1zcGFjaW5nIjoyLCJjb21tYS1zdHlsZSI6MiwiY29tcGxleGl0eSI6MiwiY29tcHV0ZWQtcHJvcGVydHktc3BhY2luZyI6MiwiY29uc2lzdGVudC1yZXR1cm4iOjIsImNvbnNpc3RlbnQtdGhpcyI6MiwiY29uc3RydWN0b3Itc3VwZXIiOjIsImN1cmx5IjoyLCJkZWZhdWx0LWNhc2UiOjIsImRlZmF1bHQtY2FzZS1sYXN0IjoyLCJkZWZhdWx0LXBhcmFtLWxhc3QiOjIsImRvdC1sb2NhdGlvbiI6MiwiZG90LW5vdGF0aW9uIjoyLCJlb2wtbGFzdCI6MiwiZXFlcWVxIjoyLCJmb3ItZGlyZWN0aW9uIjoyLCJmdW5jLWNhbGwtc3BhY2luZyI6MiwiZnVuYy1uYW1lLW1hdGNoaW5nIjoyLCJmdW5jLW5hbWVzIjoyLCJmdW5jLXN0eWxlIjoyLCJmdW5jdGlvbi1jYWxsLWFyZ3VtZW50LW5ld2xpbmUiOjIsImZ1bmN0aW9uLXBhcmVuLW5ld2xpbmUiOjIsImdlbmVyYXRvci1zdGFyLXNwYWNpbmciOjIsImdldHRlci1yZXR1cm4iOjIsImdyb3VwZWQtYWNjZXNzb3ItcGFpcnMiOjIsImd1YXJkLWZvci1pbiI6MiwiaWQtZGVueWxpc3QiOjIsImlkLW1hdGNoIjoyLCJpbXBsaWNpdC1hcnJvdy1saW5lYnJlYWsiOjIsImluZGVudCI6MiwiaW5pdC1kZWNsYXJhdGlvbnMiOjIsImpzeC1xdW90ZXMiOjIsImtleS1zcGFjaW5nIjoyLCJrZXl3b3JkLXNwYWNpbmciOjIsImxpbmUtY29tbWVudC1wb3NpdGlvbiI6MiwibGluZWJyZWFrLXN0eWxlIjoyLCJsaW5lcy1hcm91bmQtY29tbWVudCI6MiwibGluZXMtYmV0d2Vlbi1jbGFzcy1tZW1iZXJzIjoyLCJtYXgtY2xhc3Nlcy1wZXItZmlsZSI6MiwibWF4LWRlcHRoIjoyLCJtYXgtbGVuIjoyLCJtYXgtbGluZXMiOjIsIm1heC1saW5lcy1wZXItZnVuY3Rpb24iOjIsIm1heC1uZXN0ZWQtY2FsbGJhY2tzIjoyLCJtYXgtcGFyYW1zIjoyLCJtYXgtc3RhdGVtZW50cyI6MiwibWF4LXN0YXRlbWVudHMtcGVyLWxpbmUiOjIsIm11bHRpbGluZS1jb21tZW50LXN0eWxlIjoyLCJtdWx0aWxpbmUtdGVybmFyeSI6MiwibmV3LWNhcCI6MiwibmV3LXBhcmVucyI6MiwibmV3bGluZS1wZXItY2hhaW5lZC1jYWxsIjoyLCJuby1hbGVydCI6Miwibm8tYXJyYXktY29uc3RydWN0b3IiOjIsIm5vLWFzeW5jLXByb21pc2UtZXhlY3V0b3IiOjIsIm5vLWF3YWl0LWluLWxvb3AiOjIsIm5vLWJpdHdpc2UiOjIsIm5vLWNhbGxlciI6Miwibm8tY2FzZS1kZWNsYXJhdGlvbnMiOjIsIm5vLWNsYXNzLWFzc2lnbiI6Miwibm8tY29tcGFyZS1uZWctemVybyI6Miwibm8tY29uZC1hc3NpZ24iOjIsIm5vLWNvbmZ1c2luZy1hcnJvdyI6Miwibm8tY29uc29sZSI6Miwibm8tY29uc3QtYXNzaWduIjoyLCJuby1jb25zdGFudC1iaW5hcnktZXhwcmVzc2lvbiI6Miwibm8tY29uc3RhbnQtY29uZGl0aW9uIjoyLCJuby1jb25zdHJ1Y3Rvci1yZXR1cm4iOjIsIm5vLWNvbnRpbnVlIjoyLCJuby1jb250cm9sLXJlZ2V4IjoyLCJuby1kZWJ1Z2dlciI6Miwibm8tZGVsZXRlLXZhciI6Miwibm8tZGl2LXJlZ2V4IjoyLCJuby1kdXBlLWFyZ3MiOjIsIm5vLWR1cGUtY2xhc3MtbWVtYmVycyI6Miwibm8tZHVwZS1lbHNlLWlmIjoyLCJuby1kdXBlLWtleXMiOjIsIm5vLWR1cGxpY2F0ZS1jYXNlIjoyLCJuby1kdXBsaWNhdGUtaW1wb3J0cyI6Miwibm8tZWxzZS1yZXR1cm4iOjIsIm5vLWVtcHR5IjoyLCJuby1lbXB0eS1jaGFyYWN0ZXItY2xhc3MiOjIsIm5vLWVtcHR5LWZ1bmN0aW9uIjoyLCJuby1lbXB0eS1wYXR0ZXJuIjoyLCJuby1lcS1udWxsIjoyLCJuby1ldmFsIjoyLCJuby1leC1hc3NpZ24iOjIsIm5vLWV4dGVuZC1uYXRpdmUiOjIsIm5vLWV4dHJhLWJpbmQiOjIsIm5vLWV4dHJhLWJvb2xlYW4tY2FzdCI6Miwibm8tZXh0cmEtbGFiZWwiOjIsIm5vLWV4dHJhLXBhcmVucyI6Miwibm8tZXh0cmEtc2VtaSI6Miwibm8tZmFsbHRocm91Z2giOjIsIm5vLWZsb2F0aW5nLWRlY2ltYWwiOjIsIm5vLWZ1bmMtYXNzaWduIjoyLCJuby1nbG9iYWwtYXNzaWduIjoyLCJuby1pbXBsaWNpdC1jb2VyY2lvbiI6Miwibm8taW1wbGljaXQtZ2xvYmFscyI6Miwibm8taW1wbGllZC1ldmFsIjoyLCJuby1pbXBvcnQtYXNzaWduIjoyLCJuby1pbmxpbmUtY29tbWVudHMiOjIsIm5vLWlubmVyLWRlY2xhcmF0aW9ucyI6Miwibm8taW52YWxpZC1yZWdleHAiOjIsIm5vLWludmFsaWQtdGhpcyI6Miwibm8taXJyZWd1bGFyLXdoaXRlc3BhY2UiOjIsIm5vLWl0ZXJhdG9yIjoyLCJuby1sYWJlbC12YXIiOjIsIm5vLWxhYmVscyI6Miwibm8tbG9uZS1ibG9ja3MiOjIsIm5vLWxvbmVseS1pZiI6Miwibm8tbG9vcC1mdW5jIjoyLCJuby1sb3NzLW9mLXByZWNpc2lvbiI6Miwibm8tbWlzbGVhZGluZy1jaGFyYWN0ZXItY2xhc3MiOjIsIm5vLW1peGVkLW9wZXJhdG9ycyI6Miwibm8tbWl4ZWQtc3BhY2VzLWFuZC10YWJzIjoyLCJuby1tdWx0aS1hc3NpZ24iOjIsIm5vLW11bHRpLXNwYWNlcyI6Miwibm8tbXVsdGktc3RyIjoyLCJuby1tdWx0aXBsZS1lbXB0eS1saW5lcyI6Miwibm8tbmVnYXRlZC1jb25kaXRpb24iOjIsIm5vLW5lc3RlZC10ZXJuYXJ5IjoyLCJuby1uZXciOjIsIm5vLW5ldy1mdW5jIjoyLCJuby1uZXctb2JqZWN0IjoyLCJuby1uZXctc3ltYm9sIjoyLCJuby1uZXctd3JhcHBlcnMiOjIsIm5vLW5vbm9jdGFsLWRlY2ltYWwtZXNjYXBlIjoyLCJuby1vYmotY2FsbHMiOjIsIm5vLW9jdGFsIjoyLCJuby1vY3RhbC1lc2NhcGUiOjIsIm5vLXBhcmFtLXJlYXNzaWduIjoyLCJuby1wbHVzcGx1cyI6Miwibm8tcHJvbWlzZS1leGVjdXRvci1yZXR1cm4iOjIsIm5vLXByb3RvIjoyLCJuby1wcm90b3R5cGUtYnVpbHRpbnMiOjIsIm5vLXJlZGVjbGFyZSI6Miwibm8tcmVnZXgtc3BhY2VzIjoyLCJuby1yZXN0cmljdGVkLWV4cG9ydHMiOjIsIm5vLXJlc3RyaWN0ZWQtZ2xvYmFscyI6Miwibm8tcmVzdHJpY3RlZC1pbXBvcnRzIjoyLCJuby1yZXN0cmljdGVkLXByb3BlcnRpZXMiOjIsIm5vLXJlc3RyaWN0ZWQtc3ludGF4IjoyLCJuby1yZXR1cm4tYXNzaWduIjoyLCJuby1yZXR1cm4tYXdhaXQiOjIsIm5vLXNjcmlwdC11cmwiOjIsIm5vLXNlbGYtYXNzaWduIjoyLCJuby1zZWxmLWNvbXBhcmUiOjIsIm5vLXNlcXVlbmNlcyI6Miwibm8tc2V0dGVyLXJldHVybiI6Miwibm8tc2hhZG93IjoyLCJuby1zaGFkb3ctcmVzdHJpY3RlZC1uYW1lcyI6Miwibm8tc3BhcnNlLWFycmF5cyI6Miwibm8tdGFicyI6Miwibm8tdGVtcGxhdGUtY3VybHktaW4tc3RyaW5nIjoyLCJuby10ZXJuYXJ5IjoyLCJuby10aGlzLWJlZm9yZS1zdXBlciI6Miwibm8tdGhyb3ctbGl0ZXJhbCI6Miwibm8tdHJhaWxpbmctc3BhY2VzIjoyLCJuby11bmRlZiI6Miwibm8tdW5kZWYtaW5pdCI6Miwibm8tdW5kZWZpbmVkIjoyLCJuby11bmRlcnNjb3JlLWRhbmdsZSI6Miwibm8tdW5leHBlY3RlZC1tdWx0aWxpbmUiOjIsIm5vLXVubW9kaWZpZWQtbG9vcC1jb25kaXRpb24iOjIsIm5vLXVubmVlZGVkLXRlcm5hcnkiOjIsIm5vLXVucmVhY2hhYmxlIjoyLCJuby11bnJlYWNoYWJsZS1sb29wIjoyLCJuby11bnNhZmUtZmluYWxseSI6Miwibm8tdW5zYWZlLW5lZ2F0aW9uIjoyLCJuby11bnNhZmUtb3B0aW9uYWwtY2hhaW5pbmciOjIsIm5vLXVudXNlZC1sYWJlbHMiOjIsIm5vLXVudXNlZC1wcml2YXRlLWNsYXNzLW1lbWJlcnMiOjIsIm5vLXVudXNlZC12YXJzIjoyLCJuby11c2UtYmVmb3JlLWRlZmluZSI6Miwibm8tdXNlbGVzcy1iYWNrcmVmZXJlbmNlIjoyLCJuby11c2VsZXNzLWNhbGwiOjIsIm5vLXVzZWxlc3MtY2F0Y2giOjIsIm5vLXVzZWxlc3MtY29tcHV0ZWQta2V5IjoyLCJuby11c2VsZXNzLWNvbmNhdCI6Miwibm8tdXNlbGVzcy1jb25zdHJ1Y3RvciI6Miwibm8tdXNlbGVzcy1lc2NhcGUiOjIsIm5vLXVzZWxlc3MtcmVuYW1lIjoyLCJuby11c2VsZXNzLXJldHVybiI6Miwibm8tdmFyIjoyLCJuby12b2lkIjoyLCJuby13YXJuaW5nLWNvbW1lbnRzIjoyLCJuby13aGl0ZXNwYWNlLWJlZm9yZS1wcm9wZXJ0eSI6Miwibm8td2l0aCI6Miwibm9uYmxvY2stc3RhdGVtZW50LWJvZHktcG9zaXRpb24iOjIsIm9iamVjdC1jdXJseS1uZXdsaW5lIjoyLCJvYmplY3QtY3VybHktc3BhY2luZyI6Miwib2JqZWN0LXByb3BlcnR5LW5ld2xpbmUiOjIsIm9iamVjdC1zaG9ydGhhbmQiOjIsIm9uZS12YXIiOjIsIm9uZS12YXItZGVjbGFyYXRpb24tcGVyLWxpbmUiOjIsIm9wZXJhdG9yLWFzc2lnbm1lbnQiOjIsIm9wZXJhdG9yLWxpbmVicmVhayI6MiwicGFkZGluZy1saW5lLWJldHdlZW4tc3RhdGVtZW50cyI6MiwicHJlZmVyLWFycm93LWNhbGxiYWNrIjoyLCJwcmVmZXItY29uc3QiOjIsInByZWZlci1kZXN0cnVjdHVyaW5nIjoyLCJwcmVmZXItZXhwb25lbnRpYXRpb24tb3BlcmF0b3IiOjIsInByZWZlci1uYW1lZC1jYXB0dXJlLWdyb3VwIjoyLCJwcmVmZXItbnVtZXJpYy1saXRlcmFscyI6MiwicHJlZmVyLW9iamVjdC1oYXMtb3duIjoyLCJwcmVmZXItb2JqZWN0LXNwcmVhZCI6MiwicHJlZmVyLXByb21pc2UtcmVqZWN0LWVycm9ycyI6MiwicHJlZmVyLXJlZ2V4LWxpdGVyYWxzIjoyLCJwcmVmZXItcmVzdC1wYXJhbXMiOjIsInByZWZlci1zcHJlYWQiOjIsInByZWZlci10ZW1wbGF0ZSI6MiwicXVvdGUtcHJvcHMiOjIsInF1b3RlcyI6MiwicmFkaXgiOjIsInJlcXVpcmUtYXRvbWljLXVwZGF0ZXMiOjIsInJlcXVpcmUtYXdhaXQiOjIsInJlcXVpcmUtdW5pY29kZS1yZWdleHAiOjIsInJlcXVpcmUteWllbGQiOjIsInJlc3Qtc3ByZWFkLXNwYWNpbmciOjIsInNlbWkiOjIsInNlbWktc3BhY2luZyI6Miwic2VtaS1zdHlsZSI6Miwic29ydC1pbXBvcnRzIjoyLCJzb3J0LWtleXMiOjIsInNvcnQtdmFycyI6Miwic3BhY2UtYmVmb3JlLWJsb2NrcyI6Miwic3BhY2UtYmVmb3JlLWZ1bmN0aW9uLXBhcmVuIjoyLCJzcGFjZS1pbi1wYXJlbnMiOjIsInNwYWNlLWluZml4LW9wcyI6Miwic3BhY2UtdW5hcnktb3BzIjoyLCJzcGFjZWQtY29tbWVudCI6Miwic3RyaWN0IjoyLCJzd2l0Y2gtY29sb24tc3BhY2luZyI6Miwic3ltYm9sLWRlc2NyaXB0aW9uIjoyLCJ0ZW1wbGF0ZS1jdXJseS1zcGFjaW5nIjoyLCJ0ZW1wbGF0ZS10YWctc3BhY2luZyI6MiwidW5pY29kZS1ib20iOjIsInVzZS1pc25hbiI6MiwidmFsaWQtdHlwZW9mIjoyLCJ2YXJzLW9uLXRvcCI6Miwid3JhcC1paWZlIjoyLCJ3cmFwLXJlZ2V4IjoyLCJ5aWVsZC1zdGFyLXNwYWNpbmciOjIsInlvZGEiOjIsIm5vLXVudXNlZC1leHByZXNzaW9ucyI6Mn0sImVudiI6e319fQ==)

### What did you expect to happen?

The last assigned value is unused. This should be caught by a rule, presumably `no-unused-expressions` or `no-unused-vars`

### What actually happened?

No problems detected.

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by mdjermanovic** [comment] 2022-05-01 16:00
Hi @MoonE, thanks for the issue!

ESLint doesn't have a core rule that is intended to detect unused assignments (dead stores). You can check if there is a plugin that provides this functionality, It seems there's an accepted proposal to implement this rule in `eslint-plugin-unicorn` (https://github.com/sindresorhus/eslint-plugin-unicorn/issues/1693).

The `no-unused-expressions` rule checks expressions in positions where the value of the expression is always discarded and thus the expression itself is expected to have an effect on the state of the program. For example, it reports `a + b;` because this expression statement effectively does nothing. In your example, `x = 6;` has an effect as it assigns a value to `x`, so this is not a case this rule was designed to report.

The `no-unused-vars` rule only detects variables that are never read. In this example, variable `x` is read in `x === 5`.

I'm closing this issue since this is not a bug in ESLint core rules as neither of the rules was designed to report this error.

**Closed by mdjermanovic** 2022-05-01 16:00 UTC
Labels: bug, repro:needed

**Comment by aladdin-add** [comment] 2022-05-03 03:23
@mdjermanovic the `no-unused-vars` does report some similar cases, as in the docs:

https://github.com/eslint/eslint/blob/57e732be4e349470fad3e3cc44d96bf0746a598b/docs/src/rules/no-unused-vars.md?plain=1#L38-L40
