### ISSUE TITLE
Unexpected linter output Error

### ISSUE THREAD

**Issue by darioajr** [eslint/eslint#10420] opened 2018-05-29 14:54 UTC
npm run lint -s

standard: Unexpected linter output:

RangeError: Line number out of range (line 11 requested, but only 10 lines present).
    at SourceCode.getIndexFromLoc (/Users/dario/Documents/srm-app/node_modules/eslint/lib/util/source-code.js:389:19)
    at Object.fix (/Users/dario/Documents/srm-app/node_modules/eslint/lib/rules/no-multiple-empty-lines.js:116:52)
    at RuleContext.report (/Users/dario/Documents/srm-app/node_modules/eslint/lib/rule-context.js:127:34)
    at Program:exit.allLines.reduce.concat.reduce (/Users/dario/Documents/srm-app/node_modules/eslint/lib/rules/no-multiple-empty-lines.js:108:37)
    at Array.reduce (<anonymous>)
    at EventEmitter.Program:exit (/Users/dario/Documents/srm-app/node_modules/eslint/lib/rules/no-multiple-empty-lines.js:93:22)
    at EventEmitter.emit (events.js:185:15)
    at NodeEventGenerator.applySelector (/Users/dario/Documents/srm-app/node_modules/eslint/lib/util/node-event-generator.js:265:26)
    at NodeEventGenerator.applySelectors (/Users/dario/Documents/srm-app/node_modules/eslint/lib/util/node-event-generator.js:294:22)
    at NodeEventGenerator.leaveNode (/Users/dario/Documents/srm-app/node_modules/eslint/lib/util/node-event-generator.js:317:14)

If you think this is a bug in `standard`, open an issue: https://github.com/feross/standard/issues

**Comment by platinumazure** [comment] 2018-05-29 15:17
Hi @darioajr, thanks for the issue!

In order for us to look into this, we need to see the linted code that is resulting in the exception being thrown from `no-multiple-empty-lines`.

That said, I assume you're running ESLint (via standard) on a bunch of files and you can't tell which one is causing the issue. So here's what I suggest:

1. Try running ESLint directly (you might need to look in a path like `./node_modules/standard/node_modules/eslint/bin/eslint.js`, unless your npm hoists ESLint to `./node_modules/eslint/bin/eslint.js`) and tweak the command line args to make sure you get the same error
1. Once you have the ESLint CLI reproducing the error, you can add the `--debug` CLI arg. This will hopefully allow you to see what file last started linting before the crash.

When you know what file is experiencing the crash during linting, you can share that with us (or, create a similar file that reproduces the issue, if you need to avoid revealing trade secrets etc.).

**Comment by darioajr** [comment] 2018-05-29 16:51
REACT NATIVE
"babel-eslint": "7.1.1",
"standard": "10.0.2",
"lint": "standard --verbose | snazzy"
Mac OS 10.13.4
Node v9.11.1
Npm 5.6.0

No new information

![captura de tela 2018-05-29 as 13 50 13](https://user-images.githubusercontent.com/7606/40673131-3dd36388-6347-11e8-841f-fd4c03da4459.png)

**Comment by darioajr** [comment] 2018-06-07 22:44
This code triggers the error

[FixtureHubApi.js.zip](https://github.com/eslint/eslint/files/2082311/FixtureHubApi.js.zip)

**Comment by darioajr** [comment] 2018-06-07 22:52
standard@11.0.1
Windows 10 64bit

NO ERROR

![image](https://user-images.githubusercontent.com/7606/41130278-504496da-6a8c-11e8-867c-ded6dbd47492.png)

**Comment by nzakas** [comment] 2018-09-18 16:41
It looks like the conversation is resolved. As this is a question rather than an action item, I'm closing the issue. If you still need help, please send a message to our [mailing list](https://groups.google.com/group/eslint) or [chatroom](https://gitter.im/eslint/eslint). Thanks!

**Closed by nzakas** 2018-09-18 16:41 UTC
Labels: question
