### ISSUE TITLE
prefer-const，sometimes should not use const.

### ISSUE THREAD

**Issue by wghust** [eslint/eslint#7280] opened 2016-09-30 03:48 UTC
**Tell us about your environment**

* **ESLint Version: v3.5.0**
* **Node Version: v5.8.0**
* **npm Version: v3.7.3**

**What parser (default, Babel-ESLint, etc.) are you using?**

Babel-EsLint

```
module.exports = {
  'root': true,
  'parser': 'babel-eslint',
  'parserOptions': {
    'ecmaFeatures': {
      'jsx': true
    }
  },
  'extends': 'vue',
  'plugins': ['flow-vars', 'react'],
  'globals': {
    '$': true,
    'define': true,
    'require': true
  },
  'env': {
    'browser': true,
    'node': true,
    'commonjs': true,
    'es6': true,
    'amd': true
  },
  'rules': {
    // 不需要
    'space-before-function-paren': 0,
    'eol-last': 0,
    'no-extra-semi': 0,
    'semi': 0,
    'one-var': 0,
    'no-undef': 0,
    'no-return-assign': 0,
    'no-extend-native': 0,
    'no-loop-func': 0,

    // 警告
    'eqeqeq': 1,
    'no-extra-boolean-cast': 1,
    'no-extra-parens': 1,
    'no-empty': 1,
    'no-use-before-define': [1, 'nofunc'],
    'complexity': [1, 8],
    'no-unused-vars': 1,
    'no-console': 1,

    // vue
    'flow-vars/define-flow-type': 1,
    'flow-vars/use-flow-type': 1,

    // react
    'react/jsx-uses-react': 2,
    'react/jsx-uses-vars': 2,

    // 错误
    'curly': 2,
    'comma-dangle': [2, 'never'],
    'no-debugger': 2,
    'no-constant-condition': 2,
    'no-dupe-args': 2,
    'no-dupe-keys': 2,
    'no-duplicate-case': 2,
    'no-empty-character-class': 2,
    'no-invalid-regexp': 2,
    'no-func-assign': 2,
    'valid-typeof': 2,
    'no-unreachable': 2,
    'no-unexpected-multiline': 2,
    'no-sparse-arrays': 2,
    'no-shadow-restricted-names': 2,
    'no-cond-assign': 2,
    'no-native-reassign': 2,

    // 代码风格
    'no-else-return': 1,
    'no-multi-spaces': 1,
    'key-spacing': [1, {
      'beforeColon': false,
      'afterColon': true
    }],
    'block-scoped-var': 2,
    'consistent-return': 2,
    'accessor-pairs': 2,
    'dot-location': [2, 'property'],
    'no-lone-blocks': 2,
    'no-labels': 2,
    'no-floating-decimal': 2,
    'no-new-func': 2,
    'no-self-compare': 2,
    'no-sequences': 2,
    'no-throw-literal': 2,
    'no-redeclare': [2, {
      'builtinGlobals': true
    }],
    'no-unused-expressions': [2, {
      'allowShortCircuit': true,
      'allowTernary': true
    }],
    'no-useless-call': 2,
    'no-useless-concat': 2,
    'no-void': 2,
    'no-with': 2,
    'space-infix-ops': 2,
    'valid-jsdoc': [2, {
      'requireParamDescription': true,
      'requireReturnDescription': true
    }],
    'no-warning-comments': [2, {
      'terms': ['todo', 'fixme', 'any other term'],
      'location': 'anywhere'
    }],
    'no-trailing-spaces': [1, {
      'skipBlankLines': true
    }],
    'no-unneeded-ternary': [1, {
      'defaultAssignment': true
    }]
  }
};
```
![1a0451b0-0135-4a03-b3d1-1eef8f2667e8](https://cloud.githubusercontent.com/assets/3960935/18980122/a978eaee-8703-11e6-9ea6-3fb2e75d6b70.png)
![a8928b76-864a-499c-9210-82a6f9928a7a](https://cloud.githubusercontent.com/assets/3960935/18980123/aafbfeec-8703-11e6-980e-5cf0100f732d.png)

In fact, we should use `let` instands of `const`.

**Comment by not-an-aardvark** [comment] 2016-09-30 04:03
Thanks for the issue. However, I think this is a duplicate of https://github.com/eslint/eslint/issues/3104.

Node 5 has a bug where `const` declarations in `for` loops are handled incorrectly -- the value always remains at 0, as you showed in your screenshot. This is actually incorrect behavior (see the [V8 bug](https://bugs.chromium.org/p/v8/issues/detail?id=3305)), so it was decided in https://github.com/eslint/eslint/issues/3104 that ESLint would still require `const` in these scenarios.

If you upgrade to Node 6, the issue will be fixed.

I'm going to close this issue as a duplicate, but please feel free to continue the discussion.

**Closed by not-an-aardvark** 2016-09-30 04:03 UTC
Labels: triage

**Comment by wghust** [comment] 2016-09-30 07:00
@not-an-aardvark in firefox 48.0.1, it still has this problem. 
<img width="486" alt="qq20160930-1" src="https://cloud.githubusercontent.com/assets/3960935/18983293/7db46b70-871e-11e6-80e6-523454aeb8fc.png">

**Comment by ljharb** [comment] 2016-09-30 07:14
@wghust for..in is for iterating over object properties on the entire prototype, not arrays and their own list of items - you should use a for loop, or `.forEach` etc, to do that anyways, which won't suffer from this problem.

**Comment by wghust** [comment] 2016-09-30 07:23
@ljharb change the array to object, it still has this problem.
<img width="618" alt="qq20160930-2" src="https://cloud.githubusercontent.com/assets/3960935/18983842/c69dc824-8721-11e6-98e9-972d487c4353.png">

**Comment by mysticatea** [comment] 2016-09-30 09:53
@wghust Firefox has a bug, it does not support `let` and `const` on iteration scope.

http://kangax.github.io/compat-table/es6/

**Comment by mysticatea** [comment] 2016-09-30 10:09
In funny fact, there are many duplicate issues: #6337, #5568, #4933, #4838, #4333, #4088, and #3104.

https://github.com/eslint/eslint/issues/3104#issuecomment-157743822 is a detail description.
