### ISSUE TITLE
Bug: indent vars "first" with de-structuring assignment gives unexpected results.

### ISSUE THREAD

**Issue by AshHeskes** [eslint/eslint#16145] opened 2022-07-18 19:01 UTC
### Environment

Node version: 16.15.00
npm version: 8.10.0
Local ESLint version: 8.20.0
Global ESLint version: v8.20.0
Operating System: MacOS

### What parser are you using?

Default (Espree)

### What did you do?

<details>
<summary>Configuration</summary>

[Problem Demo Link:](https://eslint.org/play/#eyJ0ZXh0IjoiLyogZXNsaW50IFwiaW5kZW50XCI6IFsgXCJlcnJvclwiLCAyLCB7IFwiVmFyaWFibGVEZWNsYXJhdG9yXCI6IFwiZmlyc3RcIiB9IF0gKi9cblxuLyogRXhwZWN0IGluZGVudCB0byBtYXRjaCBvcGVuaW5nIGJyYWNrZXQvYnJhY2UgZm9yIG11bHRpbGluZSBkZS1zdHJ1Y3R1cmluZyBhcyB0byBhbGlnbiB3aXRoIHZhciBgZGAgKi9cbmNvbnN0IHtcbiAgICAgICAgYSxcbiAgICAgICAgYixcbiAgICAgICAgYyxcbiAgICAgIH0gPSB7fSxcbiAgICAgIGQgPSAnZSc7XG5cbi8qIFlvdSBnZXQgYW4gZXJyb3IgZm9yIGVpdGhlciB0aGUgZGUtc3RydWN0dXJlZCB2YXJzIG9yIHZhcnMgZGVjbGFyZWQgYWZ0ZXIuIFRoZXJlJ3Mgbm8gXCJyaWdodFwiIGFuc3dlci4gKi9cbmNvbnN0IHtcbiAgZixcbiAgZyxcbiAgaCxcbn0gPSB7fSxcbiAgaSA9ICdqJztcblxuLyogRXhjZXB0IGZvciBhbGwgb24gb25lIGxpbmUsIHdoaWNoIGNsZWFybHkgY2FuIGdldCB1Z2x5IHF1aWNrbHkgKi9cbmNvbnN0IHsgaiwgaywgbCB9ID0gJ20nLFxuICAgICAgbyA9ICdwJztcblxuLyogSXQncyB0aGUgc2FtZSBmb3IgYXJyYXkgZGUtc3RydWN0dXJpbmcuICovXG5jb25zdCBbXG4gICAgICAgIHEsXG4gICAgICAgIHIsXG4gICAgICAgIHMsXG4gICAgICBdID0gW10sXG4gICAgICB0ID0gJ3UnO1xuXG4vKiBIaWRpbmcgaXJyZWxldmVudCBsaW50ZXIgd2FybmluZ3MgKi9cbmV4cG9ydCBkZWZhdWx0IGEgKyBiICsgYyArIGQgKyBmICsgZyArIGggKyBpICsgaiArIGsgKyBsICsgbyArIHEgKyByICsgcyArIHQ7ICIsIm9wdGlvbnMiOnsicGFyc2VyT3B0aW9ucyI6eyJlY21hVmVyc2lvbiI6MjAyMiwic291cmNlVHlwZSI6Im1vZHVsZSIsImVjbWFGZWF0dXJlcyI6eyJpbXBsaWVkU3RyaWN0Ijp0cnVlfX0sInJ1bGVzIjp7ImNvbnN0cnVjdG9yLXN1cGVyIjpbImVycm9yIl0sImZvci1kaXJlY3Rpb24iOlsiZXJyb3IiXSwiZ2V0dGVyLXJldHVybiI6WyJlcnJvciJdLCJuby1hc3luYy1wcm9taXNlLWV4ZWN1dG9yIjpbImVycm9yIl0sIm5vLWNhc2UtZGVjbGFyYXRpb25zIjpbImVycm9yIl0sIm5vLWNsYXNzLWFzc2lnbiI6WyJlcnJvciJdLCJuby1jb21wYXJlLW5lZy16ZXJvIjpbImVycm9yIl0sIm5vLWNvbmQtYXNzaWduIjpbImVycm9yIl0sIm5vLWNvbnN0LWFzc2lnbiI6WyJlcnJvciJdLCJuby1jb25zdGFudC1jb25kaXRpb24iOlsiZXJyb3IiXSwibm8tY29udHJvbC1yZWdleCI6WyJlcnJvciJdLCJuby1kZWJ1Z2dlciI6WyJlcnJvciJdLCJuby1kZWxldGUtdmFyIjpbImVycm9yIl0sIm5vLWR1cGUtYXJncyI6WyJlcnJvciJdLCJuby1kdXBlLWNsYXNzLW1lbWJlcnMiOlsiZXJyb3IiXSwibm8tZHVwZS1lbHNlLWlmIjpbImVycm9yIl0sIm5vLWR1cGUta2V5cyI6WyJlcnJvciJdLCJuby1kdXBsaWNhdGUtY2FzZSI6WyJlcnJvciJdLCJuby1lbXB0eSI6WyJlcnJvciJdLCJuby1lbXB0eS1jaGFyYWN0ZXItY2xhc3MiOlsiZXJyb3IiXSwibm8tZW1wdHktcGF0dGVybiI6WyJlcnJvciJdLCJuby1leC1hc3NpZ24iOlsiZXJyb3IiXSwibm8tZXh0cmEtYm9vbGVhbi1jYXN0IjpbImVycm9yIl0sIm5vLWV4dHJhLXNlbWkiOlsiZXJyb3IiXSwibm8tZmFsbHRocm91Z2giOlsiZXJyb3IiXSwibm8tZnVuYy1hc3NpZ24iOlsiZXJyb3IiXSwibm8tZ2xvYmFsLWFzc2lnbiI6WyJlcnJvciJdLCJuby1pbXBvcnQtYXNzaWduIjpbImVycm9yIl0sIm5vLWlubmVyLWRlY2xhcmF0aW9ucyI6WyJlcnJvciJdLCJuby1pbnZhbGlkLXJlZ2V4cCI6WyJlcnJvciJdLCJuby1pcnJlZ3VsYXItd2hpdGVzcGFjZSI6WyJlcnJvciJdLCJuby1sb3NzLW9mLXByZWNpc2lvbiI6WyJlcnJvciJdLCJuby1taXNsZWFkaW5nLWNoYXJhY3Rlci1jbGFzcyI6WyJlcnJvciJdLCJuby1taXhlZC1zcGFjZXMtYW5kLXRhYnMiOlsiZXJyb3IiXSwibm8tbmV3LXN5bWJvbCI6WyJlcnJvciJdLCJuby1ub25vY3RhbC1kZWNpbWFsLWVzY2FwZSI6WyJlcnJvciJdLCJuby1vYmotY2FsbHMiOlsiZXJyb3IiXSwibm8tb2N0YWwiOlsiZXJyb3IiXSwibm8tcHJvdG90eXBlLWJ1aWx0aW5zIjpbImVycm9yIl0sIm5vLXJlZGVjbGFyZSI6WyJlcnJvciJdLCJuby1yZWdleC1zcGFjZXMiOlsiZXJyb3IiXSwibm8tc2VsZi1hc3NpZ24iOlsiZXJyb3IiXSwibm8tc2V0dGVyLXJldHVybiI6WyJlcnJvciJdLCJuby1zaGFkb3ctcmVzdHJpY3RlZC1uYW1lcyI6WyJlcnJvciJdLCJuby1zcGFyc2UtYXJyYXlzIjpbImVycm9yIl0sIm5vLXRoaXMtYmVmb3JlLXN1cGVyIjpbImVycm9yIl0sIm5vLXVuZGVmIjpbImVycm9yIl0sIm5vLXVuZXhwZWN0ZWQtbXVsdGlsaW5lIjpbImVycm9yIl0sIm5vLXVucmVhY2hhYmxlIjpbImVycm9yIl0sIm5vLXVuc2FmZS1maW5hbGx5IjpbImVycm9yIl0sIm5vLXVuc2FmZS1uZWdhdGlvbiI6WyJlcnJvciJdLCJuby11bnNhZmUtb3B0aW9uYWwtY2hhaW5pbmciOlsiZXJyb3IiXSwibm8tdW51c2VkLWxhYmVscyI6WyJlcnJvciJdLCJuby11bnVzZWQtdmFycyI6WyJlcnJvciJdLCJuby11c2VsZXNzLWJhY2tyZWZlcmVuY2UiOlsiZXJyb3IiXSwibm8tdXNlbGVzcy1jYXRjaCI6WyJlcnJvciJdLCJuby11c2VsZXNzLWVzY2FwZSI6WyJlcnJvciJdLCJuby13aXRoIjpbImVycm9yIl0sInJlcXVpcmUteWllbGQiOlsiZXJyb3IiXSwidXNlLWlzbmFuIjpbImVycm9yIl0sInZhbGlkLXR5cGVvZiI6WyJlcnJvciJdfSwiZW52Ijp7Im5vZGUiOnRydWUsImVzMjAyMSI6dHJ1ZX19fQ==)

```json
{
    "rules": {
        "indent": [ "error", 2, { "VariableDeclarator": "first" } ]
    }
}
```
</details>

```js
/* Expect indent to match opening bracket/brace for multiline de-structuring as to align with non de-structured assignments */
const {
        a,
        b,
        c,
      } = {},
      d = 'e';
```

### What did you expect to happen?

I expected that it would accept a de-structured assignment where the indent of multiline vars is +1 relative to the opening bracket.

### What actually happened?

The linter expects the de-structured assignment indent to be +1 relative to the block scope even when further assignments are expected at the opening of the de-structuring bracket/brace.

linter thinks this is correct:
```js
const {
  a,
  b,
  c,
} = {},
       d = 'e',
       f = 'g';

```

vs:

```js
const {
         a,
         b,
         c,
       } = {},
       d = 'e',
       f = 'g';

```

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by nzakas** [comment] 2022-07-21 00:55
Thanks for the report. The indent rule does have a lot of edge cases because indentation is a complex process. This looks like it’s a bug. 

Fixes to the indent rule are low priority right now, but if you’d like to dig in and see if you can fix it, we will gladly review the PR.

**Comment by iambumblehead** [comment] 2023-10-07 21:25
hello, a reproduction of related indentation issues is made here https://github.com/iambumblehead/eslint-repro-destructured-intent

**Comment by iambumblehead** [comment] 2023-10-07 21:31
to anyone who may find this, when lint errors occur around destructured assignment like this
```javascript
let t = true,
    f = false

[t, f] = [t, f].map(n => String(n)) // lint error expected indentation of 10 spaces
```

putting a semi before the assignment makes the error go away
```javascript
let t = true,
    f = false

;[t, f] = [t, f].map(n => String(n))
```

**Comment by mdjermanovic** [comment] 2023-10-08 19:25
> ```js
> let t = true,
>     f = false
> 
> [t, f] = [t, f].map(n => String(n)) // lint error expected indentation of 10 spaces
> ```

This is probably a correct indentation because the left `[t, f]` is access to a property of `false` (and `,` is the comma operator; `t, f` evaluates to `f`). This code is the same as:

```js
let t = true,
    f = (false[t, f] = [t, f].map(n => String(n)))
```

**Comment by iambumblehead** [comment] 2023-10-09 05:58
@mdjermanovic you are wrong

**Comment by iambumblehead** [comment] 2023-10-09 06:00
@mdjermanovic specifically, try running the original demonstration in a browser or a node runtime --it does not evaluate the way you have suggested

**Comment by iambumblehead** [comment] 2023-10-09 09:41
@mdjermanovic you are right and I had a typo in my own demonstration. Thanks for the explanation

**Comment by nzakas** [comment] 2023-10-19 14:55
Hi folks, I just wanted to let everyone know that the ESLint team has decided to deprecate all formatting rules, including indent, and recommend people use source code formatters like [Prettier](https://prettier.io) or [dprint](https://dprint.dev) instead. As a result, we are closing all outstanding issues related to these rules. For more information, please see https://github.com/eslint/eslint/issues/17522. Thanks.

**Closed by nzakas** 2023-10-19 14:55 UTC
Labels: bug, accepted, indent, repro:yes
