### ISSUE TITLE
eslint in a multi repository project

### ISSUE THREAD

**Issue by jonny64** [eslint/eslint#16392] opened 2022-10-06 07:57 UTC
let's say, I have following project structure:

```
back/package.json
back/lib/Content/*.js
front/package.json
slices/budget/back/package.json
slices/budget/back/lib/Content/*.js
slices/budget/front/package.json
slices/accounting/back/package.json
slices/accounting/back/lib/Content/*.js
slices/accounting/front/package.json
```
how do I?
```
cd back && eslint ./lib/**/*.js ../slices/**/lib/Content/*.js
```

+500 reputation if anwsered on https://stackoverflow.com/questions/73797616/run-eslint-in-multi-repository-project

_Originally posted by @jonny64 in https://github.com/eslint/eslint/discussions/16329_

**Comment by mdjermanovic** [comment] 2022-10-10 15:07
Duplicate of https://github.com/eslint/eslint/discussions/16329

**Closed by mdjermanovic** 2022-10-10 15:07 UTC
Labels: triage
