### ISSUE TITLE
ESLint configuration is invalid: 	- Unexpected top-level property "ecmaFeatures".

### ISSUE THREAD

**Issue by sbdm05** [eslint/eslint#8933] opened 2017-07-12 14:02 UTC
i have installed Eslint (latest version), with npm latest version

  "devDependencies": {
    "eslint": "^4.2.0",
    "eslint-config-rallycoding": "^3.2.0",
    "eslint-plugin-react": "^7.1.0"
}

* **Node Version:** v7.9.0
* **npm Version:** 4.2.0

**What parser (default, Babel-ESLint, etc.) are you using?** default

My configuration:**
{
  "name": "street-french-dictionary",
  "version": "0.0.0",
  "description": "Hello Expo!",
  "author": null,
  "private": true,
  "main": "main.js",
  "dependencies": {
    "@expo/ex-navigation": "^3.0.0",
    "babel-preset-react-native-stage-0": "^1.0.1",
    "expo": "17.0.0",
    "firebase": "^4.1.2",
    "lottie-react-native": "^1.1.1",
    "react": "16.0.0-alpha.6",
    "react-native": "https://github.com/expo/react-native/archive/sdk-17.0.0.tar.gz",
    "react-navigation": "^1.0.0-beta.11"
  },
  "devDependencies": {
    "eslint": "^4.2.0",
    "eslint-config-rallycoding": "^3.2.0",
    "eslint-plugin-react": "^7.1.0"
  }
}

**What did you do? Please include the actual source code causing the issue.**

I have installed Eslint with SublimeText3. Errors are not shown. 

Console says: 

**SublimeLinter: eslint output:
[object Object]:
	ESLint configuration is invalid:
	- Unexpected top-level property "ecmaFeatures".**

**Full Console Message:** 
```
startup, version: 3126 osx x64 channel: stable
executable: /Applications/Sublime Text.app/Contents/MacOS/Sublime Text
working dir: /
packages path: /Users/Rumas/Library/Application Support/Sublime Text 3/Packages
state path: /Users/Rumas/Library/Application Support/Sublime Text 3/Local
zip path: /Applications/Sublime Text.app/Contents/MacOS/Packages
zip path: /Users/Rumas/Library/Application Support/Sublime Text 3/Installed Packages
ignored_packages: ["Vintage"]
ignoring deprecated syntax definition: Packages/Ruby on Rails snippets/HTML (Rails).tmLanguage
pre session restore time: 1.3292
first paint time: 1.50557
startup time: 1.50684
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.01-pygments
reloading plugin 0_package_control_loader.50-backrefs
reloading plugin 0_package_control_loader.50-markupsafe
reloading plugin 0_package_control_loader.50-python-markdown
reloading plugin 0_package_control_loader.51-python-jinja2
reloading plugin 0_package_control_loader.55-mdpopups
reloading plugin AdvancedNewFile.AdvancedNewFile
reloading plugin All Autocomplete.all_views_completions
reloading plugin ApplySyntax.ApplySyntax
reloading plugin ApplySyntax.support
reloading plugin BracketHighlighter.bh_core
reloading plugin BracketHighlighter.bh_logging
reloading plugin BracketHighlighter.bh_plugin
reloading plugin BracketHighlighter.bh_popup
reloading plugin BracketHighlighter.bh_regions
reloading plugin BracketHighlighter.bh_remove
reloading plugin BracketHighlighter.bh_rules
reloading plugin BracketHighlighter.bh_search
reloading plugin BracketHighlighter.bh_swapping
reloading plugin BracketHighlighter.bh_wrapping
reloading plugin BracketHighlighter.support
reloading plugin DocBlockr.jsdocs
reloading plugin Emmet.emmet-plugin
reloading plugin Git.git_commands
reloading plugin GitGutter.plugin
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
reloading plugin SCSS.scss_completions
reloading plugin SublimeLinter-annotations.linter
SublimeLinter: annotations linter loaded 
reloading plugin SublimeLinter.commands
reloading plugin SublimeLinter.sublimelinter
reloading plugin SublimeLinter-contrib-eslint.linter
SublimeLinter: eslint linter loaded 
plugins loaded
SublimeLinter: debug mode: off 
SublimeLinter: annotations activated: <builtin> 
Emmet: No need to update PyV8
SublimeLinter: error in SublimeLinter daemon: 
SublimeLinter: -------------------- 
SublimeLinter: Traceback (most recent call last):
  File "/Users/Rumas/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/queue.py", line 57, in loop
    item = self.q.get(block=True, timeout=self.MIN_DELAY)
  File "./python3.3/queue.py", line 175, in get
queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Rumas/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/queue.py", line 65, in loop
    self.lint(view_id, timestamp)
  File "/Users/Rumas/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/queue.py", line 111, in lint
    self.callback(view_id, timestamp)
  File "/Users/Rumas/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/sublimelinter.py", line 120, in lint
    Linter.lint_view(view, filename, code, hit_time, callback)
  File "/Users/Rumas/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/linter.py", line 962, in lint_view
    callback(cls.get_view(vid), linters, hit_time)
  File "/Users/Rumas/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/sublimelinter.py", line 138, in highlight
    vid = view.id()
AttributeError: 'NoneType' object has no attribute 'id'
 
SublimeLinter: -------------------- 
Package Control: Skipping automatic upgrade, last run at 2017-07-12 15:29:15, next run at 2017-07-12 16:29:15 or after
SublimeLinter: error in SublimeLinter daemon: 
SublimeLinter: -------------------- 
SublimeLinter: Traceback (most recent call last):
  File "/Users/Rumas/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/queue.py", line 57, in loop
    item = self.q.get(block=True, timeout=self.MIN_DELAY)
  File "./python3.3/queue.py", line 175, in get
queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Rumas/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/queue.py", line 65, in loop
    self.lint(view_id, timestamp)
  File "/Users/Rumas/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/queue.py", line 111, in lint
    self.callback(view_id, timestamp)
  File "/Users/Rumas/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/sublimelinter.py", line 120, in lint
    Linter.lint_view(view, filename, code, hit_time, callback)
  File "/Users/Rumas/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/linter.py", line 962, in lint_view
    callback(cls.get_view(vid), linters, hit_time)
  File "/Users/Rumas/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/sublimelinter.py", line 138, in highlight
    vid = view.id()
AttributeError: 'NoneType' object has no attribute 'id'
 
SublimeLinter: -------------------- 
SublimeLinter: annotations activated: <builtin> 
reloading settings Packages/User/SublimeLinter.sublime-settings
ignoring deprecated syntax definition: Packages/Ruby on Rails snippets/HTML (Rails).tmLanguage
reloading settings Packages/User/SublimeLinter.sublime-settings
ignoring deprecated syntax definition: Packages/Ruby on Rails snippets/HTML (Rails).tmLanguage
reloading settings Packages/User/SublimeLinter.sublime-settings
ignoring deprecated syntax definition: Packages/Ruby on Rails snippets/HTML (Rails).tmLanguage
SublimeLinter: eslint: WordItem.js ['/Users/Rumas/Desktop/ReactNative/street-french-dictionary/node_modules/.bin/eslint', '--format', 'compact', '--stdin', '--stdin-filename', '@'] 
SublimeLinter: eslint output:
[object Object]:
	ESLint configuration is invalid:
	- Unexpected top-level property "ecmaFeatures".

Referenced from: /Users/Rumas/Desktop/ReactNative/street-french-dictionary/node_modules/eslint-config-rallycoding/index.js
Referenced from: /Users/Rumas/Desktop/ReactNative/street-french-dictionary/.eslintrc.json
Error: [object Object]:
	ESLint configuration is invalid:
	- Unexpected top-level property "ecmaFeatures".

Referenced from: /Users/Rumas/Desktop/ReactNative/street-french-dictionary/node_modules/eslint-config-rallycoding/index.js
Referenced from: /Users/Rumas/Desktop/ReactNative/street-french-dictionary/.eslintrc.json
    at validateConfigSchema (/Users/Rumas/Desktop/ReactNative/street-french-dictionary/node_modules/eslint/lib/config/config-validator.js:192:15)
    at Object.validate (/Users/Rumas/Desktop/ReactNative/street-french-dictionary/node_modules/eslint/lib/config/config-validator.js:205:5)
    at loadFromDisk (/Users/Rumas/Desktop/ReactNative/street-french-dictionary/node_modules/eslint/lib/config/config-file.js:549:19)
    at load (/Users/Rumas/Desktop/ReactNative/street-french-dictionary/node_modules/eslint/lib/config/config-file.js:592:20)
    at configExtends.reduceRight (/Users/Rumas/Desktop/ReactNative/street-french-dictionary/node_modules/eslint/lib/config/config-file.js:421:36)
    at Array.reduceRight (native)
    at applyExtends (/Users/Rumas/Desktop/ReactNative/street-french-dictionary/node_modules/eslint/lib/config/config-file.js:405:28)
    at loadFromDisk (/Users/Rumas/Desktop/ReactNative/street-french-dictionary/node_modules/eslint/lib/config/config-file.js:556:22)
    at load (/Users/Rumas/Desktop/ReactNative/street-french-dictionary/node_modules/eslint/lib/config/config-file.js:592:20)
    at configExtends.reduceRight (/Users/Rumas/Desktop/ReactNative/street-french-dictionary/node_modules/eslint/lib/config/config-file.js:421:36) 
SublimeLinter: annotations activated: <builtin> 
SublimeLinter: eslint: main.js ['/Users/Rumas/Desktop/ReactNative/street-french-dictionary/node_modules/.bin/eslint', '--format', 'compact', '--stdin', '--stdin-filename', '@'] 
SublimeLinter: eslint output:
[object Object]:
	ESLint configuration is invalid:
	- Unexpected top-level property "ecmaFeatures".

Referenced from: /Users/Rumas/Desktop/ReactNative/street-french-dictionary/node_modules/eslint-config-rallycoding/index.js
Referenced from: /Users/Rumas/Desktop/ReactNative/street-french-dictionary/.eslintrc.json
Error: [object Object]:
	ESLint configuration is invalid:
	- Unexpected top-level property "ecmaFeatures".

Referenced from: /Users/Rumas/Desktop/ReactNative/street-french-dictionary/node_modules/eslint-config-rallycoding/index.js
Referenced from: /Users/Rumas/Desktop/ReactNative/street-french-dictionary/.eslintrc.json
    at validateConfigSchema (/Users/Rumas/Desktop/ReactNative/street-french-dictionary/node_modules/eslint/lib/config/config-validator.js:192:15)
    at Object.validate (/Users/Rumas/Desktop/ReactNative/street-french-dictionary/node_modules/eslint/lib/config/config-validator.js:205:5)
    at loadFromDisk (/Users/Rumas/Desktop/ReactNative/street-french-dictionary/node_modules/eslint/lib/config/config-file.js:549:19)
    at load (/Users/Rumas/Desktop/ReactNative/street-french-dictionary/node_modules/eslint/lib/config/config-file.js:592:20)
    at configExtends.reduceRight (/Users/Rumas/Desktop/ReactNative/street-french-dictionary/node_modules/eslint/lib/config/config-file.js:421:36)
    at Array.reduceRight (native)
    at applyExtends (/Users/Rumas/Desktop/ReactNative/street-french-dictionary/node_modules/eslint/lib/config/config-file.js:405:28)
    at loadFromDisk (/Users/Rumas/Desktop/ReactNative/street-french-dictionary/node_modules/eslint/lib/config/config-file.js:556:22)
    at load (/Users/Rumas/Desktop/ReactNative/street-french-dictionary/node_modules/eslint/lib/config/config-file.js:592:20)
    at configExtends.reduceRight (/Users/Rumas/Desktop/ReactNative/street-french-dictionary/node_modules/eslint/lib/config/config-file.js:421:36) 
SublimeLinter: error in SublimeLinter daemon: 
SublimeLinter: -------------------- 
SublimeLinter: Traceback (most recent call last):
  File "/Users/Rumas/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/queue.py", line 57, in loop
    item = self.q.get(block=True, timeout=self.MIN_DELAY)
  File "./python3.3/queue.py", line 175, in get
queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Rumas/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/queue.py", line 65, in loop
    self.lint(view_id, timestamp)
  File "/Users/Rumas/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/queue.py", line 111, in lint
    self.callback(view_id, timestamp)
  File "/Users/Rumas/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/sublimelinter.py", line 120, in lint
    Linter.lint_view(view, filename, code, hit_time, callback)
  File "/Users/Rumas/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/linter.py", line 962, in lint_view
    callback(cls.get_view(vid), linters, hit_time)
  File "/Users/Rumas/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/sublimelinter.py", line 138, in highlight
    vid = view.id()
AttributeError: 'NoneType' object has no attribute 'id'
 
SublimeLinter: -------------------- 
SublimeLinter: eslint: WordItem.js ['/Users/Rumas/Desktop/ReactNative/street-french-dictionary/node_modules/.bin/eslint', '--format', 'compact', '--stdin', '--stdin-filename', '@'] 
SublimeLinter: eslint: WordItem.js ['/Users/Rumas/Desktop/ReactNative/street-french-dictionary/node_modules/.bin/eslint', '--format', 'compact', '--stdin', '--stdin-filename', '@'] 
SublimeLinter: eslint output:
[object Object]:
	ESLint configuration is invalid:
	- Unexpected top-level property "ecmaFeatures".

Referenced from: /Users/Rumas/Desktop/ReactNative/street-french-dictionary/node_modules/eslint-config-rallycoding/index.js
Referenced from: /Users/Rumas/Desktop/ReactNative/street-french-dictionary/.eslintrc.json
Error: [object Object]:
	ESLint configuration is invalid:
	- Unexpected top-level property "ecmaFeatures".

Referenced from: /Users/Rumas/Desktop/ReactNative/street-french-dictionary/node_modules/eslint-config-rallycoding/index.js
Referenced from: /Users/Rumas/Desktop/ReactNative/street-french-dictionary/.eslintrc.json
    at validateConfigSchema (/Users/Rumas/Desktop/ReactNative/street-french-dictionary/node_modules/eslint/lib/config/config-validator.js:192:15)
    at Object.validate (/Users/Rumas/Desktop/ReactNative/street-french-dictionary/node_modules/eslint/lib/config/config-validator.js:205:5)
    at loadFromDisk (/Users/Rumas/Desktop/ReactNative/street-french-dictionary/node_modules/eslint/lib/config/config-file.js:549:19)
    at load (/Users/Rumas/Desktop/ReactNative/street-french-dictionary/node_modules/eslint/lib/config/config-file.js:592:20)
    at configExtends.reduceRight (/Users/Rumas/Desktop/ReactNative/street-french-dictionary/node_modules/eslint/lib/config/config-file.js:421:36)
    at Array.reduceRight (native)
    at applyExtends (/Users/Rumas/Desktop/ReactNative/street-french-dictionary/node_modules/eslint/lib/config/config-file.js:405:28)
    at loadFromDisk (/Users/Rumas/Desktop/ReactNative/street-french-dictionary/node_modules/eslint/lib/config/config-file.js:556:22)
    at load (/Users/Rumas/Desktop/ReactNative/street-french-dictionary/node_modules/eslint/lib/config/config-file.js:592:20)
    at configExtends.reduceRight (/Users/Rumas/Desktop/ReactNative/street-french-dictionary/node_modules/eslint/lib/config/config-file.js:421:36) 
SublimeLinter: eslint output:
[object Object]:
	ESLint configuration is invalid:
	- Unexpected top-level property "ecmaFeatures".

Referenced from: /Users/Rumas/Desktop/ReactNative/street-french-dictionary/node_modules/eslint-config-rallycoding/index.js
Referenced from: /Users/Rumas/Desktop/ReactNative/street-french-dictionary/.eslintrc.json
Error: [object Object]:
	ESLint configuration is invalid:
	- Unexpected top-level property "ecmaFeatures".

Referenced from: /Users/Rumas/Desktop/ReactNative/street-french-dictionary/node_modules/eslint-config-rallycoding/index.js
Referenced from: /Users/Rumas/Desktop/ReactNative/street-french-dictionary/.eslintrc.json
    at validateConfigSchema (/Users/Rumas/Desktop/ReactNative/street-french-dictionary/node_modules/eslint/lib/config/config-validator.js:192:15)
    at Object.validate (/Users/Rumas/Desktop/ReactNative/street-french-dictionary/node_modules/eslint/lib/config/config-validator.js:205:5)
    at loadFromDisk (/Users/Rumas/Desktop/ReactNative/street-french-dictionary/node_modules/eslint/lib/config/config-file.js:549:19)
    at load (/Users/Rumas/Desktop/ReactNative/street-french-dictionary/node_modules/eslint/lib/config/config-file.js:592:20)
    at configExtends.reduceRight (/Users/Rumas/Desktop/ReactNative/street-french-dictionary/node_modules/eslint/lib/config/config-file.js:421:36)
    at Array.reduceRight (native)
    at applyExtends (/Users/Rumas/Desktop/ReactNative/street-french-dictionary/node_modules/eslint/lib/config/config-file.js:405:28)
    at loadFromDisk (/Users/Rumas/Desktop/ReactNative/street-french-dictionary/node_modules/eslint/lib/config/config-file.js:556:22)
    at load (/Users/Rumas/Desktop/ReactNative/street-french-dictionary/node_modules/eslint/lib/config/config-file.js:592:20)
    at configExtends.reduceRight (/Users/Rumas/Desktop/ReactNative/street-french-dictionary/node_modules/eslint/lib/config/config-file.js:421:36) 
```

**Comment by not-an-aardvark** [comment] 2017-07-12 16:39
Closing as duplicate of https://github.com/eslint/eslint/issues/8726

**Closed by not-an-aardvark** 2017-07-12 16:39 UTC
Labels: triage
