### ISSUE TITLE
bag in version 6.0.0

### ISSUE THREAD

**Issue by maystrenkoYurii** [eslint/eslint#11882] opened 2019-06-23 14:10 UTC
bag in version 6.0.0 and "eslint-loader": "2.1.2"
![Снимок](https://user-images.githubusercontent.com/23016311/59977450-ccec7080-95d9-11e9-8f96-d5182b157bc4.PNG)
With old version 5.16.0 good work

**Comment by maystrenkoYurii** [comment] 2019-06-23 14:17
@bot version eslint 6.0.0

**Comment by g-plane** [comment] 2019-06-23 14:19
Hey @maystrenkoYurii , thanks for the issue.

Can you fill out our issue template and tell what problems you have encountered?

**Comment by maystrenkoYurii** [comment] 2019-06-23 14:27
@g-plane I think eslint-loader version 2.1.2 causes conflict with eslint version 6.0.0

**Comment by g-plane** [comment] 2019-06-23 14:28
So I think you'd better open issue at `eslint-loader`'s repo.

**Comment by kaicataldo** [comment] 2019-06-23 15:27
@maystrenkoYurii It's really difficult to figure out what's going on here without the information requested in our templates, but it does look to me like this is a Webpack/eslint-loader issue based on the information given above.

**Comment by weilinzung** [comment] 2019-06-24 00:48
`Error: Cannot find module 'eslint/lib/formatters/stylish'`

```
    "eslint": "^6.0.0",
    "eslint-loader": "^2.1.2",
```

**Comment by g-plane** [comment] 2019-06-24 01:15
It seems that `eslint-loader` is out of maintenance.

**Comment by bsas** [comment] 2019-06-24 17:56
This issue looks like it is affecting webpack plugins:
https://github.com/webpack-contrib/eslint-loader/issues/238

**Comment by g-plane** [comment] 2019-06-24 23:51
Maybe this issue can be closed if we confirmed it's an issue from `eslint-loader`.

**Comment by mysticatea** [comment] 2019-06-25 04:11
Closing as not an issue in ESLint itself. Thank you.

**Closed by mysticatea** 2019-06-25 04:11 UTC
Labels: bug, needs info
