### ISSUE TITLE
guard-for-in doesn't recognize that Object.entries() is returning an array for for...in loop

### ISSUE THREAD

**Issue by calligraphic** [eslint/eslint#9808] opened 2018-01-05 11:29 UTC
* **ESLint Version:**
4.14.0
* **Node Version:**
v8.0.0
* **npm Version:**
5.6.0
**What parser (default, Babel-ESLint, etc.) are you using?**
babel-eslint 8.1.2
<details>
<summary>Configuration</summary>
```js
{
  "extends": "airbnb-base",
  "parser": "babel-eslint",
  "env": {
    "jest": true
  },
  "rules": {
    "arrow-parens": "off",
    "no-throw-literal": "error",
    "no-void": "off",
    "import/prefer-default-export": "off",
    "valid-jsdoc": "error",
    "no-unused-expressions": [
      "error",
      {
        "allowShortCircuit": true,
        "allowTernary": true
      }
    ]
  }
}
```
</details>
**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
for (const file in Object.entries(newMockFiles)) {
 ...
}
```
Command ran:

```bash
eslint src
```
**What did you expect to happen?**
No linting error. The linter should recognize that the `for...in` is iterating over an array.

**What actually happened? Please include the actual, raw output from ESLint.**
error  The body of a for-in should be wrapped in an if statement to filter unwanted properties from the prototype  guard-for-in

**Comment by Aladdin-ADD** [comment] 2018-01-05 14:18
I was not able to repro it.  [the demo](https://eslint.org/demo/#eyJ0ZXh0IjoiZm9yICh2YXIgZmlsZSBpbiBPYmplY3QuZW50cmllcyhuZXdNb2NrRmlsZXMpKXtcblx0Y29uc29sZS5sb2coZmlsZSk7XG59Iiwib3B0aW9ucyI6eyJwYXJzZXJPcHRpb25zIjp7ImVjbWFWZXJzaW9uIjo2LCJzb3VyY2VUeXBlIjoic2NyaXB0IiwiZWNtYUZlYXR1cmVzIjp7fX0sInJ1bGVzIjp7ImxpbmVzLWJldHdlZW4tY2xhc3MtbWVtYmVycyI6MiwiZ3VhcmQtZm9yLWluIjoyfSwiZW52Ijp7fX19)

what does the `...`mean in your code above? if the block is empty, ESLint will not report errors. I think this is working as expected.

**Comment by platinumazure** [comment] 2018-01-05 15:52
I see an error when I have something in the body, whether working with an array-returning function or an array literal. Demo [here](https://eslint.org/demo/#eyJ0ZXh0IjoiLyogZXNsaW50IGd1YXJkLWZvci1pbjogZXJyb3IgKi9cclxuZm9yIChjb25zdCBmaWxlIGluIE9iamVjdC5lbnRyaWVzKG5ld01vY2tGaWxlcykpIHtcclxuICAgIGRvU29tZXRoaW5nKCk7XHJcbn0iLCJvcHRpb25zIjp7InBhcnNlck9wdGlvbnMiOnsiZWNtYVZlcnNpb24iOjgsInNvdXJjZVR5cGUiOiJzY3JpcHQiLCJlY21hRmVhdHVyZXMiOnt9fSwicnVsZXMiOnt9LCJlbnYiOnt9fX0=).

I don't think the rule was designed to care about the type of the iterated object. So I'm having a hard time seeing this as a bug.

**Comment by calligraphic** [comment] 2018-01-05 17:22
@platinumazure The [documentation](https://eslint.org/docs/rules/guard-for-in) has the following top-level explanation for the purpose of the rule:

> Looping over objects with a for in loop will include properties that are inherited through the prototype chain. This behavior can lead to unexpected items in your for loop.

Since the purpose of this rule doesn't apply to arrays, it seems to me that arrays shouldn't trigger the rule.

**Comment by michaelficarra** [comment] 2018-01-06 00:01
@calligraphic It does make sense. What makes an array special? Arrays also have prototypes (`Array.prototype` and `Object.prototype`) which may have enumerable properties added to them.

Additionally, these types of rules often do not track what kinds of values are being acted on. It's almost always impossible, as we have no idea if that is the built-in `Object` or a shadowed/overwritten one.

**Comment by mysticatea** [comment] 2018-01-06 07:40
I think that this is intentional behavior because the rule is intended to catch the following case:

> ```js
> Array.prototype.fool = 0
> 
> for (const entry in Object.entries({a:1,b:2})) {
>  console.log(entry)
> }
> ```
> https://jsbin.com/jadupegawu/edit?js,console

**Comment by calligraphic** [comment] 2018-01-06 20:22
I understand the rule much better, thank you. Is it reasonable that the rule wouldn't trigger for a case like this?

`for (const i in [x, y, z])`

**Comment by not-an-aardvark** [comment] 2018-01-19 15:32
I think the rule still should trigger in that case, because if a property has been added to `Array.prototype` it will be found by the loop.

**Comment by not-an-aardvark** [comment] 2018-03-05 18:04
Closing because this is working as intended.

**Closed by not-an-aardvark** 2018-03-05 18:04 UTC
Labels: question
