### ISSUE TITLE
Question. Update: rule 'padding-line-between-statements'

### ISSUE THREAD

**Issue by IgorNovozhilov** [eslint/eslint#12317] opened 2019-09-26 12:54 UTC
Can I expect a reaction to my PR in the foreseeable future?
https://github.com/eslint/eslint/pull/11788

**Comment by kaicataldo** [comment] 2019-09-26 23:46
Apologies for the PR falling through the cracks. We generally recommend getting approval on a proposal in an issue before implementing it. It doesn't look like there has been enough support for the proposal yet, but I'll ping the rest of the team on the PR and see if anyone else wants to support it. We have a bot that usually auto closes proposals that aren't accepted, but we don't do the same for PRs since they can take some time to implement.

I'm going to close this issue as a dupe of https://github.com/eslint/eslint/pull/11788.

**Closed by kaicataldo** 2019-09-26 23:46 UTC
Labels: triage
