### ISSUE TITLE
"Cannot read property of 'loc' of undefined" when typing "const"

### ISSUE THREAD

**Issue by brandonwoz** [eslint/eslint#13957] opened 2020-12-25 15:34 UTC
**Tell us about your environment**

* **ESLint Version: 6.8.0**
* **Node Version: 14.15.3**
* **npm Version: 6.14.10**

**What parser (default, `@babel/eslint-parser`, `@typescript-eslint/parser`, etc.) are you using?**
    parser: '@typescript-eslint/parser',

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
module.exports = {
  root: true,
  env: {
    node: true,
  },
  extends: [
    'plugin:vue/vue3-essential',
    '@vue/airbnb',
    '@vue/typescript/recommended',
  ],
  parserOptions: {
    ecmaVersion: 2020,
    parser: '@typescript-eslint/parser',
  },
  rules: {
    'no-console': process.env.NODE_ENV === 'production' ? 'warn' : 'off',
    'no-debugger': process.env.NODE_ENV === 'production' ? 'warn' : 'off',
  },
  overrides: [
    {
      files: [
        '**/__tests__/*.{j,t}s?(x)',
        '**/tests/unit/**/*.spec.{j,t}s?(x)',
      ],
      env: {
        jest: true,
      },
    },
  ],
};
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

When typing ```const```, VScode is returning the following error:

```ESLint: Cannot read property 'loc' of undefined Occurred while linting /xxx.ts:1. at Object.VariableDeclaration [as listener] (/xxx/node_modules/eslint/lib/rules/indent.js:1384:69)```

**What did you expect to happen?**
No error message. Apparently this was also an issue a few years ago (issue 441).

**What actually happened? Please include the actual, raw output from ESLint.**

```ESLint: Cannot read property 'loc' of undefined Occurred while linting /xxx.ts:1. at Object.VariableDeclaration [as listener] (/xxx/node_modules/eslint/lib/rules/indent.js:1384:69)```

**Comment by mdjermanovic** [comment] 2020-12-25 21:14
Hi @brandonwoz, thanks for the issue!

I think this is a duplicate of https://github.com/eslint/eslint/issues/13956. Can you try with [`@typescript-eslint/indent`](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/indent.md) instead of the core `indent` rule:

```json
{
  "indent": "off",
  "@typescript-eslint/indent": ["error"]
}
```

**Comment by brandonwoz** [comment] 2020-12-25 22:44
> @typescript-eslint/indent

This worked. Thank you!

**Comment by brandonwoz** [comment] 2020-12-25 22:44
> Hi @brandonwoz, thanks for the issue!
> 
> I think this is a duplicate of #13956. Can you try with [`@typescript-eslint/indent`](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/indent.md) instead of the core `indent` rule:
> 
> ```json
> {
>   "indent": "off",
>   "@typescript-eslint/indent": ["error"]
> }
> ```

This worked. Thank you!

**Comment by mdjermanovic** [comment] 2020-12-27 20:31
Closing, since the problem is solved.

**Closed by mdjermanovic** 2020-12-27 20:31 UTC
Labels: 3rd party plugin, bug, rule

**Comment by niceue** [comment] 2021-04-27 12:21
The problem is still not solved.

**Comment by mdjermanovic** [comment] 2021-06-26 12:34
Another solution: https://github.com/eslint/eslint/issues/14538#issuecomment-862280037
