### ISSUE TITLE
Improvement: no-redeclare "globals only"

### ISSUE THREAD

**Issue by Epaminaidos** [eslint/eslint#9514] opened 2017-10-25 10:30 UTC
* **ESLint Version:** 4.9.0

The rule "no-redeclare" has been doing two things for us:
- check for redeclared local variables
- check for redeclared globals (Object, Array, etc.)

That's two very different checks combined in a single rule.

Now we would like to disable the first check and only keep the latter one.
But there is no option to do that. Would it be possible to add this option?

**Comment by not-an-aardvark** [comment] 2018-01-19 15:43
Thanks for your interest in improving ESLint. Unfortunately, it looks like this issue didn't get consensus from the team, so I'm closing it. We define [consensus](http://eslint.org/docs/maintainer-guide/issues.html#consensus) as having three :+1:s from team members, as well as a team member willing to champion the proposal. This is a high bar by design -- we can't realistically accept and maintain every feature request in the long term, so we only accept feature requests which are useful enough that there is consensus among the team that they're worth adding.

Since ESLint is pluggable and can load custom rules at runtime, the lack of consensus among the ESLint team doesn't need to be a blocker for you using this in your project, if you'd find it useful. It just means that you would need to [implement the rule](http://eslint.org/docs/developer-guide/working-with-rules) yourself, rather than using a bundled rule that is packaged with ESLint.

**Closed by not-an-aardvark** 2018-01-19 15:43 UTC
Labels: enhancement, evaluating, needs info, rule
