### ISSUE TITLE
`indentSwitchCase` doesn't work with `default`

### ISSUE THREAD

**Issue by andy-hanson** [eslint/eslint#2470] opened 2015-05-09 06:38 UTC
My code:

	function fun() {
		switch (1) {
			case 1:
				return 1
			default:
				return 2
		}
	}

I want to ensure that I remembered to indent all the switch cases.
So I set up my package.json as:

	{
		"eslintConfig": {
			"rules": {
				"indent": [ 1, "tab", { "indentSwitchCase": true } ],
				"no-unused-vars": 0,
				"semi": 0,
				"strict": 0
			}
		}
	}

And now I get errors:

	index.js
	  5:3  warning  Expected indentation of 3 characters  indent
	  6:4  warning  Expected indentation of 4 characters  indent
	  7:3  warning  Expected indentation of 3 characters  indent

	✖ 4 problems (1 error, 3 warnings)

It shouldn't expect an indentation of 3 characters. `switch` is at indentation 1, so `default` should be at indentation 2, not 3. To satisfy the rule I have to make my code look like this:

	function fun() {
		switch (1) {
			case 1:
				return 1
				default:
					return 2
				}
	}

**Comment by nzakas** [comment] 2015-05-09 15:35
Duplicate of #1797

**Closed by nzakas** 2015-05-09 15:35 UTC
