### ISSUE TITLE
Add mjs to --ext default

### ISSUE THREAD

**Issue by jaydenseric** [eslint/eslint#9592] opened 2017-11-08 01:38 UTC
Currently, the only default file extension for the `--ext` CLI option is `js`.

It would be good to add `mjs` to the default, since it is the emerging standard for native Node.js modules. Then the increasingly common lint npm script could go from `"eslint . --ext js,mjs"` back to simply `eslint .`.

**Comment by jkrems** [comment] 2017-12-18 21:40
Was just running into this because some of the files in my project were silently ignored.

**Comment by platinumazure** [comment] 2017-12-18 22:14
Could someone provide links to any literature, ECMA proposals, discussions, etc. on the mjs extension? It would be good for the team to have the background and current state of the .mjs extension.

In particular, I'm interested in what other environments besides Node will start to support the extension. We don't like to make changes in ESLint that clearly favor one particular runtime environment over another, and my limited understanding is that Node.js is helping to drive this. So if nobody else is on board, this will be more difficult to rationalize (at least for me).

**Comment by ljharb** [comment] 2017-12-18 22:25
@platinumazure it's solely a node thing; ECMA has no authority on that.

The primary environments are "browsers" - which ignore extensions altogether - and "node" - which supports `.js` and `require`, both of which eslint supports *solely for node*. `.mjs` is something `node` will almost certainly ship, and thus I think that's more than sufficient for eslint to *need* to support it

**Comment by jkrems** [comment] 2017-12-19 02:47
Even outside of node `.mjs` is a neat solution for migrating larger projects to ES modules because it's one of the few ways to [quickly declare different `parserOptions` using `overrides.files`](https://twitter.com/jankrems/status/942797322009767936).

**Comment by kaicataldo** [comment] 2017-12-21 21:07
@jkrems Just to be clear, this is possible currently. `.mjs` just has to be specified on the command line.

**Comment by jkrems** [comment] 2017-12-21 22:47
@kaicataldo Yep, that's what I'm currently doing (`--ext=mjs,js`). The issue is more that I was able to accidentally get "successful" lint runs because I didn't know that this is required. I assume other people will also run into the same issue as they adopt modules.

**Comment by not-an-aardvark** [comment] 2017-12-22 01:42
This was discussed in [today's TSC meeting](https://github.com/eslint/tsc-meetings/blob/e02b20e99ac1169d8c45ccae32ce2891248d1218/notes/2017/2017-12-21.md#add-mjs-to---ext-default). It seems like the TSC generally wants this to work by default at some point. However, a few people expressed concerns about accepting the proposal right now:

* An enhancement along the lines of https://github.com/eslint/eslint/issues/8920 might be a better general solution to avoid the need for a hardcoded list of default extensions in ESLint core.
* `.mjs` is still behind a flag in Node, leading to the impression that the behavior might change in the future.

Since this would be a breaking change in ESLint anyway, the resolution was to reevaluate this issue when we start planning for the next major release, in case anything changes (either in the `.mjs` ecosystem or in ESLint's file-extension customization) before that point.

**Comment by jpike88** [comment] 2018-02-02 07:57
.mjs based applications are stable, I’ve been running one in a large scale production environment for over 6 months. You may find demand for this is actually understated.

**Comment by jaydenseric** [comment] 2018-02-02 07:59
I've been using it in production for months too.

**Comment by ljharb** [comment] 2018-02-02 08:00
They're "stable" until node changes its experimental support; that people use it in production doesn't mean anybody should.

The behavior is unlikely to change in any meaningful way in node, but none the less, it wouldn't be appropriate for eslint to default to it until it's unflagged.

**Comment by jpike88** [comment] 2018-02-02 08:11
> That people use it in production doesn't mean anybody should.

In principle you're correct, and I agree with everything else 100%.. but that statement I agree 99.9%.

This is one of those unicorns that I'd consider absolutely worth looking into for full blown usage. The fact that it eliminates cyclic dependency issues for stateless applications is huge for us. Makes me a little annoyed that Node isn't pushing it harder, I don't know anything else that's been stuck in a so called 'experimental' state for so long.

**Comment by jaydenseric** [comment] 2018-02-02 08:51
> it wouldn't be appropriate for eslint to default to it until it's unflagged

Why not? It won't affect people who are not interested in `.mjs`. But adding a few characters will make life easier for the thousands of us who are.  [standard-things/esm](https://github.com/standard-things/esm) alone has over 2k stars, so a lot of people are having to fiddle with this seemingly unnecessary config. I have had to add ` --ext js,mjs` in at least 5 packages so far.

> that people use it in production doesn't mean anybody should

It's not the place of ESLint to gatekeep what we should or shouldn't use in production in our own apps. If people don't use `.mjs`, then no problem. But if they do, they will surely expect it to be linted just like `.js` since it *is* just standard JS. `.mjs` more likely to contain vanilla JS than `.js`, since people often put funky things like JSX, etc. in `.js` files.

Worse case scenario `.mjs` gets abandoned by Node.js a future version. It would still be handy to retain the `.mjs` default since Node.js versions using it will be supported for a while and there will be a lot of files in circulation and maintenance for years to come. At some point ESLint may just remove it from the defaults again, easy-peasy.

**Comment by ljharb** [comment] 2018-02-02 08:59
Prior to mjs being unflagged, any argument to including it is identical to an argument for including ”jsx”.

**Comment by jaydenseric** [comment] 2018-02-02 09:02
No, because `.mjs` contains vanilla JS, where `.jsx` doesn't and likely needs special parser config, etc.

**Comment by ljharb** [comment] 2018-02-02 09:06
It’d still need parser config, since the default ecmaVersion is 5.

**Comment by jaydenseric** [comment] 2018-02-02 09:09
Those smarts would be a cherry on top, ES6 `.js` files need manual ESLint config for those things too.

**Comment by kaicataldo** [comment] 2018-02-02 15:43
> It's not the place of ESLint to gatekeep what we should or shouldn't use in production in our own apps.

I know @jaydenseric knows this because they mention it in their comment, but I just want to make this clear for anyone else who stumbles across this discussion that ESLint allows files with arbitrary extensions to be linted with the [--ext](https://eslint.org/docs/user-guide/command-line-interface#--ext) command line flag.

**Comment by alberto** [comment] 2018-03-15 18:12
Given it's still marked as experimental by node terms and it could be removed, I am against adding it at this moment.

**Comment by jpike88** [comment] 2018-03-16 01:47
@alberto the fact you’re citing the experiment status shows you’re not listening to us and ignoring the reality of the situation. It doesn’t matter what the node docs say, it’s being used by many devs and increasingly so for the better part of a year. Node 9.8.0 was released with further improvements to it, it is not going to be reverted or changed in a foreseeable manner. It should be treated in effect as valid an extension to use as any other.

**Comment by not-an-aardvark** [comment] 2018-03-16 01:59
I agree with @alberto. I don't think it's relevant that some developers have chosen to ignore Node's warning and use experimental features in production. These developers may be willing to risk having their code break or run incorrectly if the feature changes, but that doesn't mean other projects and tools should be obligated to take the same risks. The behavior of ESM in node is still very much in the air and subject to change.

"Experimental" doesn't mean "this behavior will be stable eventually and you can use it to get ahead of the game", it means "this behavior could change in major ways before becoming stable and if you use it your code has a good chance of breaking". If you're willing to add a command-line flag whenever you run Node, you can also use a command-line flag when running ESLint.

**Comment by jaydenseric** [comment] 2018-03-16 02:07
@not-an-aardvark If `.mjs` is a default linted extension, and if hypothetically Node.js ends up abandoning it in a future version (they won't!), please explain a single bad consequence for ESLint users.

Sometimes it feels like tools resist adding `.mjs` support not out of concern for users, but rather to to try to sabotage mass adoption and cast a vote against the direction chosen by Node.js.

**Comment by not-an-aardvark** [comment] 2018-03-16 02:21
> If `.mjs` is a default linted extension, and if hypothetically Node.js ends up abandoning it in a future version (they won't!), please explain a single bad consequence for ESLint users.

If the semantics of `.mjs` are modified such that a file's source type depends on additional factors (e.g. if it can be overridden by a `package.json` flag), then ESLint's behavior of inferring the source type based on the file extension will become out of date with how Node works, and so ESLint will get the source type wrong.

> Sometimes it feels like tools resist adding .mjs support not out of concern for users, but rather to to try to sabotage mass adoption and cast a vote against the direction chosen by Node.js.

I don't think this suggestion is fair, especially given that I've been [actively advocating for the`.esm` extension](https://github.com/nodejs/node/pull/18392#issuecomment-370961611) in Node discussions. No one in this thread has argued against supporting `.mjs` because they don't like the extension; they've been arguing against supporting it for now because it's experimental.

---

To be honest, I don't understand why this is so controversial. Adding a command-line flag to ESLint is really not very difficult, and you're already adding a command-line flag to Node if you're using `.mjs` in production.

**Comment by jaydenseric** [comment] 2018-03-16 02:26
@not-an-aardvark

> ESLint's behavior of inferring the source type based on the file extension will become out of date with how Node works

This issue, and my PR https://github.com/eslint/eslint/pull/10058 is not about inferring source type config based on a `.mjs` extension.

**Comment by not-an-aardvark** [comment] 2018-03-16 02:29
Well, in that case the problem is much more clear -- ESLint would already be inferring the wrong source type. If/when `.mjs` becomes stable in Node, I think we would want to infer `sourceType` the same way that Node does, so that users don't need to explicitly set it in configuration.

**Comment by not-an-aardvark** [comment] 2018-03-16 02:34
> The issue is more that I was able to accidentally get "successful" lint runs because I didn't know that this is required. I assume other people will also run into the same thing as they adopt modules.

For what it's worth, this will be fixed in ESLint v5.0 (see https://github.com/eslint/eslint/issues/7390); doing a lint run that doesn't match any files will be a fatal error.

**Comment by jaydenseric** [comment] 2018-03-16 02:42
@not-an-aardvark regarding `sourceType`: https://github.com/eslint/eslint/issues/9592#issuecomment-362528379

Regarding the no files match error, that will not help projects with both `.js` and `.mjs` files. Just having `.babelrc.js` present ([although that example you have to unignore first](https://github.com/eslint/eslint/issues/10089)) will hide the fact that all your `.mjs` files were ignored.

**Comment by not-an-aardvark** [comment] 2018-04-12 21:12
In [today's TSC meeting](https://github.com/eslint/tsc-meetings/blob/4604d91e9e0c546b9bf336ed24dc9a7998a17010/notes/2018/2018-04-12.md#add-mjs-to---ext-default), the TSC decided to not accept this issue for 5.0 because Node's support for `.mjs` is still experimental. We anticipate that we will add support for this eventually when it becomes stable, unless Node's roadmap changes. (As noted earlier in this issue, you can use the `--ext=.js,.mjs` flag to lint `.mjs` files today.)

**Closed by not-an-aardvark** 2018-04-12 21:12 UTC
Labels: breaking, cli, enhancement, evaluating, tsc agenda
