### ISSUE TITLE
Can't read from Firebase Without Return 

### ISSUE THREAD

**Issue by wlaa41** [eslint/eslint#10507] opened 2018-06-22 22:02 UTC
**Tell us about your environment**

* **6.1.0**
* **Node Version:**
* **npm Version:**

**What parser (default, Babel-ESLint, etc.) are you using?**

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
const functions = require('firebase-functions');
const { WebhookClient } = require('firebase-functions');
const { Card, Suggestion } = require('firebase-functions');
//const { Carousel } = require('actions-on-google');
const func = require('http');
var http = require('http');
var url = require('url');
var key = 'xxxxxxxxxxxxxxxx';
var admin = require('firebase-admin'); // wlaa41 I added before run npm install firebase-admin --save in FUNCTIONS dir 
admin.initializeApp(functions.config().firebase);
const db = admin.firestore();

// // Create and Deploy Your First Cloud Functions
// // https://firebase.google.com/docs/functions/write-firebase-functions
//
exports.webhook = functions.https.onRequest((request, response) => {
    var Area =  request.body.queryResult.parameters.place_or_room.toString();   
    var  action = "no";
    var Devicetype = "no";
    var Answere =  { fulfillmentText:"Sorry I counld not get you", // outputContexts: [] 
};
   if(request.body.queryResult.action === 'mediaact'){
       
         Devicetype = request.body.queryResult.parameters.Media_Type;
          action = request.body.queryResult.parameters.media_act;

          Answere =  { fulfillmentText: "Ok sure, " + Devicetype+" "+ action, // outputContexts: [] 
                        }
                        triggerIftttMakerWebhook("event",key,Area,String(""+Devicetype+" "+action+""));
    }
    else{
        if(request.body.queryResult.action === 'command'){

              Devicetype = request.body.queryResult.parameters.type;
              action = request.body.queryResult.parameters.action;
              Answere =  { fulfillmentText: "Ok sure, " + Devicetype+" "+ action, // outputContexts: [] 
            }
            triggerIftttMakerWebhook("palace",key,Area,String(""+Devicetype+" "+action+""));
        }  
    }

    if(request.body.queryResult.action === 'query'){


        var NoOfOnLight = new Object();
        room = request.body.queryResult.parameters.place_or_room;

var testtext ;                         
db.collection('scc').doc('demo').get().then( (docu1) => {
    if(docu1)
    {
        testtext ="Exist "+ docu1.id;
    }
    else
    {
        testtext ="Exist but undefined";
    }
   // return  console.log("Document successfully read!");  /////  <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< RETURN 
    }).catch((onrejected ) => {
        testtext = "Error";
    });

    var mrwill = db.collection('scc').doc('demo');
    mrwill.update({
       roomname: "true"
   })
.then(function() {
    return console.log("Document successfully updated!");
 })
 .catch(function(error) {
     // The document probably doesn't exist.
     return console.error("Error updating document: ", error);
 });

     mrwill = db.collection('scc').doc('demo');
     mrwill.set({ any_data:"HELLOOOOOOOO ",roomname: "true"});
        Answere =  { fulfillmentText: " testtext     it   "+testtext+"       mm "+testtext+  "mm   "+orders[1] +"   gg g g  ", // outputContexts: [] 
        }
      }
    response.send(Answere);
     
   });
   




     var triggerIftttMakerWebhook = function (event, key, value1, value2, value3) {
        

    var iftttNotificationUrl = `https://maker.ifttt.com/trigger/${event}/with/key/${key}`;
    var postData = JSON.stringify({ value1, value2, value3 });

    var parsedUrl = url.parse(iftttNotificationUrl);
    var post_options = {
        hostname: parsedUrl.hostname,
        path: parsedUrl.path,
        method: 'POST',
        headers: {
            'Content-Type': 'application/json',
            'Content-Length': postData.length
        }
    };

    var post_req = http.request(post_options, function (res) {
        res.setEncoding('utf8');
        res.on('data', function (chunk) {
       //     console.log(chunk.toString());
            //console.log('Response: ' + chunk);
            agent.add(chunk.toString());
        });
    });
    // Trigger a POST to the url with the body.
    post_req.write(postData);
    post_req.end();
    }

exports.ZAPwebhook = functions.https.onRequest((request1, response) => {
    var string = ""+request1.body.body;
    var array = string.split(",");
    
    var arraydatetime = string.split(" ");

//     var mrwill = db.collection('SCC Office').doc('mr will')
//     mrwill.update({
//        capital: true
//    })
// .then(function() {
//     return console.log("Document successfully updated!");
//  })
//  .catch(function(error) {
//      // The document probably doesn't exist.
//      return console.error("Error updating document: ", error);
//  });

    // var mrwill = db.collection('SCC Office').doc('mr will')
    //  mrwill.set(room);
    


   


    response.send(""+array[1]+"  arraydatetime[7] :  " +arraydatetime[7] );


 
     
   });: 
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js

```

```bash

```

**Read Data from Firebase?**

**Error when I try to place the command? Please include the actual, raw output from ESLint.**

**Comment by wlaa41** [comment] 2018-06-22 22:04
when I add return everything seem to go fine but it doesn't actually read any data
![untitled](https://user-images.githubusercontent.com/40356509/41801113-4ae3c110-7681-11e8-848f-d15d6bc083df.png)

The .eslint.json is a mess

![untitleed](https://user-images.githubusercontent.com/40356509/41801114-4b0c310e-7681-11e8-919d-e54c8beb335c.png)

**Comment by ilyavolodin** [comment] 2018-06-23 17:06
Closing as duplicate of #10506

**Closed by ilyavolodin** 2018-06-23 17:06 UTC
Labels: needs info, triage
