### ISSUE TITLE
More auto-fill responses

### ISSUE THREAD

**Issue by nzakas** [eslint/eslint#5342] opened 2016-02-19 18:54 UTC
The "needs info" experiment seems to be working pretty well. I'd like to explore adding some more autoresponses so we can further cut down on the amount of issue triage we have to do. Here are some ideas:

* `question` - if we add this label, it should mean that the issue is not a bug report or change request, but rather a general question ("how do I?"). In this case, I'd like to autocomment asking them to stop by the chatroom or contact the mailing list. Then, close the issue.
* `custom rule` - if we add this label, it should mean that we're recommending someone create a custom rule rather than creating a core rule. The bot will autocomment saying this and including links to more information for how to create a custom rule. Then, close the issue.
* `as designed` - if we add this label, it should mean that a bug report has been disproved, that is, it's not a bug at all and is working as designed so we won't be making any changes. The bot would autocomment this and close the issue.

Thoughts?

**Comment by ilyavolodin** [comment] 2016-02-19 19:30
Sounds reasonable to me. Although I was never a fan of redirecting questions to other information sources. If I already spend time to mark question with labels, and then have to spend time answering the same question in chat, I might as well spend less time answering it in the issue directly. But that's a personal opinion.
I think additional rule options template would be nice too.

**Comment by BYK** [comment] 2016-02-19 19:57
I like it too. I'd prefer `invalid` to `as designed` since it is more in line with other issue trackers I use but both are fine at the end of the day.

**Comment by alberto** [comment] 2016-02-20 13:17
Sounds good. I would try to centralize questions in just one place. Right now, people ask questions in the following places (that I know of): the issue queue, the mailing list, the chat and stackoverflow.

**Comment by nzakas** [comment] 2016-02-20 17:06
@ilyavolodin the goal wrt to questions is to keep them out of issues so issues only represent tasks. If we stop answering questions in issues, people will eventually stop asking questions in issues. If we answer them, then they will keep doing it. This is a bit of social training.

@byk I think `as designed` is a lot clearer than `invalid`. I want to be as clear as possible. 

Another idea, auto comment when "help wanted" is added with a message that explains the issue won't be done by the team, but PRs are accepted.

**Comment by BYK** [comment] 2016-02-22 11:56
>@byk I think as designed is a lot clearer than invalid. I want to be as clear as possible. 

Alright, fair point :)

>Another idea, auto comment when "help wanted" is added with a message that explains the issue won't be done by the team, but PRs are accepted.

:+1:

**Comment by nzakas** [comment] 2016-02-22 16:12
Here's another:

* `babel` - when added, autocomment that the issue is related to babel-eslint and close the issue.

**Comment by nzakas** [comment] 2016-04-21 19:04
Since GitHub has canned responses now, I'm not sure this is needed. Any thoughts?

**Comment by alberto** [comment] 2016-04-21 20:24
I think it would be nice for consistency. Not sure about `custom rule` though,  since only project leaders should be able to decide on that

**Comment by alberto** [comment] 2016-08-01 19:54
Closing this. Feel free to reopen.

**Closed by alberto** 2016-08-01 19:54 UTC
Labels: enhancement, evaluating, infrastructure
