### ISSUE TITLE
remove spaces when fixing `prefer-template`

### ISSUE THREAD

**Issue by UziTech** [eslint/eslint#10025] opened 2018-02-27 06:01 UTC
**Tell us about your environment**

* **ESLint Version:** 4.18.1
* **Node Version:** 9.4.0
* **npm Version:** 5.6.0

**What parser (default, Babel-ESLint, etc.) are you using?**

default

**Please show your full configuration:**

```js
{
    "rules": {
        "prefer-template": 2
    }
}
```

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
"a" + b + "c";
```

```bash
eslint . --fix
```

**What did you expect to happen?**

```js
`a${b}c`;
```

**What actually happened? Please include the actual, raw output from ESLint.**

```js
`a${  b  }c`;
```

**Comment by not-an-aardvark** [comment] 2018-02-27 06:04
Closing as a duplicate of https://github.com/eslint/eslint/issues/8520

**Closed by not-an-aardvark** 2018-02-27 06:04 UTC
Labels: triage

**Comment by UziTech** [comment] 2018-02-27 06:11
The problem with just adding `template-curly-spacing` is you have to run --fix again in order for that rule to find the extra spaces.

Something like an option in `prefer-template` like `remove-extra-spaces` would work.

**Comment by not-an-aardvark** [comment] 2018-02-27 06:13
It shouldn't be necessary to run `--fix` again, because `--fix` already does multiple passes over the source code. Have you tried it?

**Comment by UziTech** [comment] 2018-02-27 06:18
Hmm, you seem to be right when running `eslint . --fix` from the command line but using the Node API leaves the spacing until it is run a second time. I will have to investigate further.

**Comment by UziTech** [comment] 2018-02-27 06:33
Yup that is the problem.

The plugin is using the CLIEngine without the `fix` option and sending the returned fixes back to the editor so the editor can fix them without needing to overwrite the entire file.

An option on `prefer-template` would still work for this.

**Comment by not-an-aardvark** [comment] 2018-02-27 06:44
We generally don't add options to rules that conflict with other rules, or options that pertain specifically to autofixing, because they would end up very redundant with each other, and it still wouldn't be possible to account for all of the ways that rule autofixes can combine with each other. I think it would be better for editor plugins to run multiple passes themselves if they need to apply fixes individually. (Alternatively, if the editor only runs a single pass, you can run the editor integration multiple times if you need the formatting to be exactly correct.)

**Comment by UziTech** [comment] 2018-02-27 13:52
Thanks for your help. I got it working by passing fix then diffing the output.
