### ISSUE TITLE
sort-imports: support ordering relative imports vs package imports

### ISSUE THREAD

**Issue by jonnyreeves** [eslint/eslint#5583] opened 2016-03-15 14:21 UTC
## Proposal
Either extend the existing `sort-imports` rule, or create a new rule which will enforce ordering / separation of relative imports vs package imports.

This is a stylistic rule and provides developer the means to keep clear separation between groups of imports helping visually seperate external dependencies (eg: React) from internal code.

#### Good
```js
import moment from 'moment';
import React, { PropTypes } from 'react';
import styles from './ArchiveDetails.css';
import { SHOWN, HIDDEN } from '../actions/error';
```

#### Bad
```js
import moment from 'moment';
import styles from './ArchiveDetails.css';
import React, { PropTypes } from 'react';
import { SHOWN, HIDDEN } from '../actions/error';
```

####  Why the rule should be in the core instead of creating a custom rule.
Feel like a logical extension of the `sort-imports` rule; although happy to be informed otherwise.

####  Are you willing to create the rule yourself?
Possibly; although I don't have a lot of free time to dedicate to the cause :(

**Comment by platinumazure** [comment] 2016-03-16 22:09
@eslint/eslint-team Should this be an enhancement or a feature (i.e., new rule)? Or should this not be included in core?

**Comment by ilyavolodin** [comment] 2016-03-16 22:58
If anything, this should probably be an option for `sort-imports`, not a new rule.

**Comment by nzakas** [comment] 2016-03-17 16:32
I don't see enough of a description here to make a call. What should be allowed? What should be flagged?

**Comment by jonnyreeves** [comment] 2016-03-18 10:08
@nzakas - appologies; I've updated the overview above to include a Good / Bad example.  This is the first ticket I have raised against eslint so please let me know if there's more detail I need to include.

**Comment by nzakas** [comment] 2016-03-19 16:08
Thanks, that's better. It would have to be in `sort-imports` if anything. 

I'm not sure, though, that we can do this quite yet. There's no way to know if these are the only two ways to reference module files. It's likely you'll be able to do this in browsers:

```js
import foo from "https://example.com/foo.js";
```

How would that fit into your suggestion?

**Comment by dmitry-zaets** [comment] 2016-03-31 09:48
>`import foo from "https://example.com/foo.js";`
This should go first one, before `import moment from 'moment';`

**Comment by AaronHarris** [comment] 2016-05-04 08:44
It is worth noting this enhancement can also be found in the `absolute-first` option in [import/imports-first](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/imports-first.md), however currently sort-imports interferes with that rule.

**Comment by nzakas** [comment] 2016-05-04 21:00
@AaronHarris the problem is that browsers will not require a dot as the first character to load a relative path file. For instance, this is ambiguous without knowing whether it's running in Node.js or the browser:

```js
import { foo } from "project/foo.js";
```

In Node.js, presumably this would be the `project` package and `foo.js` is inside of it, but in the browser, `project` is a subdirectory.

That sort of ambiguity makes it hard to know for sure how to categorize that import.

**Comment by jfmengels** [comment] 2016-05-12 13:40
It should be noted that such a rule exists in `eslint-plugin-import`, under the [`order`](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/order.md) rule.

It can be a bit tricky in some cases when users 
> For instance, this is ambiguous without knowing whether it's running in Node.js or the browser:
`import { foo } from "project/foo.js";`

Or used with Webpack or some other tool to resolve local modules from a given source path. This is handled by the plugin.
(cc @benmosher)

**Comment by ilyavolodin** [comment] 2016-05-12 15:15
Re-reading this issue. I think this should go into `eslint-plugin-import` instead of the core. And it seem this rule already exists there. @eslint/eslint-team anyone feels differently?

**Comment by alberto** [comment] 2016-05-12 15:34
I agree

**Comment by mikesherov** [comment] 2016-05-12 16:28
Agreed.

**Comment by AaronHarris** [comment] 2016-05-15 11:31
Yes, after my comment above I found out about [import/order](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/order.md), and import module in general is probably better suited to handle nuances of a yet-unsupported-without-babel pattern.

My only response to the above was, shouldn't the `env: { node: true }` or `env: { browser: true` in .eslintrc give a clue as to whether one is in Node or the Browser?

**Comment by nzakas** [comment] 2016-05-15 19:11
Closing as consensus is that this is better in a plugin.

**Closed by nzakas** 2016-05-15 19:11 UTC
Labels: enhancement, evaluating, rule

**Comment by jonnyreeves** [comment] 2016-05-15 19:32
+1. Thanks again for all your contributions to the javascript community.

**Comment by verekia** [comment] 2016-09-30 08:26
For those who are wondering how to combine `eslint-plugin-import` with alphabetical order like `sort-import` does, this is not possible yet with the plugin. An [issue](https://github.com/benmosher/eslint-plugin-import/issues/389) is open on the plugin as a feature suggestion. So unfortunately, we can't currently both lint for alphabetical order and import type (absolute/relative).

**Comment by 1297947244** [comment] 2017-08-15 10:31
good
