### ISSUE TITLE
Feature Request: interpolation in configuration

### ISSUE THREAD

**Issue by wmertens** [eslint/eslint#9121] opened 2017-08-17 14:03 UTC
Using ESLint v4.4.1

I encountered https://github.com/benmosher/eslint-plugin-import/issues/772 which is due to putting a relative path in eslint configuration, and the plugin having no information to correctly resolve it to an absolute path.

It would be great if in the configuration, one could somehow interpolate the configuration file's absolute path, e.g. with `"{{__dirname}}/path/to/file"` or something similar.

Another option would be to use rich objects to describe certain configuration types: `config: {type: "PATH", value: "./path/to/file"}`

**Comment by not-an-aardvark** [comment] 2017-08-17 17:29
Thanks for the proposal. However, I'm confused about what problem this is solving, and what the proposal is. Could you provide more details about what you're trying to do?

**Comment by wmertens** [comment] 2017-08-18 12:06
The problem is that in the eslint configuration, path values cannot
reliably be passed as relative paths from the configuration file.

There is at least one plugin that needs a path to a file, and it is most
convenient to pass that path as a relative path from the directory where
the config file resides.

The workaround is to create the eslint configuration as a js file and use
`require.resolve` to get the absolute path, but that's not very
developer-friendly.

I propose two ways to tackle this: Either create an interpolation mechanism
in eslint configuration, with some values that can be used, including the
path to the script; or treating paths as primary types in the
configuration, using object notation with {type, value} to encode them (and
maybe other types) as JSON objects.

**Comment by not-an-aardvark** [comment] 2017-08-19 07:03
Thanks for clarifying.

Hmm, I'm not sure I like either of the two solutions you proposed. Looking at the issue you linked, it seems like the relative path is used in `context.settings`. It seems like they would add unnecessary complexity to config files to add a new first-class "path" type or modify the string that the user provides, when the explicit goal of `context.settings` is to allow users to provide arbitrary plugin-specific data that ESLint core doesn't attach any semantic meaning to.

My recommendation would be to just use `.eslintrc.js` files for this purpose.

**Comment by wmertens** [comment] 2017-08-19 10:18
How about a third option: Providing information about the file location of
the settings, so that plugins can do their own path resolution?

Maybe an object that has the same shape as the settings, but instead of the
leaf node values is has the location of the file that provided the setting
value.

Would that be hard to do? I imagine it also makes for nicer configuration
errors.

**Comment by not-an-aardvark** [comment] 2017-11-03 20:54
Thanks for your interest in improving ESLint. Unfortunately, it looks like this issue didn't get consensus from the team, so I'm closing it. We define [consensus](http://eslint.org/docs/maintainer-guide/issues.html#consensus) as having three :+1:s from team members, as well as a team member willing to champion the proposal. This is a high bar by design -- we can't realistically accept and maintain every feature request in the long term, so we only accept feature requests which are useful enough that there is consensus among the team that they're worth adding.

**Closed by not-an-aardvark** 2017-11-03 20:54 UTC
Labels: core, enhancement, evaluating

**Comment by wmertens** [comment] 2017-11-04 08:00
I think the thumbs-up voting is a great idea, but how can you know that a proposal is seen by the entire core team? I am specifically asking about the file location proposal which is a comment.

Should I re-propose it as an issue?

Maybe the rule should be to get at least x votes and 3 of those should be 👍
