### ISSUE TITLE
cannot assign variables from destructure with camelCase rule `ignoreDestructure` set to true

### ISSUE THREAD

**Issue by sentilesdal** [eslint/eslint#12502] opened 2019-10-28 19:07 UTC
I am reopening #11226 as suggested at the end of that issue to bring this to light again.  The problem can be seen [here](https://eslint.org/demo#eyJ0ZXh0IjoiLyogZXNsaW50IGNhbWVsY2FzZTogW2Vycm9yLCB7IGlnbm9yZURlc3RydWN0dXJpbmc6IHRydWUsIHByb3BlcnRpZXM6IFwibmV2ZXJcIiB9XSAqL1xuXG5jb25zdCBhbm90aGVyRnVuYyA9ICh0ZXN0KT0+IG51bGw7XG5cbmNvbnN0IFNlY3Rpb25Gb3JtYXR0ZWRUZXh0ID0gKHsgZmllbGRfZm9ybWF0dGVkX3RleHQgfSkgPT4ge1xuICBjb25zb2xlLmxvZyhmaWVsZF9mb3JtYXR0ZWRfdGV4dCk7XG4gIFxuICBjb25zdCBhbm90aGVyVmFyID0gYW5vdGhlckZ1bmMoZmllbGRfZm9ybWF0dGVkX3RleHQpO1xuXG4gIGNvbnN0IHVuZGVyc2NvcmVPbk9iamVjdFByb3BlcnR5ID0ge1xuICAgIGFiYzogZmllbGRfZm9ybWF0dGVkX3RleHRcbiAgfTtcbiAgXG4gIGNvbnN0IG15VmFyID0gZmllbGRfZm9ybWF0dGVkX3RleHQgKyAnYWJjJztcblxuICByZXR1cm4gZmllbGRfZm9ybWF0dGVkX3RleHQ7XG59O1xuZXhwb3J0IGRlZmF1bHQgU2VjdGlvbkZvcm1hdHRlZFRleHQ7Iiwib3B0aW9ucyI6eyJwYXJzZXJPcHRpb25zIjp7ImVjbWFWZXJzaW9uIjo2LCJzb3VyY2VUeXBlIjoibW9kdWxlIiwiZWNtYUZlYXR1cmVzIjp7fX0sInJ1bGVzIjp7ImNhbWVsY2FzZSI6Mn0sImVudiI6e319fQ==).  Basically though you cannot assign any variable that is not camel cased from a destructured statement:
```
  /* eslint camelcase: [error, { ignoreDestructuring: true, properties: "never" }] */

  const { field_formatted_text } = someObject;

  const underscoreOnObjectProperty = {
    abc: field_formatted_text . // this is fine
  };
  
  // throws: Identifier 'field_formatted_text' is not camel case
  const myVar = field_formatted_text + 'abc';
```

There is an obvious solution to just rename the variable when it's destructured:
```
  const { field_formatted_test: fieldFormattedText } = someObject;
```

However, this is annoying to have to do and you may also lose semantic meaning from the different cases (i.e. variables returned from an api).  

Thanks in advance!

**Comment by sentilesdal** [comment] 2019-10-28 19:09
could a member add a comment to #11226 linking to this issue? That issue has been locked.

**Comment by mdjermanovic** [comment] 2019-10-28 19:44
Hi @sentilesdal, thanks for the issue.

This also looks like a duplicate of #11939. 

I think that the option works as intended, as described in [this comment](https://github.com/eslint/eslint/issues/11939#issuecomment-528141058), but it might be good to improve the documentation to further clarify this option.

**Comment by sentilesdal** [comment] 2019-10-28 20:48
@mdjermanovic thanks for the quick reply.  To me it seems that it's not a matter of documentation.  As people have pointed out in #11939 and #11226 and #11228, and now this issue, is that the _desired_ behavior for this rule is such that you can use a variable from a destructured statement however you'd like.  The spirit of the rule seems to be that you shouldn't be able to create _new_ variables that aren't camelCase and `ignoreDestructured` should opt you out of that completely.

**Comment by mdjermanovic** [comment] 2019-10-28 21:58
I believe it would be better to open a 'Rule change request' issue with a backward-compatible enhancement proposal. 

Destructuring creates new variables that might be used many times in the rest of the code. A change to allow underscores in this case (instead of enforcing the user to 'rename variables' in the destructuring pattern) without opt-in might be undesirable for some users.

**Comment by DMR-coding** [comment] 2019-11-08 00:57
Hi, I'm fighting this issue right now in migrating a codebase that extensively destructures external API returns, and I want to check in on the status of this before making a closely-related report.

I'm unclear on what actually IS allowed here-- @mdjermanovic, could you clarify what distinction you're drawing between the intended allowed behavior and those shown here? It seems extremely counterintuitive to me that it is explicitly permitted to _create_ this variable, but not to later access it, and I want to make sure I understand why.

**Comment by kaicataldo** [comment] 2019-11-10 00:14
@DMR-coding The options for this rule currently only toggles the behavior for when new variables are created. This means that other references to the variable aren’t affected, which leads to the somewhat confusing behavior of the rule not warning on, say, destructured assignments, but will then warn when the variable is actually used.

**Comment by mdjermanovic** [comment] 2019-11-10 20:19
> @DMR-coding The options for this rule currently only toggles the behavior for when new variables are created. This means that other references to the variable aren’t affected, which leads to the somewhat confusing behavior of the rule not warning on, say, destructured assignments, but will then warn when the variable is actually used.

Just to add that the option was designed in particular to support two use cases described in [#9807(comment)](https://github.com/eslint/eslint/issues/9807#issuecomment-355452238)

**Closed** 2019-12-11 22:43 UTC
Labels: bug, evaluating, rule
