### ISSUE TITLE
Fix is invalid

### ISSUE THREAD

**Issue by livelyPeng** [eslint/eslint#13868] opened 2020-11-20 07:09 UTC
"lint-fix": "eslint --fix --ext .js,.jsx,.ts,.tsx src",

"eslint": "^7.13.0",
    "eslint-config-prettier": "^6.15.0",
    "eslint-friendly-formatter": "^4.0.0",
    "eslint-loader": "^4.0.2",
    "eslint-plugin-prettier": "^3.1.4",
    "eslint-plugin-react": "^7.21.5",

**Comment by livelyPeng** [comment] 2020-11-23 01:24
![image](https://user-images.githubusercontent.com/32978177/99922830-802c3c80-2d6d-11eb-8867-5d886cf771ea.png)
![image](https://user-images.githubusercontent.com/32978177/99922834-891d0e00-2d6d-11eb-89db-4b4d5ac20fcc.png)
![image](https://user-images.githubusercontent.com/32978177/99922842-933f0c80-2d6d-11eb-98e2-f50876537b9f.png)

Is there a problem?

Invalid fix

**Comment by mdjermanovic** [comment] 2020-11-24 01:39
> Is there a problem?
> 
> Invalid fix

Can you please provide more details on this. Are you getting an error when you run the `lint-fix` script, or is there a source code that seems incorrectly fixed? Filling out our [bug report template](https://github.com/eslint/eslint/blob/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md) would be most helpful.

**Comment by livelyPeng** [comment] 2020-11-24 01:55
lint-fix is equivalent to lint, To do the query syntax error，lint--fix does not fix errors。

**Comment by livelyPeng** [comment] 2020-11-24 02:03
![image](https://user-images.githubusercontent.com/32978177/100036945-20509700-2e3c-11eb-8663-8e0ae213ac12.png)

===

![image](https://user-images.githubusercontent.com/32978177/100036992-3a8a7500-2e3c-11eb-8347-75ac9e6d0009.png)

**Comment by livelyPeng** [comment] 2020-11-24 02:04
![Uploading HRYK8_9KC7H5{OY2VUL3B@W.png…]()

**Comment by livelyPeng** [comment] 2020-11-24 02:05
D:\webAmbient\node\node.exe D:\webAmbient\node\node_modules\npm\bin\npm-cli.js run lint-fix --scripts-prepend-node-path=auto

> react-seed@0.1.0 lint-fix E:\react-ts-seed
> eslint --fix --ext .js,.jsx,.ts,.tsx src


E:\react-ts-seed\src\view\homeModule\component\Header.tsx
  45:38  warning  'index' is defined but never used  @typescript-eslint/no-unused-vars

E:\react-ts-seed\src\view\homeModule\services\index.ts
  5:10  warning  'par' is defined but never used  @typescript-eslint/no-unused-vars

✖ 2 problems (0 errors, 2 warnings)

**Comment by livelyPeng** [comment] 2020-11-24 02:05
lint-fix is equivalent to lint, To do the query syntax error，lint--fix does not fix errors。

**Comment by livelyPeng** [comment] 2020-11-24 02:06
"scripts": {
    "start": "webpack serve --inline --progress --config build/webpack.dev.conf.js",
    "dev": "npm run start",
    "lint": "eslint --ext .js,.jsx,.ts,.tsx src",
    "lint-fix": "eslint --fix --ext .js,.jsx,.ts,.tsx src",
    "build": "webpack --config build/webpack.prod.conf.js"
  },

**Comment by mdjermanovic** [comment] 2020-11-24 02:22
> lint-fix is equivalent to lint

Some problems are not auto-fixable. `eslint --fix` will automatically fix those that can be fixed and report the remaining ones.

**Comment by livelyPeng** [comment] 2020-11-24 02:27
eslint --fix ，what problems can be fixed?

**Comment by livelyPeng** [comment] 2020-11-24 02:27
what problems can eslint -- fix solve

**Comment by mdjermanovic** [comment] 2020-11-24 02:37
> what problems can eslint -- fix solve

That depends on the rules that report the problems. If the rule provides a fix, ESLint will apply it.

For instance, [no-extra-boolean-cast](https://eslint.org/docs/rules/no-extra-boolean-cast) is fixable.

On the other hand, [no-invalid-regexp](https://eslint.org/docs/rules/no-invalid-regexp) isn't since it's impossible to know what was the author's intention, so user has to fix the problem manually.

**Comment by livelyPeng** [comment] 2020-11-24 02:39
thank you. I think I understand！

**Comment by mdjermanovic** [comment] 2020-11-24 06:12
Closing this issue since it's clarified that ESLint works as intended.

**Closed by mdjermanovic** 2020-11-24 06:12 UTC
Labels: works as intended
