### ISSUE TITLE
TypeError: Cannot read property 'value' of null

### ISSUE THREAD

**Issue by mfurniss** [eslint/eslint#13542] opened 2020-07-31 19:14 UTC
**Tell us about your environment**

Node version: v12.13.1
npm version: v6.14.5
Local ESLint version: v7.5.0 (Currently used)
Global ESLint version: Not found

**What parser (default, Babel-ESLint, etc.) are you using?**
babel-eslint

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
{
    "extends": "airbnb",
    "parser": "babel-eslint",
    "env": {
        "browser": true,
        "jest": true
    },
    "settings": {
        "import/resolver": {
            "webpack": {
                "config": "webpack.config.js"
            }
        }
    },
    "rules": {
        "no-useless-rename": 0,
        "function-paren-newline": 0,
        "import/no-cycle": 0,
        "react/jsx-filename-extension": [1, { "extensions": [".js", ".jsx"] }],
        "react/prefer-stateless-function": 0,
        "react/destructuring-assignment": 0,
        "jsx-a11y/anchor-is-valid": [ "error", {
            "components": [ "Link" ],
            "specialLink": [ "to", "hrefLeft", "hrefRight" ],
            "aspects": [ "noHref", "invalidHref", "preferButton" ]
        }],
        "no-console": "off",
        "no-use-before-define": "off",
        "jsx-a11y/click-events-have-key-events": "off",
        "jsx-a11y/label-has-for": "off",
        "prefer-destructuring": ["error", {
            "array": false,
            "object": true
        }, {
            "enforceForRenamedProperties": false
        }]
    }
}
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
import { ApolloLink } from 'apollo-link';
import { store } from 'Lib';

const authLink = new ApolloLink((operation, forward) => {
  const token = store.getItem('token');
  if (token) {
    operation.setContext({
      headers: {
        Authorization: `Bearer ${token}`,
      },
    });
  }
  return forward(operation);
});

export default authLink;
```

```bash
eslint ./src --cache
```

**What did you expect to happen?**
Should pass all lint checks.

**What actually happened? Please include the actual, raw output from ESLint.**
yarn lint
yarn run v1.22.4
$ eslint ./src --cache

Oops! Something went wrong! :(

ESLint: 7.5.0

TypeError: Cannot read property 'value' of null
Occurred while linting /Users/matt/Workspace/cby-shopify-channel-app/src/apollo/authLink.js:9
    at checkSpacingBefore (/Users/matt/Workspace/cby-shopify-channel-app/node_modules/eslint/lib/rules/template-curly-spacing.js:52:24)
    at TemplateElement (/Users/matt/Workspace/cby-shopify-channel-app/node_modules/eslint/lib/rules/template-curly-spacing.js:136:17)
    at /Users/matt/Workspace/cby-shopify-channel-app/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/Users/matt/Workspace/cby-shopify-channel-app/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/Users/matt/Workspace/cby-shopify-channel-app/node_modules/eslint/lib/linter/node-event-generator.js:254:26)
    at NodeEventGenerator.applySelectors (/Users/matt/Workspace/cby-shopify-channel-app/node_modules/eslint/lib/linter/node-event-generator.js:283:22)
    at NodeEventGenerator.enterNode (/Users/matt/Workspace/cby-shopify-channel-app/node_modules/eslint/lib/linter/node-event-generator.js:297:14)
    at CodePathAnalyzer.enterNode (/Users/matt/Workspace/cby-shopify-channel-app/node_modules/eslint/lib/linter/code-path-analysis/code-path-analyzer.js:673:23)
    at /Users/matt/Workspace/cby-shopify-channel-app/node_modules/eslint/lib/linter/linter.js:949:32
    at Array.forEach (<anonymous>)
    at runRules (/Users/matt/Workspace/cby-shopify-channel-app/node_modules/eslint/lib/linter/linter.js:944:15)
    at Linter._verifyWithoutProcessors (/Users/matt/Workspace/cby-shopify-channel-app/node_modules/eslint/lib/linter/linter.js:1170:31)
    at Linter._verifyWithConfigArray (/Users/matt/Workspace/cby-shopify-channel-app/node_modules/eslint/lib/linter/linter.js:1268:21)
    at Linter.verify (/Users/matt/Workspace/cby-shopify-channel-app/node_modules/eslint/lib/linter/linter.js:1223:25)
    at Linter.verifyAndFix (/Users/matt/Workspace/cby-shopify-channel-app/node_modules/eslint/lib/linter/linter.js:1413:29)
error Command failed with exit code 2.

**Comment by mdjermanovic** [comment] 2020-07-31 20:21
Hi @mfurniss, thanks for the bug report!

I can't reproduce this with `babel-eslint` v10.1.0, which version are you using?

There is a known bug in v10.1.0 with template literals in dynamic imports (``import(`...`)``) but the code you provided doesn't have those.

**Comment by mfurniss** [comment] 2020-07-31 21:26
Hi @mdjermanovic ,

I am using babel-eslint v10.1.0.

**Comment by mdjermanovic** [comment] 2020-07-31 21:37
> If it helps, I'm using the same eslint config in vscode with dbaeumer.vscode-eslint without issue.

It could be that there are no errors in the "Problems" tab, but there is the same `Cannot read property 'value' of null` in the "Output" tab (select ESLint from the list on the right side).

**Comment by mfurniss** [comment] 2020-07-31 23:13
@mdjermanovic Thanks for the tip. Yes, I am seeing the same error in the VSCode ESLint ouput.

`[Info  - 4:09:39 PM] ESLint server stopped.
[Info  - 4:09:39 PM] ESLint server running in node v12.8.1
[Info  - 4:09:39 PM] ESLint server is running.
[Info  - 4:09:40 PM] ESLint library loaded from: /Users/matt/Workspace/cby-shopify-channel-app/node_modules/eslint/lib/api.js
[Info  - 4:10:18 PM] Cannot read property 'value' of null Occurred while linting /Users/matt/Workspace/cby-shopify-channel-app/src/apollo/errorLink.js:35
[Info  - 4:10:21 PM] Cannot read property 'value' of null Occurred while linting /Users/matt/Workspace/cby-shopify-channel-app/src/apollo/authLink.js:9`

**Comment by mfurniss** [comment] 2020-07-31 23:16
The lines are code in the two files which cause the error are similar.

```Authorization: `Bearer ${token}`,```

and

```description: `errorLink networkError: ${networkError}`,```

Something to do with the template literals and curly braces?

**Comment by kaicataldo** [comment] 2020-08-01 00:28
This is an issue with `babel-eslint`. It should be fixed and released in the latest release (under the new package name `@babel/eslint-parser`). Please see [here](https://babeljs.io/blog/2020/07/13/the-state-of-babel-eslint) for more information.

If this isn't fixed in the latest release, please make an issue in https://github.com/babel/babel. Thanks!

**Closed** 2020-08-01 00:28 UTC
Labels: bug, evaluating, rule

**Comment by mfurniss** [comment] 2020-08-01 00:42
@kaicataldo @mdjermanovic Updating to @babel/eslint-parser fixed the issue for me. Thanks for your help!

**Comment by kaicataldo** [comment] 2020-08-01 01:22
Yay! Glad to hear you were able to resolve it.

**Comment by marcinczenko** [comment] 2020-11-14 17:26
I had a similar problem with `standards` and indeed using `@babel/eslint-parser` helps. But integration with VSCode is not so happy anymore and I keep getting `Parsing error: No Babel config file detected...`. I am using `chenxsan.vscode-standardjs` extension for VSCode `v1.4.0`. 

I am not sure where shall I look for help. Here or with standardjs?
