### ISSUE TITLE
eslint still processing files in `node_modules` despite not showing any linting errors for them?

### ISSUE THREAD

**Issue by vinsonchuong** [eslint/eslint#5739] opened 2016-03-30 20:44 UTC
**What version of ESLint are you using?**
2.5.3

**What parser (default, Babel-ESLint, etc.) are you using?**
default

**Please show your full configuration:**
```json
{
  "rules": {
    "no-debugger": 2
  }
}
```
**What did you do? Please include the actual source code causing the issue.**
See the repo https://github.com/vinsonchuong/test-eslint-ignore for the full source code.
```sh
git clone https://github.com/vinsonchuong/test-eslint-ignore
cd test-eslint-ignore
npm install

echo 'debugger;' > node_modules/foo.js

time ./node_modules/.bin/eslint .
time ./node_modules/.bin/eslint index.js
time ./node_modules/.bin/eslint node_modules index.js
```

**What did you expect to happen?**
I expected `eslint .` to run as quickly as `eslint index.js` as the `node_modules` directory should be ignored.

**What actually happened? Please include the actual, raw output from ESLint.**
```
/home/vinsonchuong/projects/test-eslint-ignore/index.js
>> time ./node_modules/.bin/eslint .

  1:1  error  Unexpected 'debugger' statement  no-debugger

✖ 1 problem (1 error, 0 warnings)

node_modules/.bin/eslint .  0.99s user 0.05s system 100% cpu 1.028 total
```

```
>> time node_modules/.bin/eslint index.js

/home/vinsonchuong/projects/test-eslint-ignore/index.js
  1:1  error  Unexpected 'debugger' statement  no-debugger

✖ 1 problem (1 error, 0 warnings)

node_modules/.bin/eslint index.js  0.28s user 0.02s system 103% cpu 0.289 total
```

Despite the `node_modules` directory not generating any linting errors, it still looks like `eslint` is processing the files in `node_modules`.

**Comment by btmills** [comment] 2016-03-30 21:16
This looks to be a duplicate of #5679. What's happening is when you specify `index.js`, ESLint only looks for `index.js`, but when you specify `.` as the path, it traverses through the current directory, including `node_modules`, before it then excludes everything under `node_modules` from linting, so it's the traversal that's taking extra time. #5679 would provide ignore information to the traversal step so that it could proactively ignore the entire `node_modules` directory. It's accepted and just waiting for someone to implement it. @vinsonchuong we'd welcome a PR if you're interested!

**Closed by btmills** 2016-03-30 21:16 UTC
Labels: triage
