### ISSUE TITLE
Indentation for 'const' using 4 spaces

### ISSUE THREAD

**Issue by ragzovskii** [eslint/eslint#9566] opened 2017-11-02 12:56 UTC
**Tell us about your environment**

* **ESLint Version:** 4.9.0
* **Node Version:** 8.4.0
* **npm Version:** 5.3.0

**What parser (default, Babel-ESLint, etc.) are you using?** default, I assume

**Please show your full configuration:**

 I want to achieve this result with 4 spaces indentation, which  currently results in erorr
```js
function a() {
    const id    = 1,
          value = 2;
}
```
Basically, 6 spaces for multiline const declaration.
In my case it would be handy to use either 1.5 level of indentation, or maybe some way to override indentation settings, smth like:
```
// Option A
"indent": ["error", 4, {
    "VariableDeclarator": {
        "const": 1.5
    }
}]

// Option B
"indent": ["error", 4, {
    "VariableDeclarator": {
        "const": {
            "level": 2, // indentation level
            "indent": 3 // amount of spaces
        }
    }
}]

// Option C
"indent": ["error", 4, {
    "VariableDeclarator": {
        "const": "6s" // shorthand for '6 spaces'
    }
}]

```

I assume that one of the options would be to use rule such as:
```
"indent": ["error", 2, {
    "VariableDeclarator": {
        "const": 3,
        "let": 2,
        "var": 2
    },
    // every property listed in rule documentation, specifying 2 levels of indentation:
    "ArrayExpression": 2,
    ...
}]
but it appears hacky.

I would like even more flexible config, in other words.
Thanks.

**Comment by ragzovskii** [comment] 2017-11-02 13:02
Tried with 2 spaces indent, it doesn't work as expected. So no suitable solution so far

**Comment by not-an-aardvark** [comment] 2017-11-02 16:26
Closing as a duplicate of https://github.com/eslint/eslint/issues/8976

**Closed by not-an-aardvark** 2017-11-02 16:26 UTC
Labels: triage
