### ISSUE TITLE
brace-style when `if` does not need braces but `else` does

### ISSUE THREAD

**Issue by andy-hanson** [eslint/eslint#2366] opened 2015-04-24 04:28 UTC
## Here's what I did

Create a new directory.
Create `file.js` with the text:

	var f
	if (true)
		f = function() {
			return 1
		}
	else {
		var x = 1
		f = x
	}

Create `package.json` with the text:

	{
		"eslintConfig": {
			"rules": {
				"brace-style": [ 1, "1tbs", { "allowSingleLine": true } ],
				"curly": [ 1, "multi" ],
				"indent": [ 1, "tab" ],
				"no-constant-condition": 0,
				"no-unused-vars": 0,
				"semi": 0,
				"strict": 0
			}
		}
	}

Then do:

	npm install eslint/eslint
	node_modules/eslint/bin/eslint.js file.js

## Here's what happened

	file.js
	  6:5  warning  Closing curly brace does not appear on the same line as the subsequent block  brace-style

	✖ 1 problem (0 errors, 1 warning)

## Here's what I expected to happen

I don't think this should be considered an error.
If the `if` statement had braces I would want the `else` to match with them.
But only the `function` has braces, and it would look silly to put `else` on the same line as the end of the function.

**Comment by ilyavolodin** [comment] 2015-04-24 13:48
Can you provide console output as well as version of ESLint you are using?

**Comment by andy-hanson** [comment] 2015-04-24 18:01
eslint installed by `npm install eslint/eslint`.
I tested it with this package.json:

	{
		"eslintConfig": {
			"rules": {
				"brace-style": [ 1, "1tbs", { "allowSingleLine": true } ],
				"curly": [ 1, "multi" ],
				"indent": [ 1, "tab" ],
				"no-constant-condition": 0,
				"no-unused-vars": 0,
				"semi": 0,
				"strict": 0
			}
		}
	}

And the console output is:

	file.js
	  6:5  warning  Closing curly brace does not appear on the same line as the subsequent block  brace-style

	✖ 1 problem (0 errors, 1 warning)

**Comment by nzakas** [comment] 2015-04-25 01:55
I'm sorry, I don't quite understand what you're asking. Can you please phase your request in this format:

1. Here's what I did
1. Here's what happened
1. Here's what I expected to happen

Thanks.

**Comment by lo1tuma** [comment] 2015-04-25 22:03
Looks like a duplicate of #1739.

**Comment by nzakas** [comment] 2015-04-26 00:52
Good call

**Closed by nzakas** 2015-04-26 00:52 UTC
Labels: bug, rule

**Comment by andy-hanson** [comment] 2015-07-12 21:50
I'm now experiencing problems with the same package.json with this code:

	for (var key in { a: 1, b: 2 })
		if (key === 'a')
			console.log(1)
		else {
			console.log(2)
			console.log(3)
		}

I see:

	file.js
	  4:1  warning  Expected indentation of 0 characters  indent
	  5:2  warning  Expected indentation of 1 characters  indent
	  6:2  warning  Expected indentation of 1 characters  indent
	  7:1  warning  Expected indentation of 0 characters  indent
