### ISSUE TITLE
--fix converts to backtick, then valid-typeof reports error

### ISSUE THREAD

**Issue by barbalex** [eslint/eslint#7166] opened 2016-09-16 07:21 UTC
**Tell us about your environment**

* **ESLint Version:** 3.5.0
* **Node Version:** 6.5.0
* **npm Version:** 3.10.3

**What parser (default, Babel-ESLint, etc.) are you using?** "babel-eslint": "6.1.2"

**Please show your full configuration:**
.eslintrc.json:

```json
{
  "parser": "babel-eslint",
  "extends": "airbnb",
  "env": {
    "node": true
  },
  "globals": {
    "emit": true,
    "doc": true
  },
  "plugins": [
      "react"
  ],
  "rules": {
    "react/require-extension": "off",
    "linebreak-style": ["error", "windows"],
    "react/jsx-sort-props": 0,
    "react/jsx-no-bind": 0,
    "comma-dangle": 0,
    "no-use-before-define": 0,
    "consistent-return": 0,
    "semi": [2, "never"],
    "quotes": ["error", "backtick"],
    "strict": 0,
    "max-len": ["error", 120, 2, {"ignoreUrls": true}],
    "no-param-reassign": ["error", { "props": false }]
  }
}
```

package.json:
```json
{
  "name": "apflora",
  "version": "1.0.1",
  "description": "Aktionsplan Flora Kt. Zürich Backend",
  "main": "server.js",
  "dependencies": {
    "ampersand-app": "^2.0.0",
    "async": "2.0.1",
    "dateformat": "1.0.12",
    "hapi": "15.0.3",
    "hapi-node-postgres": "4.0.1",
    "inert": "4.0.2",
    "json2csv": "3.6.3",
    "json2xls": "0.1.2",
    "lodash": "4.15.0",
    "pg": "6.1.0",
    "pg-promise": "^5.3.3",
    "request": "2.74.0",
    "underscore": "1.8.3"
  },
  "devDependencies": {
    "babel-eslint": "6.1.2",
    "code": "3.0.2",
    "del": "2.2.2",
    "eslint": "3.5.0",
    "eslint-config-airbnb": "11.1.0",
    "eslint-plugin-import": "1.15.0",
    "eslint-plugin-jsx-a11y": "2.2.2",
    "eslint-plugin-react": "6.2.1",
    "gulp": "3.9.1",
    "gulp-sftp": "0.1.5",
    "lab": "11.0.1",
    "require-dir": "0.3.0",
    "run-sequence": "1.2.2"
  },
  "scripts": {
    "start": "npm test && node startServer.js",
    "startWithoutTests": "node startServer.js",
    "predeploy": "gulp prod_clean_dist",
    "deploy": "gulp prod_copy",
    "postdeploy": "gulp prod_sftp",
    "test": "eslint src --fix && lab",
    "yolo": "npm run deploy"
  },
  "repository": {
    "type": "git",
    "url": "git://github.com/FNSKtZH/apflora_api.git"
  },
  "keywords": [
    "apflora",
    "aktionsplan",
    "flora",
    "species",
    "conservation"
  ],
  "author": "Alexander Gabriel",
  "license": "ISC",
  "bugs": {
    "url": "https://github.com/FNSKtZH/apflora/issues"
  },
  "homepage": "https://github.com/FNSKtZH/apflora"
}

```

**What did you do? Please include the actual source code causing the issue.**

I added

`"quotes": ["error", "backtick"]`

to .eslintrc and

`eslint src --fix` to the scripts in package.json

after reading [this](https://ponyfoo.com/articles/template-literals-strictly-better-strings)

**What did you expect to happen?**

`'` to be replaced by backtips ONLY where applicable (as like: not in `'use strict'`).
OR: Other rules not to complain about where `--fix` sets backtips.

**What actually happened? Please include the actual, raw output from ESLint.**

this code:

```
'use strict'

module.exports = (string) => {
  if (string && typeof string === `string`) {
    // does something
  }
}
```

produced this error:

    C:\Users\alex\apflora_api\src\removeKmlNogoStrings.js
      10:35   error  Typeof comparisons should be to string literals  valid-typeof

**Comment by not-an-aardvark** [comment] 2016-09-16 15:04
It seems like the bug here is that `valid-typeof` doesn't allow comparisons to template literals. `typeof foo === \`string\`` should not cause an error to be reported.

**Comment by platinumazure** [comment] 2016-09-16 16:23
Confirmed in online demo with this repro:

```js
/* eslint valid-typeof: ["error", { "requireStringLiterals": true }] */
/* eslint-env es6 */

typeof foo === `string`;
```

I do think this should be fixed in valid-typeof since template literals are string literals too. We would just need to check that there are no interpolations and that the content of the template literal is equal to one of the allowed string values.

**Comment by platinumazure** [comment] 2016-09-16 16:35
@barbalex Can you please confirm whether or not the directive `'use strict';` was also improperly converted to backticks/template literal?

**Comment by barbalex** [comment] 2016-09-16 17:16
No, that was correctly left as 'use strict'

Am 16.09.2016 6:35 nachm. schrieb "Kevin Partington" <
notifications@github.com>:

**Comment by not-an-aardvark** [comment] 2016-09-16 17:40
See #7168

**Closed** 2016-09-19 18:21 UTC
Labels: accepted, bug, rule
