### ISSUE TITLE
error in no-useless-constructor

### ISSUE THREAD

**Issue by TrejGun** [eslint/eslint#5426] opened 2016-02-28 10:58 UTC
**What version of ESLint are you using?**
2.2.0

**What configuration and parser (Espree, Babel-ESLint, etc.) are you using?**
babel-eslint

**What did you do? Please include the actual source code causing the issue.**
```js
class A {}

class B extends A {
	constructor() {
		super(...arguments);
	}
}
```

**What did you expect to happen?**
eslint will exit with code 0

**What actually happened? Please include the actual, raw output from ESLint.**
```
...eslint/lib/rules/no-useless-constructor.js:33
                ctorParams[index].type === "RestElement" &&
                                 ^

TypeError: Cannot read property 'type' of undefined
    at ...eslint/lib/rules/no-useless-constructor.js:33:34
    at Array.every (native)
    at isRedundantSuperCall (...eslint/lib/rules/no-useless-constructor.js:29:45)
    at EventEmitter.checkForConstructor (...eslint/lib/rules/no-useless-constructor.js:52:46)
    at emitOne (events.js:95:20)
    at EventEmitter.emit (events.js:182:7)
    at NodeEventGenerator.enterNode (...eslint/lib/util/node-event-generator.js:42:22)
    at CodePathAnalyzer.enterNode (...eslint/lib/code-path-analysis/code-path-analyzer.js:591:23)
    at CommentEventGenerator.enterNode (...eslint/lib/util/comment-event-generator.js:98:23)
    at Controller.controller.traverse.enter (...eslint/lib/eslint.js:839:36)
```

**Comment by faceleg** [comment] 2016-02-28 14:01
I'm not able to replicate this by:

```
cd ~/temp
# create temp.js file with contents pasted from above
npm install eslint babel-eslint --save-dev
# creating an .eslintrc file as describe here https://github.com/babel/babel-eslint#setup
node_modules/.bin/eslint test.js
```

**Comment by faceleg** [comment] 2016-02-28 14:02
Assigned to self while evaluating.

**Comment by faceleg** [comment] 2016-02-28 14:05
Possibly related to: https://github.com/eslint/eslint/issues/5355#issuecomment-186814689

Please consider opening an issue on babel/babel-eslint.

**Comment by TrejGun** [comment] 2016-02-29 01:33
sorry here is `.eslintrc` to reproduce the issue
```.json
{
  "parser": "babel-eslint",
  "rules": {
    "no-useless-constructor": 2
  }
}
```

**Comment by michaelficarra** [comment] 2016-02-29 02:29
@trejgun Please try to repro using master. This rule has changed very significantly since the last release, and I would be surprised if this bug still exists.

**Comment by alberto** [comment] 2016-02-29 22:25
Confirmed it no longer throws in master.

**Closed by alberto** 2016-02-29 22:25 UTC
Labels: bug, evaluating

**Comment by fixpunkt** [comment] 2016-03-11 09:32
For the benefit of anybody also coming here from Google: This issue is fixed in 2.3.0.
