### ISSUE TITLE
'Parsing error: Unexpected token function' using async/await 

### ISSUE THREAD

**Issue by bettercalldough** [eslint/eslint#9761] opened 2017-12-23 02:51 UTC
**Tell us about your environment**

* **ESLint Version:** 4.13.1
* **Node Version:** 8.1.3
* **npm Version:** 5.6.0

**What parser (default, Babel-ESLint, etc.) are you using?**
eslint 
extending airbnb-base

**Please show your full configuration:**
<details>
<summary>Configuration</summary>

```
module.exports = {
  "extends": "airbnb-base",
  "parserOptions": {
    "sourceType": "module",
    "ecmaVersion": 7
  },
  "globals": {
    "document": false,
    "grecaptcha": false,
    "expect": false,
    "google": false,
    "Headway": false,
    "Stripe": false
  },
  "rules": {
    "camelcase": 0,
    "new-cap": 0,
    "max-len": 0,
    "no-mixed-operators": 0,
    "no-nested-ternary": 0,
    "no-console": 0,
    "linebreak-style": 0,
    "prefer-const": 0,
    "no-useless-escape": 0,
    "no-param-reassign": [2, {
      "props": false
    }],
    "prefer-destructuring": ["error", {
      "array": false,
      "object": false
    }, {
      "enforceForRenamedProperties": false
    }]
  },
  "plugins": [
    "import"
  ],
  "env": {
    "browser": true,
    "mocha": true
  }
};
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**
```
    const oembed = (url) => {
      const deferred = $q.defer();
      const params = {
        id: url,
      };

      OutputModel.oembed(params, (data) => {
        deferred.resolve(data);
      }, (error) => {
        deferred.reject(error);
      });
      return deferred.promise;
    };
    
    async function getOembed(url) {
      const oembedData = await oembed(url);
      console.log(oembedData);
    }
```

```
"lint:js": "node_modules/.bin/eslint src",
```

**What did you expect to happen?**
eslint to pass

**What actually happened? Please include the actual, raw output from ESLint.**
eslint failes

```
Module build failed: error: couldn't process source due to parse error,Unexpected token (45:8)
```

**Comment by not-an-aardvark** [comment] 2017-12-23 03:07
Closing as a duplicate of https://github.com/eslint/eslint/issues/8366

**Closed by not-an-aardvark** 2017-12-23 03:07 UTC
Labels: triage

**Comment by bettercalldough** [comment] 2017-12-23 03:16
updated eslint to reflect below.

```
module.exports = {
  "extends": ['eslint:recommended', 'airbnb-base'],
  "parserOptions": {
    "ecmaVersion": 2017
  },
  "globals": {
    "document": false,
    "grecaptcha": false,
    "expect": false,
    "google": false,
    "Headway": false,
    "Stripe": false
  },
  "rules": {
    "camelcase": 0,
    "new-cap": 0,
    "max-len": 0,
    "no-mixed-operators": 0,
    "no-nested-ternary": 0,
    "no-console": 0,
    "linebreak-style": 0,
    "prefer-const": 0,
    "no-useless-escape": 0,
    "no-param-reassign": [2, {
      "props": false
    }],
    "prefer-destructuring": ["error", {
      "array": false,
      "object": false
    }, {
      "enforceForRenamedProperties": false
    }]
  },
  "plugins": [
    "import"
  ],
  "env": {
    "browser": true,
    "mocha": true
  }
};
```

still receive 

> Module build failed: error: couldn't process source due to parse error,Unexpected token (45:8)

**Comment by not-an-aardvark** [comment] 2017-12-23 03:27
Are you sure that error is coming from ESLint? It doesn't look like the error messages that ESLint outputs.

**Comment by bettercalldough** [comment] 2017-12-23 19:22
Keep this one closed. Webpack issue with using eslint and babel linter
