### ISSUE TITLE
Bug: for-of loop (no-unused-vars)

### ISSUE THREAD

**Issue by shoonia** [eslint/eslint#12165] opened 2019-08-25 14:19 UTC
Eslint says the `const` and `let` declared into for-of loop brackets never used.

**Environment**

* **ESLint:** v6.2.2
* **Node:** v10.13.0
* **yarn:** v1.12.3

`babel-eslint` with `eslint:recommended`

**Configuration:**

<details>
<summary>Configuration</summary>

```js
{
  "parser": "babel-eslint",
  "extends": [
    "eslint:recommended"
  ],
  "parserOptions": {
    "ecmaVersion": 2018
  },
  "env": {
    "es6": true,
    "node": true,
    "browser": true,
    "mocha": true
  },
  "rules": {
    "linebreak-style": "off",
    "indent": [
      "error",
      2
    ],
    "quotes": [
      "error",
      "double"
    ],
    "semi": [
      "error",
      "always"
    ]
  }
}

```

</details>

```js
const arr = [1, 2, 3];

for (const key1 of arr) {
  console.log(key1);
}

for (let key2 of arr) {
  console.log(key2);
}

```

```bash
yarn run v1.12.3
$ eslint . --fix

D:\projects\mini-css-class-name\es6\test.js
  3:12  error  'key1' is defined but never used  no-unused-vars
  7:10  error  'key2' is defined but never used  no-unused-vars

✖ 2 problems (2 errors, 0 warnings)
```

It works without errors in previous `eslint v6.1.0`

**Comment by mdjermanovic** [comment] 2019-08-25 15:09
Hi @shoonia, thanks for the issue.

I'm closing this because it's a duplicate of #12117.

Please follow #12117 and babel/babel-eslint#791

**Closed by mdjermanovic** 2019-08-25 15:09 UTC
Labels: bug, triage
