### ISSUE TITLE
Print deprecation warning instead of crash on unknown rule

### ISSUE THREAD

**Issue by malandrew** [eslint/eslint#1549] opened 2014-12-05 17:51 UTC
Recently the `"space-unary-word-ops"` rule was changed to `"space-unary-ops"`. When the name of a rule is changed, eslint encounters an unknown key and crashes hard. Instead of crashing, printing an error like: "unknown rule: {{ error.ruleId }}. Please check to see if this rule exists or has been deprecated" to stderr would be more instructive. 

Along with this message could be a link to a document that is nothing more than a rule changelog, that states what rules were added, removed or modified in each release, so that users can just check that document to see what's new, what they should remove from their config file and what additional options might now be available for rules they are currently using.

**Comment by bedney** [comment] 2015-05-02 20:21
Ran into this as well. Whichever way we jump on deprecating rules, can we fix the bug where eslint crashes, rather than produce a warning, on unknown rules? The problem is that different members of the development team may have an different versions of eslint that don't know about newer rules and so they experience crashes when they pull a new .eslint file referencing newer rules.

**Comment by malandrew** [comment] 2015-05-02 22:26
I recently created a new rule and one of the really nice features of the test suite is the thoroughness that it guarantees

**Comment by gyandeeps** [comment] 2015-06-19 22:00
I was planning to work on it but before I actually started I wanted to know if it would be good to have this functionality inside `config-validator`. Since its already validating the rule.

**Comment by nzakas** [comment] 2015-06-20 00:59
Config validator throws an error when it finds a problem, which would be the same as current behavior.

I think what we are talking about here is using a stub rule that just outputs "This rule had been removed in favor of x" as a normal rule error.

**Comment by gyandeeps** [comment] 2015-06-20 01:02
Yes, what I meant was that it will not throw an error rather display the deprecation message. 
My ask is that if we should add that logic inside `config-validator` functions?

**Comment by nzakas** [comment] 2015-06-20 01:10
Sorry, I wasn't clear. No, this should not be in config-validator, as validation always throws an error. @btmills do you agree?

**Comment by welwood08** [comment] 2015-06-20 09:16
How would using stub rules solve the problem of older code encountering a newer unknown rule?

**Comment by nzakas** [comment] 2015-06-20 16:20
@welwood08 any unknown rule would be assigned to the stub. The message can always be different depending on if the rule was deprecated, removed, or unknown.

**Comment by btmills** [comment] 2015-06-20 16:56
> No, this should not be in config-validator, as validation always throws an error.

@nzakas Yep, totally. Validation errors cause ESLint to bail before linting because any results would be bogus anyway if rules are configured anyway. I very much like the idea of a stub rule for this.

**Comment by IanVS** [comment] 2015-07-02 18:59
Based on https://github.com/eslint/eslint/issues/1898#issuecomment-118068593, should this issue have a `v1.0.0` milestone assignment?

**Comment by ilyavolodin** [comment] 2015-07-02 19:00
Yes, thanks for noticing

**Comment by IanVS** [comment] 2015-07-02 20:55
I'd be happy to take a crack at it.  However, I'm not so familiar with the concept of a stub rule.  Could someone give a basic overview of what needs to be done, so I know I'm going down the right path?

**Comment by nzakas** [comment] 2015-07-03 18:46
Basically, you'd create something like this:

```js
function createStubRule(warning) {
    return {
        Program: function(node) {
            context.report(node, warning);
        }
    };
}

// called as
var rule = createStubRule("Unknown rule");
```

And whenever a rule isn't found or is deprecated (probably need to add deprecated.json into /config that maps while rules are deprecated), create a stub rule in its place.

**Comment by IanVS** [comment] 2015-07-04 03:26
@nzakas, thanks for the hints.  If you have a chance, please review what I have so far, and then I will tackle deprecations (which will use much of the same infrastructure).

**Closed** 2015-07-10 00:26 UTC
Labels: accepted, core, enhancement
