### ISSUE TITLE
CLIEngine cwd seems to be ignored for node_modules?

### ISSUE THREAD

**Issue by alansouzati** [eslint/eslint#7773] opened 2016-12-15 01:18 UTC
* **ESLint Version:** v3.12.2
* **Node Version:** v6.9.1
* **npm Version:** 3.10.9

I'm trying to create a little tool that will be able to parallelize eslint for a project. So I'm using CLIEngine directly based on the great API available.

The problem is that the code for the CLIEngine is in a separate node project that I install globally. When I try to execute it in my project the plugin lookup refers to the external project not my internal one. I thought cwd would solve this issue but I still cannot resolve it.

```
        const eslint = new CLIEngine({
          configFile: eslintrcPath,
          ignorePath: ignorePath,
          cwd: process.cwd()
        });
```

**What did you expect to happen?**

Plugin lookup should use local node_modules

**What actually happened? Please include the actual, raw output from ESLint.**

Plugin lookup is on the external project...

```
/Users/alansouza/workspace/eslint-test/node_modules/eslint/lib/config/plugins.js:137
                throw err;
                ^

Error: Failed to load plugin react: Cannot find module 'eslint-plugin-react'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
```

Any ideas how to make sure to look for modules inside `/Users/alansouza/workspace/myproject` instead of `/Users/alansouza/workspace/eslint-test` ?

**Comment by alansouzati** [comment] 2016-12-15 02:25
Editing this line:

https://github.com/eslint/eslint/blob/0b85004acdca863873d5e3cdcfcbe6fe4ac106b6/lib/config/plugins.js#L129

to this:

`require(process.cwd(), 'node_modules', longName)`

works.

If you agree I can send a pull request to fix that. But I'm not sure if this is the right fix.

**Comment by not-an-aardvark** [comment] 2016-12-15 09:14
I'm not sure, but I think this might be related to how ESLint handles locally/globally installed plugins -- it uses the location of the ESLint executable rather than the cwd.

**Comment by alansouzati** [comment] 2016-12-15 17:12
Yeah, also if it helps, this library I have is not yet published to NPM, so to test I've linked it using `npm link` to the global NPM, and then I have access to it in the command line.

**Comment by alansouzati** [comment] 2016-12-15 17:15
Also, I believe this could be connected https://github.com/nodejs/node/issues/5963

**Comment by epmatsw** [comment] 2016-12-15 17:19
This looks like a dupe of https://github.com/eslint/eslint/issues/7723

**Comment by alansouzati** [comment] 2016-12-20 20:20
This also seems related to https://github.com/eslint/eslint/issues/5476

If I install `eslint` globally and try to run eslint in my project I get the following error:

```
Error: Cannot find module 'estraverse-fb'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at monkeypatch (/usr/local/lib/node_modules/babel-eslint/index.js:55:32)
    at Object.exports.parse (/usr/local/lib/node_modules/babel-eslint/index.js:399:5)
    at parse (/usr/local/lib/node_modules/eslint/lib/eslint.js:664:31)
    at EventEmitter.module.exports.api.verify (/usr/local/lib/node_modules/eslint/lib/eslint.js:802:27)
    at processText (/usr/local/lib/node_modules/eslint/lib/cli-engine.js:264:31)
    at processFile (/usr/local/lib/node_modules/eslint/lib/cli-engine.js:303:18)
    at executeOnFile (/usr/local/lib/node_modules/eslint/lib/cli-engine.js:672:25)
```

**Comment by nzakas** [comment] 2016-12-25 17:55
CWD indicates the directory in which ESLint is running, not where to look for plugins. I don't think it's a good idea to change this behavior as it could break a lot of people's existing code. 

I'm not opposed to adding a new option for this purpose, though.

**Comment by nzakas** [comment] 2016-12-25 18:34
Realized I was thinking about this incorrectly and shareable configs and plugins should probably relate to CWD. This is a breaking change, though, so we need to be careful about how we introduce this.

**Comment by kaicataldo** [comment] 2017-03-11 20:39
Is this something we want to pursue? There hasn't been any movement on this issue in quite a while now.

**Comment by epmatsw** [comment] 2017-03-12 18:41
I would appreciate a fix for this, but also understand if it's lower priority. It does make it pretty difficult to build tooling on top of the Node API of ESLint that also interacts correctly with typical configurations (configs, plugins, etc.).

**Comment by not-an-aardvark** [comment] 2017-08-14 02:14
I think this is the same as the "local/global installation" issue/feature, where plugins need to be installed globally if eslint is installed globally. Resolving plugins from the CWD would effectively make everything a local installation.

So I'm going to close this in favor of https://github.com/eslint/eslint/issues/6732.

**Closed by not-an-aardvark** 2017-08-14 02:14 UTC
Labels: breaking, bug, core, evaluating
