### ISSUE TITLE
Bug: sharable configs not loaded through CLI

### ISSUE THREAD

**Issue by fedeci** [eslint/eslint#15697] opened 2022-03-12 17:38 UTC
### Environment

Node version: v16.13.1
npm version: v8.4.1
Local ESLint version: v8.11.0 (Currently used)
Global ESLint version: Not found
Operating System: darwin 21.2.0

### What parser are you using?

@typescript-eslint/parser

### What did you do?

Run:
`npm i @fig/eslint-config-autocomplete`
`npx eslint -c @fig/autocomplete --fix .`.

### What did you expect to happen?

I expect to correctly load the sharable config using the --config (-c) flag from the CLI.

### What actually happened?

```md
Error: Cannot read config file: /Users/federico/Documents/withfig.nosync/autocomplete/@fig/autocomplete
Error: ENOENT: no such file or directory, open '/Users/federico/Documents/withfig.nosync/autocomplete/@fig/autocomplete'
    at Object.openSync (node:fs:585:3)
    at Object.readFileSync (node:fs:453:35)
    at readFile (/Users/federico/Documents/withfig.nosync/autocomplete/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2476:35)
    at loadLegacyConfigFile (/Users/federico/Documents/withfig.nosync/autocomplete/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2541:60)
    at loadConfigFile (/Users/federico/Documents/withfig.nosync/autocomplete/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2656:20)
    at ConfigArrayFactory._loadConfigData (/Users/federico/Documents/withfig.nosync/autocomplete/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2947:42)
    at ConfigArrayFactory.loadFile (/Users/federico/Documents/withfig.nosync/autocomplete/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2813:40)
    at createCLIConfigArray (/Users/federico/Documents/withfig.nosync/autocomplete/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3621:35)
    at new CascadingConfigArrayFactory (/Users/federico/Documents/withfig.nosync/autocomplete/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3697:29)
    at new CLIEngine (/Users/federico/Documents/withfig.nosync/autocomplete/node_modules/eslint/lib/cli-engine/cli-engine.js:607:36)
```

### Participation

- [ ] I am willing to submit a pull request for this issue.

### Additional comments

Also `npx eslint -c "@fig/autocomplete" --fix .` and `npx eslint -c @fig/eslint-config-autocomplete --fix .` don't work.

**Comment by mdjermanovic** [comment] 2022-03-12 21:57
Hi @fedeci, thanks for the issue!

This works as intended, the [`-c`](https://eslint.org/docs/user-guide/command-line-interface#-c---config) option expects a file path to a configuration file. This option isn't designed to support package names and config specifiers.

[Shareable configs](https://eslint.org/docs/developer-guide/shareable-configs#using-a-shareable-config) are designed to work with the `extends` feature of configuration files. You can make an eslint config file in your project and add sharable configs to `extends`:

```js
//---------- .eslintrc.js -------------

module.exports = {
    extends: ["@fig/eslint-config-autocomplete"]
};
```

Since this is not a bug, and there's already an open issue with a request to support loading shareable configs from the command line, I'm closing this issue as a duplicate of https://github.com/eslint/eslint/issues/14574.

**Closed by mdjermanovic** 2022-03-12 21:57 UTC
Labels: works as intended

**Comment by fedeci** [comment] 2022-03-13 15:03
Thanks for the prompt response @mdjermanovic! Is there any intention to add back the possibility to specify an `extends` from the CLI?

**Comment by mdjermanovic** [comment] 2022-03-13 16:26
> Is there any proposal to add back the possibility to specify an `extends` from the CLI?

I think not, and we wouldn't be able to accept that proposal because the current eslintrc config system is frozen as we are working on the new flat config system (https://github.com/eslint/eslint/issues/13481), which doesn't have the `extends` concept. We can only evaluate loading shareable configs from CLI in the context of the new config system (https://github.com/eslint/eslint/issues/14574).
