### ISSUE TITLE
JSX linting fails due to espree minor release including major dependency bump

### ISSUE THREAD

**Issue by debugwand** [eslint/eslint#11018] opened 2018-10-25 14:05 UTC
Espree has released a minor version 4.1.0 which bumps acorn-jsx to a new major version (5), which in turn breaks JSX linting (see https://github.com/eslint/espree/issues/393)

`Acorn-jsx` needs to be used in a different way as of version 5,
https://github.com/RReverser/acorn-jsx/commit/ddcc01d707b2eb5f9ae4de36ba32e2276a18ba3c

We are running command `eslint **/*.jsx` in the terminal, errors thrown:
`error  Parsing error: Unexpected token =`

ESLint: 5.7.0
Node: any
npm: any

<details>
<summary>Configuration</summary>

```js
module.exports = {
	env: {
		node: true,
		browser: true,
		es6: true
	},
	plugins: [
		'jsx-a11y'
	],
	extends: [
		'eslint:recommended',
		// https://github.com/jest-community/eslint-plugin-jest
		'plugin:jest/recommended',
		// https://github.com/yannickcr/eslint-plugin-react
		'plugin:react/recommended',
		// https://github.com/evcohen/eslint-plugin-jsx-a11y
		'plugin:jsx-a11y/recommended'
	],
	parserOptions: {
		ecmaFeatures: {
			jsx: true
		},
		ecmaVersion: 2018,
		// Support for ESM is not tied to an ES version
		sourceType: 'module'
	},
	settings: {
		react: {
			version: '16.3'
		}
	},
	rules: {
		// We don't expect consumers of x-dash to use prop types
		'react/prop-types': 'off',
		// We don't use display names for SFCs
		'react/display-name': 'off',
		// This rule is intended to catch < or > but it's too eager
		'react/no-unescaped-entities': 'off'
	},
	overrides: [
		{
			// Components in x-dash interact with x-engine rather than React
			files: [ 'components/**/*.jsx' ],
			settings: {
				react: {
					pragma: 'h',
					createClass: 'Component'
				}
			},
			rules: {
				'react/prefer-stateless-function': 'error'
			}
		}
	]
};

```

</details>

**Comment by not-an-aardvark** [comment] 2018-10-25 16:10
Hi, thanks for the report. Could you provide an example of a source file that fails to parse? JSX parsing in general seems to be working for me using the latest version of `espree`. It's possible that there is a bug here, but as far as I can tell it doesn't seem to apply to all JSX code, so it would be helpful to have a reproducible example.

**Comment by sholladay** [comment] 2018-10-25 22:41
I am also experiencing this. Getting a lot of crazy parse errors on JSX files that have not changed since the last time CI passed, while plain old JS files seem to be unaffected.

One thing to note about my setup is I am using ESLint via XO. Interestingly, I wasn't able to quickly reproduce with a plain old global ESLint install, yet ESLint and its dependencies seem to be the only ones with a new release this month.

```sh
$ npm ls acorn-jsx
└─┬ xo@0.23.0
  └─┬ eslint@5.7.0
    └─┬ espree@4.1.0
      └── acorn-jsx@5.0.0
```

**Comment by mysticatea** [comment] 2018-10-26 00:29
So this is a bug in npm.

npm doesn't seem to install dependencies correctly if a package which has a name before `eslint` in the alphabet order and has old `acorn` in that dependencies exists.... The `acorn` that `espree` depends on is lost.

**Comment by mysticatea** [comment] 2018-10-26 01:12
I reported: https://npm.community/t/failed-to-install-eslint-in-a-specific-situation/2975

**Comment by ibc** [comment] 2018-10-29 11:58
Hi, I've two projects A and B, both with same subset and config of react+babel+eslint. Not sure if relevant, but:

* In project A the issue above happens to me after upgrading from eslint 5.7.0 to eslint 5.8.0, but it also happens if I later downgrade it to 5.7.0. I also upgraded these deps:

```
 react-responsive  ^5.0.0  →         ^6.0.0
 randomatic         ^3.1.0  →   ^3.1.1
 react             ^16.5.2  →  ^16.6.0
 react-dom         ^16.5.2  →  ^16.6.0
 react-image-crop   ^6.0.0  →   ^6.0.4
 react-redux        ^5.0.7  →   ^5.1.0
 ansi-colors        ^3.1.0  →   ^3.2.1
 eslint             ^5.7.0  →   ^5.8.0
```

* In project B, even upgrading to eslint 5.8.0, I don't get the error. Those are my updates in B:

```
 react        ^16.5.2  →  ^16.6.0
 react-dom    ^16.5.2  →  ^16.6.0
 react-redux   ^5.0.7  →   ^5.1.0
 eslint        ^5.7.0  →   ^5.8.0
```

* In A:

```
$ npm ls acorn-jsx
myProjectA
└─┬ eslint@5.8.0
  └─┬ espree@4.1.0
    └── acorn-jsx@5.0.0
```

* In B:

```
$ npm ls acorn-jsx
myProjectB
├─┬ eslint@5.8.0
│ └─┬ espree@4.0.0
│   └── acorn-jsx@4.1.1
└─┬ web-ext@2.9.1
  └─┬ addons-linter@1.3.1
    └─┬ eslint-plugin-no-unsafe-innerhtml@1.0.16
      └─┬ eslint@3.19.0
        └─┬ espree@3.5.4
          └── acorn-jsx@3.0.1
```

I've ala

**Comment by herodrigues** [comment] 2018-10-29 14:06
I also got weird lint errors after upgrading eslint to v5.8.0

``` 
error  Parsing error: Unexpected token =
```

Deleting `node_modules` and `package-lock.json`, then installing all packages again solved the issue.

**Comment by ibc** [comment] 2018-10-29 16:15
Confirmed that I got rid of those errors by also removing `node_modules` and `package-lock.json`. It seems that, previously, I did not delete the lock file.

**Comment by nzakas** [comment] 2018-11-14 16:39
@mysticatea @not-an-aardvark has this been addressed now or are we still waiting for an npm fix?

**Comment by ljharb** [comment] 2018-11-14 16:42
Since this happens in eslint 5.8 but not 5.7, perhaps whatever changed to surface the npm bug should be reverted and shipped in a patch release?

**Comment by mysticatea** [comment] 2018-11-14 17:00
I don't think the revert makes sense. This causes by acorn's breaking change. Currently, the npm's bug appears when there is a older acorn in another dependency. After reverting, it will appear when there is a newer acorn in another dependency.

I had emailed with the npm support and they said they will discuss about this bug in npm inc.

But my request (please share the current status on https://npm.community/t/failed-to-install-eslint-in-a-specific-situation/2975) was ignored or they have no progress.

**Comment by mysticatea** [comment] 2018-11-21 00:57
The npm support team told me: "the bug fix requires substantial architectural changes, as a result, it's on our roadmap for 2019 and might be implemented in the summer."

Probably, it's the following item in the roadmap:

> Two-pass installer where resolution of the logical tree is distinct from computing the physical tree. With this we may be able to, at long last, end the pain around peerDependencies.
> https://blog.npmjs.org/post/173239798780/beyond-npm6-the-future-of-the-npm-cli

**Comment by ljharb** [comment] 2018-12-22 18:54
This isn't a change that needs implementing; it's an outstanding bug. Please reopen.

**Comment by kaicataldo** [comment] 2018-12-22 19:00
Agreed. I think this is helpful to leave open for now so that others experiencing this issue can track the progress of this.

**Comment by nzakas** [comment] 2018-12-27 20:15
@kaicataldo are you willing to take on responsibility for this issue? We need someone assigned to it to make sure that it doesn't get auto closed again.

Also, this issue isn't yet accepted, so we should figure out what the next steps are for getting it accepted.

**Comment by kaicataldo** [comment] 2019-01-14 19:21
Sorry, this flew under my radar. I've committed to quite a few things already and am not sure I can stay on top of this.

Given the fact that this is an `npm` bug, what do we want to do here? It sounds like the solution is to just wait for them to fix it.

**Comment by ljharb** [comment] 2019-02-14 19:05
lol this is a bug, not a change request - please reopen it.

**Comment by ZebraFlesh** [comment] 2019-06-08 22:13
Here's a solution, based on npm 6.4.1:

1. `npm ls acorn` to find all packages that depend on acorn
2. `npm uninstall` those packages
3. Verify acorn is fully removed via `npm ls acorn`. If not, repeat steps 1 and 2 until npm reports acorn is no longer installed. (Tip: Just keep adding onto your uninstall command, even if some packages have already been removed. At the end, I had `npm uninstall webpack eslint jest jest-jenkins-reporter`.)
4. `npm install` all of the packages that were previously removed.
5. `npm ls acorn` should now list a consistent version.

**Comment by feross** [comment] 2019-08-15 07:22
This is the simplest workaround I've found:

```
rm -rf node_modules && npm install --legacy-bundling
```

It forces npm to install packages like it did in npm@2, with no attempt to flatten the tree (which is where the bug is happening).

**Comment by kaicataldo** [comment] 2019-08-20 10:32
Since this issue seems to have been made worse by this past weekend’s release: 

I don’t think we’re doing anything out of the ordinary here regarding Espree and its dependencies, and I’m curious if other projects are running into this issue at all.

**Closed** 2019-10-24 19:48 UTC
Labels: accepted, blocked, bug, core
