### ISSUE TITLE
No rule category details in output 

### ISSUE THREAD

**Issue by InsightLive** [eslint/eslint#8292] opened 2017-03-20 11:49 UTC
**Tell us about your environment**

ESLint Version: 3.16.0
Node Version: 6.10.0
npm Version: 3.10.10

**What parser (default, Babel-ESLint, etc.) are you using?**

default parser

**Please show your full configuration:**

```js
{

  "parserOptions": {
      "ecmaVersion": 8,
      "ecmaFeatures": {
        "experimentalObjectRestSpread": true,
        "jsx": true
      },
      "sourceType": "module"
  },

  "env": {
      "browser": true
      , "jquery": true
      , "node": true
      , "es6": true
  },

  "globals": {
    "document": false,
    "navigator": false,
    "window": false
  },

  "rules": {

      // Possible Errors
      // These rules relate to possible syntax or logic errors in JavaScript code:
      "no-cond-assign":					"error" // disallow assignment operators in conditional expressions
      , "no-console":					"error" // ? disallow the use of console
      , "no-constant-condition":		"error" // ? disallow constant expressions in conditions
      , "no-control-regex":				"error" // disallow control characters in regular expressions
      , "no-debugger":					"error" // disallow the use of debugger
      , "no-dupe-args":					"error" // disallow duplicate arguments in function definitions
      , "no-dupe-keys":					"error" // disallow duplicate keys in object literals
      , "no-duplicate-case":			"error" // disallow duplicate case labels
      , "no-empty-character-class":		"error" // disallow empty character classes in regular expressions
      , "no-empty":						"error" // ? disallow empty block statements
      , "no-ex-assign":					"error" // disallow reassigning exceptions in catch clauses
      , "no-extra-boolean-cast":		"error" // disallow unnecessary boolean casts
      , "no-extra-semi":				"error" // ? disallow unnecessary semicolons
      , "no-func-assign":				"error" // disallow reassigning function declarations
      , "no-inner-declarations":		["error", "functions"] // disallow variable or function declarations in nested blocks
      , "no-invalid-regexp":			"error" // disallow invalid regular expression strings in RegExp constructors
      , "no-irregular-whitespace":		"error" // disallow irregular whitespace outside of strings and comments
      , "no-obj-calls":					"error" // disallow calling global object properties as functions
      , "no-regex-spaces":				"error" // disallow multiple spaces in regular expressions
      , "no-sparse-arrays":				"error" // disallow sparse arrays
      , "no-template-curly-in-string":	"error" // disallow template literal placeholder syntax in regular strings
      , "no-unexpected-multiline":		"error" // disallow confusing multiline expressions
      , "no-unreachable":				"error" // disallow unreachable code after return, throw, continue, and break statements
      , "no-unsafe-finally":			"error" // disallow control flow statements in finally blocks
      , "use-isnan":					"error" // require calls to isNaN() when checking for NaN
      , "valid-typeof":					["error", { "requireStringLiterals": true }] // enforce comparing typeof expressions against valid strings

      // Best Practices
      // These rules relate to better ways of doing things to help you avoid problems:
      , "no-case-declarations":			"error" // ? disallow lexical declarations in case clauses
      , "no-empty-pattern":				"error" // disallow empty destructuring patterns
      , "no-fallthrough":				"error" // disallow fallthrough of case statements
      , "no-global-assign":				"error" // disallow assignments to native objects or read-only global variables
      , "no-octal":						"error" // disallow octal literals
      , "no-redeclare":					"error" // disallow variable redeclaration
      , "no-self-assign":				"error" // disallow assignments where both sides are exactly the same
      , "no-unused-labels":				"error" // ? disallow unused labels

      // Variables
      // These rules relate to variable declarations:
      , "no-delete-var":				"error" // disallow deleting variables
      , "no-undef":						"error" // disallow the use of undeclared variables unless mentioned in /*global */ comments
      , "no-unused-vars":				["error", { "vars": "all", "args": "none" }] // disallow unused variables

      // Stylistic Issues
      // These rules relate to style guidelines, and are therefore quite subjective:
      , "no-mixed-spaces-and-tabs":		"error" // disallow mixed spaces and tabs for indentation

      // ECMAScript 6
      // These rules relate to ES6, also known as ES2015:
      , "constructor-super":			"error" // require super() calls in constructors
      , "no-class-assign":				"error" // disallow reassigning class members
      , "no-const-assign":				"error" // disallow reassigning const variables
      , "no-dupe-class-members":		"error" // disallow duplicate class members
      , "no-new-symbol":				"error" // disallow new operators with the Symbol object
      , "no-this-before-super":			"error" // disallow this/super before calling super() in constructors
      , "require-yield":				"error" // ? require generator functions to contain yield
  }
}
```

**What did you do? Please include the actual source code causing the issue.**

```js
// Unintentional assignment
var x;
if (x = 0) {
    var b = 1;
}

// Practical example that is similar to an error
function setHeight(someNode) {
    "use strict";
    do {
        someNode.height = "100px";
    } while (someNode = someNode.parentNode);
}
```

**What did you expect to happen?**

I need the description and category elements in json output.

```js
[
  {
    "filePath": "C:\\Virtusa Projects\\Test\\GIT\\QA_Sawani\\JavaScript\\JS_Isurika\\src\\TestESLint.js",
    "messages": [
      {
        "ruleId": "no-unused-vars",
        "severity ": 2,
        "message": "'x' is assigned a value but never used.",
        "line": 4,
        "nodeType": "Identifier",
        "description": "disallow unused variables",
        "category": "Variabl es"
      },
      ..
    ]
  }
]
```

**What actually happened? Please include the actual, raw output from ESLint.**

```js
[
  {
    "filePath": "C:\\Virtusa Projects\\Test\\GIT\\QA_Sawani\\JavaScript\\JS_Isurika\\src\\TestESLint.js",
    "messages": [
      {
        "ruleId": "no-unused-vars",
        "severity": 2,
        "message": "'x' is assigned a value but never used.",
        "line": 4,
        "nodeType": "Identifier"
      },
      ..
    ]
  }
]
```

**Comment by not-an-aardvark** [comment] 2017-03-20 13:56
Thanks for the feature request. Could you elaborate on why this would be useful?

**Comment by InsightLive** [comment] 2017-03-22 08:31
We create a report from javascript issues by running ESLint tool.
We need, 
- Category: Categorize and filter the issues by rule category.
- Description: Show the common description of a rule.

**Comment by vitorbal** [comment] 2017-03-22 08:57
I think you can do this by means of the Node.js API and the `getRules` method. For example:
```js
const eslint = require('eslint').linter;

eslint.getRules().get('yoda').meta;
```

Produces:
```js
{
    docs: {
        description: 'require or disallow "Yoda" conditions',
        category: 'Best Practices',
        recommended: false
    },
    schema: [
        { enum: [Object] },
        { type: 'object', properties: [Object], additionalProperties: false }
    ],
    fixable: 'code'
}
```

**Comment by InsightLive** [comment] 2017-03-22 09:28
I just need to access this data from my custom formatter.

**Comment by InsightLive** [comment] 2017-03-22 09:56
Here is my custom json formatter file. Please correct me if there is any issue.

"use strict";

const rules = require("../rules");

module.exports = function(results) {

	let files = [];
	results.forEach(result => {

		let violations = [];
		const messages = result.messages;
        messages.forEach(message => {

            let description;
            let category;
            const rule = rules.get(message.ruleId);
            if(rule && rule.meta && rule.meta.docs){
                description = rule.meta.docs.description;
                category = rule.meta.docs.category;
            }

			let violation = {};
			violation.ruleId = message.ruleId;
			violation.severity = message.severity;
			violation.message = message.message;
			violation.line = message.line;
			violation.nodeType = message.nodeType;
			violation.description = description;
			violation.category = category;
			violations.push(violation);
        });

		let file = {};
		file.filePath = result.filePath;
		file.messages = violations;
		files.push(file);
    });

	return JSON.stringify(files);
};

**Comment by not-an-aardvark** [comment] 2017-03-22 16:46
You can replace these two lines:

```js
violation.description = description;
violation.category = category;
```

with this:

```js
const rule = require("eslint").linter.getRules().get(message.ruleId);

violation.description = rule.meta.docs.description;
violation.category = rule.meta.docs.category;
```

**Comment by InsightLive** [comment] 2017-03-23 09:12
My custom json formatter file is inside ./lib/formatter folder. I added linter to that file as following,.

const linter = require("../eslint").linter;

But I cannot read property 'getRules()', due to linter is undefined.

**Comment by ilyavolodin** [comment] 2017-03-23 13:26
@InsightLive custom formatters run outside of eslint installation path. So you have to require eslint as a separate package (`require("eslint")`), and not by path.

**Comment by InsightLive** [comment] 2017-03-23 13:48
@ilyavolodin, I moved it to several locations (root, bin, lib), but still fails.
Cannot find module 'eslint'

**Comment by platinumazure** [comment] 2017-03-23 13:57
@InsightLive In order to use ESLint with your project, you need to use `npm install eslint --save-dev` (for local project installation) or `npm install -g eslint` (for global installation). This assumes you've already run `npm init` for your project and thus created a package.json file.

It's not a good idea to move installed packages around. Instead, let NPM install the packages and let Node handle finding them by using `require("eslint"), as Ilya recommended.

Please stop by our [Gitter chat](https://gitter.im/eslint/eslint) if you need more help installing or configuring ESLint and we'll do what we can!

**Comment by not-an-aardvark** [comment] 2017-04-21 19:28
Closing because this is working as intended.

**Closed by not-an-aardvark** 2017-04-21 19:28 UTC
Labels: question
