### ISSUE TITLE
[Tests] Improve "Output is incorrect." for fixes assert message

### ISSUE THREAD

**Issue by pke** [eslint/eslint#5917] opened 2016-04-20 22:53 UTC
Currently when an output condition is not matching the applied fix the assert message does not contain the expected and actual values:

```
assert.js:86
  throw new assert.AssertionError({
        ^
AssertionError: Output is incorrect.
    at testInvalidTemplate (c:\dev\projects\evopark\app\eslint-rules\node_modules\eslint\lib\testers\rule-tester.js:424:28)
    at Function.<anonymous> (c:\dev\projects\evopark\app\eslint-rules\node_modules\eslint\lib\testers\rule-tester.js:452:25)
    at Function.RuleTester.it (c:\dev\projects\evopark\app\eslint-rules\node_modules\eslint\lib\testers\rule-tester.js:194:19)
    at c:\dev\projects\evopark\app\eslint-rules\node_modules\eslint\lib\testers\rule-tester.js:451:32
    at Array.forEach (native)
    at Function.<anonymous> (c:\dev\projects\evopark\app\eslint-rules\node_modules\eslint\lib\testers\rule-tester.js:450:30)
    at Function.RuleTester.describe (c:\dev\projects\evopark\app\eslint-rules\node_modules\eslint\lib\testers\rule-tester.js:190:19)
    at Function.<anonymous> (c:\dev\projects\evopark\app\eslint-rules\node_modules\eslint\lib\testers\rule-tester.js:449:24)
    at Function.RuleTester.describe (c:\dev\projects\evopark\app\eslint-rules\node_modules\eslint\lib\testers\rule-tester.js:190:19)
    at Object.RuleTester.run (c:\dev\projects\evopark\app\eslint-rules\node_modules\eslint\lib\testers\rule-tester.js:440:20)
```

Also the stacktrace does not reveal anything useful about the assertion.

I propose to include the `output` and fixed source code in the assertion.

**Comment by ilyavolodin** [comment] 2016-04-21 00:12
Hmm... throw statement is coming directly from Chai's assert. I'm not really sure what can be done about that.

**Comment by pke** [comment] 2016-04-21 00:22
Line 424 in rule-tester.js

```es6
assert.equal(fixResult.output, item.output, "Output is incorrect.");
```

``´es6
assert.equal(fixResult.output, item.output, "Output is incorrect.\nExpected: " + item.output + "\nGot: " + fixResult.output);
```

**Comment by ilyavolodin** [comment] 2016-04-21 00:29
In that case, I'm all for doing that. Those stack traces are not very helpful, I agree. @nzakas are you OK with doing this?

**Comment by pke** [comment] 2016-04-21 00:51
So I understand this `assert` is coming from `chai`? If so, that might be also a bug in `chai`, cause I remember it used to print out unequal strings. With color diffs on the console even. But maybe that was a `chai` plugin.
I could also stem from the fact, that `assert` prints different outputs than `expect`(which I used). See http://chaijs.com/guide/styles/

**Comment by platinumazure** [comment] 2016-04-21 02:18
I think it's because we're supplying the third argument at all. Try removing it, maybe that's all we need? (Though the longer message may be better)

**Comment by nzakas** [comment] 2016-04-21 15:44
I think @platinumazure is right. The ideal is to have the comparison output rather a message, and I think that should happen automatically. 

Either way, a change would be good.

**Comment by alberto** [comment] 2016-04-21 20:51
@pke failing tests print the (colored) diff:
```
      AssertionError: Output is incorrect.
      + expected - actual

      -var foo = [ 1, 5, { 'bar': 'baz' }];
      +var foo =  [ 1, 5, { 'bar': 'baz' }];
```

Can you share some code exposing the problem?

**Comment by pke** [comment] 2016-04-22 07:46
But without the message you wouldn't know any context. The chai assert function should have an option to display the message + the diff.

**Comment by nzakas** [comment] 2016-04-22 15:39
@pke I think the point he's making is that we can't reproduce what you're describing. We see a diff.

**Comment by pke** [comment] 2016-04-22 16:18
You can see my console output in my OP. However you can clone https://github.com/pke/eslint-plugin-redux-saga and modify a test there that has output expectations to reproduce this error.

**Comment by alberto** [comment] 2016-05-07 22:13
```
$ npm test

> eslint-plugin-redux-saga@1.0.0 test /Users/alberto/projects/oss/sandbox/eslint-plugin-redux-saga
> tests/best-before.js

sh: tests/best-before.js: Permission denied
npm ERR! Test failed.  See above for more details.
```

```
$ node tests/best-before.js
module.js:440
    throw err;
    ^

Error: Cannot find module '../best-before'
    at Function.Module._resolveFilename (module.js:438:15)
    at Function.Module._load (module.js:386:25)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/alberto/projects/oss/sandbox/eslint-plugin-redux-saga/tests/best-before.js:2:12)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
```

**Comment by pke** [comment] 2016-05-08 23:29
Ups. Need to fix that

**Comment by alberto** [comment] 2016-05-16 15:55
Duplicate of #6106

**Closed by alberto** 2016-05-16 15:55 UTC
Labels: core, enhancement, evaluating
