### ISSUE TITLE
Bug: 0 files found (flat config)

### ISSUE THREAD

**Issue by igortas** [eslint/eslint#16701] opened 2022-12-24 23:28 UTC
### Environment

Node version:  v19.1.0
npm version: 8.19.3 (actually using pnpm 7.18.2)
Local ESLint version:  8.30.0
Operating System: Windows 11 WSL2

### What parser are you using?

Default (Espree)

### What did you do?

I have some `turbo` repo default project template the latest one (`apps` and `packages` mono repo structure).
I've removed everything `eslint` related and reinstalled all dependencies in `apps` and `packages` folders.
I've created `eslint.config.js` in the root of the project and set `lint` script like:
```
"lint": "ESLINT_USE_FLAT_CONFIG=true eslint --debug -c eslint.config.mjs"
```
Tried various configurations with `files` and `ignores` patterns, nothing works, I'm getting `eslint:flat-eslint 0 files found`

### What did you expect to happen?

I'm expecting to lint all files I've set glob pattern and ignore those that are set for ignoring with glob pattern.

### What actually happened?

No files are matched.

### Participation

- [ ] I am willing to submit a pull request for this issue.

### Additional comments

```
  eslint:cli CLI args: [ '--debug', '-c', 'eslint.config.mjs' ] +0ms
  eslint:cli Using flat config? true +2ms
  eslint:cli Running on files +3ms
  eslint:flat-eslint Override config file path is eslint.config.mjs +0ms
  eslint:flat-eslint Loading config from /home/igor/projects/turbo-vinyl/eslint.config.mjs +1ms
  eslint:flat-eslint Config file URL is file:///home/igor/projects/turbo-vinyl/eslint.config.mjs +0ms
  eslint:flat-eslint Deleting cache file at /home/igor/projects/turbo-vinyl/.eslintcache +5ms
  eslint:flat-eslint 0 files found in: 1ms +1ms
```

_No response_

**Comment by mdjermanovic** [comment] 2022-12-25 00:53
Hi @igortas, thanks for the issue!

I think this is a duplicate of https://github.com/eslint/eslint/issues/14308. If you don't specify at least one file/directory/glob in the command, ESLint will silently not lint anything. We'll fix this case so that it either throws an error or lints everything that matches `files` from the config file. In the meantime, you can add `.` (current directory) to the command:

```js
"lint": "ESLINT_USE_FLAT_CONFIG=true eslint --debug -c eslint.config.mjs ."
```

**Closed by mdjermanovic** 2022-12-25 00:53 UTC
Labels: bug, repro:needed
