### ISSUE TITLE
Bug: Intl.NumberFormat generates values that trigger no-irregular-whitespace

### ISSUE THREAD

**Issue by frattaro** [eslint/eslint#18009] opened 2024-01-18 18:28 UTC
### Environment

Node version: 18.18.2
npm version: 9.8.1
Local ESLint version: 8.56.0
Global ESLint version: 
Operating System: macos

### What parser are you using?

Default (Espree)

### What did you do?

<details>
<summary>Configuration</summary>

```
{
  "root": true,
  "parserOptions": {
    "ecmaVersion": "latest",
    "sourceType": "module"
  },
  "extends": [
    "eslint:recommended"
  ],
  "globals": {
    "Intl": "readonly",
    "require": "readonly"
  }
}

```
</details>

```js
// you can execute this in browser devtools:
new Intl.NumberFormat("en-US", {
    style: "currency",
    currency: "BZD"
  })
    .format(28524.25)
```

generates 
![image](https://github.com/eslint/eslint/assets/14955351/7a727531-1ccf-4cd0-bb87-94520683ad8b)

and it's in the code because it's in a fixture. Looking at the character:
![image](https://github.com/eslint/eslint/assets/14955351/1881c943-e7f6-4204-947b-d3219691914a)

So, I mean, very much an edge case and easily worked around. But, the irregular whitespace character is part of the language so I figured I'd make an issue if only for awareness.

### What did you expect to happen?

I'd expect eslint to be okay with a character generated from a built-in function.

### What actually happened?

ESLint did not like the character.

### Link to Minimal Reproducible Example

https://github.com/frattaro/eslint-whitespace-repro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by mdjermanovic** [comment] 2024-01-18 19:09
Hi @frattaro, thanks for the issue!

Can you please update the "What did you do section" with your eslint configuration and a code example where this rule produces the error you think is incorrect?

**Comment by frattaro** [comment] 2024-01-18 19:38
@mdjermanovic all set thanks

**Comment by mdjermanovic** [comment] 2024-01-18 21:52
> https://github.com/frattaro/eslint-whitespace-repro

To clarify, the problem is that this rule by default reports irregular whitespace characters in template literals?

**Comment by frattaro** [comment] 2024-01-18 22:04
Oh that is interesting I didn't notice it doesn't happen with double quotes. Then, yes.

**Comment by Rec0iL99** [comment] 2024-01-19 00:58
> Oh that is interesting I didn't notice it doesn't happen with double quotes. Then, yes.

@frattaro that's because `no-irregular-whitespace` rule by default [skips checking](https://eslint.org/docs/latest/rules/no-irregular-whitespace#options) strings (double or single quoted). If you want the rule to skip template literals then please use the `skipTemplates` option.

[playground](https://eslint.org/play/#eyJ0ZXh0IjoiLyplc2xpbnQgbm8taXJyZWd1bGFyLXdoaXRlc3BhY2U6IFtcImVycm9yXCIsIHsgXCJza2lwVGVtcGxhdGVzXCI6IHRydWUgfV0qL1xuXG5leHBvcnQgY29uc3QgdmFsdWUgPSBgQlpEwqAyOCw1MjQuMjVgOyIsIm9wdGlvbnMiOnsiZW52Ijp7fSwicnVsZXMiOnt9LCJwYXJzZXJPcHRpb25zIjp7ImVjbWFGZWF0dXJlcyI6e30sImVjbWFWZXJzaW9uIjoibGF0ZXN0Iiwic291cmNlVHlwZSI6Im1vZHVsZSJ9fX0=)

**Comment by mdjermanovic** [comment] 2024-01-19 14:39
I think this works as intended, but maybe we should change the default value of `skipTemplates` to `true` to match the default value of `skipStrings`, as I'm not sure if it makes sense for these two options to have different defaults. I believe this option was set to `false` for backwards compatibility at the time it was added.

**Comment by Tanujkanti4441** [comment] 2024-02-18 14:28
@eslint/eslint-team, in `no-irregular-whitespace` rule should we change the default value of `skipTemplates` option to `true` so that it can match the default value of `skipStrings` (default: `true`) or we should keep the default as is because template literals is more dynamic than strings and close this as complete?

**Comment by nzakas** [comment] 2024-02-19 18:18
I'm in favor of keeping the default as-is.

**Closed** 2024-02-28 15:30 UTC
Labels: bug, repro:needed
