### ISSUE TITLE
no-dupe-class-members does not work at all?

### ISSUE THREAD

**Issue by NullVoxPopuli** [eslint/eslint#14927] opened 2021-08-13 20:29 UTC
**Tell us about your environment**

```
  "dependencies": {
    "@babel/core": "^7.15.0",
    "@babel/eslint-parser": "^7.15.0",
    "eslint": "^7.32.0"
  }
```  
```
~/projects/node-w3g9tx
❯ node -v
v14.16.0

~/projects/node-w3g9tx
❯ npm -v
7.17.0
```

* **Operating System:**  n/a, tested locally on Mac, Linux, and StackBlitz

**What parser (default, `@babel/eslint-parser`, `@typescript-eslint/parser`, etc.) are you using?**

`@babel/eslint-parser`

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
'use strict';

module.exports = {
  // broken (no-error):
  // parser: 'babel-eslint',
  // also broken:
  parser: '@babel/eslint-parser',
  parserOptions: {
    requireConfigFile: false
  },
  extends: ['eslint:recommended'],
  env: {
    browser: true
  },
  rules: {
    'no-dupe-class-members': 'error'
  }
};

```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
// test.js
export class A {
  foo = 2;

  foo() {}

  bar = 3;
  bar = 4;
}
```

```bash
eslint ./test.js
```

**What did you expect to happen?**

two errors from no-dupe-class-members about a duplicate `foo` and duplicate `bar`

**What actually happened? Please copy-paste the actual, raw output from ESLint.**

nothing, no output. I can get output if I add `no-console: 'error'` to rules and use console in `test.js`, so I know the command and output are working.

**Steps to reproduce this issue:**

1.  create .eslintrc.js from provided config above
2. create test.js from provided source above
3. run eslint

**Are you willing to submit a pull request to fix this bug?**

mabybe? idk how involved something like this is, since the rule is in the default recommended rules, fixing it might mean a breaking change? but idk, if anyone is violating this rule in runtime code, they have bigger problems. I mostly care for pre-PR debugging for when accidents happen :upside_down_face:

**Comment by nzakas** [comment] 2021-08-14 00:39
This is happening because the rule hasn’t yet been updated to support class fields. That update will happen in v8.0.0 Along with native support for class fields. Using Babel means that you are using syntax currently not supported by ESLint and that’s why you are seeing this.

**Comment by nzakas** [comment] 2021-08-14 00:40
Duplicate of https://github.com/eslint/eslint/issues/14857

**Closed by nzakas** 2021-08-14 00:40 UTC
Labels: bug, repro:yes
