### ISSUE TITLE
Unexpected top-level property "name" error running this scan with the recommended config.

### ISSUE THREAD

**Issue by happyhebaby** [eslint/eslint#9509] opened 2017-10-24 17:52 UTC
I tried to run eslint-config-secure shared module by following the setup step on its site:https://www.npmjs.com/package/eslint-config-secure
Setup is smooth. After install I run the following command:
eslint --no-eslintrc -c package.eslint_config_secure.json c:\mycompany\GoogleChromeExtension
using the exact recommended setting as content for my package.eslint_config_secure.json:
{
 "name": "my-super-package",
"eslintConfig": {
"extends": "secure"
},
"scripts": {
"lint": "./node_modules/.bin/eslint ."
}
}
It gave the following error:
ESLint configuration in C:\mycompany\SecTools\Code\nodejs\NodeJSSecRun\package.eslint_config_secure.json is invalid:
- Unexpected top-level property "name".

Error: ESLint configuration in C:\mycompany\SecTools\Code\nodejs\NodeJSSecRun\package.eslint_config_secure.json is invalid:
- Unexpected top-level property "name".

at validateConfigSchema (C:\Program Files\nodejs\node_modules\eslint\lib\config\config-validator.js:212:15)
at Object.validate (C:\Program Files\nodejs\node_modules\eslint\lib\config\config-validator.js:229:5)
at loadFromDisk (C:\Program Files\nodejs\node_modules\eslint\lib\config\config-file.js:549:19)
at Object.load (C:\Program Files\nodejs\node_modules\eslint\lib\config\config-file.js:592:20)
at Config.loadSpecificConfig (C:\Program Files\nodejs\node_modules\eslint\lib\config.js:139:46)
at new Config (C:\Program Files\nodejs\node_modules\eslint\lib\config.js:101:14)
at new CLIEngine (C:\Program Files\nodejs\node_modules\eslint\lib\cli-engine.js:412:23)
at Object.execute (C:\Program Files\nodejs\node_modules\eslint\lib\cli.js:185:28)
at Object.<anonymous> (C:\Program Files\nodejs\node_modules\eslint\bin\eslint.js:74:28)
at Module._compile (module.js:570:32)

Info with my system:
nodejs:v6.11.3
eslint:v4.9.0
OS:windows 8.

I am not sure it's issue with this specific shared module or a general issue with eslint. I opened a new bug on the shared module github and have got no response at all, so I open a same bug in here.

**Comment by not-an-aardvark** [comment] 2017-10-24 18:27
Thanks for the report. The issue is that the `-c` flag, which can only be used to point to an ESLint config file. ESLint can read a config from a `package.json` file in a directory, but a `package.json` file is not the same thing as an ESLint config file, so the `-c` flag can't be used with `package.json` files.

**Comment by happyhebaby** [comment] 2017-10-24 18:42
the doc for config says:Configuration Files - use a JavaScript, JSON or YAML file to specify configuration information for an entire directory and all of its subdirectories. This can be in the form of an .eslintrc.* file or an eslintConfig field in a package.json file, both of which ESLint will look for and read automatically, or you can specify a configuration file on the command line.

It seems matching with the usage pattern above as the following part directs the usage of this shared module. 
"eslintConfig": {
"extends": "secure"
},

BTW I used the exact same pattern command on this issue and it also worked properly: https://github.com/eslint/eslint/issues/9479#issuecomment-337867927
Also the doc site also listed the following sample package.json, which I tried with eslint and it gave a similar error on "name". Time to update the doc site to reflect the latest version?
{
    "name": "mypackage",
    "version": "0.0.1",
    "eslintConfig": {
        "env": {
            "browser": true,
            "node": true
        }
    }
}

**Comment by not-an-aardvark** [comment] 2017-10-24 21:16
I agree that the documentation is a bit unclear. To clarify:

* When ESLint looks for a config file *on its own*, it searches for `.eslintrc.yml`, `.eslintrc.yaml`, `.eslintrc.json`, `.eslintrc.js`, and `.eslintrc` files in the directory. It also looks for `package.json` files, and can read the `eslintConfig` property from `package.json` to get a config.
* When ESLint resolves a config file *provided with the `-c` flag*, it reads any arbitrary `.yml`, `.yaml`, `.json`, or `.js` file as a config. However, ESLint does not access the `eslintConfig` property of a config which is provided with the `-c` flag.

This is because when you use `-c` with a JSON file path, ESLint assumes that file is like `.eslintrc.json` (where the config is directly in the file), rather than like `package.json` (where the config is in the `eslintConfig` property. It doesn't distinguish between `package.json` and `.eslintrc.json` behavior in this case, because it's reading an arbitrary user-provided JSON file, so it can't tell which type of file to expect by looking at the filename.

To set the config file, you could do one of the following things:

* Create a separate JSON file like this, and then use `-c` with a path to that JSON file:

    ```json
    {
        "env": {
            "browser": true,
            "node": true
        }
    }
    ```

* Create an `.eslintrc.json` file in your project root that `extends` your shareable config, instead of using the `-c` flag:

    ```json
    {
        "extends": "secure"
    }
    ```

**Comment by happyhebaby** [comment] 2017-10-24 21:40
Actually I tried your method one before while experiment to work around the issue.
Look at the following example, the behaves between using a direct .eslintrc.json and a exact copy of  ,eslintrc,json as package.json, the behavior is difficult. Which looks like a different bug
C:\work\temp>copy .eslintrc.json package.json
        1 file(s) copied.

C:\work\temp>eslint foo.js

C:\work\temp\foo.js
  1:1  warning  eval with argument of type NewExpression  security/detect-eval-with-expression

? 1 problem (0 errors, 1 warning)

C:\work\temp>eslint --no-eslintrc --c package.json foo.js

**Comment by happyhebaby** [comment] 2017-10-24 22:09
I tried your scenario two. It worked properly. I guess the issue above is basically you can't feed -c option with package.json, which is a special meaning config file for the config for nodejs. The doc site needs quite rewriting to clarify above points out.

**Comment by not-an-aardvark** [comment] 2018-01-19 15:37
Closing because this is working as intended, but feel free to create a PR if you think the docs can be improved.

**Closed by not-an-aardvark** 2018-01-19 15:37 UTC
Labels: works as intended
