### ISSUE TITLE
eslint uses a different filesystem root than .gitignore

### ISSUE THREAD

**Issue by gavacho** [eslint/eslint#1862] opened 2015-02-21 22:50 UTC
I'm using `eslint --ignore-path .gitignore .` and my `.gitignore` file contains `/build`.  To git, this means "ignore the directory named build that's in the same directory as the gitignore file" but eslint seems to interpret this differently because that directory isn't ignored unless i change my `.gitignore` file to `./build`.

**Comment by nzakas** [comment] 2015-02-22 01:03
We definitely don't have 100% compatibility with `.gitignore`, that's a known limitation because `.gitignore` is a lot more complicated. Are you requesting a change? If so, please explain.

**Comment by gavacho** [comment] 2015-02-22 21:13
So I'm not 100% sure I'm using the right terminology here, but I'd like for eslint to consider the project root (however that's defined) as the file system root for the purposes of fully-qualified paths like `/some_directory`.  So, in other words, if my project root were `/Users/gavacho/my-project` and my gitignore contained the line `/some_directory` then eslint would ignore `/Users/gavacho/my-project/some_directory` (but not `/Users/gavacho/my-project/src/some_directory`).

Would such a PR be welcome?

**Comment by gavacho** [comment] 2015-02-23 00:41
Now I think I'm reporting a bug.  [These tests](https://github.com/eslint/eslint/blob/master/tests/lib/ignored-paths.js#L141) send paths which begin with `/` to `contains` but at runtime the application never sends paths prefixed with `/` to `contains`.

**Comment by nzakas** [comment] 2015-02-23 00:56
Can you explain more about the bug you think exists? I'm not sure I follow.

**Comment by gavacho** [comment] 2015-02-23 01:23
Sure.  You can see that the first line of [the fixture ignore file](https://github.com/eslint/eslint/blob/master/tests/fixtures/.eslintignore4) contains the value `/dir` and that [this test](https://github.com/eslint/eslint/blob/master/tests/lib/ignored-paths.js#L141) is asserting that a file with path `/dir/bar.js` is ignored.

This is the behavior I desire and is the feature I requested above.  I was surprised to find this test because this feature wasn't working for me.  When I have `/dir` in my ignore file, eslint checks all the files in `<my project root>/dir`.

So I investigated the cause for why the test would pass and the feature would be broken.  What I discovered is that when the test asks the `ignoredPaths` object if a file should be ignored, it sends `/dir/bar.js`.  As you can see, it sends a fully qualified path name.  This causes the test to pass but it does not match what eslint does at runtime/in production.  At runtime, eslint never calls `ignoredPaths.contains` with a string which has the first character `/`.

**Comment by nzakas** [comment] 2015-02-23 17:02
Okay, I understand that you think the test should be failing. I'm still not sure I'd describe this as a bug. ESLint won't pass in a for beginning with `/` because it always uses relative file paths, and that's not a bug.

What I think you're requesting now is that a leading `/` be treated like `./`. Is that correct?

**Comment by gavacho** [comment] 2015-02-23 17:16
Yes.

**Comment by nzakas** [comment] 2015-02-23 20:03
Okay, that seems rational. I need to see if this would break anything before making any change. We could treat it like a bug fix (this behavior was unexpected, patch release) or an enhancement (maybe a breaking change, minor release).

**Comment by tomekwi** [comment] 2015-07-29 17:35
+1 this is definitely unexpected behavior. See here: <https://github.com/stoeffel/chickencurry/issues/13#issuecomment-126015491>.

Your user guide [says](http://eslint.org/docs/user-guide/configuring#ignoring-files-and-directories): *“Any file that follows the standard ignore file format can be used.”* JSHint (via `.jshintgnore`) and git (via `.gitignore`) both handle `/file` correctly. And I don’t know of any other explicit standard for `.*ignore` files except [the gitignore man page](http://git-scm.com/docs/gitignore).

**Comment by nzakas** [comment] 2015-07-29 22:02
@tomekwi yup, we just need someone to look into this.

**Comment by tomekwi** [comment] 2015-07-30 17:06
By the way, the [`package.json` `files` field](https://docs.npmjs.com/files/package.json#files) [handles these correctly](https://github.com/tomekwi/virtual-dom-lite/blob/1f70eac9a73ea89f75f963a10d60b1fb63a82324/package.json#L31-L37) too.

Perhaps it’s a module which resolves these inside *npm*? Perhaps you could use their logic? I’d love to help but I’m completely buried with work t the moment.

**Comment by ilyavolodin** [comment] 2015-09-16 02:35
Closing this in favor of #1862 as that one has already been accepted on a roadmap for v2

**Closed by ilyavolodin** 2015-09-16 02:35 UTC
Labels: bug, core

**Comment by tomekwi** [comment] 2015-09-16 06:22
Sure – but #1862 looks like this very issue :)

**Comment by BYK** [comment] 2015-09-16 07:59
Hah, good catch. I think he meant #2365.
