### ISSUE TITLE
require-atomic-updates isn't consistent between locals and params

### ISSUE THREAD

**Issue by darthwalsh** [eslint/eslint#11911] opened 2019-06-27 01:33 UTC
**Tell us about your environment**

* **ESLint Version:** 6.0.1
* **Node Version:** 10.15.3
* **npm Version:** 6.4.1

**What parser (default, Babel-ESLint, etc.) are you using?**
default

**Please show your full configuration:**
`require-atomic-updates: error`
<details>
<summary>Configuration</summary>

```yaml
env:
  browser: true
  es6: true
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
rules:
  require-atomic-updates: error

```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

[Demo online](https://eslint.org/demo/#eyJ0ZXh0Ijoic2FmZSA9IGFzeW5jIHAgPT4ge1xyXG4gIGNvbnN0IHBsYXllciA9IHBcclxuICBwbGF5ZXIubW9uZXkgKz0gYXdhaXQgcGxheWVyLmNhbGN1bGF0ZUluY29tZSgpOyAvLyBubyBlcnJvclxyXG59XHJcblxyXG51bnNhZmUgPSBhc3luYyBwbGF5ZXIgPT4ge1xyXG4gIHBsYXllci5tb25leSArPSBhd2FpdCBwbGF5ZXIuY2FsY3VsYXRlSW5jb21lKCk7IC8vIFBvc3NpYmxlIHJhY2UgY29uZGl0aW9uXHJcbn1cclxuIiwib3B0aW9ucyI6eyJwYXJzZXJPcHRpb25zIjp7ImVjbWFWZXJzaW9uIjo5LCJzb3VyY2VUeXBlIjoibW9kdWxlIiwiZWNtYUZlYXR1cmVzIjp7fX0sInJ1bGVzIjp7InJlcXVpcmUtYXRvbWljLXVwZGF0ZXMiOjJ9LCJlbnYiOnt9fX0=)

```js
safe = async p => {
  const player = p
  player.money += await player.calculateIncome(); // no error
}

unsafe = async player => {
  player.money += await player.calculateIncome(); // Possible race condition
}
```

```bash
node_modules/.bin/eslint a.js
```

**What did you expect to happen?**
I'd prefer neither line to cause an error, but for consistency both lines should at least have the same behavior.

#10655 specified that local variables should be excluded. Function parameters have the same scope as local variables in the function. As far as I can reason as long as the local or param isn't captured by a closure, there's no reason to treat them differently.

If this was changed, I suspect it would also fix #11899

**What actually happened? Please include the actual, raw output from ESLint.**
```
~/code/blah$ node_modules/.bin/eslint a.js

~/code/blah/a.js
  7:3  error  Possible race condition: `player.money` might be reassigned based on an outdated value of `player.money`  require-atomic-updates

✖ 1 problem (1 error, 0 warnings)
```

**Are you willing to submit a pull request to fix this bug?**
My employer hasn't pre-approved your CLA, and there's probably no business justification for fixing this

**Comment by mysticatea** [comment] 2019-07-09 03:19
Thank you for your report.

I think this is a duplicate of #11899. Please track that issue.

**Closed by mysticatea** 2019-07-09 03:19 UTC
Labels: bug, triage
