### ISSUE TITLE
no-extra-parens should not raise issues for (a&b)?c:d

### ISSUE THREAD

**Issue by andoras** [eslint/eslint#9668] opened 2017-11-30 10:27 UTC
**What rule do you want to change?**
`no-extra-parens`, especially with configuration `"nestedBinaryExpressions": false`.

**Does this change cause the rule to produce more or fewer warnings?**
Fewer warnings due this is legitim and good code. A lot of developers use code like `a=(b&c)?d:e;` to mark the whole clause for the condition.

**How will the change be implemented? (New option, new default behavior, etc.)?**
I would recommend it as default behavior or at least fit into the exception for `nestedBinaryExpressions`.

According to the documentation of this rule it should not raise issues:
`(function(){}) ? a() : b();`

**Please provide some example code that this change will affect:**
See issue https://github.com/eslint/eslint/issues/9654

**What does the rule currently do for this code?**
See issue https://github.com/eslint/eslint/issues/9654

**What will the rule do after it's changed?**
It will not raise a issue anymore.

**Comment by platinumazure** [comment] 2017-11-30 14:23
The main issue is that the conditional expression is not a binary expression. So we allow parentheses for a binary expression within a binary expression (e.g., `(4*2) + 3`), but that doesn't apply to conditional expressions.

I'm not sure if this is best handled as a new option or by augmenting the existing option (although I think the option name would become confusing in the latter case).

@eslint/eslint-team Any thoughts?

**Comment by andoras** [comment] 2017-11-30 14:36
Sounds legitimate. Using `conditionalAssign` would not make sense either. So there could be an additional option to allow this? Something like `conditionalExpression`?

**Comment by not-an-aardvark** [comment] 2018-03-05 17:47
Thanks for your interest in improving ESLint. Unfortunately, it looks like this issue didn't get consensus from the team, so I'm closing it. We define [consensus](http://eslint.org/docs/maintainer-guide/issues.html#consensus) as having three :+1:s from team members, as well as a team member willing to champion the proposal. This is a high bar by design -- we can't realistically accept and maintain every feature request in the long term, so we only accept feature requests which are useful enough that there is consensus among the team that they're worth adding.

Since ESLint is pluggable and can load custom rules at runtime, the lack of consensus among the ESLint team doesn't need to be a blocker for you using this in your project, if you'd find it useful. It just means that you would need to [implement the rule](http://eslint.org/docs/developer-guide/working-with-rules) yourself, rather than using a bundled rule that is packaged with ESLint.

**Closed by not-an-aardvark** 2018-03-05 17:47 UTC
Labels: enhancement, evaluating, rule
