### ISSUE TITLE
ability to add exceptions to no-param-reassign

### ISSUE THREAD

**Issue by rgarcia** [eslint/eslint#7780] opened 2016-12-16 02:57 UTC
**1. The version of ESLint you are using.**

3.x

**2. The problem you want to solve.**

Express route handlers take in `req` as a parameter and use mutation of `req.session` as the mechanism to write data to a user's session. This is considered problematic by `no-param-reassign`, but since it's a requirement of using express, it's not really feasible to clear this lint error.

**3. Your take on the correct solution to problem.**

We'd like the ability to add an exception to `no-param-reassign` to allow this particular case.

**Comment by not-an-aardvark** [comment] 2016-12-16 06:57
Thanks for the suggestion. However, I think this is a duplicate of https://github.com/eslint/eslint/issues/6505.

**Comment by platinumazure** [comment] 2016-12-16 14:41
Closing since this is a duplicate. Please follow #6505 for further updates.

**Closed by platinumazure** 2016-12-16 14:41 UTC
Labels: enhancement, evaluating, rule
