### ISSUE TITLE
Bug: build failing with knip v5.31.0

### ISSUE THREAD

**Issue by fasttime** [eslint/eslint#18990] opened 2024-10-06 06:49 UTC
### Environment

Node version: v22.9.0
npm version: v10.8.3
Local ESLint version: v9.12.0 (Currently used)
Global ESLint version: Not found
Operating System: darwin 24.0.0

### What parser are you using?

Default (Espree)

### What did you do?

The CI build is failing because of unused files and dependencies reported by knip when running

`npm run lint:unused`

See https://github.com/eslint/eslint/actions/runs/11199501281/job/31131926579

We should remove these files and dependencies if they are unused, or otherwise mark them as safe in the knip config.

### What did you expect to happen?

No error.

### What actually happened?

```plain
Unused files (15)
docs/src/_data/eslintVersions.js
docs/src/_data/flags.js
docs/src/_data/helpers.js
docs/src/_data/layout.js
docs/src/_data/rules_categories.js
docs/src/_data/site.js
docs/src/static/serviceworker.js
docs/src/assets/js/components-index.js
docs/src/assets/js/css-vars-ponyfill@2.js
docs/src/assets/js/focus-visible.js
docs/src/assets/js/inert-polyfill.js
docs/src/assets/js/main.js
docs/src/assets/js/scroll-up-btn.js
docs/src/assets/js/tabs.js
docs/src/assets/js/themes.js
Unused devDependencies (2)
@11ty/eleventy-fetch  docs/package.json
algoliasearch         docs/package.json
```

### Link to Minimal Reproducible Example

https://github.com/eslint/eslint/actions/runs/11199501281/job/31131926579

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by mdjermanovic** [comment] 2024-10-06 16:52
> `docs/src/_data/eslintVersions.js`

This is used here:

https://github.com/eslint/eslint/blob/1ee87ca1c50018947e76c29e78da9aaf711f53a2/docs/src/_includes/components/version-switcher.html#L15

> `docs/src/_data/flags.js`

This is used here:

https://github.com/eslint/eslint/blob/1ee87ca1c50018947e76c29e78da9aaf711f53a2/docs/src/pages/flags.md?plain=1#L37

>`docs/src/_data/helpers.js`

This is used here:

https://github.com/eslint/eslint/blob/1ee87ca1c50018947e76c29e78da9aaf711f53a2/docs/src/_includes/layouts/components.html#L30

> `docs/src/_data/rules_categories.js`

This is used here:

https://github.com/eslint/eslint/blob/1ee87ca1c50018947e76c29e78da9aaf711f53a2/docs/src/pages/rules.md?plain=1#L25

> `docs/src/static/serviceworker.js`

I couldn't find where this is used.

> `docs/src/assets/js/components-index.js`

This is used here:

https://github.com/eslint/eslint/blob/1ee87ca1c50018947e76c29e78da9aaf711f53a2/docs/src/_includes/layouts/base.html#L169

> `docs/src/assets/js/inert-polyfill.js`

I couldn't find where this is used.

> `docs/src/assets/js/css-vars-ponyfill@2.js`
> `docs/src/assets/js/focus-visible.js`
> `docs/src/assets/js/main.js`
> `docs/src/assets/js/scroll-up-btn.js`
> `docs/src/assets/js/tabs.js`

These are used here:

https://github.com/eslint/eslint/blob/1ee87ca1c50018947e76c29e78da9aaf711f53a2/docs/src/_includes/layouts/base.html#L161-L165

> `docs/src/assets/js/themes.js`

This is used here:

https://github.com/eslint/eslint/blob/1ee87ca1c50018947e76c29e78da9aaf711f53a2/docs/src/_includes/layouts/base.html#L149

> `@11ty/eleventy-fetch  docs/package.json`

This is used here:

https://github.com/eslint/eslint/blob/1ee87ca1c50018947e76c29e78da9aaf711f53a2/docs/src/_data/eslintVersions.js#L12

> `algoliasearch         docs/package.json`

This is used here:

https://github.com/eslint/eslint/blob/1ee87ca1c50018947e76c29e78da9aaf711f53a2/docs/.eleventy.js#L413-L415

**Comment by mdjermanovic** [comment] 2024-10-06 16:55
@webpro is this maybe a problem in the new version of knip?

**Comment by webpro** [comment] 2024-10-06 17:29
Looks like `npm install` isn't run in docs folder?

Odds are small there's an regression specifically for ESLint, since this repo is part of ecosystem checks here: https://github.com/webpro-nl/knip/blob/e4bada4208d860e40415f3de1c6e850b1803f244/.github/workflows/integration.yml#L77-L84 (you could ignore `--cache` flag, that's just an feature I'd like to have in at least one of the projects).

Btw, you could consider adding `docs` folder to `package.json#workspaces` so those deps are installed with `npm install` from root.

**Comment by mdjermanovic** [comment] 2024-10-06 17:50
> Looks like `npm install` isn't run in docs folder?

It's run in a previous step:

https://github.com/eslint/eslint/blob/1ee87ca1c50018947e76c29e78da9aaf711f53a2/.github/workflows/ci.yml#L23-L25

The knip check was passing yesterday on https://github.com/eslint/eslint/pull/18988 but started failing today when we merged it.

**Comment by webpro** [comment] 2024-10-06 18:08
Ah now I see. You're right. There's an issue in Knip v5.31.0 (something with the Jiti v2 upgrade) but also it has already been fixed in main. So you can just stay on a previous version and/or wait for v5.32.0 and it'll be alright again.

**Comment by mdjermanovic** [comment] 2024-10-06 18:19
It looks like jiti v2.3.x releases yesterday started these failures. When I pin `"jiti": "2.2.1"`, the knip check is passing for me locally.

Okay, then waiting for the fix in dependencies.

**Comment by webpro** [comment] 2024-10-06 19:02
Not sure how many are affected, so prioritized a release :)

**Comment by amareshsm** [comment] 2024-10-06 21:28
It looks like version knip [v5.32.0](https://github.com/webpro-nl/knip/releases/tag/5.32.0) has been released, and the issue seems to be resolved in this version

**Closed** 2024-10-07 06:38 UTC
Labels: accepted, chore
