### ISSUE TITLE
Rules confilct (prefer-const for var that assigned after define)

### ISSUE THREAD

**Issue by vasa-c** [eslint/eslint#9693] opened 2017-12-07 10:04 UTC
ESLint 4.11.0
Node 6.1.0
NPM 3.8.6

How to write correctly?

```javascript
const a = 1, value = loadValue();

function loadValue() {
    return [];
}
```

Error `'loadValue' was used before it was defined  no-use-before-define`

```javascript
const a = 1;
let value;

function loadValue() {
    return [];
}

value = loadValue();
```

Error: `'value' is never reassigned. Use 'const' instead  prefer-const`

```javascript
const a = 1;

function loadValue() {
    return [];
}

const value = loadValue();
```

Error: `Combine this with the previous 'const' statement  one-var`

**Comment by platinumazure** [comment] 2017-12-09 02:25
Hi @vasa-c, thanks for the issue.

For your example, I think you could write it like this:

```js
function loadValue() {
    return [];
}

const a = 1,
    value = loadValue();
```

But I could see this falling apart if some of the variables depended on each other in weird ways. So if you have a slightly more complicated example (such that my suggestion wouldn't work), could you share that please?

**Comment by vasa-c** [comment] 2017-12-11 08:57
@platinumazure but what about `vars-on-top`: "all variable declarations in the leading series of statements".
I do not see that rule for module level, but this code can be inside a function:

```javascript
function main() {
    function loadValue() {
        return [];
    }

    const a = 1,
        value = loadValue();
}
```

**Comment by huyb1991** [comment] 2017-12-19 02:04
My case is the same with the third error warning of @vasa-c 

My code:
```
let middleware = []

const isProduction = process.env.NODE_ENV === 'production',
  
if (!isProduction) {
  middleware.push(logger)
}

const configureStore = () => {
  const store = createStore(
      persistReducer(config, rootReducer),
      compose(applyMiddleware(...middleware))
    ),
    persistor = persistStore(store)

  return { persistor, store }
}
```
It show error:
> Combine this with the previous 'const' statement one-var

The first at `const configureStore` and second at `const store`

**Comment by not-an-aardvark** [comment] 2018-03-05 18:01
Closing because this is working as intended based on the documentation for `vars-on-top` and `prefer-const`.

**Closed by not-an-aardvark** 2018-03-05 18:01 UTC
Labels: evaluating, question

**Comment by vasa-c** [comment] 2018-03-06 14:27
@not-an-aardvark and what is the correct answer?
