### ISSUE TITLE
possible bug in config/config-file.js

### ISSUE THREAD

**Issue by mvolkmann** [eslint/eslint#8168] opened 2017-02-28 01:03 UTC
See the function `loadJSONConfigFile` here:
https://github.com/eslint/eslint/blob/master/lib/config/config-file.js#L120
That parses a `.eslintrc.json` file. It returns that as an object created by parsing the JSON.
But this line: https://github.com/eslint/eslint/blob/master/lib/config/config-file.js#L178
expects the object returned to have a property named `eslintConfig` that holds the object.
The return value IS the object. It isn't an object with an `eslintConfig` property.
Is this a bug?

**Comment by ilyavolodin** [comment] 2017-02-28 02:04
No, it's not a bug. `filePath` property can be a `.eslintrc.json` file or it can also be `package.json` file that contains `eslintConfig` property with the configuration object.

**Comment by not-an-aardvark** [comment] 2017-03-06 17:46
Closing this since the question has been answered.

**Closed by not-an-aardvark** 2017-03-06 17:46 UTC
Labels: question
