### ISSUE TITLE
error  Parsing error: Unexpected token )

### ISSUE THREAD

**Issue by adamchenwei** [eslint/eslint#9920] opened 2018-02-01 19:50 UTC
**Tell us about your environment**
Mac OS
* **ESLint Version:**
4.19
* **Node Version:**
8.9.1
* **npm Version:**
5.x
**What parser (default, Babel-ESLint, etc.) are you using?**
"babel-cli": "^6.26.0",
    "babel-core": "^6.26.0",
    "babel-jest": "^21.2.0",
    "babel-loader": "^7.1.2",
    "babel-plugin-dynamic-import-node": "^1.2.0",
    "babel-plugin-transform-object-rest-spread": "^6.26.0",
    "babel-preset-airbnb": "^2.4.0",
    "babel-preset-env": "^1.6.1",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-react": "^6.24.1",
    "babel-preset-stage-0": "^6.24.1",
"eslint": "^4.16.0",
    "eslint-config-airbnb": "^16.1.0",
    "eslint-import-resolver-alias": "^1.0.3",
    "eslint-import-resolver-webpack": "^0.8.3",
    "eslint-plugin-import": "^2.8.0",
    "eslint-plugin-jest": "^21.3.2",
    "eslint-plugin-jsx-a11y": "^6.0.2",
    "eslint-plugin-react": "^7.4.0",
    "eslint-watch": "^3.1.3",
**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js



```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**
`./node_modules/eslint/bin/eslint.js --c ./.eslintrc --fix ./src`

```js

//... inside JSX from a `render()` function inside a react component

       {
          this.generateButtons(
            currentPage,
            totalPages,
            paginationButtonDisplayMax,
            currentRange,
            onUpdate)
        }



```

```bash
./node_modules/eslint/bin/eslint.js --c ./.eslintrc --fix ./src
```

**What did you expect to happen?**
not fixing it
**What actually happened? Please include the actual, raw output from ESLint.**

It turn into 

```
// see that little comma after onUpdate? It keeps adding it back!!!!!!!!!!
{
          this.generateButtons(
            currentPage, totalPages, paginationButtonDisplayMax,
            currentRange, onUpdate,
)
        }
```
or how it looks like in VScode
![screen shot 2018-02-01 at 2 49 47 pm](https://user-images.githubusercontent.com/4201698/35699831-385a9afa-075f-11e8-98da-3c26ccaf958c.png)

**Comment by not-an-aardvark** [comment] 2018-02-01 20:04
Closing as a duplicate of https://github.com/eslint/eslint/issues/7851, https://github.com/eslint/eslint/issues/8513, https://github.com/eslint/eslint/issues/8700, and https://github.com/eslint/eslint/issues/9110

**Closed by not-an-aardvark** 2018-02-01 20:04 UTC
Labels: triage

**Comment by adamchenwei** [comment] 2018-02-01 20:10
@not-an-aardvark  Would you know a way I can somehow disable this specific rule becomes auto applied with comma danger into function? Thanks

**Comment by not-an-aardvark** [comment] 2018-02-01 20:12
You can add this to your configuration file:

```yml
rules:
  comma-dangle: [error, always-multiline]
```

**Comment by adamchenwei** [comment] 2018-02-01 20:15
Thanks
