### ISSUE TITLE
prefer-const and conditional return

### ISSUE THREAD

**Issue by mlarcher** [eslint/eslint#9643] opened 2017-11-20 17:53 UTC
**Tell us about your environment**

* **ESLint Version:**
3.19
* **Node Version:**
8.5
* **npm Version:**
5.5.1
**What parser (default, Babel-ESLint, etc.) are you using?**
default
**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
{
    "parserOptions": {
        "ecmaVersion": 6,
        "sourceType": "script",
        "ecmaFeatures": {}
    },
    "rules": {
        "constructor-super": 2,
        "no-case-declarations": 2,
        "no-class-assign": 2,
        "no-compare-neg-zero": 2,
        "no-cond-assign": 2,
        "no-console": 2,
        "no-const-assign": 2,
        "no-constant-condition": 2,
        "no-control-regex": 2,
        "no-debugger": 2,
        "no-delete-var": 2,
        "no-dupe-args": 2,
        "no-dupe-class-members": 2,
        "no-dupe-keys": 2,
        "no-duplicate-case": 2,
        "no-empty-character-class": 2,
        "no-empty-pattern": 2,
        "no-empty": 2,
        "no-ex-assign": 2,
        "no-extra-boolean-cast": 2,
        "no-extra-semi": 2,
        "no-fallthrough": 2,
        "no-func-assign": 2,
        "no-global-assign": 2,
        "no-inner-declarations": 2,
        "no-invalid-regexp": 2,
        "no-irregular-whitespace": 2,
        "no-mixed-spaces-and-tabs": 2,
        "no-new-symbol": 2,
        "no-obj-calls": 2,
        "no-octal": 2,
        "no-redeclare": 2,
        "no-regex-spaces": 2,
        "no-self-assign": 2,
        "no-sparse-arrays": 2,
        "no-this-before-super": 2,
        "no-undef": 2,
        "no-unexpected-multiline": 2,
        "no-unreachable": 2,
        "no-unsafe-finally": 2,
        "no-unsafe-negation": 2,
        "no-unused-labels": 2,
        "no-unused-vars": 2,
        "no-useless-escape": 2,
        "require-yield": 2,
        "use-isnan": 2,
        "valid-typeof": 2,
        "prefer-const": 2
    },
    "env": {}
}


```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js

function fn() {
  let foo;
  if (Math.random() > .5) {
    foo = 'hop';
    return foo;
  }
  foo = 'baz';
  return foo;
}
fn();



```

```bash
eslint filename
```

**What did you expect to happen?**
I expected ESlint to pickup on the fact that either we enter the `if`, in which case the return makes it so the `foo` var is never reassigned, or we don't, in which case the `foo` bar is also never reassigned.

**What actually happened? Please include the actual, raw output from ESLint.**
ESlint doesn't report an error

**Comment by not-an-aardvark** [comment] 2017-11-20 21:11
Hi, thanks for the report.

I'm confused about the behavior that you were expecting. There are two locations where `foo` *could* be assigned, even though only one of them will actually be selected at runtime. This means that it wouldn't be possible to declare `foo` with `const`, so I wouldn't expect `prefer-const` to report an error for this case.

Simpler example:

```js
let foo;
if (x) {
  foo = 1;
} else {
  foo = 2;
}
console.log(foo);
```

Similarly, in this example `foo` will only get assigned once at runtime, but it doesn't seem like it would be possible to declare `foo` with `const` (assuming we keep the general structure of the code rather than reducing it to a ternary expression).

**Comment by kane-thornwyrd** [comment] 2017-11-21 08:14
The exemple would rather be something along those lines:
```js
let foo;
if (x) {
  foo = doSomething('args');
  foo.doSomethingElse();
  return foo;
}
foo = doSomething('args2');
foo.doSomethingElseDifferent();
return foo;
```

**Comment by mlarcher** [comment] 2017-11-21 08:30
When you omit the *if* block, an error is raised: "'foo' is never reassigned. Use 'const' instead."
We *can* detect that no reassign will ever occur whatever the branch path taken, through static analysis (even though it's probably not trivial). So I'd expect the raised errors to be consistent and handle this case too the same way.

Note that your code sample does not match my example, which has a `return` in the if branch. That return makes all the difference, as it is because of it that we know the variable will never be reassigned.
The construct the rule would point to would be of the following form:
```js
function fn() {
  if (Math.random() > .5) {
    const foo = 'hop';
    return foo;
  }
  const foo = 'baz';
  return foo;
}
fn();
```
This construct makes it cleat that we have two different variables with the same name but not the same scope.

**Comment by not-an-aardvark** [comment] 2017-11-28 02:23
I don't think this would be in scope for the `prefer-const` rule. The goal of the rule is to report `let` declarations that can be replaced with `const`, or moved to a different location and then replaced with `const`. However, the rule is not intended to tell the user when they could create a new variable to accomplish the same thing.

**Comment by not-an-aardvark** [comment] 2018-03-05 17:48
Thanks for your interest in improving ESLint. Unfortunately, it looks like this issue didn't get consensus from the team, so I'm closing it. We define [consensus](http://eslint.org/docs/maintainer-guide/issues.html#consensus) as having three :+1:s from team members, as well as a team member willing to champion the proposal. This is a high bar by design -- we can't realistically accept and maintain every feature request in the long term, so we only accept feature requests which are useful enough that there is consensus among the team that they're worth adding.

Since ESLint is pluggable and can load custom rules at runtime, the lack of consensus among the ESLint team doesn't need to be a blocker for you using this in your project, if you'd find it useful. It just means that you would need to [implement the rule](http://eslint.org/docs/developer-guide/working-with-rules) yourself, rather than using a bundled rule that is packaged with ESLint.

**Closed by not-an-aardvark** 2018-03-05 17:48 UTC
Labels: bug, evaluating, rule
