### ISSUE TITLE
Disable return in valid-jsdoc rule

### ISSUE THREAD

**Issue by simonhaenisch** [eslint/eslint#10360] opened 2018-05-17 04:10 UTC
**What rule do you want to change?**

[`valid-jsdoc`](https://eslint.org/docs/rules/valid-jsdoc)

I want to add an option to disable requiring a `@returns` rule entirely, because Editors are able to figure out return types of functions by themselves.

**Does this change cause the rule to produce more or fewer warnings?**

Fewer.

**How will the change be implemented?**

Let the existing rule option [`requireReturn`](https://eslint.org/docs/rules/valid-jsdoc#options) accept a string `"always"`, `"if-returns"` or `"never"` instead of a boolean. That way the current implementation can still be used and marked as deprecated.

`"always"` would be the same as what the current default (`true`) does, `"if-returns"` the same as what the current `false` does (only require it if the function explicitly returns), and `"never"` would turn the rule of entirely.

_(There might be a better name for `"if-returns"`, like `"if-explicit-return"`?)_

**Please provide some example code that this change will affect:**

```js
/**
 * adds two numbers
 * @param {number} a
 * @param {number} b
 */
function add(a, b) {
	return a + b;
}
```

VS Code will return the signature of that function as

```ts
function add(a: number, b: number): number
```

so I don't see any benefit in documenting the return type for simple functions like that.

I get that adding at least a return description is usually a good idea, but for some simple functions (like the example) it's just obvious enough from the function name what it will return and I don't want to repeat myself.

**What does the rule currently do for this code?**

```
 ⚠    1:1   Missing JSDoc @returns for function.
```

**What will the rule do after it's changed?**

It will not warn about the missing `@returns` anymore.

**Comment by platinumazure** [comment] 2018-05-17 13:26
Hi @simonhaenisch, thanks for the issue.

This seems like a reasonable enhancement request (subject to bikeshedding/discussion on the "if-returns" option value). I'll :+1: it.

**Comment by not-an-aardvark** [comment] 2018-07-22 07:02
Thanks for your interest in improving ESLint. Unfortunately, it looks like this issue didn't get consensus from the team, so I'm closing it. We define [consensus](http://eslint.org/docs/maintainer-guide/issues.html#consensus) as having three :+1:s from team members, as well as a team member willing to champion the proposal. This is a high bar by design -- we can't realistically accept and maintain every feature request in the long term, so we only accept feature requests which are useful enough that there is consensus among the team that they're worth adding.

Since ESLint is pluggable and can load custom rules at runtime, the lack of consensus among the ESLint team doesn't need to be a blocker for you using this in your project, if you'd find it useful. It just means that you would need to [implement the rule](http://eslint.org/docs/developer-guide/working-with-rules) yourself, rather than using a bundled rule that is packaged with ESLint.

**Closed by not-an-aardvark** 2018-07-22 07:02 UTC
Labels: enhancement, evaluating, rule
