### ISSUE TITLE
Parenthesized destructuring assignment should error

### ISSUE THREAD

**Issue by kaicataldo** [eslint/eslint#6542] opened 2016-06-27 03:35 UTC
Was working with @hzoo on trying to get babel-eslint's tests running with the ESLint test suite and came across [this](https://github.com/eslint/eslint/blob/c32b35bc1496f5d91a866a892be0b82f79e41ccc/tests/lib/rules/no-class-assign.js#L44) in our test suite. This passes in ESLint using Espree, but Babylon (babel-eslint's parser) throws with the following error:

> You're trying to assign to a parenthesized expression, eg. instead of `({a}) = 0` use `({a} = 0)`

I did a little digging, and it does seem like this shouldn't be parsed by Espree. Some findings that back this up:
- https://github.com/babel/babel/pull/3260
- http://whereswalden.com/2015/06/20/new-changes-to-make-spidermonkeys-and-firefoxs-parsing-of-destructuring-patterns-more-spec-compliant/
- https://bugzilla.mozilla.org/show_bug.cgi?id=1146136

I also tested in Chrome:
<img width="721" alt="screen shot 2016-06-26 at 11 15 40 pm" src="https://cloud.githubusercontent.com/assets/7041728/16367725/6503913e-3bf4-11e6-9afc-b354b4b10627.png">

and Firefox:
<img width="949" alt="screen shot 2016-06-26 at 11 16 28 pm" src="https://cloud.githubusercontent.com/assets/7041728/16367718/58ef3c68-3bf4-11e6-97fe-269ca170b533.png">

If this is accepted I'll also file an issue for Espree (and probably ultimately Acorn as well), but I wanted to have an issue open here so we could discuss and track this issue as well as fix the tests if and when this gets fixed in the parser.

**Comment by mysticatea** [comment] 2016-06-27 04:24
I confirmed it. (I'm not sure where it exists in the language spec)

I think this should be reported to Acorn repo as well.

**Comment by kaicataldo** [comment] 2016-06-27 04:31
Issue filed with Acorn: https://github.com/ternjs/acorn/issues/429

**Comment by mysticatea** [comment] 2016-06-27 04:33
Maybe 

> - It is a Syntax Error if LeftHandSideExpression is either an ObjectLiteral or an ArrayLiteral and the lexical token sequence matched by LeftHandSideExpression cannot be parsed with no tokens left over using AssignmentPattern as the goal symbol.
> - It is an early Reference Error if LeftHandSideExpression is neither an ObjectLiteral nor an ArrayLiteral and IsValidSimpleAssignmentTarget of LeftHandSideExpression is false.
>
> https://tc39.github.io/ecma262/#sec-assignment-operators-static-semantics-early-errors

If the `LeftHandSideExpression` is enclosed by parentheses, it's [CoverParenthesizedExpressionAndArrowParameterList](https://tc39.github.io/ecma262/#prod-CoverParenthesizedExpressionAndArrowParameterList). So those early errors are matched.

**Comment by kaicataldo** [comment] 2016-06-29 17:45
Looks like this is a known issue in acorn that's been open for quite some time

**Comment by kaicataldo** [comment] 2016-07-04 01:43
@mysticatea I was planning on looking at acorn to see if I could contribute a PR to fix this, but it looks like you might be interested too!

**Comment by mysticatea** [comment] 2016-07-04 01:51
Wow, I'm sorry, I had pushed a wrong button (maybe I should assign me to another issue).

**Comment by kaicataldo** [comment] 2016-07-04 01:52
No worries - happy to work on this together/decide what's best if you are interested :)

**Comment by mysticatea** [comment] 2016-07-04 02:16
Yes, I'm interested in this as well :D

I guess [lval.js#L10](https://github.com/ternjs/acorn/blob/54fde50051100004faa0825c6ec7957ee9caf81d/src/lval.js#L10) is modifying `ObjectExpression`/`ArrayExpression` to patterns, so maybe it should check parentheses.

**Comment by kaicataldo** [comment] 2016-08-27 03:30
@mysticatea I started working on this but then got busy - if you're interested you should definitely feel free to work on it :)

**Comment by kaicataldo** [comment] 2016-08-27 03:31
My first attempt is here, though it seems like it's not actually going to do the job: https://github.com/ternjs/acorn/pull/433

**Comment by mysticatea** [comment] 2016-08-28 08:26
I guess it's going to conflict with ES2017's implementations, so I will do it if it's remained after I have done implementing ES2017.

**Comment by not-an-aardvark** [comment] 2017-04-22 06:00
Closing because this was fixed in `acorn@4.0.5`.

**Closed by not-an-aardvark** 2017-04-22 06:00 UTC
Labels: accepted, blocked, bug
