### ISSUE TITLE
Parsing error: 'return' outside of function

### ISSUE THREAD

**Issue by vitaly-t** [eslint/eslint#8767] opened 2017-06-20 11:23 UTC
Cannot disable one line `/* eslint-disable-next-line */` or even the whole file at the top with `/* eslint-disable */`; both have no effect when the code contains a `return` outside of the function:

```js
if (condition) {
    /* eslint-disable-next-line */
    return; // ESLint always errors here, can't avoid it
}
```

And it always bombs out with error `Parsing error: 'return' outside of function`.

I'm trying to add ESLint into a large test suit (jasmine) that's been running successfully for years, and it uses the conditional `return`-s as shown above to stop certain test execution under special conditions.

I've been struggling to figure out how to make ESLint disregard that one line without success.

**Comment by platinumazure** [comment] 2017-06-20 12:19
This answer assumes you are using espree (that is, the default parser, or you haven't specified a different one).

I think this can be achieved using `ecmaFeatures.globalReturn` in your configuration (see [here](http://eslint.org/docs/user-guide/configuring#specifying-parser-options) for more details).

Example:

```json
{
    "parserOptions": {
        "globalReturn": true
    },
    "rules": {}
}
```

**Comment by vitaly-t** [comment] 2017-06-20 12:26
This my complete `.eslintrc.json`:

```js
{
  "env": {
    "es6": true,
    "node": true,
    "jasmine": true
  },
  "extends": "eslint:recommended",
  "parserOptions": {
    "sourceType": "module",
    "globalReturn": true
  },
  "rules": {
    "no-else-return": "error",
    "no-multi-spaces": "error",
    "no-whitespace-before-property": "error",
    "camelcase": "error",
    "new-cap": "error",
    "no-console": "error",
    "comma-dangle": "error",
    "quotes": [
      "error",
      "single"
    ],
    "semi": [
      "error",
      "always"
    ]
  }
}
```
and it doesn't work, i.e. the error is thrown.

**Comment by platinumazure** [comment] 2017-06-20 12:28
As I edited into my comment, `globalReturn` has to go in an `ecmaFeatures` object inside `parserOptions`. (My original comment had it wrong, but it's correct now.)

**Comment by vitaly-t** [comment] 2017-06-20 12:30
Tried that too, no change:
```js
  "parserOptions": {
    "ecmaVersion": 6,
    "sourceType": "module",
    "ecmaFeatures": {
      "globalReturn": true
    }
  }
```

**Comment by vitaly-t** [comment] 2017-06-20 12:39
Just found out that if I remove `"sourceType": "module"`, then it suddenly works:

```js
  "parserOptions": {
  }
```
even without `globalReturn`. But I'm not sure about other possible implications.

**Comment by kaicataldo** [comment] 2017-06-20 15:40
Looking at https://github.com/babel/babel/issues/1298, it looks like top-level `return`s are not ES6 module compliant, but are compliant with CommonJS style modules (since the module is wrapped in a function).

**Comment by vitaly-t** [comment] 2017-06-20 15:45
>  I would expect the `globalReturn` option to still work...

So would I, but it is not the case, as I explained and showed earlier.

**Comment by kaicataldo** [comment] 2017-06-20 15:46
Looking at both Espree and Acorn, nothing jumps out immediately to me, but I don't have a lot of time at the moment.

@vitaly-t Could you do us a favor and fill out the full [bug report template(https://github.com/eslint/eslint/blob/master/templates/bug-report.md)? It'll help us a lot. Thanks!

**Comment by mysticatea** [comment] 2017-06-20 16:30
This is working as intended.

- `globalReturn` option cannot be used together with ES modules. Because both setting need special scope which is the child of the global scope.
- `env: node` includes `globalReturn` option, so you don't need specifying the option manually.
- `eslint-disable` hides error reports from rules, but does not hide parsing errors of parsers.

**Comment by vitaly-t** [comment] 2017-06-20 16:49
@mysticatea so in other words, removing `"sourceType": "module"` as I did was the right thing to do?

**Comment by platinumazure** [comment] 2017-06-20 16:56
If you don't want to use ES6 import/export statements, removing the
sourceType is probably correct.

**Comment by not-an-aardvark** [comment] 2017-07-02 08:17
Closing because this is working as intended.

**Closed by not-an-aardvark** 2017-07-02 08:17 UTC
Labels: question
