### ISSUE TITLE
Plugins were not considered using the Node API .verify() function

### ISSUE THREAD

**Issue by tom-lichtenstein** [eslint/eslint#9578] opened 2017-11-03 15:15 UTC
If I use the linter.verify() function from the Node API with plugins (e.g.: eslint-plugin-angular), the included plugins do not work or do not affect the result even if they should (tested with the cli). 
I tested this with the following configuration:
```javascript
const eslintConfig =  {
    parserOptions: {
      ecmaVersion: 2017,
    },
    plugins: [
      'eslint-plugin-angular',
    ],
    extends: [
      'eslint:recommended',
      'plugin:angular/johnpapa',
    ],
}
```
Changing the ecmaVersion affected the result, but the plugin does not seem to work. The plugins are installed and work without any problems with the cli (I tested this with various plugins). Did I miss some special configurations or is it a bug?

**Comment by mysticatea** [comment] 2017-11-03 15:50
Thank you for this issue.

This works as intended.
`Linter` is separated from file systems in order to use it in browsers. Then, finding/loading plugins require file systems.

Please use [CLIEngine#executeOnText](https://eslint.org/docs/developer-guide/nodejs-api#executeontext) method on Node.js.

**Comment by not-an-aardvark** [comment] 2017-11-08 09:04
Closing because this is working as intended.

**Closed by not-an-aardvark** 2017-11-08 09:04 UTC
Labels: works as intended
