### ISSUE TITLE
nextjs 9 support

### ISSUE THREAD

**Issue by lifeiscontent** [eslint/eslint#12007] opened 2019-07-19 03:14 UTC
With the next version of next js (version 9) they now have filenames which have `[]` in them

so in the case I want to load a blog post at `/post/1` the page file will be named `/pages/post/[id].js` eslint for some reason complains about this filename.

**Comment by kaicataldo** [comment] 2019-07-19 03:22
Duplicate of https://github.com/eslint/eslint/issues/11940. Please track that issue.

**Closed by kaicataldo** 2019-07-19 03:22 UTC
Labels: bug, triage
