### ISSUE TITLE
Bug: no-restricted-imports not work

### ISSUE THREAD

**Issue by Romick2005** [eslint/eslint#16568] opened 2022-11-22 15:41 UTC
### Environment

Node version: v16.16.0
npm version: v8.19.2
Local ESLint version: v8.28.0 (Currently used)
Global ESLint version: v7.26.0
Operating System: darwin 22.1.0

### What parser are you using?

@babel/eslint-parser

### What did you do?

<details>
<summary>Configuration</summary>

```
    "no-restricted-imports": [
      "error",
      {
        patterns: [ 
          {
            group: [
              "components/singletons/*"
            ],
            message: "Please use import { ComponentName} from '/components/singletons' instead"
          }
        ]
      }
    ]
```
</details>

```js
import SoundPlayer from "../components/singletons/SoundPlayer";
```

### What did you expect to happen?

error  '../components/singletons/SoundPlayer' import is restricted from being used by a pattern. Please use import { ComponentName} from '/components/singletons' instead  no-restricted-imports

### What actually happened?

No error.

### Participation

- [ ] I am willing to submit a pull request for this issue.

### Additional comments

[Eslint Playground Link](https://eslint.org/play/#eyJ0ZXh0IjoiLyogZXNsaW50IFwibm8tcmVzdHJpY3RlZC1pbXBvcnRzXCI6IFtcImVycm9yXCIsIHtcbiAgICBcInBhdHRlcm5zXCI6IFt7XG4gICAgICAgIFwiZ3JvdXBcIjogW1wiY29tcG9uZW50cy9zaW5nbGV0b25zLypcIl0sXG4gICAgICAgIFwibWVzc2FnZVwiOiBcIlBsZWFzZSB1c2UgaW1wb3J0IHsgQ29tcG9uZW50TmFtZX0gZnJvbSAnL2NvbXBvbmVudHMvc2luZ2xldG9ucycgaW5zdGVhZFwiXG4gICAgfV1cbn1dXG4qL1xuXG5pbXBvcnQgU291bmRQbGF5ZXIxIGZyb20gXCIuLi9jb21wb25lbnRzL3NpbmdsZXRvbnMvU291bmRQbGF5ZXJcIjsgLy8gQmFkIHwgU2hvdWxkIHRocm93IGVycm9yLCBidXQgbm90IHdvcmtpbmchXG5pbXBvcnQgeyBTb3VuZFBsYXllciB9IGZyb20gXCIuLi9jb21wb25lbnRzL3NpbmdsZXRvbnNcIjsgLy8gR29vZCB8IFdvcmtzIGFzIGV4cGVjdGVkXG5cbmltcG9ydCB7IFNvdW5kUGxheWVyMiB9IGZyb20gXCJjb21wb25lbnRzL3NpbmdsZXRvbnNcIjsgLy8gR29vZCB8IFdvcmtzIGFzIGV4cGVjdGVkXG5pbXBvcnQgeyBTb3VuZFBsYXllcjMgfSBmcm9tIFwiY29tcG9uZW50cy9zaW5nbGV0b25zL1NvdW5kUGxheWVyXCI7IC8vIEJhZCB8IFdvcmtzIGFzIGV4cGVjdGVkXG5pbXBvcnQgU291bmRQbGF5ZXI0IGZyb20gXCJjb21wb25lbnRzL3NpbmdsZXRvbnMvU291bmRQbGF5ZXJcIjsgLy8gQmFkIHwgV29ya3MgYXMgZXhwZWN0ZWQiLCJvcHRpb25zIjp7InBhcnNlck9wdGlvbnMiOnsiZWNtYVZlcnNpb24iOjEyLCJzb3VyY2VUeXBlIjoibW9kdWxlIiwiZWNtYUZlYXR1cmVzIjp7fX0sInJ1bGVzIjp7fSwiZW52Ijp7fX19)

![image](https://user-images.githubusercontent.com/17779660/203356815-78193f14-a73e-41c0-bc36-ef8b64f2f104.png)

**Comment by mdjermanovic** [comment] 2022-11-22 17:20
Hi @Romick2005, thanks for the issue!

> group: [
>    "components/singletons/*"
> ],

This works as intended because restricting with patterns works per the [.gitignore specification](https://git-scm.com/docs/gitignore), so if there's a `/` in the middle of the pattern then the pattern does not match at any level. You can use `**/components/singletons/*` pattern to restrict importing from both `"../components/singletons/SoundPlayer"` and `"components/singletons/SoundPlayer"` paths.

Here's the same playground example with `**/components/singletons/*` pattern:

[Eslint Playground Link](https://eslint.org/play/#eyJ0ZXh0IjoiLyogZXNsaW50IFwibm8tcmVzdHJpY3RlZC1pbXBvcnRzXCI6IFtcImVycm9yXCIsIHtcbiAgICBcInBhdHRlcm5zXCI6IFt7XG4gICAgICAgIFwiZ3JvdXBcIjogW1wiKipcXC9jb21wb25lbnRzL3NpbmdsZXRvbnMvKlwiXSxcbiAgICAgICAgXCJtZXNzYWdlXCI6IFwiUGxlYXNlIHVzZSBpbXBvcnQgeyBDb21wb25lbnROYW1lfSBmcm9tICcvY29tcG9uZW50cy9zaW5nbGV0b25zJyBpbnN0ZWFkXCJcbiAgICB9XVxufV1cbiovXG5cbmltcG9ydCBTb3VuZFBsYXllcjEgZnJvbSBcIi4uL2NvbXBvbmVudHMvc2luZ2xldG9ucy9Tb3VuZFBsYXllclwiOyAvLyBCYWQgfCBTaG91bGQgdGhyb3cgZXJyb3IsIGJ1dCBub3Qgd29ya2luZyEgLS0gaXQgd29ya3Mgbm93XG5pbXBvcnQgeyBTb3VuZFBsYXllciB9IGZyb20gXCIuLi9jb21wb25lbnRzL3NpbmdsZXRvbnNcIjsgLy8gR29vZCB8IFdvcmtzIGFzIGV4cGVjdGVkXG5cbmltcG9ydCB7IFNvdW5kUGxheWVyMiB9IGZyb20gXCJjb21wb25lbnRzL3NpbmdsZXRvbnNcIjsgLy8gR29vZCB8IFdvcmtzIGFzIGV4cGVjdGVkXG5pbXBvcnQgeyBTb3VuZFBsYXllcjMgfSBmcm9tIFwiY29tcG9uZW50cy9zaW5nbGV0b25zL1NvdW5kUGxheWVyXCI7IC8vIEJhZCB8IFdvcmtzIGFzIGV4cGVjdGVkXG5pbXBvcnQgU291bmRQbGF5ZXI0IGZyb20gXCJjb21wb25lbnRzL3NpbmdsZXRvbnMvU291bmRQbGF5ZXJcIjsgLy8gQmFkIHwgV29ya3MgYXMgZXhwZWN0ZWQiLCJvcHRpb25zIjp7InBhcnNlck9wdGlvbnMiOnsiZWNtYVZlcnNpb24iOjEyLCJzb3VyY2VUeXBlIjoibW9kdWxlIiwiZWNtYUZlYXR1cmVzIjp7fX0sInJ1bGVzIjp7fSwiZW52Ijp7fX19)

Note that I had to escape `/` after `*` (`*\/` in `"**\/components/singletons/*"`) in the configuration comment to avoid closing the comment with `*/`, but when it's evaluated the pattern is `**/components/singletons/*`.

**Closed by mdjermanovic** 2022-11-22 17:20 UTC
Labels: works as intended
