### ISSUE TITLE
object-shorthand consistent-as-needed crashes linting after last object-shorthand rule update

### ISSUE THREAD

**Issue by dzek69** [eslint/eslint#7305] opened 2016-10-04 18:19 UTC
**Tell us about your environment**

* **ESLint Version:** 3.7.1
* **Node Version:** 5.12.0
* **npm Version:** 3.8.6

**What parser (default, Babel-ESLint, etc.) are you using?** default

**Please show your full configuration:**
```json
{
  "plugins": [],
  "env": {
    "browser": true,
    "es6": true,
    "node": true
  },
  "parserOptions": {
    "sourceType": "module",
    "impliedStrict": true,
    "ecmaVersion": 6,
    "ecmaFeatures": {
      "experimentalObjectRestSpread": true
    }
  },
  "rules": {
    "object-shorthand": ["error", "consistent-as-needed"]
  },
  "globals": {}
}
```

**What did you do? Please include the actual source code causing the issue.**

```js
const x = {};
const y = { ... x };
```

**What did you expect to happen?**
Eslint should finish its job of linting specified files.

**What actually happened? Please include the actual, raw output from ESLint.**
```
Cannot read property 'type' of undefined
TypeError: Cannot read property 'type' of undefined
    at isRedundant (/home/dzek/Projects/eslint-fail/node_modules/eslint/lib/rules/object-shorthand.js:160:22)
    at Array.every (native)
    at checkConsistency (/home/dzek/Projects/eslint-fail/node_modules/eslint/lib/rules/object-shorthand.js:196:66)
    at EventEmitter.ObjectExpression (/home/dzek/Projects/eslint-fail/node_modules/eslint/lib/rules/object-shorthand.js:215:21)
    at emitOne (events.js:90:13)
    at EventEmitter.emit (events.js:182:7)
    at NodeEventGenerator.enterNode (/home/dzek/Projects/eslint-fail/node_modules/eslint/lib/util/node-event-generator.js:40:22)
    at CodePathAnalyzer.enterNode (/home/dzek/Projects/eslint-fail/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:608:23)
    at CommentEventGenerator.enterNode (/home/dzek/Projects/eslint-fail/node_modules/eslint/lib/util/comment-event-generator.js:97:23)
    at Controller.enter (/home/dzek/Projects/eslint-fail/node_modules/eslint/lib/eslint.js:898:36)
```

**Comment by not-an-aardvark** [comment] 2016-10-04 20:40
I was able to reproduce this -- it does look like a bug. Thanks for the report!

**Comment by not-an-aardvark** [comment] 2016-10-04 23:57
Marked this as a "regression" since it looks like it worked fine in 3.6.

**Closed** 2016-10-07 16:57 UTC
Labels: accepted, bug, regression, rule
