### ISSUE TITLE
Missing eslint on npmjs

### ISSUE THREAD

**Issue by Dyktus** [eslint/eslint#16076] opened 2022-06-30 20:07 UTC
### Environment

Linux with node v18

### What parser are you using?

@typescript-eslint/parser

### What did you do?

I was trying to create a new app with nestJS and noticed that @types/eslint is missing from npmjs
```bash
npm i @types/eslint
```

```
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@types/eslint/-/eslint-8.4.4.tgz - Not found
npm ERR! 404 
npm ERR! 404  '@types/eslint@https://registry.npmjs.org/@types/eslint/-/eslint-8.4.4.tgz' is not in this registry.
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

So you released something badly :) 

### What did you expect to happen?

Install it :) 

### What actually happened?

Cannot create new nest project because of missing library

### Participation

- [ ] I am willing to submit a pull request for this issue.

### Additional comments

Fix it ASAP please.

**Comment by MarioBanovac** [comment] 2022-06-30 20:21
Also have the same problem when using create react app

**Comment by kalras** [comment] 2022-06-30 20:22
Seeing the same for Angular App.

```
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@types/eslint/-/eslint-8.4.4.tgz
npm ERR! 404
npm ERR! 404  '@types/eslint@*' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of '@types/eslint-scope'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

**Comment by mdjermanovic** [comment] 2022-06-30 20:24
Duplicate of https://github.com/eslint/eslint/issues/16074

Please see https://github.com/eslint/eslint/issues/16074#issuecomment-1171617408

**Closed by mdjermanovic** 2022-06-30 20:24 UTC
Labels: bug, repro:needed
