### ISSUE TITLE
All values for parserOptions.ecmaVersion deems Promise as not defined

### ISSUE THREAD

**Issue by rooftopsparrow** [eslint/eslint#8186] opened 2017-03-02 21:35 UTC
**Tell us about your environment**

* **ESLint Version:** v3.16.1
* **Node Version:** v6.10.0
* **npm Version:** 3.10.10

**What parser (default, Babel-ESLint, etc.) are you using?**
default
**Please show your full configuration:**

```js
{
  "parserOptions": {
    "ecmaVersion": 8 // you can change this to 6,7,8 or 2015,2016,2017
  },
  "env": {
    "node": true
  },
  "extends": "eslint:recommended"
}
```

**What did you do? Please include the actual source code causing the issue.**

```js
module.exports = Promise.resolve('hello!')
```

**What did you expect to happen?**
No errors

**What actually happened? Please include the actual, raw output from ESLint.**
```
→ eslint --debug test.js
  eslint:cli Running on files +0ms
  eslint:glob-util Creating list of files to process. +20ms
  eslint:ignored-paths Looking for ignore file in ~/eslint-test +4ms
  eslint:ignored-paths Could not find ignore file in cwd +0ms
  eslint:cli-engine Processing ~/eslint-test/test.js +5ms
  eslint:cli-engine Linting ~/eslint-test/test.js +1ms
  eslint:config Constructing config for ~/eslint-test/test.js +0ms
  eslint:config Using .eslintrc and package.json files +0ms
  eslint:config Loading ~/eslint-test/.eslintrc.json +2ms
  eslint:config-file Loading JSON config file: ~/eslint-test/.eslintrc.json +1ms
  eslint:config-file Loading ~/eslint-test/node_modules/eslint/conf/eslint-recommended.js +2ms
  eslint:config-file Loading JS config file: ~/eslint-test/node_modules/eslint/conf/eslint-recommended.js +0ms
  eslint:config Using ~/eslint-test/.eslintrc.json +59ms
  eslint:config Merging command line environment settings +0ms
  eslint:config-ops Apply environment settings to config +0ms
  eslint:config-ops Creating config for environment node +1ms
  eslint:cli-engine Linting complete in: 112ms +35ms

~/eslint-test/test.js
  1:18  error  'Promise' is not defined  no-undef

✖ 1 problem (1 error, 0 warnings)
```

**Comment by platinumazure** [comment] 2017-03-02 21:54
The `ecmaVersion` parser option only defines what syntax is allowed. Whether a global variable such as Promise has value or not is a semantic issue that has nothing to do with ecmaVersion.

What you need to do is enable the "es6" environment, which brings in the ES6 globals. As a bonus, it also sets ecmaVersion to 6, but you can set it to a higher version if you like.

**Comment by rooftopsparrow** [comment] 2017-03-03 00:38
I think this is a bug. If I'm using a ECMAScript 2017 parser, I expect the parser to know the features available for ECMAScript 2017 (including any new "global" build-in Objects).

I think my confusion stems from the question: 'Why is this behavior different than using the any other build-in object ( pre ECMAScript 2015 ) like `Array`, `Date`, `JSON`, etc?"

```js
// test.js
module.exports = new Date()
```

```js
// .eslintrc.json
{
  "env": {
    "node": true
  },
  "extends": "eslint:recommended"
}
```

```
eslint test.js
# No errors
```

**Comment by rooftopsparrow** [comment] 2017-03-03 00:50
Reading the docs futher:

> es6 - enable all ECMAScript 6 features except for modules (this automatically sets the ecmaVersion parser option to 6)

It looks like my issue can be summed up that I do not have an `es8` or `es2017` flag that sets the parserOptions and provides the global variables?

**Comment by ilyavolodin** [comment] 2017-03-03 02:52
`Promise` is part of es6, not es2017. You should set `env` to es6 (to bring in all of the globals), and then set `ecmaVersion` to es2017/8. To the best of my knowledge, neither es2016 nor es2017 add any new global objects, so it would be a bit strange for us to create new environments for them.

**Comment by not-an-aardvark** [comment] 2017-03-03 02:55
Actually, es2017 adds two new globals, from the [shared memory proposal](https://tc39.github.io/ecmascript_sharedmem/shmem.html#GlobalObject.ConstructorProps) which reached stage 4 in January: `SharedArrayBuffer` and `Atomics`. We might want to create an environment for these.

**Comment by mysticatea** [comment] 2017-03-03 02:56
This is intentional behavior.
The `paeserOptions` is defined by each parser. For example, babel-eslint does not have `ecmaVersion` option. So only parsers rely on the `parserOptions`. Definitions of global variables are not related in parsers (syntax parsing).

**Comment by not-an-aardvark** [comment] 2017-03-11 07:23
Closing this issue since this is intended behavior.

**Closed by not-an-aardvark** 2017-03-11 07:23 UTC
Labels: question
