### ISSUE TITLE
Parse Error when Specifying Default Value When Destructuring

### ISSUE THREAD

**Issue by Swivelgames** [eslint/eslint#8446] opened 2017-04-11 16:01 UTC
The following line of code causes eslint to get quite excited, throwing a parser error:

```javascript
let { name: '' } = type;
```

The following error occurs (masked):
```
Parsing error: Unexpected token 1 | const *** = ({ type }) => { > 2 | let { name: '' } = type; | ^ 3 | if (!name) return ''; 4 | if (name === '***') { 5 | name = type*****(/******\((\w+)\)/g, '$1'); (Fatal)
```

**Comment by soda0289** [comment] 2017-04-11 16:07
I think you are mixing up the syntax

To give destructed property a default value the equal operator should be used.
```js
let {a = ''} = type;
```
The colon can be used to rename the property for the current scope
```js
let { name: fullName } = type;
console.log(fullName);
```

**Comment by not-an-aardvark** [comment] 2017-04-21 19:29
Closing because this is working as intended.

**Closed by not-an-aardvark** 2017-04-21 19:29 UTC
Labels: question
