### ISSUE TITLE
CLI super slow!

### ISSUE THREAD

**Issue by vjancik** [eslint/eslint#6001] opened 2016-04-29 10:09 UTC
**Problem description:**
ESLint takes super long to lint my practically empty project. It contains 3 lintable files each under 50 lines.

This is what `time` reports:
`10.94s user 1.07s system 82% cpu 14.553 total`
`11.75s user 1.34s system 76% cpu 17.209 total`

I tried swapping out `extends: airbnb` with `extends: eslint:recommended` in hope that it's the additional plugins that are causing it, but I still got 12 seconds `time`.
I'm running OSX.

Any idea what could be causing this?

ESLint Version **2.8.0**
Additional ESLint plugins: `eslint-config-airbnb`, `eslint-plugin-import`, `eslint-plugin-jsx-a11y`, `eslint-plugin-react`
Running as: `eslint . --ext .js --ext .jsx --cache`

**.eslintrc**
```json
{
  "extends": "airbnb",
  "rules": {
    "comma-dangle": 0,
    }
}
```

**Comment by SimonSchick** [comment] 2016-04-29 10:50
Have you tried to check what files the process opens? Might give some insight one what's happening.

**Comment by vjancik** [comment] 2016-04-29 10:55
Not sure how. Can you tell me how?

**Comment by SimonSchick** [comment] 2016-04-29 11:09
On osx you can use dtruss.

**Comment by ilyavolodin** [comment] 2016-04-29 12:54
Most likely a duplicate of #5679 While your project might be empty, I'm guessing you have a lot of dependencies under `node_modules`, right?

**Comment by vjancik** [comment] 2016-04-29 13:06
Yes, tons, as everybody. Is there any way to set the `globOptions to include ignore: 'node_modules/**'` through a/the config file?

**Comment by alberto** [comment] 2016-04-29 13:17
@vjancik No, there isn't. You can workaround it specifying your folders and files to avoid including `node_modules`. For example `eslint src/ test/ other/ foo.js`.

**Comment by alberto** [comment] 2016-04-29 13:29
Closing since this is most likely a duplicate of #5679. Please reopen otherwise

**Closed by alberto** 2016-04-29 13:29 UTC
Labels: triage
