### ISSUE TITLE
no-undef: ignorePattern option

### ISSUE THREAD

**Issue by silverwind** [eslint/eslint#8250] opened 2017-03-14 16:37 UTC
With `no-undef: [2]` and this code:

```js
var x;
[_, x] = [1, 2];
console.log(x);
```
one gets
```
2:2  error  '_' is not defined  no-undef
```
There are two possible ways for the author to solve this:

1) `var [_, x] = [1, 2];`. Not an option if one wants to re-use existing variables in scope.
2) `[, x] = [1, 2];`. Arguably ugly.

I think it would be great if `no-undef` would gain a `ignorePattern` option for cases like this, similar to the options available in `no-unused-vars`.

**Comment by vitorbal** [comment] 2017-03-24 13:06
Looks like we last track of this one. Sorry, @silverwind!

I think this sounds reasonable, since the option also exists for `no-unused-vars`.

Could you do me a favor? Can you fill in the template for a [rule change proposal](https://github.com/eslint/eslint/blob/master/templates/rule-change-proposal.md)? That helps the team members quickly scan and understand the issue, so there's a higher chance we can get some feedback. Thanks in advance!

**Comment by silverwind** [comment] 2017-03-25 08:41
Sure:

----

**What rule do you want to change?**

Add a `ignorePattern` option to `no-undef`, which takes a RegExp pattern for variable names that are ignored by the rule. This is useful for unavoidable "trash" variables like `_` during array destructuring, where a pattern `^_` can match them. 

**Does this change cause the rule to produce more or fewer warnings?**

Fewer warnings based on the user's preference.

**How will the change be implemented? (New option, new default behavior, etc.)?**

New option.

**Please provide some example code that this change will affect:**

```js
var x;
[_, x] = [1, 2];
console.log(x);
```

**What does the rule currently do for this code?**

```
2:2  error  '_' is not defined  no-undef
```

**What will the rule do after it's changed?**

With `ignorePattern: ^_`, the code would pass.

**Comment by vitorbal** [comment] 2017-03-25 16:05
@silverwind thanks! I've updated the labels accordingly. I think this proposal makes sense, i'll give it my support 👍 . Let's see what the rest of the team thinks.

**Comment by not-an-aardvark** [comment] 2017-03-25 18:30
Would the `ignorePattern` option cause all unused variables that match the pattern to be ignored, or would it specifically be used for array destructuring?

**Comment by ilyavolodin** [comment] 2017-03-25 21:38
I'm not sure why `[ , x] = [1, 2]` is considered ugly? That seems like a significantly better and much more readable solution then proposed `[_, x]` with a throw-away variable.

**Comment by not-an-aardvark** [comment] 2017-09-16 05:30
Thanks for your interest in improving ESLint. Unfortunately, it looks like this issue didn't get consensus from the team, so I'm closing it. We define [consensus](http://eslint.org/docs/maintainer-guide/issues.html#consensus) as having three :+1:s from team members, as well as a team member willing to champion the proposal. This is a high bar by design -- we can't realistically accept and maintain every feature request in the long term, so we only accept feature requests which are useful enough that there is consensus among the team that they're worth adding.

Since ESLint is pluggable and can load custom rules at runtime, the lack of consensus among the ESLint team doesn't need to be a blocker for you using this in your project, if you'd find it useful. It just means that you would need to [implement the rule](http://eslint.org/docs/developer-guide/working-with-rules) yourself, rather than using a bundled rule that is packaged with ESLint.

**Closed by not-an-aardvark** 2017-09-16 05:30 UTC
Labels: enhancement, evaluating, rule
