### ISSUE TITLE
no-warning-comments doesn't work

### ISSUE THREAD

**Issue by ChrisyehGone** [eslint/eslint#8897] opened 2017-07-08 06:50 UTC
**Tell us about your environment**

* **ESLint Version:v3.19.0**
* **Node Version:v7.10.0**
* **npm Version:4.2.0**

**What parser (default, Babel-ESLint, etc.) are you using?**
Babel-ESLint
**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
{
  "parser": "babel-eslint",
  "plugins": [
    "react"
  ],
  "parserOptions": {
    "ecmaVersion": 6,
    "sourceType": "module",
    "ecmaFeatures": {
      "jsx": true
    }
  },
  "env": {
    "browser": true,
    "amd": true,
    "es6": true,
    "node": true,
    "mocha": true
  },
  "rules": {
    "react/jsx-uses-vars": 1,
    "react/react-in-jsx-scope": 0,
    "react/prop-types": 0,
    "react/sort-comp": 0,
    "react/no-multi-comp": 1,
    "react/forbid-prop-types": 0, //[2, {"forbid": ["any", "array"]}],
    "jsx-a11y/no-static-element-interactions": 0,
    "import/no-extraneous-dependencies": 0,
    "import/no-unresolved": [
      2,
      {
        "ignore": [
          "^@.*"
        ]
      }
    ],
    "import/extensions": 0,
    "no-debugger": 1,
    "no-warning-comments": ["error", { "terms": ["todo", "fixme", "any other term"], "location": "anywhere" }],
    "no-param-reassign": 1,
    "semi": [
      0,
      "never"
    ],
    "global-require": 0,
    "react/jsx-no-bind": 0,
    "jsx-a11y/label-has-for": 0,
    "no-nested-ternary": 0,
    "no-unused-vars": 1,
    "no-plusplus": [
      2,
      {
        "allowForLoopAfterthoughts": true
      }
    ],
    "no-underscore-dangle": [
      2,
      {
        "allow": [
          "__ssoinfo"
        ],
        "allowAfterThis": true,
        "allowAfterSuper": true
      }
    ],
    "guard-for-in": 1,
    "no-unused-expressions": [
      2,
      {
        "allowShortCircuit": true,
        "allowTernary": true
      }
    ],
    "no-restricted-syntax": 1,
    "prefer-template": 1,
    "max-len": 0,
    "no-tabs": "off",
    "indent": [
      "error",
      2
    ],
    "no-mixed-spaces-and-tabs": ["error", "smart-tabs"],
    "react/jsx-indent": [
      "error",
      2
    ],
    "react/jsx-indent-props": [
      "error",
      2
    ]
  }
}
```

</details>

**What did you do? Please include the actual source code causing the issue.**

```js
// todo
// fixme
function takeAction() {
  // fixme
  let a = 1;
  if (a === 1) {
    a = 2;
  }
  return 0;
}

export default takeAction;

```

**What did you expect to happen?**
It is expected to show me some warnings, but I didn't receive anything yet.

**What actually happened? Please include the actual, raw output from ESLint.**
This js file passed the ESLint check.

**Comment by not-an-aardvark** [comment] 2017-07-08 06:56
Hi,

I can't reproduce this issue in the [demo](http://eslint.org/demo/) -- `no-warning-comments` is producing errors for that code.

![](https://i.gyazo.com/b228f3db925a51851e2a7db600088b69.png)

**Comment by not-an-aardvark** [comment] 2017-08-10 18:59
Closing because I couldn't reproduce this issue.

**Closed by not-an-aardvark** 2017-08-10 18:59 UTC
Labels: bug, evaluating, rule
