### ISSUE TITLE
Rule proposal: no-unneeded-disabled-rules

### ISSUE THREAD

**Issue by josh** [eslint/eslint#5659] opened 2016-03-23 21:49 UTC
**When does this rule warn? Please describe and show example code:**

ESLint configuration comments are handy for temporarily allowing an exception or hack. But sometimes the hack is fixed but the comment is still left in place.

If a `eslint-disable-line` comment is declared but would have no effect, it would be considered a problem.

The following patterns are considered problems:

``` js
/* eslint no-alert:2 */

showModal('foo'); // eslint-disable-line no-alert

// eslint-disable-next-line no-alert
showModal('foo');
```

The following patterns are not considered problems:

``` js
/* eslint no-alert:2 */

alert('foo'); // eslint-disable-line no-alert

// eslint-disable-next-line no-alert
alert('foo');
```

**Is this rule preventing an error or is it stylistic?**

Stylistic leaving unnecessary comments in a file.

**Why is this rule a candidate for inclusion instead of creating a custom rule?**

Seemed pretty meta since its about ESLint's own comment configuration.

**Are you willing to create the rule yourself?**

Sure!

**Other**

Could maybe extended to cover all inline unnecessary configuration comments like per file rule disabling.

```
// .eslintrc.json
{ "rules": { "no-alert": 2 } }

// foo.js
/* no-alert:0 */
showModal("foo")

$ eslint foo.js
// ok
$ eslint --no-inline-config foo.js
// still okay, overriding no-alert could be removed
```

Another weird case, could you disable this rule itself with an inline disable comment? :trollface: 

``` js
// eslint-disable-next-line no-unneeded-disabled-rules
// eslint-disable-next-line no-alert
showModal('foo');
```

**Comment by ilyavolodin** [comment] 2016-03-23 23:03
This can't be done in the rule. By design, rules don't know anything about other rules, hence you would be able to do something like that. However, you can easily create a stand-alone tool that would be able to identify unneeded comments. You can run eslint once normally, and once with `--no-inline-config` flag, and then compare results and flag any comment that didn't cause an error to show up with second run.
Closing as this is not something we can do as part of a rule.

**Closed by ilyavolodin** 2016-03-23 23:03 UTC
Labels: evaluating, feature, rule
