### ISSUE TITLE
eslint 2.3.0 has a missing dependency of estraverse

### ISSUE THREAD

**Issue by mdouglass** [eslint/eslint#5476] opened 2016-03-05 01:00 UTC
**What version of ESLint are you using?**
2.3.0

**What configuration and parser (Espree, Babel-ESLint, etc.) are you using?**
babel-eslint

**What did you do? Please include the actual source code causing the issue.**
Out of the box configuration is throwing an error:
```sh
Error: Cannot find module 'estraverse-fb'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at monkeypatch (/project/node_modules/babel-eslint/index.js:59:32)
    at Object.exports.parse (/project/node_modules/babel-eslint/index.js:385:5)
    at parse (/project/node_modules/eslint/lib/eslint.js:578:27)
    at EventEmitter.module.exports.api.verify (/project/node_modules/eslint/lib/eslint.js:716:19)
    at processText (/project/node_modules/eslint/lib/cli-engine.js:187:27)
    at processFile (/project/node_modules/eslint/lib/cli-engine.js:227:18)
    at executeOnFile (/project/node_modules/eslint/lib/cli-engine.js:603:23)
```

**Comment by unindented** [comment] 2016-03-05 01:25
Experiencing the same issue across all my repos. Greenkeeper is spamming me like crazy.

**Comment by ilyavolodin** [comment] 2016-03-05 01:31
This looks like problem with `babel-eslint` which was relying on `estraverse-fb` that we removed in this release. @hzoo is that statement correct?

**Comment by nzakas** [comment] 2016-03-05 01:40
If we do #4640, we might be able to fix this the right way.

I'm guessing this is related to #5443.

**Comment by nzakas** [comment] 2016-03-05 01:42
Oops, hit Enter too soon. Even without removing estraverse-fb, I think the rest of the changes in #5443 would probably have caused other problems with babel-eslint.

**Comment by nzakas** [comment] 2016-03-05 02:01
I just looked at babel-eslint and it looks like it's just modifying VisitorKeys from estraverse-fb, so #4640 should work.

**Comment by mysticatea** [comment] 2016-03-05 02:25
`keys` option of `estraverse` and `childVisitorKeys` option of `escope` are merged with `estraverse.VisitorKeys` inside of them.
So I think the previous way of patching still works.

**Comment by platinumazure** [comment] 2016-03-05 02:32
Shouldn't babel-eslint just declare the dependency if they need it?

**Comment by mysticatea** [comment] 2016-03-05 02:44
@platinumazure Actually `babel-eslint` doesn't need `estraverse-fb`. `babel-eslint` is searching and modifying `estraverse-fb` which ESLint is using, in order to patch for ES.next and Flow features.

As far as I remember, that patch of `estraverse-fb` is for `eslint@<1.9.0`

**Comment by egoroof** [comment] 2016-03-05 03:39
Have the same problem. Eslint not working :(

**Comment by red2678** [comment] 2016-03-05 04:18
Same here. 

I just installed `estraverse-fb` without using the  `--save` or `--save-dev` flag, all is good.
Then when this is fixed, I'll just run `npm-prune`

**Comment by hzoo** [comment] 2016-03-05 04:47
Yeah estraverse-fb was only added since eslint had it (and since it was removed, it can also be removed from babel-eslint) - so unless I'm missing something I guess we can just do a patch release and remove it

**Comment by hzoo** [comment] 2016-03-05 16:03
Ok nvm, I guess we'll need to wait on https://github.com/eslint/eslint/issues/4640 since you can't override espree's visitorkeys either since it's frozen?

Ah I see https://github.com/eslint/eslint/pull/5478

**Comment by nzakas** [comment] 2016-03-05 16:09
Yeah, let's not replace monkey patching with more monkey patching. :) @ilyavolodin said he'd take a look at #4640 this weekend. Otherwise, I'll take a look on Monday.

**Comment by jhabdas** [comment] 2016-03-05 18:30
Curious how this issue could have slipped in. My automated lint test [caught this](https://travis-ci.org/jhabdas/react-native-webpack-starter-kit/builds/113816814) before attempting to submit a PR to my Starter Kit with the updates, as shown here:

![screen shot 2016-03-05 at 12 22 41 pm](https://cloud.githubusercontent.com/assets/440298/13549547/09af029e-e2cd-11e5-90e8-c15cd850e93d.png)

It may be worthwhile to set-up an example project [similar to mine](https://github.com/jhabdas/react-native-webpack-starter-kit) using [Greenkeeper](http://greenkeeper.io) to programmatically submit PRs for updates, and leveraging [Travis](travis-ci.org/) as I have, so you can release with more confidence end-users won't be impacted. It requires very little work and could save hundreds of man hours.

Nevertheless, thanks for continuing to improve this awesome project. I cannot stress enough to others the usefulness of this project in reducing bugs.

**Comment by ilyavolodin** [comment] 2016-03-05 18:37
@jhabdas This issue is not with ESLint, it's with `babel-eslint` relying on the dependency of ESLint. Since we don't run tests for `babel-eslint` there wasn't much we could've done.

**Comment by hzoo** [comment] 2016-03-05 18:40
Yep ^, It's because there is no clear API for ESLint/estraverse/escope for babel-eslint to use to modify it and thus the "monkey patching". Could potentially be caught by setting up an integration test for babel-eslint when pushing a PR. Should be helped with @ilyavolodin's https://github.com/eslint/eslint/pull/5478 PR

**Comment by developit** [comment] 2016-03-05 18:46
@hzoo would it make more sense to cover this via integration tests in `eslint`, or in `babel-eslint`?

**Comment by jhabdas** [comment] 2016-03-05 19:00
@ilyavolodin Given that logic it sounds like this issue should be closed. Am I missing something?

**Comment by ilyavolodin** [comment] 2016-03-05 19:25
@jhabdas Yes. But we are keeping it open for tracking purposes.

**Comment by vasco3** [comment] 2016-03-06 08:07
quick fix, install `estraverse-fb`

**Comment by jhabdas** [comment] 2016-03-06 13:59
A better quick fix IMO is to not upgrade until the problem is solved unless there's a clear benefit to doing so. I hit three new Babel issues alone yesterday trying to upgrade my goods to React Native 0.21. That's not the upgrade path I want, and adding additional dependencies serves only to complicate projects.

**Comment by hzoo** [comment] 2016-03-07 03:31
You can pin to 2.2.x at this point since the VisitorKeys from babel-eslint will still be used.

I made https://github.com/babel/babel-eslint/pull/269 which won't error in eslint@2.3.0 (wraps `estraverse-fb)` since users could still be using eslint < 2.3.0.

```js
// package.json
"babel-eslint": "babel/babel-eslint#eslint-2.3.0",
```

If it's good I can make another 6.0.0 beta release, and backport to 5

**Comment by nzakas** [comment] 2016-03-07 21:25
We're going to pursue a fix via estraverse that would allow us to not even need the visitor keys ahead of time: https://github.com/estools/estraverse/issues/67

**Comment by nzakas** [comment] 2016-03-07 22:16
The PR for estraverse is here: https://github.com/estools/estraverse/pull/68

If accepted, we'll need to do the same thing on esrecurse.

**Comment by heldr** [comment] 2016-03-08 21:57
https://github.com/airbnb/javascript/issues/781

**Comment by niftylettuce** [comment] 2016-03-10 16:07
Shouldn't you deprecate 2.3.0 because of thos?

**Comment by vtambourine** [comment] 2016-03-10 21:11
I am lucky this bug is already opened and can be found on top of issues list! Looking forward to final solution.

**Comment by nzakas** [comment] 2016-03-10 21:30
I'm locking this issue because we are working hard to get this resolved and every new comment creates a notification that distracts us. :)

**Comment by nzakas** [comment] 2016-03-10 22:31
estraverse fix has landed, so I'm starting work on integrating that. esrecurse (which escope relies on) isn't yet ready, so won't be able to merge until that's complete.

**Comment by nzakas** [comment] 2016-03-11 16:31
Published new version of esrecurse, now working on escope.

**Comment by nzakas** [comment] 2016-03-11 16:39
https://github.com/estools/escope/pull/103

**Comment by nzakas** [comment] 2016-03-11 18:34
All dependencies have been updated with new functionality, so removing the "blocked" label.

PR: https://github.com/eslint/eslint/pull/5543

**Comment by nzakas** [comment] 2016-03-11 18:51
PR has been merged. Release is starting.

**Comment by BYK** [comment] 2016-03-13 11:19
Do you think we can close this since 2.4.0 is out now?

**Comment by nzakas** [comment] 2016-03-13 17:39
Yeah, not sure why this didn't automatically close when the PR was merged.

**Closed by nzakas** 2016-03-13 17:39 UTC
Labels: accepted, bug, core
