### ISSUE TITLE
Global .eslintrc breaks when upgrading from eslint v5 to v6

### ISSUE THREAD

**Issue by kurtextrem** [eslint/eslint#12266] opened 2019-09-13 09:12 UTC
**Tell us about your environment**

* **ESLint Version:** 6.3.0
* **Node Version:** 12.10.0
* **npm Version:** 6.10.3

**What parser (default, Babel-ESLint, etc.) are you using?**
default

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
module.exports = {
	root: true,
	parserOptions: {
		ecmaVersion: 10,
		sourceType: 'module',
		ecmaFeatures: {
			impliedStrict: true,
			jsx: true,
		},
	},
	extends: [
		'airbnb', // @TODO: react config outdated
		'eslint:recommended',
		'plugin:node/recommended',
		'plugin:inferno/recommended',
		'plugin:import/errors',
		'plugin:import/warnings',
		'plugin:promise/recommended',
		'plugin:unicorn/recommended',
		'plugin:flowtype/recommended',
		'plugin:jsdoc/recommended',
		'plugin:security/recommended',
		'xo',
		'xo/browser',
		'xo/esnext',
		'standard',
		'react-app',
		'standard-react',
		'canonical',
		'prettier',
		'prettier/react',
		'prettier/standard',
		'plugin:react-perf/recommended',
	],
	plugins: [
		'compat',
		'security',
		'promise',
		'promise-catch',
		'node',
		'babel',
		'unicorn',
		'jsdoc',
		'dependencies',
		'perf-standard',
		'prototype-chain',
		'inferno',
		'sort-imports-es6-autofix',
		'optimize-regex',
		'react-functional-set-state',
		'react-perf',
		'tree-shaking',
		'no-useless-assign',
		'no-unsafe-regex',
		'lean-imports',
		'dollar-sign',
		'prefer-object-spread',
		'class-prefer-methods',
		'sort-class-members',
	],
	env: {
		browser: true,
		jquery: true,
		node: true,
		webextensions: true,
		serviceworker: true,
		worker: true,
		'shared-node-browser': true,
		commonjs: true,
		es6: true,
	},
	rules: {
	}
}

```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

I'm using the vscode-eslint plugin, however as linting breaks when I upgrade eslint *globally*, it is an eslint issue.

```js

```

```bash

```

**What did you expect to happen?**
Globally installed ESLint loads globally installed eslint plugins/presets.

**What actually happened? Please include the actual, raw output from ESLint.**
Error message:
Failed to load config "airbnb" to extend from. Referenced from: C:\Users\Jacob\.eslintrc.js. Please see the 'ESLint' output channel for details.

```
Referenced from: C:\Users\Jacob\.eslintrc.js
    at configMissingError (C:\Users\Jacob\AppData\Roaming\npm\node_modules\eslint\lib\cli-engine\config-array-factory.js:233:9)
    at ConfigArrayFactory._loadExtendedShareableConfig (C:\Users\Jacob\AppData\Roaming\npm\node_modules\eslint\lib\cli-engine\config-array-factory.js:712:23)
    at ConfigArrayFactory._loadExtends (C:\Users\Jacob\AppData\Roaming\npm\node_modules\eslint\lib\cli-engine\config-array-factory.js:617:25)
    at ConfigArrayFactory._normalizeObjectConfigDataBody (C:\Users\Jacob\AppData\Roaming\npm\node_modules\eslint\lib\cli-engine\config-array-factory.js:547:25)
    at _normalizeObjectConfigDataBody.next (<anonymous>)
    at ConfigArrayFactory._normalizeObjectConfigData (C:\Users\Jacob\AppData\Roaming\npm\node_modules\eslint\lib\cli-engine\config-array-factory.js:491:20)
    at _normalizeObjectConfigData.next (<anonymous>)
    at createConfigArray (C:\Users\Jacob\AppData\Roaming\npm\node_modules\eslint\lib\cli-engine\config-array-factory.js:307:25)
    at ConfigArrayFactory.loadInDirectory (C:\Users\Jacob\AppData\Roaming\npm\node_modules\eslint\lib\cli-engine\config-array-factory.js:400:16)
    at CascadingConfigArrayFactory._finalizeConfigArray (C:\Users\Jacob\AppData\Roaming\npm\node_modules\eslint\lib\cli-engine\cascading-config-array-factory.js:380:55)
```

If I comment out airbnb, the error message shows the next (Failed to load plugin 'node')

**Are you willing to submit a pull request to fix this bug?**
Not sure as I have no idea about the code base.

**Comment by valignatev** [comment] 2019-09-13 12:50
Have the same issue after upgrading to `6.3.0` from `5.16.0`.
Other eslint plugins installed:
```
    "eslint-config-airbnb": "18.0.1",
    "eslint-import-resolver-webpack": "0.11.1",
    "eslint-loader": "3.0.0",
    "eslint-plugin-import": "2.18.2",
    "eslint-plugin-jsx-a11y": "6.2.3",
    "eslint-plugin-no-only-tests": "2.3.1",
    "eslint-plugin-react": "7.14.3",
    "eslint-plugin-react-hooks": "2.0.1",
    "eslint-scope": "5.0.0",
```
Node: 12.10.0, yarn 1.17.3, npm 6.11.3
I've checked every eslint release after 5.16.0 (except for alpha and RC releases), they all have this error.
this is the output of eslint if being run directly:
```
Oops! Something went wrong! :(

ESLint: 6.3.0.

ESLint couldn't find the config "airbnb" to extend from. Please check that the name of the config is correct.

The config "airbnb" was referenced from the config file in "/path/to/.eslintrc.json".

If you still have problems, please stop by https://gitter.im/eslint/eslint to chat with the team.
```

**Comment by mysticatea** [comment] 2019-09-13 22:30
Thank you for your report.

But this is intentional change that [the migration guide](https://eslint.org/docs/user-guide/migrating-to-6.0.0#package-loading-simplification) explains. We strongly recommend to not use global installations. See that for details.

I'm closing as a duplicate of #11914.

**Closed by mysticatea** 2019-09-13 22:30 UTC
Labels: bug, triage
