### ISSUE TITLE
RangeError: Maximum call stack size exceeded from `scope-manager`

### ISSUE THREAD

**Issue by mockdeep** [eslint/eslint#9657] opened 2017-11-27 01:45 UTC
Ported over, per request from https://github.com/yannickcr/eslint-plugin-react/issues/1571

**Tell us about your environment**

* **ESLint Version:** 4.11.0
* **Node Version:** 8.1.4
* **npm Version:** 5.0.3

**What parser (default, Babel-ESLint, etc.) are you using?** default

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```yaml
root: true
# have to include `plugin:react/recommended` to avoid errors
extends:
  - eslint:all
  - plugin:eslint-plugin-jsx-a11y/recommended
  - plugin:fp/recommended
  - plugin:import/errors
  - plugin:react/all
plugins: [eslint-plugin-jsx-a11y, fp, import, react]
parserOptions:
  sourceType: module
  ecmaVersion: 2017
  ecmaFeatures:
    jsx: true
    experimentalObjectRestSpread: true
env:
  browser: true
  es6: true
  node: true
globals:
  $: true
settings:
  import/resolver:
    node:
      moduleDirectory: [app/javascript, node_modules, spec/javascript]
rules:
  ### to enable/improve
  class-methods-use-this: off
  fp/no-class: off
  fp/no-delete: off
  fp/no-let: off
  fp/no-loops: off
  fp/no-mutating-methods: off
  fp/no-mutation: off
  fp/no-nil: off
  fp/no-rest-parameters: off
  fp/no-this: off
  fp/no-throw: off
  fp/no-unused-expression: off
  init-declarations: off
  jsx-a11y/anchor-is-valid: off
  jsx-a11y/click-events-have-key-events: off
  jsx-a11y/href-no-hash: off
  jsx-a11y/label-has-for: off
  jsx-a11y/no-onchange: off
  jsx-a11y/no-static-element-interactions: off
  jsx-a11y/onclick-has-role: off
  max-len: [error, 112]
  max-statements: [error, { max: 14 }]
  multiline-comment-style: off
  no-magic-numbers: off
  react/forbid-component-props: off
  react/forbid-prop-types: off
  # https://github.com/yannickcr/eslint-plugin-react/issues/1449
  react/jsx-curly-brace-presence: off
  react/jsx-sort-props: off
  react/no-set-state: off
  # https://github.com/yannickcr/eslint-plugin-react/issues/811
  react/no-unused-prop-types: off
  react/prefer-es6-class: off
  react/require-default-props: off
  react/require-optimization: off
  sort-imports: off # https://github.com/eslint/eslint/issues/7766
  sort-keys: off

  ### departures from default
  brace-style: [error, 1tbs, { allowSingleLine: true }]
  comma-dangle: [error, always-multiline]
  func-style: [error, declaration]
  function-paren-newline: [error, consistent]
  id-length: [error, { exceptions: [_, $] }]
  indent: [error, 2]
  jsx-quotes: [error, prefer-single]
  max-statements-per-line: [error, { max: 2 }]
  multiline-ternary: [error, never]
  newline-per-chained-call: [error, { ignoreChainWithDepth: 3 }]
  no-extra-parens: [error, all, { nestedBinaryExpressions: false, ignoreJSX: 'multi-line' }]
  no-multiple-empty-lines: [error, { max: 1, maxEOF: 0, maxBOF: 0 }]
  no-underscore-dangle: [error, { allowAfterThis: true }]
  object-property-newline: [error, { allowMultiplePropertiesPerLine: true }]
  one-var: [error, never]
  padded-blocks: [error, never]
  prefer-arrow-callback: [error, { allowNamedFunctions: true }]
  prefer-destructuring: [error, { array: false }]
  quote-props: [error, as-needed, { keywords: true }]
  quotes: [error, single]
  react/jsx-indent-props: [error, 2]
  react/jsx-indent: [error, 2]
  react/jsx-wrap-multilines: [error, { declaration: false }]
  space-before-function-paren: [error, { anonymous: always, named: never }]
  spaced-comment: [error, always, { markers: [=] }]

  ### disabled for good
  array-element-newline: off
  capitalized-comments: off
  jsx-a11y/no-autofocus: off
  line-comment-position: off
  no-inline-comments: off
  no-ternary: off
  react/jsx-filename-extension: off
  react/jsx-handler-names: off
  react/jsx-max-props-per-line: off
  require-jsdoc: off
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

I made a typo in one of my tests, and got a weird `RangeError` from ESLint.

```jsx
const props = {...props, scratch: {mode: 'edit'}};
const component = shallow(<TaskEditableTitle {...props} />);
```

```bash
./node_modules/eslint/bin/eslint.js ./ --ext .js,.jsx --cache
```

**What did you expect to happen?**

Some complaint about invalid syntax, or maybe a rule violation if it is technically valid syntax. (Doesn't appear to be...)

**What actually happened? Please include the actual, raw output from ESLint.**

```
Maximum call stack size exceeded
RangeError: Maximum call stack size exceeded
    at ScopeManager.__get (/home/fletch/Dropbox/projects/web_apps/questlog/node_modules/eslint-scope/lib/scope-manager.js:85:10)
    at ScopeManager.acquire (/home/fletch/Dropbox/projects/web_apps/questlog/node_modules/eslint-scope/lib/scope-manager.js:127:29)
    at getScope (/home/fletch/Dropbox/projects/web_apps/questlog/node_modules/eslint/lib/linter.js:613:36)
    at Object.getScope (/home/fletch/Dropbox/projects/web_apps/questlog/node_modules/eslint/lib/linter.js:843:37)
    at Object.variablesInScope (/home/fletch/Dropbox/projects/web_apps/questlog/node_modules/eslint-plugin-react/lib/util/variable.js:36:23)
    at findSpreadVariable (/home/fletch/Dropbox/projects/web_apps/questlog/node_modules/eslint-plugin-react/lib/rules/no-danger-with-children.js:23:27)
    at node.properties.find.prop (/home/fletch/Dropbox/projects/web_apps/questlog/node_modules/eslint-plugin-react/lib/rules/no-danger-with-children.js:38:28)
    at Array.find (native)
    at findObjectProp (/home/fletch/Dropbox/projects/web_apps/questlog/node_modules/eslint-plugin-react/lib/rules/no-danger-with-children.js:34:30)
    at node.properties.find.prop (/home/fletch/Dropbox/projects/web_apps/questlog/node_modules/eslint-plugin-react/lib/rules/no-danger-with-children.js:40:20)
```

**Comment by ljharb** [comment] 2017-11-27 03:26
For reference, in node, when I try to run `const props = { ...props };`, I get either `ReferenceError: props is not defined` or `SyntaxError: Identifier 'props' has already been declared`.

**Comment by not-an-aardvark** [comment] 2017-11-28 01:35
Although this code could never actually execute, core rules and APIs are generally supposed to work if the code is valid syntax.

The stack trace seems to involve the `context.getScope` method. However, I'm unsure what's causing this crash because it's not clear to me how `react/no-danger-with-children` is calling the `context.getScope` API. Would it be possible to create a simplified example of a rule that only calls `context.getScope` and causes this crash?

If not, then I can try to figure out what's going on in `react/no-danger-with-children`, but it would be easier to determine the bug with a simpler example.

**Comment by ljharb** [comment] 2017-11-28 05:13
https://github.com/yannickcr/eslint-plugin-react/blob/master/lib/util/variable.js#L36 ← https://github.com/yannickcr/eslint-plugin-react/blob/master/lib/util/variable.js#L61 ← https://github.com/yannickcr/eslint-plugin-react/blob/master/lib/rules/no-danger-with-children.js#L23 ← … ← https://github.com/yannickcr/eslint-plugin-react/blob/master/lib/rules/no-danger-with-children.js#L114 - not sure if that helps or not :-/

**Comment by mysticatea** [comment] 2017-11-28 06:45
The [findObjectProp](https://github.com/yannickcr/eslint-plugin-react/blob/c072c899083bbbfba0a3d51ce0fe4b152f934c27/lib/rules/no-danger-with-children.js#L30-L45) function itself looks to be called recursively.

1. `findObjectProp` finds the variable of a spread property.
2. If it was found, it calls `findObjectProp(variable.defs[0].node.init, propName);`. But the `init` includes the spread property, then go back 1.

**Comment by ljharb** [comment] 2017-11-29 08:01
@mysticatea hmm; you're right that it's called recursively; are you suggesting that by using the higher stackTraceLimit, we can figure out where we're not stopping the recursion?

**Comment by mysticatea** [comment] 2017-11-29 08:15
@ljharb Yes. I guessed the cause of confusion is that the stack trace didn't show actual recursive calls because `context.getScope()` has deep depth calling.

**Comment by not-an-aardvark** [comment] 2018-01-19 15:40
Closing because this doesn't seem to be an issue with ESLint core.

**Closed by not-an-aardvark** 2018-01-19 15:40 UTC
Labels: works as intended
