### ISSUE TITLE
Bug: flat config changing a plugin name will lead to chaos

### ISSUE THREAD

**Issue by kkmuffme** [eslint/eslint#17371] opened 2023-07-15 19:09 UTC
### Environment

Node version: 16.19.0
npm version: 8.9.0
Local ESLint version: 8.45.0
Global ESLint version: 8.45.0
Operating System: RHEL

### What parser are you using?

Default (Espree)

### What did you do?

<details>
<summary>Configuration</summary>

```
import jsdoc from "eslint-plugin-jsdoc";

export default [
	{
		plugins: {
			jsdoc,
		},
		rules: {
			...jsdoc.configs.recommended.rules,
		}
	},
	{
		plugins: {
			abc: jsdoc,
		},
		rules: {
			'abc/check-tag-names': 'error',
		}
	},
];
```
</details>

```js
/**
 * foo
 *
 * @param {string} foo
 *
 * @return {string}
 */
```

### What did you expect to happen?

That rules are deduplicated/overwritten using their "original" plugin name instead of their "custom" name, as otherwise chaos will ensue, if any imported config renames a plugin.
You then have to manually duplicate all the rules from that plugin again, to disable them all and re-enable with the default name.

### What actually happened?

abc/check-tag-names and jsdoc/check-tag-names are the same rules, however because it's renamed in 1 case, I get errors for the same code twice, instead of it being overwritten.

### Link to Minimal Reproducible Example

https://eslint.org/docs/latest/use/configure/configuration-files-new#using-configurations-included-in-plugins

### Participation

- [ ] I am willing to submit a pull request for this issue.

### Additional comments

This might seem irrelevant/on purpose at first, when checking how most eslint configs work today (with plugins) this makes using plugins a pain though, when using flat config.

**Comment by fasttime** [comment] 2023-07-16 20:02
Could you elaborate on this a little more? For example, what would a problem message (including rule name) look like when reported by a deduplicated rule? What should happen if rules `abc/check-tag-names` and `jsdoc/check-tag-names` have different configurations? Which configuration would have to be used in this case - or should this be forbidden?

Also, I don't understand this sentence:
> You then have to manually duplicate all the rules from that plugin again, to disable them all and re-enable with the default name.

Looking at the provided sample config and file, I can't see any of these three actions taking place:

* to manually duplicate all the rules
* to disable them all
* re-enable with the default name

Could you show an example that makes it clear what each of the sentences means, and why the current behavior _makes using plugins a pain_?

**Comment by aladdin-add** [comment] 2023-07-17 07:18
To me it seems to be working as expected.

To use`jsdoc.configs.recommended.rules`, it's assuming you're using the default namespace `jsdoc`. If not, you cannot use it directly.

**Comment by matwilko** [comment] 2023-07-17 10:35
This seems like the completely intended behaviour of flat config? You can specify any arbitrary plugin with any name you like, as long as when the individual config elements are merged for a single file, no two plugins have the same name.

This doesn't preclude the same exact plugin having two or more different names upon merge - but ESLint assumes that if you gave the plugin a custom name, you did that _on purpose_, so wouldn't change that.

Is this perhaps a confusion of how the merging process happens, and users might potentially think that they can only configure `rules` in a config element if the plugin those rules comes from also appears in that same config element?

Do we need to clarify the docs on flat config to spell out that you can specify any `rules` you like in a config element, as long as the plugin those rules come from gets merged into the config for that file from another element before/after that element?

**Comment by matwilko** [comment] 2023-07-17 13:16
I can see how theoretically this could be a problem, but since most of the ecosystem is yet to transition to flat configs, do you have a concrete example of these sort of conflicts happening in the real world?

Is this a case of providing some clear guidance in plugin/config writing guides and the flat config migration docs to say that plugins should usually be named whatever ESLint would have named them previously in order to ease transition for users?

Also, your stated problem of trying to shorten rule names is solvable by yourself - you have direct access to the configuration object, so you can write a helper function that rewrites the config to use a different name and rename all the rule configurations. As far I can tell, this is part of the planned flexibility and explicitness of the new system - the user has full control of what goes into their configuration and there's no implicit require'ing going on in the background.

e.g.
```js
function renamePluginsInConfig(config, pluginNameMap) {
    if (Array.isArray(config)) {
        return config.map(c => renamePluginsInConfig(c, pluginNameMap));
    } else {
        return {
            ...config,
            { plugins: mapKeys(config.plugins, pluginName => pluginName in pluginNameMap ? pluginNameMap[pluginName] : pluginName) },
            { rules: mapKeys(config.rules, ruleName => {
                    for (const [pluginNameOld, pluginNameNew] of Object.entries(pluginNameMap)) {
                        if (ruleName.startsWith(`${pluginNameOld}/`)) {
                            return `${pluginNameNew}/${ruleName.slice(pluginNameOld.length + 1)}`;
                        }
                    }

                    return ruleName;
                })
            }
        }
    }
}

function mapKeys(obj, keyMapFunc) {
    if (!obj) { return {}; }
    return Object.fromEntries(
        Object.entries(obj).map(([key, value]) => [keyMapFunc(key), value])
    );
}
```

^^ this is all just example code to demonstrate, I haven't tested it works, it just outlines that you can reshape things coming from external packages yourself if they don't meet your specific needs - I've already had to do plenty of stuff like this in a new project I set up recently trying to use flat config with lots of plugins that haven't transitioned yet!

**Comment by nzakas** [comment] 2023-07-17 14:51
To close the loop on this: this is 100% the expected behavior. When you register two namepaces for the same plugin, you are able to configure two completely separate instances of the same rule. This has been a requested feature of ESLint for several years. So, the behavior you describe, where you are getting two warnings from the same rule, one for each namespace, is what should be happening.

There is definitely a case where if you're using an exported config from a plugin, and that config includes their preferred namespace, you'll need to negotiate that on your own. However, I'd say that is an advanced use of plugins, so you'd need to work through those details.

**Closed by nzakas** 2023-07-17 14:51 UTC
Labels: bug, repro:needed

**Comment by matwilko** [comment] 2023-07-17 14:56
> Take it as a joke, but: great approach to engineering - [we designed a new aircraft we know has a config flaw, but let's wait until it crashes before we fix it](https://en.wikipedia.org/wiki/Boeing_737_MAX_groundings) 😁

I'm taking this in stride, but maybe just be a bit careful with your tone and how it might come off - I'm trying to help and be collaborative, not confrontational 😄

The question wasn't intended as a "is this actually a real problem in the world as it stands and if not, can ESLint just not do anything about it?" - it was to explore whether the current system and guidance have already generated problematic scenarios, and how likely those are, and so from there the maintainers can decide what, if anything, needs to change - whether that be a documentation update to try to steer plugin/config authors in a certain direction to avoid conflicts, or whether that part of the system needs a rethink while there's still time.

It's a pretty common ask in many issues I've come across in ESLint to provide some analysis of the existing ecosystem to demonstrate that whatever you're talking about is both a real problem that is currently being experienced, and how impacting that problem is so the solution can be tailored.

In this case, there's the added dimension of "is this an artifact of the ecosystem being in the middle of a transition, and will it stop being a problem in the future when things are settled and there's proper guidance?"

So no, not a joke question.

> The docs would have to say that you are not allowed to rename the plugins if you want to have other people use your config AND that you cannot rename a plugin if you import any existing config for it, as you'd end up getting all errors in duplicate for "warn"/"error" and "off" won't work at all (since by default all rules are off, so only ones enabled by a plugin config you imported will be on, but you cannot "off" them with your custom name)

> Now why would anybody in their right mind rename a plugin?

But again, users have full control over their config now - my suggestion was that plugin/config authors should make the plugin name they use predictable and consistent with the old plugin name. If users wish to combine multiple third-party configs together that _may_ have conflicting plugin names, they have the tools they need to fix things up - they can modify the config objects.

For config publishers like `eslint-config-hardcore` et al., it might be the case that they make changes to other configs that they import to make things more consistent/compatible in their exported config. This is something ESLint should probably give some guidance on before the hard transition to flat config in ESLint v9.

> which is with the imported configs that might have renamed.

Multiple configs _may_ import the same plugin under different names, sure, but is this _likely_?

Most plugins are likely to only provide configuration that lists themselves as a plugin.

`eslint-config-*` packages might overlap, but I think in that case it's up to the user to resolve any incompatibilities between them - you're in JS land, you have the tools available to you to fix up the config objects so they are compatible 😄

I could imagine there being a small npm package with some helpers for modifying ESLint flat config elements like renaming plugins etc., but I don't think those sorts of helpers would belong in core ESLint.

> I just think the current implementation of it - that "renaming" essentially creates a completely new set of plugin rules - does not only not add any value, but in fact makes it worse (duplicate errors or double the amount of config needed)

> I guess, the "fix" would be relatively straightforward too: eslint should internally use the default names for overwrites, so the final config does not end up with duplicate rules, if any plugin was renamed.

I don't think being able to give plugins an arbitrary name is _just_ about being able to rename all the plugin rules etc. There's wider potential applications, but the point is is that it's explicit on the part of the user. To have ESLint start re-introducing implicit resolution behaviour behind the scenes seems to go against that.

**Comment by aladdin-add** [comment] 2023-07-18 02:23
Renaming is an advanced feature that is best suited for experienced users. For the majority of users, it is recommended to stick with the default namespace. It would not hurt to highlight this point in the document to ensure users are aware of the availability and suitability of the default namespace.
