### ISSUE TITLE
SyntaxError: Unexpected token = on class fat arrow functions

### ISSUE THREAD

**Issue by moimael** [eslint/eslint#9848] opened 2018-01-15 15:01 UTC
**Tell us about your environment**

* **ESLint Version:** 4.15.0
* **Node Version:** 8.9.4
* **npm Version:** 5,6,0

**What parser (default, Babel-ESLint, etc.) are you using?**
babel-eslint

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
module.exports = {
  extends: ['airbnb', 'plugin:jest/recommended'],
  parser: 'babel-eslint',
  plugins: [
    'react',
    'jest',
  ],
  settings: {
    'import/resolver': {
      webpack: {
        config: 'webpack.config.js',
        'config-index': 2,
      },
    },
  },
  env: {
    browser: true,
    jest: true,
    node: true,
  },
  rules: {
    indent: ['error', 2, {
      SwitchCase: 1,
      VariableDeclarator: 1,
      outerIIFEBody: 1,
      MemberExpression: 1,
      FunctionDeclaration: {
        parameters: 1,
        body: 1,
      },
      FunctionExpression: {
        parameters: 1,
        body: 1,
      },
    }],
    'no-multi-str': 'off',
    // Weird bug with isNan, need to investigate
    'no-restricted-globals': 'off',
    // Seems broken
    'jsx-a11y/label-has-for': 'off',
    // Do not work with react-router
    'jsx-a11y/anchor-is-valid': 'off',
    // Enable again when we have time to fix this
    'jsx-a11y/mouse-events-have-key-events': 'off',
    // Enable again when we have time to fix this
    'jsx-a11y/click-events-have-key-events': 'off',
    'jsx-a11y/media-has-caption': 'off',
    'react/jsx-filename-extension': [1, {
      extensions: ['.js', '.jsx'],
    }],
    'react/jsx-sort-props': 2,
    'import/extensions': 'off',
    'import/no-extraneous-dependencies': 'off',
    'import/no-dynamic-require': 'off',
    'import/no-named-as-default': 'off',
    'react/no-multi-comp': 'off',
    'arrow-parens': 'off',
    'react/forbid-prop-types': 'off',
    'react/no-unused-prop-types': [1, {
      skipShapeProps: true,
    }],
    // Re-enable this rule when fixed in npm release
    'react/no-array-index-key': 'off',
    // This rule might make sense, we should discuss it but right now throws hundreds of errors.
    'react/require-default-props': 'off',
  },
};
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
onLooped = (fromSegment, toSegment) => {}
```

```bash
npm run eslint src
```

**What did you expect to happen?**
Eslint would show no errors.

**What actually happened? Please include the actual, raw output from ESLint.**

 FAIL  src/client/apps/admin/form-builder/components/dnd/item-types.js
  ● Test suite failed to run

    /home/mlavault/Development/galaxy/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:644
        onLooped = (fromSegment, toSegment) => {
                 ^
    
    SyntaxError: Unexpected token =
      
      at Object.<anonymous> (node_modules/eslint/lib/linter.js:18:24)

It seems like eslint cannot parse class fat arrow functions. Any idea on a workaround ? 
Thanks !

**Comment by pmcelhaney** [comment] 2018-01-15 19:18
Can you show the full text of item-types.js?

**Comment by moimael** [comment] 2018-01-16 11:07
Actually it seems the error is in eslint code-path-analyzer. I get the same error 742 times. Line 644 there is an arrow function and it seems it breaks everything.

**Comment by moimael** [comment] 2018-01-16 11:09
Everything works as expected if I change the line 644 to use a classic function

**Comment by pmcelhaney** [comment] 2018-01-16 11:14
Okay, it would be helpful to see the context around line 644. 

Better still: can you delete most of the file but still reproduce the error (minimal test case)?

**Comment by moimael** [comment] 2018-01-16 12:26
```
    /**
     * This is called on a code path looped.
     * Then this raises a looped event.
     *
     * @param {CodePathSegment} fromSegment - A segment of prev.
     * @param {CodePathSegment} toSegment - A segment of next.
     * @returns {void}
     */
    onLooped = (fromSegment, toSegment) => {
        if (fromSegment.reachable && toSegment.reachable) {
            debug.dump(`onCodePathSegmentLoop ${fromSegment.id} -> ${toSegment.id}`);
            this.emitter.emit(
                "onCodePathSegmentLoop",
                fromSegment,
                toSegment,
                this.currentNode
            );
        }
    };
```
It's the only arrow function in the file. Changing it to a normal function solves the issue.

**Comment by pmcelhaney** [comment] 2018-01-16 15:57
Oh, sorry, I get it now. The syntax error is in ESLint itself!

https://github.com/eslint/eslint/blob/master/lib/code-path-analysis/code-path-analyzer.js#L646

**Comment by platinumazure** [comment] 2018-01-16 16:03
@moimael Our master branch uses a shorthand method, not a class property. Are you using some sort of transpiler (e.g., Babel) which is transforming ESLint itself in your project? You might want to check your configuration and avoid transpiling ESLint, unless your project is actually using/deploying ESLint (e.g., if your project is an online text editor or linter).

**Comment by not-an-aardvark** [comment] 2018-03-05 18:04
Closing because this is working as intended.

**Closed by not-an-aardvark** 2018-03-05 18:04 UTC
Labels: question
