### ISSUE TITLE
no-shadow-restricted-names throws error on catch with no exception identifier

### ISSUE THREAD

**Issue by noctre-net** [eslint/eslint#10026] opened 2018-02-27 11:28 UTC
* **ESLint Version: 4.18.1**
* **Node Version: v6.11.0**
* **npm Version: 3.10.10**

* **Parser: 'babel-eslint'**

Source code like this
```js
/*eslint no-shadow-restricted-names: "error"*/
function isValidJSON(text) {
    try {
        JSON.parse(text);
        return true;
    } catch {
        return false;
    }
}
```

causes
```bash
TypeError: Cannot read property 'name' of null
    at checkForViolation (c:\myProject\node_modules\eslint\lib\rules\no-shadow-restricted-names.js:34:38)
    at CatchClause (c:\myProject\node_modules\eslint\lib\rules\no-shadow-restricted-names.js:65:15)
    at listeners.(anonymous function).forEach.listener (c:\myProject\node_modules\eslint\lib\util\safe-emitter.js:47:58)
    at Array.forEach (native)
    at Object.emit (c:\myProject\node_modules\eslint\lib\util\safe-emitter.js:47:38)
    at NodeEventGenerator.applySelector (c:\myProject\node_modules\eslint\lib\util\node-event-generator.js:251:26)
    at NodeEventGenerator.applySelectors (c:\myProject\node_modules\eslint\lib\util\node-event-generator.js:280:22)
    at NodeEventGenerator.enterNode (c:\myProject\node_modules\eslint\lib\util\node-event-generator.js:294:14)
    at CodePathAnalyzer.enterNode (c:\myProject\node_modules\eslint\lib\code-path-analysis\code-path-analyzer.js:608:23)
    at Traverser.enter [as _enter] (c:\myProject\node_modules\eslint\lib\linter.js:1017:32)
```

Adding check for params existence  in `no-shadow-restricted-names.js` would fix the problem:
```js
CatchClause(node) {
  if(node.param) {
    checkForViolation(node.param);
  }
}
```

**Comment by not-an-aardvark** [comment] 2018-02-27 15:37
Closing as a duplicate of https://github.com/eslint/eslint/pull/9613

**Closed by not-an-aardvark** 2018-02-27 15:37 UTC
Labels: triage
