### ISSUE TITLE
Error with prefer-const rule

### ISSUE THREAD

**Issue by pnadalini** [eslint/eslint#15022] opened 2021-09-03 02:33 UTC
**Tell us about your environment**

Environment Info:

Node version: v16.4.2
npm version: v7.18.1
Local ESLint version: v7.27.0 (Currently used)
Global ESLint version: Not found
Operating System: darwin 20.6.0

**What parser (default, `@babel/eslint-parser`, `@typescript-eslint/parser`, etc.) are you using?**

```
"parser": "@typescript-eslint/parser"
```

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
{
  "parser": "@typescript-eslint/parser",
  "extends": ["eslint:recommended", "plugin:react/recommended", "plugin:@typescript-eslint/eslint-recommended", "plugin:@typescript-eslint/recommended", "prettier"],
  "plugins": ["@typescript-eslint", "react-hooks", "prettier"],
  "parserOptions": {
    "ecmaVersion": 2018,
    "sourceType": "module",
    "ecmaFeatures": {"jsx": true}
  },
  "rules": {
    "@typescript-eslint/ban-types": "off",
    "@typescript-eslint/explicit-function-return-type": "off",
    "@typescript-eslint/explicit-member-accessibility": ["off"],
    "@typescript-eslint/explicit-module-boundary-types": "off",
    "@typescript-eslint/member-ordering": [
      "error",
      {
        "default": {
          "memberTypes": [
            "public-static-field",
            "protected-static-field",
            "private-static-field",
            "public-static-method",
            "protected-static-method",
            "private-static-method",
            "public-instance-field",
            "protected-instance-field",
            "private-instance-field",
            "public-abstract-field",
            "protected-abstract-field",
            "private-abstract-field",
            "public-constructor",
            "protected-constructor",
            "private-constructor",
            "public-instance-method",
            "protected-instance-method",
            "private-instance-method",
            "public-abstract-method",
            "protected-abstract-method",
            "private-abstract-method"
          ],
          "order": "as-written"
        }
      }
    ],
    "@typescript-eslint/no-empty-function": "off",
    "@typescript-eslint/no-empty-interface": "off",
    "@typescript-eslint/no-explicit-any": "off",
    "@typescript-eslint/no-inferrable-types": "off",
    "@typescript-eslint/no-non-null-assertion": "off",
    "@typescript-eslint/no-unused-vars": "error",
    "@typescript-eslint/no-var-requires": "off",
    "@typescript-eslint/no-use-before-define": ["error", "nofunc"],
    "no-async-promise-executor": "off",
    "arrow-body-style": "off",
    "eqeqeq": ["error", "smart"],
    "no-console": ["error", {"allow": ["info"]}],
    "no-duplicate-imports": ["error"],
    "no-useless-computed-key": ["error"],
    "no-useless-rename": ["error"],
    "no-var": ["error"],
    "no-fallthrough": "off",
    "object-shorthand": ["error"],
    "prefer-const": ["error"],
    "prefer-arrow-callback": "off",
    "prettier/prettier": "error",
    "react-hooks/exhaustive-deps": ["off"],
    "react-hooks/rules-of-hooks": ["error"],
    "react/display-name": "off",
    "react/jsx-boolean-value": ["error", "never"],
    "react/jsx-curly-brace-presence": ["error", {"props": "never", "children": "ignore"}],
    "react/jsx-fragments": ["error", "syntax"],
    "react/jsx-no-target-blank": "off",
    "react/no-unescaped-entities": ["off"],
    "react/prop-types": "off",
    "require-yield": "off"
  },
  "settings": {
    "react": {"version": "detect"}
  },
  "overrides": [
    {
      "files": ["**/module/*/*/index.ts", "**/module/*/*/index.tsx", "**/module/main/index.ts", "**/module/main/index.tsx"],
      "rules": {
        "@typescript-eslint/explicit-function-return-type": ["error"]
      }
    }
  ]
}
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
        let timer: NodeJS.Timeout;

        const clear = () => {
            clearInterval(timer);
            // other code
            window.location.reload();
        };

        const child = window.open("example.com", "Login", "toolbar=no,scrollbars=yes,resizable=yes");

        const checkChild = () => {
            if (child && child.closed) {
                clear();
            }
        };

        timer = setInterval(checkChild, 500);
```

(I have the configuration in a different file and in the root I have a reference to that file as well. Like it's shown in [this project](https://github.com/neowu/frontend-demo-project/blob/master/website-frontend/.eslintrc.json))
```bash
eslint -c webpack/lint/.eslintrc.json \"{src,test}/**/*.{ts,tsx}\"
```

**What did you expect to happen?**
The code should open a window and check with an interval of `500` check if the new opened page is closed to run the code inside `clear`.

**What actually happened? Please copy-paste the actual, raw output from ESLint.**
The eslint configuration throws an error claiming that `timer` should be a `const` when I'm assigning it at the end of my code example.
And due to the rules I have configures if I move the functions around it will throw errors that the variables are being used before they are declared.
Output:

>   23:13  error  'timer' is never reassigned. Use 'const' instead  prefer-const
> 
> ✖ 1 problem (1 error, 0 warnings)

**Steps to reproduce this issue:**

1. Copy the configurations I have inserted here for a react / typescript project
2. Create a new react function component
3. Copy the code I added here and run eslint check

**Are you willing to submit a pull request to fix this bug?**

**Comment by mdjermanovic** [comment] 2021-09-03 08:29
Hi @pnadalini, thanks for the issue!

You can use [ignoreReadBeforeAssign](https://eslint.org/docs/rules/prefer-const#ignorereadbeforeassign) option:

> This is an option to avoid conflicting with `no-use-before-define` rule (without `"nofunc"` option).
> If `true` is specified, this rule will ignore variables that are read between the declaration and the first assignment.
> Default is `false`.

With `{ ignoreReadBeforeAssign: true }` there will be no `prefer-const` errors on `let timer`.

```js
/* eslint prefer-const: ["error", { ignoreReadBeforeAssign: true }] */

let timer;

const clear = () => {
  clearInterval(timer);
  // other code
  window.location.reload();
};

const child = window.open("example.com", "Login", "toolbar=no,scrollbars=yes,resizable=yes");

const checkChild = () => {
  if (child && child.closed) {
    clear();
  }
};

timer = setInterval(checkChild, 500);
```

[Online Demo](https://eslint.org/demo#eyJ0ZXh0IjoiLyogZXNsaW50IHByZWZlci1jb25zdDogW1wiZXJyb3JcIiwgeyBpZ25vcmVSZWFkQmVmb3JlQXNzaWduOiB0cnVlIH1dICovXG5cbmxldCB0aW1lcjtcblxuY29uc3QgY2xlYXIgPSAoKSA9PiB7XG4gIGNsZWFySW50ZXJ2YWwodGltZXIpO1xuICAvLyBvdGhlciBjb2RlXG4gIHdpbmRvdy5sb2NhdGlvbi5yZWxvYWQoKTtcbn07XG5cbmNvbnN0IGNoaWxkID0gd2luZG93Lm9wZW4oXCJleGFtcGxlLmNvbVwiLCBcIkxvZ2luXCIsIFwidG9vbGJhcj1ubyxzY3JvbGxiYXJzPXllcyxyZXNpemFibGU9eWVzXCIpO1xuXG5jb25zdCBjaGVja0NoaWxkID0gKCkgPT4ge1xuICBpZiAoY2hpbGQgJiYgY2hpbGQuY2xvc2VkKSB7XG4gICAgY2xlYXIoKTtcbiAgfVxufTtcblxudGltZXIgPSBzZXRJbnRlcnZhbChjaGVja0NoaWxkLCA1MDApOyIsIm9wdGlvbnMiOnsicGFyc2VyT3B0aW9ucyI6eyJlY21hVmVyc2lvbiI6MTIsInNvdXJjZVR5cGUiOiJzY3JpcHQiLCJlY21hRmVhdHVyZXMiOnt9fSwicnVsZXMiOnt9LCJlbnYiOnt9fX0=)

**Comment by Shinigami92** [comment] 2021-09-23 11:00
We at Vite are also affected by this 🤔 

An example can be found here: https://github.com/vitejs/vite/blob/fe25567828e7a5cadc6c009ae674a59670e14a49/packages/vite/src/node/ssr/ssrExternal.ts#L61-L74

![image](https://user-images.githubusercontent.com/7195563/134495843-e2e59f83-38bf-462a-bc98-48dea73c3800.png)

Same for `requireEntry` and in total 14 warnings in the whole project.
Feel free to check out the project and analyse it. Just run `yarn install && yarn lint` in root folder.

**Comment by mdjermanovic** [comment] 2021-09-23 13:22
@Shinigami92 your example is different because there's assignment in an inner scope, and that would be a bug.

I think the cause is same as in https://github.com/eslint/eslint/issues/14977, you're using [`ecmaVersion: 'latest'`](https://github.com/vitejs/vite/blob/83881aa0e12f2c10275b695bba1acb48de3aeafe/.eslintrc.js#L14) with `@typescript-eslint/parser` which doesn't support that value, so the scope analysis is done as if it was es5 code (without block scopes). The solution is to not use `'latest'` with `@typescript-eslint/parser` because it's not a valid option for that parser.

**Comment by Shinigami92** [comment] 2021-09-23 14:03
@mdjermanovic you are right 🎉 
setting it to `ecmaVersion: 2021` solved it

**Comment by mdjermanovic** [comment] 2021-09-23 15:16
Thanks for the info! Per the thumbs up reaction on https://github.com/eslint/eslint/issues/15022#issuecomment-912360438 it seems that the original problem has been resolved as well, so I'm closing this issue.

**Closed by mdjermanovic** 2021-09-23 15:16 UTC
Labels: bug, repro:needed
