### ISSUE TITLE
Feature Request: multiple max-len rules

### ISSUE THREAD

**Issue by kmdavis** [eslint/eslint#6785] opened 2016-07-28 16:03 UTC
It would be nice to be able to configure eslint such that a line with a length greater than, say 80 characters, is a warning, but a length greater than, say 100, is an error.

**Comment by alberto** [comment] 2016-07-28 19:15
Duplicate of https://github.com/eslint/eslint/issues/6776

**Closed by alberto** 2016-07-28 19:15 UTC
Labels: triage
