### ISSUE TITLE
/* in yaml comment actually acts as a multiline comment

### ISSUE THREAD

**Issue by austinhyde** [eslint/eslint#6545] opened 2016-06-27 22:09 UTC
**What version of ESLint are you using?**

2.13.1

**What parser (default, Babel-ESLint, etc.) are you using?**

babel-eslint

**Please show your full configuration:**

See below

**What did you do? Please include the actual source code causing the issue.**

```yaml
# adsf/*adsf
parserOptions:
  ecmaFeatures:
    jsx: true
    modules: true
```

**What did you expect to happen?**

Lint with jsx/modules semantics

**What actually happened? Please include the actual, raw output from ESLint.**

Linted without jsx/modules semantics

```
$ ./node_modules/.bin/eslint .

path/to/my/file.js
  1:1  error  Parsing error: The keyword 'import' is reserved
...
```

I've been able to reproduce this 100% of the time in different configurations, and 100% of the time, it behaves like a multiline comment.

Bonus round:

```yaml
# adsf/*adsf
asdflk;jasdfjkl
# asdf*/asdf
parserOptions:
  ecmaFeatures:
    jsx: true
    modules: true
```

lints correctly. Removing the first comment yields a configuration parse error, as you'd expect.

**Comment by mysticatea** [comment] 2016-06-28 11:50
Thank you for this issue.

```yaml
parserOptions:
  ecmaFeatures:
    jsx: true
    modules: true
```

There is no `modules: true` configuration for default parser. ([Specifying Parser Options](http://eslint.org/docs/user-guide/configuring#specifying-parser-options))
Please try `sourceType: "module"` instead.

```yaml
parserOptions:
  sourceType: "module"
  ecmaVersion: 6
  ecmaFeatures:
    jsx: true
```

**Comment by austinhyde** [comment] 2016-06-28 13:45
Sorry for the confusion: I believe `modules: true` is left over from a configuration for an older version. I've also confirmed this with the correct configuration as you suggested. Regardless, this bug affects any configuration, regardless of semantic validity

**Comment by platinumazure** [comment] 2016-06-28 15:03
@austinhyde Can you try reproducing with a rule config? For example, just have semi on and run it against code missing semicolons. That way we'll know for sure if it's a configuration parsing error rather than possible incorrect configuration.

**Comment by vitorbal** [comment] 2016-06-28 15:04
Hm, I tried to reproduce this but couldn't. I also tried to isolate the problem to the `js-yaml` library but also couldn't reproduce it there, it parses the config just fine.

**Comment by austinhyde** [comment] 2016-06-28 15:08
I was able to reproduce this with both valid and invalid configurations, as well as simple single-rule configurations and the large project configuration where I encountered this. I was simply trying to provide a reduced test case.

I'm not sure if it matters, but this was in the old-style `.eslintrc` file, not a `.eslintrc.yaml` file.

I'll throw up a simple project soon that reproduces the issue.

**Comment by vitorbal** [comment] 2016-06-28 15:54
@austinhyde thanks, that would be really helpful! Maybe being old-style matters because it follows a different code path in the source code, but i'm not very familiar with that part of the code.

**Comment by nzakas** [comment] 2016-06-28 15:57
Yes, `.eslintrc` is the old (deprecated) format that recognized both JS-style comments and YAML-style comments. If you don't want that behavior, just add ".yml" to the filename to parse it in strict YAML mode. 

We can't change the old format because we don't know who is using it, but we did deprecate it and recommend using one of the formats with a file extension.

**Comment by nzakas** [comment] 2016-06-28 15:58
Ref: http://eslint.org/docs/user-guide/configuring#configuration-file-formats

**Comment by vitorbal** [comment] 2016-06-29 12:17
That makes a lot of sense. @austinhyde can you confirm that adding the "`.yml`" to the file fixes the problem?

**Comment by austinhyde** [comment] 2016-06-29 13:54
Actually, yes, that fixes it! I can't believe I didn't try that to begin with. Would you still like me to make a sample project? Or is this one of those cases where it's not worth the effort to reproduce/fix because it's a deprecated thing?

It's all the same to me, it's easy enough to avoid in my config file, I just wanted to make sure that it was reported if it was a larger issue.

**Comment by nzakas** [comment] 2016-06-29 17:47
There's no need for you to do any additional work here, as the behavior is expected.

**Comment by platinumazure** [comment] 2016-06-29 20:57
Closing, as the issue seems to be resolved. Please reopen if there is more to discuss.

**Closed by platinumazure** 2016-06-29 20:57 UTC
Labels: question
