### ISSUE TITLE
Enhancement: integrate commitlint

### ISSUE THREAD

**Issue by snitin315** [eslint/eslint#13205] opened 2020-04-21 13:07 UTC
**The version of ESLint you are using.**

v7

**The problem you want to solve.**

Eslint has specific guidelines for commit messages,  but at the moment user is able to commit with any commit message and he may not find it wrong until he opens a Pull request.

**Your take on the correct solution to the problem.**

by integrating [commitlint](https://github.com/conventional-changelog/commitlint) the user will be able to commit only if the commit message is as required.

This will save the time of developers from amending the commit messages if accidentally typed wrong.

**Are you willing to submit a pull request to implement this change?**
Yes

**Comment by mdjermanovic** [comment] 2020-04-21 17:35
Hi @snitin315, thanks for the issue!

I think this is a duplicate of #13124

**Comment by snitin315** [comment] 2020-04-21 17:43
Yes, I didn't see that.

**Closed** 2020-04-21 18:06 UTC
Labels: core, enhancement, triage
