### ISSUE TITLE
`indent` not playing nice with comma-first style

### ISSUE THREAD

**Issue by BrandonZacharie** [eslint/eslint#9125] opened 2017-08-18 14:12 UTC
* **ESLint Version:** 4.4.1
* **Node Version:** 8.1.4
* **NPM Version:** 5.3.0

**What parser (default, Babel-ESLint, etc.) are you using?**
default

<details>
<summary>Configuration</summary>
```yml
env:
  es6: true
  node: true
extends: 'eslint:recommended'
parserOptions:
  ecmaVersion: 8
rules:
  indent:
  - error
  - 2
  - SwitchCase: 1
  linebreak-style:
  - error
  - unix
  quotes:
  - error
  - single
  semi:
  - error
  - always
  eqeqeq:
  - error
  - smart
  key-spacing:
  - error
  keyword-spacing:
  - error
  handle-callback-err:
  - error
  comma-style:
  - error
  - first
  comma-dangle:
  - error
  - never
  yoda:
  - error
  no-trailing-spaces:
  - error
  no-case-declarations:
  - error
  no-new-wrappers:
  - error
  no-new:
  - error
  no-multi-spaces:
  - error
  no-lone-blocks:
  - error
  no-multiple-empty-lines:
  - error
  - max: 1
    maxEOF: 0
  semi-spacing:
  - error
  spaced-comment:
  - error
  - always
  unicode-bom:
  - error
  - never
  one-var:
  - error
  - never
  newline-per-chained-call:
  - error
  - ignoreChainWithDepth: 3
  newline-before-return:
  - error
  require-jsdoc:
  - error
  - require:
      FunctionDeclaration: true
      MethodDefinition: true
      ClassDeclaration: true
      ArrowFunctionExpression: true
  valid-jsdoc:
  - error
  - prefer:
      arg: argument
      param: argument
      returns: return
    preferType:
      object: Object
      string: String
      boolean: Boolean
      bool: Boolean
      number: Number
    requireParamDescription: false
    requireReturnDescription: false
```

</details>

**What did you do? Please include the actual source code causing the issue.**

```js

let object = {
  a: 1
, b: 2
, c: 3
};

```

**What did you expect to happen?**

No indent errors

**What actually happened? Please include the actual, raw output from ESLint.**

```
  3:1  error  Expected indentation of 4 spaces but found 2  indent
  4:1  error  Expected indentation of 4 spaces but found 2  indent
```

**Comment by BrandonZacharie** [comment] 2017-08-18 14:20
This issue was originally reported in #3456. In this project, I'm following the comma-first styled from https://gist.github.com/isaacs/357981 sans the newline semicolon.

**Comment by not-an-aardvark** [comment] 2017-08-18 16:55
Thanks for the report. However, this is working as intended -- line 2 is indented, but lines 3 and 4 are not. To fix the issue, you should use the same indentation for all of the properties.

It's true that `a`, `b`, and `c` are aligned with each other in your code, but that is isn't just caused by indentation -- it's also caused by other stylistic choices in your code, such as the decision to put a space after `,`. So it wouldn't make sense for the `indent` rule to enforce a smaller indentation for lines 3 and 4, because it would be aligning your properties by depending on whitespace that is not actually at the start of the line.

The previous version of the `indent` rule handled this by simply ignoring lines starting with a comma. However, in ESLint 4.0.0 the `indent` rule was rewritten to be more strict, so it is catching errors like this by design. If you'd like to revert to the v3.x behavior, you can use the `indent-legacy` rule.

**Comment by not-an-aardvark** [comment] 2017-08-23 04:38
Closing because this is working as intended.

**Closed by not-an-aardvark** 2017-08-23 04:38 UTC
Labels: works as intended
