### ISSUE TITLE
ESLint: TypeError: Cannot set property 'prevName' of null

### ISSUE THREAD

**Issue by motionrus** [eslint/eslint#11812] opened 2019-06-06 15:52 UTC
**Tell us about your environment**

* **ESLint Version:**
+ eslint@5.16.0
* **Node Version:**
v8.11.3
* **npm Version:**
6.9.0

**What parser (default, Babel-ESLint, etc.) are you using?**
parser: babel-eslint
**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js

```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
class Select extends React.Component {
    constructor (props) {
        super(props);
    }

    plainChildrenTree (childrenTree) {
        return childrenTree.reduce((values, child) => {
            if (child.children.length) {
                values.push(...this.plainChildrenTree(child.children));
            } else {
                values.push({id: child.id, text: child.Title});
            }
            return values;
        }, []);
    }
}
```

```bash

```

**What did you expect to happen?**

**What actually happened? Please include the actual, raw output from ESLint.**
```TypeError: Cannot set property 'prevName' of null

TypeError: Cannot set property 'prevName' of null
    at SpreadElement (/Users/rus/.npm-packages/lib/node_modules/eslint/lib/rules/sort-keys.js:133:32)
    at listeners.(anonymous function).forEach.listener (/Users/rus/.npm-packages/lib/node_modules/eslint/lib/util/safe-emitter.js:45:58)
    at Array.forEach (<anonymous>)
    at Object.emit (/Users/rus/.npm-packages/lib/node_modules/eslint/lib/util/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/Users/rus/.npm-packages/lib/node_modules/eslint/lib/util/node-event-generator.js:251:26)
    at NodeEventGenerator.applySelectors (/Users/rus/.npm-packages/lib/node_modules/eslint/lib/util/node-event-generator.js:280:22)
    at NodeEventGenerator.enterNode (/Users/rus/.npm-packages/lib/node_modules/eslint/lib/util/node-event-generator.js:294:14)
    at CodePathAnalyzer.enterNode (/Users/rus/.npm-packages/lib/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:632:23)
    at nodeQueue.forEach.traversalInfo (/Users/rus/.npm-packages/lib/node_modules/eslint/lib/linter.js:750:28)
    at Array.forEach (<anonymous>)```

**Are you willing to submit a pull request to fix this bug?**

**Comment by platinumazure** [comment] 2019-06-06 17:15
Hi @motionrus, thanks for the issue.

Can you reproduce this with the default parser, out of curiosity? (I'm not seeing anything that espree would fail to parse.)

**Comment by motionrus** [comment] 2019-06-06 18:31
Hi @platinumazure  If you tell me, what i should do. Sorry, this error showed in PyCharm and I do not know what to do

**Comment by platinumazure** [comment] 2019-06-06 19:14
Thanks @motionrus.

You had mentioned that you were using babel-eslint parser. If you can find the configuration file where that was defined, you could temporarily remove that line from the config file and then rerun ESLint. Curious to see if you get the same answer with babel-eslint not set as the parser.

**Comment by motionrus** [comment] 2019-06-06 20:20
@platinumazure Thanks for answer. When i restart my PyCharm, error is disappear. I don't no why, so when i restarted early, error didn't go away. May be when i reinstall eslint plugin for PyCharm, something happened.

**Comment by platinumazure** [comment] 2019-06-06 20:39
Are you able to recreate the issue by running ESLint on the command line?

**Comment by motionrus** [comment] 2019-06-07 07:44
@platinumazure  no, i can't, when i run eslint in cli, it works normally. i think, this issue can be close up.

**Comment by g-plane** [comment] 2019-06-07 07:50
Closing because this question is out of scope.

**Closed by g-plane** 2019-06-07 07:50 UTC
Labels: bug, evaluating, rule
