### ISSUE TITLE
[no-duplicate-imports] Treat namespace imports as different

### ISSUE THREAD

**Issue by G-Rath** [eslint/eslint#12758] opened 2020-01-07 21:07 UTC
**What rule do you want to change?**
no-duplicate-imports

**Does this change cause the rule to produce more or fewer warnings?**
Reduces warnings.

**How will the change be implemented? (New option, new default behavior, etc.)?**
Behavioural change, which could be either option controlled or new default behaviour.
Prior art: [TSLint](https://github.com/palantir/tslint/pull/4524).

**Please provide some example code that this change will affect:**

```js
import * as parsers from '@src/parsers';
import { SpecificParser } from '@src/parsers';
```

**What does the rule currently do for this code?**
Marks the imports as duplicates

**What will the rule do after it's changed?**
Not mark the imports as duplicates

**Are you willing to submit a pull request to implement this change?**
Yes

----

The primary use I have for the above is with mocking in jest, such as [here](https://github.com/G-Rath/terraport/blob/master/test/src/parser/parseTFAttribute.spec.ts) where I want to both use the parsers & also spy on them to test that specific ones are called.

While I can use destructuring, or reference off `parsers`, the former won't be understood by auto-importers (i.e TS & IDE), and the latter would be inconsistent to how I use the functions in the rest of the codebase.

**Comment by mdjermanovic** [comment] 2020-01-08 01:39
I think this is reasonable since these two cannot be merged into one, so the rule at the moment indirectly disallows named imports if the namespace is imported. 

This could be indeed user's preference, but I'm not sure that such restriction was the intention of this particular rule. 

Maybe this can be treated as a bug and become a new default behavior instead of an option?

**Comment by G-Rath** [comment] 2020-01-08 02:27
> Maybe this can be treated as a bug and become a new default behavior instead of an option?

I've got no major preference so your call; If released as a bug fix / default behaviour change it shouldn't have any negative impact since it's fixing what is currently an error.

Worst case we'll have someone in 6 months asking if `no-duplicate-imports` can support treating namespace & named imports as the same, and it should be fairly easy to add an option for that if desired.

Either way, the actual fix implementation is mostly uneffected by if it's controlled by an option or not (it just changes the amount of code that's in the rule). If people are happy, I'll get started on a PR later this week :)

**Comment by mdjermanovic** [comment] 2020-01-08 03:15
> If people are happy, I'll get started on a PR later this week :)

Let's wait for other opinions from the team, and for [consensus](https://eslint.org/docs/maintainer-guide/issues#championing-issues) about the new option if this isn't a bug.

While at the subject, what should be the behavior in cases such as these:

```js
import * as parsers1 from 'parsers';
import * as parsers2 from 'parsers';
```

```js
// these two can be merged
import * as parsers from 'parsers';
import DefaultParser from 'parsers';
```

```js
import DefaultParser, * as parsers from 'parsers';
import { SpecificParser } from 'parsers';
```

**Comment by G-Rath** [comment] 2020-01-08 04:08
> Let's wait for other opinions from the team, and for consensus about the new option if this isn't a bug.

👍 

> While at the subject, what should be the behavior in cases such as these:

The first I class as an actual duplicate that can be fixed by replacing the second with `const parsers2 = parsers1`, since there shouldn't be any difference in what's imported. (similar to no-useless-rename`)
The second is mergeable, and so a duplicate.
The third not mergeable, and so not a duplicate.

**Comment by kaicataldo** [comment] 2020-01-09 23:00
> I think in general the behaviour of no-duplicate-imports should be "an import that can be merged with another is a duplicate of that other".

This makes sense as a heuristic to me. :+1:

**Comment by mdjermanovic** [comment] 2020-01-10 00:15
> The first I class as an actual duplicate that can be fixed by replacing the second with `const parsers2 = parsers1`, since there shouldn't be any difference in what's imported. (similar to no-useless-rename`)

That's reasonable, but following the same logic the original example can be replaced with `const { SpecificParser } = parsers `? Also, this behavior wouldn't match "an import that can be merged with another is a duplicate of that other".

Not saying that it shouldn't be reported as a duplicate, just trying to find out what makes the most sense as the responsibility of this rule.

**Comment by G-Rath** [comment] 2020-01-10 02:40
> That's reasonable, but following the same logic the original example can be replaced with const { SpecificParser } = parsers ? 

Probably (I've not tried, but I don't think the transpiling would change it enough to cause that not to work), but it would mean I'd have to rename if I was already importing that specific parser.

> Also, this behavior wouldn't match "an import that can be merged with another is a duplicate of that other".

Actually I think you could argue it does, because those imports can be merged by renaming them to share the same name.

I think what you're after here is a heuristic for what "can be merged" means, which I'd say is:

> An import is considered mergable with another if the act of merging does not require the creation of extra nodes.

Then, with that defined, this rule takes on the heuristic for its responsibility to be:

> An import that can be merged with another import is a duplicate of that other.

So, in applying this we get:
```
// mergable, as parsers1 & parsers2 hold the same reference, and so their identifiers can be replaced.
import * as parsers1 from 'parsers';
import * as parsers2 from 'parsers';

// mergable, as they can be combined without changing behaviour & remaining syntactically valid.
import defaultValue from 'parsers';
import { anotherValue } from 'parsers';

// mergable as they will both trigger any side effects the module has.
import * as parsers2 from 'parsers';
import from 'parsers';

// not mergable, as they would require new nodes to be created.
import defaultValue from 'parsers';
import * as parsers1 from 'parsers';
```

------

*Personally*, I also think that it's a good thing to encourage not duplicating such imports, as (based on my understanding on the specification for modules) there is completely no reason to do so - it's effectively the namespace form of `no-useless-rename`.

Overall, I totally agree that this is an interesting question, but I don't think it's big enough to be worth the bikeshed given it's very easy to implement an option for later 🙂

I do think that the fixer for merging the last case should be a suggestion, since it will cause other to be invalid.

**Comment by ljharb** [comment] 2020-01-25 18:24
imo this isn't an enhancement, it's a bug, and should be marked as such.

**Comment by nzakas** [comment] 2020-02-13 22:25
I agree, this seems like a bug.

**Comment by kaicataldo** [comment] 2020-02-16 04:51
Marking as accepted since three team members agree that this is a bug.

**Comment by JoaoDsv** [comment] 2020-02-18 11:06
Working on this issue.

**Comment by JoaoDsv** [comment] 2020-02-18 16:36
Solved in [this](https://github.com/eslint/eslint/pull/12935) PR. If someone can have a look 🙏

**Comment by ljharb** [comment] 2020-04-08 03:40
This is a bug with an open PR; it should be reopened.

**Comment by cmal** [comment] 2020-04-14 14:20
I think I've fixed this bug in https://github.com/eslint/eslint/pull/13180
Can anyone help review my code?

**Comment by ljharb** [comment] 2020-04-14 14:24
@cmal #12935 already exists

**Comment by cmal** [comment] 2020-04-14 15:15
@ljharb Hi, how can I reuse issue #12935?

**Comment by ljharb** [comment] 2020-05-16 04:05
This remains a bug with an open PR; please reopen. cc @mdjermanovic

**Comment by nzakas** [comment] 2020-06-19 16:35
Per https://github.com/eslint/eslint/pull/12767#issuecomment-643496156, we should also address  #12760 in this issue.

**Comment by boutahlilsoufiane** [comment] 2021-01-17 12:15
I'm going to do this, give me two weeks.

**Comment by nzakas** [comment] 2021-01-19 01:14
@boutahlilsoufiane great, thanks!

**Comment by misfitonie** [comment] 2021-01-19 11:15
Hi, if this ticket is still open, i'll be happy to work on it :)

**Comment by nzakas** [comment] 2021-01-20 01:41
@misfitonie we do have a volunteer (@boutahlilsoufiane) so let’s wait for now unless you two want to decide between yourselves who wants to work on this.

**Comment by misfitonie** [comment] 2021-01-25 00:06
@boutahlilsoufiane do you need some help ? Or you just need time ?

**Comment by boutahlilsoufiane** [comment] 2021-01-25 09:33
@misfitonie thank you for proposing your help, I need just time.

**Comment by boutahlilsoufiane** [comment] 2021-02-20 13:37
After spending too many hours trying to figure out how to run eslint project to test my changes in lib\rules\no-duplicate-imports.js, I didn't find anything. I tried this command node ./bin/eslint.js test.js.

The content of test.js:
import * as parsers1 from 'parsers';
import * as parsers2 from 'parsers';

The eslint report these errors:

  1:1   error  Import and export declarations are not supported yet      node/no-unsupported-features/es-syntax
  1:10  error  'StringCursor' is defined but never used              no-unused-vars
  1:24  error  'parseTFAttribute' is defined but never used          no-unused-vars
  1:48  error  Strings must use doublequote                          quotes
  1:48  error  "@src/parser" is not found                            node/no-missing-import
  2:1   error  Import and export declarations are not supported yet  node/no-unsupported-features/es-syntax
  2:10  error  'TFNodeType' is defined but never used                no-unused-vars
  2:28  error  Strings must use doublequote                          quotes
  2:28  error  "@src/types" is not found                             node/no-missing-import
  2:41  error  Newline required at end of file but not found         eol-last

I need a way to test my code, I'm stuck!!, I will appreciate any help

**Comment by mdjermanovic** [comment] 2021-02-23 16:47
Hi @boutahlilsoufiane!

The tests for this change should be added to [tests/lib/rules/no-duplicate-imports.js](https://github.com/eslint/eslint/blob/master/tests/lib/rules/no-duplicate-imports.js) 

Command to run the tests: `npm run test:cli tests/lib/rules/no-duplicate-imports.js` 

You can find more details about the tests here:

* https://eslint.org/docs/developer-guide/working-with-rules#rule-unit-tests
* https://eslint.org/docs/developer-guide/nodejs-api#ruletester
* https://eslint.org/docs/developer-guide/unit-tests

**Comment by boutahlilsoufiane** [comment] 2021-03-07 22:51
Hi **mdjermanovic!**
Thank you, I can now test my code.

**Comment by SimonAlling** [comment] 2021-03-18 14:12
Could be worth mentioning that [TSLint has/had an option for this](https://palantir.github.io/tslint/rules/no-duplicate-imports/); maybe we can reuse [their implementation](https://github.com/palantir/tslint/blob/master/src/rules/noDuplicateImportsRule.ts) or at least use it as inspiration?

> ## Config
> 
> “allow-namespace-imports” allows you to import namespaces on separate lines.
> ### Config examples
> 
> ```
> "no-duplicate-imports": [true, {"allow-namespace-imports": true}]
> ```
> 
> ### Schema
> 
> ```
> {
>   "type": "object",
>   "properties": {
>     "allow-namespace-imports": {
>       "type": "boolean"
>     }
>   }
> }
> ```

**Comment by boutahlilsoufiane** [comment] 2021-05-19 03:24
Hi @mdjermanovic, I worked on your notes, could you review the PR, please?

**Comment by boutahlilsoufiane** [comment] 2021-05-26 09:24
Hi @mdjermanovic, could you review the PR, please?

**Closed** 2021-06-04 15:58 UTC
Labels: accepted, bug, good first issue, help wanted, rule
