### ISSUE TITLE
yarn eslint --init problem

### ISSUE THREAD

**Issue by Leonardo-Henrique** [eslint/eslint#14297] opened 2021-04-06 11:10 UTC
**Tell us about your environment**

* **ESLint Version:**
 7.23.0

* **Node Version:**
v14.15.4

* **yarn Version:**
1.22.10

* **SO:**
Windows 10

**What parser (default, `@babel/eslint-parser`, `@typescript-eslint/parser`, etc.) are you using?**

<details>
<summary>Configuration</summary>

```js

```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

``

```
```yarn eslint --init

```

**What did you expect to happen?**
The dependencies are installed.

**What actually happened? Please copy-paste the actual, raw output from ESLint.**

yarn run v1.22.10 Henrique\Documents\Estudos\aplicacao-web>yarn eslint --init
$ "C:\Users\Leonardo Henrique\Documents\Estudos\aplicacao-web\node_modules\.bin\eslint" --init
√ How would you like to use ESLint? · style
√ What type of modules does your project use? · esm
√ Which framework does your project use? · react
√ Does your project use TypeScript? · No / Yes
√ Where does your code run? · browser
√ How would you like to define a style for your project? · guide
√ Which style guide do you want to follow? · airbnb
√ What format do you want your config file to be in? · JSON
Checking peerDependencies of eslint-config-airbnb@latest

Oops! Something went wrong! :(

ESLint: 7.23.0

SyntaxError: Unexpected token { in JSON at position 580
    at JSON.parse (<anonymous>)
    at Object.fetchPeerDependencies (C:\Users\Leonardo Henrique\Documents\Estudos\aplicacao-web\node_modules\eslint\lib\init\npm-utils.js:83:17)
    at getPeerDependencies (C:\Users\Leonardo Henrique\Documents\Estudos\aplicacao-web\node_modules\eslint\lib\init\config-initializer.js:80:27)
    at hasESLintVersionConflict (C:\Users\Leonardo Henrique\Documents\Estudos\aplicacao-web\node_modules\eslint\lib\init\config-initializer.js:382:30)
    at TogglePrompt.skip (C:\Users\Leonardo Henrique\Documents\Estudos\aplicacao-web\node_modules\eslint\lib\init\config-initializer.js:580:107)
    at TogglePrompt.skip (C:\Users\Leonardo Henrique\Documents\Estudos\aplicacao-web\node_modules\enquirer\lib\prompt.js:188:46)
    at C:\Users\Leonardo Henrique\Documents\Estudos\aplicacao-web\node_modules\enquirer\lib\prompt.js:232:22
    at new Promise (<anonymous>)
    at TogglePrompt.run (C:\Users\Leonardo Henrique\Documents\Estudos\aplicacao-web\node_modules\enquirer\lib\prompt.js:229:12)
    at Enquirer.ask (C:\Users\Leonardo Henrique\Documents\Estudos\aplicacao-web\node_modules\enquirer\index.js:137:43)
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Steps to reproduce this issue:**

I'm just running yarn eslint --init

**Are you willing to submit a pull request to fix this bug?**

**Comment by mdjermanovic** [comment] 2021-04-06 13:32
Hi @Leonardo-Henrique, thanks for the issue!

Can you please run this command and copy & paste the output here:

```
npm show --json eslint-config-airbnb@latest peerDependencies
```

**Comment by Leonardo-Henrique** [comment] 2021-04-06 19:48
For sure!

This is the complete output:

```
{
  "eslint": "^5.16.0 || ^6.8.0 || ^7.2.0",
  "eslint-plugin-import": "^2.22.1",
  "eslint-plugin-jsx-a11y": "^6.4.1",
  "eslint-plugin-react": "^7.21.5",
  "eslint-plugin-react-hooks": "^4 || ^3 || ^2.3.0 || ^1.7.0"
}

```

**Comment by mdjermanovic** [comment] 2021-04-07 21:45
> Just to notice, I'm trying to init ESlint with yarn

Yes, but ESLint is still internally using `npm` to get the list of peer dependencies.

Here's the function that fails on the `JSON.parse` line 83:

https://github.com/eslint/eslint/blob/bd46dc4647faa4c3bbb5f60d4c00616a64081398/lib/init/npm-utils.js#L69-L86

`fetchedText` should be [this output](https://github.com/eslint/eslint/issues/14297#issuecomment-814394880), and it looks like a valid JSON.

Unfortunately, I can't reproduce this locally to debug. Can you add `console.log(fetchedText);` before the `JSON.parse()` line?

**Comment by nzakas** [comment] 2021-04-28 00:38
No repro case, so closing.

**Closed by nzakas** 2021-04-28 00:38 UTC
Labels: bug, repro:needed
