### ISSUE TITLE
Uncaught TypeError

### ISSUE THREAD

**Issue by da0ka** [eslint/eslint#9901] opened 2018-01-27 23:14 UTC
https://eslint.org/demo
console reports error when touch Rules of Rules configuration.
react.min.js:14 Uncaught TypeError: $(...).popover is not a function

**Comment by not-an-aardvark** [comment] 2018-01-27 23:21
Closing as a duplicate of https://github.com/eslint/eslint.github.io/issues/437

**Closed by not-an-aardvark** 2018-01-27 23:21 UTC
Labels: triage
