### ISSUE TITLE
Fix option not recognized

### ISSUE THREAD

**Issue by SimonChaumet** [eslint/eslint#13780] opened 2020-10-21 16:14 UTC
**Tell us about your environment**

Environment Info:

Node version: v12.19.0
npm version: v6.14.8
Local ESLint version: v7.11.0 (Currently used)
Global ESLint version: Not found

parser: @typescript-eslint/parser

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
module.exports = {
    root: true,
    extends: [
        'plugin:@typescript-eslint/recommended',
        '@react-native-community',
    ],
    parser: '@typescript-eslint/parser',
    parserOptions: {
        ecmaFeatures: {
            "jsx": true
        },
        project: "./tsconfig.json",
        tsconfigRootDir: __dirname,
    },
    plugins: [
        "@typescript-eslint",
    ],
    settings: {
        react: {
            "pragma": "React",
            "version": "detect"
        }
    },
    rules: {
        'no-console': process.env.NODE_ENV === 'production' ? 'warn' : 'off',
        'no-debugger': process.env.NODE_ENV === 'production' ? 'warn' : 'off',
        'block-scoped-var': 'warn',
        'no-multi-spaces': 'warn',
        'array-bracket-newline': ['warn', 'consistent'],
        'block-spacing': 'warn',
        'brace-style': ['warn', '1tbs'],
        'comma-dangle': ['warn', 'only-multiline'],
        'comma-spacing': ['warn', {before: false, after: true}],
        'comma-style': ['warn', 'last'],
        'eol-last': ['warn', 'always'],
        'func-call-spacing': ['warn', 'never'],
        'indent': ['error', 4],
        'key-spacing': ['warn', {mode: 'minimum', afterColon: true}],
        'keyword-spacing': ['warn', {before: true, after: true}],
        'linebreak-style': ['warn', 'unix'],
        'new-parens': ['warn', 'always'],
        'newline-per-chained-call': ['warn', {ignoreChainWithDepth: 3}],
        'no-lonely-if': 'warn',
        'no-trailing-spaces': 'warn',
        'no-unneeded-ternary': 'warn',
        'no-whitespace-before-property': 'warn',
        'semi-spacing': ['warn', {before: false, after: true}],
        'space-before-blocks': 'warn',
        'space-before-function-paren': ['warn', {anonymous: 'never', named: 'never', asyncArrow: 'always'}],
        'space-infix-ops': ['warn', {'int32Hint': true}],
        'space-unary-ops': ['warn', {words: true, nonwords: false}],
        'spaced-comment': ['warn', 'always'],
        'no-unused-vars': process.env.NODE_ENV === 'production' ? 'error' : 'warn',
    },
};

// package.json
{
  "name": "XXX",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "NODE_ENV=production && eslint index.js src --ext .tsx,.js,.ts --fix",
    "check-lint": "cross-env NODE_ENV=production eslint index.js src --max-warnings 0 --ext .tsx,.js,.ts"
  },
  "dependencies": {
    "@react-native-community/masked-view": "^0.1.10",
    "@react-navigation/drawer": "^5.9.3",
    "@react-navigation/native": "^5.7.6",
    "@react-navigation/stack": "^5.9.3",
    "axios": "^0.20.0",
    "cross-env": "^7.0.2",
    "react": "16.13.1",
    "react-native": "0.63.3",
    "react-native-gesture-handler": "^1.8.0",
    "react-native-reanimated": "^1.13.1",
    "react-native-safe-area-context": "^3.1.8",
    "react-native-screens": "^2.11.0"
  },
  "devDependencies": {
    "@babel/core": "^7.8.4",
    "@babel/runtime": "^7.8.4",
    "@react-native-community/eslint-config": "^1.1.0",
    "@types/react": "^16.9.53",
    "@types/react-native": "^0.63.26",
    "@typescript-eslint/eslint-plugin": "^4.5.0",
    "@typescript-eslint/parser": "^4.5.0",
    "babel-jest": "^25.1.0",
    "eslint": "^7.11.0",
    "jest": "^25.1.0",
    "metro-react-native-babel-preset": "^0.59.0",
    "react-test-renderer": "16.13.1",
    "typescript": "^4.0.3"
  },
  "jest": {
    "preset": "react-native"
  }
}
```

</details>

```bash
NODE_ENV=production && eslint index.js src --ext .tsx,.js,.ts --fix
cross-env NODE_ENV=production eslint index.js src --ext .tsx,.js,.ts --fix
```

**What did you expect to happen?**
My code is fixed

**What actually happened? Please include the actual, raw output from ESLint.**

✖ 87 problems (59 errors, 28 warnings)
  56 errors and 18 warnings potentially fixable with the `--fix` option.

**Are you willing to submit a pull request to fix this bug?**
No

**Comment by mdjermanovic** [comment] 2020-10-21 17:44
Hi @SimonChaumet, thanks for the issue!

Can you also set `DEBUG=eslint:cli`, run again, and then copy & paste the output here?

**Comment by SimonChaumet** [comment] 2020-10-22 07:55
@mdjermanovic here it is

```html
<pre><b>yarn run v1.22.4</b>
<font color="#8A9093">$ NODE_ENV=production &amp;&amp; eslint index.js src --ext .tsx,.js,.ts --fix</font>
  <font color="#D75F5F"><b>eslint:cli </b></font>CLI args: [ <font color="#4E9A06">&apos;index.js&apos;</font>, <font color="#4E9A06">&apos;src&apos;</font>, <font color="#4E9A06">&apos;--ext&apos;</font>, <font color="#4E9A06">&apos;.tsx,.js,.ts&apos;</font>, <font color="#4E9A06">&apos;--fix&apos;</font> ] <font color="#D75F5F">+0ms</font>
  <font color="#D75F5F"><b>eslint:cli </b></font>Running on files <font color="#D75F5F">+3ms</font>
  <font color="#D75F5F"><b>eslint:cli </b></font>Fix mode enabled - applying fixes <font color="#D75F5F">+4s</font>

<u style="text-decoration-style:single">/projects/TwoUApp/index.js</u>
  4:8   <font color="#CC0000">error</font>  Replace `&apos;react-native-gesture-handler&apos;` with `&quot;react-native-gesture-handler&quot;`  prettier/prettier
  5:29  <font color="#CC0000">error</font>  Replace `&apos;react-native&apos;` with `&quot;react-native&quot;`                                  prettier/prettier
  6:17  <font color="#CC0000">error</font>  Replace `&apos;./src/App&apos;` with `&quot;./src/App&quot;`                                        prettier/prettier
  7:33  <font color="#CC0000">error</font>  Replace `&apos;./app.json&apos;` with `&quot;./app.json&quot;`                                      prettier/prettier

<u style="text-decoration-style:single">/projects/TwoUApp/src/App.tsx</u>
   1:19  <font color="#CC0000">error</font>    Replace `&apos;react&apos;` with `&quot;react&quot;`      prettier/prettier
   2:24  <font color="#C4A000">warning</font>  Strings must use singlequote          quotes
   3:34  <font color="#C4A000">warning</font>  Strings must use singlequote          quotes
   5:16  <font color="#C4A000">warning</font>  Missing return type on function       @typescript-eslint/explicit-module-boundary-types
   6:3   <font color="#CC0000">error</font>    Delete `··`                           prettier/prettier
   7:1   <font color="#CC0000">error</font>    Delete `····`                         prettier/prettier
   8:1   <font color="#CC0000">error</font>    Replace `············` with `······`  prettier/prettier
   9:1   <font color="#CC0000">error</font>    Delete `····`                         prettier/prettier
  10:1   <font color="#CC0000">error</font>    Delete `··`                           prettier/prettier

<u style="text-decoration-style:single">/projects/TwoUApp/src/router/ScenarioNavigation.tsx</u>
   1:38  <font color="#CC0000">error</font>    Replace `&apos;@react-navigation/stack&apos;` with `&quot;@react-navigation/stack&quot;`                                                      prettier/prettier
   2:24  <font color="#CC0000">error</font>    Replace `&apos;react&apos;` with `&quot;react&quot;`                                                                                          prettier/prettier
   3:22  <font color="#CC0000">error</font>    Replace `&apos;../views/Emotions&apos;` with `&quot;../views/Emotions&quot;`                                                                  prettier/prettier
   4:21  <font color="#CC0000">error</font>    Replace `&apos;../views/Context&apos;` with `&quot;../views/Context&quot;`                                                                    prettier/prettier
   8:1   <font color="#C4A000">warning</font>  Missing return type on function                                                                                           @typescript-eslint/explicit-module-boundary-types
   9:3   <font color="#CC0000">error</font>    Delete `··`                                                                                                               prettier/prettier
  10:1   <font color="#CC0000">error</font>    Replace `········&lt;Stack.Navigator·initialRouteName={&apos;Emotions&apos;` with `····&lt;Stack.Navigator·initialRouteName={&quot;Emotions&quot;`  prettier/prettier
  11:7   <font color="#CC0000">error</font>    Replace `······&lt;Stack.Screen·name={&apos;Emotions&apos;` with `&lt;Stack.Screen·name={&quot;Emotions&quot;`                                      prettier/prettier
  12:1   <font color="#CC0000">error</font>    Replace `············&lt;Stack.Screen·name={&apos;Context&apos;` with `······&lt;Stack.Screen·name={&quot;Context&quot;`                            prettier/prettier
  13:5   <font color="#CC0000">error</font>    Delete `····`                                                                                                             prettier/prettier
  14:1   <font color="#CC0000">error</font>    Delete `··`                                                                                                               prettier/prettier

<u style="text-decoration-style:single">/projects/TwoUApp/src/router/index.tsx</u>
   1:24  <font color="#C4A000">warning</font><font color="#8A9093">  Strings must use singlequote                                                                                    quotes</font>
   2:52  <font color="#C4A000">warning</font><font color="#8A9093">  Strings must use singlequote                                                                                    quotes</font>
   3:39  <font color="#C4A000">warning</font><font color="#8A9093">  Strings must use singlequote                                                                                    quotes</font>
   4:22  <font color="#C4A000">warning</font><font color="#8A9093">  Strings must use singlequote                                                                                    quotes</font>
   5:30  <font color="#C4A000">warning</font><font color="#8A9093">  Strings must use singlequote                                                                                    quotes</font>
   6:32  <font color="#C4A000">warning</font><font color="#8A9093">  Strings must use singlequote                                                                                    quotes</font>
  10:1   <font color="#C4A000">warning</font><font color="#8A9093">  Missing return type on function                                                                                 @typescript-eslint/explicit-module-boundary-types</font>
  11:3   <font color="#CC0000">error</font><font color="#8A9093">    Delete `··`                                                                                                     prettier/prettier</font>
  13:3   <font color="#CC0000">error</font><font color="#8A9093">    Delete `··`                                                                                                     prettier/prettier</font>
  14:5   <font color="#CC0000">error</font><font color="#8A9093">    Delete `····`                                                                                                   prettier/prettier</font>
  15:1   <font color="#CC0000">error</font><font color="#8A9093">    Replace `············&lt;View·style={{·alignItems:·&apos;flex-end&apos;` with `······&lt;View·style={{·alignItems:·&quot;flex-end&quot;`  prettier/prettier</font>
  15:26  <font color="#C4A000">warning</font><font color="#8A9093">  Inline style: { alignItems: &apos;flex-end&apos; }                                                                        react-native/no-inline-styles</font>
  16:1   <font color="#CC0000">error</font><font color="#8A9093">    Replace `················` with `········`                                                                      prettier/prettier</font>
  17:1   <font color="#CC0000">error</font><font color="#8A9093">    Replace `····················title={&apos;Menu&apos;` with `··········title={&quot;Menu&quot;`                                      prettier/prettier</font>
  18:1   <font color="#CC0000">error</font><font color="#8A9093">    Delete `··········`                                                                                             prettier/prettier</font>
  19:1   <font color="#CC0000">error</font><font color="#8A9093">    Delete `············`                                                                                           prettier/prettier</font>
  20:11  <font color="#CC0000">error</font><font color="#8A9093">    Delete `··········`                                                                                             prettier/prettier</font>
  21:1   <font color="#CC0000">error</font><font color="#8A9093">    Replace `················` with `········`                                                                      prettier/prettier</font>
  23:1   <font color="#CC0000">error</font><font color="#8A9093">    Replace `················` with `········`                                                                      prettier/prettier</font>
  24:1   <font color="#CC0000">error</font><font color="#8A9093">    Replace `············` with `······`                                                                            prettier/prettier</font>
  25:1   <font color="#CC0000">error</font><font color="#8A9093">    Delete `······`                                                                                                 prettier/prettier</font>
  26:1   <font color="#CC0000">error</font><font color="#8A9093">    Replace `················` with `········`                                                                      prettier/prettier</font>
  26:53  <font color="#C4A000">warning</font><font color="#8A9093">  Strings must use singlequote                                                                                    quotes</font>
  27:1   <font color="#CC0000">error</font><font color="#8A9093">    Replace `····················` with `··········`                                                                prettier/prettier</font>
  27:42  <font color="#C4A000">warning</font><font color="#8A9093">  Strings must use singlequote                                                                                    quotes</font>
  28:1   <font color="#CC0000">error</font><font color="#8A9093">    Delete `··········`                                                                                             prettier/prettier</font>
  28:42  <font color="#C4A000">warning</font><font color="#8A9093">  Strings must use singlequote                                                                                    quotes</font>
  29:1   <font color="#CC0000">error</font><font color="#8A9093">    Replace `················` with `········`                                                                      prettier/prettier</font>
  30:1   <font color="#CC0000">error</font><font color="#8A9093">    Replace `············` with `······`                                                                            prettier/prettier</font>
  31:5   <font color="#CC0000">error</font><font color="#8A9093">    Delete `····`                                                                                                   prettier/prettier</font>
  32:1   <font color="#CC0000">error</font><font color="#8A9093">    Delete `··`                                                                                                     prettier/prettier</font>

<u style="text-decoration-style:single">/projects/TwoUApp/src/services/API.ts</u>
  0:0  <font color="#CC0000">error</font>  Parsing error: &quot;parserOptions.project&quot; has been set for @typescript-eslint/parser.
The file does not match your project config: src/services/API.ts.
The file must be included in at least one of the projects provided

<u style="text-decoration-style:single">/projects/TwoUApp/src/views/Context.tsx</u>
   1:28  <font color="#C4A000">warning</font>  Strings must use singlequote                                                  quotes
   2:24  <font color="#C4A000">warning</font>  Strings must use singlequote                                                  quotes
   4:16  <font color="#C4A000">warning</font>  Missing return type on function                                               @typescript-eslint/explicit-module-boundary-types
   4:33  <font color="#C4A000">warning</font>  Object pattern argument should be typed                                       @typescript-eslint/explicit-module-boundary-types
   4:42  <font color="#CC0000">error</font>    &apos;navigation&apos; is defined but never used. Allowed unused args must match /^_/u  @typescript-eslint/no-unused-vars
   5:3   <font color="#CC0000">error</font>    Delete `··`                                                                   prettier/prettier
   5:13  <font color="#C4A000">warning</font>  &apos;emotionId&apos; is assigned a value but never used                                no-unused-vars
   5:13  <font color="#CC0000">error</font>    &apos;emotionId&apos; is assigned a value but never used                                @typescript-eslint/no-unused-vars
   7:3   <font color="#CC0000">error</font>    Delete `··`                                                                   prettier/prettier
   8:1   <font color="#CC0000">error</font>    Replace `········` with `····`                                                prettier/prettier
   9:1   <font color="#CC0000">error</font>    Replace `············` with `······`                                          prettier/prettier
  10:5   <font color="#CC0000">error</font>    Delete `····`                                                                 prettier/prettier
  11:1   <font color="#CC0000">error</font>    Delete `··`                                                                   prettier/prettier

<u style="text-decoration-style:single">/projects/TwoUApp/src/views/Emotions.tsx</u>
  1:24  <font color="#C4A000">warning</font>  Strings must use singlequote          quotes
  2:28  <font color="#C4A000">warning</font>  Strings must use singlequote          quotes
  4:1   <font color="#C4A000">warning</font>  Missing return type on function       @typescript-eslint/explicit-module-boundary-types
  5:3   <font color="#CC0000">error</font>    Delete `··`                           prettier/prettier
  6:1   <font color="#CC0000">error</font>    Replace `········` with `····`        prettier/prettier
  7:1   <font color="#CC0000">error</font>    Replace `············` with `······`  prettier/prettier
  8:5   <font color="#CC0000">error</font>    Delete `····`                         prettier/prettier
  9:1   <font color="#CC0000">error</font>    Delete `··`                           prettier/prettier

<u style="text-decoration-style:single">/projects/TwoUApp/src/views/Home.tsx</u>
   1:22  <font color="#C4A000">warning</font>  Strings must use singlequote                                                                    quotes
   2:24  <font color="#C4A000">warning</font>  Strings must use singlequote                                                                    quotes
   3:30  <font color="#C4A000">warning</font>  Strings must use singlequote                                                                    quotes
   5:8   <font color="#C4A000">warning</font>  Missing return type on function                                                                 @typescript-eslint/explicit-module-boundary-types
   6:3   <font color="#CC0000">error</font>    Delete `··`                                                                                     prettier/prettier
   7:1   <font color="#CC0000">error</font>    Delete `····`                                                                                   prettier/prettier
   8:1   <font color="#CC0000">error</font>    Replace `············&lt;Text·style={{·color:·&apos;black&apos;` with `······&lt;Text·style={{·color:·&quot;black&quot;`  prettier/prettier
   8:26  <font color="#C4A000">warning</font>  Inline style: { color: &apos;black&apos; }                                                                react-native/no-inline-styles
   9:1   <font color="#CC0000">error</font>    Replace `········` with `····`                                                                  prettier/prettier
  10:1   <font color="#CC0000">error</font>    Delete `··`                                                                                     prettier/prettier

<font color="#EF2929"><b>✖ 87 problems (59 errors, 28 warnings)</b></font>
<font color="#EF2929"><b>  56 errors and 18 warnings potentially fixable with the `--fix` option.</b></font>

<font color="#CC0000">error</font> Command failed with exit code 1.
<font color="#3465A4">info</font> Visit <b>https://yarnpkg.com/en/docs/cli/run</b> for documentation about this command.
</pre>
```

**Comment by mdjermanovic** [comment] 2020-10-22 11:13
It looks like this is caused by conflicts between prettier and eslint's layout rules.

Fix makes a change in one pass, e.g., to fix a layout error reported by an eslint core rule, but the fixed code triggers a prettier error which then fixes the code back to the original version. That again triggers the original error and so on (`--fix` runs up to 10 passes, or until no more fixable problems are found).

If you're using prettier (via `@react-native-community` config), then you shouldn't use layout rules like `indent`, `array-bracket-newline`, `block-spacing` etc.

There is a list of rules that shouldn't be enabled when prettier is used here:

https://github.com/prettier/eslint-config-prettier/blob/master/index.js

**Comment by SimonChaumet** [comment] 2020-10-22 14:10
Thanks ! I didn't knew

**Comment by nzakas** [comment] 2020-11-17 18:29
Resolved, so closing.

**Closed by nzakas** 2020-11-17 18:29 UTC
Labels: bug, cli, evaluating
