### ISSUE TITLE
rule suggestion: newline before comment

### ISSUE THREAD

**Issue by xjamundx** [eslint/eslint#2534] opened 2015-05-14 16:00 UTC
We have this rule in the PayPal UIE style guide and I couldn't find a way to enable it with ESLint.

I think JSCS has something similar:
http://jscs.info/rule/requirePaddingNewLinesBeforeLineComments.html

I'd be happy implementing it.

**Comment by gyandeeps** [comment] 2015-05-14 16:01
I like the idea. :+1:

**Comment by lo1tuma** [comment] 2015-05-14 16:02
Looks like a duplicate of #1344.

**Comment by gyandeeps** [comment] 2015-05-14 16:02
yup.

**Closed** 2015-05-14 16:02 UTC
Labels: question
