### ISSUE TITLE
Invoking ESLint via Node API Uses Seemingly Incorrect Path for Configs and Plugins

### ISSUE THREAD

**Issue by epmatsw** [eslint/eslint#7723] opened 2016-12-08 18:34 UTC
**Tell us about your environment**

* **ESLint Version:** 3.11.1
* **Node Version:** 7.2
* **npm Version:** 3.10.9

**What parser (default, Babel-ESLint, etc.) are you using?** default

**Please show your full configuration:**

```
{
  "extends": "@example/eslint-config-example
}
```

**What did you do? Please include the actual source code causing the issue.**

```js
const cliEngine = new CLIEngine({
    useEslintrc: true,
    cwd: process.cwd()
});
const report = cliEngine.executeOnFiles(files);
```

**What did you expect to happen?**
I have a utility that is globally installed and invoked via the command line. It has a dependency on `eslint`, but should execute the rules and plugins specified in the `cwd`'s `.eslintrc`. That mostly seems to work, but when it attempts to process the extends, the path received from `getBaseDir` seems incorrect. In particular, it tries to search relative to the `eslint` in the globally installed tool rather than relative to the `.eslintrc`, which means that it misses the dependencies installed by the project.

Basically, the dependencies I've got are:

```
SomeProject:
    devDependencies:
        eslint-config-mine:
            dependencies:
                eslint-config-otherTeam,
                eslint-plugin-mine,
MyTool:
    dependencies:
        eslint
```

**What actually happened? Please include the actual, raw output from ESLint.**

```
/Users/wstamper/mytool/node_modules/eslint/lib/config/config-file.js:402
            throw e;
            ^

Error: Cannot find module 'eslint-config-mine'
Referenced from: /Users/wstamper/github/someproject/.eslintrc.json
    at ModuleResolver.resolve (/Users/wstamper/mytool/node_modules/eslint/lib/util/module-resolver.js:74:19)
    at resolve (/Users/wstamper/mytool/node_modules/eslint/lib/config/config-file.js:479:33)
    at load (/Users/wstamper/mytool/node_modules/eslint/lib/config/config-file.js:496:26)
    at configExtends.reduceRight (/Users/wstamper/mytool/node_modules/eslint/lib/config/config-file.js:392:36)
    at Array.reduceRight (native)
    at applyExtends (/Users/wstamper/mytool/node_modules/eslint/lib/config/config-file.js:363:28)
    at Object.load (/Users/wstamper/mytool/node_modules/eslint/lib/config/config-file.js:530:22)
    at loadConfig (/Users/wstamper/mytool/node_modules/eslint/lib/config.js:63:33)
    at getLocalConfig (/Users/wstamper/mytool/node_modules/eslint/lib/config.js:130:29)
    at Config.getConfig (/Users/wstamper/mytool/node_modules/eslint/lib/config.js:256:22)
    at processText (/Users/wstamper/mytool/node_modules/eslint/lib/cli-engine.js:224:33)
    at processFile (/Users/wstamper/mytool/node_modules/eslint/lib/cli-engine.js:303:18)
    at executeOnFile (/Users/wstamper/mytool/node_modules/eslint/lib/cli-engine.js:672:25)
    at fileList.forEach.fileInfo (/Users/wstamper/mytool/node_modules/eslint/lib/cli-engine.js:710:13)
    at Array.forEach (native)
    at CLIEngine.executeOnFiles (/Users/wstamper/mytool/node_modules/eslint/lib/cli-engine.js:709:18)
```

**Comment by gyandeeps** [comment] 2016-12-08 18:37
Linter api doesn't do any kind of config resolution. If you want to do that then use CLIEngine interface.
Docs: http://eslint.org/docs/developer-guide/nodejs-api#cliengine

**Comment by epmatsw** [comment] 2016-12-08 18:44
@gyandeeps whoops, turns out that was an extremely misleadingly named variable. Updated the code.

**Comment by jonathantneal** [comment] 2016-12-10 03:28
I’ve been running into this issue as well.

```js
const cli = new CLIEngine({
	cwd: path.resolve(dir),
	envs: ['browser']
});
```

Within the `dir` directory, a `package.json` file with `eslintConfig.extends` is successfully read.  However, eslint does **not** resolve `extends` from the `cwd`, despite that being where it identified the `package.json`. Rather, it resolves `extends` from the actual current working directory.

**Comment by jonathantneal** [comment] 2016-12-12 14:38
I’m trying to track down this bug. Perhaps, `cwd` or something related to it needs to get passed as an `extraLookupPath` to `ModuleResolver#resolve` in [lib/util/module-resolver.js](https://github.com/eslint/eslint/blob/master/lib/util/module-resolver.js#L55).

**Comment by jonathantneal** [comment] 2016-12-12 14:56
The issue may be here:

```js
function getBaseDir(configFilePath) {

    // calculates the path of the project including ESLint as dependency
    const projectPath = path.resolve(__dirname, "../../../");
```

The `projectPath` that gets calculated here is not *the path of the project including eslint as a dependency*, but in fact the project’s `node_modules` directory.

The `__dirname` will be:

```
PROJECT/node_modules/eslint/lib/config
```

Which means `'../../../'` will take us...

```
PROJECT/node_modules/eslint/lib
PROJECT/node_modules/eslint
PROJECT/node_modules
```

Perhaps this file moved? I will make a PR to add the additional `../`. This resolves the issue for me.

**Comment by epmatsw** [comment] 2016-12-12 15:28
@jonathantneal I think your bug is a little different than mine. In my case, `projectPath` is something like `/Users/wstamper/mytool/node_modules`, while the config and plugins are in `/Users/wstamper/github/someproject`. I think both of our issues would be solved by returning `process.cwd()` or maybe the passed through cwd from `getBaseDir`. There would need to be a separate fix for plugin loading (something similar I imagine), but we'd also need to make sure that the fix works with NPM2's deeper directory structure.

**Comment by not-an-aardvark** [comment] 2017-07-11 03:41
The internal config logic was refactored in ESLint 4.1.0. Is this still a problem?

**Comment by epmatsw** [comment] 2017-07-12 01:15
Based on a quick try, it does not appear to have been fixed by those changes, but it's kind of hard to be certain because I've rearranged things quite a bit since I filed this and don't have my original test case around any more. @not-an-aardvark if you're fairly certain that this should work now (configs being resolved relative to the .eslintrc.json rather than the cwd) I can try to do a more rigorous test.

**Comment by not-an-aardvark** [comment] 2017-07-12 01:20
No, I'm not sure either way -- I just asked because some code that seems related to this got modified recently, but the changes weren't specifically intended to address this problem. Thanks for checking again.

**Comment by not-an-aardvark** [comment] 2017-08-31 00:00
Closing this because https://github.com/eslint/eslint/issues/7773 was also closed (see https://github.com/eslint/eslint/issues/7773#issuecomment-322085389), and I think that issue is a duplicate of this one.

Sorry about the long delay in triaging this.

**Closed by not-an-aardvark** 2017-08-31 00:00 UTC
Labels: bug, core, evaluating
