### ISSUE TITLE
CLIEngine 4.1.0 - TypeError: Cannot read property 'getConfig' of undefined

### ISSUE THREAD

**Issue by EvgenyOrekhov** [eslint/eslint#8803] opened 2017-06-25 13:13 UTC
* **ESLint Version:** 4.1.0
* **Node Version:** 8.1.2
* **npm Version:** 5.0.3

**What parser (default, Babel-ESLint, etc.) are you using?**
default

**Please show your full configuration:**

```json
{"extends": "eslint:recommended"}
```

**What did you do? Please include the actual source code causing the issue.**

```js
const {CLIEngine} = require("eslint");

const cli = new CLIEngine({
    useEslintrc: false,
    baseConfig: {extends: "eslint:recommended"}
});
```

**What did you expect to happen?**
I expected to get an instance of `CLIEngine`.

**What actually happened? Please include the actual, raw output from ESLint.**
A TypeError was thrown:

```text
TypeError: Cannot read property 'getConfig' of undefined
    at load (node_modules/eslint/lib/config/config-file.js:582:51)
    at configExtends.reduceRight (node_modules/eslint/lib/config/config-file.js:421:36)
    at Array.reduceRight (native)
    at applyExtends (node_modules/eslint/lib/config/config-file.js:405:28)
    at Object.loadObject (node_modules/eslint/lib/config/config-file.js:567:35)
    at new Config (node_modules/eslint/lib/config.js:70:46)
    at new CLIEngine
```
This bug was introduced in ESLint 4.1.0.

**Comment by ilyavolodin** [comment] 2017-06-25 13:54
Thanks for the issue. This is a duplicate of #8791 and we already have PR open to fix this. Closing this issue as duplicate.

**Closed by ilyavolodin** 2017-06-25 13:54 UTC
Labels: triage
