### ISSUE TITLE
Generic Exceptions to the camelcase rule?

### ISSUE THREAD

**Issue by gkatsanos** [eslint/eslint#9233] opened 2017-09-05 15:12 UTC
**What rule do you want to change?**
camelcase

**Does this change cause the rule to produce more or fewer warnings?**
fewer

**How will the change be implemented? (New option, new default behavior, etc.)?**
new option in the camelcase rule

**Please provide some example code that this change will affect:**

```js
var vwoDefined = typeof window._vwo_code !== 'undefined';
var git_version_file = pathUtils.resolvePath('./GIT_VERSION');
```

**What does the rule currently do for this code?**
throws warning   `warning  Identifier '_vwo_code' is not in camel case `

**What will the rule do after it's changed?**
not throw a warning provided the exception in question is added in the configuration/option

Previous version of the issue:

Is there a way to add generic exceptions to the camelcase rule, like provide a list of items, a regex rule etc?(except adding a comment to disable the rule)
 
For example if there's a global / window variable from a script we have no control over (GA, AB testing tools such as VWO etc)

My suggestion:

```json
"camelcase":[  
   1,
   ['variable_here', 'other_variable']
]
```

**Comment by platinumazure** [comment] 2017-09-05 15:16
At this point, there is no way to do so. I could get behind an exception list being added to this rule, though.

I wanted to note that you could also probably use [`id-match`](https://eslint.org/docs/rules/id-match) to do what you need here. Mind giving that a try? Let us know if you need more information.

If you are strongly interested in enhancing the camelcase rule, could you please edit your original post to match [this template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md)? Thanks!

**Comment by gkatsanos** [comment] 2017-09-05 15:22
I added an example of how this could be handled. Not sure about the syntax. (doesn't matter so much for me)

**Comment by jpickwell** [comment] 2017-10-13 22:09
I think the array of variables should be keyed. Also, regular expressions would be handy for Vue.js support. (https://vuejs.org/v2/style-guide/#Private-property-names-essential)

```
"camelcase": [
  1,
  {
    "exceptions": [
      "some_variable",
      "some_other_variable",
      "/^\$_/"
    ]
  }
]
```

**Comment by kaicataldo** [comment] 2017-10-16 14:44
Relevant comment: https://github.com/eslint/eslint/issues/9435#issuecomment-336610102

**Comment by not-an-aardvark** [comment] 2018-01-19 15:39
Thanks for your interest in improving ESLint. Unfortunately, it looks like this issue didn't get consensus from the team, so I'm closing it. We define [consensus](http://eslint.org/docs/maintainer-guide/issues.html#consensus) as having three :+1:s from team members, as well as a team member willing to champion the proposal. This is a high bar by design -- we can't realistically accept and maintain every feature request in the long term, so we only accept feature requests which are useful enough that there is consensus among the team that they're worth adding.

Since ESLint is pluggable and can load custom rules at runtime, the lack of consensus among the ESLint team doesn't need to be a blocker for you using this in your project, if you'd find it useful. It just means that you would need to [implement the rule](http://eslint.org/docs/developer-guide/working-with-rules) yourself, rather than using a bundled rule that is packaged with ESLint.

**Closed by not-an-aardvark** 2018-01-19 15:39 UTC
Labels: enhancement, evaluating, rule

**Comment by smably** [comment] 2018-06-22 03:44
Is there value in reopening this issue now that React 16.4 has added `UNSAFE_`-prefixed lifecycle methods (e.g., https://reactjs.org/docs/react-component.html#unsafe_componentwillmount)? A lot of React developers will be disabling this rule as the old lifecycle methods are deprecated.

**Comment by platinumazure** [comment] 2018-06-22 03:46
@smably You're welcome to open a new issue with this new context about React, and we'll gladly take another look. Thanks!

**Comment by smably** [comment] 2018-06-22 04:13
@platinumazure Thanks! Done: #10503.
