### ISSUE TITLE
`autofix` option for lint messages?

### ISSUE THREAD

**Issue by bolinfest** [eslint/eslint#1787] opened 2015-02-07 21:59 UTC
In addition to the existing `column`, `line`, `ruleId`, `message`, `severity`, etc. properties defined for a [lint message](http://eslint.org/docs/developer-guide/nodejs-api.html), would you be open to supporting an `autofix` property (and updating many of the built-in rules to use it)?

For example, a JavaScript linter that tells you that you are missing a semicolon should provide the user the option to just add the semicolon in the right spot. This is something that could easily have an `autofix` option.

I was thinking the value of `autofix` could be either a string diff to apply to the file to fix the lint or a JavaScript function that would take the source as input and return the "fixed" source as output (or it could return the diff as a string). The latter is not JSON-serializable, but might be useful for lazily generating the value from `autofix`. In an IDE that runs the linter repeatedly, it's important that the linter runs quickly, so I want to avoid a situation where `autofix` support slows things down.

[Arcanist Lint](https://secure.phabricator.com/book/phabricator/article/arcanist_lint/) supports the `autofix` property, though it appears to be a `severity` level and the patches are a separate property. There isn't a code example there, but it sounds like there can be an array of patches, which seems sensible.

See also https://github.com/AtomLinter/Linter/issues/418

**Comment by lo1tuma** [comment] 2015-02-07 22:03
This is duplicate of #1332.

I don't think this should be done in eslint. You could build a tool which consumes eslint errors and warnings and automatically fixing them.

**Comment by bolinfest** [comment] 2015-02-07 22:06
Hmm, I see that #1332 is closed as wontfix :( It seems like a lot more work to regex parse the error and deduce the meaning and then figure out what the right patch would be than to have the rule implementer do it since presumably most of the computation to figure out the patch has been done in the process of generating the lint in the first place.

**Comment by bolinfest** [comment] 2015-02-07 22:09
It always seems a little lame when a computer can tell me that I'm missing a semicolon yet can't add it for me.

**Comment by nzakas** [comment] 2015-02-07 22:09
As @lo1tuma mentioned, this has been brought up before. It's not a goal of ours to autofix problems.

Although, if I'm reading this correctly, it seems like all you're asking is if it would be possible for rules to suggest fixes and then add that to the message that's returned. Is that correct? That might be something we could do if an external tool wants to use that info to do the actual fixing.

I definitely think it's out-of-scope for ESLint itself to autofix, but providing suggestions as part of messages seems like a lightweight way to allow others to build such functionality on top of ESLint.

**Comment by bolinfest** [comment] 2015-02-07 22:11
@nzakas Right, I'm not asking to run eslint in "autofix" mode: I'm asking it to have the option to produce a patch that other tools can decide what to do with. For "obvious" fixes like a missing semicolon, I don't expect there to be a great debate about what the appropriate patch for eslint to propose would be.

**Comment by nzakas** [comment] 2015-02-07 22:17
Yeah, I think we'd be open to that. Are you interested in coming up with a proposal for how this might be implemented?

**Comment by bolinfest** [comment] 2015-02-07 22:23
@nzakas Sure. I should investigate what Arcanist does in a little more detail for a motivating example, but my instinct is to offer an optional `autofix` property that, if present, contained an array of patches to apply.

I'll have to do a little research into what the JSON patch format should be (and whether it can contain other metadata, such as the file path, or should it always be required that the patch can only be applied to the file that was linted).

I'll do some digging and report back.

**Comment by nzakas** [comment] 2015-02-07 22:38
Awesome, thanks!

**Comment by doberkofler** [comment] 2015-02-08 11:38
@bolinfest This sound like a great addition to eslint

**Comment by michaelficarra** [comment] 2015-02-08 13:17
Guys, this is *exactly* what I was suggesting way back in https://github.com/eslint/eslint/issues/912...

**Comment by nzakas** [comment] 2015-02-08 16:52
Yup, and my response here was the same. If you had put together an implementation proposal, we would have considered it.

**Comment by bolinfest** [comment] 2015-02-08 21:41
OK, I just spent quite a bit of time looking at how Arcanist lint defines and applies autofixes. The API is pretty simple in that there is an [ArcanistLintResult](https://github.com/phacility/arcanist/blob/master/src/lint/ArcanistLintResult.php) with 1 or more [ArcanistLintMessage](https://github.com/phacility/arcanist/blob/master/src/lint/ArcanistLintMessage.php)s.

Each message has the following properties of interest:

* `path` to file
* `line` 1-based line offset
* `char` 1-based column offset
* `originalText` If present, the original code in the file at the line/char offset.
* `replacementText` If present, the code with which to replace `originalText` at the line/char offset.

There is an [ArcanistLintPatcher](https://github.com/phacility/arcanist/blob/master/src/lint/ArcanistLintPatcher.php) that iterates over the messages and applies them if the `replacementText` is non-null and differs from the `originalText`.

If there are multiple changes to apply, it does do the work to keep track of the offset changes introduced by applying earlier changes. All characters before the most recently applied patch are considered "dirty" and subsequent patches that would modify the dirty state are *silently* ignored. I found this behavior a little surprising, but I put together a test repository to verify this: https://github.com/bolinfest/arcanist-lint-test.

Obviously, this is a tricky scenario to handle correctly, but silently ignoring it seems wrong to me. For all ignored lints, I would think the right thing to do would be to keep track of which linters generated them and to re-run those linters after the other fixes were applied. There might be some sort of pathological case where that ends in an infinite loop, though (and it's probably a bad user experience to see the lint run again).

However, in something like an IDE, re-running all the linters after accepting one autofix is what would likely happen naturally, so perhaps this sort of API isn't so bad. I expect that an API that is based on offset/oldText/newText is a lot easier for developers to implement correctly than one based on patch formats, though I'll keep exploring.

**Comment by bolinfest** [comment] 2015-02-08 22:02
After reading [the Wikipedia entry on `diff`](http://en.wikipedia.org/wiki/Diff_utility), I'm disinclined to go with an API that is based on diff formats because they seem like a pain to generate. Arcanist's approach seems a lot simpler.

I'm going to try implementing autofix suggestions for some of ESLint's rules first to see how tricky an offset/oldText/newText API would be to support.

**Comment by bolinfest** [comment] 2015-02-08 23:21
While I'm here: any tips/instructions on how to run an individual test in the eslint codebase? I don't see anything on http://eslint.org/docs/developer-guide/unit-tests.html.

Also, I did a clean checkout on an OS X machine and `npm test` fails :(

**Comment by bolinfest** [comment] 2015-02-08 23:22
nm, `node_modules/.bin/mocha tests/lib/rules/quotes.js` ftw.

**Comment by michaelficarra** [comment] 2015-02-09 00:24
What was wrong with my proposal from #912 to give an AST as the replacement suggestion? We shouldn't be encouraging working with programs as text. I guarantee that will lead to syntax/precedence issues.

Also, we don't need `originalText` if we're already passing in the erroneous node.

**Comment by bolinfest** [comment] 2015-02-09 02:55
@michaelficarra I suspect that such an API would be very difficult for an arbitrary tool to consume and make use of. A line-based suggestion is crude, but much easier to build other tooling on top of, as Arcanist has demonstrated. Ultimately, you would have to turn it into a diff, anyway, for a programming-language agnostic autofix consumer to make use of it.

**Comment by bolinfest** [comment] 2015-02-09 02:59
(Also, I figured out why the tests were failing for me locally: my personal `~/.eslintrc` was interfering with test runs.)

**Comment by michaelficarra** [comment] 2015-02-09 03:28
Then how do you plan to mitigate the inevitable syntax and precedence errors the replacement strings introduce?

**Comment by bolinfest** [comment] 2015-02-09 04:49
I just sent out https://github.com/eslint/eslint/pull/1809, which is a refactoring that I think will make the introduction of autofix cleaner. Even if we ultimately do not accept autofix, I think this is good hygiene for the codebase.

**Comment by bolinfest** [comment] 2015-02-09 05:09
@michaelficarra I'm not sure yet. Perhaps the AST replacement will be an appropriate internal representation, but not an external representation.

**Comment by bolinfest** [comment] 2015-02-09 05:58
@michaelficarra A naive implementation would be to apply the AST replacement and then diff the codegen'd versions of the ASTs. It seems like escodegen is the de-facto standard for generating JavaScript code from a Spidermonkey AST. Unfortunately for me, as best I can tell, it normalizes the code:

```
> escodegen.generate(espree.parse('console.log("Hello world!")'))
'console.log(\'Hello world!\');'
> escodegen.generate(esprima.parse('console.log("Hello world!")'))
'console.log(\'Hello world!\');'
```

In both of these examples, the original code uses double quotes for the string literal and is missing a semicolon, but the generated code uses single quotes for the string literal and adds the semicolon. This is obviously a problem if you want to replace the `"Hello world!"` literal in the AST with `'Hello world!'` and regenerate the output and diff it to produce the replacement text.

Though I guess the problem is that most of these AST transformations would not be in-place, in which case updating the ranges in the other AST nodes so it can codegen correctly is probably the tricky part? Are there other tools I should be looking at? Maybe trying to do something with source maps instead?

**Comment by bolinfest** [comment] 2015-02-09 06:13
Come to think of it, just using the original source and the range of the node might be sufficient to produce the replacement text in a number of cases.

**Comment by nzakas** [comment] 2015-03-06 02:05
@bolinfest are you still investigating this?

**Comment by Techwraith** [comment] 2015-03-31 22:37
Just letting people here know that I'm interested in this too. Has there been any progress here?

**Comment by kyriacos** [comment] 2015-04-07 16:19
Interested in this too. Is it still being investigated?

**Comment by ilyavolodin** [comment] 2015-04-07 16:54
This is one of the items that we want to address for 2.0.0 version. So nobody is working on this actively right now.

**Comment by bhamodi** [comment] 2015-05-22 16:14
+1. Also interested in an auto fix option. However, I'd like to be able to specify a certain rule to auto fix, not all of them. For example, just fixing all the semicolon and comma rule violations would be awesome.

**Comment by gyandeeps** [comment] 2015-05-22 18:22
I am going to close this issue as this is one of the items on this issue: https://github.com/eslint/eslint/issues/2203
For further discussions lets talk on the above mentioned issue.

**Closed by gyandeeps** 2015-05-22 18:22 UTC
Labels: question
