### ISSUE TITLE
Allow output when fixes are automatically applied

### ISSUE THREAD

**Issue by pfhayes** [eslint/eslint#7404] opened 2016-10-19 18:16 UTC
Observed in eslint 3.8.1

Right now if you run with `--fix` and eslint only finds fixable issues, it will output nothing and exit with code 0.

However, it may have caused changes to your files on disk. Developers might not notice this. We've found some problems where developers will run `eslint` and then push to Github, without catching that changes have been applied locally.

Is it currently possible to output messages for fixes that have been automatically applied? Or some other way of differentiating between "everything is good" vs. "there were errors but they were fixed". I'm happy to put together a PR for this if this functionality does not exist.

**Comment by not-an-aardvark** [comment] 2016-10-19 18:28
This seems like a reasonable change. However, in terms of reporting the actual number of fixes, I'm worried about overestimating the number of fixed problems due to the way multi-pass autofixing works.

For example, here's some code:

```js
/* eslint quote-props: [error, "always"], quotes: [error, "single"] */

({ foo: 1 })
```

First, the `quote-props` fixer is applied:

```js
({ "foo": 1 })
```

Then ESLint is run again on the resulting code, to ensure fix any other linting errors that might have been output. In this case, a new error with `quotes` has been created, so another fix will be applied:

```js
({ 'foo': 1 })
```

Then ESLint is run again on the resulting code. No errors are reported, so the process exits.

In this scenario, how many fixes were applied? Technically, 2 fixes were applied, but it might be confusing if we output something like `2 problems fixed`, or `` `quote-props` and `quotes` fixed problems``, because the original code only had one problem. The second fix was only necessary as a result of the first fix.

I still think this change is doable, but if the message is going to be anything more detailed than `some things were fixed`, we should think about how we can convey that without confusion.

**Comment by pfhayes** [comment] 2016-10-19 18:32
"Some things were fixed" is good enough for my purposes - but I understand if we want to evaluate if there is a way to do this "properly"

Could the fixes be emitted as they are applied? So in your example it would emit that the "quote-props" fixer was applied and then it would also emit the "quotes" fixer was applied.

**Comment by not-an-aardvark** [comment] 2016-10-19 18:40
That would probably be feasible -- I'm just worried that it will be confusing to display that the `quotes` fixer was applied, because the `quotes` rule did not report any problems with the original code.

**Comment by platinumazure** [comment] 2016-10-19 19:47
It's worth noting that our Node.JS APIs (specifically CLIEngine) do distinguish between the linting and fixing phase, so one option is to write a wrapper that runs the linter and the fixer but outputs a different exit code or stdout depending on whether fixes were applied.

**Comment by vitorbal** [comment] 2016-10-20 15:08
I think the easiest solution would be for the formatter to output "Some fixes were applied" like @not-an-aardvark suggests. 
I might be wrong, but if you just call bin/eslint.js directly, the formatter doesn't get access to the number of fixes, so the most it could do is check for the presence of the `output` property to know if "fixes were applied" or not, right?

Otherwise, for something more involved, I'd go with @platinumazure's suggestion to wrap the CLIEngine API.

**Comment by pfhayes** [comment] 2016-10-20 20:17
PR here: https://github.com/eslint/eslint/pull/7416

**Comment by vitorbal** [comment] 2016-10-20 20:58
Just to be clear: we need TSC approval before we can mark this proposal as accepted.

**Comment by gyandeeps** [comment] 2016-10-20 21:00
All the reporting done by ESLint is done using a formatter API which many build-in and custom formatters use. We can't just use `console` to output messages/data. We have to consider scenarios where ESLint is programitically used also.

With that being said, if we want to provide this functionality then we need to start thinking wrt to formatter API.

**Comment by nzakas** [comment] 2016-10-21 19:13
I'm of the mind that changing the output of the core to say this will be disruptive to existing systems who are depending on the current output. The CLI is working "as designed", which is to say that if ESLint finds an error that you need to fix, it will tell you, but otherwise won't because there's nothing for you to do. I think that's the correct behavior. Trying to update every formatter to include this information doesn't seem like a good solution to this problem, especially since none of them were created with the idea of displaying whether or not fixes were applied.

For your particular problem @pfhayes, you might want to investigate using a custom formatter instead. You can make it output whatever you want, and there's already an `output` field in the results that is only present when fixes have been applied. You'd just need to update your lint step to reference that formatter.

**Comment by pfhayes** [comment] 2016-10-21 23:26
I've updated the PR so that the output is generated in the `stylish` formatter

**Comment by pfhayes** [comment] 2016-10-21 23:30
@nzakas I would agree that the `unix` formatter, or other formatters that are more appropriate to be consumed by machines, should prehaps not emit anything when fixes are automatically applied.

For `stylish`, I think this is useful information for the reader. I don't agree that there is "nothing for you to do" - if fixes are applied you often need to commit them to your VCS. It routinely bites me and other members of my team that this action is invisibly applied.

**Comment by nzakas** [comment] 2016-10-29 21:55
@pfhayes I know you think this information is important, which is why I'm encouraging you to find a way to include it without making a change to the core. I know it seems like a small thing, but we really can't be sure who is relying on the exact format of the output we have.

Is there a reason you can't create your own formatter that does exactly what you want?

**Comment by pfhayes** [comment] 2016-10-30 21:00
Nothing prohibits this from being a separate formatter - I'm happy to make this an independent formatter if it is not desired in `stylish`.

I think this information is sufficiently useful that many others will find benefit in it, which is why I am proposing it to be included in the default "pretty" output. If this is in a separate formatter then the number of people who can benefit from this change is greatly diminished, particularly for new or beginner users of eslint.

I understand the concerns around breaking the existing output. Perhaps this should be added in the next major version update?

**Comment by nzakas** [comment] 2016-11-14 19:38
I'll be honest - I just don't see a ton of value to adding this into the core. It's my belief that a custom formatter is the right way to go. We'll review at the next TSC meeting to get a consensus. 

(Note for all, related PR: https://github.com/eslint/eslint/pull/7416)

**Comment by nzakas** [comment] 2016-11-14 19:41
TSC Summary: The request is to add some additional output when ESLint has successfully applied fixes so that users are aware that fixes were applied. There are a few implementation possibilities, including updating every formatter or having the ESLint CLI just output warnings itself. All options are considered breaking because it will affect ESLint output that other tools might be relying on. It is possible to create custom formatters to accomplish the same result.

TSC Question: Do we want to pursue this in core, or should we encourage people to create custom formatters if they want such functionality?

**Comment by alberto** [comment] 2016-11-17 22:17
TSC resolution: Issue has been accepted. See [meeting notes](https://github.com/eslint/tsc-meetings/blob/0d75733ef001385a7ff5ba6336e60f210d1b0d21/notes/2016/2016-11-17.md) for details

**Comment by kaicataldo** [comment] 2016-11-29 04:11
Looks like this needs some more discussion as to the actual implementation. We have a [PR](https://github.com/eslint/eslint/pull/7416) open for this issue already, so would be nice to get discussion going @eslint/eslint-team

**Comment by alberto** [comment] 2017-03-14 17:46
I would favor to output the number of fixes being applied, so I would like to hear more opinions before we merge this @eslint/eslint-team

**Comment by not-an-aardvark** [comment] 2017-03-21 21:34
@alberto I agree with that idea in general, but there are a few implementation issues that need to be worked out:

* Would the output come from a formatter, or would it come from core?
  * If it's from a formatter, then the formatter would need to know how many fixes were applied, which isn't currently possible. So we would need to expand the formatter API.
  * If it would come directly from core, the output won't be customizable, which could be annoying. It would also cause problems for programs using computer-readable formatters (e.g. `json`) and expecting the output to be JSON-parsable -- the parsers will fail if there is an unexpected line of output from core.

**Comment by alberto** [comment] 2017-03-21 21:50
@not-an-aardvark I would expand the formatter API to provide the results to formatters.

**Comment by not-an-aardvark** [comment] 2017-03-21 21:55
How would the result be counted? In the example in https://github.com/eslint/eslint/issues/7404#issuecomment-254900044, would the number of fixes be 1 or 2?

**Comment by platinumazure** [comment] 2017-03-21 21:59
Do we actually need to count the fixes?

Would it be sufficient to augment the report object to indicate if fixes were applied (or, perhaps better, written to disk)?

```js
{
    results: [
        {
            filePath: "/Users/eslint/project/myfile.js",
            messages: [{
                ruleId: "semi",
                severity: 2,
                message: "Missing semicolon.",
                line: 1,
                column: 13,
                nodeType: "ExpressionStatement",
                source: "\"use strict\"",
                fix: { range: [12, 12], text: ";" }
            }],
            errorCount: 1,
            warningCount: 0,
            source: "\"use strict\"\n",
            fixesApplied: true           // <--- This would be new
        }
    ],
    errorCount: 1,
    warningCount: 0
}
```

**Comment by alberto** [comment] 2017-03-21 22:00
I'd say 2, I don't find that to be confusing. Do you think it would be less confusing if we also included the number of iterations?

**Comment by not-an-aardvark** [comment] 2017-03-21 22:02
@platinumazure The report object already contains enough information to determine whether fixes were applied (based on the `output` property). That's how the implementation in https://github.com/eslint/eslint/pull/7416 works.

If we just say "fixes were applied" without counting the fixes, then I feel like this feature isn't very useful. We would be violating the [rule of silence](http://www.linfo.org/rule_of_silence.html) for very little benefit.

**Comment by platinumazure** [comment] 2017-03-21 22:04
@not-an-aardvark Are you sure? I was going back to the problem statement at the top of this issue, which is that sometimes files get committed with unintentional changes due to ESLint not indicating that fixes were applied to those files. I don't know how much more information we need than to output files with fixes applied (as you say, it *may* be sufficient to use the output property, although that wouldn't hold for CLIEngine consumers who don't choose to call `CLIEngine.outputFixes()`).

**Comment by not-an-aardvark** [comment] 2017-03-21 22:05
@alberto I think it's very mildly confusing, but it's probably acceptable to output it anyway without including the number of iterations. I suspect many users don't realize that autofix uses multiple passes anyway, so including the number of iterations might just lead to further confusion.

**Comment by not-an-aardvark** [comment] 2017-03-21 22:10
@platinumazure To be honest, I'm not really sold on the benefit of this in the first place, but given that the TSC has already accepted it I'm fine with going along with it. It seems like if someone is intentionally using the `--fix` flag, they are accepting that the files *might* change, so they should look at the diff afterwards if they care about whether files were changed.

**Comment by platinumazure** [comment] 2017-03-21 22:13
@not-an-aardvark True enough. In the particular case of git, one can `git add` all their files before running `eslint --fix`-- any changes in the working directory that aren't on the index would necessarily be changes applied by ESLint.

**Comment by ilyavolodin** [comment] 2017-03-22 02:10
I honestly think that this issue should be moved out of 4.0 and into the next milestone. It doesn't have an implementation yet, and it doesn't even look like we are settled on a way to do this. I would rather not rush a solution just to get it into a release. There's nothing stopping us from doing another major release in a month or two.

**Comment by not-an-aardvark** [comment] 2017-03-22 02:14
I agree that this should be moved out of the 4.0 milestone. 

> There's nothing stopping us from doing another major release in a month or two.

Not sure I agree with this part. Breaking changes can be disruptive to the ecosystem, so I think it's better to space them out a bit if possible. But we don't need to have that discussion right now.

**Comment by alberto** [comment] 2017-03-27 22:45
After having a look at this, I think the best thing to do would be to add the info in a non-enumerable property to the results array. I'm thinking of adding a top level `meta` property (name up for bikeshedding) to contain any needed info. (like total errorCount and warningCount from report object).

The report object would be the natural place for it, but it's just used in the cli and not by the linter api or formatters, so I don't see a clear way to use that in a backwards compatible way.

**Comment by not-an-aardvark** [comment] 2017-03-30 01:02
I agree that the report object would be the natural place for it. I'm concerned that by adding a property the results array, we would be adding information where it wasn't designed to go. The linter API isn't supposed to handle fixes at all -- that decision is supposed to be made by `CLIEngine`. Formatters are just supposed to format a list of problems, without needing additional metadata about the linting steps that generated the list of problems.

Maybe the best way to get around this would be to add a second argument to the formatter API.

**Comment by pfhayes** [comment] 2017-04-11 16:52
I just noticed https://github.com/eslint/eslint/issues/7364. Does this change add the information we need here? Should we just emit these numbers, or do these fixable numbers underestimate the actual number of fixes because of the aforementioned number of iterations?

**Comment by ilyavolodin** [comment] 2017-04-11 18:00
@pfhayes Those are number of fixable problem, not the number of fixes. I.E. some of the fixes might cause other rules to kick in and create extra fixes.

**Comment by kaicataldo** [comment] 2017-10-13 19:07
Looks like this has stalled. Is this something we still want to pursue?

**Comment by not-an-aardvark** [comment] 2017-10-13 19:18
Looking back on this discussion, it seems like there was some confusion about what changes this would require (partially caused by me, since I was also confused).

It seems like:

* This is possible to do with a custom formatter, so no changes would be required to core.
* Arguably, we should enhance the bundled formatters to output this information.
* From what I can tell, the TSC discussion on this a year ago centered on the fact that we would need to change the formatter API in order to make this work, which is not the case.

**Comment by kaicataldo** [comment] 2017-10-13 20:48
@not-an-aardvark Thanks for the summary!

So it sounds like the actual actionable item here is to 
> enhance the bundled formatters to output this information

If this sounds right, I think we should update the issue title, remove the accepted label, and go through the process of gaining consensus again.

**Comment by not-an-aardvark** [comment] 2018-03-24 23:57
Closing because there hasn't been any action on this issue for a long time.

**Closed by not-an-aardvark** 2018-03-24 23:57 UTC
Labels: core, enhancement, evaluating, needs bikeshedding
