### ISSUE TITLE
Cannot extend from scoped npm packages

### ISSUE THREAD

**Issue by axefrog** [eslint/eslint#9868] opened 2018-01-20 21:12 UTC
Apparently eslint does not work with scoped npm packages. My npm package is here:
https://www.npmjs.com/package/@frptools/config

And here is a reference to the file I want to extend from:
https://unpkg.com/@frptools/config/eslint-config-frptools.json

When I try to use my scoped package in my eslintrc file, eslint "helps" me out by editing the `/config` portion of the package name and erroneously prefixing it with `eslint-config-`, when in fact it should be doing this only to the trailing portion of the path. See examples below.

**Tell us about your environment**

* **ESLint Version:** 4.16.0
* **Node Version:** 9.0.0
* **npm Version:** 5.6.0
* **OS Version:** Windows 10

**What parser (default, Babel-ESLint, etc.) are you using?**

CLI (no parser)
My package is symlinked locally, using Lerna and Yarn workspaces.

**Please show your full configuration:**

I have tried all of these:

```json
{
  "extends": "@frptools/config/frptools"
}
```

```bash
eslint src
Error: Cannot find module '@frptools/eslint-config-config/frptools'
```

```json
{
  "extends": "@frptools/config/eslint-config-frptools"
}
```

```bash
eslint src
Error: Cannot find module '@frptools/eslint-config-config/eslint-config-frptools'
```

```json
{
  "extends": "@frptools/config/eslint-config-frptools.json"
}
```

```bash
eslint src
Error: Cannot find module '@frptools/eslint-config-config/eslint-config-frptools.json'
```

**Comment by axefrog** [comment] 2018-01-21 06:22
Still, it's not prefix the start of the package name that's being prefixed, as per what you're saying is intended behaviour, but the middle of the package name.

In any case, perhaps this constraint is unnecessarily restrictive? Why force people to maintain an entire package just for eslint, when it may be useful to store other configurations in there as well?

**Comment by mysticatea** [comment] 2018-01-21 06:36
> the middle of the package name.

`@frptools/config/frptools` is `@scope-name/package-name/file-name`.

> In any case, perhaps this constraint is unnecessarily restrictive? Why force people to maintain an entire package just for eslint, when it may be useful to store other configurations in there as well? The whole point is to load the configuration from a package. Why not make it easy to do that from any package?

Because npm package name was global. We avoided arbitrary names in npm registry for ESLint sharable configs and plugins in order to prevent annoying to other packages.

So probably it makes sense if it allows arbitrary names in personal scopes. But just it doesn't allow currently since we have not received such requests.

**Comment by not-an-aardvark** [comment] 2018-03-05 17:54
Thanks for your interest in improving ESLint. Unfortunately, it looks like this issue didn't get consensus from the team, so I'm closing it. We define [consensus](http://eslint.org/docs/maintainer-guide/issues.html#consensus) as having three :+1:s from team members, as well as a team member willing to champion the proposal. This is a high bar by design -- we can't realistically accept and maintain every feature request in the long term, so we only accept feature requests which are useful enough that there is consensus among the team that they're worth adding.

**Closed by not-an-aardvark** 2018-03-05 17:54 UTC
Labels: core, enhancement, evaluating
