### ISSUE TITLE
Allow no-underscore-dangle to specify if allow beginning and end

### ISSUE THREAD

**Issue by mitchellsimoens** [eslint/eslint#9036] opened 2017-07-29 15:32 UTC
This is a feature request. The `no-underscore-dangle` rule can be handy but I'd like separate options to allow underscores before and/or after the identifier. For example, I personally denote private members with an underscore prefix so I want to allow an underscore before but I do not want an underscore to suffix the identifier.

    var _foo = 'good';
    var bar_ = 'bad';

So I'd specify the rule such as:

    "no-underscore-dangle": [
        "warn",
        {
            "allowPrefix": true, // default would be false
            "allowSuffix": false // should be default
        }
    ]

**Comment by platinumazure** [comment] 2017-07-29 16:05
Hi @mitchellsimoens, thanks for the issue.

This seems reasonable to me, since the current schema should easily map to the new options.

**Comment by not-an-aardvark** [comment] 2017-09-16 05:22
Thanks for your interest in improving ESLint. Unfortunately, it looks like this issue didn't get consensus from the team, so I'm closing it. We define [consensus](http://eslint.org/docs/maintainer-guide/issues.html#consensus) as having three :+1:s from team members, as well as a team member willing to champion the proposal. This is a high bar by design -- we can't realistically accept and maintain every feature request in the long term, so we only accept feature requests which are useful enough that there is consensus among the team that they're worth adding.

Since ESLint is pluggable and can load custom rules at runtime, the lack of consensus among the ESLint team doesn't need to be a blocker for you using this in your project, if you'd find it useful. It just means that you would need to [implement the rule](http://eslint.org/docs/developer-guide/working-with-rules) yourself, rather than using a bundled rule that is packaged with ESLint.

**Closed by not-an-aardvark** 2017-09-16 05:22 UTC
Labels: enhancement, evaluating, rule
