### ISSUE TITLE
Bug: Eslint upgrade to v9. ConfigError: Config (unnamed): Unexpected key "deprecatedRules" found.

### ISSUE THREAD

**Issue by sametsahin37** [eslint/eslint#18661] opened 2024-07-06 14:34 UTC
### Environment

Node version: 20.10.0
yarn version: 3.6.4 
Local ESLint version: 9.6.0
Global ESLint version: 9.6.0
Operating System: MacOS

### What parser are you using?

Default (Espree)

### What did you do?

I'm trying to upgrade ESlint to v9. This is my eslint.config.mjs

```js
import { FlatCompat } from "@eslint/eslintrc";
import react from 'eslint-plugin-react';
import reactNative from 'eslint-plugin-react-native';
import fileName from 'eslint-plugin-filename-rules';
import imprt from 'eslint-plugin-import';
import tseslint from 'typescript-eslint';
import typescriptPlugin from '@typescript-eslint/eslint-plugin';
import * as graphqlEslint from "@graphql-eslint/eslint-plugin"
import * as folders from 'eslint-plugin-folders';
import sonarjs from "eslint-plugin-sonarjs";
import prettier from 'eslint-plugin-prettier';
import prettierRecommended from 'eslint-plugin-prettier/recommended';
import jest from 'eslint-plugin-jest';
import eslintPluginUnicorn from 'eslint-plugin-unicorn';
import eslintPluginReactHooks from 'eslint-plugin-react-hooks';
import eslint from '@eslint/js';
import stylistic from '@stylistic/eslint-plugin'
import globals from "globals";
import { fixupPluginRules } from '@eslint/compat';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const compat = new FlatCompat({
    baseDirectory: __dirname,
    recommendedConfig: eslint.configs.recommended,
    allConfig: eslint.configs.all
});

export default tseslint.config(
    reactNative,
    eslint.configs.recommended,
    prettierRecommended,
    sonarjs.configs.recommended,
    ...compat.extends("airbnb"),
    ...compat.extends("airbnb-typescript"),
    ...tseslint.configs.recommended,
    {
        ignores: [
        "src/assets/translations/*",
        "**/android",
        "**/ios",
        "**/package.json",
        "**/__mocks__",
        "**/jest-setup",
        "**/app.json",
        "**/.eslintrc.js",
        "**/*.config.js",
        "**/coverage",
        "**/schema.graphql",
        "**/node_modules",
        "**/*.d.ts",
        "src/utils/graphql/generated.ts",
        "src/dev-only-purpose",
        "**/__generated__",
        ],
    }, 
    {
        files: ['**/*.{js,jsx,ts,tsx}'],
        plugins: {
            'react': react,
            'react-native': fixupPluginRules(reactNative),
            '@typescript-eslint': tseslint.plugin,
            '@stylistic': stylistic,
            'filename-rules': fixupPluginRules(fileName),
            'import': fixupPluginRules(imprt),
            'prettier': prettier,
            'jest': jest,
            'unicorn': eslintPluginUnicorn,
            'folders': fixupPluginRules(folders),
            'sonarjs': sonarjs,
            'react-hooks': fixupPluginRules(eslintPluginReactHooks)
        },
        languageOptions: {
            ecmaVersion: 12,
            sourceType: 'module',
            parser: tseslint.parser,
            parserOptions: {
                ecmaFeatures: { jsx: true },
                warnOnUnsupportedTypeScriptVersion: false,
                operations: "./src/**/*.graphql",
                schema: "./schema.graphql",
                project: "./tsconfig.json",
            },
            globals: {
                ...globals.jest,
                ...globals.node,
                ...globals.es2021,
                ...globals.browser,
            },
        },
        settings: {
            react: {
              version: 'detect',
            },
        },
        ignores: ["**/src/assets/translations/*"],
        rules: {
            ...eslintPluginReactHooks.configs.recommended.rules,
            "sonarjs/cognitive-complexity": "error",
            "sonarjs/prefer-immediate-return": 0,
            "sonarjs/no-duplicate-string": 0,
            "sonarjs/no-nested-template-literals": 0,
            "sonarjs/no-redundant-jump": 0,
            "sonarjs/no-small-switch": 0,
    
            "import/no-cycle": ["warn", {
                ignoreExternal: true,
            }],
    
            "prettier/prettier": 2,
    
            "no-console": ["warn", {
                allow: ["warn", "error"],
            }],
    
            "@stylistic/comma-dangle": ["error", "always-multiline"],
            "prefer-destructuring": 2,
            "camelcase": 2,
            "object-shorthand": 2,
            "no-nested-ternary": 1,
            "no-shadow": 0,
            "@typescript-eslint/no-shadow": 2,
            "no-unused-vars": 0,
    
            "@typescript-eslint/no-unused-vars": ["error", {
                args: "after-used",
                argsIgnorePattern: "^_",
            }],
    
            "no-use-before-define": "off",
            "@typescript-eslint/no-use-before-define": 2,
            "@typescript-eslint/no-var-requires": 0,
            "@typescript-eslint/explicit-module-boundary-types": 0,
            "@typescript-eslint/no-explicit-any": 2,
            "import/no-default-export": 2,
            "import/prefer-default-export": 0,
            "react/require-default-props": 0,
    
            "import/no-extraneous-dependencies": ["error", {
                devDependencies: true,
            }],
    
            "react/function-component-definition": "off",
            "react/jsx-uses-react": "off",
            "react/react-in-jsx-scope": "off",
            "react/prop-types": "off",
    
            "react/jsx-curly-brace-presence": ["error", {
                props: "never",
                children: "never",
            }],
    
            "react-native/no-inline-styles": 2,
            "consistent-return": "off",
            curly: ["error", "all"],
            "react/display-name": "off",
    
            "@typescript-eslint/naming-convention": ["off", {
                selector: ["enumMember", "enum"],
                format: ["PascalCase"],
            }],
    
            "@typescript-eslint/consistent-type-definitions": ["error", "type"],
            "unicorn/no-abusive-eslint-disable": "error",
    
            "unicorn/filename-case": ["error", {
                case: "kebabCase",
                ignore: ["[A-Za-z]+.tsx", "[A-Za-z]+.d.ts", "[A-Za-z0-9]+.graphql"],
            }],
    
            "filename-rules/match": [2, {
                ".tsx": "PascalCase",
                ".ts": {},
            }],
    
            "folders/match-regex": [2, {}, "/src/"],
    
            "no-restricted-imports": [1, {
                paths: [{
                    name: "@fresh-direct/theme",
                    importNames: ["theme", "gaps", "colors"],
                    message: "Please use useTheme from @rneui/themed instead.",
                }, {
                    name: "react-native",
                    importNames: ["ScrollView", "FlatList"],
                    message: "Please consider to use needed element from react-native-gesture-handler; https://github.com/gorhom/react-native-bottom-sheet/issues/770",
                }],
    
                patterns: [{
                    group: ["**/__generated__/types"],
                    message: "\nIt's a general backend types those might be not available on the client.\nPlease use types provided by the query/hook/service.\nOr use ApiEnums",
                }],
            }],
        },
    },
    // OVERRIDES
    {
        files: ['*.test.{ts,tsx}'],
        plugins: {
            'react-native': fixupPluginRules(reactNative),
            '@typescript-eslint': tseslint.plugin,
        },
        rules: {
          'react-native/no-inline-styles': 0,
          '@typescript-eslint/no-empty-function': 0,
          '@typescript-eslint/no-explicit-any': 0,
          '@typescript-eslint/no-unused-vars': 0,
        },
    },
    {
        files: ['*.json'],
        plugins: {
            '@stylistic': stylistic,
        },
        rules: {
          '@stylistic/comma-dangle': 'off',
        },
    },
    {
        files: ['{**/,}/{constants,utils}/{**/,}*.{ts,tsx}'],
        plugins: {
            'filename-rules': fixupPluginRules(fileName),
        },
        rules: {
          'filename-rules/match': [
            2,
            {
              '.tsx': 'PascalCase',
              '.ts': 'kebab-case',
            },
          ],
        },
    },
    {
        files: ['**/*.graphql'],
        languageOptions: {
            parser: {...graphqlEslint, meta: { name: "@graphql-eslint" }}
        },
        plugins: {
            '@graphql-eslint': fixupPluginRules(graphqlEslint),
            'prettier': prettier,
        },
        rules: {
            "prettier/prettier": [2, {
                parser: "graphql",
            }],
            "@graphql-eslint/fields-on-correct-type": "error",
            "@graphql-eslint/fragments-on-composite-type": "error",
            "@graphql-eslint/known-argument-names": 0,
            "@graphql-eslint/known-directives": "error",
            "@graphql-eslint/known-type-names": "error",
            "@graphql-eslint/no-anonymous-operations": "error",
            "@graphql-eslint/no-deprecated": "warn",
            "@graphql-eslint/no-unused-variables": "warn",
            "@graphql-eslint/provided-required-arguments": "error",
            "@graphql-eslint/scalar-leafs": "error",
            "@graphql-eslint/unique-argument-names": "error",
            "@graphql-eslint/unique-input-field-names": "error",
            "@graphql-eslint/unique-variable-names": "error",
            "@graphql-eslint/value-literals-of-correct-type": "error",
            "@graphql-eslint/variables-are-input-types": "error",
            "@graphql-eslint/variables-in-allowed-position": "error",
            "@graphql-eslint/match-document-filename": ["error", {
                fileExtension: ".graphql",
                query: "PascalCase",
                mutation: "PascalCase",
                subscription: "PascalCase",
    
                fragment: {
                    style: "PascalCase",
                    suffix: ".fragment",
                },
            }],
        },
    },
)
```

### What did you expect to happen?

I expect to run OK when I type yarn lint

### What actually happened?

It throwed an error:

Oops! Something went wrong! :(

ESLint: 9.6.0

ConfigError: Config (unnamed): Unexpected key "deprecatedRules" found.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/vitejs-vite-fbhlqh?file=.eslintrc.cjs

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by franblanco95** [comment] 2024-07-18 15:30
The 'eslint-plugin-react-native' plugin is giving that error.. Not sure why.. But if you remove that plugin it starts working

**Comment by mdjermanovic** [comment] 2024-07-18 16:35
> ### Link to Minimal Reproducible Example
> https://stackblitz.com/edit/vitejs-vite-fbhlqh?file=.eslintrc.cjs

This seems to be an example with eslint v8.57.0 and `.eslintrc.cjs` config file. Please provide a reproducible example where you are getting the error from the original post with eslint v9 and `eslint.config.mjs` config file.

As @franblanco95 noted, the problem is probably with how the `eslint-plugin-react-native` plugin is used in the config file.

In particular:

```js
import reactNative from 'eslint-plugin-react-native';
// ...
export default tseslint.config(
    reactNative,
// ...
```

It seems that you are inserting a plugin object directly into the config array where config objects are expected, not plugin objects.

**Comment by nzakas** [comment] 2024-07-18 17:41
@mdjermanovic don't forget to move issues into "Triaging" when you're working on them.

**Comment by Manhha3010** [comment] 2024-07-26 02:14
> It doesn't matter if the plugin has a key for `deprecatedRules`, that's not the error.
> 
> The error is that a config object contains `deprecatedRules`. You'll need to track down which object that is. Try using `--inspect-config`.

how can i using lint v9 with react native ? 
import reactNativeConfig from '@react-native/eslint-config';
import reactNative from '@react-native/eslint-plugin';

**Comment by nzakas** [comment] 2024-07-29 14:39
This isn't a bug with ESLint, so closing.

@Manhha3010 I have no idea. you'd need to contact the maintainers of react native for help.

**Closed by nzakas** 2024-07-29 14:39 UTC
Labels: bug, needs info, repro:needed

**Comment by Maruth51** [comment] 2024-08-12 11:20
> ### Environment
> Node version: 20.10.0 yarn version: 3.6.4 Local ESLint version: 9.6.0 Global ESLint version: 9.6.0 Operating System: MacOS
> 
> ### What parser are you using?
> Default (Espree)
> 
> ### What did you do?
> I'm trying to upgrade ESlint to v9. This is my eslint.config.mjs
> 
> ```js
> import { FlatCompat } from "@eslint/eslintrc";
> import react from 'eslint-plugin-react';
> import reactNative from 'eslint-plugin-react-native';
> import fileName from 'eslint-plugin-filename-rules';
> import imprt from 'eslint-plugin-import';
> import tseslint from 'typescript-eslint';
> import typescriptPlugin from '@typescript-eslint/eslint-plugin';
> import * as graphqlEslint from "@graphql-eslint/eslint-plugin"
> import * as folders from 'eslint-plugin-folders';
> import sonarjs from "eslint-plugin-sonarjs";
> import prettier from 'eslint-plugin-prettier';
> import prettierRecommended from 'eslint-plugin-prettier/recommended';
> import jest from 'eslint-plugin-jest';
> import eslintPluginUnicorn from 'eslint-plugin-unicorn';
> import eslintPluginReactHooks from 'eslint-plugin-react-hooks';
> import eslint from '@eslint/js';
> import stylistic from '@stylistic/eslint-plugin'
> import globals from "globals";
> import { fixupPluginRules } from '@eslint/compat';
> import { fileURLToPath } from 'node:url';
> import path from 'node:path';
> 
> const __filename = fileURLToPath(import.meta.url);
> const __dirname = path.dirname(__filename);
> 
> const compat = new FlatCompat({
>     baseDirectory: __dirname,
>     recommendedConfig: eslint.configs.recommended,
>     allConfig: eslint.configs.all
> });
> 
> export default tseslint.config(
>     reactNative,
>     eslint.configs.recommended,
>     prettierRecommended,
>     sonarjs.configs.recommended,
>     ...compat.extends("airbnb"),
>     ...compat.extends("airbnb-typescript"),
>     ...tseslint.configs.recommended,
>     {
>         ignores: [
>         "src/assets/translations/*",
>         "**/android",
>         "**/ios",
>         "**/package.json",
>         "**/__mocks__",
>         "**/jest-setup",
>         "**/app.json",
>         "**/.eslintrc.js",
>         "**/*.config.js",
>         "**/coverage",
>         "**/schema.graphql",
>         "**/node_modules",
>         "**/*.d.ts",
>         "src/utils/graphql/generated.ts",
>         "src/dev-only-purpose",
>         "**/__generated__",
>         ],
>     }, 
>     {
>         files: ['**/*.{js,jsx,ts,tsx}'],
>         plugins: {
>             'react': react,
>             'react-native': fixupPluginRules(reactNative),
>             '@typescript-eslint': tseslint.plugin,
>             '@stylistic': stylistic,
>             'filename-rules': fixupPluginRules(fileName),
>             'import': fixupPluginRules(imprt),
>             'prettier': prettier,
>             'jest': jest,
>             'unicorn': eslintPluginUnicorn,
>             'folders': fixupPluginRules(folders),
>             'sonarjs': sonarjs,
>             'react-hooks': fixupPluginRules(eslintPluginReactHooks)
>         },
>         languageOptions: {
>             ecmaVersion: 12,
>             sourceType: 'module',
>             parser: tseslint.parser,
>             parserOptions: {
>                 ecmaFeatures: { jsx: true },
>                 warnOnUnsupportedTypeScriptVersion: false,
>                 operations: "./src/**/*.graphql",
>                 schema: "./schema.graphql",
>                 project: "./tsconfig.json",
>             },
>             globals: {
>                 ...globals.jest,
>                 ...globals.node,
>                 ...globals.es2021,
>                 ...globals.browser,
>             },
>         },
>         settings: {
>             react: {
>               version: 'detect',
>             },
>         },
>         ignores: ["**/src/assets/translations/*"],
>         rules: {
>             ...eslintPluginReactHooks.configs.recommended.rules,
>             "sonarjs/cognitive-complexity": "error",
>             "sonarjs/prefer-immediate-return": 0,
>             "sonarjs/no-duplicate-string": 0,
>             "sonarjs/no-nested-template-literals": 0,
>             "sonarjs/no-redundant-jump": 0,
>             "sonarjs/no-small-switch": 0,
>     
>             "import/no-cycle": ["warn", {
>                 ignoreExternal: true,
>             }],
>     
>             "prettier/prettier": 2,
>     
>             "no-console": ["warn", {
>                 allow: ["warn", "error"],
>             }],
>     
>             "@stylistic/comma-dangle": ["error", "always-multiline"],
>             "prefer-destructuring": 2,
>             "camelcase": 2,
>             "object-shorthand": 2,
>             "no-nested-ternary": 1,
>             "no-shadow": 0,
>             "@typescript-eslint/no-shadow": 2,
>             "no-unused-vars": 0,
>     
>             "@typescript-eslint/no-unused-vars": ["error", {
>                 args: "after-used",
>                 argsIgnorePattern: "^_",
>             }],
>     
>             "no-use-before-define": "off",
>             "@typescript-eslint/no-use-before-define": 2,
>             "@typescript-eslint/no-var-requires": 0,
>             "@typescript-eslint/explicit-module-boundary-types": 0,
>             "@typescript-eslint/no-explicit-any": 2,
>             "import/no-default-export": 2,
>             "import/prefer-default-export": 0,
>             "react/require-default-props": 0,
>     
>             "import/no-extraneous-dependencies": ["error", {
>                 devDependencies: true,
>             }],
>     
>             "react/function-component-definition": "off",
>             "react/jsx-uses-react": "off",
>             "react/react-in-jsx-scope": "off",
>             "react/prop-types": "off",
>     
>             "react/jsx-curly-brace-presence": ["error", {
>                 props: "never",
>                 children: "never",
>             }],
>     
>             "react-native/no-inline-styles": 2,
>             "consistent-return": "off",
>             curly: ["error", "all"],
>             "react/display-name": "off",
>     
>             "@typescript-eslint/naming-convention": ["off", {
>                 selector: ["enumMember", "enum"],
>                 format: ["PascalCase"],
>             }],
>     
>             "@typescript-eslint/consistent-type-definitions": ["error", "type"],
>             "unicorn/no-abusive-eslint-disable": "error",
>     
>             "unicorn/filename-case": ["error", {
>                 case: "kebabCase",
>                 ignore: ["[A-Za-z]+.tsx", "[A-Za-z]+.d.ts", "[A-Za-z0-9]+.graphql"],
>             }],
>     
>             "filename-rules/match": [2, {
>                 ".tsx": "PascalCase",
>                 ".ts": {},
>             }],
>     
>             "folders/match-regex": [2, {}, "/src/"],
>     
>             "no-restricted-imports": [1, {
>                 paths: [{
>                     name: "@fresh-direct/theme",
>                     importNames: ["theme", "gaps", "colors"],
>                     message: "Please use useTheme from @rneui/themed instead.",
>                 }, {
>                     name: "react-native",
>                     importNames: ["ScrollView", "FlatList"],
>                     message: "Please consider to use needed element from react-native-gesture-handler; https://github.com/gorhom/react-native-bottom-sheet/issues/770",
>                 }],
>     
>                 patterns: [{
>                     group: ["**/__generated__/types"],
>                     message: "\nIt's a general backend types those might be not available on the client.\nPlease use types provided by the query/hook/service.\nOr use ApiEnums",
>                 }],
>             }],
>         },
>     },
>     // OVERRIDES
>     {
>         files: ['*.test.{ts,tsx}'],
>         plugins: {
>             'react-native': fixupPluginRules(reactNative),
>             '@typescript-eslint': tseslint.plugin,
>         },
>         rules: {
>           'react-native/no-inline-styles': 0,
>           '@typescript-eslint/no-empty-function': 0,
>           '@typescript-eslint/no-explicit-any': 0,
>           '@typescript-eslint/no-unused-vars': 0,
>         },
>     },
>     {
>         files: ['*.json'],
>         plugins: {
>             '@stylistic': stylistic,
>         },
>         rules: {
>           '@stylistic/comma-dangle': 'off',
>         },
>     },
>     {
>         files: ['{**/,}/{constants,utils}/{**/,}*.{ts,tsx}'],
>         plugins: {
>             'filename-rules': fixupPluginRules(fileName),
>         },
>         rules: {
>           'filename-rules/match': [
>             2,
>             {
>               '.tsx': 'PascalCase',
>               '.ts': 'kebab-case',
>             },
>           ],
>         },
>     },
>     {
>         files: ['**/*.graphql'],
>         languageOptions: {
>             parser: {...graphqlEslint, meta: { name: "@graphql-eslint" }}
>         },
>         plugins: {
>             '@graphql-eslint': fixupPluginRules(graphqlEslint),
>             'prettier': prettier,
>         },
>         rules: {
>             "prettier/prettier": [2, {
>                 parser: "graphql",
>             }],
>             "@graphql-eslint/fields-on-correct-type": "error",
>             "@graphql-eslint/fragments-on-composite-type": "error",
>             "@graphql-eslint/known-argument-names": 0,
>             "@graphql-eslint/known-directives": "error",
>             "@graphql-eslint/known-type-names": "error",
>             "@graphql-eslint/no-anonymous-operations": "error",
>             "@graphql-eslint/no-deprecated": "warn",
>             "@graphql-eslint/no-unused-variables": "warn",
>             "@graphql-eslint/provided-required-arguments": "error",
>             "@graphql-eslint/scalar-leafs": "error",
>             "@graphql-eslint/unique-argument-names": "error",
>             "@graphql-eslint/unique-input-field-names": "error",
>             "@graphql-eslint/unique-variable-names": "error",
>             "@graphql-eslint/value-literals-of-correct-type": "error",
>             "@graphql-eslint/variables-are-input-types": "error",
>             "@graphql-eslint/variables-in-allowed-position": "error",
>             "@graphql-eslint/match-document-filename": ["error", {
>                 fileExtension: ".graphql",
>                 query: "PascalCase",
>                 mutation: "PascalCase",
>                 subscription: "PascalCase",
>     
>                 fragment: {
>                     style: "PascalCase",
>                     suffix: ".fragment",
>                 },
>             }],
>         },
>     },
> )
> ```
> 
> ### What did you expect to happen?
> I expect to run OK when I type yarn lint
> 
> ### What actually happened?
> It throwed an error:
> 
> Oops! Something went wrong! :(
> 
> ESLint: 9.6.0
> 
> ConfigError: Config (unnamed): Unexpected key "deprecatedRules" found.
> 
> ### Link to Minimal Reproducible Example
> https://stackblitz.com/edit/vitejs-vite-fbhlqh?file=.eslintrc.cjs
> 
> ### Participation
> * [ ]  I am willing to submit a pull request for this issue.
> 
> ### Additional comments
> _No response_

I faced similar issue, i updated node to v18.20.2 it fixed and working

**Comment by efstathiosntonas** [comment] 2024-09-03 08:10
@sametsahin37 hi, did you managed to solve this?

**Comment by ht-ishan** [comment] 2025-04-28 16:04
I had similar issue with prettier plugin. After searching here I checked the documentation of prettier and found I was using latest config file(eslint.config.js) with legacy way of adding prettier i.e. .eslintrc file. Actually it was added by AI IDE. So its better to always check documentation manually whenever got stuck.
