### ISSUE TITLE
Bug: (no-warning-comments: warn)

### ISSUE THREAD

**Issue by emanual4real** [eslint/eslint#15607] opened 2022-02-14 21:29 UTC
### Environment

Node version: 16.13.1
npm version: 8.5.0
Local ESLint version: 8.9.0
Global ESLint version: n/a
Operating System: Rocky Linux 8.5

### What parser are you using?

@typescript-eslint/parser

### What did you do?

<details>
<summary>Fresh CRA</summary>

1. Ran `npx create-react-app my-app --template typescript`
2. Ran `npm init @eslint/config` Chose airbnb, react, browser options
3. Add `"no-warning-comments": "warn",` rule to .eslintrc.js
4. Add `// TODO: I need to add some real code.`
5. Ran command `"eslint \"src/**/*.{js,jsx,ts,tsx}\" --quiet"`
6. Change `"no-warning-comments": "error",` rule in .eslintrc.js
7. Ran command `"eslint \"src/**/*.{js,jsx,ts,tsx}\" --quiet"`

Step 5 had no warnings
Step 7 had errors

</details>

### What did you expect to happen?

I expected to receive a warning for using `\\ TODO: lorem ipsum...`

### What actually happened?

I did not receive a warning for using `\\ TODO: lorem ipsum...`

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by mdjermanovic** [comment] 2022-02-14 23:04
Hi @emanual4real, thanks for the issue!

 

> 3\. Add `"no-warning-comments": "warn",` rule to .eslintrc.js
> 4\. Add `// TODO: I need to add some real code.`
> 5\. Ran command `"eslint \"src/**/*.{js,jsx,ts,tsx}\" --quiet"`
> 6\. Change `"no-warning-comments": "error",` rule in .eslintrc.js
> 7\. Ran command `"eslint \"src/**/*.{js,jsx,ts,tsx}\" --quiet"`
> 
> Step 5 had no warnings Step 7 had errors

This is expected behavior because the [`--quiet`](https://eslint.org/docs/user-guide/command-line-interface#--quiet) flag disables reporting on warnings (rules configured with `"warn"`). It's exactly the purpose of this flag, to show only problems reported by rules that were configured with the `"error"` severity.

I'm closing this issue since it works as intended. If I have misunderstood something, please let me know and I'll reopen the issue.

**Closed by mdjermanovic** 2022-02-14 23:04 UTC
Labels: works as intended
