### ISSUE TITLE
Bug: Cannot read properties of undefined (reading 'type') after esquery updated to 1.4.1

### ISSUE THREAD

**Issue by AhmedSaied94** [eslint/eslint#16900] opened 2023-02-16 14:11 UTC
### Environment

Node version: 16.18.0 
npm version: 8.19.2
Local ESLint version: 8.31.0
Global ESLint version:  8.31.0
Operating System: github action

### What parser are you using?

Default (Espree)

### What did you do?

<details>
<summary>Configuration</summary>

```
{
    "env": {
        "browser": true,
        "es2021": true
    },
    "extends": [
        "eslint:recommended",
        "standard",
        "plugin:react/recommended"
    ],
    "globals": {
        "Atomics": "readonly",
        "SharedArrayBuffer": "readonly"
    },
    "parserOptions": {
        "ecmaFeatures": {
            "jsx": true
        },
        "ecmaVersion": 12,
        "sourceType": "module"
    },
    "plugins": [
        "react",
        "react-hooks"
    ],
}
```
</details>

```
eslint ./src
```

### What did you expect to happen?

lint the src directory

### What actually happened?

<details>
<summary>Configuration</summary>

```
> frontend_v2@0.1.0 lint
> eslint ./src


Oops! Something went wrong! :(

ESLint: 8.31.0

TypeError: Cannot read properties of undefined (reading 'type')
Occurred while linting /home/runner/work/sm_frontend/sm_frontend/src/App.js:1
    at /home/runner/work/sm_frontend/sm_frontend/node_modules/esquery/dist/esquery.min.js:1:29469
    at /home/runner/work/sm_frontend/sm_frontend/node_modules/esquery/dist/esquery.min.js:1:30512
    at Function.b.matches (/home/runner/work/sm_frontend/sm_frontend/node_modules/esquery/dist/esquery.min.js:1:34848)
    at NodeEventGenerator.applySelector (/home/runner/work/sm_frontend/sm_frontend/node_modules/eslint/lib/linter/node-event-generator.js:296:21)
    at NodeEventGenerator.applySelectors (/home/runner/work/sm_frontend/sm_frontend/node_modules/eslint/lib/linter/node-event-generator.js:324:22)
    at NodeEventGenerator.enterNode (/home/runner/work/sm_frontend/sm_frontend/node_modules/eslint/lib/linter/node-event-generator.js:340:14)
    at CodePathAnalyzer.enterNode (/home/runner/work/sm_frontend/sm_frontend/node_modules/eslint/lib/linter/code-path-analysis/code-path-analyzer.js:795:23)
    at /home/runner/work/sm_frontend/sm_frontend/node_modules/eslint/lib/linter/linter.js:1150:32
    at Array.forEach (<anonymous>)
    at runRules (/home/runner/work/sm_frontend/sm_frontend/node_modules/eslint/lib/linter/linter.js:1145:15)
Error: Process completed with exit code 2.
```
</details>

### Participation

- [ ] I am willing to submit a pull request for this issue.

### Additional comments

i was be able to fix the problem by downgrading the esquery version to 1.4.0 but be aware to this issue

**Comment by Rec0iL99** [comment] 2023-02-16 14:44
Duplicate of #16896

**Closed** 2023-02-16 14:58 UTC
Labels: bug, repro:needed
