### ISSUE TITLE
no-unused-vars crashes for enum fields with quotes in Svelte TS file

### ISSUE THREAD

**Issue by iOiurson** [eslint/eslint#14760] opened 2021-07-01 10:25 UTC
Hello !

I'm running against this error which concerns the `no-unused-vars` rule.

```bash
AssertionError [ERR_ASSERTION]: Node must be provided when reporting error if location is not provided
    at assertValidNodeInfo (/Users/Romain/Code/map/front/node_modules/eslint/lib/linter/report-translator.js:98:9)
    at /Users/Romain/Code/map/front/node_modules/eslint/lib/linter/report-translator.js:332:9
    at Object.report (/Users/Romain/Code/map/front/node_modules/eslint/lib/linter/linter.js:922:41)
    at Program:exit (/Users/Romain/Code/map/front/node_modules/eslint/lib/rules/no-unused-vars.js:667:33)
    at /Users/Romain/Code/map/front/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/Users/Romain/Code/map/front/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/Users/Romain/Code/map/front/node_modules/eslint/lib/linter/node-event-generator.js:293:26)
    at NodeEventGenerator.applySelectors (/Users/Romain/Code/map/front/node_modules/eslint/lib/linter/node-event-generator.js:322:22)
    at NodeEventGenerator.leaveNode (/Users/Romain/Code/map/front/node_modules/eslint/lib/linter/node-event-generator.js:345:14)
```

Commenting `no-unused-vars` solves it, using the equivalent `@typescript-eslint/no-unused-vars` too (my codebase is in TS).

This is my config:

```js
module.exports = {
    root: true,
    env: {
        browser: true,
        es6: true,
        node: true,
    },
    parser: '@typescript-eslint/parser',
    parserOptions: {
        ecmaVersion: 2019,
        sourceType: 'module',
    },
    plugins: ['svelte3', 'prettier', 'cypress', '@typescript-eslint'],
    extends: [
        'eslint:recommended',
        'plugin:cypress/recommended',
        'plugin:@typescript-eslint/recommended',
    ],
    rules: {
        eqeqeq: ['error', 'always', { null: 'ignore' }],
        'no-alert': 'error',
        'no-var': 'error',
        'prefer-arrow-callback': 'error',
        'id-length': ['error', { min: 1, max: 30 }],
        'no-unused-vars': [
            'error',
            {
                args: 'after-used',
                ignoreRestSiblings: true,
            },
        ],
        '@typescript-eslint/explicit-function-return-type': ['error', { allowExpressions: true }],
        '@typescript-eslint/explicit-module-boundary-types': 'off',
        '@typescript-eslint/no-inferrable-types': [
            'error',
            {
                ignoreParameters: true,
                ignoreProperties: true,
            },
        ],
        // '@typescript-eslint/no-unused-vars': [
        //     'error',
        //     {
        //         args: 'after-used',
        //         ignoreRestSiblings: true,
        //     },
        // ],
        '@typescript-eslint/no-explicit-any': ['error', { ignoreRestArgs: true }],
    },
    overrides: [
        {
            files: ['*.svelte'],
            processor: 'svelte3/svelte3',
        },
        {
            files: ['**/*.ts'],
            extends: ['plugin:prettier/recommended', 'plugin:@typescript-eslint/recommended'],
        },
    ],
    settings: {
        'svelte3/typescript': () => require('typescript'),
        'svelte3/ignore-styles': () => {
            return true;
        },
    },
};

```

* **ESLint Version:** 7.29
* **Node Version:** 14.13.1
* **npm Version:** 6.14.8
* **Operating System:** MacOS 11.4

**Comment by mdjermanovic** [comment] 2021-07-01 10:33
Hi @iOiurson!

Can you please fill out the rest of the bug report template, we can't know why the rule crashes without a code example on which that happens.

**Comment by iOiurson** [comment] 2021-07-01 10:57
Sorry about that, i admit that i was lazy earlier, i thought it was a generic issue.

This is actually quite specific.

It only occurs for `.svelte` files with TS.

The problem comes from defining enum fields with quotes.

Here is the repro:

```svelte
<!-- repro.svelte -->
<script lang="ts">
    enum MyEnum {
        'should-break',
        'shouldBreak',
        works
    }
</script>
```

Everything works fine in an equivalent `.ts` file.

```ts
enum MyEnum {
    'this-works-no-pb',
}
```

**Comment by aladdin-add** [comment] 2021-07-01 11:38
you will have to use '@typescript-eslint/no-unused-vars'(if you are using ts).

another point is: maybe we could fix it to make it not crash with the core rules.

**Comment by mdjermanovic** [comment] 2021-07-01 17:06
The cause of the problem is that `no-unused-vars` expects an array of [identifiers](https://eslint.org/docs/developer-guide/scope-manager-interface#identifiers) which define the variable, but `@typescript-eslint/parser` doesn't populate this array with quoted enum fields because they're not identifiers but string literals.

This means that the core rule `no-unused-vars` and `@typescript-eslint/parser` are not compatible.

The solution is to disable `no-unused-vars` and enable [`@typescript-eslint/no-unused-vars`](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-unused-vars.md) rule instead.

I'm closing this issue since the replacement rule exists in the typescript plugin.

**Closed by mdjermanovic** 2021-07-01 17:06 UTC
Labels: 3rd party plugin
