### ISSUE TITLE
Yoda "except range" fails with other check in same statement. 

### ISSUE THREAD

**Issue by jaepage** [eslint/eslint#7682] opened 2016-11-30 20:42 UTC
Environment: 

    "eslint": "^3.10.1",
    "eslint-config-airbnb": "^13.0.0",
    "eslint-plugin-import": "^2.2.0",
    "eslint-plugin-jsx-a11y": "^2.0.0",
    "eslint-plugin-react": "^6.7.0",
    Node v6.7.0
    NPM 3.10.8
    Sublime Text 3, build 3126
    Mac OS X El Capitan 10.11.6 (15G1004)

Rule in project's `.eslintrc.json`:

    "yoda": [1, "never", { "exceptRange": true }]

Code in question:

    if (percent !== null && 0 <= percent && percent < 100) {

Linter response: 

    Expected literal to be on the right side of <=. (yoda)

Expected response: 

    Linter should not complain.

**Comment by vitorbal** [comment] 2016-12-01 14:16
Thank you for your issue. I believe this is a duplicate of #7676. @mysticatea can you confirm?

**Comment by platinumazure** [comment] 2016-12-01 18:14
@vitorbal Not sure it's an exact duplicate: #7676 seems to be about different operators (or exceptRange being utterly broken, not sure), whereas this issue seems to be about three conditions throwing off the rule. Maybe the root cause is similar or the same, but on the face of it I don't think this is a duplicate.

**Comment by jaepage** [comment] 2016-12-01 22:51
I don't believe my issue filed here is the same as the one linked above. In my if-check, I first confirm that the variable is not equal to `null`, before checking whether it fits in the range. 

The value `null` is falsey, and a `null` variable would ordinarily result in `true` when compared to a range that includes the value `0`. Because I want to include `0` in my range while _excluding_ `null`, I precede the range with a short-circuit against `null`.

**Comment by platinumazure** [comment] 2016-12-02 00:04
Haven't had a chance to try to repro yet, so marking bug/evaluating for now. If it turns out this is a duplicate, we can close.

**Comment by mysticatea** [comment] 2016-12-02 02:12
This issue is different to #7676. But this behavior is intentionally as based on #1570, I think.

**Comment by mysticatea** [comment] 2016-12-02 02:18
Sounds good if `yoda` rule can distinguish ranges without parentheses.
So I mark this issue as an enhancement.

**Comment by btmills** [comment] 2016-12-06 15:46
@mysticatea correct, the paren restriction made things easier to implement, but the intention was always to relax it if somebody asked. :+1: from me.

**Comment by nzakas** [comment] 2016-12-28 18:40
Team - we need a champion for this proposal or else it's time to close it.

**Comment by platinumazure** [comment] 2016-12-28 19:09
@eslint/eslint-team If we can get a champion on this, we can accept the issue.

**Comment by not-an-aardvark** [comment] 2016-12-28 19:15
I'll champion this.

**Comment by not-an-aardvark** [comment] 2017-05-15 05:47
I'm unassigning myself from this issue because I don't think I'll have time to work on it.

**Comment by not-an-aardvark** [comment] 2017-07-11 02:24
Closing this as it doesn't appear that there is enough interest, either from the team or from the community, to implement this at this time.

**Closed by not-an-aardvark** 2017-07-11 02:24 UTC
Labels: accepted, enhancement, help wanted, rule
