### ISSUE TITLE
Provide a default plugin list only aware of breaking code errors .

### ISSUE THREAD

**Issue by eromoe** [eslint/eslint#9179] opened 2017-08-29 09:06 UTC
Hello, 

I only want `eslint` tell me where has syntax error , such as `function not found`  or something else which make my code broken.  Unfortunately,  there are too much plugin, it is not friendly for newbee.

As we usually choose a boilerplate which has a custom eslint config. Errors like below are really annoying(from some eslint config, as a newbee, I have to disable eslint to make these disappear):

![image](https://user-images.githubusercontent.com/3938751/29108622-64588d6a-7d12-11e7-9328-6f26b8f0c1af.png)

![image](https://user-images.githubusercontent.com/3938751/29108613-5a9ef340-7d12-11e7-9c13-618e78ab98e0.png) 

And I see there is a eslint config parameter use to `autofix` error, but I don't tend to fix error like 
```
[eslint] 'select' is defined but never used. (no-unused-vars)
```

So, I think it would be nice to split in three level (or provide some standard to set plugin level )

1. [Break code error] `eslint` only tell me where has syntax error , import error, not define  etc.  
2. [Warning that need append new line, comma, indent ..etc ]
3. [Warning that need delete some of you code, `no-unused-vars` ..etc]

But even `eslint:recommended`  contain many rules would not break code.

I think most people would like `1.` (at least newbee like me ).
Beauty code is `2.` can use in auto-fix .   `3.` is for the strict ones (lazy man like to keeps some code may use in tomorrow, and auto clean that only on deployment).

**Comment by not-an-aardvark** [comment] 2017-08-30 20:31
Thanks for the proposal.

Hmm, I'm not sure about this. The goal of `eslint:recommended` is to catch issues that are likely to be mistakes in your code (such as undefined variable references, unreachable code, and unused variables). I don't see the value of separating out problems that would actually cause runtime exceptions. For example, even if unreachable code doesn't cause an error to be thrown in your code, it's almost certainly not what the developer intended to do. I think the main purpose of a linter is to catch mistakes like this. If you just want to catch issues that will cause a runtime exception, you could simply run the code and see if an error gets thrown.

**Comment by platinumazure** [comment] 2017-08-31 01:00
This can be done by running ESLint with no configuration (`--no-eslintrc`). Will that suffice?

(N.B. We don't automatically run recommended rules by default- even that requires a configuration with `"extends": "eslint:recommended"`.)

**Comment by ilyavolodin** [comment] 2017-09-03 13:49
@platinumazure I think we made a change at some point, that makes ESLint error out if no config at all is provided, so I don't think your suggestion will work.

@eromoe I agree with @not-an-aardvark `eslint:recommended` is what you are looking for. Some of the rule might look like they are not necessary, but there are edge cases where what they are tracking will break your code, unless fixed.

**Comment by platinumazure** [comment] 2017-09-03 13:56
@ilyavolodin We support running with no config *only if* user specifically says `--no-eslintrc`. If users don't specify any options related to configs and no config can be found using our usual traversal methods, we throw an error in that case. Using `--no-eslintrc` and no other configuration options means ESLint will parse only.

That said, ESLint's power comes from the core rules and the ability to add your own rules, so of course I agree that users should create a configuration and leverage some rules, including but not limited to `eslint:recommended`.

**Comment by not-an-aardvark** [comment] 2018-01-19 15:55
Thanks for your interest in improving ESLint. Unfortunately, it looks like this issue didn't get consensus from the team, so I'm closing it. We define [consensus](http://eslint.org/docs/maintainer-guide/issues.html#consensus) as having three :+1:s from team members, as well as a team member willing to champion the proposal. This is a high bar by design -- we can't realistically accept and maintain every feature request in the long term, so we only accept feature requests which are useful enough that there is consensus among the team that they're worth adding.

**Closed by not-an-aardvark** 2018-01-19 15:55 UTC
Labels: core, enhancement, evaluating
