### ISSUE TITLE
 how to use custom eslint plugin in CLIEngine class?   is the property of rulePaths? how to use rulePaths?what is the format?

### ISSUE THREAD

**Issue by xinqiymsz** [eslint/eslint#14134] opened 2021-02-24 14:03 UTC
how to use custom eslint plugin in CLIEngine class?  
is the property of rulePaths? how to use rulePaths?what is the format?

**Comment by mdjermanovic** [comment] 2021-02-24 22:20
Closing as a duplicate of https://github.com/eslint/eslint/discussions/14133

**Closed by mdjermanovic** 2021-02-24 22:20 UTC
Labels: bug
