### ISSUE TITLE
indent option for higher-order functions

### ISSUE THREAD

**Issue by xareelee** [eslint/eslint#8939] opened 2017-07-13 03:39 UTC
ESLint asks the arrow functions should be indented:

```js
export const ofoGraphQLPost =
  (server: ?BaseURL) =>
    (token: string) =>
      (query: string, variables?: Object = {}): Promise<any> => {
        const path = `graphql?access_token=${token}`;
        const url = urljoin(server, path);
        const requestInit = graphqlRequestInit(query, variables);

        return fetch(url, requestInit)
          .then(response => response.json());
      };
```

but I want to keep the same indentation level for multiple arrow functions (higher-order function):

```js
export const ofoGraphQLPost =
  (server: ?BaseURL) =>
  (token: string) =>
  (query: string, variables?: Object = {}): Promise<any> => {
    const path = `graphql?access_token=${token}`;
    const url = urljoin(server, path);
    const requestInit = graphqlRequestInit(query, variables);

    return fetch(url, requestInit)
      .then(response => response.json());
  };
```

Does or will ESLint support that?

**Comment by not-an-aardvark** [comment] 2017-07-13 03:53
Sorry, this isn't supported.

**Comment by not-an-aardvark** [comment] 2017-08-28 03:30
Thanks for your interest in improving ESLint. Unfortunately, it looks like this issue didn't get consensus from the team, so I'm closing it. We define [consensus](http://eslint.org/docs/maintainer-guide/issues.html#consensus) as having three :+1:s from team members, as well as a team member willing to champion the proposal. This is a high bar by design -- we can't realistically accept and maintain every feature request in the long term, so we only accept feature requests which are useful enough that there is consensus among the team that they're worth adding.

Since ESLint is pluggable and can load custom rules at runtime, the lack of consensus among the ESLint team doesn't need to be a blocker for you using this in your project, if you'd find it useful. It just means that you would need to [implement it as a rule](http://eslint.org/docs/developer-guide/working-with-rules) yourself, rather than using a bundled rule that is packaged with ESLint.

**Closed by not-an-aardvark** 2017-08-28 03:30 UTC
Labels: enhancement, evaluating, indent, rule
