### ISSUE TITLE
Change Request: Support `info` and `hint` severity levels

### ISSUE THREAD

**Issue by ackvf** [eslint/eslint#17828] opened 2023-12-08 00:09 UTC
### ESLint version

v7.32

### What problem do you want to solve?

With IDEs and extensions evolving, it would be great time to revisit this old ticket https://github.com/eslint/eslint/issues/6139
- `error` and `warn` are supposed to be intrusive and prompt the user to resolve them, even though `warn` may be not enforced during build.
- `info` and `hint` levels are useful bits of information to the programmer, but don't require any action - those can be custom eslint rules, rules to consider in the future, etc.

### What do you think is the correct solution?

I would like Eslint to support `error`, `warn`, `info` and `hint` severity levels.

### Participation

- [ ] I am willing to submit a pull request for this change.

**Comment by nzakas** [comment] 2023-12-12 17:04
Duplicate of https://github.com/eslint/eslint/issues/6139.

This has been suggested before, but it doesn't actually make sense for ESLint. See the referenced issue above for discussion.

**Closed by nzakas** 2023-12-12 17:04 UTC
Labels: enhancement, core

**Comment by ackvf** [comment] 2023-12-18 22:45
Hi @nzakas I did go through the linked discussion contrary to your belief, it seems to more support the idea of adding several logging levels with a variety of elaborate use-cases, than provide a _strong consensus against doing so_. Moreover, the linke ticket is over 7 years old and the ecosystem around software development has changed drastically. Now with ever smarter IDEs and onset of AI integrations, more granular feedback would really be beneficial and it would certainly allow more sophisticated integrations built on top of eslint.

**Comment by psychedelicious** [comment] 2024-01-20 06:31
@nzakas I agree with @ackvf . Things have changed since 2016. Are you willing to re-open this issue for discussion?

My use-case for `eslint` having `info` and/or `hint` severity levels must be fairly common. There are patterns that contributors _probably_ should do, but not always.

For example, say you have `functionCommon` and `functionRare` that do similar things. `functionCommon` should be used in 99% of cases, but 1% of the time, you should `functionRare`. I'd like to provide an feedback when `functionRare` is used, but not fail any checks.

At first glance, this sounds like a use-case for `warn`. However, it is very common to use `--max-warnings 0` during CI. This allows individual commits to be non-compliant, but a change/PR must be compliant. It's a much nicer developer experience than failing immediately on `warn` rules.

Having an `info` level would provide two very nice DX wins:
- Provide feedback during checks like "This thing you are doing is probably a bad idea, and you should double-check your work - but we aren't going to fail the checks".
- Editors could use this metadata to provide inline hinting, like a little neutral-colored squiggly line, indicating to devs that there is something in this area they should double-check.

**Comment by Rec0iL99** [comment] 2024-01-21 04:47
After reading through the discussions around this, I feel having `warn` and `info` severity levels in the core would be confusing to users. This feels like a feature that should exist in a 3rd party wrapper around ESLint like this https://github.com/eslint/eslint/issues/6972#issuecomment-242279061 suggests.

**Comment by psychedelicious** [comment] 2024-01-22 06:11
@Rec0iL99 While it may make sense (from some perspectives) for a `info` level to be outside the core, I doubt such wrapper will ever exist. Certainly not with the ubiquity of `eslint`. So it's not a very practical suggestion.

From a user perspective, supporting more granular severity seems very reasonable and would allow `eslint` to be used in more expressive ways. Conceptually, an additional severity level sounds very much in line with the goals of `eslint`:

> Find and fix problems in your JavaScript code 

A comment in #6139 has a good suggestion to re-frame the existing levels to fudge more granular severity:

> For the specific use case you outlined, you could use two separate configurations (one for normal development, one for CI specifically). The CI configuration would extend the main configuration but set more rules to "error" level as needed. Your "info" rules are represented by rules set to "warn" in both configurations; your "fix before check-in" rules are represented by rules set to "warn" in the main configuration and "error" in the CI configuration. You can use npm scripts to encapsulate all that, as well.

https://github.com/eslint/eslint/issues/6139#issuecomment-219306198

It's a bit fiddly to have two different sets of rules but this is probably a workable solution for those who want more granularity in their static analysis.
