### ISSUE TITLE
--init fails silently if no package.json present

### ISSUE THREAD

**Issue by nafarlee** [eslint/eslint#5226] opened 2016-02-13 00:05 UTC
Just installed version 2.0.0

Running --init on a folder missing a package.json will prompt the user to answer all of the questions, but upon answering the final question, will exit without creating an .eslintrc or signaling any type of failure. It also signals to the command line that it exited successfully.

**Comment by nafarlee** [comment] 2016-02-13 00:13
Further testing reveals that the --init question path that allows the user to "Answer questions about your style" seems to fail no matter what.

**Comment by gyandeeps** [comment] 2016-02-13 00:18
Probably duplicate of https://github.com/eslint/eslint/issues/5220

**Comment by ilyavolodin** [comment] 2016-02-13 00:40
Yes, this is a duplicate of #5220 and it has been fixed in #5222 Should be released with the next patch.

**Closed by ilyavolodin** 2016-02-13 00:40 UTC
Labels: triage
