### ISSUE TITLE
Request: a way to disable autofixing for `no-debugger`

### ISSUE THREAD

**Issue by Kovensky** [eslint/eslint#8695] opened 2017-06-07 07:09 UTC
`no-debugger` now has support for autofix in 4.0.0.

The problem with that support is that, if you have autofix on save enabled on your code editor (very useful for being able to forget about indents, quote styles, etc), it becomes _impossible_ to write temporary `debugger` statements for debugging without first turning off the rule; but I do not necessarily want a chance of that statement being _committed_ to the repository.

**Comment by not-an-aardvark** [comment] 2017-06-07 07:12
I think this is a duplicate of https://github.com/eslint/eslint/issues/8018, https://github.com/eslint/eslint/issues/8479, and https://github.com/eslint/eslint/issues/8039. At the moment, it is possible to disable autofixing for `no-debugger` by doing something like `eslint yourFile.js --fix --rule 'no-debugger:off'`. Some editor integrations like [`linter-eslint`](http://github.com/atomlinter/linter-eslint) have an option for disabling a particular rule when autofixing.

**Comment by kaicataldo** [comment] 2017-06-12 04:06
Closing this issue as it looks like the question has been answered. Please feel free to visit us in the [ESLint Gitter](https://gitter.im/eslint/eslint) if you have any other issues!

**Closed by kaicataldo** 2017-06-12 04:06 UTC
Labels: question
