### ISSUE TITLE
"indent" rule doesnt respect indentation in multiline expressions using parenthesis

### ISSUE THREAD

**Issue by sagiavinash** [eslint/eslint#7972] opened 2017-01-24 08:22 UTC
* **ESLint Version:**
"eslint": "^3.14.0",
"eslint-config-airbnb": "^14.0.0",
"eslint-plugin-import": "^2.2.0",
"eslint-plugin-jsx-a11y": "^3.0.2",
"eslint-plugin-react": "^6.9.0",
* **Node Version:**
v5.0.0
* ** npm Version:**
3.3.12
* ** Parser **
babel-eslint

Configuration:
```
module.exports = {
  "extends": "airbnb",
  "env": {
    "browser": true,
    "es6": true,
    "jest": true,
  },
  "globals": {
   
    "process": true,
    "module": true,
    "window": true,
   
    "$": true,
   
    "belongError": true,
    "FS": true,
    "Intercom": true,
    "Appcues": true,
    "Raven": true,
   
    "SEGMENT_API_KEY": true,
    "APP_RESOURCE_VERSION": true,
    "LOGGED_IN_USER_ID": true,
    "LOGGED_IN_USER_EMAIL": true,
    "LOGGED_IN_USER_ORG_ID": true,
    "USER_ROLE": true,
    "USER_PERSONA_NAME": true,
    "ACCOUNTS_URL": true,
    "PROVIDER": true,
  },
  "parser": "babel-eslint",
  "rules": {
    /* Errors */
    "newline-before-return": "error",

    /* Ignored */
    "max-len": "off",
    "react/no-multi-comp": "off",
    "react/no-danger": "off",
    "no-bitwise": "off",
    "arrow-parens": "off",
    "react/jsx-filename-extension": "off",
    "class-methods-use-this": "off",
    "import/prefer-default-export": "off",
   
    "jsx-a11y/no-static-element-interactions": "off",
    "jsx-a11y/img-has-alt": "off",
    "jsx-a11y/label-has-for": "off",
    "jsx-a11y/href-no-hash": "off",
    "jsx-a11y/tabindex-no-positive": "off",
    "jsx-a11y/heading-has-content": "off",
   
    "react/forbid-prop-types": "off",
    "no-useless-escape": "off",
    "react/no-unescaped-entities": "off",
    "react/jsx-no-target-blank": "off",
    "react/no-string-refs": "off",
    "react/no-find-dom-node": "off",
    "react/require-default-props": "off",
    "no-plusplus": "off",
    "react/self-closing-comp": "off",
    "no-mixed-operators": "off",
    "react/no-array-index-key": "off",
    "import/no-extraneous-dependencies": ["off", { "devDependencies": ["**/*.test.js", "**/*.spec.js"], }],
    "react/no-unused-prop-types": "off",
  },
  "ecmaFeatures": {
    "jsx": true,
  },
};
```

**What did you do? Please include the actual source code causing the issue.**
Snippet1:
![eslint1](https://cloud.githubusercontent.com/assets/2546485/22239328/fbaa1836-e23b-11e6-9320-2025256a0c3a.png)
Snippet2:
![eslint2](https://cloud.githubusercontent.com/assets/2546485/22239329/fd6f7e90-e23b-11e6-8f43-8eb855cdd51a.png)
Snippet3:
![eslint3](https://cloud.githubusercontent.com/assets/2546485/22239330/fe74e4f6-e23b-11e6-946c-4882292ac467.png)

**What did you expect to happen?**
I expected Snippet1, Snippet3 to be correct.

**What actually happened? Please include the actual, raw output from ESLint.**
according to eslint Snippet1, Snippet2 to be correct.

**Comment by not-an-aardvark** [comment] 2017-01-24 15:16
Thanks for the report.

This is a duplicate of https://github.com/eslint/eslint/issues/6007, so I'm going to close this. Please follow https://github.com/eslint/eslint/issues/6007 instead.

**Closed by not-an-aardvark** 2017-01-24 15:16 UTC
Labels: triage
