### ISSUE TITLE
Change Request: Add support of custom file-extension of ESLint flat config

### ISSUE THREAD

**Issue by pubmikeb** [eslint/eslint#17178] opened 2023-05-13 11:36 UTC
### ESLint version

8.40.0

### What problem do you want to solve?

Currently, a name and an extension of the ESLint flat config file is hard-coded and must be `eslint.config` with the extension `.js`.

However, some projects are purely `.mjs` or even TypeScript based (`.ts`, `.mts`), and in sake of consistency of the code base, it is better to keep all script-files in the same format.

### What do you think is the correct solution?

It would be great if ESLint could check not only for `eslint.config.js`, but also for:
* `eslint.config.mjs`
* `eslint.config.ts`
* `eslint.config.mts`

Of course, the edge-case when `eslint.config` persists in multiple formats should be addressed.

### Participation

- [ ] I am willing to submit a pull request for this change.

**Comment by Rec0iL99** [comment] 2023-05-13 13:44
Duplicate of #16580.

Hi @pubmikeb, thanks for the issue. You can use the `-c` option in CLI to pass `eslint.config.cjs` or `eslint.config.mjs` as another file format other than `.js`.

As for `.ts` and `.mts`, ESLint core is not designed for TypeScript code. TypeScript is handled by a 3rd party ESLint plugin (`typescript-eslint`).

[Docs](https://eslint.org/docs/latest/use/configure/configuration-files-new#configuration-file-resolution)

**Closed by Rec0iL99** 2023-05-13 13:44 UTC
Labels: enhancement, core
