### ISSUE TITLE
indent looks off in 4.x

### ISSUE THREAD

**Issue by paladox** [eslint/eslint#8881] opened 2017-07-05 15:57 UTC
**Tell us about your environment**

* **ESLint Version:**
4.1.1

* **Node Version:**
v8.1.3
* **npm Version:**
5.0.4
**What parser (default, Babel-ESLint, etc.) are you using?**
default and eslint-config-google

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

https://github.com/google/eslint-config-google/blob/master/index.js

https://github.com/GerritCodeReview/gerrit/blob/master/polygerrit-ui/app/.eslintrc.json

</details>

**What did you do? Please include the actual source code causing the issue.**

When running eslint under 4.x it does this for the indentation
```js
    _getDiff() {
      return this.$.restAPI.getDiff(
          this.changeNum,
          this.patchRange.basePatchNum,
          this.patchRange.patchNum,
          this.path,
          this._handleGetDiffError.bind(this)).then(diff => {
        this.filesWeblinks = {
          meta_a: diff && diff.meta_a && diff.meta_a.web_links,
          meta_b: diff && diff.meta_b && diff.meta_b.web_links,
        };
        return diff;
      });
    },
```
before:
```js
    _getDiff() {
      return this.$.restAPI.getDiff(
          this.changeNum,
          this.patchRange.basePatchNum,
          this.patchRange.patchNum,
          this.path,
          this._handleGetDiffError.bind(this)).then(diff => {
            this.filesWeblinks = {
              meta_a: diff && diff.meta_a && diff.meta_a.web_links,
              meta_b: diff && diff.meta_b && diff.meta_b.web_links,
            };
            return diff;
          });
    },
```

**What did you expect to happen?**
I expect that this.filesWeblinks line should be under this._handleGetDiffError not a couple lines before it.
**What actually happened? Please include the actual, raw output from ESLint.**
it's indentation put it before it now. Worked in eslint 3.x but changed it to putting it behind that line in 4.x.

https://gerrit-review.googlesource.com/#/c/112350/4/polygerrit-ui/app/elements/diff/gr-diff/gr-diff.js

**Comment by not-an-aardvark** [comment] 2017-07-05 18:01
Thanks for the report. This is working as intended -- the `.then` call is chained from the `getDiff` call, and it's not a descendant of the `this._handleGetDiffError.bind(this)` argument. So the body of the `.then` call is offset from the `getDiff` call, not `this._handleGetDiffError.bind(this)`.

It's easier to see where this indentation choice comes from if you insert a linebreak:

```js
    _getDiff() {
      return this.$.restAPI.getDiff(
          this.changeNum,
          this.patchRange.basePatchNum,
          this.patchRange.patchNum,
          this.path,
          this._handleGetDiffError.bind(this)
      ).then(diff => {
        this.filesWeblinks = {
          meta_a: diff && diff.meta_a && diff.meta_a.web_links,
          meta_b: diff && diff.meta_b && diff.meta_b.web_links,
        };
        return diff;
      });
    },
```

Anecdotally, when looking at the "before" version of your code, I was initially confused because I thought the `.then` call was a descendant of `this._handleGetDiffError.bind(this)`. I think the fixed `indent` behavior is useful in that regard because it helps to point out possibly-incorrect nesting without needing to count parentheses.

**Comment by not-an-aardvark** [comment] 2017-07-11 02:16
Closing because this is working as intended.

**Closed by not-an-aardvark** 2017-07-11 02:16 UTC
Labels: works as intended
