### ISSUE TITLE
Wrong line number on `no-unused-vars` error

### ISSUE THREAD

**Issue by mt-sebastien-robert** [eslint/eslint#12311] opened 2019-09-25 05:37 UTC
**Tell us about your environment**

* **ESLint Version:** `5.16.0`
* **Node Version:** `10.9.0`
* **npm Version:** `6.4.1`

**What parser (default, Babel-ESLint, etc.) are you using?**
`Default`

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

Here are the YAML config files:
- Entry: https://github.com/moneytree/eslint-config/blob/master/eslintrc/nodejs-bin.yml
- Base: https://github.com/moneytree/eslint-config/blob/master/eslintrc/nodejs.yml

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
const doSomeProcessing = (obj) => {
  // do something with obj and possibly create a new one
  return obj;
};

let obj = { x: 1 };

obj = doSomeProcessing(obj);
obj = doSomeProcessing(obj);
```

```bash
npm run eslint
```

**What did you expect to happen?**

Expecting an error on line 9, character 1, on the first `obj = `.
Like: `9:1  error  'obj' is assigned a value but never used    no-unused-vars`

**What actually happened? Please include the actual, raw output from ESLint.**

Get an error on line 6, character 5.
ESLint output:
```bash
6:5  error  'obj' is assigned a value but never used    no-unused-vars`
```
This is very misleading because `obj` is used on line 8. The rule `no-unused-vars` is very clear about the conditions to be fulfilled.

**Note**

Removing the `obj =` on line 9:
```js
const doSomeProcessing = (obj) => {
  // do something with obj and possibly create a new one
  return obj;
};

let obj = { x: 1 };

obj = doSomeProcessing(obj);
doSomeProcessing(obj);
```
makes the error on line 6 go away. I think the error should point to line 9 and not line 6.

**Are you willing to submit a pull request to fix this bug?**

Why not, but I have absolutely zero knowledge about the internals of ESLint.

**Comment by kaicataldo** [comment] 2019-09-25 21:19
I can see why this would be confusing, but I actually believe this is working as intended. It looks like we currently report the declaration rather than the last assignment. Sounds like you're advocating for reporting the last assignment to the unused variable, which I think would also be a legitimate way to report this (in the case of a reassigned variable). I don't think the current behavior is broken, though, and I would consider this to be more of an enhancement as it would be employing another strategy to reporting the error.

**Comment by mt-sebastien-robert** [comment] 2019-09-25 23:29
Thank you for the consideration.

Right, this is not necessarily a bug, depending on the point of view, I agree. I'm fine with an enhancement, as long as this is improved and the confusion gone ^^

Let me know if I can help further. In the meantime I will try to find a bit of time to have a look at the ESLint internals.

**Comment by mt-sebastien-robert** [comment] 2019-09-27 02:35
@kaicataldo 
After a quick code check (cloned and read from my editor) I think I won't be able to find the time needed to learn deeper and update the rule. Sorry about that.

**Closed** 2019-10-28 22:43 UTC
Labels: enhancement, evaluating, rule
