### ISSUE TITLE
`--print-config` ignore the old `overrides` field and flat config overrides

### ISSUE THREAD

**Issue by Conaclos** [eslint/eslint#18206] opened 2024-03-14 16:09 UTC
### Environment

Node version: 21.7.0
npm version: 10.5.0
Local ESLint version: 9.0.0-beta.2
Global ESLint version: none
Operating System: ArchLinux (up-to-date)

### What parser are you using?

Default (Espree)

### What did you do?

Reproduction:

```sh
❯ npm init --yes

❯ npm i -D --save-exact eslint@9.0.0-beta.2

❯ cat eslint.config.mjs
export default [
    {
        rules: { "prefer-const": "error" }
    },
    {
        files: ["**/*.js"],
        ignores: ["**/*.config.js"],
        rules: { "no-console": "error" },
        languageOptions: { globals: { MY_CUSTOM_GLOBAL: "readonly" } }
    }
];

❯ npx eslint --print-config eslint.config.mjs
{
  "linterOptions": {
    "reportUnusedDisableDirectives": 1
  },
  "languageOptions": {
    "ecmaVersion": "latest",
    "sourceType": "module",
    "parser": "espree@10.0.1",
    "parserOptions": {},
    "globals": {}
  },
  "plugins": [
    "@"
  ],
  "rules": {
    "prefer-const": [
      2
    ]
  }
}
```

The issue is also present for the last stable version of eslint with the old config format:

```sh
❯ npm init --yes

❯ npm i -D --save-exact eslint@8.57.0

❯ cat eslint.config.mjs
export default {
  "rules": {
    "prefer-const": "error"
  },
  "overrides": [
     {
        files: ["**/*.js"],
        rules: { "no-console": "error" },
        languageOptions: { globals: { MY_CUSTOM_GLOBAL: "readonly" } }
    }
  ]
};

❯ npx eslint --print-config eslint.config.mjs
{
  "languageOptions": {
    "ecmaVersion": "latest",
    "sourceType": "module",
    "parser": "espree@9.6.1",
    "parserOptions": {},
    "globals": {}
  },
  "plugins": [
    "@"
  ],
  "rules": {
    "prefer-const": [
      2
    ]
  }
}
```

### What did you expect to happen?

I expect `--print-config` I prints one of the following output:

Either this output:

```json
{
  "linterOptions": {
    "reportUnusedDisableDirectives": 1
  },
  "languageOptions": {
    "ecmaVersion": "latest",
    "sourceType": "module",
    "parser": "espree@10.0.1",
    "parserOptions": {},
    "globals": {}
  },
  "plugins": [
    "@"
  ],
  "rules": {
    "prefer-const": [
      2
    ]
  }
  overrides: [
    {
        files: ["**/*.js"],
        excluded_files: ["**/*.config.js"],
        rules: { "no-console": "error" },
        languageOptions: { globals: { MY_CUSTOM_GLOBAL: "readonly" } }
    }
  ]
}
```

or "simply" the resolved flat config:

```json
[
  {
    "linterOptions": {
      "reportUnusedDisableDirectives": 1
    },
    "languageOptions": {
      "ecmaVersion": "latest",
      "sourceType": "module",
      "parser": "espree@10.0.1",
      "parserOptions": {},
      "globals": {}
    },
    "plugins": [
     "@"
    ],
    "rules": {
      "prefer-const": [
        2
      ]
    }
  },
  {
    files: ["**/*.js"],
    ignores: ["**/*.config.js"],
    rules: { "no-console": "error" },
    languageOptions: { globals: { MY_CUSTOM_GLOBAL: "readonly" } }
  }
]
```

### What actually happened?

`overrides` and flat config overrides are ignored.

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by mdjermanovic** [comment] 2024-03-14 17:22
Hi @Conaclos, thanks for the issue!

This works as intended. `npx eslint --print-config eslint.config.mjs` prints calculated configuration that will be used when linting `eslint.config.mjs` file.

https://eslint.org/docs/latest/use/command-line-interface#--print-config

> This option outputs the configuration to be used for the file passed.

If you use `--print-config` with a .js file, for example `npx eslint --print-config foo.js`, it will return merged configuration that includes settings for `**/*.js` files.

```
$ npx eslint --print-config foo.js
{
  "linterOptions": {
    "reportUnusedDisableDirectives": 1
  },
  "languageOptions": {
    "ecmaVersion": "latest",
    "sourceType": "module",
    "globals": {
      "MY_CUSTOM_GLOBAL": "readonly"
    },
    "parser": "espree@10.0.1",
    "parserOptions": {}
  },
  "plugins": [
    "@"
  ],
  "rules": {
    "prefer-const": [
      2
    ],
    "no-console": [
      2
    ]
  }
}
```

**Closed by mdjermanovic** 2024-03-14 17:22 UTC
Labels: works as intended
