### ISSUE TITLE
Proposal: Add WIP rule documentation style guide to repo

### ISSUE THREAD

**Issue by aubergine10** [eslint/eslint#6465] opened 2016-06-18 14:07 UTC
Currently rule documentation style guide is being discussed in a myriad of issues, and it's getting difficult to see the wood for the trees.

Is it OK to add a WIP document to the repo, so that we can track changes to it, discuss changes in PRs, etc?

The document would be limited scope: rule documentation.

Cons:
- An unfinished document, with non-stable guidance in repo
  - Mitigate by filename (eg. `_style-guide(WIP).md` and h1 message at start of doc?

Pros:
- All style guide discussions focus on one tracked file
- Bikeshedding leads to tangible results in the file
- It's easier to discuss and iterate something that exists, than something that doesn't
- Whilst maintaining docs, if we spot an issue, we can update the guide as part of our workflow

cc: @pedrottimark @scriptdaemon @ilyavolodin

**Comment by platinumazure** [comment] 2016-06-18 14:15
One disadvantage of relying on multiple issues is that it's not clear when a comment might be overridden by a later comment unless folks are very good at going back and striking through old comment text (and maybe not even then). A source controlled file shows history just as well via commits, but also very clearly shows latest and greatest. Only question is how to avoid confusing people.

**Comment by ilyavolodin** [comment] 2016-06-18 16:45
That's what I've been asking for a while. It takes a long time to read through all of the discussions we have on format of the documentation. I just want to see a template with all the latest discussions. Github actually provides much better facility to deal with the, instead of creating a PR. You can use wiki (which supports the same md format) while you are in the process of discussing all of the different approaches. When the template is stable, it can be checked into the repository.

**Comment by aubergine10** [comment] 2016-06-19 00:24
@ilyavolodin the wiki for the eslint repo is currently disabled - at least to non-contributors. On forking the repo I saw why - it has all the old docs in it.

**Comment by pedrottimark** [comment] 2016-06-20 14:43
@aubergine10 Because I need to fix a serious regression mistake that I have made before I can give your recent issues and PR the attention they deserve, could you put the ball in play with a rough draft on your wiki?

It sounds like the following 2 docs are the minimum?
* imagine a link from Working with Rules to whichever of the following titles you think is more meaningful: Editing Rule Docs or Rule Doc Conventions
* Rule Doc Template

@ilyavolodin Any other thoughts about highest priority things to include at the beginning?

**Comment by aubergine10** [comment] 2016-06-20 15:09
Yup, I'll add a rough draft to the wiki this evening and post link here when done.

**Comment by pedrottimark** [comment] 2016-06-20 15:20
Question about a rule doc template: where are y’all aiming toward between the extremes:
* **minimal** template that most people will need to add to
* **maximal** template that most people will need to delete from

Given whatever target y’all think is most helpful to contributors, we could consider linking to some actual rule docs which are examples of simpler or more complex than the template.

**Comment by aubergine10** [comment] 2016-06-20 15:40
My plan is that the template should be a series of headings, and under each heading state:

* if it's optional, conditional or required
* what sort of stuff should go in it (link to rule docs as example)
* template content that can be edited

I'm hoping to keep it minimal, while still providing clear guidance to authors. It will obviously need several rounds of edits and feedback over coming week or two.

BTW, there are also markdown linters, we could apply [rules](https://github.com/DavidAnson/markdownlint/blob/master/doc/Rules.md) to our docs in CI. I'm discussing a [heading validation rule](https://github.com/DavidAnson/markdownlint/issues/22#issuecomment-226971264) with the project maintainer. Other rules could be added, eg. to ensure correct caption pattern for fenced code samples.

**Comment by pedrottimark** [comment] 2016-06-20 15:54
Here are the current rules that apply when `Validating Markdown Files`

https://github.com/eslint/eslint/blob/master/Makefile.js#L329-L358

**Comment by ilyavolodin** [comment] 2016-06-20 16:59
@pedrottimark I think Rule Documentation Template is probably the best place to start. I would go with maximum template, noting which parts are optional. @aubergine10 plan sounds good.

**Comment by aubergine10** [comment] 2016-06-20 19:54
For heading names and order, what do you think to this approach:

https://github.com/aubergine10/scrapbook/wiki/quote-props-(example-layout)

**Comment by aubergine10** [comment] 2016-06-22 03:49
@pedrottimark In the markdown linter code you linked earlier, I assume `false` means to disable the rule?

**Comment by aubergine10** [comment] 2016-06-22 17:21
Initial drafts:

* [Contributing Documentation](https://github.com/aubergine10/scrapbook/wiki/Contributing-Documentation) - doc-specific workflow
* [Markdown Style Guide](https://github.com/aubergine10/scrapbook/wiki/Markdown-Style-Guide) - markdown linting
* [Rule Docs Style Guide](https://github.com/aubergine10/scrapbook/wiki/Rule-Style-Guide) - specific guidelines for rule docs
* [Example Rule Doc](https://github.com/aubergine10/scrapbook/wiki/Example-Rule-Doc) - example to refer to while reading rule style guide

**Comment by aubergine10** [comment] 2016-06-23 15:38
Related: Confirm style for block comments https://github.com/eslint/eslint/issues/6518

**Comment by aubergine10** [comment] 2016-06-24 00:19
Separated out the PR troubleshooting sections to a new page: [Pull Request Troubleshooting](https://github.com/aubergine10/scrapbook/wiki/Pull-Request-Troubleshooting)

**Comment by aubergine10** [comment] 2016-06-24 11:02
Updated git commands on [Contributing Documentation](https://github.com/aubergine10/scrapbook/wiki/Contributing-Documentation). Still not 100% sure if they are correct, it seems everyone has their own unique workflow.

**Comment by kaicataldo** [comment] 2017-01-08 05:39
I'm closing this issues because it looks like consensus couldn't be reached. While we wish we could accommodate all requests, we have limited resources and do need to prioritize. We've found that issues failing to reach consensus after 21 days tend to never reach consensus, and as a team have decided to close such issues. This doesn't mean the idea isn't interesting or valuable, only that it's not something the team can commit to at the moment.

**Closed by kaicataldo** 2017-01-08 05:39 UTC
Labels: documentation, evaluating, feature
