### ISSUE TITLE
Change Request: Prettier in the --init options

### ISSUE THREAD

**Issue by kaihendry** [eslint/eslint#15344] opened 2021-11-23 13:17 UTC
### ESLint version

8.3.0

### What problem do you want to solve?

Is not super clear how to integrate eslint with prettier https://prettier.io/docs/en/install.html#eslint-and-other-linters

### What do you think is the correct solution?

Shouldn't there be an init option to setup ESLint with this very common formatter?

### Participation

- [ ] I am willing to submit a pull request for this change.

**Comment by nzakas** [comment] 2021-11-25 01:11
Duplicate of https://github.com/eslint/eslint/issues/15131

You’ll need to talk to the Prettier folks if you’re having trouble.

**Closed by nzakas** 2021-11-25 01:11 UTC
Labels: enhancement, triage, core
