### ISSUE TITLE
More flexible arrow-body-style

### ISSUE THREAD

**Issue by tjbenton** [eslint/eslint#9062] opened 2017-08-02 13:38 UTC
* **ESLint Version:** 4.3.0
* **Node Version:** 6.11.1
* **npm Version:** 3.10.10

parser: babel-eslint

Here's my config for this rule

```js
'arrow-body-style': [ 'error', 'as-needed', { requireReturnForObjectLiteral: true } ],
```

I would like to propose some additional options for the `arrow-body-style` rule. There's only 1 option and that doesn't feel flexible enough for me.

  - `'arrow-body-style': [ 'error', 'as-needed', { multiLine: true } ]`. This would force arrow functions that have multiple lines to be in brace style.

 This rule would target cases like this
  ```js
  const getIconSource = (iconName) => Icon.getImageSource(iconName, 20).then((source) => {
    navIcons[iconName] = source;
  });

  const getCategories = ({ people, search_term, tags }) => service(`/media/v1/app/${global.Config.app}/categories`, {
    method: 'GET',
    params: { people, search_term, tags },
  });

  // this variation should result in the same thing
  const getCategories = ({ people, search_term, tags }) =>
    service(`/media/v1/app/${global.Config.app}/categories`, {
      method: 'GET',
      params: { people, search_term, tags },
    })
  
  ```
  
  Would like it to be
  
  ```js
  const getIconSource = (iconName) => {
    return Icon.getImageSource(iconName, 20).then((source) => {
      navIcons[iconName] = source;
    })
  };

  const getCategories = ({ people, search_term, tags }) => {
    return service(`/media/v1/app/${global.Config.app}/categories`, {
      method: 'GET',
      params: { people, search_term, tags },
    })
  }
  ```
  
  - `'arrow-body-style': [ 'error', 'as-needed', { maxFunctionsPerLine: 2 } ]`. This would allow us to declare how many functions we would allow per line. If the user passes in `0` it would be the same as infinity.
  
  currently you can do this
  ```js
  const delay = (duration = 100) => new Promise((resolve) => setTimeout(() => resolve(), duration))
  ```
  
  would like it to be
  
  ```js
  // 'arrow-body-style': [ 'error', 'as-needed', { maxFunctionsPerLine: 2 } ]
  const delay = (duration = 100) => {
    return new Promise((resolve) => setTimeout(() => resolve(), duration)
  })

  // 'arrow-body-style': [ 'error', 'as-needed', { maxFunctionsPerLine: 1 } ]
  const delay = (duration = 100) => {
    return new Promise((resolve) => {
      setTimeout(() => resolve(), duration)
    })
  }
  
  // 'arrow-body-style': [ 'error', 'as-needed', { maxFunctionsPerLine: 1 } ]
  const delay = (duration = 100) => {
    return new Promise((resolve) => setTimeout(resolve, duration))
  }
  ```

**Comment by not-an-aardvark** [comment] 2017-08-06 02:03
Thanks for the proposal. Personally, I'm not sure whether this is worth adding to the core rule, since it seems like a fairly specific preference -- I'm not sure counting the number of functions on a line is a good way to measure its complexity in the general case. However, let's see what the rest of the team thinks.

In any case, if this doesn't get added to the `arrow-body-style` rule, you can always implement it as part of an ESLint plugin.

**Comment by platinumazure** [comment] 2017-08-06 04:11
Maybe we could implement a "max nested functions per line" rule which would flag excessive callback nesting on a single line? Then users would simply have to find a way to break that line up (including but not limited to using a non-concise arrow body).

In order for this to work with arrow-body-style, it would need to be enhanced to allow non-concise bodies when the body is multi-line.

**Comment by not-an-aardvark** [comment] 2017-09-16 05:21
Thanks for your interest in improving ESLint. Unfortunately, it looks like this issue didn't get consensus from the team, so I'm closing it. We define [consensus](http://eslint.org/docs/maintainer-guide/issues.html#consensus) as having three :+1:s from team members, as well as a team member willing to champion the proposal. This is a high bar by design -- we can't realistically accept and maintain every feature request in the long term, so we only accept feature requests which are useful enough that there is consensus among the team that they're worth adding.

Since ESLint is pluggable and can load custom rules at runtime, the lack of consensus among the ESLint team doesn't need to be a blocker for you using this in your project, if you'd find it useful. It just means that you would need to [implement the rule](http://eslint.org/docs/developer-guide/working-with-rules) yourself, rather than using a bundled rule that is packaged with ESLint.

**Closed by not-an-aardvark** 2017-09-16 05:21 UTC
Labels: enhancement, evaluating, rule
