### ISSUE TITLE
Rule Enhancement Proposal: space-infix-ops: for loop initialiser exception

### ISSUE THREAD

**Issue by SystemParadox** [eslint/eslint#8415] opened 2017-04-05 11:04 UTC
Is there any chance that we could add an option to space-infix-ops to customise the behaviour regarding for loop initialisers?

I know it's a bit of a special case, but for loops look so much better if the initialiser isn't spaced. This currently gives an error:

```
for (var i=0; i < 5; i++) {}
// Infix operators must be spaced
```

Thanks.

**Comment by not-an-aardvark** [comment] 2017-04-05 16:52
Thanks for the feature suggestion.

To me, this seems like a very unusual preference, so I'm not sure it would be worth adding it to the space-infix-ops rule (although you could always create a custom rule to enforce it). However, let's see what the rest of the team thinks.

**Comment by platinumazure** [comment] 2017-04-05 16:56
I'd be interested in seeing something like this implemented using AST selectors (if at all feasible). There was a similar request for assignment patterns as well. It'd be awesome to be able to say, yes require spaces, but for nodes matching user-specified AST selectors, override the setting.

That said, I don't know how feasible that would be.

**Comment by not-an-aardvark** [comment] 2017-04-05 17:00
I think it would be feasible to do that (and it seems like it would be very useful, e.g. it would allow people to configure spacing for default parameters differently, which is a common request). However, it would also probably conflict with the changes in https://github.com/eslint/eslint/pull/7591, so we should figure out how to coordinate that.

**Comment by not-an-aardvark** [comment] 2017-09-16 05:27
Thanks for your interest in improving ESLint. Unfortunately, it looks like this issue didn't get consensus from the team, so I'm closing it. We define [consensus](http://eslint.org/docs/maintainer-guide/issues.html#consensus) as having three :+1:s from team members, as well as a team member willing to champion the proposal. This is a high bar by design -- we can't realistically accept and maintain every feature request in the long term, so we only accept feature requests which are useful enough that there is consensus among the team that they're worth adding.

Since ESLint is pluggable and can load custom rules at runtime, the lack of consensus among the ESLint team doesn't need to be a blocker for you using this in your project, if you'd find it useful. It just means that you would need to [implement the rule](http://eslint.org/docs/developer-guide/working-with-rules) yourself, rather than using a bundled rule that is packaged with ESLint.

**Closed by not-an-aardvark** 2017-09-16 05:27 UTC
Labels: enhancement, evaluating, rule
