### ISSUE TITLE
docs: no-delete-var docs should mention strict mode

### ISSUE THREAD

**Issue by aparajita** [eslint/eslint#5485] opened 2016-03-06 01:32 UTC
**What version of ESLint are you using?**

2.3.0

**What configuration and parser (Espree, Babel-ESLint, etc.) are you using?**

N/A

**What did you do? Please include the actual source code causing the issue.**

Tried the example used in the no-delete-var docs.

**What did you expect to happen?**

I expected the no-delete-var error.

**What actually happened? Please include the actual, raw output from ESLint.**

`641:1  error  Parsing error: Deleting local variable in strict mode`

The no-delete-var docs should mention that this rule is only effective when in non-strict mode.

**Comment by platinumazure** [comment] 2016-03-06 02:43
It is indeed a parsing error in strict mode to attempt to delete a variable. You are correct that the rule, therefore, is only really effective (or, put another way, necessary) in non-strict mode.

I don't see much value in adding that to docs, but I don't see much harm either. Let's see what the rest of the team thinks.

**Comment by aparajita** [comment] 2016-03-06 04:24
Other rules that don't work in strict mode mention that. For example, no-dupe-args says right at the beginning:

> In strict mode you will receive a SyntaxError if a function takes multiple arguments with the same name. Outside of strict mode duplicate arguments will mask the value of the first argument.

Something along those lines would make it crystal clear what to expect with this rule.

**Comment by nzakas** [comment] 2016-04-21 19:12
Seems like an easy win to clarify what's going on here.

**Comment by pedrottimark** [comment] 2016-04-21 20:19
Agree, that caught me recently while testing example code, but I forget where 😳

I will search for which rules already say something, add a pattern to the guidelines, and make **Variables** my next batch of docs so that we can close this issue as soon as possible.

**Comment by pedrottimark** [comment] 2016-04-27 19:32
@aparajita Although it has taken a while for us to think this through, can you please give feedback about possibilities below to improve no-delete-var and no-dupe-args. These improvements will become a pattern we can apply to other rules which have similar issues. Specifically:

* Do you prefer **A1** or **A2** or some other grammar or formatting for **When Not To Use It**
* Do you think only some rules (for example, no-dupe-args) **B1** need to deal with this in the introduction (between the main heading and Rule Details) or all rules (including no-delete-var) **B2** And any critique of the grammar is welcome.

**A1**. A minimal solution is a level-2 heading following Rule Details (or Options, if a rule has them)

**When Not To Use It**

You do not need to enable this rule if ESLint parses code in strict mode, because it reports uses of the `delete` operator on variables as parsing errors.

**A2**. A stronger solution (pardon the pun :) is to use bold font formatting:

**When Not To Use It**

You do not need to enable this rule if ESLint parses code in **strict mode**, because it reports uses of the `delete` operator on variables as **parsing errors**.

**B1**. Switching to no-dupe-args, there are 2 questions (in my mind, at least) when it is relevant:

If more than one parameter has the same name in a function definition, the last occurrence "shadows" the preceding occurrences. A duplicated name might be a typing error.

JavaScript engines report duplicate parameter names as parsing errors:

* in strict mode for function declarations or expressions (therefore, this rule is unnecessary)
* always for arrow functions or class methods (this rule does not apply)

**B2**. So the biggest question in my mind is whether the introduction to no-delete-var requires an additional sentence as illustrated below?

The purpose of the `delete` operator is to remove a property from an object. Using the `delete` operator on a variable might lead to unexpected behavior. [WE WILL REWRITE second sentence to be clearer]

JavaScript engines report uses of the `delete` operator on variables as parsing errors.

**Comment by pedrottimark** [comment] 2016-04-27 21:29
Here is a first look at other occurrences of strict mode in rule docs:
* parsing errors which will follow the emerging pattern: no-octal, no-octal-literal (does not mention strict mode at all), no-with
* code throws errors when run in strict mode, therefore rule is relevant to report problems at lint time: no-caller, no-invalid-this (description needs improvement), quote-props (example code did not throw)
* strict mode affects which code the rule applies to: no-lone-blocks, no-shadow-restricted-names

**Comment by aparajita** [comment] 2016-04-27 22:41
Thanks for thinking it through. I vote far A2, but in addition to making "strict mode" bold, I would also make it a link to http://eslint.org/docs/rules/strict, so that users can have some reference as to what strict mode is and when it applies.

As for B2, I would use this for the second sentence:

> In [**strict mode**](http://eslint.org/docs/rules/strict), JavaScript engines report uses of the `delete` operator on variables as parsing errors, thus in strict mode ESLint's parser will fail before this rule has a chance to run.

**Closed** 2016-05-03 00:12 UTC
Labels: accepted, documentation, enhancement
