### ISSUE TITLE
Parsing a upper level .eslintrc.js

### ISSUE THREAD

**Issue by exos** [eslint/eslint#8777] opened 2017-06-21 22:28 UTC
* **ESLint Version:** v3.19.0
* **Node Version:** v6.10.0
* **npm Version:** 3.10.10
* **parser:** default

**Files tree**

    * ~/alpha
        * ./project
              * ./.eslintrc.js <- (File that extends google configuration)
              * ./project-server  <- (Working directory)
                    * ./.eslintrc.js <- (File that extends default configuration)

**Configuration:** (This is my `/home/exos/alpha/project/project-server/.eslintrc.js`)
```
module.exports = {
    env: {
        node: true,
    },
    plugins: [
    ],
    extends: [
        "defaults",
    ],
    parserOptions: {
        ecmaVersion: 5,
        sourceType: "module",
        ecmaFeatures: {}
    },
    rules: {
        "comma-dangle": 0,
    }
};
```

I'm using gulp-eslint, but running the cli command (in the package dependency version of eslint) I have the same error:

    > ./node_modules/gulp-eslint/node_modules/.bin/eslint lib/models/users.js
    Cannot find module 'eslint-config-google'
    Referenced from: /home/exos/alpha/project/.eslintrc.js
    Error: Cannot find module 'eslint-config-google'
    Referenced from: /home/exos/alpha/project/.eslintrc.js
        at ModuleResolver.resolve (/home/exos/alpha/project/project-server/node_modules/eslint/lib/util/module-resolver.js:74:19)
        at resolve (/home/exos/alpha/project/project-server/node_modules/eslint/lib/config/config-file.js:515:25)
        at load (/home/exos/alpha/project/project-server/node_modules/eslint/lib/config/config-file.js:532:26)
        at configExtends.reduceRight.e (/home/exos/alpha/project/project-server/node_modules/eslint/lib/config/config-file.js:424:36)
        at Array.reduceRight (native)
        at applyExtends (/home/exos/alpha/project/project-server/node_modules/eslint/lib/config/config-file.js:408:28)
        at Object.load (/home/exos/alpha/project/project-server/node_modules/eslint/lib/config/config-file.js:566:22)
        at loadConfig (/home/exos/alpha/project/project-server/node_modules/eslint/lib/config.js:63:33)
        at getLocalConfig (/home/exos/alpha/project/project-server/node_modules/eslint/lib/config.js:130:29)
        at Config.getConfig (/home/exos/alpha/project/project-server/node_modules/eslint/lib/config.js:260:26)

This supose to use the actual level `.eslintrc.js` file, but It's looking for `eslint-config-google` extended in the top level directory.

I tried to replicate this, coping a copy in the `~/alpha` (one top more):

    $ cp .eslintrc.js ~/alpha
    $ sed -i "s/default/showmeanerror/g" ~/alpha/.eslintrc.js  

But this isn't read, only one level is throwing this error.

Sorry my uggly english.

**Update: **

When I rename the file `~/alpha/project/.eslintrc.js` to be ignored, eslint read the file I did create in `~/alpha`. eslint are ignoring the file in the working directory:

    $ pwd                                                                     /home/exos/alpha/project/project-server [19:33:45]
    /home/exos/alpha/project/project-server
    $ la .eslintrc.js
    -rw-r--r-- 1 exos exos 277 jun 21 18:49 .eslintrc.js
    $ grep -A2 "extend" .eslintrc.js
        extends: [
            "defaults",
        ],
    $ ./node_modules/gulp-eslint/node_modules/.bin/eslint lib/models/users.js
    Cannot find module 'eslint-config-showmeanerrors'
    Referenced from: /home/exos/alpha/.eslintrc.js
    Error: Cannot find module 'eslint-config-showmeanerrors'
    Referenced from: /home/exos/alpha/.eslintrc.js
        at ModuleResolver.resolve (/home/exos/alpha/project/project-server/node_modules/eslint/lib/util/module-resolver.js:74:19)
        at resolve (/home/exos/alpha/project/project-server/node_modules/eslint/lib/config/config-file.js:515:25)
        at load (/home/exos/alpha/project/project-server/node_modules/eslint/lib/config/config-file.js:532:26)
        at configExtends.reduceRight.e (/home/exos/alpha/project/project-server/node_modules/eslint/lib/config/config-file.js:424:36)
        at Array.reduceRight (native)
        at applyExtends (/home/exos/alpha/project/project-server/node_modules/eslint/lib/config/config-file.js:408:28)
        at Object.load (/home/exos/alpha/project/project-server/node_modules/eslint/lib/config/config-file.js:566:22)
        at loadConfig (/home/exos/alpha/project/project-server/node_modules/eslint/lib/config.js:63:33)
        at getLocalConfig (/home/exos/alpha/project/project-server/node_modules/eslint/lib/config.js:130:29)
        at Config.getConfig (/home/exos/alpha/project/project-server/node_modules/eslint/lib/config.js:260:26)

**Comment by kaicataldo** [comment] 2017-06-21 22:39
Trying to understand what the issue is, but I'm curious why you're running this command:
`./node_modules/gulp-eslint/node_modules/.bin/eslint lib/models/users.js`.

Does the error still occur if you use the version of eslint you install in your own package.json? In other words, ``./node_modules/.bin/eslint lib/models/users.js`?

**Comment by exos** [comment] 2017-06-21 22:48
I use gulp-eslint, I have not the directly dependency of `eslint`, I run the bin from the `gulp-eslint` dependencies to pass over gulp. This don't matter, I can reproduce the same error using, for example the global binary of eslint:

    $ pwd
    /home/exos/alpha/project/project-server
    $ /usr/bin/eslint lib/models/users.js  | head -n 4
    Cannot find module 'eslint-config-showmeanerrors'
    Referenced from: /home/exos/alpha/.eslintrc.js
    Error: Cannot find module 'eslint-config-showmeanerrors'
    Referenced from: /home/exos/alpha/.eslintrc.js

**Comment by exos** [comment] 2017-06-21 23:42
Well aparentrly the file is readed, but ignored ¿?:

Adding

```js
console.log("LOADED", __dirname); 
```

In both files, I get this:

    $ eslint lib/models/users.js
    LOADED /home/exos/alpha/project/project-server
    LOADED /home/exos/alpha
    Cannot find module 'eslint-config-showmeanerrors'
    Referenced from: /home/exos/alpha/.eslintrc.js
    Error: Cannot find module 'eslint-config-showmeanerrors'
    Referenced from: /home/exos/alpha/.eslintrc.js
    ...

**Comment by not-an-aardvark** [comment] 2018-01-19 16:19
Closing because there hasn't been any discussion on this issue for awhile. Feel free to create a new issue if you're still having trouble.

**Closed by not-an-aardvark** 2018-01-19 16:19 UTC
Labels: question
