### ISSUE TITLE
operator-linebreak for symbol `=` and `&&`

### ISSUE THREAD

**Issue by cybermerlin** [eslint/eslint#13749] opened 2020-10-10 21:11 UTC
hi guys, sorry about this issue.

I catch this situation:
```
        const { name, type } = typeof subject === 'object'
            ? subject
...
```
fixed to:
```
        const { name, type } =
          typeof subject === 'object'
            ? subject
            : {
                name: subject,
                type: 'null',
              };
```

but the rule is:
```
'operator-linebreak': ["error", "before",  { "overrides": { "=": "ignore", "+=": "ignore", "-=": "ignore", "?=": "ignore", "*=": "ignore", "/=": "ignore" } }],
```

nodejs, eslint, prettier, typescript - latest.

**if u know in what file n at what line I can look for to fix - I'll be thankful n will try to fix this bug.**

------------
![image](https://user-images.githubusercontent.com/1460479/95665491-7b168380-0b59-11eb-8c7b-0952f9cc4610.png)

>>>

![image](https://user-images.githubusercontent.com/1460479/95665486-6cc86780-0b59-11eb-9e80-f92b8f1ee8e0.png)

-----------

**Tell us about your environment**

* **ESLint Version:**
* **Node Version:**
* **npm Version:**

**What parser (default, `@babel/eslint-parser`, `@typescript-eslint/parser`, etc.) are you using?**

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js

```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js

```

```bash

```

**What did you expect to happen?**

**What actually happened? Please include the actual, raw output from ESLint.**

**Are you willing to submit a pull request to fix this bug?**

**Comment by anikethsaha** [comment] 2020-10-12 05:02
Thanks for the report. 

Could you share the code which is having the linting issue? Above, the code snippet is not complete  and it is working fine (assume a variable in `alternate` for the ternary) [demo](https://eslint.org/demo#eyJ0ZXh0IjoiLyogZXNsaW50IG9wZXJhdG9yLWxpbmVicmVhazogW1wiZXJyb3JcIiwgXCJiZWZvcmVcIiwgIHsgXCJvdmVycmlkZXNcIjogeyBcIj1cIjogXCJpZ25vcmVcIiwgXCIrPVwiOiBcImlnbm9yZVwiLCBcIi09XCI6IFwiaWdub3JlXCIsIFwiPz1cIjogXCJpZ25vcmVcIiwgXCIqPVwiOiBcImlnbm9yZVwiLCBcIi89XCI6IFwiaWdub3JlXCIgfSB9XSAqL1xuXG4gY29uc3QgeyBuYW1lLCB0eXBlIH0gPSB0eXBlb2Ygc3ViamVjdCA9PT0gJ29iamVjdCdcbiAgICAgICAgICAgID8gc3ViamVjdCA6IHN1YiIsIm9wdGlvbnMiOnsicGFyc2VyT3B0aW9ucyI6eyJlY21hVmVyc2lvbiI6MTIsInNvdXJjZVR5cGUiOiJzY3JpcHQiLCJlY21hRmVhdHVyZXMiOnt9fSwicnVsZXMiOnt9LCJlbnYiOnt9fX0=)

and as per the snapshot, it is different from the code snippet, and also it is a linting issue as per the [prettier plugin](https://github.com/prettier/eslint-plugin-prettier).

It is better to fill the issue template as it would helping in triaging.

**Comment by cybermerlin** [comment] 2020-10-12 12:09
@anikethsaha 
hi
thank you. I see now... that is a problem with the Prettier (actually eslint-plugin-prettier)

**Comment by nzakas** [comment] 2020-10-14 01:06
@anikethsaha please leave the evaluating label until the issue is closed or accepted.

**Comment by anikethsaha** [comment] 2020-10-14 03:46
Ok sure.

**Comment by nzakas** [comment] 2020-10-16 00:14
Closing as it seems like this isn’t an issue for ESLint itself to address.

**Closed by nzakas** 2020-10-16 00:14 UTC
Labels: 3rd party plugin, evaluating
