### ISSUE TITLE
turn off no-console in try catch

### ISSUE THREAD

**Issue by xiaojingzhao091** [eslint/eslint#10085] opened 2018-03-14 04:45 UTC
**Browser**

* **ESLint Version: v4.13.0**
* **Node Version: v7.7.4**
* **npm Version: 5.6.0**

**What parser (default, Babel-ESLint, etc.) are you using?**
Babel-ESLint

**Please show your full configuration:**
```
"extends": [
    "airbnb-base",
    "prettier",
    "prettier/react",
    "plugin:react/recommended"
  ],
"rules":  {
  "no-console": "off",
}
```

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
try{
  fn()
} catch(e) {
  console.log(e) //eslint-disbale-line
}
```

```bash
 ./node_modules/.bin/eslint
```

**What did you expect to happen?**
I wish I could use console in try catch or in catch block, so I don't have to add ` //eslint-disbale-line` again and again
**What actually happened? Please include the actual, raw output from ESLint.**
I need to add ` //eslint-disbale-line` after every console.log in catch block

**Comment by VictorHom** [comment] 2018-03-14 13:35
@xiaojingzhao091 thanks for the issue!

One thing I can think of: wrap the console.log in a modified console function and use the modified function in try-catch. This way, you would have only one `//eslint-disable-line`
```
function mySuperConsole(err) {
  console.log(err); //eslint-disable-line
}
```

would that work?

**Comment by platinumazure** [comment] 2018-03-14 14:34
Hi @xiaojingzhao091, thanks for the issue!

I highly doubt this sort of exception would be accepted into core. It feels too specific to me.

That said, you are welcome to create a custom rule for your use case. In fact, you could probably use [eslint-rule-composer](https://github.com/not-an-aardvark/eslint-rule-composer) to create a rule based on the current `no-console` rule (you could use the `filterReports` method to filter out reports that are inside a catch clause in the same function scope). That would allow you to get what you need, hopefully.

Please stop by our [Gitter chat](https://gitter.im/eslint/eslint) if you need any help.

**Comment by xiaojingzhao091** [comment] 2018-03-20 14:49
Hi @platinumazure 
I would like to try eslint-rule-composer .
Thanks a lot

**Comment by not-an-aardvark** [comment] 2018-04-29 09:03
Thanks for your interest in improving ESLint. Unfortunately, it looks like this issue didn't get consensus from the team, so I'm closing it. We define [consensus](http://eslint.org/docs/maintainer-guide/issues.html#consensus) as having three :+1:s from team members, as well as a team member willing to champion the proposal. This is a high bar by design -- we can't realistically accept and maintain every feature request in the long term, so we only accept feature requests which are useful enough that there is consensus among the team that they're worth adding.

Since ESLint is pluggable and can load custom rules at runtime, the lack of consensus among the ESLint team doesn't need to be a blocker for you using this in your project, if you'd find it useful. It just means that you would need to [implement the rule](http://eslint.org/docs/developer-guide/working-with-rules) yourself, rather than using a bundled rule that is packaged with ESLint.

**Closed by not-an-aardvark** 2018-04-29 09:03 UTC
Labels: enhancement, evaluating, rule
