### ISSUE TITLE
eslint 6.2.0 unexpected token = and /

### ISSUE THREAD

**Issue by y0y0z** [eslint/eslint#12119] opened 2019-08-19 05:29 UTC
**My environment**
```bash
$ uname -a
Darwin foo.baz 18.7.0 Darwin Kernel Version 18.7.0: Thu Jun 20 18:42:21 PDT 2019; root:xnu-4903.270.47~4/RELEASE_X86_64 x86_64
```

* **ESLint Version:** 6.2.0
```bash
$ cat package.json | jq '.devDependencies.eslint'
"^6.2.0"
$ cat node_modules/eslint/package.json | jq '.version'
"6.2.0"
```
* **Node Version:** 12.8.1
```bash
$ node --version
v12.8.1
```
* **npm Version:** 6.10.3
```bash
$ npm --version
6.10.3
```

**Please show your full configuration:**
```bash
$ cat .eslintrc.js
```
```js
module.exports = {
  env: {
    browser: true,
    es6:     true,
    node:    true,
    jest:    true,
  },
  extends: [
    "eslint:recommended",
    "plugin:react/recommended",
    "plugin:jest/recommended",
    "plugin:jsx-a11y/recommended"
  ],
  parserOptions: {
    ecmaFeatures: {
      jsx: true
    },
    ecmaVersion: "2018",
    sourceType:  "module",
  },
  plugins: [
    "react",
    "jest",
    "jsx-a11y"
  ],
  rules: {
    indent: [
      "error",
      2
    ],
    "linebreak-style": [
      "error",
      "unix"
    ],
    quotes: [
      "error",
      "double"
    ],
    semi: [
      "error",
      "always"
    ],
    "key-spacing": [
      "error",
      {align: "value"}
    ],
    "no-console":           "off",
    "no-debugger":          "warn",
    "no-alert":             "warn",
    "object-curly-spacing": [
      "error",
      "never"
    ],
    "array-bracket-spacing": [
      "error",
      "never"
    ]
  },
  overrides: [
    {
      files: ["*.test.js"],
      rules: {
        "react/no-find-dom-node": "off"
      }
    }
  ],
  settings: {
    react: {
      version: "detect"
    }
  }
};
```

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```bash
$ cat src/components/App/App.js
```
```js
"use strict";

import React from "react";

class App extends React.Component {
  render() {
    return (
      <div id="container">
        <p>
          hello internet!
        </p>
      </div>
    );
  }
}

export default App;
```

```bash
$ cat src/index.js
```
```js
"use strict";

import React from "react";
import ReactDOM from "react-dom";
import App from "./components/App/App";

ReactDOM.render(
  <App />,
  document.getElementById("root")
);
```

```bash
$ npx eslint src/**/**.js
```

**What did you expect to happen?**
that all linting will pass.
when running eslint@6.1.0, it passes fine.
when running eslint@6.2.0 it fails as above.

**What actually happened? Please include the actual, raw output from ESLint.**
```bash
$ npx eslint src/**/**.js

/Users/foo/react/src/components/App/App.js
  8:14  error  Parsing error: Unexpected token =

/Users/foo/react/src/index.js
  8:8  error  Parsing error: Unexpected token /

✖ 2 problems (2 errors, 0 warnings)
```

**Comment by g-plane** [comment] 2019-08-19 06:13
Hi @y0y0z , it seems that there is something wrong with your configuration file.

The value of `ecmaVersion` must be a number, not a string.

**Comment by ljharb** [comment] 2019-08-19 06:16
@g-plane i think that's a red herring; i'm getting the same in https://github.com/airbnb/react-dates when i try to upgrade to eslint 6, and i have it as a number.

**Comment by y0y0z** [comment] 2019-08-19 06:20
> Hi @y0y0z , it seems that there is something wrong with your configuration file.
> 
> The value of `ecmaVersion` must be a number, not a string.

@g-plane: i get the same error when changing `"2018"` (string) with `2018` (number)

**Comment by g-plane** [comment] 2019-08-19 06:36
It seems that it works well on the demo:
[Demo 1](https://eslint.org/demo#eyJ0ZXh0IjoiXCJ1c2Ugc3RyaWN0XCI7XG5cbmltcG9ydCBSZWFjdCBmcm9tIFwicmVhY3RcIjtcblxuY2xhc3MgQXBwIGV4dGVuZHMgUmVhY3QuQ29tcG9uZW50IHtcbiAgcmVuZGVyKCkge1xuICAgIHJldHVybiAoXG4gICAgICA8ZGl2IGlkPVwiY29udGFpbmVyXCI+XG4gICAgICAgIDxwPlxuICAgICAgICAgIGhlbGxvIGludGVybmV0IVxuICAgICAgICA8L3A+XG4gICAgICA8L2Rpdj5cbiAgICApO1xuICB9XG59XG5cbmV4cG9ydCBkZWZhdWx0IEFwcDsiLCJvcHRpb25zIjp7InBhcnNlck9wdGlvbnMiOnsiZWNtYVZlcnNpb24iOjksInNvdXJjZVR5cGUiOiJtb2R1bGUiLCJlY21hRmVhdHVyZXMiOnsianN4Ijp0cnVlfX0sInJ1bGVzIjp7fSwiZW52Ijp7fX19)
[Demo 2](https://eslint.org/demo#eyJ0ZXh0IjoiXCJ1c2Ugc3RyaWN0XCI7XG5cbmltcG9ydCBSZWFjdCBmcm9tIFwicmVhY3RcIjtcbmltcG9ydCBSZWFjdERPTSBmcm9tIFwicmVhY3QtZG9tXCI7XG5pbXBvcnQgQXBwIGZyb20gXCIuL2NvbXBvbmVudHMvQXBwL0FwcFwiO1xuXG5SZWFjdERPTS5yZW5kZXIoXG4gIDxBcHAgLz4sXG4gIGRvY3VtZW50LmdldEVsZW1lbnRCeUlkKFwicm9vdFwiKVxuKTsiLCJvcHRpb25zIjp7InBhcnNlck9wdGlvbnMiOnsiZWNtYVZlcnNpb24iOjksInNvdXJjZVR5cGUiOiJtb2R1bGUiLCJlY21hRmVhdHVyZXMiOnsianN4Ijp0cnVlfX0sInJ1bGVzIjp7fSwiZW52Ijp7fX19)

**Comment by y0y0z** [comment] 2019-08-19 06:40
@g-plane: clear to me that the lint should not fail, as this is the case with the previous version (6.1.0). also, i am not sure that the link that you posted coincide with the configuration excert above.

**Comment by g-plane** [comment] 2019-08-19 06:43
The demo is running ESLint 6.2.0. It's the same version as you're using. Also, the parser options of the demo above are same with yours.

**Comment by y0y0z** [comment] 2019-08-19 06:45
@g-plane: i did not see that the online linting respect my configuration. but if you are insisting it is, then we should not argue about it :)

**Comment by ljharb** [comment] 2019-08-19 06:49
@g-plane it's possible that something in eslint's dep tree isn't deterministic, such that deduping might cause the wrong version of espree and/or acorn to be used. This was the case in eslint 5 as well; there's another closed issue about it.

**Comment by g-plane** [comment] 2019-08-19 06:55
@ljharb So can we try removing the `node_modules` directory and installing dependencies again?

**Comment by ljharb** [comment] 2019-08-19 06:57
@g-plane my issue is reproducible both locally and in CI (where node_modules is always fresh).

See https://travis-ci.org/airbnb/react-dates/jobs/572611629

**Comment by aladdin-add** [comment] 2019-08-19 09:41
possible duplicate of https://github.com/eslint/eslint/issues/11018, could you try `npm ls espree` and `npm ls acorn`?

**Comment by y0y0z** [comment] 2019-08-19 11:50
@aladdin-add:

```bash
$ npm ls espree
react-app@1.0.0 /Users/foo/react
└─┬ UNMET PEER DEPENDENCY eslint@6.2.0
  └── espree@6.1.0

npm ERR! peer dep missing: eslint@^5.0.0, required by @typescript-eslint/eslint-plugin@1.13.0
npm ERR! peer dep missing: eslint@^5.0.0, required by @typescript-eslint/parser@1.13.0

npm ls acorn
react-app@1.0.0 /Users/foo/react
├─┬ UNMET PEER DEPENDENCY eslint@6.2.0
│ └─┬ espree@6.1.0
│   └── acorn@7.0.0
├─┬ jest@24.9.0
│ └─┬ jest-cli@24.9.0
│   └─┬ jest-config@24.9.0
│     └─┬ jest-environment-jsdom@24.9.0
│       └─┬ jsdom@11.12.0
│         └── acorn@5.7.3
├─┬ react-scripts@3.1.1
│ ├─┬ jest-environment-jsdom-fourteen@0.1.0
│ │ └─┬ jsdom@14.1.0
│ │   ├── acorn@6.1.1
│ │   └─┬ acorn-globals@4.3.2
│ │     └── acorn@6.1.1  deduped
│ └─┬ webpack@4.39.1
│   └── acorn@6.3.0
└─┬ webpack@4.39.2
  └── acorn@6.3.0

npm ERR! peer dep missing: eslint@^5.0.0, required by @typescript-eslint/eslint-plugin@1.13.0
npm ERR! peer dep missing: eslint@^5.0.0, required by @typescript-eslint/parser@1.13.0
```

**Comment by platinumazure** [comment] 2019-08-19 13:05
We saw this when releasing espree over the weekend and trying to release ESLint yesterday.

This is an npm issue. Npm does not deduplicate the dependency tree correctly in some cases, and as a result, an old version of Acorn (espree dependency) is pulled into espree.

The only way we've found to for sure avoid this is to `rm -rf node_modules` and then `npm install --legacy-bundles`, which forces npm to use the old, un-flattened/-deduplicated installation mode from npm@2.

Another option that could maybe work in your case is to add acorn 7.0.0 as a dependency or devDependency in your project (updating ESLint's direct dependency on Acorn was what got us out the door yesterday).

Again, the root cause is an npm@>=3 deduplication bug.

**Comment by y0y0z** [comment] 2019-08-19 13:47
@platinumazure:
i tried both:

forcing npm to un-flatten dependencies:
```bash
$ rm -rf node_modules && npm install --legacy-bundling
```
also tried
 > add acorn 7.0.0 as a dependency

by executing
```bash
$ npm install acorn@latest --save-dev
```

both did not work for me.



[1]: https://github.com/eslint/eslint/issues/11018#issuecomment-521543349

**Comment by platinumazure** [comment] 2019-08-19 13:51
> both did not work for me.

Hmm... Then I'm not sure what's going on... We'll need to investigate further.

**Comment by g-plane** [comment] 2019-08-19 14:02
FWIW, I've tried with Yarn, and it works well.

**Comment by ljharb** [comment] 2019-08-19 14:09
The Travis log i linked included using the legacy bundles option, so that’s not it.

If espree added acorn as both a peer and a regular dep, that might fix it, however.

**Comment by platinumazure** [comment] 2019-08-19 14:17
@ljharb Why would adding a peer dep help here?

**Comment by ljharb** [comment] 2019-08-19 14:21
Oh, i assumed the issue was that it was already a peer dep. it’s a regular dep now?

**Comment by platinumazure** [comment] 2019-08-19 14:26
@ljharb espree declares acorn as a dependency, because it uses acorn to do the initial parse. (Basically, espree calls acorn, and then converts the output to ESTree.)

ESLint declares acorn as a devDependency. The reason for this is because we use acorn to create a loose parser for some tests (i.e., to handle recoverable errors as recoverable, which espree currently does not support).

Neither project declares acorn as a peer dependency. That seems correct to me, since espree does not expect an acorn instance to be passed in by consumers. But if you think that's incorrect, please let us know what you suggest we should do.

**Comment by ljharb** [comment] 2019-08-19 14:34
I guess I’m unclear then on how this bug happens. If espree declares acorn as a regular dep, and then npm gives it the wrong version, it should make `npm ls` fail, but it’s not failing.

**Comment by mysticatea** [comment] 2019-08-20 04:30
This bug is:

1. `acorn-jsx` requires `acorn`.
2. `acorn-jsx` has `acorn` in `peerDependencies` because the `acorn` must be the same entity of end-user's `acorn`.
3. `espree` has `acorn` and `acorn-jsx` in `dependencies`.
4. npm doesn't hoist `acorn` if a different version of `acorn` existed on another place of the depencency tree, but hoists `acorn-jsx`. For example,
    ```
    node_modules
    ├ acorn 6 (from another dep)
    ├ acorn-jsx (from espree)
    └ espree
      └ node_modules
        └ acorn 7
    ```
5. therefore, `acorn-jsx` and `espree` import different versions of `acorn` and get broken.

Anyway, I'm closing this issue because this is a duplicate of https://github.com/eslint/eslint/issues/11018.

**Comment by y0y0z** [comment] 2019-08-20 04:33
@mysticatea: thank you for the details explanation. could you please offer a bypass without pinning eslint to version 6.1.0?

**Comment by mysticatea** [comment] 2019-08-20 04:44
Please read https://github.com/eslint/eslint/issues/11018 :)

The solution is different per environments because the reason that npm doesn't hoist acorn is different per environments. The most reliable solution is [to use `npm@2`-style installation that was mentioned in that issue](https://github.com/eslint/eslint/issues/11018#issuecomment-521543349). (or use yarn)

npm Inc. has noticed this problem and they have a plan to fix. I hope `npm@7` to fix this bug (https://blog.npmjs.org/post/186983646370/npm-cli-roadmap-summer-2019)

**Comment by ljharb** [comment] 2019-08-20 04:46
As i said above tho, npm 2 style install doesn’t fix the issue on react-dates.

**Comment by mysticatea** [comment] 2019-08-20 04:48
Oh, sorry.

**Comment by mysticatea** [comment] 2019-08-20 04:53
I hope to see `npm ls acorn acorn-jsx` (and how those placed in `node_modules` directory).

**Comment by y0y0z** [comment] 2019-08-20 09:33
@mysticatea: i hope this would help (took it from my own project where i experience the issue)

```bash
$ npm ls acorn acorn-jsx
react-app@1.0.0 /Users/foo/react
├── acorn@7.0.0
├─┬ eslint@6.2.0
│ └─┬ espree@6.1.0
│   ├── UNMET PEER DEPENDENCY acorn@7.0.0
│   └── acorn-jsx@5.0.1
├─┬ jest@24.9.0
│ └─┬ jest-cli@24.9.0
│   └─┬ jest-config@24.9.0
│     └─┬ jest-environment-jsdom@24.9.0
│       └─┬ jsdom@11.12.0
│         ├── acorn@5.7.3
│         └─┬ acorn-globals@4.3.2
│           └── acorn@6.3.0
└─┬ webpack@4.39.2
  └── acorn@6.3.0

npm ERR! peer dep missing: acorn@^6.0.0, required by acorn-jsx@5.0.1
```

**Comment by sanchitrk** [comment] 2019-08-20 11:35
I am getting the same issue when using React app - I reverted back to eslint version 6.1

**Comment by SimenB** [comment] 2019-08-20 11:36
`espree` depends on `acorn@7` and `acorn-jsx@5` - however `acorn-jsx@5` has a peer dependency on `acorn@6`. Yarn also prints a warning, but it doesn't fail at runtime.

`warning "eslint > espree > acorn-jsx@5.0.1" has incorrect peer dependency "acorn@^6.0.0".`

https://github.com/eslint/espree/blob/c0635bac4cd891cb612fb81655012e2579f4e2b1/package.json#L21-L22
https://github.com/RReverser/acorn-jsx/blob/6697d3407221a58e23d040b4059f20eb045247a5/package.json#L21-L26

**Comment by y0y0z** [comment] 2019-08-20 15:10
@SimenB \ @aladdin-add \ @mysticatea: i've upgraded to version [6.2.1][1] and my issues are gone! :)

[1]: https://github.com/eslint/eslint/tree/v6.2.1

**Comment by y0y0z** [comment] 2019-08-20 15:11
@ljharb: can you please also upgrade to 6.2.1 and check whether it solves the issue for you?

**Comment by ljharb** [comment] 2019-08-20 15:20
Rerunning the CI job (which would install 6.2.1 via semver) did not fix it, with [npm 2 style bundling](https://travis-ci.org/airbnb/react-dates/jobs/572611629); I’ll give it another shot today with some of the workarounds removed.

**Comment by y0y0z** [comment] 2019-08-20 15:24
@ljharb: can you bump the version of your npm and check? i am using npm version 6.10.3.

**Comment by SimenB** [comment] 2019-08-20 15:27
Only code change in `6.2.1` is #12131 - doesn't seem like that should fix anything (unless you have a lockfile)? I'm currently locked to 6.1.0 anyways (#12117), so I haven't tested any upgrade

**Comment by y0y0z** [comment] 2019-08-20 15:30
@SimenB: this is what i did in order to verify whether bumping eslint to version 6.2.1 solved my issue:

```bash
$ rm -rf node_modules package-lock.json
$ npm install
$ npx eslint src/**/**.js
$ echo $?
0
```

**Comment by ljharb** [comment] 2019-08-20 15:38
@y0y0z npm is automatically bumped to latest in Travis-CI on react-dates using nvm install-latest-npm, so that has no impact.

**Comment by aladdin-add** [comment] 2019-08-20 15:53
> @SimenB \ @aladdin-add \ @mysticatea: i've upgraded to version 6.2.1 and my issues are gone! :)

@y0y0z I think it's because `acorn-jsx` just published v5.0.2 😄 
https://github.com/RReverser/acorn-jsx/releases/tag/5.0.2

**Comment by ljharb** [comment] 2019-08-20 20:13
Still broken: https://travis-ci.org/airbnb/react-dates/jobs/574535275

<details>
<summary>`npm ls acorn acorn-jsx`</details>

```sh
react-dates@20.3.0 /Users/ljharb/Dropbox/git/react-dates.git
├─┬ eslint@6.2.1
│ └─┬ espree@6.1.0
│   ├── acorn@7.0.0 
│   └── acorn-jsx@5.0.2 
├─┬ react-with-styles-interface-css-compiler@2.0.0
│ └─┬ jsdom@11.12.0
│   ├── acorn@5.7.3 
│   └─┬ acorn-globals@4.3.3
│     └── acorn@6.3.0 
└─┬ webpack@4.39.2
  └── acorn@6.3.0 
```
</details>

acorn v6.3 is at the top level of node_modules, as is acorn-jsx v5.0.2.

**Comment by y0y0z** [comment] 2019-08-21 09:11
@mysticatea: do you consider this issue as resolved?

**Comment by aladdin-add** [comment] 2019-08-21 12:12
> Rerunning the CI job (which would install 6.2.1 via semver) did not fix it, with npm 2 style bundling;

@ljharb  I guess it's working now -- acorn-jsx published a new version with peerDependency: acorn v7. can you give it a try?

**Comment by platinumazure** [comment] 2019-08-21 13:53
@aladdin-add See [this comment](https://github.com/eslint/eslint/issues/12119#issuecomment-523176305), I think Jordan was saying his CI is still not fixed.

**Comment by aladdin-add** [comment] 2019-08-21 14:35
this is why the issue happening:
![image](https://user-images.githubusercontent.com/13050025/63440304-2d751e00-c462-11e9-8aca-1272792f0bdf.png)

it should  have been working to use npm2-style installing, but at that time `acorn-jsx` has a peer dependency acorn v6 (npm 2 will install peer deps) -- it was fixed now!

**Comment by ljharb** [comment] 2019-08-21 14:47
I’ll rerun the job and try it again.

**Comment by ljharb** [comment] 2019-08-21 14:51
Still failed, same error.

**Comment by y0y0z** [comment] 2019-08-21 15:21
i am *not* experiencing the issue any more. this is my current environment and i hope it helps.

```bash
$ node -v
v12.9.0
$ npm -v
6.11.1
$ rm -rf node_modules package-lock.json
$ npm install
...
$ npx eslint src/**/**.js
...
$ echo $?
0
$ npm ls espree acorn
react-app@1.0.0 /Users/foo/react
├── acorn@7.0.0
├─┬ eslint@6.2.1
│ └─┬ espree@6.1.0
│   └── acorn@7.0.0  deduped
├─┬ jest@24.9.0
│ └─┬ jest-cli@24.9.0
│   └─┬ jest-config@24.9.0
│     └─┬ jest-environment-jsdom@24.9.0
│       └─┬ jsdom@11.12.0
│         ├── acorn@5.7.3
│         └─┬ acorn-globals@4.3.3
│           └── acorn@6.3.0
└─┬ webpack@4.39.2
  └── acorn@6.3.0
```

**Comment by ljharb** [comment] 2019-08-21 15:22
The CI job I linked to includes a git branch; you can all clone it yourself and look into whatever you like :-)

**Comment by aladdin-add** [comment] 2019-08-22 01:54
@ljharb it's working well to use npm2-style installing🎉. see https://travis-ci.org/airbnb/react-dates/builds/575135825?utm_source=github_status&utm_medium=notification

**Comment by ljharb** [comment] 2019-08-22 02:23
@aladdin-add wow, thanks. it was failing for me before, but i'll take the w.

For the record, npm bug or not, I'm still convinced that this is something eslint's dep graph can fix on its own - otherwise this same bug would be occurring in babel and react, both ecosystems that make heavy use of peer deps.

**Comment by kaicataldo** [comment] 2019-08-22 02:34
I really would like to see if we can figure out why we're seeing this issue more than other projects.

**Comment by aladdin-add** [comment] 2019-08-22 03:09
One possible option is: bundling eslint/espree(using something like [ncc](https://github.com/zeit/ncc)), it also brings a faster bootup(https://zeit.co/blog/ncc#faster-bootup)

**Comment by mysticatea** [comment] 2019-08-22 03:42
Webpack and Rollup have the same problem.

If this is not a bug of npm then this is the problem in Acorn. This problem appears when two Acorns are different entities: (1) Acorn that plugins loaded, (2) Acorn that is using the plugins. If Acorn does pass self to plugins, this problem will not appear.

**Comment by mysticatea** [comment] 2019-08-31 06:17
I have opened an issue on acorn: https://github.com/acornjs/acorn/pull/870

I'm closing this issue because of duplicate. Please track on #11018 and https://github.com/acornjs/acorn/pull/870.

**Closed** 2019-08-31 06:17 UTC
Labels: bug, evaluating
