### ISSUE TITLE
--fix with rule option

### ISSUE THREAD

**Issue by sabrehagen** [eslint/eslint#8479] opened 2017-04-19 07:21 UTC
Hi,

I'd like to make a feature request. I often want to use the `--fix` command line option to fix one rule, but currently eslint attempts to fix all rules. My current workaround is to create a `.eslintrc` file with only the rule I want to fix, then run `--fix` against the codebase with that `.eslintrc`, then restore my original `.eslintrc` file.

Could you add an optional parameter to `--fix` which is the rule name(s) to be fixed?

Thanks

**Comment by freshp86** [comment] 2017-04-20 05:37
Seems like a duplicate of https://github.com/eslint/eslint/issues/8018 and related to the discussion at https://github.com/eslint/eslint/issues/8039.

**Comment by platinumazure** [comment] 2017-06-26 15:46
Going to close this as a duplicate of #8039. Thanks!

**Closed by platinumazure** 2017-06-26 15:46 UTC
Labels: triage
