### ISSUE TITLE
Eslint with popular style guides is mildly broken

### ISSUE THREAD

**Issue by kaustavha** [eslint/eslint#5190] opened 2016-02-08 20:59 UTC
I get this error:
```
Kaustavs-MacBook-Pro:ele kaustavhaldar$ eslint lib/**
/usr/local/lib/node_modules/eslint/lib/config/config-file.js:332
            throw e;
            ^

Error: Cannot read config package: eslint-config-standard
Error: Cannot find module 'eslint-config-standard'
Referenced from: /Users/kaustavhaldar/Dev/maas2/ele/.eslintrc.js
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at loadPackage (/usr/local/lib/node_modules/eslint/lib/config/config-file.js:168:16)
    at loadConfigFile (/usr/local/lib/node_modules/eslint/lib/config/config-file.js:212:18)
    at load (/usr/local/lib/node_modules/eslint/lib/config/config-file.js:385:18)
    at /usr/local/lib/node_modules/eslint/lib/config/config-file.js:326:36
    at Array.reduceRight (native)

```

After using `eslint --init` like so:
```
Kaustavs-MacBook-Pro:ele kaustavhaldar$ eslint --init
? How would you like to configure ESLint? Use a popular style guide
? Which style guide do you want to follow? Standard
? What format do you want your config file to be in? JavaScript
Successfully created .eslintrc.js file in /Users/kaustavhaldar/Dev/maas2/ele
Installing additional dependencies
```

I'm using node v5 and tried 5.5 as well on OSX 10.10.5

`npm install eslint-config-standard` returns this:
```
Kaustavs-MacBook-Pro:playground kaustavhaldar$ sudo npm install eslint-config-standard
Password:
/Users/kaustavhaldar/Dev/maas2/playground
├── UNMET PEER DEPENDENCY eslint@1.10.3
├── eslint-config-standard@5.1.0
└── eslint-plugin-promise@1.0.8

npm WARN enoent ENOENT: no such file or directory, open '/Users/kaustavhaldar/Dev/maas2/playground/package.json'
npm WARN eslint-config-standard@5.1.0 requires a peer of eslint@^2.0.0-rc.0 but none was installed.
```

Using the answer questions about your style approach works flawlessly.
Additionally a similiar error pops up using either the airbnb or google standards. 

Trying to install eslint 2.0.0 rc 0 returns this:
```
Kaustavs-MacBook-Pro:playground kaustavhaldar$ sudo npm install eslint@^2.0.0-rc.0
esprima@2.7.2 node_modules/js-yaml/node_modules/esprima -> node_modules/esprima
- glob@6.0.4 node_modules/globby/node_modules/glob
- glob@6.0.4 node_modules/rimraf/node_modules/glob
/Users/kaustavhaldar/Dev/maas2/playground
├─┬ UNMET PEER DEPENDENCY eslint@2.0.0-rc.0
│ ├── doctrine@1.1.0
│ ├─┬ espree@3.0.1
│ │ ├── acorn@2.7.0
│ │ └── acorn-jsx@2.0.1
│ ├── glob@6.0.4
│ ├── ignore@2.2.19
│ ├── js-yaml@3.5.2
│ ├─┬ lodash.isequal@3.0.4
│ │ └── lodash._baseisequal@3.0.7
│ ├─┬ optionator@0.8.1
│ │ ├── fast-levenshtein@1.1.3
│ │ ├── levn@0.3.0
│ │ └── wordwrap@1.0.0
│ ├── progress@1.1.8
│ └── resolve@1.1.7
├── eslint-config-standard@5.1.0
└── eslint-plugin-promise@1.0.8

npm WARN enoent ENOENT: no such file or directory, open '/Users/kaustavhaldar/Dev/maas2/playground/package.json'
npm WARN eslint-config-airbnb@5.0.0 requires a peer of eslint@>=1.0.0 but none was installed.
npm WARN eslint-config-google@0.3.0 requires a peer of eslint@>=1.8.0 but none was installed.
npm WARN eslint-config-xo@0.7.1 requires a peer of eslint@>=1.7.3 but none was installed.
```

**Comment by mysticatea** [comment] 2016-02-09 03:23
Thank you for this issue.

This is duplicate of #5160.
Please see also: #5164 (PR #5191).

**Closed by mysticatea** 2016-02-09 03:23 UTC
Labels: bug, core, proposal
