### ISSUE TITLE
Scheduled release for October 27th, 2017

### ISSUE THREAD

**Issue by not-an-aardvark** [eslint/eslint#9474] opened 2017-10-18 16:21 UTC
The scheduled release on Friday, October 27th, 2017 is assigned to:

* @ilyavolodin
* @gyandeeps 

Please use this issue to document how the release went, any problems during the release, and anything the team might want to know about the release process. This issue should be closed after all patch releases have been completed (or there was no patch release needed).

Resources:

* [Release guidelines](https://eslint.org/docs/maintainer-guide/releases)

**Comment by ilyavolodin** [comment] 2017-10-27 21:22
ESLint v4.10.0 has been released.

We ran into two issues during this release. First issue was simple, since this was a first release with NPM 5 on our CI server, I had to modify release script to do `npm clear cache --force`. It's probably not necessary anymore, since npm 5 guarantees integrate of the cache.
Second issue was that somehow a lot of PRs that were released as part of v4.9.0 sneaked into v.4.10.0 release. I'm not sure how that happened. Maybe somebody merged a PR with `merge` strategy? Even though Github should allow that anymore.

@eslint/eslint-team Please remember to only merge semver-patch patches until we evaluate on Monday whether we need to do a patch release.

**Comment by ilyavolodin** [comment] 2017-10-30 20:02
There were no regressions or major problems reported since Friday's release, so this concludes the 4.10.0 release cycle. Feel free to merge semver-minor changes again!

**Closed by ilyavolodin** 2017-10-30 20:02 UTC
Labels: release
