### ISSUE TITLE
Missing support for hoisted packages

### ISSUE THREAD

**Issue by FezVrasta** [eslint/eslint#11238] opened 2019-01-04 14:56 UTC
**Tell us about your environment**

* **ESLint Version:** any version
* **Node Version:** any version
* **npm Version:** not involved, the problem happens with Yarn and other package managers that support module hoisting

**What parser (default, Babel-ESLint, etc.) are you using?**
irrelevant

**Please show your full configuration:**
irrelevant

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**
irrelevant, any eslint configuration that refers to a eslint plugin or preset that has been hoisted will fail to resolve it.
The same happens if `eslint` gets hoisted, but one of the plugins doesn't.

**What did you expect to happen?**
Eslint should use the standard node.js module resolution system to make sure it can find hoisted modules.

**What actually happened? Please include the actual, raw output from ESLint.**
Eslint doesn't seem to use the standard module resolution system and fails to resolve the location of the requested eslint plugins and presets.

**Are you willing to submit a pull request to fix this bug?**
no, discussion is needed, some of it happened years ago [here](https://github.com/eslint/eslint/issues/9746)

I think a possible solution would be to implement https://github.com/eslint/eslint/issues/6237, Babel does the same and allows to resolve the problem by having the plugins and presets referred to as `require.resolve('module-name-here')`

**Comment by not-an-aardvark** [comment] 2019-01-04 16:22
Closing as a duplicate of https://github.com/eslint/eslint/issues/10125.

This is a known issue and there is ongoing work to resolve it; you might be interested in looking at https://github.com/eslint/rfcs/pull/7 and https://github.com/eslint/rfcs/pull/5.

**Closed by not-an-aardvark** 2019-01-04 16:22 UTC
Labels: bug, triage

**Comment by FezVrasta** [comment] 2019-01-08 15:42
From what I see it's more than 4 years that the eslint contributors and maintainers are discussing about this issue.

I wonder if it would make sense to consider alternatives to eslint at this point.

Thanks for the heads up anyway
