### ISSUE TITLE
Fixing eslint rule "quote-props" cause parse error

### ISSUE THREAD

**Issue by krackerman** [eslint/eslint#12005] opened 2019-07-18 19:58 UTC
Our Environemnt: 

eslint: 6.0.1
node: 10.15.3
npm: 6.4.1

Parser: babel-eslint: 10.0.2

When we fix the "quote-props" rule we get a parsing error in the following code:
```
const CHAR_MAPPING = {
  æ: 'ae',
  œ: 'oe',
  ',': '',
  "'": '',
  '`': '',
  '½': '1/2',
  '¼': '1/4'
};
```
 on the keys:
  '½': '1/2',
  '¼': '1/4'

The file is:
https://github.com/eslint/eslint/blob/master/lib/rules/quote-props.js

**Comment by mysticatea** [comment] 2019-07-18 20:50
Thank you for your report.

But I could not reproduce it on [our online demo](https://eslint.org/demo#eyJ0ZXh0IjoiLyogZXNsaW50IHF1b3RlLXByb3BzOiBlcnJvciAqL1xuY29uc3QgQ0hBUl9NQVBQSU5HID0ge1xuICDDpjogJ2FlJyxcbiAgxZM6ICdvZScsXG4gICcsJzogJycsXG4gIFwiJ1wiOiAnJyxcbiAgJ2AnOiAnJyxcbiAgJ8K9JzogJzEvMicsXG4gICfCvCc6ICcxLzQnXG59OyIsIm9wdGlvbnMiOnsicGFyc2VyT3B0aW9ucyI6eyJlY21hVmVyc2lvbiI6OCwic291cmNlVHlwZSI6Im1vZHVsZSIsImVjbWFGZWF0dXJlcyI6e319LCJydWxlcyI6e30sImVudiI6e319fQ==). Would you provide a repro case?

**Comment by krackerman** [comment] 2019-07-18 22:48
1) `mkdir test && cd test && yarn init`

2) Add the following files:


<details>
<summary>.eslintrc</summary>

```json
{
  "parser": "babel-eslint",
  "extends": ["airbnb-base"],
  "rules": {
    "comma-dangle": ["error", "never"]
  }
}
```

</details>

<details>
<summary>package.json</summary>

```json
{
  "name": "fix-lint",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "devDependencies": {
    "babel-eslint": "10.0.2",
    "eslint": "6.0.1",
    "eslint-config-airbnb-base": "13.2.0",
    "eslint-plugin-import": "2.18.0"
  }
}

```

</details>

<details>
<summary>test.js</summary>

```js
const CHAR_MAPPING = {
  æ: 'ae',
  œ: 'oe',
  ',': '',
  "'": '',
  '`': '',
  '½': '1/2',
  '¼': '1/4'
};

```

</details>

3) `yarn install`
4) `eslint test.js`

I got these errors: 
```
  1:7  error  'CHAR_MAPPING' is assigned a value but never used  no-unused-vars
  7:3  error  Unnecessarily quoted property '½' found            quote-props
  8:3  error  Unnecessarily quoted property '¼' found            quote-props
```

The "no-unused-vars" error is okay.

Thank you very much for the help.

**Comment by mysticatea** [comment] 2019-07-18 23:34
Thank you. But I still could not reproduce it with/without babel-eslint.

```
~\dev\sandbox> eslint test.js

C:\Users\t-nagashima.AD\dev\sandbox\test.js
  1:7  error  'CHAR_MAPPING' is assigned a value but never used  no-unused-vars

✖ 1 problem (1 error, 0 warnings)
```

**Comment by mysticatea** [comment] 2019-07-18 23:41
Ah, OK. At first, I used npm. But indeed, if I used yarn then I could reproduce it.

**Comment by mysticatea** [comment] 2019-07-19 00:05
Looks like a bug in `acorn@6.2.0` that handles `½` as a valid identifier. As a workaround for right now, if you use `acorn@~6.1`, this bug will disappear.

**Comment by mysticatea** [comment] 2019-07-19 00:38
I have reported: https://github.com/acornjs/acorn/issues/846

**Comment by kaicataldo** [comment] 2019-07-20 22:58
It looks like this is fixed now.

**Comment by platinumazure** [comment] 2019-07-20 23:47
Do we need to upgrade acorn in espree, and espree in ESLint, to fully resolve this?

**Comment by mysticatea** [comment] 2019-07-21 03:10
I think so. Probably Acorn has a plan to release 7.0.0 for dynamic imports soon, I think that we can upgrade at that time.

**Comment by kaicataldo** [comment] 2019-09-29 20:13
This appears to be fixed!

**Closed by kaicataldo** 2019-09-29 20:13 UTC
Labels: accepted, bug
