### ISSUE TITLE
Prevent undocumented functions with names

### ISSUE THREAD

**Issue by andreas-marschke** [eslint/eslint#2981] opened 2015-07-13 08:10 UTC
Currently I'm working on documenting a larger codebase of JS that has several named functions exposed internally or to third parties as API. Some are and some aren't documented. Seeing/Knowing how far along the way I am and preventing code going in that isn't documented in the future would greatly improve the code quality.

This issue is for PR #2980

**Comment by mysticatea** [comment] 2015-07-13 08:18
maybe duplicate of #1842?

**Comment by andreas-marschke** [comment] 2015-07-13 08:23
@mysticatea Didn't see that issue. I mostly opened this ticket to have a reference to the aforementioned PR. But yeah for the most part this should solve both problems even in depth.

But this (as documentation and code shows) is purely for named functions.

**Comment by nzakas** [comment] 2015-07-14 01:08
Closing in favor of #1842. Please continue discussion there.

**Closed by nzakas** 2015-07-14 01:08 UTC
Labels: question
