### ISSUE TITLE
Deprecated mkdirp@0.5.4

### ISSUE THREAD

**Issue by johnschult** [eslint/eslint#13106] opened 2020-03-27 11:29 UTC
**The version of ESLint you are using.**
6.80.

**The problem you want to solve.**
The reference to `mkdirp@0.5.4` can be [here](https://github.com/eslint/eslint/blob/v6.8.0/package.json#L75).

In a new project:
```
test ❯ node -v
v13.11.0
test ❯ yarn add eslint
yarn add v1.22.4
warning package.json: No license field
warning No license field
[1/4] 🔍  Resolving packages...
warning eslint > mkdirp@0.5.4: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
warning eslint > file-entry-cache > flat-cache > write > mkdirp@0.5.4: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...

success Saved lockfile.
warning No license field
success Saved 107 new dependencies.
info Direct dependencies
└─ eslint@6.8.0
```

**Your take on the correct solution to problem.**
Make changes to use `mkdirp@1.x`

**Are you willing to submit a pull request to implement this change?**
Not sure. [I could not find](https://github.com/eslint/eslint/search?q=mkdirp&unscoped_q=mkdirp) any references to `mkdirp` in the project. The reason I could not find anything is that it appears that the 7.x alpha version is now on `master` and it looks like `mkdirp` is not being used in 7.x.

**Comment by kaicataldo** [comment] 2020-03-27 21:19
Duplicate of https://github.com/eslint/eslint/issues/13050.

**Closed by kaicataldo** 2020-03-27 21:19 UTC
Labels: core, enhancement, triage
