### ISSUE TITLE
Unable to setup developer environment

### ISSUE THREAD

**Issue by JeremyTCD** [eslint/eslint#7239] opened 2016-09-25 14:44 UTC
**Tell us about your environment**

* **ESLint Version: Latest**
* **Node Version: 6.5.0**
* **npm Version: 3.10.8**

**What did you do? Please include the actual source code causing the issue.**

I forked eslint and followed the [developer guide](http://eslint.org/docs/developer-guide/development-environment) up till step 5. I then ran `npm test`.

**What did you expect to happen?**  
Expected tests to pass successfully.

**What actually happened? Please include the actual, raw output from ESLint.**  
When I ran `npm test` i got the following error:
>Oops! Something went wrong!
ESLint couldn't find the plugin "eslint-plugin-node".  This can happen for a couple different reasons:
If ESLint is installed globally, then make sure eslint-plugin-node is also installed globally.
A globally-installed ESLint cannot find a locally-installed plugin.
If ESLint is installed locally, then it's likely that the plugin isn't installed correctly. 
Try reinstalling by running the following:
`npm i eslint-plugin-node@latest --save-dev`
If you still can't figure out the problem, please stop by https://gitter.im/eslint/eslint to chat with the team..  

eslint-plugin-node was in my node_modules folder. However it had an unfulfilled peer dependency. When I ran `npm list` i got this error:  
>npm ERR! peer dep missing: eslint@>=2.0.0, required by eslint-plugin-node@2.1.0  

`npm install eslint --save` causes this error though:  
>npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Users\Jeremy\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js" "install" "eslint" "--save"
npm ERR! node v6.5.0
npm ERR! npm v3.10.7
npm ERR! code ENOSELF
npm ERR! Refusing to install eslint as a dependency of itself
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR! https://github.com/npm/npm/issues
npm ERR! Please include the following file with any support request:
npm ERR!   C:\Users\Jeremy\Desktop\LibrariesAndTools\eslint\eslint\npm-debug.log

Any assistance would be greatly appreciated. Thank you.

**Comment by kdex** [comment] 2016-09-25 14:49
The issue is reproducible in [Travis](https://travis-ci.org/eslint/eslint/builds/162571834) for Node 5.x and above.

**Comment by not-an-aardvark** [comment] 2016-09-25 15:34
I can reproduce this. It might be caused by the release of `eslint-plugin-node@2.1.0`.

cc @mysticatea

**Comment by not-an-aardvark** [comment] 2016-09-25 16:00
As a temporary workaround, you can fix the problem by using `npm install eslint --force`.

**Comment by kaicataldo** [comment] 2016-09-25 21:51
Have confirmed this locally. Locking `eslint-plugin-node` to v2.0.0 fixes this, which makes me think it's not the `eslint` `peerDep` causing the issue (since that change was present in v2.0.0 as well).

**Comment by not-an-aardvark** [comment] 2016-09-25 21:56
@kaicataldo The issue is [this line](https://github.com/mysticatea/eslint-plugin-node/blob/8788242783a299546e3fc64a969ec4ad2ed3722b/lib/rules/exports-style.js#L12), which was just added in the latest release. It's trying to require() a file within `eslint`, and throwing because it's not there.

**Comment by platinumazure** [comment] 2016-09-25 22:07
Wonder if we should consider creating a sub-package with some of the ESLint utils? That way eslint-plugin-node could just consume that (and I know of a few plugins which have wanted to use ast-utils or which have re-implemented their own ast-utils file).

**Comment by mysticatea** [comment] 2016-09-26 01:48
I'm sorry, I will publish `eslint-plugin-node@2.1.1` to resolve this soon.

**Comment by mysticatea** [comment] 2016-09-26 02:06
I have done.
I'm restarting Travis jobs.

**Comment by mysticatea** [comment] 2016-09-26 02:35
Closing as [PRs](https://github.com/eslint/eslint/pulls) seem good now.

I'm sorry, I had not realized this problem since I have the symlink of eslint in the node_modules of my local eslint repository.

**Closed by mysticatea** 2016-09-26 02:35 UTC
Labels: accepted, bug, build
