### ISSUE TITLE
'ecmaFeatures' config file property is deprecated, but not in the docs

### ISSUE THREAD

**Issue by wolfy1339** [eslint/eslint#10683] opened 2018-07-26 20:30 UTC
**Tell us about your environment**

* **ESLint Version:** 5.2.0
* **Node Version:** 10.0.0
* **npm Version:** 6.0.0

**What parser (default, Babel-ESLint, etc.) are you using?** default

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
module.exports = {
    "env": {
        "es6": true,
        "node": true,
        "browser": true,
        "jest": true
    },
    "parserOptions": {
        "ecmaVersion": 2018,
        "sourceType": "module",
    },
    "ecmaFeatures": {
        "jsx": true
    },
    "plugins": ["react"],
    "extends": ["eslint:recommended", "google", "plugin:react/recommended"],
    "rules": {
        "require-jsdoc": [
            "warn",
            {
                "require": {
                    "FunctionDeclaration": true,
                    "MethodDefinition": true,
                    "ClassDeclaration": true,
                    "ArrowFunctionExpression": true,
                    "FunctionExpression": true
                }
            }
        ],
        "comma-dangle": [
            "error",
            "never"
        ],
        "padded-blocks": [
            "error",
            {
                "blocks": "never"
            }
        ],
        "arrow-parens": [
            "error",
            "as-needed"
        ],
        "one-var": "off",
        "camelcase": "off",
        "max-len": [
            "error",
            {
                "code": 120,
                "tabWidth": 4,
                "ignoreComments": true,
                "ignoreTrailingComments": true,
                "ignoreUrls": true
            }
        ],
        "id-match": "off", // Google sets this
        "curly": "off", // Can't configure this enough
        "block-spacing": [
            "error",
            "always"
        ],
        "brace-style": [
            "error",
            "1tbs",
            {
                "allowSingleLine": true
            }
        ],
        "object-curly-spacing": [
            "error",
            "always"
        ],
        "space-unary-ops": [
            "error",
            {
                "words": true,
                "nonwords": false
            }
        ],
        "padding-line-between-statements": [
            "error",
            { "blankLine": "always", "prev": "*", "next": "return" },
            { "blankLine": "always", "prev": ["const", "let"], "next": "*" },
            { "blankLine": "any", "prev": ["const", "let"], "next": ["const", "let"] }
        ],
        "eqeqeq": [
            "warn",
            "smart"
        ],
        "no-redeclare": [
            "error",
            {
                "builtinGlobals": true
            }
        ],
        "no-shadow": "error",
        "no-useless-return": "error",
        "no-cond-assign": "error",
        "block-scoped-var": "error",
        "no-else-return": "error",
        "no-undef-init": "error",
        "quote-props": [
            "error",
            "as-needed"
        ],
        "semi": [
            "error",
            "always"
        ]
    }
};
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

Source code not applicable here, as you just need an eslintrc file with the `ecmaFeatures' config option

```bash
eslint . --fix
```

**What did you expect to happen?** To not give me a deprecation notice

**What actually happened? Please include the actual, raw output from ESLint.**
(node:7736) [ESLINT_LEGACY_ECMAFEATURES] DeprecationWarning: The 'ecmaFeatures' config file property is deprecated, and has no effect. (found in ".eslintrc.js")

**Comment by wolfy1339** [comment] 2018-07-26 20:34
I believe that this is related to the deprecation of `experimentalObjectRestSpread`.

**Comment by not-an-aardvark** [comment] 2018-07-26 20:35
Hi, thanks for the report. To clarify the warning, using `ecmaFeatures` at the top level of a config file is deprecated (and ineffective). However, using an `ecmaFeatures` object within a `parserOptions` object is supported and [documented](https://eslint.org/docs/user-guide/configuring#specifying-parser-options). Does that address the issue? (I'm a bit unclear on what the issue is -- it would be useful if you could clarify which part of the documentation is causing confusion.)

**Comment by nzakas** [comment] 2018-09-19 15:42
It looks like the conversation is stalled here. As this is a question rather than an action item, I'm closing the issue. If you still need help, please send a message to our [mailing list](https://groups.google.com/group/eslint) or [chatroom](https://gitter.im/eslint/eslint). Thanks!

**Closed by nzakas** 2018-09-19 15:42 UTC
Labels: question
