### ISSUE TITLE
Rule suggestion: `always-as-needed` option for `quote-props`

### ISSUE THREAD

**Issue by bobthecow** [eslint/eslint#1658] opened 2015-01-15 19:34 UTC
Well, `always-as-needed` is an awkward name, so let's not do that. But it would be super rad if there were an option like `as-needed`, but in the event that a single property of an object needs it, it treats it like `always` for that object.

Because this is ugly:

```js
{
  foo: 1,
  bar: 2,
  'baz-qux': 3
}
```

… and always having to quote _everything_ is even uglier :)

**Comment by nzakas** [comment] 2015-01-15 22:03
There's already an "as-needed" option:
http://eslint.org/docs/rules/quote-props.html

**Comment by bobthecow** [comment] 2015-01-15 22:06
I know. Please re-read my comment?

**Comment by nzakas** [comment] 2015-01-15 22:16
I've re-read it several times but still don't understand what you're asking for. Can you provide more detail?

**Comment by bobthecow** [comment] 2015-01-15 23:02
Yeah. Sorry it's unclear, and sorry for the brevity, I'm on my phone. 

I'm looking for something like as-needed, but instead of "quote any property of an object that needs it", it's "quote all properties of an object if any property needs it". If that's still unclear I can write up examples when I'm back at a computer.

**Comment by nzakas** [comment] 2015-01-15 23:46
Ah, I gotcha now. Thanks for the clarification. I'm not sure about the naming, but this seems feasible.

**Comment by bobthecow** [comment] 2015-01-16 15:09
Yeah, definitely don't use that name, I don't like it either :)

**Comment by bobthecow** [comment] 2015-01-16 15:12
I feel like a slightly more nuanced pair of rules would capture the full intent of what I'm thinking, one for consistent property name quoting, and one for only quoting if you need to (or if any property name in the object needs to). That way you could error for one and warn for the other:

You MUST use consistent property name quoting in each object. You SHOULD avoid unnecessarily quoting property names.

 * WARN if you've quoted property names where it's not necessary. 
 * ERROR if you have inconsistent property name quoting in a single object.

**Comment by michaelficarra** [comment] 2015-01-16 15:38
:+1: I would use these rules in exactly that way.

**Comment by btmills** [comment] 2015-01-17 18:55
While I really like the idea of two separate rules for this, I'm not sure it's possible because rules are unaware of each other. Allow me to demonstrate:

```js
// You MUST us consistent property name quoting in each object.
// "quote-props-consistently": 2
// You SHOULD avoid unnecessarily quoting property names.
// "quote-props": [1, "as-needed"]

// Error because properties are inconsistently quoted
var obj1 = {
    foo: 42,
    "foo-bar": "forty-two"
};

var obj2 = {
    "foo": 42, // Warning because "foo" does not require quotes
    "foo-bar": "forty-two"
};
```

Ideally, `obj2` should pass validation.

To accomplish this given the current architecture of ESLint, the `quote-props` rule would need to duplicate all of the consistency-checking logic that should ideally exist just once in the hypothetical `quote-props-consistently` rule. `quote-props` would need an exception that won't report an unnecessarily-quoted property if any one of the properties does require quotes, but the exception should be enabled only when `quote-props-consistently` is itself enabled, which would require users to duplicate that setting (and keep it consistent) in their configuration. Unfortunately I think an `always-as-needed` option (by some other name) might be the best we can do, unless someone has a better solution that I'm not considering?

**Comment by nzakas** [comment] 2015-01-17 22:54
Yeah, any change needs to be to the existing rule. We don't want mutually exclusive rules.

**Comment by bobthecow** [comment] 2015-01-18 17:23
_If_ `always-as-needed` were implemented for `quote-props` (can we just pick a better name for this so we don't have to talk about it using my stupid name?) then they wouldn't be mutually exclusive:

```
// You MUST us consistent property name quoting in each object.
// "quote-props-consistently": 2
// You SHOULD avoid unnecessarily quoting property names.
// "quote-props": [1, "always-as-needed"]
//                      ^ not that name, but you get the picture :)

// Error because properties are inconsistently quoted
var obj1 = {
    foo: 42,
    "foo-bar": "forty-two"
};

// Warning because quoted properties are unnecessary
var obj2 = {
    "foo": 42,
    "bar": "forty-two"
};

// No error or warning
var obj2 = {
    "foo": 42,
    "foo-bar": "forty-two"
};
```

I can see a use for `quote-props-consistently` as a standalone rule — we don't care what you do, just be consistent about it. I can also see a use case for errors on `quote-props` == `always-as-needed` — if you want your code to be absolutely consistent, this would be the best way to do it. But with an error on one and a warning on the other, it would be both possible and, IMO, an ideal way to apply these rules.

That said, I'd be happy with just having `always-as-needed` (but not called `always-as-needed`, obvs).

**Comment by nzakas** [comment] 2015-01-18 17:47
I'm having a hard time rationalizing two different rule for this. If we add an option like `consistent` that basically says "if any property name is quoted then all must be quoted," then doesn't that solve all use cases?

**Comment by bobthecow** [comment] 2015-01-18 17:50
It doesn't solve the "must" vs "should" use case. "You MUST be consistent, you SHOULD only use quotes when necessary". There's no way to make one of those an error and one of those a warning with only one rule. I see them as complementary rules, but not necessarily the same. Just like you wouldn't include rules regarding single v double quoted property names in the `quote-props` rule, you'd defer to the string quoting rule instead.

**Comment by bobthecow** [comment] 2015-01-18 17:51
But again, that's the "nice to have". I'm content with just the (oh so poorly named) `always-as-needed` :)

**Comment by nzakas** [comment] 2015-01-18 17:59
Okay, so how about:

* `always` -> all objects must quote properties
* `consistent` -> if any property is quoted all must be
* `consistent-as-needed` -> properties without special characters must be quoted if  quotes are needed for any property in the same object
* `as-needed` -> properties without special characters must not be quoted

**Comment by bobthecow** [comment] 2015-01-18 18:01
Here's a concrete use case: I'm thinking specifically about declarative event and data binding, routing, etc in Backbone views, React components, and similar class-like structures.

This, IMO, is ugly, but it's as good as we can do with `as-needed`:

```js
var MyRouter = Backbone.Router.extend({
  routes: {
    home:    'showHome',
    about:   'showAbout',
    ':user': 'showProfile'
  }
});
```

Adding a `consistent` — I'm assuming by this you meant it as a replacement for my stupid `always-as-needed` :) — would fix that, because you'd be required to quote all the routes. But if that `:user` route weren't there, then you _wouldn't be able_ to quote all the routes, which is also ugly. Because objects are so often used for configuration hashes like this, a rule like `consistent` would force one config object to have quoted property names and force another (with possibly identical purpose) to not have quoted property names.

In order for my project to say "always quote routes, even if none of the routes in this particular config hash need quoted", I need to be able to make `consistent` an error, and `as-needed` a warning. It only works with two rules.

**Comment by bobthecow** [comment] 2015-01-18 18:08
Given the four options you outlined, I'd have to choose `consistent` as an error, and wouldn't get a warning for gratuitous name quoting. Which would be okay, and preferable to the current setup. So if you're really set against two rules, let's just go with that one ;)

**Comment by lo1tuma** [comment] 2015-01-23 22:58
Isn’t this a duplicate of #1283?

**Comment by bobthecow** [comment] 2015-01-23 23:06
In the one-rule variant, yep. Looks like it!

**Comment by tomecko** [comment] 2015-07-18 09:21
Hey, I think I'll deliver it (one-rule variant) in coming days.

**Comment by nzakas** [comment] 2015-07-18 15:26
Thanks!

**Comment by tomecko** [comment] 2015-07-18 21:45
My implementation follows nzakas's last proposal with one exception: I found `consistent-as-needed` to be a rather confusing name, in my opinion `always-if-needed` is a good name for proposed behavior (as this option is indeed about quoting ALL properties IF a certain condition is met). Curious to see what you think ;)

**Comment by nzakas** [comment] 2015-07-19 15:49
Can you send a pull request?

**Comment by ilyavolodin** [comment] 2015-07-19 15:51
@nzakas #3069

**Closed** 2015-07-27 15:31 UTC
Labels: accepted, beginner, enhancement, rule
