### ISSUE TITLE
Configuration for rule "space-after-keywords" is invalid: Value "always" is the wrong type.

### ISSUE THREAD

**Issue by moroshko** [eslint/eslint#2872] opened 2015-06-29 10:47 UTC
In versions 0.24.0 and 0.23.0, I get the error below. In version 0.22.0, this error doesn't appear.

```
/Users/mishamoroshko/react-chessboard/node_modules/eslint/lib/config-validator.js:88
        throw new Error(message.join(""));
              ^
Error: /Users/mishamoroshko/react-chessboard/.eslintrc:
	Configuration for rule "space-after-keywords" is invalid:
	Value "always" is the wrong type.

    at validateRuleOptions (/Users/mishamoroshko/react-chessboard/node_modules/eslint/lib/config-validator.js:88:15)
    at /Users/mishamoroshko/react-chessboard/node_modules/eslint/lib/config-validator.js:101:13
    at Array.forEach (native)
    at Object.validate (/Users/mishamoroshko/react-chessboard/node_modules/eslint/lib/config-validator.js:100:35)
    at loadConfig (/Users/mishamoroshko/react-chessboard/node_modules/eslint/lib/config.js:99:19)
    at getLocalConfig (/Users/mishamoroshko/react-chessboard/node_modules/eslint/lib/config.js:225:23)
    at Config.getConfig (/Users/mishamoroshko/react-chessboard/node_modules/eslint/lib/config.js:363:22)
    at processText (/Users/mishamoroshko/react-chessboard/node_modules/eslint/lib/cli-engine.js:183:27)
    at processFile (/Users/mishamoroshko/react-chessboard/node_modules/eslint/lib/cli-engine.js:226:12)
    at /Users/mishamoroshko/react-chessboard/node_modules/eslint/lib/cli-engine.js:322:26
```

---
**.eslintrc**
```
{
  "env": {
    "node": true,
    "browser": true,
    "es6": true,
    "mocha": true
  },
  "parser": "babel-eslint",
  "plugins": [
    "react"
  ],
  "ecmaFeatures": {
    "jsx": true
  },
  "rules": {
    "space-after-keywords": "always",
    "quotes": "single",
    "new-cap": [2, {
      "capIsNewExceptions": [
        "DragDropContext",
        "HTML5Backend",
        "DragSource",
        "DropTarget"
      ]
    }],

    "react/jsx-boolean-value": 1,
    "react/jsx-quotes": [1, "double"],
    "react/jsx-no-undef": 1,
    "react/jsx-uses-react": 1,
    "react/jsx-uses-vars": 1,
    "react/no-did-mount-set-state": 1,
    "react/no-did-update-set-state": 1,
    "react/no-multi-comp": 1,
    "react/no-unknown-property": 1,
    "react/prop-types": 1,
    "react/react-in-jsx-scope": 1,
    "react/self-closing-comp": 1,
    "react/sort-comp": 1,
    "react/wrap-multilines": 1
  }
}
```

**Comment by hzoo** [comment] 2015-06-29 13:13
Can reproduce - I fixed by doing `"space-after-keywords": [1, "always"],`  (the value can't be a string since you can't specify the rule ID / error level then)

**Comment by gyandeeps** [comment] 2015-06-29 14:22
your rules are not configured correctly. This is how all the rules work
```
<rule name> : [<error level>, <options>]
```

example:
`"space-after-keywords": [1, "always"]`

**Closed** 2015-06-29 17:35 UTC
Labels: question

**Comment by moroshko** [comment] 2015-06-30 00:46
@hzoo @gyandeeps Thanks, makes perfect sense. I wonder however why 0.22.0 doesn't complain on `"space-after-keywords": "always"`?

**Comment by gyandeeps** [comment] 2015-06-30 00:47
we lately added the config validator. O.22.0 din't have that.

**Comment by hzoo** [comment] 2015-06-30 00:47
Started validation of rule options after 0.23.0 https://github.com/eslint/eslint/issues/2595

**Comment by moroshko** [comment] 2015-06-30 01:20
I see. Thanks!

**Comment by GrayedFox** [comment] 2015-07-01 16:27
Documentation should perhaps also be updated? (http://eslint.org/docs/rules/space-after-keywords.html)[this] doesn't give the example of [1, "always"] - in fact, until reading @gyandeeps comment I didn't even realize every single rule was set that way! 

And I thought I read the tutorial...
