### ISSUE TITLE
Links to sign the CLA are broken

### ISSUE THREAD

**Issue by edmorley** [eslint/eslint#8516] opened 2017-04-27 13:18 UTC
I'm trying to sign the CLA, and have tried the links on each of:
http://eslint.org/docs/developer-guide/contributing/
http://eslint.org/docs/developer-guide/contributing/pull-requests
https://github.com/eslint/eslint/blob/master/CONTRIBUTING.md

...however they point to either one of:
https://contribute.jquery.org/cla
https://contribute.jquery.org/CLA/

...which both redirect to https://js.foundation/CLA - which is a 404.

Somewhere else I saw a reference to https://cla.js.foundation/ - however that fails with an HTTP 502.

Many thanks!

**Comment by edmorley** [comment] 2017-04-27 13:27
Bah wrong window focused, I submitted too soon. I've edited the OP to add the missing description.

**Comment by platinumazure** [comment] 2017-04-27 14:17
@edmorley Thank you for raising this issue! Anything on jquery.org is definitely not the right place for the CLA, so we should update those. As soon as @kborchers comes in with clarification on the current status of and canonical link to the current JS Foundation CLA service, then someone on the team can hopefully fix the documentation. Thanks!

@kborchers Can you please clarify the up/down status of JS Foundation CLA site and provide a canonical link for signing the CLA? Then we can fix our documentation.

**Comment by ilyavolodin** [comment] 2017-04-27 15:07
I sent an email to @kborchers about it just now. Let's give JSF a chance to fix it.

**Comment by kborchers** [comment] 2017-04-27 15:12
Sorry everyone. We are on it and hope to have it back up soon. I'll keep you posted.

**Comment by kborchers** [comment] 2017-04-27 16:25
Ok, CLA Assistant should be back up and running. Please let us know if you continue to experience issues.

As far as the link, the js.foundation/CLA should also be working again for viewing the CLA. For signing, the system is meant to be linked to from PRs. That said, there is an ongoing conversation about adding signing links to /CLA which you can view at https://github.com/JSFoundation/js.foundation/issues/26

**Comment by ilyavolodin** [comment] 2017-04-28 01:05
Thanks @kborchers for the update. Looks like the issue is resolved, so closing.

**Closed by ilyavolodin** 2017-04-28 01:05 UTC
Labels: accepted, documentation, website

**Comment by edmorley** [comment] 2017-04-28 14:38
Many thanks for fixing the CLA system being down.

Are you still wanting to update the URLs in the OP so they (a) don't redirect, (b) point at something that isn't to do with jquery?

**Comment by kborchers** [comment] 2017-04-28 15:23
PRs to update those to https://js.foundation/CLA would be most appreciated
