### ISSUE TITLE
one-var rule doesn't cover destructuring

### ISSUE THREAD

**Issue by greggman** [eslint/eslint#9681] opened 2017-12-04 06:35 UTC
** Environment **

* ESLint v4.12.1

Using the [ESLint online demo](https://eslint.org/demo/#eyJ0ZXh0IjoiLyplc2xpbnQgb25lLXZhcjogW1wiZXJyb3JcIiwgXCJuZXZlclwiXSovXG4vKmVzbGludC1lbnYgZXM2Ki9cblxuZnVuY3Rpb24gZm9vKCkge1xuICAgIGNvbnN0IHsgYmFyLCBiYXogfSA9IHsgYmFyOiAxMjMsIGJhejogNDU2IH07XG4gICAgd2luZG93LnVua25vd25GdW5jKGJhciwgYmF6KTtcbn1cblxuZm9vKCk7Iiwib3B0aW9ucyI6eyJwYXJzZXJPcHRpb25zIjp7ImVjbWFWZXJzaW9uIjo2LCJzb3VyY2VUeXBlIjoic2NyaXB0IiwiZWNtYUZlYXR1cmVzIjp7fX0sInJ1bGVzIjp7fSwiZW52Ijp7ImJyb3dzZXIiOnRydWV9fX0=)

**What parser (default, Babel-ESLint, etc.) are you using?**

default

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
{
    "parserOptions": {
        "ecmaVersion": 6,
        "sourceType": "script",
        "ecmaFeatures": {}
    },
    "rules": {},
    "env": {
        "browser": true
    }
}
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
/*eslint one-var: ["error", "never"]*/
/*eslint-env es6*/

function foo() {
    const { bar, baz } = { bar: 123, baz: 456 };
    window.unknownFunc(bar, baz);
}

foo();
```

[link to eslint demo](https://eslint.org/demo/#eyJ0ZXh0IjoiLyplc2xpbnQgb25lLXZhcjogW1wiZXJyb3JcIiwgXCJuZXZlclwiXSovXG4vKmVzbGludC1lbnYgZXM2Ki9cblxuZnVuY3Rpb24gZm9vKCkge1xuICAgIGNvbnN0IHsgYmFyLCBiYXogfSA9IHsgYmFyOiAxMjMsIGJhejogNDU2IH07XG4gICAgd2luZG93LnVua25vd25GdW5jKGJhciwgYmF6KTtcbn1cblxuZm9vKCk7Iiwib3B0aW9ucyI6eyJwYXJzZXJPcHRpb25zIjp7ImVjbWFWZXJzaW9uIjo2LCJzb3VyY2VUeXBlIjoic2NyaXB0IiwiZWNtYUZlYXR1cmVzIjp7fX0sInJ1bGVzIjp7fSwiZW52Ijp7ImJyb3dzZXIiOnRydWV9fX0=)

**What did you expect to happen?**

Based on [description of one-var](https://eslint.org/docs/rules/one-var) I expected eslint to complain that 2 variables were declared with one const

**What actually happened? Please include the actual, raw output from ESLint.**

Lint-free!

Not sure if this a documentation bug or an implementation bug but "one-var" "never" by name alone seems pretty clearly to require the code above to fail to pass linting.

**Comment by j-f1** [comment] 2017-12-04 11:45
I think it’s supposed to check for multiple `VariableDeclarator`s, while this is only using one `VariableDeclarator`. This should probably be an option since it would be a little excessive writing it like this:

```js
const { bar } = { bar: 123, baz: 456 };
const { baz } = { bar: 123, baz: 456 };
```

**Comment by greggman** [comment] 2017-12-13 08:03
seems like the more common example would be something like

**correct**

```
function foo(obj) [
   const { bar } = obj;
   const { baz } = obj;
}

foo({bar: 123, baz: 456});
```

**incorrect**

```
function foo(obj) [
   const { bar, baz } = obj;
}

foo({bar: 123, baz: 456});
```

it certainly seems in the spirit of one-var never

**Comment by not-an-aardvark** [comment] 2018-01-19 15:39
Thanks for your interest in improving ESLint. Unfortunately, it looks like this issue didn't get consensus from the team, so I'm closing it. We define [consensus](http://eslint.org/docs/maintainer-guide/issues.html#consensus) as having three :+1:s from team members, as well as a team member willing to champion the proposal. This is a high bar by design -- we can't realistically accept and maintain every feature request in the long term, so we only accept feature requests which are useful enough that there is consensus among the team that they're worth adding.

Since ESLint is pluggable and can load custom rules at runtime, the lack of consensus among the ESLint team doesn't need to be a blocker for you using this in your project, if you'd find it useful. It just means that you would need to [implement the rule](http://eslint.org/docs/developer-guide/working-with-rules) yourself, rather than using a bundled rule that is packaged with ESLint.

**Closed by not-an-aardvark** 2018-01-19 15:39 UTC
Labels: enhancement, evaluating, rule
