### ISSUE TITLE
Prompt for autofix rules

### ISSUE THREAD

**Issue by vjeux** [eslint/eslint#8510] opened 2017-04-26 22:34 UTC
Inside of Facebook, when you run lint, it's going to show all the lint errors like eslint does but if there are rules with autofix, it's going to pause and write

```
- call()
+ call();
Do you want to fix it? [Yn]
```

and wait for the user to chose what to do. This makes for a good way to upsell the autofixes and less scary than running --fix on everything.

I'm not sure if you are interested in implementing this but I figured I would suggest it :)

**Comment by not-an-aardvark** [comment] 2017-07-11 02:48
Sorry about the lack of a response on this.

For what it's worth, I think [`eslint-nibble`](https://github.com/ianvs/eslint-nibble) has basically the interface you described.

**Comment by not-an-aardvark** [comment] 2018-01-19 16:15
Thanks for your interest in improving ESLint. Unfortunately, it looks like this issue didn't get consensus from the team, so I'm closing it. We define [consensus](http://eslint.org/docs/maintainer-guide/issues.html#consensus) as having three :+1:s from team members, as well as a team member willing to champion the proposal. This is a high bar by design -- we can't realistically accept and maintain every feature request in the long term, so we only accept feature requests which are useful enough that there is consensus among the team that they're worth adding.

**Closed by not-an-aardvark** 2018-01-19 16:15 UTC
Labels: enhancement, evaluating, feature
