### ISSUE TITLE
padding-line-between-statements: add generic multiline option

### ISSUE THREAD

**Issue by hotforfeature** [eslint/eslint#9642] opened 2017-11-20 16:09 UTC
**What rule do you want to change?**
padding-line-between-statements

**Does this change cause the rule to produce more or fewer warnings?**
More

**How will the change be implemented? (New option, new default behavior, etc.)?**
Add a `multiline` statement type that detects all multiline statements. This will be identical to `multiline-block-like` but match on any type instead of just block-like statements.

As a side effect, this would also match unknown multiline block-like statements, such as TypeScript interface declarations.

**Please provide some example code that this change will affect:**

```js
foo(
  a,
  b
);
foo(a, b);
```

**What does the rule currently do for this code?**
Nothing

**What will the rule do after it's changed?**
Enforce newlines for the first multiline function statement.

**Comment by Aladdin-ADD** [comment] 2017-11-20 16:24
👎 to add this:
+ in `foo(a, b)`, `a` and `b` are not statements.
+ `padding-line-between-statements` aims to enforce **padding**, not linebreak. so the option would enforce code like:
```js
foo(
a,

b
);
```

**Comment by hotforfeature** [comment] 2017-11-20 16:32
That is not the use case I am proposing.

Before:
```js
foo(
  a,
  b
);
foo(a, b);
```

After:
```js
foo(
  a,
  b
);

foo(a, b);
```

The statement is the multiline `foo()` function invocation.

**Comment by Aladdin-ADD** [comment] 2017-11-20 16:53
ψ(._. )>sorry for misunderstanding! 😄

it seems a generic case. 👍 to make the change.

**Comment by platinumazure** [comment] 2017-11-20 17:57
I think I could get behind this. :+1: from me.

**Comment by not-an-aardvark** [comment] 2017-11-20 21:11
This seems similar to https://github.com/eslint/eslint/issues/9491. Would one of the proposals be better than the other?

**Comment by not-an-aardvark** [comment] 2018-01-19 15:41
Thanks for your interest in improving ESLint. Unfortunately, it looks like this issue didn't get consensus from the team, so I'm closing it. We define [consensus](http://eslint.org/docs/maintainer-guide/issues.html#consensus) as having three :+1:s from team members, as well as a team member willing to champion the proposal. This is a high bar by design -- we can't realistically accept and maintain every feature request in the long term, so we only accept feature requests which are useful enough that there is consensus among the team that they're worth adding.

Since ESLint is pluggable and can load custom rules at runtime, the lack of consensus among the ESLint team doesn't need to be a blocker for you using this in your project, if you'd find it useful. It just means that you would need to [implement the rule](http://eslint.org/docs/developer-guide/working-with-rules) yourself, rather than using a bundled rule that is packaged with ESLint.

**Closed by not-an-aardvark** 2018-01-19 15:41 UTC
Labels: enhancement, evaluating, rule
