### ISSUE TITLE
no-param-reassign fires when changing properties on parameter

### ISSUE THREAD

**Issue by isaacl** [eslint/eslint#5705] opened 2016-03-28 15:39 UTC
**What version of ESLint are you using?**
v2.4.0

**What parser (default, Babel-ESLint, etc.) are you using?**
babel-eslint

**Please show your full configuration:**
```
{
  "extends": "airbnb",
  "parser": 'babel-eslint',
  "rules": {
    "comma-dangle": 0,
    "react/no-multi-comp": [1, { "ignoreStateless": true }],
    "id-length": 0,
    "indent": [1, 4, {"SwitchCase": 1}],
    "max-len": 0,
    "no-nested-ternary": 0,
    "object-curly-spacing": 0,
    "react/jsx-indent-props": [1, 4],
    "react/prefer-stateless-function": 0,
    "new-cap": [2, {"capIsNewExceptions": [
      "App",
      "DataTable",
      "Immutable.Map",
      "Immutable.Set",
      "Immutable.List",
      "chai.Should",
      "$.Deferred"
    ]}],
    "no-else-return": 0,
    "no-unused-vars": [1, {"vars": "local", "args": "none"}],
    "space-in-parens": 1
  }
}
```

```
$ grep eslint package.json
    "babel-eslint": "^4.1.8",
    "eslint": "^2.4.0",
    "eslint-config-airbnb": "^6.2.0",
    "eslint-plugin-react": "^4.2.3",
```

**What did you do? Please include the actual source code causing the issue.**
```
const updateFoo = foo => {
    foo.bar = true;
    return 'baz';
};
```

**What did you expect to happen?**
This is not a reassignment of parameter, it is setting a side effect. Maybe eslint should track this, but it should not be firing the no-param-assign rule.

**What actually happened? Please include the actual, raw output from ESLint.**
`14:9  error  Assignment to function parameter 'foo'  no-param-reassign`

**Comment by BYK** [comment] 2016-03-28 15:49
This is not a bug since the `props` option for that rule is `true` in AirBNB style guide: https://github.com/airbnb/javascript/blob/master/packages/eslint-config-airbnb/rules/best-practices.js#L89

See http://eslint.org/docs/rules/no-param-reassign#props for more info.

**Comment by isaacl** [comment] 2016-03-28 15:52
fair enough, thanks.  Still, the rule is misnamed. This is not reassigning a prop.

**Comment by isaacl** [comment] 2016-03-28 15:52
Could the text eslint prints be changed when you set a prop to indicate it's from props: true?

**Comment by platinumazure** [comment] 2016-03-28 16:03
@BYK @isaacl Personally I think that's a worthwhile enhancement (changing the error text to be more clear). Can we reopen this as an enhancement request?

**Comment by BYK** [comment] 2016-03-28 16:10
>Can we reopen this as an enhancement request?

WFM.

> Still, the rule is misnamed. This is not reassigning a prop.

It is mutating a parameter. I can see why this is confusing but I'd argue this is a more important check than reassigning arguments :)

**Comment by isaacl** [comment] 2016-03-28 19:21
@BYK pull request #5706 ready for your review.

**Closed** 2016-04-01 01:36 UTC
Labels: enhancement, evaluating, rule
