### ISSUE TITLE
Bug: Configuration that throws an error with an immutable message will crash ESLint with useless error

### ISSUE THREAD

**Issue by 6XGate** [eslint/eslint#16246] opened 2022-08-26 14:32 UTC
### Environment

Node version: 14.19.3
npm version: 8.15.0
Local ESLint version: 8.22.0
Global ESLint version: N/A
Operating System: Manjaro

### What parser are you using?

Default (Espree)

### What did you do?

<details>
<summary>Configuration</summary>

```
class TestError extends Error {
  get message () {
    return `TestError: message`
  }
}

throw new TestError()
```
</details>

No linted code necessary

### What did you expect to happen?

ESLint to "crash out" with the TestError's message: `TestError: message`

### What actually happened?

ESLint triggered an unexpected `TypeError: Cannot set property message of Error which has only a getter`

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by nzakas** [comment] 2022-08-26 16:57
Can you create a reproduction case? 

ESLint doesn’t execute your code, and the error you’re getting is a runtime error.

**Comment by 6XGate** [comment] 2022-08-26 21:19
The config code is the reproduction case, it doesn't require any actual code to lint. The `.eslintrc.js` file is itself throwing an error on purpose.

The issue is; if the error thrown from the config file has an immutable/read-only message property, ESLint causes an new runtime error and swallow the more relevant error thrown by the config file. In this case, the TestError is completely lost and the user is shown the message and stack trace of the irrelevant runtime error.

Hope this helps.

**Comment by nzakas** [comment] 2022-08-29 17:59
Oh I see, thanks for explaining. We will take a look.

**Comment by snitin315** [comment] 2022-11-12 02:07
@6XGate This seems to be fixed in the [new configuration system](https://eslint.org/docs/latest/user-guide/configuring/configuration-files-new). I'm not sure if we would want to fix it in the current config system.

@nzakas WDYT?

### Old config
<img width="1094" alt="Screenshot 2022-11-12 at 7 31 13 AM" src="https://user-images.githubusercontent.com/46647141/201451326-ed69b530-b8e6-4038-b646-539440c97deb.png">


### New Config

<img width="900" alt="Screenshot 2022-11-12 at 7 31 18 AM" src="https://user-images.githubusercontent.com/46647141/201451309-b1d8a584-ac45-4707-ba66-5cc057c5a68c.png">

**Comment by nzakas** [comment] 2022-11-23 21:29
@snitin315 thanks for looking into this! As long as it's fixed in the new config system, then I think we are all set and don't need to worry about it for the old config system. @mdjermanovic do you agree?

**Comment by mdjermanovic** [comment] 2022-11-25 23:43
I agree as the eslintrc config system is frozen and this doesn't seem like a critical problem.

**Closed by mdjermanovic** 2022-11-25 23:43 UTC
Labels: bug, repro:yes
