### ISSUE TITLE
Getting Started instructions don't work

### ISSUE THREAD

**Issue by djmitche** [eslint/eslint#5681] opened 2016-03-25 20:20 UTC
**What version of ESLint are you using?**

latest

**What parser (default, Babel-ESLint, etc.) are you using?**

none

**Please show your full configuration:**

```
```

**What did you do? Please include the actual source code causing the issue.**

```
(v0.12.9) dustin@dustin-tc-devel ~/tmp $ npm install eslint
eslint@2.5.0 node_modules/eslint
(v0.12.9) dustin@dustin-tc-devel ~/tmp $ eslint --init
```

**What did you expect to happen?**

Creation of a configuration file

**What actually happened? Please include the actual, raw output from ESLint.**

```
module.js:338
    throw err;
          ^
Error: Cannot find module 'object-assign'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at /home/dustin/tmp/node_modules/eslint/node_modules/escope/node_modules/esrecurse/esrecurse.js:32:14
    at Object.<anonymous> (/home/dustin/tmp/node_modules/eslint/node_modules/escope/node_modules/esrecurse/esrecurse.js:134:2)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
```

This occurs with node 0.12 and node 4.  This was done in a clean directory with no other config or `node_modules` present.  Even in a fresh docker image, I see the same, and even when using `-g` (which I suspected was the problem)

```
(v0.12.9) dustin@dustin-tc-devel ~/tmp $ docker run -ti --rm node:4.2.6 bash
root@81545aaf0d38:/# npm install -g eslint
npm info it worked if it ends with ok
npm info using npm@2.14.12
npm info using node@v4.2.6
...
npm info postinstall user-home@2.0.0
npm info install eslint@2.5.0
npm info postinstall eslint@2.5.0
eslint@2.5.0 /usr/local/lib/node_modules/eslint
npm info ok 
root@81545aaf0d38:/# eslint --init
module.js:328
    throw err;
    ^

Error: Cannot find module 'object-assign'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at /usr/local/lib/node_modules/eslint/node_modules/escope/node_modules/esrecurse/esrecurse.js:32:14
    at Object.<anonymous> (/usr/local/lib/node_modules/eslint/node_modules/escope/node_modules/esrecurse/esrecurse.js:134:2)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
```

**Comment by alberto** [comment] 2016-03-25 20:25
Duplicate of #5680

**Closed by alberto** 2016-03-25 20:25 UTC
Labels: triage
