### ISSUE TITLE
`TypeError: Cannot read property 'value' of undefined` in eslint 2.11.0's generator-star-spacing.js

### ISSUE THREAD

**Issue by Kovensky** [eslint/eslint#6281] opened 2016-05-30 09:32 UTC
Updating eslint from 2.10.2 to 2.11.0 caused the following crash to happen (with no other context printed) when trying to lint:

```
Cannot read property 'value' of undefined
TypeError: Cannot read property 'value' of undefined
    at getStarToken (node_modules/eslint/lib/rules/generator-star-spacing.js:68:25)
    at EventEmitter.checkFunction (node_modules/eslint/lib/rules/generator-star-spacing.js:123:29)
    at emitOne (events.js:82:20)
    at EventEmitter.emit (events.js:169:7)
    at NodeEventGenerator.enterNode (node_modules/eslint/lib/util/node-event-generator.js:40:22)
    at CodePathAnalyzer.enterNode (node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:607:23)
    at CommentEventGenerator.enterNode (node_modules/eslint/lib/util/comment-event-generator.js:97:23)
    at Controller.traverser.traverse.enter (node_modules/eslint/lib/eslint.js:886:36)
    at Controller.__execute (node_modules/estraverse/estraverse.js:397:31)
    at Controller.traverse (node_modules/estraverse/estraverse.js:501:28)
```

Reverting eslint to 2.10.2 makes all lints pass.

The last few lines printed before the crash:

```
  eslint:cli-engine Processing .../foo.js +17ms
  eslint:cli-engine Linting .../foo.js +0ms
  eslint:config Constructing config for .../foo.js +0ms
  eslint:config Using config from cache +1ms
```

The file actually does not contain any generators, though it does include `async` functions.

Config file:
```js
module.exports = {
  root: true,
  extends: 'standard',

  parser: 'babel-eslint',

  plugins: [
    'babel'
  ],

  globals: {
    'ENV_PRODUCTION': false,
    'ENV_DEVELOPMENT': false
  },

  env: {
    browser: true,
    commonjs: true,
    es6: true
  }
}
```

**Comment by deveb** [comment] 2016-05-30 14:54
I have the same issue. It occurs after re-install all npm packages. Is there any solutions?

**Comment by platinumazure** [comment] 2016-05-30 15:33
Oops, this is a duplicate of https://github.com/eslint/eslint/issues/6274. Please look at that issue.Basically

 this is a babel-eslint problem, and using eslint-plugin-babel's version of generator-star-spacing might be what you want here.

Sorry for my confusion.

**Closed by platinumazure** 2016-05-30 15:33 UTC
Labels: triage
