### ISSUE TITLE
overrides support extends

### ISSUE THREAD

**Issue by Aladdin-ADD** [eslint/eslint#10609] opened 2018-07-15 20:24 UTC
**The version of ESLint you are using.**
5.1.0/master
**The problem you want to solve.**
I have a config:
```js
// ...
module.exports = {
  extends: base,
  overrides: [
    {
      files: ['**/*.jsx'],
      extends: [reactConfig], // seems no support "extends"
      parser: 'babel-eslint'
    }
  ],
};
```
got an error when running eslint:
![image](https://user-images.githubusercontent.com/13050025/42738011-2111bcbc-88af-11e8-8fe6-28d876078e79.png)

**Your take on the correct solution to problem.**

add support `"extends"` option in `overrides`

**Comment by ilyavolodin** [comment] 2018-07-19 15:09
There's already an issue for this somewhere. Overrides were specifically designed to not support `extends` initially, due to complexity.

**Comment by mysticatea** [comment] 2018-07-20 07:57
Closing as a duplicate of #8813.

**Closed by mysticatea** 2018-07-20 07:57 UTC
Labels: core, enhancement, evaluating
