### ISSUE TITLE
array-bracket-spacing autofix removes inline comments

### ISSUE THREAD

**Issue by AlansCodeLog** [eslint/eslint#13319] opened 2020-05-18 15:15 UTC
**Tell us about your environment**

* **ESLint Version: 7.0.0**
* **Node Version: v14.2.0**
* **npm Version: v6.14.4**

**What parser (default, Babel-ESLint, etc.) are you using?**
default

**Please show your full configuration:**
I can reproduce it with just:

<details>
<summary>Configuration</summary>

```js
module.exports = {
	rules: {
		"array-bracket-spacing": [ "warn", "never", {
			objectsInArrays: false,
			arraysInArrays: false
		} ],
	}
}
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

A comment with a space preceding or following it causes the autofix to delete the comment.
```js
let a = [ /* test */]
let b = [/* test */ ]
```

**What did you expect to happen?**
I expected just any surrounding spaces to be deleted since eslint won't complain about the following:
```js
let a = [/* test */]
let b = [/* test */]
```

**What actually happened? Please include the actual, raw output from ESLint.**
Running eslint with `--fix` or letting an IDE autofix errors deletes the comment.
```js
let a = []
let b = []
```

**Are you willing to submit a pull request to fix this bug?**
No.

**Comment by anikethsaha** [comment] 2020-05-18 16:25
Thanks for the issue. 

It seems it is a bug.

[repl](https://eslint.org/demo#eyJ0ZXh0IjoiLyplc2xpbnQgYXJyYXktYnJhY2tldC1zcGFjaW5nOiBbXCJlcnJvclwiLCBcIm5ldmVyXCJdKi9cbi8qZXNsaW50LWVudiBlczYqL1xuXG52YXIgYXJyID0gWyAnZm9vJywgJ2JhcicvKiogZ2Vra28gKi8gXTsiLCJvcHRpb25zIjp7InBhcnNlck9wdGlvbnMiOnsiZWNtYVZlcnNpb24iOjExLCJzb3VyY2VUeXBlIjoic2NyaXB0IiwiZWNtYUZlYXR1cmVzIjp7fX0sInJ1bGVzIjp7fSwiZW52Ijp7fX19)

**Comment by mdjermanovic** [comment] 2020-05-18 17:42
@AlansCodeLog thanks for the bug report!

Confirmed. I think we should check all "whitespace" rules and figure out a consistent approach on how to fix this.

**Comment by anikethsaha** [comment] 2020-05-18 18:21
With respect to this rule's issue. 

a check for comments before/after and if there is, then last/first range of the comment should be considered in fixer.

**Comment by anikethsaha** [comment] 2020-05-19 10:19
@mdjermanovic I submitted a PR to make the procedure better for discussing the fix.

**Comment by anikethsaha** [comment] 2020-06-11 19:24
- [ ] `func-call-spacing` has this issue as well  [demo](https://eslint.org/demo#eyJ0ZXh0IjoiLyplc2xpbnQgZnVuYy1jYWxsLXNwYWNpbmc6IFtcImVycm9yXCIsIFwibmV2ZXJcIl0qL1xuXG5mbiAvKmNvbW1lbnQqLygpOyIsIm9wdGlvbnMiOnsicGFyc2VyT3B0aW9ucyI6eyJlY21hVmVyc2lvbiI6MTEsInNvdXJjZVR5cGUiOiJzY3JpcHQiLCJlY21hRmVhdHVyZXMiOnt9fSwicnVsZXMiOnsiaW5kZW50IjoyfSwiZW52Ijp7fX19)

**Comment by mdjermanovic** [comment] 2020-06-13 17:23
I believe we'll find more whitespace rules that mistakenly remove comments like this one, so it might be good to define a consistent approach between similar rules.

Some ideas:

1. Just fix the auto-fixer

For example:

```js
/* eslint array-bracket-spacing: ["error", "never"] */

[ /* 1 */ /* 2 */ foo /* 3 */ /* 4 */ ]
```

could be auto-fixed to:

```js
/* eslint array-bracket-spacing: ["error", "never"] */

[/* 1 *//* 2 */foo/* 3 *//* 4 */]
```

This doesn't change what's being reported, i.e. any space (outside comments) between `[` and the first following non-comment token is still considered as a space after `[`, so these would be still errors:

```js
/* eslint array-bracket-spacing: ["error", "never"] */

[/**/ foo]; // error

[ /**/foo]; // error

[/**/ /**/foo]; // error
```

This is how rules such as `space-before-function-paren` and `template-tag-spacing` work. Though, these rules are a bit different than `array-bracket-spacing` because they also disallow newlines.

2. Treat comments as tokens

For example, these cases would be valid now:

```js
/* eslint array-bracket-spacing: ["error", "never"] */

[/**/ foo /**/]; // ok

[/**/ /**/ foo /**/ /**/]; // ok
```

but would also become new errors for `"always"`, so this change could produce more and fewer warnings.

This is how some rules pretty similar to `array-bracket-spacing` already work:

```js
/* eslint object-curly-spacing: ["error", "never"] */

var foo = {/**/ bar /**/}; // ok

/* eslint template-curly-spacing: ["error", "never"] */

`${/**/ baz /**/}`; // ok

/* eslint space-in-parens: ["error", "never"] */

(/**/ quux /**/); // ok

/* eslint block-spacing: ["error", "never"] */

{/**/ quuux; /**/} // ok

/*eslint comma-spacing: ["error", { "before": false, "after": false }]*/

(a /**/,/**/ b);
```

3. Ignore cases where there are comments immediately after `[`

```js
/* eslint array-bracket-spacing: ["error", "never"] */

[/**/ foo /**/]; // ok

[ /**/ foo /**/ ]; // ok
```

This change could produce only fewer warnings. There was an idea to also add new rule `space-around-comment` which would handle these cases (ignored by all other rules), but it isn't likley that we'll implement that rule.

**Comment by anikethsaha** [comment] 2020-06-13 18:28
Thanks for the detailed explaination. 

I did try the `1` and `2` (somewhat similar) for the `array-bracket-spacing` 

with `1` for example like this 

![image](https://user-images.githubusercontent.com/26347874/84576148-298b0180-add0-11ea-903d-7e8b7e950bd9.png)

I changed the fixer [here](https://github.com/eslint/eslint/blob/master/lib/rules/array-bracket-spacing.js#L97)  and [here](https://github.com/eslint/eslint/blob/master/lib/rules/array-bracket-spacing.js#L119) with a similar approach that you mentioned [here](https://github.com/eslint/eslint/pull/13411#discussion_r439281916)


With `2` , it is similar to the fix in https://github.com/eslint/eslint/pull/13325.

I would favor the `2` approach i.e considering the comments as tokens and not removing the whitespace between two comments because that would increase the readability as 

```js
[ /*comment 1*//*comment 2*/ ] 

[ /*comment 1*/ /*comment 2*/ ]  // more readable. 
```


Also, I was thinking of having a method in the fixer like `fixer.removeRangePreservingComments` so that it would be more general and consistent across all rules !
This would be mostly wrapper of similar [this](https://github.com/eslint/eslint/pull/13411#discussion_r439281916) (the `return` statement)

**Comment by mdjermanovic** [comment] 2020-06-15 08:01
> With `2` , it is similar to the fix in #13325.

I think it's different, `2` changes the logic on what's valid code for the rule (not just how the autofix works):

```js
/* eslint space-in-parens: ["error", "never"] */

(/**/ foo /**/); // ok
```

so if we decide to apply that to `array-bracket-spacing`, it would be:

```js
/* eslint array-bracket-spacing: ["error", "never"] */

[/**/ foo /**/]; // ok
```

In #13325 the logic is still mostly same as in the actual version:

```js
/* eslint array-bracket-spacing: ["error", "never"] */

[/**/ foo /**/]; // errors
```

**Comment by anikethsaha** [comment] 2020-06-15 08:33
ohh gotcha, this is scope to checking rather than fixing. cool

IMO, I would go with `2`

**Comment by jsejcksn** [comment] 2021-05-07 20:48
Here's a screen recording to show what happens when it's used with auto fix on save in an editor:

![screen-recording](https://user-images.githubusercontent.com/868251/117506599-7a0ccf80-af4b-11eb-8812-1532ebbbd645.gif)

**Comment by mdjermanovic** [comment] 2023-11-04 23:47
Closing as this rule has been deprecated per https://github.com/eslint/eslint/issues/17522

**Closed by mdjermanovic** 2023-11-04 23:47 UTC
Labels: bug, rule, accepted, needs design
