### ISSUE TITLE
babel-eslint necessary when not using babel

### ISSUE THREAD

**Issue by rightaway** [eslint/eslint#9349] opened 2017-09-25 07:27 UTC
I'm using the latest NodeJS without Babel and the latest eslint, but when I remove the `parser` option from my `eslintrc`, which is set to `babel-eslint` and which I started using earlier when I was using babel, I get many parsing errors in my eslint output. Shouldn't babel-eslint only be necessary when there's no use of babel? At what point will eslint be able to handle official ES2017/8 code and I won't need babel-eslint?

**Comment by not-an-aardvark** [comment] 2017-09-25 07:35
eslint can already handle ES2017 and ES2018 code without babel-eslint. You need to set `parserOptions: { ecmaVersion: 2017 }` in your config file to enable ES2017 parsing -- see our [configuration docs](https://eslint.org/docs/user-guide/configuring#specifying-parser-options).

**Comment by mysticatea** [comment] 2017-09-25 09:50
FYI:

- Since [v2.3.0](https://eslint.org/blog/2016/03/eslint-v2.3.0-released) (March 2016), ESLint supports ES2016 natively.
- Since [v3.6.0](https://eslint.org/blog/2016/09/eslint-v3.6.0-released) (September 2016), ESLint supports ES2017 natively.
- Since [v4.4.0](https://eslint.org/blog/2017/08/eslint-v4.4.0-released) (August 2017), ESLint supports a part of ES2018 (only syntax which is stage 4 at that time) natively.

If you want to use [stage 0-3 syntaxes](https://github.com/tc39/proposals#active-proposals), you need `babel-eslint`.

**Comment by rightaway** [comment] 2017-09-25 12:04
Since JS is backwards compatible wouldn't it be good to have the default always be set to the latest? Because that would work for people whose code is written is ES2017 but also earlier?

**Comment by mysticatea** [comment] 2017-09-25 12:36
Sounds fine to me. But people might overlook syntax errors in IE if the default behavior is ES2017.

A side note, ES includes a few breaking changes in rare case. For example, the following code is valid in ES2015 but is a syntax error in ES2016-2018.

```js
function foo(a = 0) {
    "use strict"
}
```

**Comment by kaicataldo** [comment] 2017-09-30 01:21
@rightaway I imagine that at some point we will want to bump the default version up. Ideally, I think we would bump to whatever the latest supported version is during each major release. The danger in this is that someone could upgrade to a new major version of ESLint and accidentally start allowing syntax and language features their execution environments don't support.

**Comment by not-an-aardvark** [comment] 2017-09-30 01:26
There were a few people opposed to changing the default the last time this was discussed in https://github.com/eslint/eslint/issues/8290.

**Comment by ljharb** [comment] 2017-09-30 01:29
Indeed, the default ecmaVersion shouldn't be set to the latest, it should be set to the safest thing - which is ES5.

**Comment by ilyavolodin** [comment] 2017-10-04 03:19
Agree with @ljharb it's unsafe to set default to the latest version. Also last year's state of js survey showed there's still more developers using ES5 then ES6 (and that's not even talking about ES7+)

**Comment by ljharb** [comment] 2017-10-04 04:24
Note also that the safety argument means that even if "more" devs are using ES6, because *nonzero* devs are using ES5, it will still remain the safest choice to default to ES5 (until it's "close enough" to zero, whatever that means)

**Comment by not-an-aardvark** [comment] 2017-10-24 08:30
Closing because this is working as intended.

**Closed by not-an-aardvark** 2017-10-24 08:30 UTC
Labels: question
