### ISSUE TITLE
Unable to resolve path to module 'moment-range'  import/no-unresolved

### ISSUE THREAD

**Issue by slim-hmidi** [eslint/eslint#10288] opened 2018-04-30 17:27 UTC
**Tell us about your environment**

* **ESLint Version:**  4.17.0
* **Node Version:** 8.11.1
* **npm Version:** 5.6.0

**What parser (default, Babel-ESLint, etc.) are you using?**

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
{
    "parserOptions": {
        "ecmaVersion": 2017
    },
    "env": {
        "node": true
    },
    "extends": "airbnb-base"
}
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
const MomentRange = require('moment-range'); 
```

```bash

```

**What did you expect to happen?**
No eslint error 

**What actually happened? Please include the actual, raw output from ESLint.**
```
Unable to resolve path to module 'moment-range'  import/no-unresolved
```
package.json: 
```
"dependencies":{
    "moment-range": "4.0.0"
}
```

package-lock.json:
```
"moment-range": {
      "version": "4.0.0",
      "resolved": "https://registry.npmjs.org/moment-range/-/moment-range-4.0.0.tgz",
      "integrity": "sha1-9g7VbMfh+wzeXQbrjadgImxTkqE=",
      "requires": {
        "es6-symbol": "3.1.1"
      }
    }
```

**Comment by platinumazure** [comment] 2018-04-30 17:56
This appears to be an issue with eslint-plugin-import, not core ESLint. Would you mind creating a [new issue](https://github.com/benmosher/eslint-plugin-import/issues) in the eslint-plugin-import repository? Thanks!

**Comment by ljharb** [comment] 2018-08-07 15:00
https://github.com/benmosher/eslint-plugin-import/issues/1155 filed, this can be closed.

**Comment by gyandeeps** [comment] 2018-08-07 15:03
duplicate of https://github.com/benmosher/eslint-plugin-import/issues/1155

**Closed by gyandeeps** 2018-08-07 15:03 UTC
Labels: question
