### ISSUE TITLE
Alignment of multiple variables in var statement

### ISSUE THREAD

**Issue by goloroden** [eslint/eslint#2068] opened 2015-03-16 14:01 UTC
At the moment, the following code is considered correct:

```javascript
var x = 2,
  y = 3;
```

It would be awesome if one could specify (maybe using a new rule?) whether normal indentation should be enforced (as with sample above) or whether the variables should be aligned below each other, such as:

```javascript
var x = 2,
    y = 3;
```

**Comment by lo1tuma** [comment] 2015-03-16 14:08
Looks like a duplicate of #1800.

**Closed** 2015-03-16 16:04 UTC
