### ISSUE TITLE
allow passing "--stdin-filename" or other filename override to eslint --fix

### ISSUE THREAD

**Issue by graingert** [eslint/eslint#9405] opened 2017-10-10 09:00 UTC
**Tell us about your environment**

* **ESLint Version:** v4.8.0
* **Node Version:** 8.6.0
* **npm Version:** npm@5

**What parser (default, Babel-ESLint, etc.) are you using?** babel-eslint

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
{
    "extends": ["airbnb", "plugin-mocha", "plugin:lodash-fp/recommended", "plugin:lodash/recommended"],
    "parser": "babel-eslint",
    "plugins": ["babel", "mocha", "mysticatea", "prefer-object-spread", "lodash-fp", "lodash"],
    "rules": {
        ...
    },
    "globals": {
        "DEV_SERVER": false,
        "GOOGLE_MAPS_API_KEY": false,
        "document": true
    },
    "settings": {
        "import/resolver": {
            "webpack": {
                "config": "webpack/eslint.js"
            }
        }
    },
    "env": {
        "browser": true
    },
    "overrides": [
        {
            "files": ["test/**", "**/*_?(b|n)test.js"],
            "env": {
                "mocha": true
            },
            "rules": {
                "func-names": 0,
                "prefer-arrow-callback": 0,
                "import/no-extraneous-dependencies": 0
            }
        }
    ]
}


```

</details>

**What did you do? Please include the actual source code causing the issue.**

When I use --fix from w0rp/ale it doesn't respect the filename.

**What did you expect to happen?**
When I use --fix from w0rp/ale it respects the filename.
**What actually happened? Please include the actual, raw output from ESLint.**

When I use --fix from w0rp/ale it doesn't respect the filename.

**Comment by not-an-aardvark** [comment] 2017-10-10 17:53
Closing as a duplicate of https://github.com/eslint/eslint/issues/9076

**Closed by not-an-aardvark** 2017-10-10 17:53 UTC
Labels: triage
