### ISSUE TITLE
Rule Request: prevent equality comparison with booleans

### ISSUE THREAD

**Issue by lukemwillis** [eslint/eslint#9743] opened 2017-12-20 18:36 UTC
# Please describe what the rule should do:

Disallow `==`, `===`, `!=`, and `!==` when one (or both) of the operands are `true` or `false`.

# What category of rule is this? (place an "X" next to just one item)

  [X] Enforces code style 
  [ ] Warns about a potential error 
  [ ] Suggests an alternate way of doing something 
  [ ] Other (please specify:)

# Provide 2-3 code examples that this rule will warn about:

    x === true
    false != x
    true === true

# Why should this rule be included in ESLint (instead of a plugin)?

This is an extremely basic style issue that has cropped up in just about every codebase I've ever worked in.

**Comment by lukemwillis** [comment] 2017-12-20 22:42
@platinumazure I'll play around with that, thanks.

One benefit to making this a dedicated rule is that it could be fixable. Not sure if that's reason enough, though.

**Comment by not-an-aardvark** [comment] 2017-12-20 22:47
I don't think it would be safe to autofix it anyway, because there are cases where a user actually cares whether a value is `false` (as opposed to e.g. `0`). ESLint isn't able to determine whether a given variable will have a boolean value at runtime, so it can't tell whether a given check is always redundant.

**Comment by lukemwillis** [comment] 2017-12-20 23:00
@not-an-aardvark That's fair. Definitely applicable when using `===` and `!==`. Should be okay to autofix when using `==` or `!=`, though.

**Comment by not-an-aardvark** [comment] 2017-12-20 23:14
I don't think it would be safe with `==` either; `if (' ' == false)` passes, but `if (!' ')` fails.

**Comment by lukemwillis** [comment] 2017-12-20 23:16
Huh, so it does. Alright, so fixing's right out then. Thanks for the feedback!

**Comment by lukemwillis** [comment] 2017-12-21 17:40
@platinumazure I set up that rule, slightly modified to account for true and false:

    "no-restricted-syntax": [
        "error",
        {
            "selector": "BinaryExpression[operator=/(==|===|!=|!==)/][left.value=/(true|false)/], BinaryExpression[operator=/(==|===|!=|!==)/][right.value=/(true|false)/]",
            "message": "Don't compare for equality against boolean literals"
        }
    ]

This catches all the issues, but also captures `x === 'true'` and `"the value is false" != x`.

I could probably write a regex that excluded strings, but that would be pretty fragile.

**Comment by platinumazure** [comment] 2017-12-21 17:59
Just add ^ and $ anchors and that should avoid strings containing. You
could also try using left.raw instead of left.value, that might avoid false
positives for "true"/"false" strings. Sorry for the mix-up.

**Comment by lukemwillis** [comment] 2017-12-21 18:08
@platinumazure nice! That worked:

    "no-restricted-syntax": [
        "error",
        {
            "selector": "BinaryExpression[operator=/(==|===|!=|!==)/][left.raw=/^(true|false)$/], BinaryExpression[operator=/(==|===|!=|!==)/][right.raw=/^(true|false)$/]",
            "message": "Don't compare for equality against boolean literals"
        }
    ]

**Comment by platinumazure** [comment] 2017-12-21 19:34
Might want to anchor the operators as well just to be safe, but that looks
good, hope it helps!

**Comment by lukemwillis** [comment] 2017-12-21 19:36
So, the only other useful functionality to add on top of the above would be more fine-grained control. 

# Examples

 - only disallow comparison with `==` and `!=` (could be done by altering the regex)
 - only disallow comparison when outside of `if` or `while` conditions

If that's not desirable and/or worth adding another rule, I think it's okay to reject this request.

Thanks for the help!

**Comment by not-an-aardvark** [comment] 2018-01-19 15:34
Thanks for your interest in improving ESLint. Unfortunately, it looks like this issue didn't get consensus from the team, so I'm closing it. We define [consensus](http://eslint.org/docs/maintainer-guide/issues.html#consensus) as having three :+1:s from team members, as well as a team member willing to champion the proposal. This is a high bar by design -- we can't realistically accept and maintain every feature request in the long term, so we only accept feature requests which are useful enough that there is consensus among the team that they're worth adding.

Since ESLint is pluggable and can load custom rules at runtime, the lack of consensus among the ESLint team doesn't need to be a blocker for you using this in your project, if you'd find it useful. It just means that you would need to [implement the rule](http://eslint.org/docs/developer-guide/working-with-rules) yourself, rather than using a bundled rule that is packaged with ESLint.

**Closed by not-an-aardvark** 2018-01-19 15:34 UTC
Labels: evaluating, feature, rule
