### ISSUE TITLE
`import something from './something.jsx!';` causes error

### ISSUE THREAD

**Issue by aaronz8** [eslint/eslint#2039] opened 2015-03-15 00:48 UTC
Whenever a file has an import with `.jsx!` suffix, eslint throws an unhandled error.

`import something from './something.jsx!';` 

    ❯❯❯ eslint src/js/components/ProjectSection.jsx                            ✭ ✱
    /usr/local/lib/node_modules/eslint/lib/rules/no-unused-vars.js:43
                if (definition.type === "VariableDeclarator") {
                              ^
    TypeError: Cannot read property 'type' of undefined
        at isExported (/usr/local/lib/node_modules/eslint/lib/rules/no-unused-vars.js:43:27)
        at EventEmitter.Program:exit (/usr/local/lib/node_modules/eslint/lib/rules/no-unused-vars.js:120:70)
        at emitOne (events.js:82:20)
        at EventEmitter.emit (events.js:166:7)
        at Controller.controller.traverse.leave (/usr/local/lib/node_modules/eslint/lib/eslint.js:743:25)
        at Controller.__execute (/usr/local/lib/node_modules/eslint/node_modules/estraverse/estraverse.js:393:31)
        at Controller.traverse (/usr/local/lib/node_modules/eslint/node_modules/estraverse/estraverse.js:481:28)
        at EventEmitter.module.exports.api.verify (/usr/local/lib/node_modules/eslint/lib/eslint.js:728:24)
        at processFile (/usr/local/lib/node_modules/eslint/lib/cli-engine.js:193:27)
        at /usr/local/lib/node_modules/eslint/lib/cli-engine.js:293:26

**Comment by ilyavolodin** [comment] 2015-03-15 23:54
Duplicate of #2042

**Closed by ilyavolodin** 2015-03-15 23:54 UTC
