### ISSUE TITLE
Add --ci or --bail flag to stop linting on error

### ISSUE THREAD

**Issue by jehy** [eslint/eslint#10366] opened 2018-05-17 10:38 UTC
**The version of ESLint you are using.**

4.19.1

**The problem you want to solve.**

In my project there are about 4.000 big JS files, and it takes reeeeally long time to check them all in CI.
But all I really want is to check if there is at least **one** problem in my files, and it could be checked much faster in positive case (when there is some error which is not in the end of files list).

**Your take on the correct solution to problem.**

1. It would be good if we could stop processing current file if there was at least one error (option --bail-file, for example).
2. Also, it would be good if we could stop ALL processing if there was at least one error (option --bail-all, for example).

I am not sure if those should be CLI options or options for CLIEngine - I think that either is fine.

**Comment by platinumazure** [comment] 2018-05-17 13:18
Hi @jehy, thanks for the issue.

This is an interesting idea. I'm neutral about it myself but would be interested to see what the rest of the team and/or community members think about it.

In case you're unfamiliar with our contribution process, I'll note that this proposal (being a core change) will need to be evaluated by our Technical Steering Committee and accepted before we will merge any PRs for the change. If you or anyone else wants to submit a PR, you're welcome to do so, but we won't merge until this issue is marked "accepted" which will only happen after the proposal is evaluated at our regular TSC meetings.

**Comment by g-plane** [comment] 2018-05-18 12:04
@jehy Does the `--bail-file` mean if a file contains more than one errors, it just reports one error and stop linting? IMHO, this may increase the complexity of linting process.

**Comment by jehy** [comment] 2018-05-21 08:38
@g-plane yeah, I mean exactly this. This is a feature for CI, not for developers - developer would see that there was some kind of error and will run full linting with IDE or cli.

**Comment by g-plane** [comment] 2018-05-21 10:05
@jehy The *linting process* means the internal process of ESLint, not for developers.

**Comment by jehy** [comment] 2018-05-21 10:12
Yup, I understand this. But I don't think that it will become more complex - we will only need to exit process on error...

**Comment by g-plane** [comment] 2018-05-21 10:18
This may change the function https://github.com/eslint/eslint/blob/fb148aad5199b0d51ea0c031fea4f42a50f99156/lib/linter.js#L758 to adding an extra parameter which indicates whether it has `--bail` flag.

**Comment by not-an-aardvark** [comment] 2018-07-22 07:17
Thanks for your interest in improving ESLint. Unfortunately, it looks like this issue didn't get consensus from the team, so I'm closing it. We define [consensus](http://eslint.org/docs/maintainer-guide/issues.html#consensus) as having three :+1:s from team members, as well as a team member willing to champion the proposal. This is a high bar by design -- we can't realistically accept and maintain every feature request in the long term, so we only accept feature requests which are useful enough that there is a strong consensus among the team that they're worth adding.

**Closed by not-an-aardvark** 2018-07-22 07:17 UTC
Labels: cli, evaluating, feature
