### ISSUE TITLE
Bug: Lint should not fail if disabling a rule that doesn't exist

### ISSUE THREAD

**Issue by JavaScriptBach** [eslint/eslint#17104] opened 2023-04-21 22:15 UTC
### Environment

Node version: 18.12.0
npm version: 8.19.2
Local ESLint version: 8.39.0
Global ESLint version: 8.39.0
Operating System: Ubuntu 20.04

### What parser are you using?

@typescript-eslint/parser

### What did you do?

I'm running this command:

```
npx eslint --no-eslintrc --parser '@typescript-eslint/parser' --plugin 'eslint-plugin-import' --rule 'import/order: error' --fix foo.ts
```

Contents of foo.ts:
```
// eslint-disable-next-line @typescript-eslint/ban-types
import { foo } from "bar";
```

### What did you expect to happen?

Command succeeds because no imports are out of order.

### What actually happened?

Command fails with:

```
1:1  error  Definition for rule '@typescript-eslint/ban-types' was not found  @typescript-eslint/ban-types
```

### Link to Minimal Reproducible Example

See above

### Participation

- [ ] I am willing to submit a pull request for this issue.

### Additional comments

Elaborating on my use case:

I have a repo with lots of ESlint plugins, rules, and configs. Linting all these files takes a prohibitively long time. I want to run a particular autofix linter (import sorting) as a pre-commit hook. So I am explicitly specifying a single rule and plugin and ignoring configs in the command above, and I need to be able to deal with disable directives referencing rules that don't exist in the pre-commit hook.

I filed this issue as a bug because there is no need for eslint to run a rule that is explicitly annotated as disabled. I also didn't set `--report-unused-disable-directives`, so I can't see why eslint should even be trying to run this rule.

I'm able to work around this by specifying more plugins to load, but it seems a waste to load plugins that aren't going to be used.

**Comment by Rec0iL99** [comment] 2023-04-25 01:04
Hi @JavaScriptBach, thanks for the issue. I think the [`--no-inline-config`](https://eslint.org/docs/latest/use/command-line-interface#--no-inline-config) CLI option should help you in this case. ESLint will ignore any inline comments when using this option.

**Comment by JavaScriptBach** [comment] 2023-04-25 04:34
I can't ignore all inline comments because some of them apply to the rule I'm running. I just want to ignore the inline comments for all the other rules.

**Comment by mdjermanovic** [comment] 2023-04-25 12:15
As discussed in https://github.com/eslint/eslint/issues/16554 and https://github.com/eslint/eslint/issues/14851, this works as designed because an unknown rule in a comment directive is usually a typo, in which case we think it's better to report an error rather than just silently ignore the directive.

I'm closing this issue because this works as intended. If anyone has an idea on how this could be improved to cover all use cases, please feel free to open a change request with a concrete proposal.

**Closed by mdjermanovic** 2023-04-25 12:15 UTC
Labels: works as intended
