### ISSUE TITLE
ESlint 4.18.1 unmet peer dependency due to table 4.0.3 updating to ajv 6

### ISSUE THREAD

**Issue by Ricket** [eslint/eslint#10023] opened 2018-02-26 20:48 UTC
**Tell us about your environment**

* **ESLint Version:** 4.18.1
* **Node Version:** 6.2.0
* **npm Version:** 3.8.9

**What parser (default, Babel-ESLint, etc.) are you using?** n/a

**Please show your full configuration:** n/a

**What did you do?**

```bash
npm install
```

**What did you expect to happen?** Success

**What actually happened? Please include the actual, raw output from ESLint.**

```
└─┬ eslint@4.18.1
  ├─┬ ajv@5.5.2
  │ ├── fast-deep-equal@1.1.0
  │ ├── fast-json-stable-stringify@2.0.0
  │ └── json-schema-traverse@0.3.1

...

npm WARN ajv-keywords@3.1.0 requires a peer of ajv@^6.0.0 but none was installed.

...

  └─┬ table@4.0.3
    ├── UNMET PEER DEPENDENCY ajv@6.2.0
    ├── ajv-keywords@3.1.0
```

Looks like table 4.0.3 updated their ajv dependency to 6.x, but eslint is still on ajv 5.5.2.

**Comment by not-an-aardvark** [comment] 2018-02-26 21:01
Closing as a duplicate of https://github.com/eslint/eslint/pull/10022

**Closed by not-an-aardvark** 2018-02-26 21:01 UTC
Labels: triage
