### ISSUE TITLE
New Rule Option Proposal for space-infix-ops

### ISSUE THREAD

**Issue by machineghost** [eslint/eslint#5553] opened 2016-03-12 01:31 UTC
**When does this rule option warn? Please describe and show example code:**
Currently if you set space-infix-ops=1 code like the following is flagged:

    var a=1; // should be a = 1

That's great, as most programmers would agree adding spaces helps readability.

However, with the introduction of ES6, there is now a new use case for the `=` operator, and that is for defining default parameters:

    var foo = function(options = {}) {
        this.bar = options.bar; 
    }

Adding spaces to that doesn't look as great, because in this case the `=` is acting less like an operator and more like the `:` character:

    var foo = function(options={}) { // looks better (arguably)
        this.bar = options.bar; 
    }

Therefore, I would propose adding a new option (just like the existing `int32Hint` option), named something to the effect of `ignore-default-parameters`.  When set to `false` it would apply the `space-infix-ops` rule normally, except for `=` characters used to define a default parameter.

**Is this rule option preventing an error or is it stylistic?**
Stylistic

**Why is this rule option a candidate for inclusion instead of creating a custom rule?**
ES6 is being adopted by more and more developers, and I doubt I'm the only one who would like to have a space-less `=` when defining default parameters.  This is especially true because other programming languages already have this functionality (eg. Python), and the standard formatting in those languages is often space-less (http://stackoverflow.com/questions/8853063/pep-8-why-no-spaces-around-in-keyword-argument-or-a-default-parameter-value).  Therefore, I believe it belongs as part of the core rule set.

**Are you willing to create the rule yourself?**
This seems like something that would be very easy to someone familiar with the codebase to implement, but would require a great deal of learning for someone not familiar with it (ie. me).

But that being said, I would be willing to implement it if necessary.

**Comment by michaelficarra** [comment] 2016-03-12 03:30
Since that's not an operator, space-infix-ops shouldn't even be handling it in the first place.

**Comment by BYK** [comment] 2016-03-12 11:08
Related to https://github.com/eslint/eslint/issues/3380#issuecomment-184567365.

I guess we decided to create a new rule, `space-ops`. Does that cover your use case (with the option of course)?

Also @michaelficarra would you be happy with this solution since the name won't have "infix" in it? :)

**Comment by michaelficarra** [comment] 2016-03-12 18:08
It's not the infix part, it's the operator part of the name that I don't like. It could be argued, but I don't see the `=` in parameter defaults as an operator. But I guess that doesn't mean the same rule can't handle it if there will be significant overlap in implementation. :confused:

**Comment by machineghost** [comment] 2016-03-12 18:15
@BYK Breaking things out in to a separate rule works for me.

**Comment by aaugustin** [comment] 2016-07-27 11:09
I believe this is a duplicate of #3587.

**Comment by alberto** [comment] 2016-08-01 23:39
Closing as duplicate.

**Closed by alberto** 2016-08-01 23:39 UTC
Labels: enhancement, evaluating, rule
