### ISSUE TITLE
Prevent direct mutation on user supplied object

### ISSUE THREAD

**Issue by sindresorhus** [eslint/eslint#2770] opened 2015-06-15 19:22 UTC
I don't have a concrete solution for this, but I'm going to elaborate on the problem.

## Problem

I make a node module. The main export takes an input and some options as an object:

```js
module.exports = function (input, options) {
  return options.foo == 'unicorn' ? input.split('/') : input;
};
```

The module does something with the input based on these options.

The problem is when the module matures and gets more functionality:

```js
module.exports = function (input, options) {
  options.foo = options.bar === true ? 'unicorn' : 'cake';
  return options.foo ? input.split('/') : input;
};
```

As you might notice, we're now suddenly modifying the user supplied object. The change looks harmless, but what if the user uses the same object for multiple invocations.

It's an easy mistake to make, but can result in some really hard to track down bugs.

I've seen this mistake made in countless of modules and code. Even just [today](https://github.com/kevva/screenshot-stream/commit/97e6a6dc4af1a5a5a7c2f495dd0866f06fc08e5a).

## Correct way

The correct solution here is using some kind of extend method like [`Object.assign()`](https://github.com/sindresorhus/object-assign):

```js
var objectAssign = require('object-assign');

module.exports = function (input, options) {
  options = objectAssign({}, options);
  options.foo = options.bar === true ? 'unicorn' : 'cake';
  return options.foo ? input.split('/') : input;
};
```

## Discuss

I was hoping we could discuss what ESLint can do to help with this.

**Comment by gyandeeps** [comment] 2015-06-15 19:24
@sindresorhus is `object.assign` doing a shallow copy or deep?

**Comment by xjamundx** [comment] 2015-06-15 19:24
I recently submitted a talk proposal to partially talk about how to statically analyze for immutable/pure functions. Haven't thought through it carefully though :)

`Object.assign` is shallow.

**Comment by gyandeeps** [comment] 2015-06-15 19:29
We recently solved an issue where we were using `object-assign`. then we had to move away from it and use a deep copy mechanism.
https://github.com/eslint/eslint/issues/2592

**Comment by xjamundx** [comment] 2015-06-15 19:33
haha should this be tagged "question" or "needs-bikeshedding"? I assume it's really more of a discussion than a specific ask.

**Comment by lo1tuma** [comment] 2015-06-15 20:42
Duplicate of #1600.

**Comment by gyandeeps** [comment] 2015-06-17 22:35
Here is an library which is highly adopted by different modules and it does a deep copy.
https://www.npmjs.com/package/deepmerge

**Comment by nzakas** [comment] 2015-06-18 01:39
Merging into #1600

**Closed by nzakas** 2015-06-18 01:39 UTC
Labels: duplicate
