### ISSUE TITLE
Bug: Parse error when using FlatCompat in new flat config

### ISSUE THREAD

**Issue by thepassle** [eslint/eslint#17953] opened 2024-01-04 15:49 UTC
### Environment

Node version: 18.19.0
npm version: 9.5.1
Local ESLint version: 8.56.0
Global ESLint version: n/a
Operating System: macos

### What parser are you using?

Default (Espree)

### What did you do?

<details>
<summary>Configuration</summary>

```
import * as url from 'url';
import { FlatCompat } from "@eslint/eslintrc";
const __dirname = url.fileURLToPath(new URL('.', import.meta.url));
const flatCompat = new FlatCompat({
  baseDirectory: __dirname,
});

import airbnb from 'eslint-config-airbnb-base';

export default [
  ...flatCompat.config(airbnb),
];
```
</details>

```js
import foo from './foo.js';

console.log(foo);
```

### What did you expect to happen?

`eslint-config-airbnb-base` internally uses `eslint-plugin-import`. When using the `FlatCompat` utility to use `eslint-config-airbnb-base` in my new flat config format, I'm getting the following error, which I'm not getting with the old eslint configuration format:

```
  1:17  error    Parse errors in imported module './foo.js': parserPath or languageOptions.parser is required! (undefined:undefined)  import/no-named-as-default
```

I found this confusing, because it does work in the old config format. But it seems like with the new config format, each config object that you export in the array thats exported in `eslint.config.js`, requires their own `parserPath` or `languageOptions.parser`, is that assumption correct? Previously we configured the parser in one place, and when extending that, it applied to everything else. (as far as my understanding goes)

I tried to look into the code a little bit to see whats happening, and it seems like the `FlatCompat` utility creates the following object for `eslint-plugin-import` specifically:
```
{
    settings: {
      'import/resolver': [Object],
      'import/extensions': [Array],
      'import/core-modules': [],
      'import/ignore': [Array]
    },
    rules: {
      'import/no-unresolved': [Array],
      'import/named': 'error',
      'import/default': 'off',
      'import/namespace': 'off',
      'import/export': 'error',
      'import/no-named-as-default': 'error',
      'import/no-named-as-default-member': 'error',
      'import/no-deprecated': 'off',
      'import/no-extraneous-dependencies': [Array],
      'import/no-mutable-exports': 'error',
      'import/no-commonjs': 'off',
      'import/no-amd': 'error',
      'import/no-nodejs-modules': 'off',
      'import/first': 'error',
      'import/imports-first': 'off',
      'import/no-duplicates': 'error',
      'import/no-namespace': 'off',
      'import/extensions': [Array],
      'import/order': [Array],
      'import/newline-after-import': 'error',
      'import/prefer-default-export': 'error',
      'import/no-restricted-paths': 'off',
      'import/max-dependencies': [Array],
      'import/no-absolute-path': 'error',
      'import/no-dynamic-require': 'error',
      'import/no-internal-modules': [Array],
      'import/unambiguous': 'off',
      'import/no-webpack-loader-syntax': 'error',
      'import/no-unassigned-import': 'off',
      'import/no-named-default': 'error',
      'import/no-anonymous-default-export': [Array],
      'import/exports-last': 'off',
      'import/group-exports': 'off',
      'import/no-default-export': 'off',
      'import/no-named-export': 'off',
      'import/no-self-import': 'error',
      'import/no-cycle': [Array],
      'import/no-useless-path-segments': [Array],
      'import/dynamic-import-chunkname': [Array],
      'import/no-relative-parent-imports': 'off',
      'import/no-unused-modules': [Array],
      'import/no-import-module-exports': [Array],
      'import/no-relative-packages': 'error'
    },
    languageOptions: { ecmaVersion: 6, sourceType: 'module' },
    plugins: { import: [Object] }
  },
```

Note that there's no `parserPath` or `languageOptions.parser` present. There _is_ a `languageOptions.parser` present in other objects of the config, however, but as mentioned above, it seems like that's not getting applied to other objects in the exported flat config array.

When I looked into the code, I saw that the error is thrown in `eslint-module-utils`:
<img width="1398" alt="image" src="https://github.com/eslint/eslint/assets/17054057/52fa9416-8e02-48ed-8b25-95ad77b084b4">

And in the `getParserPath` I see the following:
<img width="684" alt="image" src="https://github.com/eslint/eslint/assets/17054057/7748e27e-666e-41b1-bff1-24c5e9f66cfa">

Judging on the comment, it seems like it _should_ have defaulted to eslints parser, but that is undefined:
<img width="206" alt="image" src="https://github.com/eslint/eslint/assets/17054057/c826138f-0f8b-4ed1-8284-7a78c7ad770d">

I'm not too familiar with ESLint's internals, but this feels like it could potentially be a bug, so I figured I'd report it.

So two main questions are:
- Is my assumption that parser options are not "inherited" anymore, like was the case in the old config format, and instead now every object in the exported flat config array from `eslint.config.js` needs to configure their own parser options?
- Is this a bug in ESLint? Or should I report this elsewhere? (like `eslint-plugin-import`?)

### What actually happened?

See explanation above

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/stackblitz-starters-g64xvt?file=eslint.config.js

### Participation

- [ ] I am willing to submit a pull request for this issue.

### Additional comments

Open the stackblitz and run `npm run lint` in the terminal to see the result:

```
  1:17  error    Parse errors in imported module './foo.js': parserPath or languageOptions.parser is required! (undefined:undefined)  import/no-named-as-default
```

**Comment by aladdin-add** [comment] 2024-01-04 17:39
it's not eslint's bug - the plugin just has not supported flat configs: https://github.com/import-js/eslint-plugin-import/issues/2943, https://github.com/import-js/eslint-plugin-import/pull/2873

**Comment by mdjermanovic** [comment] 2024-01-04 18:27
> * Is my assumption that parser options are not "inherited" anymore, like was the case in the old config format, and instead now every object in the exported flat config array from `eslint.config.js` needs to configure their own parser options?

`context.languageOptions.parser` is always defined. If `languageOptions.parser` isn't specified in config objects, then it defaults to Espree which is set in the [default config](https://github.com/eslint/eslint/blob/3ee0f6ca5d756da647e4e76bf3daa82a5905a792/lib/config/default-config.js#L43), so when the config objects are merged with the default config the resulting config for a file will have Espree in `languageOptions.parser`.

**Closed** 2024-01-04 18:29 UTC
Labels: bug, 3rd party plugin, repro:needed

**Comment by G-Rath** [comment] 2024-04-19 04:12
@mdjermanovic I've been working on v9 support for `eslint-plugin-import` and was wondering if you could help clarify something about this for me - a lot of tests are failing due to the error in the original description, seemingly because the `parser` isn't there.

i.e. if you compare [this run using v7](https://github.com/import-js/eslint-plugin-import/actions/runs/8747922114/job/24007142612?pr=2996) to [this run using v9)[https://github.com/import-js/eslint-plugin-import/actions/runs/8747922114/job/24007140735?pr=2996] - even just glancing through the logs you'll see a lot of `parserPath: undefined`.

I have a feeling the answer is probably that the defaults you linked to are used for the CLI but not by `RuleTester` - does that sound right to you?

**Comment by G-Rath** [comment] 2024-06-25 19:08
@arhirani `eslint-plugin-import` does not yet support ESLint v9 - see https://github.com/import-js/eslint-plugin-import/pull/2996 and https://github.com/import-js/eslint-plugin-import/issues/2948 for more.

One of the things blocking progress is this issue - from what I can tell, it seems like @mdjermanovic's comment about `context.languageOptions.parser` always being defined isn't true in v9, at least by the time this particular code path is called; it feels like what's happened is previously the property was always explicitly set to a value whereas in v9 it's implicitly set (e.g. at some point ESLint does something like `context.languageOptions.parser || defaultParser`)

**Comment by mdjermanovic** [comment] 2024-06-25 19:20
@G-Rath sorry, I missed this. Can you please open an issue describing in which cases `context.languageOptions.parser` isn't set?

**Comment by G-Rath** [comment] 2024-06-25 19:47
@mdjermanovic unfortunately I've not got a lot of bandwidth right now - I have tried quickly to reproduce this with the plugin example from [the docs](https://eslint.org/docs/latest/extend/plugins) without success which doesn't entirely surprise me but while I can't remember the details I know I was pretty confident that there at least wasn't much code in between where the plugin throws and ESLint.

Ultimately though this is why I didn't open an issue at the time, and was hoping one of your team might have a rare bit of available bandwidth to spare for a look to help shed some light on what's going on 🙂 

I pushed up https://github.com/import-js/eslint-plugin-import/pull/2996/commits/727839a5e671c732640e08b757c1801ef45aa0b2 to log the context right before the error - while the logs will now have expired, they did show the context as being empty.

Of course now re-digging into the code a bit more, I'm seeing some more complex code paths than I remember so whose knows 🤷 I'll see if I can get bandwidth sometime this week to dig a bit more into it
