### ISSUE TITLE
eslint rule camelcase needs --fix command

### ISSUE THREAD

**Issue by revisionfour** [eslint/eslint#7530] opened 2016-11-03 19:42 UTC
eslint rule camelcase needs a --fix command to automatically convert from snake case to camel case. 
[camelcase](https://github.com/eslint/eslint/blob/master/docs/rules/camelcase.md)

Any eslint rule that can be automatically fixed through a --fix command should have that option. If not, then a codemod for jscodeshift should be written for it if possible. I've started adding at least the issue to repos for now. I hope to start helping code these in the coming weeks when I have some time.

Go team open source.

**Comment by not-an-aardvark** [comment] 2016-11-03 19:49
Hi, thanks for the suggestion.

I'm worried that it wouldn't be possible to fix this without changing the behavior of code. For example, the following fix could be made:

```js
module.exports.bar_baz = 5;

// gets fixed to:

module.exports.barBaz = 5;
```

but that would cause code in a different file that was depending on the `bar_baz` property to break.

Would you mind filling out the [rule change proposal template](https://raw.githubusercontent.com/eslint/eslint/master/templates/rule-change-proposal.md) to clarify how this fix would work?

**Comment by revisionfour** [comment] 2016-11-03 19:56
Yeah, I can do that. I was more thinking that this would be something you would run against multiple files vs just one, therefore having consistency in your codebase. 

There could be other edge cases that would be hard to catch such as the following,

const str1 = 'foo';
const str2 = '_bar';

obj[str1 + str2] = 'this would be hard to catch'; 

Ill see what I can do to put together the template later tonight.

**Comment by platinumazure** [comment] 2016-11-03 20:27
@revisionfour Thanks for the issue. Just so you know, it is by design that not all rules are fixable (and even for those rules that are fixable, not all violations can be fixed). The `--fix` flag should be thought of as a process switch, not a switch that can be applied to any particular rule. The flag basically means, "Attempt to fix any violations that we know how to fix".

As not-an-aardvark pointed out already, auto-fix for this could be dangerous due to consumers outside the file possibly being broken. If you are writing a library for other projects to consume, then ESLint will not be able to fix their code, so you *will* be breaking your consumers.

That said, we are happy to consider any proposals that follow our rule change proposal template. Thanks in advance!

**Comment by ilyavolodin** [comment] 2016-11-04 14:12
Adding autofixing to this rule gets us into a realm of pre-compilers. Consider the example below:
```js
var myVariable = 0;
var my_variable = "hello";
```
Autofixing the code above will result in shadowing of the original variable. In order to fix this properly, we need to catalog all variables in the file and start renaming them so there wouldn't be any collisions. That's what Babel does when it transpiles code. I think this is outside of the scope of the responsibilities of linter. I'm am 👎  on adding this into the core.

**Comment by vitorbal** [comment] 2016-11-04 18:08
I agree with @ilyavolodin. Autofixing this rule will mean a lot of complexity and probably even a considerable performance hit.

**Comment by revisionfour** [comment] 2016-11-05 03:39
Fair. eslint may not be the place to implement this autofix. I think it is a worthy discussion deciding which rules should be fixable and which should not.

IF it is decided by the community that this rule should not have a --fix command for eslint, I think that should be noted at the top of the Readme. Something like

**Not Fixable:** This rule is not fixable or does not have intention of adding this functionality via eslint.

I only say this because there is an effort underway to add --fix commands to rules that can handle them. A successful experiment was carried out by my team, you can see that here.
[Pull request 886](https://github.com/yannickcr/eslint-plugin-react/pull/886)

All readmes do not have to be changed to put **Not-Fixable** at the top, however if they do not include it, it could be assumed that either a decision has not been made on the rule whether it is fixable or not or a --fix command just has not been written yet.

I'm probably going to be crucified for making this suggestion but we need to understand that there are very large Javascript projects that could greatly benefit by computer refactor vs human refactor. Its something to consider when you take into account that Governments are moving to open source full stack Javascript. However, right now it is in the experimental phase.

The [codemod](https://github.com/facebook/codemod) [jscodeshift](https://github.com/facebook/jscodeshift) community can take on this autofix for this rule at a later date.

**Comment by not-an-aardvark** [comment] 2016-11-05 03:51
@revisionfour Thanks for the suggestion. However, I'm not sure I understand the point of putting a **Not-Fixable** notice at the top of non-fixable rules. Could you clarify how this would be useful?

> I only say this because there is an effort underway to add --fix commands to rules that can handle them. A successful experiment was carried out by my team, you can see that here.

Great! I agree, having fixers for theoretically fixable rules seems like a very good goal. However, I don't think `camelcase` is one of these rules, because fixing it would end up breaking working code, which is very undesirable.

> I'm probably going to be crucified for making this suggestion but we need to understand that there are very large Javascript projects that could greatly benefit by computer refactor vs human refactor. Its something to consider when you take into account that Governments are moving to open source full stack Javascript. However, right now it is in the experimental phase.

I agree, there are certainly a lot of benefits of being able to automatically fix problems in code. However, it's very important that tools like ESLint don't create "fixes" that actually cause working code to break.

**Comment by revisionfour** [comment] 2016-11-05 04:16
"I'm not sure I understand the point of putting a Not-Fixable notice at the top of non-fixable rules"

Is the rule non-fixable because the community decided that or because a --fix command has not been written yet?

For instance, based on the logic you just used, this rule [jsx-first-prop-new-line](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-first-prop-new-line.md) was non-fixable a day ago.

However, if you look at this [commit](https://github.com/yannickcr/eslint-plugin-react/commit/4e83bea87c5598783a1f4a741af8fef121ebd81a), you will see that this rule is now fixable and that is now noted in the Readme.

It should not be assumed that a rule is non-fixable just because a --fix command is not noted at the top. It should be known however that a rule is Not-Fixable if it is noted at the top because the community or repo maintainers have already made that decision.

**Comment by not-an-aardvark** [comment] 2016-11-05 04:21
> Is the rule non-fixable because the community decided that or because a --fix command has not been written yet?

I see your point. However, I'm not convinced that this distinction is relevant to the rule's users; either the rule can be fixed in the current version of ESLint, or it can't. There are a lot of rules that will never be fixable (because fixing them would change the behavior of the code). Displaying a notice on each of them that the rule won't be fixable in the future seems sort of redundant and unnecessary to me.

**Comment by revisionfour** [comment] 2016-11-05 04:21
Also worth noting that I am in agreement that this rule does not need a -fix command for eslint. I am only making the suggestion that this should be noted in rules where the maintainers or community has deemed that this rule is not to be fixable by eslint. Give the idea a little time to think over. Doing this would add drive and desire by the open source community to add --fix commands to the rules that could be fixable. It would be a catalyst.

**Comment by not-an-aardvark** [comment] 2016-12-12 20:29
It looks like there was consensus that we should not add autofixing for `camelcase`, so I'm going to close this issue.

**Closed by not-an-aardvark** 2016-12-12 20:29 UTC
Labels: enhancement, evaluating, rule
