### ISSUE TITLE
`overrides` with processor works unexpectedly

### ISSUE THREAD

**Issue by JounQin** [eslint/eslint#14207] opened 2021-03-12 12:59 UTC
**Tell us about your environment**

* **ESLint Version:** 7.21.0
* **Node Version:** v14.16.0
* **npm Version:** 7.5.6
* **Operating System:** GNU/Linux 5.4.0-1024-gcp

**What parser (default, `@babel/eslint-parser`, `@typescript-eslint/parser`, etc.) are you using?**

Default

**Please show your full configuration:**

https://github.com/JounQin/test/blob/eslint/.eslintrc.js

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

https://github.com/JounQin/test/blob/eslint/test.cjs

```bash
yarn eslint test.cjs
```

**What did you expect to happen?**

No error because prettier is intended to be disabled

**What actually happened? Please copy-paste the actual, raw output from ESLint.**

```log
Oops! Something went wrong! :(

ESLint: 7.21.0

Error: ENOTDIR: not a directory, stat '/workspace/test/test.cjs/0_.cjs'
Occurred while linting /workspace/test/test.cjs/0_.cjs:1
    at Object.statSync (fs.js:1086:3)
    at isTypeSync (/workspace/test/node_modules/prettier/third-party.js:9748:46)
    at getDirectorySync (/workspace/test/node_modules/prettier/third-party.js:9802:62)
    at ExplorerSync.searchSync (/workspace/test/node_modules/prettier/third-party.js:9950:66)
    at _resolveConfig (/workspace/test/node_modules/prettier/index.js:25592:50)
    at Function.resolveConfig.sync (/workspace/test/node_modules/prettier/index.js:25621:42)
    at Program (/workspace/test/node_modules/eslint-plugin-prettier/eslint-plugin-prettier.js:167:40)
    at /workspace/test/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/workspace/test/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
```

**Steps to reproduce this issue:**

1. clone https://github.com/JounQin/test/tree/eslint or open https://turquoise-limpet-v0as7arg.ws-us03.gitpod.io/
2. run `yarn eslint test.cjs`, there will be an error
3. toggle the comment in `.eslintrc.js` and run `yarn eslint test.cjs` again, there will be no error, but it is not expected, I want to check `test.cjs` with `prettier` but disable it on code block

**Are you willing to submit a pull request to fix this bug?**

I don't know how to fix it easily.

**Comment by mdjermanovic** [comment] 2021-03-18 01:07
I can confirm this behavior.

When `preprocess()` returns a filename with the same extension as the original file, that virtual file will be linted with the configuration for the original file (except the `"processor"` option).

https://github.com/eslint/eslint/blob/ebd70263f6e6fe597613d90f4b8de84710c2f3d6/lib/linter/linter.js#L1311-L1326

I believe we assumed that if a processor used for `*.foo` files returns a `.foo` filename, then it's the same content, and calling `this._verifyWithConfigArray` again would cause infinite recursion. But, as a side effect of using the same config, overrides for `*.foo/*.foo` do not apply.

I'm not sure what's the intended behavior in this case. For users, it might make more sense to see this as the original file and thus make a configuration for `*.foo` (not `*.foo/*.foo`). On the other hand, it looks inconsistent with the behavior when processors return different extensions.

**Comment by JounQin** [comment] 2021-03-18 01:37
I think rules for `*.foo/*` should take higher priority than `*.foo` then there will be no problem.

**Comment by JounQin** [comment] 2021-03-18 03:13
> I believe we assumed that if a processor used for *.foo files returns a .foo filename, then it's the same content, and calling this._verifyWithConfigArray again would cause infinite recursion. 

That's not true for markdown/mdx in markdown/mdx.

**Comment by JounQin** [comment] 2021-03-18 03:37
I think we should change the following

https://github.com/eslint/eslint/blob/ebd70263f6e6fe597613d90f4b8de84710c2f3d6/lib/linter/linter.js#L1312-L1319

to

```js
// Resolve configuration again if the file content was changed.
if (configForRecursive && text !== blockText) {
  debug('Resolving configuration again because the file extension was changed.')
  return this._verifyWithConfigArray(blockText, configForRecursive, {
    ...options,
    filename: blockName,
  })
}
```

@mdjermanovic I'd like to raise a PR if you like it.

**Comment by mdjermanovic** [comment] 2021-03-25 21:12
@eslint/eslint-tsc thoughts about this, is it a bug or the intended behavior?

If it's a bug, does the fix in https://github.com/eslint/eslint/pull/14227 makes sense, and would it be a breaking change now?

**Comment by nzakas** [comment] 2021-03-26 00:59
I think this is a bug. We probably did this for performance reasons, since calculating configs is expensive.

I’m also guessing this use case is fairly uncommon so fixing this bug doesn’t seem like a breaking change to me.

**Comment by btmills** [comment] 2021-03-27 22:09
I agree this is a bug that we can fix in a semver-minor change.

**Comment by nzakas** [comment] 2021-03-31 00:56
Marking as accepted. There is already a PR open.

**Closed** 2021-04-13 05:45 UTC
Labels: accepted, bug, core, repro:yes
