### ISSUE TITLE
Error installing dependencies with ESLint

### ISSUE THREAD

**Issue by Tlaloc-Es** [eslint/eslint#11865] opened 2019-06-20 15:51 UTC
**Tell us about your environment**

* **ESLint Version: 5.16.0**
* **Node Version:10.16.0**
* **npm Version:6.9.0**

**What did you do? 

```bash
npx eslint --init 
```

> ? How would you like to use ESLint? To check syntax, find problems, and enforce 
> code style
> ? What type of modules does your project use? JavaScript modules (import/export)
> 
> 
> ? Which framework does your project use? None of these
> ? Where does your code run? Node
> ? How would you like to define a style for your project? Use a popular style gui
> de
> ? Which style guide do you want to follow? Standard (https://github.com/standard
> /standard)
> ? What format do you want your config file to be in? JavaScript
> Checking peerDependencies of eslint-config-standard@latest
> The config that you've selected requires the following dependencies:
> 
> eslint-config-standard@latest eslint@>=5.0.0 eslint-plugin-import@>=2.13.0 eslint-plugin-node@>=7.0.0 eslint-plugin-promise@>=4.0.0 eslint-plugin-standard@>=4.0.0
> ? Would you like to install them now with npm? (Y/n) 

Answer all the questions until this

**What did you expect to happen?**
That the STDIN worked and could continue

**What actually happened? Please include the actual, raw output from ESLint.**
The stdin is blocked and I can not continue

**Comment by g-plane** [comment] 2019-06-20 15:53
Duplicate of #11862

**Closed by g-plane** 2019-06-20 15:53 UTC
Labels: bug, triage
