### ISSUE TITLE
Add type validation for IntersectionType

### ISSUE THREAD

**Issue by joelday** [eslint/eslint#7963] opened 2017-01-22 21:43 UTC
Pending merge of https://github.com/eslint/doctrine/pull/184, (implementation of https://github.com/eslint/doctrine/issues/183), https://github.com/eslint/eslint/blob/75b7ba4113db4d9bc1661a4600c8728cf3bfbf2b/lib/rules/valid-jsdoc.js#L174 needs to be changed to treat IntersectionType (`{String&number&Test}`) as valid.

Thanks!

**Comment by platinumazure** [comment] 2017-01-23 01:12
Marking as rule enhancement for now.

I'm :+1: to the enhancement contingent on the doctrine change being accepted. If IntersectionType isn't valid JSDoc, though, then I'm :-1: to this enhancement.

**Comment by joelday** [comment] 2017-01-23 03:01
@platinumazure It does indeed appear to be currently unsupported on the JSDoc side: https://github.com/jsdoc3/jsdoc/issues/1285

**Comment by joelday** [comment] 2017-01-23 03:01
Will follow up. Thanks!

**Comment by not-an-aardvark** [comment] 2018-01-19 16:20
Thanks for your interest in improving ESLint. Unfortunately, it looks like this issue didn't get consensus from the team, so I'm closing it. We define [consensus](http://eslint.org/docs/maintainer-guide/issues.html#consensus) as having three :+1:s from team members, as well as a team member willing to champion the proposal. This is a high bar by design -- we can't realistically accept and maintain every feature request in the long term, so we only accept feature requests which are useful enough that there is consensus among the team that they're worth adding.

Since ESLint is pluggable and can load custom rules at runtime, the lack of consensus among the ESLint team doesn't need to be a blocker for you using this in your project, if you'd find it useful. It just means that you would need to [implement the rule](http://eslint.org/docs/developer-guide/working-with-rules) yourself, rather than using a bundled rule that is packaged with ESLint.

**Closed by not-an-aardvark** 2018-01-19 16:20 UTC
Labels: blocked, enhancement, evaluating, rule
