### ISSUE TITLE
Bug: Running ESLint now shows Error: Missing initializer in const declaration

### ISSUE THREAD

**Issue by adamlui** [eslint/eslint#18895] opened 2024-09-13 13:50 UTC
### Environment

Node version: v21.6.2
npm version: v10.2.4
Local ESLint version:  v9.10.0
Global ESLint version: N/A
Operating System: win32 10.0.19045

### What parser are you using?

Default (Espree)

### What did you do?

`npm run lint:all` which runs the package.json script `"lint:all": "eslint ."`

<details>
<summary>Configuration</summary>

```
import js from '@eslint/js';
import globals from 'globals';
import json from 'eslint-plugin-json';

export default [
    js.configs.recommended,
    {
        rules: {
            'indent': 'off', 'no-unexpected-multiline': 'off', 'key-spacing': 'off', // allow whitespace anywhere
            'quotes': ['error', 'single', { 'allowTemplateLiterals': true }], // enforce single quotes except backticks to avoid escaping quotes
            'comma-dangle': ['error', 'never'], // enforce no trailing commas in arrays or objects
            'no-async-promise-executor': 'off', // allow promise executor functions to be async (to accomodate await lines)
            'no-constant-condition': 'off', // allow constant conditions
            'no-empty': 'off', // allow empty blocks
            'no-inner-declarations': 'off', // allow function declarations anywhere
            'no-useless-escape': 'off', // allow all escape chars cause ESLint sucks at detecting truly useless ones
            'no-unused-vars': ['error', { 'caughtErrors': 'none' }] // allow unused named args in catch blocks
        },
        languageOptions: {
            ecmaVersion: 2022, sourceType: 'script',
            globals: {
                ...globals.browser, ...globals.greasemonkey,
                chatgpt: 'readonly', chrome: 'readonly', CryptoJS: 'readonly', GM_cookie: 'readonly', hljs: 'readonly',
                ipv4: 'readonly', marked: 'readonly', renderMathInElement: 'readonly', syncExtension: 'writable'
            }
        }
    },
    { files: ['**/*.mjs', '**/lib/*.js'], languageOptions: { sourceType: 'module' }},
    { files: ['**/*.json'], ...json.configs['recommended'] }
];
```
</details>

### What did you expect to happen?

Successful linting

### What actually happened?

![Image](https://github.com/user-attachments/assets/9e06da2e-4905-4430-b11c-58929d723cdf)

### Link to Minimal Reproducible Example

I can't because it happens in cmd.exe, but the repo is https://github.com/adamlui/chatgpt-apps

### Participation

- [x] I am willing to submit a pull request for this issue.

**Comment by nzakas** [comment] 2024-09-13 15:32
Please create a minimal reproduction case in a GitHub repo and we can take a look.

**Comment by adamlui** [comment] 2024-09-13 17:25
@nzakas do you know of a site I can use to emulate cmd.exe causing this error? (It works fine on GitHub Actions I think)

**Comment by nzakas** [comment] 2024-09-13 19:23
I don't. But we don't need a StackBlitz, just a GitHub repo with the minimum required to reproduce the error. I'm on Windows so I can clone it and try it locally.

**Comment by adamlui** [comment] 2024-09-13 20:02
Ok it is occurring for my https://github.com/adamlui/chatgpt-apps since the last update from 9.9.X (but oddly it didn't happen in other repos after this update) when running `npm run lint:all`

**Comment by Tanujkanti4441** [comment] 2024-09-14 07:08
@adamlui, i tried to test the repo locally but couldn't reproduce the error you specified.

![Image](https://github.com/user-attachments/assets/acbab3bc-23ce-43e1-bdd1-184907fe69e7)

**Comment by adamlui** [comment] 2024-09-14 07:16
Thanks @Tanujkanti4441 I'll delete node_modules after my smoke break and it should fix it, idk whether to leave this issue open in case something of eslint can be fixed though

**Comment by adamlui** [comment] 2024-09-14 07:32
The deletion then `npm i` fixed it

**Comment by Tanujkanti4441** [comment] 2024-09-15 06:06
> The deletion then `npm i` fixed it

Great! so we can close this issue now.

**Closed by Tanujkanti4441** 2024-09-15 06:06 UTC
Labels: bug, repro:needed
