### ISSUE TITLE
New rule: Validate (template) strings for non-normalised Unicode chars

### ISSUE THREAD

**Issue by pke** [eslint/eslint#9682] opened 2017-12-04 14:11 UTC
OSX has a bug that it encodes German umlaute not in Normalization Form Canonical Composition (NFC). This leads to wrong outputs of those strings in React/Browser env. Only Chrome seems to be able to render those char sequences in UTF-8 docs correctly.

I wonder if a rule: "unicode-normalization" rule (with autofix) would make sense. It would default to NFC but would allow to change the form according to the [available options](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/normalize).

Or would such rule be better of in a (unicode-)plugin?

**Comment by platinumazure** [comment] 2017-12-04 14:16
Hi @pke, thanks for the issue. It would really help to see a few examples, along with anything else called out in the "Proposing a New Rule" instructions linked above.

Also, if this doesn't get accepted for inclusion in core ESLint, you are more than welcome to create this as a custom rule (and maybe even include it in a plugin).

**Comment by pke** [comment] 2017-12-04 16:24
Thanks fr consideration. I'll read up about proposing new rules, didn't find that before.
When you say create it as a custom rule. Is there an easy way to use custom rules without putting them into a plugin?

**Comment by j-f1** [comment] 2017-12-04 16:31
You can put the rule in an `eslint-rules` directory in your project, then run `eslint --rulesdir eslint-rules` and enable the with just its name.

<details><summary>This is the template the ESLint team would like you to add to your original issue so that the rule can be properly evaluated:</summary>

````markdown
**Please describe what the rule should do:**


**What category of rule is this? (place an "X" next to just one item)**

[ ] Enforces code style
[ ] Warns about a potential error
[ ] Suggests an alternate way of doing something
[ ] Other (please specify:)

**Provide 2-3 code examples that this rule will warn about:**

```js
<!-- put your code examples here -->
```

**Why should this rule be included in ESLint (instead of a plugin)?**

````

</details>

**Comment by not-an-aardvark** [comment] 2018-01-19 15:44
Thanks for your interest in improving ESLint. Unfortunately, it looks like this issue didn't get consensus from the team, so I'm closing it. We define [consensus](http://eslint.org/docs/maintainer-guide/issues.html#consensus) as having three :+1:s from team members, as well as a team member willing to champion the proposal. This is a high bar by design -- we can't realistically accept and maintain every feature request in the long term, so we only accept feature requests which are useful enough that there is consensus among the team that they're worth adding.

Since ESLint is pluggable and can load custom rules at runtime, the lack of consensus among the ESLint team doesn't need to be a blocker for you using this in your project, if you'd find it useful. It just means that you would need to [implement the rule](http://eslint.org/docs/developer-guide/working-with-rules) yourself, rather than using a bundled rule that is packaged with ESLint.

**Closed by not-an-aardvark** 2018-01-19 15:44 UTC
Labels: evaluating, feature, needs info, rule

**Comment by pke** [comment] 2018-01-20 21:48
That's ok. Thanks for the thorough explanation! I'll create a unicode linting plugin then.
