### ISSUE TITLE
Pug templates. Highlighting js errors in VS Code working incorrectly

### ISSUE THREAD

**Issue by believer-ufa** [eslint/eslint#9628] opened 2017-11-15 20:13 UTC
Hello and thanks for this library!

I have errors in checking JS code in my Pug templates.

![image](https://user-images.githubusercontent.com/801727/32857148-bf02019e-ca68-11e7-9bad-82ec3980eca7.png)

I described all details in [issue to VS Code ESLint plugin](https://github.com/Microsoft/vscode-eslint/issues/338) because think what error in it, but we realized that the root of the problem is somewhere else. I also created an [issue in eslint-plugin-pug repository](https://github.com/myfreeweb/eslint-plugin-pug/issues/4) about it. I just dont know where root of problem, therefore creating this issue also.

Please, can you read above issue and say you thoughts about it?

* **ESLint Version:** 4.10.0
* **Node Version:** 8.8.1
* **npm Version:** 5.5.1

**What parser (default, Babel-ESLint, etc.) are you using?**

I dont know, sorry :( I just use Visual Studio Code and plugins for linting.

I use [Visual Studio Code](https://github.com/Microsoft/vscode) ide, [vscode-eslint](https://github.com/Microsoft/vscode-eslint) plugin, [eslint-plugin-pug](https://github.com/myfreeweb/eslint-plugin-pug) plugin.

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
module.exports = {
    "env": {
        "browser": true,
        "es6": true,
        "node": true
    },
    "extends": "eslint:recommended",
    "parserOptions": {
        "ecmaFeatures": {
            "experimentalObjectRestSpread": true,
            "jsx": true
        },
        "sourceType": "module",
    },
    "plugins": [
        "react",
        "html",
        "pug"
    ],
    "globals" : {
        "$" : true,
        "jQuery" : true,
        "Loader" : true,
        "Navigation" : true,
        "UserParams" : true,
        "opts" : true,
        "trans" : true,
        "ENV" : true,
        "User" : true,
        "HeaderToggler" : true,
        "RiotApps" : true,
        "riot" : true,
        "SystemJS" : true,
    },
    "rules": {
        "no-undef": 1,
        "no-unused-vars": 1,
        "no-console": "off",
        "no-case-declarations" : "off",
        "indent": [ "error", 4, {
            "SwitchCase" : 1 ,
            "ArrayExpression"  : "off",
            "ObjectExpression" : "off",
        } ],
        "linebreak-style": [
            "error",
            "unix"
        ],
        "semi": [
            "error",
            "never"
        ],
        "react/jsx-uses-vars": [2]
    }
};
```
</details>

-------------

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

You can try to play with linting js code in Pug files if you clone [this repository](https://github.com/believer-ufa/vscode-eslint-pug).

```pug
.some-element
.testing

script.
    function ss() {

    }
```

I dont know how VS Code using eslint, sorry.

**What did you expect to happen?**

VS Code correctly highlight js errors in my Pug files.

**What actually happened? Please include the actual, raw output from ESLint.**

VS Code incorrectly highlight js errors in my Pug files.

**Comment by not-an-aardvark** [comment] 2017-11-15 21:12
Hi,

This is an issue with `eslint-plugin-pug`. The problem is that `eslint-plugin-pug` is not setting the `endLine` and `endColumn` properties correctly on errors, so the resulting error objects have an invalid range.

**Comment by myfreeweb** [comment] 2017-11-15 22:17
@not-an-aardvark thanks for the tip, added handling of these properties. Where do `endLine` and `endColumn` come from? They don't appear when testing with `CLIEngine`…

**Comment by not-an-aardvark** [comment] 2017-11-15 22:24
They should be appearing with `CLIEngine`. Support for the properties in ESLint v3.1.0 (and there was a change in ESLint v4.4.0 which made more rules use the properties implicitly). Is it possible that you're using an older version of ESLint?

**Comment by myfreeweb** [comment] 2017-11-15 22:29
Oh, okay. All my tests are using the missing semicolon rule :D Makes sense that it doesn't report a whole range.

**Comment by believer-ufa** [comment] 2017-11-15 22:30
Many thanks, now everything works fine! :)

![image](https://user-images.githubusercontent.com/801727/32863802-8bc070f2-ca7e-11e7-9a27-75f39963c909.png)

**Comment by not-an-aardvark** [comment] 2017-11-15 22:38
Great, I'll close this issue then.

**Closed by not-an-aardvark** 2017-11-15 22:38 UTC
Labels: question
