### ISSUE TITLE
eslint 2.4.0 has a missing dependency of estraverse-fb

### ISSUE THREAD

**Issue by kumar303** [eslint/eslint#5569] opened 2016-03-14 12:17 UTC
**What version of ESLint are you using?**
2.4.0

**What parser (default, Babel-ESLint, etc.) are you using?**
babel-eslint

**Please show your full configuration:**
https://github.com/mozilla/web-ext/blob/0ce1debe0546559fd79ec43523250f776148749f/.eslintrc

**What did you do? Please include the actual source code causing the issue.**
Upgraded babel-eslint

**What did you expect to happen?**
I expected my eslint configuration to work just like before.

**What actually happened? Please include the actual, raw output from ESLint.**
I get this traceback:
````
Error: Cannot find module 'estraverse-fb'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at monkeypatch (/home/travis/build/mozilla/web-ext/node_modules/babel-eslint/index.js:59:32)
    at Object.exports.parse (/home/travis/build/mozilla/web-ext/node_modules/babel-eslint/index.js:385:5)
    at parse (/home/travis/build/mozilla/web-ext/node_modules/eslint/lib/eslint.js:577:27)
    at EventEmitter.module.exports.api.verify (/home/travis/build/mozilla/web-ext/node_modules/eslint/lib/eslint.js:715:19)
    at processText (/home/travis/build/mozilla/web-ext/node_modules/eslint/lib/cli-engine.js:187:27)
    at processFile (/home/travis/build/mozilla/web-ext/node_modules/eslint/lib/cli-engine.js:227:18)
    at executeOnFile (/home/travis/build/mozilla/web-ext/node_modules/eslint/lib/cli-engine.js:603:23)
    at /home/travis/build/mozilla/web-ext/node_modules/eslint/lib/cli-engine.js:630:17
    at Array.forEach (native)
    at CLIEngine.executeOnFiles (/home/travis/build/mozilla/web-ext/node_modules/eslint/lib/cli-engine.js:625:18)
    at Object.<anonymous> (/home/travis/build/mozilla/web-ext/node_modules/grunt-eslint/tasks/eslint.js:38:20)
    at Object.<anonymous> (/home/travis/build/mozilla/web-ext/node_modules/grunt/lib/grunt/task.js:264:15)
    at Object.thisTask.fn (/home/travis/build/mozilla/web-ext/node_modules/grunt/lib/grunt/task.js:82:16)
    at Object.<anonymous> (/home/travis/build/mozilla/web-ext/node_modules/grunt/lib/util/task.js:301:30)
    at Task.runTaskFn (/home/travis/build/mozilla/web-ext/node_modules/grunt/lib/util/task.js:251:24)
    at Task.<anonymous> (/home/travis/build/mozilla/web-ext/node_modules/grunt/lib/util/task.js:300:12)
    at /home/travis/build/mozilla/web-ext/node_modules/grunt/lib/util/task.js:227:11
    at process._tickDomainCallback (node.js:381:11)
````

You can see my failing test run here: https://travis-ci.org/mozilla/web-ext/jobs/115443944

This was originally reported in https://github.com/eslint/eslint/issues/5476 but the fix for it (https://github.com/eslint/eslint/commit/97b24668b390b398225e8ef1bc817d6a0d1a4c59) does not appear to declare `estraverse-fb` as a direct dependency -- unless I missed it.

**Comment by platinumazure** [comment] 2016-03-14 12:52
I believe we've fixed our issue, but `babel-eslint` has to make a change as well.

**Comment by hzoo** [comment] 2016-03-14 13:24
I've been making all changes on the 6.x branch - can you try with babel-eslint@v6.0.0-beta.6?

**Comment by swillard-r7** [comment] 2016-03-14 14:14
@hzoo I can confirm that the 6.x (latest beta) fixes this issue with eslint.

On a slightly unrelated note, I guess things were renamed in babel-eslint 6 from 5, so I'm getting several errors

```
  6:1  error  Rule 'no-empty-label' was removed and replaced by: no-labels                 no-empty-label
  6:1  error  Rule 'space-before-keywords' was removed and replaced by: keyword-spacing    space-before-keywords
  6:1  error  Rule 'space-after-keywords' was removed and replaced by: keyword-spacing     space-after-keywords
  6:1  error  Rule 'space-return-throw-case' was removed and replaced by: keyword-spacing  space-return-throw-case
```

**Comment by hzoo** [comment] 2016-03-14 14:21
@swillard-r7 Yes, those would be eslint 2 errors since rules were renamed (and yes unrelated to babel-eslint).

ESLint 2 would be major version change and thus with breaking changes (this is why babel-eslint 5 is for ESLint 1 and babel-eslint 6 is for ESLint 2)

**Comment by ilyavolodin** [comment] 2016-03-14 15:36
Closing this since it's been fixed.

**Closed by ilyavolodin** 2016-03-14 15:36 UTC
Labels: triage
