### ISSUE TITLE
Option to disable inline global declarations

### ISSUE THREAD

**Issue by aboyton** [eslint/eslint#8909] opened 2017-07-09 22:20 UTC
**Tell us about your environment**

* **ESLint Version:** v3.19.0
* **Node Version:** v6.10.0
* **npm Version:** 3.10.10

**What parser (default, Babel-ESLint, etc.) are you using?** babel-eslint

**The problem you want to solve.**
Disallowing developers to introduce new globals.

ESLint allows two ways of specifying global variables—setting `globals` in a configuration file and as a comment in a JavaScript file `/* global var1, var2 */`.

http://eslint.org/docs/user-guide/configuring#specifying-globals

**Your take on the correct solution to problem**
While globals are sometimes necessary, I'd like to be able to only allow globals that are specified by the `globals` in a config file and not as comments inside a JavaScript file. The reason for this is that we have a large codebase and we'd like to be able to enforce which globals we allow at a top level without allowing individual developers to be able to override this in their own files. While we can do this by making sure people don't change the `.eslintrc` file it's harder to watch for people doing `/* global var1, var2 */` in a file.

I noticed this issue the other day when someone was porting some code that contained `/* global jq */` to a place where jQuery was not defined on the global scope and thus ESLint didn't help with catching this.

Of course I can use a different tool or a custom ESLint rule to disable comments like `/* global var1, var2 */` but it would be nice if this could be included natively as part of ESLint.

I'm unsure the best way to do this. Intuitively it makes more sense to me for this to be an option to [`no-undef`](http://eslint.org/docs/rules/no-undef) but given that this logic appears to be handled well before the code in [`no-undef`](http://eslint.org/docs/rules/no-undef) is even run it might make more sense to happen in the configuration file.

**Comment by not-an-aardvark** [comment] 2017-07-10 00:03
Thanks for the proposal. Does the [`--no-inline-config`](http://eslint.org/docs/user-guide/command-line-interface#options) option work for you?

I would personally be inclined against adding something to a config file for this, because seems like it would be simple to just create a plugin rule that disallows `/* global */` comments.

**Comment by ljharb** [comment] 2017-07-10 03:03
`no-inline-config` is a very broad brush; it'd be really great to be able to fine-tune the no-inline-config options. Also, anything that can't be stored in `.eslintrc` isn't very useful for per-project management :-/

**Comment by platinumazure** [comment] 2017-07-10 04:29
@ljharb In general, I take your point; however, one could manage CLI options per project using npm scripts in package.json.

That said, I wouldn't be opposed to leveraging optionator to expand `inline-config` to support key/value options to augment its current Boolean mode. Might be worth creating a separate issue?

**Comment by pzuraq** [comment] 2017-07-10 22:14
Would also love this feature, we have a lot of globals and shims and can't quite get rid of the global values yet. This would allow us to enforce usage of the shims and prevent our developers from accidentally using a global.

**Comment by not-an-aardvark** [comment] 2017-07-10 22:36
I'm not convinced yet that `no-inline-config` needs to be enhanced to support this (rather than just creating a rule to disallow `/* global */` comments), but I'm open to hearing a more concrete proposal.

**Comment by aboyton** [comment] 2017-07-10 22:55
`no-inline-config` is an incredibly broad brush, and exactly the broad brush that I was after. Personally we want to be able to disable all inline config, and so this is perfect. I'd missed this command line option, thanks.

I understand that potentially others might want more fine-grained control but for now at least I don't.

@ljharb It would be nice if this could be specified in `.eslintrc` but given that we're wrapping ESLint in a script called by `package.json` anyway it isn't hard to add this parameter to our script.

@pzuraq Does specifying all your globals and shims in `.eslintrc` (or similar) work for you? We have globals that we can't get rid of yet, but we want to vet their inclusion rather than just letting individual developers go wild.

**Comment by pzuraq** [comment] 2017-07-10 23:01
@aboyton that's exactly what we want, we don't want anyone to add a global without it being vetted first. We do however have some inline overrides for rules, usually small things that are one-offs in infra-code, a "you have to know what you're doing here anyways so it's alright for now" kind of thing. Disallowing inline globals is universal for us though.

I could see either a more granular `no-inline-config` or a single option to disable inline globals specifically.

**Comment by not-an-aardvark** [comment] 2017-11-03 20:43
Thanks for your interest in improving ESLint. Unfortunately, it looks like this issue didn't get consensus from the team, so I'm closing it. We define [consensus](http://eslint.org/docs/maintainer-guide/issues.html#consensus) as having three :+1:s from team members, as well as a team member willing to champion the proposal. This is a high bar by design -- we can't realistically accept and maintain every feature request in the long term, so we only accept feature requests which are useful enough that there is consensus among the team that they're worth adding.

Since ESLint is pluggable and can load custom rules at runtime, the lack of consensus among the ESLint team doesn't need to be a blocker for you using this in your project, if you'd find it useful. It just means that you would need to [implement a rule](http://eslint.org/docs/developer-guide/working-with-rules) yourself to disallow `/* global */` comments, rather than using core behavior that is packaged with ESLint.

**Closed by not-an-aardvark** 2017-11-03 20:43 UTC
Labels: core, enhancement, evaluating
