### ISSUE TITLE
sort-vars should have option to separate initialized variables.

### ISSUE THREAD

**Issue by mitchellsimoens** [eslint/eslint#9038] opened 2017-07-29 18:31 UTC
Currently, `sort-vars` rule works great in a variable block. However, in the case of a `var` or `let` where you are initializing a variable, it's common to have those initialized variables at the end.

So currently this is invalid (but a very common convention):

    var bar = 1,
        foo = 2,
        a, b;

    a = 3;

It expects this:

    var a, b,
        bar = 1,
        foo = 2;

    a = 3;

I'd like to specify an option to the `sort-vars` rule to allow the invalid snippet above:

    "sort-vars": [
        "warn",
        {
            "separateInitializers": true
        }
    ]

So it would treat the initialized variables separate from the declared variables meaning `a`b and `b` variables would get sorted separate of the `bar` and `foo` variables. Essentially treat it as two different blocks:

    var bar = 1,
        foo = 2;
    var a, b;

This would still take in the `ignoreCase` option into sorting both.

This is similar to #9039 so a common API could be setup.

**Comment by not-an-aardvark** [comment] 2017-11-03 20:55
Thanks for your interest in improving ESLint. Unfortunately, it looks like this issue didn't get consensus from the team, so I'm closing it. We define [consensus](http://eslint.org/docs/maintainer-guide/issues.html#consensus) as having three :+1:s from team members, as well as a team member willing to champion the proposal. This is a high bar by design -- we can't realistically accept and maintain every feature request in the long term, so we only accept feature requests which are useful enough that there is consensus among the team that they're worth adding.

Since ESLint is pluggable and can load custom rules at runtime, the lack of consensus among the ESLint team doesn't need to be a blocker for you using this in your project, if you'd find it useful. It just means that you would need to [implement the rule](http://eslint.org/docs/developer-guide/working-with-rules) yourself, rather than using a bundled rule that is packaged with ESLint.

**Closed by not-an-aardvark** 2017-11-03 20:55 UTC
Labels: enhancement, evaluating, rule
