### ISSUE TITLE
Spaces within --rulesdir are stripped

### ISSUE THREAD

**Issue by apexskier** [eslint/eslint#14025] opened 2021-01-22 08:25 UTC
**Tell us about your environment**

* **ESLint Version:** v7.18.0
* **Node Version:** v12.18.1
* **npm Version:** 6.14.5

~**What parser are you using?**~ (unrelated - this is a cli argument parsing error)

~**Please show your full configuration:**~ (unrelated - this is a cli argument parsing error)

**What did you do?**

Run one of these commands:

```bash
eslint --rulesdir "/Volumes/Macintosh HD/Users/test/foo/bar"
eslint --rulesdir /Volumes/Macintosh\ HD/Users/test/foo/bar
```

**What did you expect to happen?**

```
Oops! Something went wrong! :(

ESLint: 7.18.0

Error: ENOENT: no such file or directory, scandir '/Volumes/Macintosh HD/Users/test/foo/bar'
    at Object.readdirSync (fs.js:948:3)
...
```

**What actually happened? Please include the actual, raw output from ESLint.**

Note the missing space in "Macintosh HD"

```
Oops! Something went wrong! :(

ESLint: 7.18.0

Error: ENOENT: no such file or directory, scandir '/Volumes/MacintoshHD/Users/test/foo/bar'
    at Object.readdirSync (fs.js:948:3)
...
```

**Are you willing to submit a pull request to fix this bug?**

Yes

---

The core issue here is https://github.com/gkz/optionator/issues/34, which I'm currently investigating.

**Comment by anikethsaha** [comment] 2021-01-22 08:51
Thanks for the report.

Can you try with `eslint "--rulesdir" "/Volumes/Macintosh\ HD/Users/test/foo/bar"`. working fine for me

**Comment by apexskier** [comment] 2021-01-22 09:20
`eslint "--rulesdir" "/Volumes/Macintosh\ HD/Users/test/foo/bar"` is double escaping since it includes both quotes and the `\` character; the string literal should be parsed with both a `\` and a ` `.

```
cameronlittle@Chinook:~
▻ ls "/Volumes/Macintosh\ HD/" # double escaped, not valid
ls: /Volumes/Macintosh\ HD/: No such file or directory
cameronlittle@Chinook:~
▻ ls "/Volumes/Macintosh HD/" # string literal in quotes, valid
Applications/ System/       Volumes/      cores/        etc@          opt/          sbin/         usr/
Library/      Users/        bin/          dev/          home@         private/      tmp@          var@
cameronlittle@Chinook:~
▻ ls /Volumes/Macintosh HD/ # not escaped - two string literals
ls: /Volumes/Macintosh: No such file or directory
ls: HD/: No such file or directory
1 ↩
cameronlittle@Chinook:~
▻ ls /Volumes/Macintosh\ HD/ # escaped space, valid
Applications/ System/       Volumes/      cores/        etc@          opt/          sbin/         usr/
Library/      Users/        bin/          dev/          home@         private/      tmp@          var@
```

The context in which I'm working with this is using a process executor, so conditionally double escaping as a workaround will cause problems.

**Comment by anikethsaha** [comment] 2021-01-22 09:58
yeah I meant `\` without `"` one. (I have updated the comment)

Wierd I am not able to reproduce this when using quotes. it is working fine with it.

Also when not using quotes, it is not removing the spaces instead it is considering it as nested dir as `process.argv` would convert it as a separate element.

**Comment by apexskier** [comment] 2021-01-22 12:12
I updated my comment as well - any method of escaping the space causes the same behavior.

**Comment by apexskier** [comment] 2021-01-22 12:12
It doesn't happen for relative paths.

**Comment by apexskier** [comment] 2021-01-22 12:14
I'm not sure I understand your repl link, given the `works as intended` label. It seems to have same issue there.

![Repl it - testing - Google Chrome - 2021-01-22 at 13 13 43](https://user-images.githubusercontent.com/329222/105489530-a873e100-5cb3-11eb-8245-15b8f8a187e6.png)

**Comment by apexskier** [comment] 2021-01-22 12:20
If you spin up a debugger, you see that `process.argv` has the correct spacing, but after they're parsed the space is removed.

![devtoolsdevtoolsbundledjs_app html?remoteBase=httpschrome-devtools-frontend appspot comserve_file@9f05d1d9ee7483a73e9fe91ddcb8274ebcec9d7f dockSide=undocked - Google Chrome - 2021-01-22 at 13 19 54](https://user-images.githubusercontent.com/329222/105490114-99416300-5cb4-11eb-8d00-828b96e519ef.png)

Here - https://github.com/eslint/eslint/blob/c753b442ef67867a178ffc2ad29b4e0534f72469/lib/cli.js#L225

**Comment by mdjermanovic** [comment] 2021-01-22 12:51
I can reproduce this, but only if the path starts with `/` and it happens only after the second `/`.

It seems to be a problem with `levn`:

```js
const { parse } = require("levn");

console.log(parse("[String]", "/a/b c")); // [ '/a/bc' ]
```

Just a guess - it could be because `/a/b` looks like a regex.

**Comment by mdjermanovic** [comment] 2021-01-22 12:58
I'll mark this as 'blocked' for now. Not sure if there's anything we could do in ESLint aside from upgrading `optionator` to a new version once the problem gets fixed.

**Comment by apexskier** [comment] 2021-01-22 13:01
> I'll mark this as 'blocked' for now. Not sure if there's anything we could do in ESLint aside from upgrading optionator to a new version once the problem gets fixed.

@mdjermanovic Makes sense. I've root caused it to https://github.com/gkz/levn/issues/6#issuecomment-765370241. If I don't make progress there I suspect there might be a workaround by json encoding strings somewhere in the stack to force wrapping with `"` characters.

**Comment by anikethsaha** [comment] 2021-01-22 13:07
> I'm not sure I understand your repl link, given the `works as intended` label. It seems to have same issue there.
> 
> ![Repl it - testing - Google Chrome - 2021-01-22 at 13 13 43](https://user-images.githubusercontent.com/329222/105489530-a873e100-5cb3-11eb-8245-15b8f8a187e6.png)

Is it same when adding quotes ?

**Comment by apexskier** [comment] 2021-01-22 13:10
@anikethsaha Yes - same behavior as I get locally.

**Comment by mdjermanovic** [comment] 2023-05-12 14:11
Since this has been open for two years now but the problem in the dependencies is still not fixed and the [`--rulesdir`](https://eslint.org/docs/latest/use/command-line-interface#--rulesdir) option is now deprecated, I agree it's time to close it.

I don't think this problem can occur with other CLI options we have, because for that to happen the option must be of a string array type (`[String]` or `[path::String]`) with `oneValuePerFlag: false` (default) and the argument must start with `/`. 

String array options we currently have are: `--rulesdir`, `--ignore-pattern`, `--env`, `--ext`, and `--plugin` (plugin names).

`--ignore-pattern` arguments can start with `/`, but this option has [`oneValuePerFlag: true`](https://github.com/eslint/eslint/blob/8bf550594fca6d29fab1a3453e701c1a457767e1/lib/options.js#L228). For `--env`, `-ext`, and `--plugin`, it doesn't make sense that arguments start with `/`, so while the parsing problem can be reproduced with these options, it shouldn't appear in real use.

**Closed by mdjermanovic** 2023-05-12 14:11 UTC
Labels: bug, cli, blocked
