### ISSUE TITLE
Warning: Property 'propertyIsEnumerable' of object object is not a function

### ISSUE THREAD

**Issue by tborychowski** [eslint/eslint#2691] opened 2015-06-04 15:49 UTC
There's a but that crashes eslint with that warning:
```sh
Warning: Property 'propertyIsEnumerable' of object object is not a function
```

I've managed to locate it to the `object-assign` module. The latest version (3.0.0) of that module works fine, the one eslint is using (^2.0.0) - doesn't.

Can you bump the version of `object-assign` to 3.0.0?

**Comment by ilyavolodin** [comment] 2015-06-04 15:54
This is a duplicate of #2690 `object-assign` already pulled version 2.1.0 that caused this issue from NPM. All you need to do is reinstall npm dependancies and it will pull version 2.0.0 again.

**Comment by tborychowski** [comment] 2015-06-04 15:54
thanks!

**Closed by ilyavolodin** 2015-06-04 15:54 UTC

**Comment by tborychowski** [comment] 2015-06-04 16:04
Although `v2.1.0` seems to be still there:
```sh
> npm view object-assign

npm http GET http://npmjs.org/object-assign
npm http 200 http://npmjs.org/object-assign

{ name: 'object-assign',
  versions:
   [ '0.1.0',
     '0.1.1',
     '0.1.2',
     '0.2.0',
     '0.2.1',
     '0.2.2',
     '0.3.0',
     '0.3.1',
     '0.4.0',
     '1.0.0',
     '2.0.0',
     '2.1.0',
     '3.0.0' ],
  'dist-tags': { latest: '3.0.0' },
  version: '3.0.0',
  description: 'ES6 Object.assign() ponyfill',
  license: 'MIT',
  repository:
   { type: 'git',
     url: 'https://github.com/sindresorhus/object-assign' },
  author: 'Sindre Sorhus <sindresorhus@gmail.com> (http://sindresorhus.com)',
  engines: { node: '>=0.10.0' },
  scripts: { test: 'mocha' },
  files: 'index.js',
  keywords:
   [ 'object',
     'assign',
     'extend',
     'properties',
     'es6',
     'ecmascript',
     'harmony',
     'ponyfill',
     'prollyfill',
     'polyfill',
     'shim',
     'browser' ],
  devDependencies: { mocha: '*' },
  gitHead: '02622dcb0d82bd81a071ed0b04fedf5e5eea7059',
  bugs: { url: 'https://github.com/sindresorhus/object-assign/issues' },
  homepage: 'https://github.com/sindresorhus/object-assign',
  dist:
   { shasum: '9bedd5ca0897949bca47e7ff408062d549f587f2',
     tarball: 'http://build-npm.mo.sap.corp:8080/object-assign/-/object-assign-3.0.0.tgz' },
  maintainers: 'sindresorhus <sindresorhus@gmail.com>',
  directories: {} }
```

**Comment by michaelficarra** [comment] 2015-06-04 16:06
Not for me:

```
$ npm view object-assign

{ name: 'object-assign',
  description: 'ES6 Object.assign() ponyfill',
  'dist-tags': { latest: '3.0.0' },
  versions:
   [ '0.1.0',
     '0.1.1',
     '0.1.2',
     '0.2.0',
     '0.2.1',
     '0.2.2',
     '0.3.0',
     '0.3.1',
     '0.4.0',
     '1.0.0',
     '2.0.0',
     '3.0.0' ],
  maintainers: 'sindresorhus <sindresorhus@gmail.com>',
  time:
   { modified: '2015-06-04T14:09:02.051Z',
     created: '2014-02-02T15:47:58.857Z',
     '0.1.0': '2014-02-02T15:47:58.857Z',
     '0.1.1': '2014-02-04T20:02:13.757Z',
     '0.1.2': '2014-02-04T21:03:17.088Z',
     '0.2.0': '2014-02-15T21:39:23.178Z',
     '0.2.1': '2014-03-24T14:06:35.136Z',
     '0.2.2': '2014-04-08T13:53:46.644Z',
     '0.3.0': '2014-04-11T22:34:55.461Z',
     '0.3.1': '2014-04-30T22:36:40.407Z',
     '0.4.0': '2014-08-13T07:47:00.902Z',
     '1.0.0': '2014-08-14T10:45:03.502Z',
     '2.0.0': '2014-11-22T03:40:09.589Z',
     '2.1.0': '2015-06-04T13:06:53.193Z',
     '3.0.0': '2015-06-04T14:09:02.051Z' },
  readmeFilename: 'readme.md',
  homepage: 'https://github.com/sindresorhus/object-assign',
  keywords:
   [ 'object',
     'assign',
     'extend',
     'properties',
     'es6',
     'ecmascript',
     'harmony',
     'ponyfill',
     'prollyfill',
     'polyfill',
     'shim',
     'browser' ],
  repository:
   { type: 'git',
     url: 'https://github.com/sindresorhus/object-assign' },
  author: 'Sindre Sorhus <sindresorhus@gmail.com> (http://sindresorhus.com)',
  bugs: { url: 'https://github.com/sindresorhus/object-assign/issues' },
  license: 'MIT',
  users:
   { steindaniel: true,
     levisl176: true,
     ivanoats: true,
     '9joneg': true,
     schnittstabil: true,
     alexkval: true,
     antouank: true,
     'crees!': true,
     phuson: true,
     markthethomas: true,
     qqqppp9998: true },
  version: '3.0.0',
  engines: { node: '>=0.10.0' },
  scripts: { test: 'mocha' },
  files: 'index.js',
  devDependencies: { mocha: '*' },
  gitHead: '02622dcb0d82bd81a071ed0b04fedf5e5eea7059',
  dist:
   { shasum: '9bedd5ca0897949bca47e7ff408062d549f587f2',
     tarball: 'http://registry.npmjs.org/object-assign/-/object-assign-3.0.0.tgz' },
  directories: {} }

$
```
