### ISSUE TITLE
JSON formatter "source" attribute should focus on relevant lines

### ISSUE THREAD

**Issue by MVrachev** [eslint/eslint#11362] opened 2019-02-07 12:32 UTC
**Tell us about your environment**

* **ESLint Version:** 5.12.0
* **Node Version:** 11.9.0
* **npm Version:** 6.5.0

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
/**
 * Save a file to a specific location and create required directories
 * @param {string} filePath path to file relative to main directory
 * @param {string} data file contents
 */
function writeFileCreateDirs (filePath, data) {
  fs.mkdirpSync(path.dirname(filePath))
  fs.writeFileSync(filePath, data)
}
```

```bash
node_modules/.bin/eslint --format=json -o=eslint_result.json cache.js
```

**What did you expect to happen?**
I want an understandable and short JSON formatted output.

**What actually happened? Please include the actual, raw output from ESLint.**
In the eslint_result.json I have this content when I console.log it:

![image](https://user-images.githubusercontent.com/16246778/52411715-5eed5400-2ae5-11e9-997e-1af06f876753.png)

I think it will much more useful if every single issue contains its JSON attribute called "filePath" and in the source attribute is not the whole file but instead the problematic line or problematic block.

**Are you willing to submit a pull request to fix this bug?**

Yes, but maybe I will need help.

**Comment by not-an-aardvark** [comment] 2019-02-08 01:52
Hi, thanks for the proposal.

This is working as intended -- we include the entire source file in info provided to formatters/JSON output because some formatters and integrations use the info to display context around a reported problem. We intentionally decided not to truncate the file because we would rather let integrations decide how much context they want to provide for their use case.

I think the mismatch here is that you mentioned you want "want an understandable and short JSON formatted output", but the `json` formatter isn't really designed with human readability as a primary goal. Have you tried using one of the human-readable formatters like `codeframe` instead?

**Comment by MVrachev** [comment] 2019-02-08 06:54
Yes, I know that the JSON format is used to access that data with a programming language, it's just that the JSON format is so overcrowded because of this source filed.

Okay, then can you give us an option to use little context?
Although the JSON format main purpose is not to be readable by humans I think you can make it readable and for humans and keep the main idea behind the JSON format.
Like the example you give here: https://eslint.org/docs/developer-guide/working-with-custom-formatters#the-results-object 
![image](https://user-images.githubusercontent.com/16246778/52463288-04a0d180-2b7f-11e9-8fab-0aa079a529be.png)

instead of this: https://eslint.org/docs/user-guide/formatters/#json
![image](https://user-images.githubusercontent.com/16246778/52463339-31ed7f80-2b7f-11e9-9f42-c221c3653b6a.png)

**Comment by g-plane** [comment] 2019-02-08 07:10
You can create a custom formatter if you want.

**Comment by MVrachev** [comment] 2019-02-08 08:20
Yes, but why the default JSON format in ESlint has to be non-readable?

And okay, if there is no fix for the readability of the JSON format then at least give us a flag in the command line interface for the source attribute.
A flag which when is up/true we get only the context between the start line (it's the line attribute) and the endLine attribute.

**Comment by g-plane** [comment] 2019-02-08 08:27
There is source location information in each linting report. With this, you can located the problem. If you are curious how to do, it's recommended to see the source code of ["codeframe"](https://github.com/eslint/eslint/blob/master/lib/formatters/codeframe.js).

**Comment by not-an-aardvark** [comment] 2019-02-08 08:27
I think we don't put whitespace in the JSON output in order to reduce the amount of memory it takes up for very large linting results.

I'm still a bit confused about your use case. Could you clarify what you're trying to accomplish, and how having the JSON be readable/omitting the `source` property would be helpful for that? Again, if you want readable output there are several other formatters that are better-suited to making the output human-readable.

**Comment by MVrachev** [comment] 2019-02-08 08:59
I am developing an app called Precaution: https://github.com/vmware/precaution
and I am using ESlint underneath. With ESlint, I generate the output from it in a JSON file. The annoying thing is that this "source" attribute is soo big in the JSON format that the generated files are abnormally big.

Also, another use case is when I use ESlint on the command line. Then there I would prefer to see the filed "source" in every single issue and the content in it to be only the problematic lines. 
This applies not only to the JSON format but the other formats as well. If there is more context to the problem in the command line that would be useful.
If you give this flag as an option the other formats can benefit from that.

I know that many others will prefer the other way but I am sure I am not the only preferring different organization of the output.

**Comment by g-plane** [comment] 2019-02-08 09:12
For the first question, you can use the Node.js API of ESLint. It may be complex but you can gain a free control of ESLint. If you really feel hard to use that Node.js API, you can create a custom formatter and customize what you want, it's easier than the Node.js API of ESLint.

For the second question, it's recommended to use the bulit-in formatter "codeframe" or an external formatter like [`eslint-formatter-beauty`](https://github.com/g-plane/eslint-formatter-beauty).

**Comment by MVrachev** [comment] 2019-02-08 09:40
Okay, thanks for the information. I will investigate those options.

**Comment by nzakas** [comment] 2019-02-18 16:53
As this is a question rather than an action item, I'm closing the issue. If you still need help, please send a message to our [mailing list](https://groups.google.com/group/eslint) or [chatroom](https://gitter.im/eslint/eslint). Thanks!

**Closed by nzakas** 2019-02-18 16:53 UTC
Labels: question
