### ISSUE TITLE
eslint --fix with dot-location breaks code

### ISSUE THREAD

**Issue by nightpool** [eslint/eslint#11868] opened 2019-06-21 20:28 UTC
* **ESLint Version: 5.16.0**
* **Node Version: 8.1.4**
* **npm Version: 6.7.0**

[ESLint playground link](https://eslint.org/demo/#eyJ0ZXh0IjoiLyplc2xpbnQgZG90LWxvY2F0aW9uOiBbXCJlcnJvclwiLCBcIm9iamVjdFwiXSovXG5cbnZhciBmb28gPSAoXG4gIGNvbmQxID09IHRydWUgJiZcbiAgY29uZDJmdW5jKClcbikudG9TdHJpbmcoKTsiLCJvcHRpb25zIjp7InBhcnNlck9wdGlvbnMiOnsiZWNtYVZlcnNpb24iOjUsInNvdXJjZVR5cGUiOiJzY3JpcHQiLCJlY21hRmVhdHVyZXMiOnt9fSwicnVsZXMiOnsiY29uc3RydWN0b3Itc3VwZXIiOjIsImZvci1kaXJlY3Rpb24iOjIsImdldHRlci1yZXR1cm4iOjIsIm5vLWNhc2UtZGVjbGFyYXRpb25zIjoyLCJuby1jbGFzcy1hc3NpZ24iOjIsIm5vLWNvbXBhcmUtbmVnLXplcm8iOjIsIm5vLWNvbmQtYXNzaWduIjoyLCJuby1jb25zb2xlIjoyLCJuby1jb25zdC1hc3NpZ24iOjIsIm5vLWNvbnN0YW50LWNvbmRpdGlvbiI6Miwibm8tY29udHJvbC1yZWdleCI6Miwibm8tZGVidWdnZXIiOjIsIm5vLWRlbGV0ZS12YXIiOjIsIm5vLWR1cGUtYXJncyI6Miwibm8tZHVwZS1jbGFzcy1tZW1iZXJzIjoyLCJuby1kdXBlLWtleXMiOjIsIm5vLWR1cGxpY2F0ZS1jYXNlIjoyLCJuby1lbXB0eSI6Miwibm8tZW1wdHktY2hhcmFjdGVyLWNsYXNzIjoyLCJuby1lbXB0eS1wYXR0ZXJuIjoyLCJuby1leC1hc3NpZ24iOjIsIm5vLWV4dHJhLWJvb2xlYW4tY2FzdCI6Miwibm8tZXh0cmEtc2VtaSI6Miwibm8tZmFsbHRocm91Z2giOjIsIm5vLWZ1bmMtYXNzaWduIjoyLCJuby1nbG9iYWwtYXNzaWduIjoyLCJuby1pbm5lci1kZWNsYXJhdGlvbnMiOjIsIm5vLWludmFsaWQtcmVnZXhwIjoyLCJuby1pcnJlZ3VsYXItd2hpdGVzcGFjZSI6Miwibm8tbWl4ZWQtc3BhY2VzLWFuZC10YWJzIjoyLCJuby1uZXctc3ltYm9sIjoyLCJuby1vYmotY2FsbHMiOjIsIm5vLW9jdGFsIjoyLCJuby1yZWRlY2xhcmUiOjIsIm5vLXJlZ2V4LXNwYWNlcyI6Miwibm8tc2VsZi1hc3NpZ24iOjIsIm5vLXNwYXJzZS1hcnJheXMiOjIsIm5vLXRoaXMtYmVmb3JlLXN1cGVyIjoyLCJuby11bmRlZiI6Miwibm8tdW5leHBlY3RlZC1tdWx0aWxpbmUiOjIsIm5vLXVucmVhY2hhYmxlIjoyLCJuby11bnNhZmUtZmluYWxseSI6Miwibm8tdW5zYWZlLW5lZ2F0aW9uIjoyLCJuby11bnVzZWQtbGFiZWxzIjoyLCJuby11bnVzZWQtdmFycyI6Miwibm8tdXNlbGVzcy1lc2NhcGUiOjIsInJlcXVpcmUteWllbGQiOjIsInVzZS1pc25hbiI6MiwidmFsaWQtdHlwZW9mIjoyfSwiZW52Ijp7fX19)

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
/*eslint dot-location: ["error", "object"]*/

var foo = (
  cond1 == true &&
  cond2func()
).toString();
```

```bash
eslint --fix
```

**What did you expect to happen?**

No change to file

**What actually happened? Please include the actual, raw output from ESLint.**

```js
/*eslint dot-location: ["error", "object"]*/

var foo = (
  cond1 == true &&
  cond2func().
)toString();
```

As you can see, this code doesn't even parse. `eslint --fix` should never break correctness and certainly shouldn't ever output something that fails to parse.

**Comment by nightpool** [comment] 2019-06-21 20:29
This is also an issue on 5.15.3

**Comment by platinumazure** [comment] 2019-06-21 21:13
Hi @nightpool, thanks for the issue.

My guess is we're not adequately taking the parentheses into account. The ESTree spec defines the object node as ending just after `cond2func()` in your example. If the lint rule places the dot "after the object node", then it won't work correctly. Instead, it should place it "after the previous token before the dot", which should account for the parentheses.

I would bet a similar bug exists if the property is surrounded by parentheses and the lint rule is configured to attach the dot to the property. It may place the dot "before the property node" rather than "before the next token after the dot".

If I'm correct, whoever works on a fix for this should make sure they don't accidentally pick up a comment token in the updated fixer logic.

**Comment by mdjermanovic** [comment] 2019-06-29 02:22
I'd like to work on this, of course if the issue is going to be accepted  (guess it will, because fix produces syntax error).

> 
> My guess is we're not adequately taking the parentheses into account. The ESTree spec defines the object node as ending just after `cond2func()` in your example. If the lint rule places the dot "after the object node", then it won't work correctly. Instead, it should place it "after the previous token before the dot", which should account for the parentheses.
> 

This part of the fix works exactly as you described, and should be corrected to work exactly as you said.

> I would bet a similar bug exists if the property is surrounded by parentheses and the lint rule is configured to attach the dot to the property. It may place the dot "before the property node" rather than "before the next token after the dot".

It takes the first token before the property, then safely checks if it is really a dot punctuator, and gives up if it isn't. So there would be no reports and no fixes. Regardless of the options, the node is completely ignored if the first non-comment token before the property node is not the dot.

This is actually very helpful at the moment, given the fact that the code never checks the `computed` flag (I believe this check should be added before anything else).

Apart from the `!computed`, perhaps it would be better to leave this part as is, at least for now? I don't think there is a single possible case of a non-comment token between the dot and the property in current js (parentheses are not a problem, `a.(b)` is not valid syntax), proposals (e.g. `#x` would be all in the property, `?.` is on the left side and it would be a new expression type anyway), typescript or any code that uses `babel-eslint`. And if really something unexpected comes between, the node will be simply ignored (and perhaps it should be).

**Comment by platinumazure** [comment] 2019-07-03 14:06
I've [reproduced the issue on the ESLint demo](https://eslint.org/demo/#eyJ0ZXh0IjoiLyplc2xpbnQgZG90LWxvY2F0aW9uOiBbXCJlcnJvclwiLCBcIm9iamVjdFwiXSwgbm8tdW5kZWY6IG9mZiAqL1xyXG5cclxudmFyIGZvbyA9IChcclxuICBjb25kMSA9PSB0cnVlICYmXHJcbiAgY29uZDJmdW5jKClcclxuKS50b1N0cmluZygpOyIsIm9wdGlvbnMiOnsicGFyc2VyT3B0aW9ucyI6eyJlY21hVmVyc2lvbiI6OSwic291cmNlVHlwZSI6InNjcmlwdCIsImVjbWFGZWF0dXJlcyI6e319LCJydWxlcyI6eyJuby11bmRlZiI6Mn0sImVudiI6e319fQ==), so I'm marking this as accepted. Thanks @nightpool for the bug report!

**Closed** 2019-07-21 03:06 UTC
Labels: accepted, bug, rule
