### ISSUE TITLE
Proposed new rule: wrong-quotes-for-template-string

### ISSUE THREAD

**Issue by BigstickCarpet** [eslint/eslint#6186] opened 2016-05-15 18:51 UTC
**When does this rule warn? Please describe and show example code:**
This rule would warn when a string appears to use ES6 template string variable substitution, but isn't using a backtick quotes.  The goal is to eliminate an easy code mistake, such as the following:

**This code would warn:**
```javascript
let name = "John Doe";             // <--- This is a normal string (not a template string)
let greeting = "Hello, ${name}";   // <--- This is ALSO a normal string, but the coder 
                                   //      probably meant for it to be a template string
```

**This code would _not_ warn:**
```javascript
let name = "John Doe";             // <--- This is a normal string (not a template string)
let greeting = `Hello, ${name}`;   // <--- This is a template string
```

**Is this rule preventing an error or is it stylistic?**
This rule aims to prevent a common ES6 coding mistake.  It's easy to mistakenly use the wrong quotes (e.g. double-quotes instead of backticks) for a template string.  When this happens, the code lints and runs perfectly fine, but at runtime, the string value will contain the raw `"${name}"` rather than the variable value `"John Doe"`.

**Why is this rule a candidate for inclusion instead of creating a custom rule?**
This is a rule that would benefit everybody who is using ES6 template strings.  It's not limited to a specific framework or platform.

**Are you willing to create the rule yourself?**
Maybe.  Not sure how hard it would be.

**Comment by nzakas** [comment] 2016-05-15 19:33
Duplicate of https://github.com/eslint/eslint/issues/5850

**Comment by BigstickCarpet** [comment] 2016-05-15 19:43
Damn.  I searched to make sure I wasn't creating a duplicate issue, but forgot to search _closed_ issues.

So, since #5850 has been closed, does that mean this rule won't get implemented?  Or is there still a chance?  I know it's a bit anecdotal, but I've seen this mistake bite myself and some other devs on my team quite a few times.

**Comment by mysticatea** [comment] 2016-05-15 20:49
I will give :+1: for this.
There are 5 issues (#6143, #5408, #5376, #4286, #2170) about this in this repo, and my coworker also had this mistake before.
Plus, autofixing for this is usefull to me. I cannot modify both quotes by one step.

**Comment by nzakas** [comment] 2016-05-16 15:34
Okay, we need a champion and two more 👍 

@BigstickCarpet if accepted, we will ask you to try to implement it yourself (see http://eslint.org/docs/developer-guide/contributing/new-rules#implementation-is-your-responsibility for details). The core team just doesn't have the time to implement every rule that is suggested.

**Comment by jfmengels** [comment] 2016-06-15 12:03
I'm willing to implement the rule if this gets accepted.

**Comment by ilyavolodin** [comment] 2016-06-15 14:24
I'll support this. Seems like a good rule to have. 👍

**Comment by nzakas** [comment] 2016-06-15 19:13
I'll give a :+1: but we still need a champion to shepherd this through the process.

**Comment by platinumazure** [comment] 2016-07-19 16:47
I might be willing to implement this if we can find a champion.`

**Comment by mysticatea** [comment] 2016-07-25 13:12
I'm a champion. (and we need one more :+1:)

**Comment by nzakas** [comment] 2016-07-25 18:19
Looks like @michaelficarra have a 👍 On the issue, so marking as accepted.

**Comment by ljharb** [comment] 2016-07-25 18:22
Hooray, glad this is finally going to be added :-D

**Comment by platinumazure** [comment] 2016-07-26 00:57
Ah, I didn't see @jfmengels' comment earlier. Still want to implement? I'm out of town for a week so I won't try to stake a claim here :smile:

**Comment by jfmengels** [comment] 2016-07-26 07:03
> Still want to implement?

Yes :) I'll try to take a stab at it tonight.

**Closed** 2016-08-09 00:57 UTC
Labels: accepted, feature, rule
