### ISSUE TITLE
(no-useless-escape) Error. RegEx Lint giving error when no error should be given.

### ISSUE THREAD

**Issue by MarcGodard** [eslint/eslint#11168] opened 2018-12-07 14:38 UTC
`/^[^src="]((?:https?:\/\/)+[a-z\-_0-9\/:.]*\.(?:jpg|jpeg|png|gif))/gi` causes the error (no-useless-escape). It's the 2nd escape here -> `[a-z\-_0-9\/:.]`

However, fixing that error cause the regEx to stop working because that escape is needed.
`/^[^src="]((?:https?:\/\/)+[a-z\-_0-9/:.]*\.(?:jpg|jpeg|png|gif))/gi`

I am at a loss as to what is going on. My regex skills are not great, but everything says mine is fine.

**Comment by platinumazure** [comment] 2018-12-07 14:45
This is working as designed. That forward slash escape is indeed unnecessary in a character class, according to the ECMAScript spec.

If a particular runtime environment is breaking with the forward slash unescaped, that is a bug in that environment.

If you really have no choice but to leave in the escape, you should use [disable comments](https://eslint.org/docs/user-guide/configuring#disabling-rules-with-inline-comments) to suppress the rule error.

**Comment by ilyavolodin** [comment] 2018-12-09 04:16
Closing as this is working as intended.

**Closed by ilyavolodin** 2018-12-09 04:16 UTC
Labels: works as intended
