### ISSUE TITLE
Change Request: (Allow silently ignoring explicitly passed files)

### ISSUE THREAD

**Issue by flying-sheep** [eslint/eslint#15288] opened 2021-11-11 12:15 UTC
### ESLint version

v8.2.0

### What problem do you want to solve?

Tools like pre-commit run ESLint by passing a list of changed files.

This results in ESLint complaining with

> `0:0 warning File ignored because of a matching ignore pattern. Use "--no-ignore" to override`

When not run manually, this warning is spurious: People shouldn’t have to configure their ignore list twice.

It’s hard to solve this from `pre-commit`’s side, since it would have to call into ESLint’s internal ignore mechanism to manipulate the list of files.

### What do you think is the correct solution?

There should be a way to run ESLint so it silently ignores when passed file paths that are ignored.

That way tools can just pass a list of files they’re interested in (e.g. changed files) and ESLint will care about its ignore configuration.

### Participation

- [ ] I am willing to submit a pull request for this change.

### Additional comments

Some context here: https://github.com/pre-commit/mirrors-eslint/issues/33

**Comment by nzakas** [comment] 2021-11-12 01:49
Duplicate of https://github.com/eslint/eslint/issues/15010

**Closed by nzakas** 2021-11-12 01:49 UTC
Labels: enhancement, triage, core
