### ISSUE TITLE
TypeError: Cannot read property 'range' of null

### ISSUE THREAD

**Issue by JeromeLin** [eslint/eslint#10544] opened 2018-06-30 01:22 UTC
**Tell us about your environment**

* **ESLint Version:**4.19.1
* **Node Version:**8.11.3
* **npm Version:**5.6.0
* **yarn Version:**1.7.0

**What parser (default, Babel-ESLint, etc.) are you using?**
babel-eslint

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
{
  "extends": ["za"],
  "parser": "babel-eslint",
  "env": {
    "browser": true,
    "node": true,
    "jest": true,
    "es6": true
  }
}

```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

my project: https://github.com/ZhonganTechENG/zarm

```bash
eslint --ext '.js,.jsx' examples examples-rn
```

**What did you expect to happen?**
after installing with yarn, the execution command is error, and the npm install is fine.

**What actually happened? Please include the actual, raw output from ESLint.**
> eslint --ext '.js,.jsx' examples examples-rn

Cannot read property 'range' of null
TypeError: Cannot read property 'range' of null
    at SourceCode.getTokenBefore (/Users/linji/Documents/workspace/zarm/node_modules/eslint/lib/token-store/index.js:303:18)
    at checkSpacingBefore (/Users/linji/Documents/workspace/zarm/node_modules/eslint/lib/rules/template-curly-spacing.js:52:42)
    at TemplateElement (/Users/linji/Documents/workspace/zarm/node_modules/eslint/lib/rules/template-curly-spacing.js:117:17)
    at listeners.(anonymous function).forEach.listener (/Users/linji/Documents/workspace/zarm/node_modules/eslint/lib/util/safe-emitter.js:47:58)
    at Array.forEach (<anonymous>)
    at Object.emit (/Users/linji/Documents/workspace/zarm/node_modules/eslint/lib/util/safe-emitter.js:47:38)
    at NodeEventGenerator.applySelector (/Users/linji/Documents/workspace/zarm/node_modules/eslint/lib/util/node-event-generator.js:251:26)
    at NodeEventGenerator.applySelectors (/Users/linji/Documents/workspace/zarm/node_modules/eslint/lib/util/node-event-generator.js:280:22)
    at NodeEventGenerator.enterNode (/Users/linji/Documents/workspace/zarm/node_modules/eslint/lib/util/node-event-generator.js:294:14)
    at CodePathAnalyzer.enterNode (/Users/linji/Documents/workspace/zarm/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:608:23)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zarm@1.2.0-beta.32 lint:js: `eslint --ext '.js,.jsx' examples examples-rn`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the zarm@1.2.0-beta.32 lint:js script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/linji/.npm/_logs/2018-06-30T01_03_55_804Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zarm@1.2.0-beta.32 lint: `npm run lint:ts && npm run lint:js && npm run lint:style`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the zarm@1.2.0-beta.32 lint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/linji/.npm/_logs/2018-06-30T01_03_55_831Z-debug.log

**Comment by not-an-aardvark** [comment] 2018-06-30 01:58
Closing as a duplicate of https://github.com/eslint/eslint/issues/9872

**Closed by not-an-aardvark** 2018-06-30 01:58 UTC
Labels: triage
