### ISSUE TITLE
Disable rules for given identifiers

### ISSUE THREAD

**Issue by tlvince** [eslint/eslint#2620] opened 2015-05-27 09:12 UTC
Is it possible to disable rules for given identifiers? For example, in CouchDB projects, I'm forced to scatter `/*eslint-disable no-underscore-dangle */` comments on every instance of `_id` or `_rev` as I'd otherwise like to keep this rule enabled globally.

Could this be part of a rule's configuration? Perhaps:

```yml
rules:
  no-underscore-dangle:
    - 2
    - disable:
      - _id
      - _rev
```

**Comment by lo1tuma** [comment] 2015-05-27 09:54
Looks like a duplicate of #2135.

**Comment by ilyavolodin** [comment] 2015-05-27 13:55
Closing in favor of #2135

**Closed by ilyavolodin** 2015-05-27 13:55 UTC
Labels: question
