### ISSUE TITLE
support config sets for file matches

### ISSUE THREAD

**Issue by jasonkuhrt** [eslint/eslint#7887] opened 2017-01-08 01:36 UTC
```
❯ eslint --version
v3.12.2
```

ESLint current has [configuration cascading](http://eslint.org/docs/user-guide/configuring#configuration-cascading-and-hierarchy) which is useful when e.g. your test code has different lint standards than your source code. However this assumes that folders are used to group distinct sets of eslint configurations. If instead I want to co-locate tests with source code in my tree:

```
/source
  Foo.js
  Foo.spec.js
  Bar.js
  Bar.spec.js
  ...
```

then I can no longer use configuration cascading to manage my different lint standards.

A solution to this limitation could be a new top-level configuration field for creating configuration sets particular to a glob pattern. For example in .eslint.yaml:

```
files-matching:
  ./**/*.spec.js:
    ...      
```

Or maybe use regex instead of glob patterns:

```
files-matching:
  .*\.spec\.js:
    ...      
```

Thanks for your consideration!

**Comment by gyandeeps** [comment] 2017-01-08 02:38
possible duplicate of https://github.com/eslint/eslint/issues/3611 , if I understand it correctly.

**Closed** 2017-01-08 12:04 UTC
Labels: triage

**Comment by jasonkuhrt** [comment] 2017-01-09 03:30
@gyandeeps Perfect yep. Pardon the noise.
