### ISSUE TITLE
Bug: indent rule expects argument not to be indented if it comes after a multiline array

### ISSUE THREAD

**Issue by guillaumebrunerie** [eslint/eslint#15792] opened 2022-04-20 14:56 UTC
### Environment

Node version: v17.3.0
npm version: v8.3.0
Local ESLint version: v8.13.0 (Currently used)
Global ESLint version: Not found
Operating System: darwin 19.6.0

### What parser are you using?

Default (Espree)

### What did you do?

With the `indent` option, ESLint reports wrong indentation for `b` in `foo`, but not in `bar`.

```js
var foo = f([
    a,
],
    b
);

var bar = f(a,
    b
);
```
[Demo link](https://eslint.org/demo#eyJ0ZXh0IjoidmFyIGZvbyA9IGYoW1xuICAgIGEsXG5dLFxuICAgIGJcbik7XG5cbnZhciBiYXIgPSBmKGEsXG4gICAgYlxuKTsiLCJvcHRpb25zIjp7InBhcnNlck9wdGlvbnMiOnsiZWNtYVZlcnNpb24iOiJsYXRlc3QiLCJzb3VyY2VUeXBlIjoic2NyaXB0IiwiZWNtYUZlYXR1cmVzIjp7fX0sInJ1bGVzIjp7ImNvbnN0cnVjdG9yLXN1cGVyIjoyLCJmb3ItZGlyZWN0aW9uIjoyLCJnZXR0ZXItcmV0dXJuIjoyLCJuby1hc3luYy1wcm9taXNlLWV4ZWN1dG9yIjoyLCJuby1jYXNlLWRlY2xhcmF0aW9ucyI6Miwibm8tY2xhc3MtYXNzaWduIjoyLCJuby1jb21wYXJlLW5lZy16ZXJvIjoyLCJuby1jb25kLWFzc2lnbiI6Miwibm8tY29uc3QtYXNzaWduIjoyLCJuby1jb25zdGFudC1jb25kaXRpb24iOjIsIm5vLWNvbnRyb2wtcmVnZXgiOjIsIm5vLWRlYnVnZ2VyIjoyLCJuby1kZWxldGUtdmFyIjoyLCJuby1kdXBlLWFyZ3MiOjIsIm5vLWR1cGUtY2xhc3MtbWVtYmVycyI6Miwibm8tZHVwZS1lbHNlLWlmIjoyLCJuby1kdXBlLWtleXMiOjIsIm5vLWR1cGxpY2F0ZS1jYXNlIjoyLCJuby1lbXB0eSI6Miwibm8tZW1wdHktY2hhcmFjdGVyLWNsYXNzIjoyLCJuby1lbXB0eS1wYXR0ZXJuIjoyLCJuby1leC1hc3NpZ24iOjIsIm5vLWV4dHJhLWJvb2xlYW4tY2FzdCI6Miwibm8tZXh0cmEtc2VtaSI6Miwibm8tZmFsbHRocm91Z2giOjIsIm5vLWZ1bmMtYXNzaWduIjoyLCJuby1nbG9iYWwtYXNzaWduIjoyLCJuby1pbXBvcnQtYXNzaWduIjoyLCJuby1pbm5lci1kZWNsYXJhdGlvbnMiOjIsIm5vLWludmFsaWQtcmVnZXhwIjoyLCJuby1pcnJlZ3VsYXItd2hpdGVzcGFjZSI6Miwibm8tbG9zcy1vZi1wcmVjaXNpb24iOjIsIm5vLW1pc2xlYWRpbmctY2hhcmFjdGVyLWNsYXNzIjoyLCJuby1taXhlZC1zcGFjZXMtYW5kLXRhYnMiOjIsIm5vLW5ldy1zeW1ib2wiOjIsIm5vLW5vbm9jdGFsLWRlY2ltYWwtZXNjYXBlIjoyLCJuby1vYmotY2FsbHMiOjIsIm5vLW9jdGFsIjoyLCJuby1wcm90b3R5cGUtYnVpbHRpbnMiOjIsIm5vLXJlZGVjbGFyZSI6Miwibm8tcmVnZXgtc3BhY2VzIjoyLCJuby1zZWxmLWFzc2lnbiI6Miwibm8tc2V0dGVyLXJldHVybiI6Miwibm8tc2hhZG93LXJlc3RyaWN0ZWQtbmFtZXMiOjIsIm5vLXNwYXJzZS1hcnJheXMiOjIsIm5vLXRoaXMtYmVmb3JlLXN1cGVyIjoyLCJuby11bmV4cGVjdGVkLW11bHRpbGluZSI6Miwibm8tdW5yZWFjaGFibGUiOjIsIm5vLXVuc2FmZS1maW5hbGx5IjoyLCJuby11bnNhZmUtbmVnYXRpb24iOjIsIm5vLXVuc2FmZS1vcHRpb25hbC1jaGFpbmluZyI6Miwibm8tdW51c2VkLWxhYmVscyI6Miwibm8tdXNlbGVzcy1iYWNrcmVmZXJlbmNlIjoyLCJuby11c2VsZXNzLWNhdGNoIjoyLCJuby11c2VsZXNzLWVzY2FwZSI6Miwibm8td2l0aCI6MiwicmVxdWlyZS15aWVsZCI6MiwidXNlLWlzbmFuIjoyLCJ2YWxpZC10eXBlb2YiOjIsImluZGVudCI6Mn0sImVudiI6e319fQ==)

### What did you expect to happen?

I don’t think that `b` in `foo` violates the `indent` rule, it is an argument of `foo` on a new line and should therefore be indented with one level of indentation, just like in `bar`. I would expect no error in the code above.

### What actually happened?

ESLint expects `b` in `foo` not to be indented.

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by mdjermanovic** [comment] 2022-04-20 22:05
Hi @guillaumebrunerie, thanks for the issue!

The rule expects this:

> ```js
> var foo = f([
>     a,
> ],
> b
> );
> ```

I think this works as intended. The first argument (the array) is multiline and it starts on the same line as `var foo`, so it should end with the same indentation as `var foo`, which is `0` in this example. Other arguments should be aligned with the first one, so it seems correct that their indentation is also `0`, while the array elements are +1 level.

Consider the following example, this is what the `indent` rule expects when the first argument is another function call:

```js
var foo = f(g(
    a,
),
b
);
```

If the rule works as in the example with an array, the expected indentation would be:

```js
var foo = f(g(
    a,
),
    b
);
```

`a` and `b` would be on the same level, but that doesn't seem right because `a` is an argument of an inner function call, so it should be +1 level.

**Comment by nzakas** [comment] 2022-04-22 00:47
This is one of those tricky situations where the right choice programmatically doesn’t align with perception. These multi line indentation schemes are always going to be a point of disagreement, and here I think it’s doing the right thing.

**Comment by mdjermanovic** [comment] 2022-06-22 00:26
Closing since we think this works as intended.

**Closed by mdjermanovic** 2022-06-22 00:26 UTC
Labels: works as intended
