### ISSUE TITLE
no error on non-existent files

### ISSUE THREAD

**Issue by piotr-s-brainhub** [eslint/eslint#9362] opened 2017-09-27 16:00 UTC
* ESLint Version: 3.19.0
* eslint-config-airbnb-base Version: 8.0.0
* Node Version: 8.1.2
* npm Version: 5.4.2

**What parser (default, Babel-ESLint, etc.) are you using?**
default

**Please show your full configuration:**
```json
{
  "extends": "airbnb-base"
}
```

**What did you do?**

I run `eslint` on a non-existent file:
`./node_modules/.bin/eslint foo`

(it's a simplification, to be frankly, I run it on a result of `git ls-files | grep '\\.js$'` which returned colored output which `eslint` treated as different file names)

**What did you expect to happen?**
I expected `eslint` to return a non-zero exit code.

**What actually happened?**
It returned 0 exit code.

**Comment by not-an-aardvark** [comment] 2017-09-27 16:04
Thanks for the report. This is working as intended -- see https://github.com/eslint/eslint/pull/7395.

**Comment by not-an-aardvark** [comment] 2017-10-24 08:29
Closing because this is working as intended.

**Closed by not-an-aardvark** 2017-10-24 08:29 UTC
Labels: works as intended
