### ISSUE TITLE
Named import is read as a single import

### ISSUE THREAD

**Issue by lacsinagramar** [eslint/eslint#14259] opened 2021-03-26 17:05 UTC
**Tell us about your environment**

* **ESLint Version: 7.22.0**
* **Node Version: 12.18.3**
* **npm Version: 6.14.6**
* **Operating System: Windows** 

**What parser (default, `@babel/eslint-parser`, `@typescript-eslint/parser`, etc.) are you using?**
I am using `@typescript-eslint/parser`

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
{
  "env": {
    "browser": true,
    "es6": true,
    "node": true,
    "jest": true
  },
  "extends": ["plugin:@typescript-eslint/recommended", "prettier"],
  "globals": {
    "Atomics": "readonly",
    "SharedArrayBuffer": "readonly",
    "graphql": false
  },
  "parser": "@typescript-eslint/parser",
  "parserOptions": {
    "ecmaVersion": 2018,
    "sourceType": "module"
  },
  "plugins": ["prettier", "react"],
  "rules": {
    "prettier/prettier": "error",
    "linebreak-style": ["error", "unix"],
    "quotes": ["error", "single"],
    "semi": ["error", "never"],
    "@typescript-eslint/explicit-function-return-type": 0,
    "@typescript-eslint/interface-name-prefix": 0,
    "@typescript-eslint/camelcase": 0,
    "@typescript-eslint/no-parameter-properties": 0,
    "@typescript-eslint/no-explicit-any": 0,
    "sort-imports": [
      "error",
      {
        "ignoreCase": true,
        "ignoreDeclarationSort": false,
        "ignoreMemberSort": false,
        "memberSyntaxSortOrder": ["all", "single", "multiple", "none"],
        "allowSeparatedGroups": true
      }
    ]
  }
}
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
import React from 'react'
import { Box } from '@material-ui/core'
import { makeStyles } from '@material-ui/styles'
import { createMuiTheme, MuiThemeProvider, Theme, ThemeOptions } from '@material-ui/core/styles'
```

I am using VSCode ESLint

**What did you expect to happen?**
I am expecting `import { Box } from '@material-ui/core'` to be read as `multiple` import since it's using named imports

**What actually happened? Please copy-paste the actual, raw output from ESLint.**
`import { Box } from '@material-ui/core'` is read as a single import which leads to ESLint giving me `imports should be sorted alphabetically` cause `Box` comes before `React`

**Steps to reproduce this issue:**

1. Use the same `sort-imports` rule I use.
1. Import a named import under a default import unalphabetically

**Are you willing to submit a pull request to fix this bug?**
Yes, but not sure how ESLint code works

**Comment by mdjermanovic** [comment] 2021-03-29 17:07
Hi @lacsinagramar, thanks for the issue!

This works as intended. Per the [documentation](https://eslint.org/docs/rules/sort-imports#options):

> * `multiple` = import multiple members.
> * `single` = import single member.

I think that options like `"named"` and `"default"` would make more sense than `"multiple"` and `"single"`, but given that the stylistic rules are frozen (please find more details in [this blog post](https://eslint.org/blog/2020/05/changes-to-rules-policies)) we won't be adding new options to this rule, so this looks like a good case for a plugin.

**Closed by mdjermanovic** 2021-03-29 17:07 UTC
Labels: works as intended
