### ISSUE TITLE
`@Param` with a capitol P causes Error: Cannot read property 'indexOf' of undefined

### ISSUE THREAD

**Issue by tgolen** [eslint/eslint#6145] opened 2016-05-11 22:10 UTC
**What version of ESLint are you using?**
2.9.0

**What parser (default, Babel-ESLint, etc.) are you using?**
Default

**Please show your full configuration:**
```
{
    "extends": "airbnb",

    "env": {
        "browser": true,
        "node": true,
        "jquery": true,
        "es6": true
    },

    "rules": {
        "camelcase": 0,
        "comma-dangle": 0,
        "consistent-return": 0,
        "consistent-this": [1, "self"],
        "func-names": 0,
        "import/no-unresolved": 0,
        // Enforce indentation of 4 spaces
        "indent": [2, 4],
        "max-len": [1, {
            "code": 120
        }],
        "no-alert": 0,
        "object-curly-spacing": [2, "never"],
        "prefer-template": 1,
        // Require space before function opening parenthesis
        "space-before-function-paren": [2, {
            "anonymous": "always",
            "named": "never"
        }],
        "strict": [0],
        "valid-jsdoc": [2, {
            "requireParamDescription": false,
            "requireReturnDescription": false,
            "requireReturn": false
        }],
        // This enforces wrapping always the function expression.
        "wrap-iife": [2, "inside"],

        // eslint-plugin-react
        //
        // React specific rules for ESLint.
        //
        // Do not prevent multiple component definition per file
        "react/no-multi-comp": 0,
        // Do not prevent missing React when using JSX
        "react/react-in-jsx-scope": 0,
        "react/jsx-indent-props": [2, 4],
        "react/jsx-indent": [2, 4],
        "react/prefer-es6-class": 1,

        // The following rules are actually supposed to be errors but we decided to
        // switch them to warnings to not invalidate our current codebase. We should
        // still try to get rid of these modifications at some point and turn them
        // back in to errors.
        //
        "new-cap": [1, {"newIsCap": true}],
        "no-param-reassign": 1,
        "no-underscore-dangle": 1,
        "no-unused-vars": 1,
        "no-var": 1
    },

    "ecmaFeatures": {
        "generators": true,
        "objectLiteralDuplicateProperties": true,
        "experimentalObjectRestSpread": true
    }
}
```
**What did you do? Please include the actual source code causing the issue.**

Code causing the error:
```js
    /**
     * Performs API command 
     *
     * @param {Object} parameters
     * @param {Object} parameters.reportID 
     * @Param {Object} parameters.bankAccountID from.
     * @return {APIDeferred}
     */
```

**What did you expect to happen?**
I expected the linter to pass, but kept getting this error that didn't indicate what the issue might be.

**What actually happened? Please include the actual, raw output from ESLint.**

```
Error: Cannot read property 'indexOf' of undefined
TypeError: Cannot read property 'indexOf' of undefined
    at /Users/.../node_modules/eslint/lib/rules/valid-jsdoc.js:273:48
    at Array.forEach (native)
    at EventEmitter.checkJSDoc (/Users/.../node_modules/eslint/lib/rules/valid-jsdoc.js:256:28)
    at emitOne (events.js:82:20)
    at EventEmitter.emit (events.js:169:7)
    at NodeEventGenerator.leaveNode (/Users/.../node_modules/eslint/lib/util/node-event-generator.js:49:22)
    at CodePathAnalyzer.leaveNode (/Users/.../node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:627:23)
    at CommentEventGenerator.leaveNode (/Users/.../node_modules/eslint/lib/util/comment-event-generator.js:110:23)
    at Controller.traverser.traverse.leave (/Users/.../node_modules/eslint/lib/eslint.js:889:36)
    at Controller.__execute (/Users/.../node_modules/eslint/node_modules/estraverse/estraverse.js:397:31)
```

After some deduction, I was able to determine that the root case was `@Param` as opposed to `@param`

**Comment by ilyavolodin** [comment] 2016-05-11 22:32
Looks like a bug that we should fix. It's not OK for rules to ever throw.

**Comment by kaicataldo** [comment] 2016-05-12 04:04
Was able to reproduce locally. Is `@Param` legal syntax for JSDoc? If so, this looks to me like this might be an issue with doctrine itself, as a `name` property is not attached to the parsed `@Param` tag, but is with the lowercase `@param` tag. Regardless, agreed with @ilyavolodin, some kind of guard should be in place to prevent the rule from throwing.

**Comment by kaicataldo** [comment] 2016-05-12 04:05
<img width="1006" alt="screen shot 2016-05-12 at 12 05 26 am" src="https://cloud.githubusercontent.com/assets/7041728/15203819/453da454-17d5-11e6-9e1a-dbc96aef62b3.png">

**Comment by kaicataldo** [comment] 2016-05-12 04:18
Seems to be similar to https://github.com/eslint/eslint/issues/6121. In both cases, changing the first character of the tag from lowercase to uppercase results in missing properties that the valid-jsdoc rule is expecting. Changing the characters back to lowercase fixes the issue. My hunch is that this is occurring in Doctrine itself, though I'm unsure if capitalized tag names are valid JSDoc or not.

**Comment by alberto** [comment] 2016-05-12 19:11
Closing since it's a duplicate of #6121

**Closed by alberto** 2016-05-12 19:11 UTC
Labels: accepted, bug, rule
