### ISSUE TITLE
no-fallthrough inconsistent comment behavior

### ISSUE THREAD

**Issue by reviewher** [eslint/eslint#8570] opened 2017-05-08 19:30 UTC
**Tell us about your environment**

* **ESLint Version:** v3.19.0
* **Node Version:** v7.9.0
* **npm Version:** 4.5.0

**What parser (default, Babel-ESLint, etc.) are you using?** default

**Please show your full configuration:**

```json
{
	"env": { "shared-node-browser":true },
	"globals": {},
	"parserOptions": {
		"ecmaVersion": 3,
	},
	"plugins": [ "html", "json" ],
	"extends": "eslint:recommended",
	"rules": {
		"no-use-before-define": [ 1, {
			"functions":false, "classes":true, "variables":false
		}],
		"no-console": 0,
		"no-bitwise": 0,
		"curly": 0,
		"comma-style": [ 2, "last" ],
		"no-trailing-spaces": 2,
		"semi": [ 2, "always" ],
		"comma-dangle": [ 2, "never" ]
	}
}
```

**What did you do? Please include the actual source code causing the issue.**

```js
switch(1) {
  case 2: /* innocuous comment */
  case 3:
    /* offending comment */
  case 4:
	/* falls through */
  case 5: /* innocuous comment */
    /* falls through */
  case 6: /* innocuous comment */
    /* innocuous comment */
    /* falls through */
  case 7: /* innocuous comment */
    /* falls through */
    /* offending comment */
  case 8:
    break;
}
```

**What did you expect to happen?** the behavior is not defined in http://eslint.org/docs/rules/no-fallthrough, but intuitively I would expect either all comments to trigger errors or no comments 

**What actually happened? Please include the actual, raw output from ESLint.**

something inconsistent.  Lines 5 and 15 show `Expected a 'break' statement before 'case'.`  This can be verified in the demo http://eslint.org/demo/

Given the lack of documentation, I'm not sure if the behavior has been clearly defined yet, but it appears that the logic is to disregard comments on the same line as the case statement and honor the `falls through` comment only if it appears directly before the next case.

Since the behavior is not clearly defined in the documentation, I would propose disregarding comments when determining whether a fall through comment is needed (no errors in the example above).  line-level annotations like flow's suppress comment feature (https://flow.org/en/docs/config/options/#toc-suppress-comment-regex) would require this.  Note: the modifier is specifically intended to target the following source line, whereas "falls through" really describes an expectation for the previous block, so logically it would make sense to allow comments after the "falls through".  (we happen to use this pattern in places including http://github.com/SheetJS/js-xlsx/blob/master/bits/62_fxls.js#L967)

**Comment by not-an-aardvark** [comment] 2018-03-05 18:03
Sorry about the delayed response. However, I think this is working as intended and there hasn't been any activity on this issue for a long time, so I'm closing it. Feel free to open a new issue if you'd like to propose a change to the rule.

**Closed by not-an-aardvark** 2018-03-05 18:03 UTC
Labels: evaluating, question, rule
