### ISSUE TITLE
Change Request: Make Linter export browser-compatible 

### ISSUE THREAD

**Issue by milohansen** [eslint/eslint#18715] opened 2024-07-24 20:53 UTC
### ESLint version

v9.7.0

### What problem do you want to solve?

In the Node.js API Reference ([link](https://eslint.org/docs/latest/integrate/nodejs-api)), it is stated that to lint code in the browser, users should use the `Linter` class.

When importing `Linter` code paths that rely on `fs` are hit and the import/bundling fails.

The eslint playground uses a hack to import the linter by directly referencing `node_modules` ([link](https://github.com/eslint/eslint.org/blob/6d8a97d79fc5c2b37821a33d5a817e1ca14864af/src/playground/App.js#L14)).

### What do you think is the correct solution?

I propose adding a new export to `package.json` that links directly to the linter to enable use in the browser.

### Participation

- [X] I am willing to submit a pull request for this change.

**Comment by fasttime** [comment] 2024-07-25 08:48
Thanks for the report @milohansen. I think I understand the problem you are describing here, but for clarity, it would be helpful if you could show an example of what you are trying to do including the bundler setup and the error you are getting.

Just to point out the obvious, browsers don't have package resolution like Node.js does, so unless you are using a bundler, you would import `Linter` exactly like the Playground does, by the relative URL of its module (in this particular case, I also think it was a _hack_).

**Comment by milohansen** [comment] 2024-08-02 21:16
Sure thing! Here's a simple repro of the issue in a Vite app on StackBlitz: [link](https://stackblitz.com/edit/vitejs-vite-n8cyce?file=src%2FlintCode.ts)

It has a simplified linter in `lintCode.ts` which is called by `App.tsx`.
```typescript
import js from "@eslint/js";
import { Linter } from "eslint";

const linter = new Linter();

export function lintCode(code: string) {
  return linter.verify(code, js.configs.recommended);
}
```

The code compiles thanks to Vite's externalization of Node modules but fails to run and throws the following error int he console:

![image](https://github.com/user-attachments/assets/c1d111e9-56e3-45b6-8cb7-1e1e97927e9d)

The line I marked in green shows that the bundle is attempting to load `api.js` which requires Node APIs to function.

---

I believe that if the change I'm suggesting is made, line 2 of `lintCode.ts` can be changed to `import { Linter } from "eslint/linter";` and Vite (or other bundlers) will be able to resolve that path and avoid including Node dependent files.

**Comment by fasttime** [comment] 2024-09-02 14:44
Thanks for the repro @milohansen and sorry for the delay. So, the problem is that it's not possible to import `Linter` from the main exported module [lib/api.js](https://github.com/eslint/eslint/blob/main/lib/api.js) in a browser environment because that module assumes the existence of APIs that are only available in Node.js (for example `node:fs`).

The proposed solution consists in adding a new entry to the `exports` mappings in `package.json` to export just the `Linter`. @eslint/eslint-team thoughts about this suggestion?

**Comment by mdjermanovic** [comment] 2024-09-02 15:44
I'm also okay with it, and I agree we should use a more generic name that would allow us to add more to it in the future.

Maybe `universal`, like in [`@eslint/eslintrc`](https://github.com/eslint/eslintrc/blob/fc9837d3c4eb6c8c97bd5594fb72ea95b6e32ab8/package.json#L13-L16)?

**Comment by JoshuaKGoldberg** [comment] 2024-09-02 17:07
👍 `universal` sounds good to me. In general, this sounds like it'd be good for any kind of runtime that doesn't have Node-specific `fs`: browsers, Deno/Bun _(ignoring their mostly-complete compatibility layers)_, maybe even edge workers or the like.

**Comment by fasttime** [comment] 2024-09-02 21:08
It seems that we have consensus to add a new subpath export to expose `Linter`, and potentially more APIs later. We will only need to agree on the most appropriate name for that, so marking as accepted.

@milohansen are you still interested in submitting a PR for this change?

**Comment by nzakas** [comment] 2024-09-03 14:28
I think `universal` makes sense, as @mdjermanovic mentioned.

**Comment by aladdin-add** [comment] 2024-09-10 09:01
I was under the impression that eslint does not **officially** support browser environments. `Linter` being exported seems to be more of a gray area - it was used on eslint's official website. Does adding this export mean we're going to change that strategy?

I'm not against this change, but I bring it up because I want us to be able to evaluate the impact of this change in its entirety - because modern bundlers (e.g. vite.js, webpack v5, rollup) no longer bundle node.js core modules by default, which means that eslint (including its dependencies, e.g. espree, eslint-scope) can no longer use them.

**Comment by aladdin-add** [comment] 2024-09-10 09:12
I'm slightly more inclined to keep as it was - something like `use-at-your-own-risks`, than officially supporting. thoughts?🤔

**Comment by aladdin-add** [comment] 2024-09-11 03:47
right, I'll send a PR.

**Closed** 2024-09-18 14:59 UTC
Labels: enhancement, core, accepted, repro:yes
