### ISSUE TITLE
TypeError: this.cliEngine is not a constructor

### ISSUE THREAD

**Issue by Viciky** [eslint/eslint#11957] opened 2019-07-06 04:03 UTC
**Tell us about your environment**

* **ESLint Version: v6.0.1
* **Node Version: v10.13.0
* **npm Version: v6.4.1

**What parser (default, Babel-ESLint, etc.) are you using?**

**Please show your full configuration:**
module.exports = {
  parser: '@typescript-eslint/parser',
  extends: [
    'airbnb',
    'prettier',
    'prettier/@typescript-eslint',
    'plugin:compat/recommended',
    'plugin:@typescript-eslint/recommended',
  ],
  plugins: ['@typescript-eslint'],
  env: {
    browser: true,
    node: true,
    es6: true,
    mocha: true,
    jest: true,
    jasmine: true,
  },
  globals: {
    APP_TYPE: true,
    __ALIYUN_ENV__: true,
    WODAX_APP_NAME: true,
    page: true,
  },
  rules: {
    /// for base 配置
    'linebreak-style': 0,
    'no-unused-vars': 0,
    'no-param-reassign': 0,
    'no-underscore-dangle': 0,

    /// for compat
    'compat/compat': 0,

    /// for import 配置
    'import/no-cycle': 0,
    'import/no-unresolved': [2, { ignore: ['^@/', '^umi/', '^./', '^../', '^.', '^..'] }],
    'import/no-extraneous-dependencies': [
      'warn',
      {
        optionalDependencies: true,
        devDependencies: [
          '**/tests/**(.js,.jsx,.ts,.tsx)',
          '**/e2e/**(.js,.jsx,.ts,.tsx)',
          '/mock/**/**(.js,.jsx,.ts,.tsx)',
          '**/**.test.(.js,.jsx,.ts,.tsx)',
        ],
      },
    ],

    /// for jsx-a11y 配置
    'jsx-a11y/no-noninteractive-element-interactions': 0,
    'jsx-a11y/click-events-have-key-events': 0,
    'jsx-a11y/no-static-element-interactions': 0,
    'jsx-a11y/anchor-is-valid': 0,
    "jsx-a11y/label-has-for": [ 2, {          /// for < esLint@^6.1.0
      "components": [ "Label" ],
      "required": {
        "every": [ "nesting", "id" ]
      },
      "allowChildren": false
    }],
    'jsx-a11y/label-has-associated-control': [ /// for esLint@^6.1.0
      2,
      {
        labelComponents: ['CustomInputLabel'],
        labelAttributes: ['label'],
        controlComponents: ['CustomInput'],
        depth: 3,
      },
    ],

    /// for react/jsx 配置
    'react/jsx-filename-extension': [
      1,
      { extensions: ['.js', '.jsx', '.tsx'] },
    ],
    'react/jsx-wrap-multilines': 0,
    'react/jsx-boolean-value': 0,
    'react/prop-types': 0,
    'react/forbid-prop-types': 0,
    'react/jsx-no-bind': 0,
    'react/jsx-one-expression-per-line': 0,
    'react/jsx-tag-spacing': [1, { beforeSelfClosing: 'always' }],

    // ==> @typescript-eslint 配置
    '@typescript-eslint/indent': 0,
    '@typescript-eslint/interface-name-prefix': 0,
    '@typescript-eslint/explicit-member-accessibility': 0,
    '@typescript-eslint/no-explicit-any': 0,
    '@typescript-eslint/explicit-function-return-type': 0,
    '@typescript-eslint/no-unused-vars': 0,
    '@typescript-eslint/camelcase': 0,
  },
  settings: {
    polyfills: ['fetch', 'promises', 'url', 'object-assign'],
  },
};

<details>
<summary>Configuration</summary>

```js

```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js

```

```bash

```

**What did you expect to happen?**

**What actually happened? Please include the actual, raw output from ESLint.**

**Are you willing to submit a pull request to fix this bug?**

**Comment by angelikatyborska** [comment] 2019-07-08 08:27
I am experiencing this error as well, in my IDE.

I use RubyMine, and after updating ESLint from 5.16.0 to 6.0.1, RubyMine's built in support for ESLint no longer works throwing this error.

Running ESlint from the command line, e.g. via `./node_modules/.bin/eslint -c .eslintrc.js  'js/**/*.js'` still works as expected.

Of course I don't expect the ESlint team to be responsbile for how JetBrains uses your library, but I thought I will still mention the issue just in case it's really a bug.

<img width="717" alt="Screenshot 2019-07-08 at 10 20 30" src="https://user-images.githubusercontent.com/7852553/60794531-42277c00-a16a-11e9-8ba3-fbcad6391208.png">

When I click on "details", I get this error log:
```
TypeError: this.cliEngine is not a constructor

TypeError: this.cliEngine is not a constructor
    at ESLintPlugin.invokeESLint (/Applications/RubyMine.app/Contents/plugins/JavaScriptLanguage/languageService/eslint/bin/eslint-plugin.js:97:25)
    at ESLintPlugin.getErrors (/Applications/RubyMine.app/Contents/plugins/JavaScriptLanguage/languageService/eslint/bin/eslint-plugin.js:76:21)
    at ESLintPlugin.onMessage (/Applications/RubyMine.app/Contents/plugins/JavaScriptLanguage/languageService/eslint/bin/eslint-plugin.js:42:29)
    at Interface.<anonymous> (/Applications/RubyMine.app/Contents/plugins/JavaScriptLanguage/jsLanguageServicesImpl/js-language-service.js:105:39)
    at Interface.emit (events.js:189:13)
    at Interface._onLine (readline.js:290:10)
    at Interface._normalWrite (readline.js:433:12)
    at Socket.ondata (readline.js:149:10)
    at Socket.emit (events.js:189:13)
    at addChunk (_stream_readable.js:284:12)
Process finished with exit code -1
```

Here is the content of `/Applications/RubyMine.app/Contents/plugins/JavaScriptLanguage/languageService/eslint/bin/eslint-plugin.js`:
```js
"use strict";
var __assign = (this && this.__assign) || function () {
    __assign = Object.assign || function(t) {
        for (var s, i = 1, n = arguments.length; i < n; i++) {
            s = arguments[i];
            for (var p in s) if (Object.prototype.hasOwnProperty.call(s, p))
                t[p] = s[p];
        }
        return t;
    };
    return __assign.apply(this, arguments);
};
exports.__esModule = true;
var ESLintResponse = /** @class */ (function () {
    function ESLintResponse() {
    }
    return ESLintResponse;
}());
var FileKind;
(function (FileKind) {
    FileKind["js"] = "js";
    FileKind["ts"] = "ts";
    FileKind["html"] = "html";
    FileKind["vue"] = "vue";
})(FileKind || (FileKind = {}));
var ESLintPlugin = /** @class */ (function () {
    function ESLintPlugin(state) {
        this.filterSource = state.filterSource;
        this.additionalRulesDirectory = state.additionalRootDirectory;
        var packagePath = normalizePath(state.eslintPackagePath);
        this.options = require(packagePath + "lib/options");
        this.cliEngine = require(packagePath + "lib/cli-engine");
    }
    ESLintPlugin.prototype.onMessage = function (p, writer) {
        var request = JSON.parse(p);
        var response = new ESLintResponse();
        response.request_seq = request.seq;
        response.command = request.command;
        try {
            var body = void 0;
            if (request.command === ESLintPlugin.GetErrors) {
                body = this.getErrors(request.arguments);
            }
            else if (request.command === ESLintPlugin.FixErrors) {
                body = this.fixErrors(request.arguments);
            }
            if (this.filterSource == null || this.filterSource) {
                ESLintPlugin.filterSourceOut(body);
            }
            response.body = body;
        }
        catch (e) {
            response.isNoConfigFile = "no-config-found" === e.messageTemplate
                || (e.message && containsString(e.message.toString(), "No ESLint configuration found"));
            response.error = e.toString() + "\n\n" + e.stack;
        }
        writer.write(JSON.stringify(response));
    };
    ESLintPlugin.filterSourceOut = function (body) {
        for (var i = 0; i < body.length; i++) {
            var elem = body[i];
            if (elem != null) {
                if (elem.source != null)
                    elem.source = "";
                if (elem.messages != null) {
                    for (var j = 0; j < elem.messages.length; j++) {
                        var message = elem.messages[j];
                        if (message.source != null)
                            message.source = "";
                    }
                }
            }
        }
    };
    ESLintPlugin.prototype.getErrors = function (getErrorsArguments) {
        return this.invokeESLint(getErrorsArguments);
    };
    ESLintPlugin.prototype.fixErrors = function (fixErrorsArguments) {
        return this.invokeESLint(fixErrorsArguments, { fix: true });
    };
    ESLintPlugin.prototype.invokeESLint = function (requestArguments, additionalOptions) {
        if (additionalOptions === void 0) { additionalOptions = {}; }
        var parsedCommandLineOptions = translateOptions(this.options.parse(requestArguments.extraOptions || ""));
        var options = __assign({}, parsedCommandLineOptions, additionalOptions);
        options.ignorePath = requestArguments.ignoreFilePath;
        if (requestArguments.configPath != null) {
            options.configFile = requestArguments.configPath;
        }
        if (this.additionalRulesDirectory != null && this.additionalRulesDirectory.length > 0) {
            if (options.rulePaths == null) {
                options.rulePaths = [this.additionalRulesDirectory];
            }
            else {
                options.rulePaths.push(this.additionalRulesDirectory);
            }
        }
        var cliEngine = new this.cliEngine(options);
        var config = cliEngine.getConfigForFile(requestArguments.fileName);
        if (!isFileKindAcceptedByConfig(config, requestArguments.fileKind) || cliEngine.isPathIgnored(requestArguments.fileName)) {
            return { results: [], warningCount: 0, fixableWarningCount: 0, fixableErrorCount: 0, errorCount: 0 };
        }
        return cliEngine.executeOnText(requestArguments.content, requestArguments.fileName);
    };
    ESLintPlugin.GetErrors = "GetErrors";
    ESLintPlugin.FixErrors = "FixErrors";
    return ESLintPlugin;
}());
exports.ESLintPlugin = ESLintPlugin;
function isFileKindAcceptedByConfig(config, fileKind) {
    var plugins = config.plugins;
    function hasPlugin(toCheck) {
        return plugins != null && plugins
            .filter(function (value) { return value == toCheck || value == "eslint-plugin-" + toCheck; }).length > 0;
    }
    function hasParser(parser) {
        return (config.parser != null && containsString(normalizePath(config.parser), parser))
            || (config.parserOptions != null && parser == config.parserOptions["parser"]);
    }
    if (fileKind === FileKind.ts) {
        return hasPlugin("typescript") || hasParser("babel-eslint") || hasParser("typescript-eslint-parser")
            || hasParser("@typescript-eslint/parser");
    }
    if (fileKind === FileKind.html) {
        return hasPlugin("html");
    }
    if (fileKind === FileKind.vue) {
        return (
        //eslint-plugin-html used to process .vue files prior to v5
        hasPlugin("html") ||
            //eslint-plugin-vue in plugins used to be enough to process .vue files prior to v3
            hasPlugin("vue") ||
            hasParser("vue-eslint-parser"));
    }
    return true;
}
function containsString(src, toFind) {
    return src != null && src.indexOf(toFind) >= 0;
}
function normalizePath(eslintPackagePath) {
    if (eslintPackagePath.charAt(eslintPackagePath.length - 1) !== '/' &&
        eslintPackagePath.charAt(eslintPackagePath.length - 1) !== '\\') {
        eslintPackagePath = eslintPackagePath + '/';
    }
    return eslintPackagePath.split("\\").join("/");
}
// taken from private part of eslint(lib/cli.js), we need it here
/**
 * Translates the CLI options into the options expected by the CLIEngine.
 * @param {Object} cliOptions The CLI options to translate.
 * @returns {CLIEngine.Options} The options object for the CLIEngine.
 * @private
 */
function translateOptions(cliOptions) {
    return {
        envs: cliOptions.env,
        extensions: cliOptions.ext,
        rules: cliOptions.rule,
        plugins: cliOptions.plugin,
        globals: cliOptions.global,
        ignore: cliOptions.ignore,
        ignorePath: cliOptions.ignorePath,
        ignorePattern: cliOptions.ignorePattern,
        configFile: cliOptions.config,
        rulePaths: cliOptions.rulesdir,
        useEslintrc: cliOptions.eslintrc,
        parser: cliOptions.parser,
        parserOptions: cliOptions.parserOptions,
        cache: cliOptions.cache,
        cacheFile: cliOptions.cacheFile,
        cacheLocation: cliOptions.cacheLocation,
        allowInlineConfig: cliOptions.inlineConfig,
        reportUnusedDisableDirectives: cliOptions.reportUnusedDisableDirectives
    };
}
//# sourceMappingURL=eslint-plugin.js.map
```

* **ESLint Version:** 6.0.1
* **Node Version:** 10.15.3
* **npm Version:** 6.9.0

**Comment by g-plane** [comment] 2019-07-08 08:30
That is, the problem is from JetBrain's ESLint plugin, not ESLint itself.

**Comment by platinumazure** [comment] 2019-07-08 14:59
To add further, JetBrains should do something like this: `this.cliEngine = require("eslint").CLIEngine;`

This is the supported public API access point for CLIEngine. We did change the path where CLIEngine was located with ESLint 6.0 but we made sure that access point continued to work.

**Comment by g-plane** [comment] 2019-07-08 15:12
Maybe we can open an issue at YouTrack.

**Comment by yozzh** [comment] 2019-07-10 13:12
Update to 2019.1.3 solves this issue.
https://intellij-support.jetbrains.com/hc/en-us/community/posts/360004195120-TypeError-this-cliEngine-is-not-a-constructor

**Comment by g-plane** [comment] 2019-07-10 13:50
Closing now since it's fixed: https://youtrack.jetbrains.com/issue/WEB-38922 .

**Closed by g-plane** 2019-07-10 13:50 UTC
Labels: question

**Comment by NongDeng** [comment] 2019-07-18 04:11
or change the eslint version to 5.16.0 with webstorm 2018.3.6

**Comment by zrbaihld** [comment] 2019-07-29 01:21
thinks

**Comment by blakedietz** [comment] 2019-08-02 22:06
> Update to 2019.1.3 solves this issue.

This fixed my issue.

**Comment by mmarquezv** [comment] 2019-08-03 16:22
> 
> 
> or change the eslint version to 5.16.0 with webstorm 2018.3.6

This solved my issue in WebStorm

**Comment by mhuguet** [comment] 2019-08-15 13:57
> To add further, JetBrains should do something like this: `this.cliEngine = require("eslint").CLIEngine;`
> 
> This is the supported public API access point for CLIEngine. We did change the path where CLIEngine was located with ESLint 6.0 but we made sure that access point continued to work.

Thanks for the tip @platinumazure. Our custom runner was using a relative path, which broke when uptaking the ESLint 6.x. I switched it to require("eslint").CLIEngine; and it worked as expected.

**Comment by ben1226q** [comment] 2019-09-20 01:22
edit this file
/Applications/WebStorm.app/Contents/plugins/JavaScriptLanguage/languageService/eslint/bin/eslint-plugin.js

// this.cliEngine = require(packagePath + "lib/cli-engine");
 this.cliEngine = require(packagePath + "lib/cli-engine").CLIEngine;

**Comment by Ma-Wen** [comment] 2019-10-08 11:19
![image](https://user-images.githubusercontent.com/44662993/66391718-76783600-ea00-11e9-841c-7dfbda7ececb.png)
change
![image](https://user-images.githubusercontent.com/44662993/66391754-93146e00-ea00-11e9-864d-fbe5c34cffee.png)
