### ISSUE TITLE
indent rule: support fat arrow class method

### ISSUE THREAD

**Issue by PaveeWong** [eslint/eslint#11646] opened 2019-04-23 02:20 UTC
**Tell us about your environment**

* **ESLint Version:** 5.16.0
* **Node Version:** v6.11.3
* **npm Version:** 3.10.10

**What parser (default, Babel-ESLint, etc.) are you using?**

Babel-ESLint

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
module.exports = { // eslint 规则文档：https://cn.eslint.org/docs/rules/
    "env": {
        "browser": true,
        "es6": true
    },
    "parser": "babel-eslint",
    "globals": {
        "Atomics": "readonly",
        "SharedArrayBuffer": "readonly"
    },
    "parserOptions": {
        "sourceType": "module"
    },
    "plugins": [
        "babel"
    ],
    "rules": {
        "indent": ["error", 4],
    }
};
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
// for example
export class A {
    constructor () {
        this.fn(); // 8 spaces before
        this.fatArrowFn(); // 8 spaces before
    }
    
    fn () {
        this.a = 1; // 8 spaces before
    }

    fatArrowFn = () => {
        this.a = 1; // 2 tabs before
    }
}
```

```bash
 ./node_modules/.bin/eslint src/
```

**What did you expect to happen?**
error detected with rule indent at `fatArrowFn` cause 2 tabs before `this.a = 1; `

**What actually happened? Please include the actual, raw output from ESLint.**
0 error

**Are you willing to submit a pull request to fix this bug?**
no

**Comment by not-an-aardvark** [comment] 2019-04-23 02:32
Closing as a duplicate of https://github.com/eslint/eslint/issues/11485.

**Closed by not-an-aardvark** 2019-04-23 02:32 UTC
Labels: bug, triage

**Comment by PaveeWong** [comment] 2019-04-23 07:55
@not-an-aardvark No changes as I add `ClassProperty` to `KNOWN_NODES`

**Comment by PaveeWong** [comment] 2019-04-23 08:24
@not-an-aardvark 

It seems that the rule cannot detect tab after space.
For example:

```
    fatArrowFn = () => {
        this.a = 1; // 4 space and then 1 tabs before the expression —— nothing happend
	this.b = 1; // 2 tabs before the expression —— detected！and error occured
    }
```

**Comment by PaveeWong** [comment] 2019-04-23 08:29
Add
`
"no-mixed-spaces-and-tabs": "error"
`
Problem Solved!
