### ISSUE TITLE
Global var that holds an iife is getting hit with the no-unused-vars

### ISSUE THREAD

**Issue by Megale** [eslint/eslint#11282] opened 2019-01-17 13:20 UTC
**Tell us about your environment**

* **ESLint Version:** v5.12.0

* **Node Version:** v10.13.0
* **npm Version:** 6.4.1

**What parser (default, Babel-ESLint, etc.) are you using?**
Custom parser.

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
module.exports = {

    "globals": {
        "assinaturaService": true,
        "sap": true,
        "jQuery": true,
        "formatter": true,
       "docPoderService ":true 


    },
    "env": {
        "browser": true,
        "es6": true
    },
    "extends": "eslint:recommended",
    "parserOptions": {
        "ecmaVersion": 2015
    },
    "rules": {
        "indent": [
            "error",
            "tab"
        ],
        "linebreak-style": [
            "error",
            "windows"
        ],
        "quotes": [
            "error",
            "single"
        ],
        "semi": [
            "error",
            "always"
        ]
    }
};

```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

In my code (browser enviromment) i create several IIFE that are used all over. I keep getting the "no-unused-vars" for them

```js
/**
 * Retorna um objeto com funções básicas para formatação e conversão de dados
 */

var docPoderService = (function () {

	'use strict';
	return {

		init
	};

	function init() {

		let documentoPoder;

		documentoPoder = {};

		documentoPoder.dataVencimento = '';
		documentoPoder.empresaAlvo = {};
		documentoPoder.instituicaoFinanceira = {};

		documentoPoder.codigoDocumentoASubstituir = '';

		documentoPoder.outorgantes = [];
		documentoPoder.gruposPoder = [];
		documentoPoder.regrasPoder = [];


		return documentoPoder;
	}

})();




```

```bash

```

**What did you expect to happen?**
I expected that by configuring "docPoderService" as a global that error should not have been identified.

**What actually happened? Please include the actual, raw output from ESLint.**
![image](https://user-images.githubusercontent.com/2500619/51321393-c74a9780-1a49-11e9-811a-ac13ed1f1c68.png)

**Comment by platinumazure** [comment] 2019-01-17 13:33
Hi @Megale, thanks for the issue.

The `no-unused-vars` rule is designed to warn when a variable is only assigned in a file without being read or exported.

If this is a script which is assigning to an implied global variable intentionally, then you should add an [`/* exported */` comment](https://eslint.org/docs/rules/no-unused-vars#exported) to indicate that fact to ESLint. This will suppress the lint message.

Unless I'm missing something, this is working as intended.

**Comment by Megale** [comment] 2019-01-17 13:43
Hi @platinumazure ,

First of all, thanks for the quick response!

Your are absolutelly right! Works like a charm.

Cheers!

**Closed** 2019-01-17 13:43 UTC
Labels: works as intended
