### ISSUE TITLE
Eslint doesn't respect `extends` value from `overrides`

### ISSUE THREAD

**Issue by Joozty** [eslint/eslint#12906] opened 2020-02-12 20:21 UTC
**Environment Info:**

Node version: v13.8.0
npm version: v6.13.6
Local ESLint version: v6.8.0 (Currently used)
Global ESLint version: Not found

**What parser (default, Babel-ESLint, etc.) are you using?**
I am trying to use typescript parser (all `.ts`, `.tsx` files) along with esprima parser (`*.config.js` files).

**Source code:**
<details>

**.eslintrc.js**
```js
module.exports = {
    root: true,
    parser: '@typescript-eslint/parser',
    extends: [
        'plugin:@typescript-eslint/recommended',
    ],
    overrides: [
        {
            parser: 'esprima',
            parserOptions: {
                ecmaVersion: 5,
                sourceType: 'module',
            },
            plugins: [],
            extends: [
                'eslint:recommended',
            ],
            files: ['*.config.js'],
            env: {
                browser: false,
                node: true,
            },
        },
    ],
};
```

**example.config.js**
```js
const path = require('path')
path.extname('index.html');
```

**package.json**
```js
{
  "name": "test",
  "version": "1.0.0",
  "description": "",
  "main": "example.config.js",
  "scripts": {
    "lint": "eslint --ext .js,.jsx,.ts,.tsx ."
  },
  "dependencies": {
    "@typescript-eslint/eslint-plugin": "^2.19.2",
    "@typescript-eslint/parser": "^2.19.2",
    "eslint": "^6.8.0",
    "typescript": "^3.7.5"
  }
}
```
</details>

**What did you do?**
I just ran lint command and expected no errors to occur.

```bash
npm run lint
```

More precisely I expected that `extends` value from `overrides` in eslint config would replace `plugin:@typescript-eslint/recommended` with `eslint:recommended` for `*.config.js` files.

**What actually happened? Please include the actual, raw output from ESLint.**
It looks like rules from `plugin:@typescript-eslint/recommended` are applied on `example.config.js` file even when it is overridden.
```
/.../Documents/test/example.config.js
  1:14  error  Require statement not part of import statement  @typescript-eslint/no-var-requires

✖ 1 problem (1 error, 0 warnings)
```

**Are you willing to submit a pull request to fix this bug?**
Perhaps not.

Thanks for looking into this. 🙂

**Comment by kaicataldo** [comment] 2020-02-16 21:08
This looks like it's working as intended to me. `overrides` are merged into the top-level config, so it's best to think of the top-level config as defaults that apply to everything being linted.

I'd recommend doing this:

```js
module.exports = {
    root: true,
    overrides: [
        {
            files: ['*.ts', "*.tsx"],
            parser: '@typescript-eslint/parser',
            extends: [
                'plugin:@typescript-eslint/recommended',
            ],
        },
        {
            parser: 'esprima',
            parserOptions: {
                ecmaVersion: 5,
                sourceType: 'module',
            },
            plugins: [],
            extends: [
                'eslint:recommended',
            ],
            files: ['*.config.js'],
            env: {
                browser: false,
                node: true,
            },
        },
    ],
};
```

Also, is using `esprima` intentional? The default parser is called `espree`, and if you do what I suggested about you won't need to specify it :)

**Comment by Joozty** [comment] 2020-02-17 17:18
Ok then. I didn't expect it got merged. I thought it would completely replace the value.

@kaicataldo Thanks for the explanation. 

PS:
> Also, is using esprima intentional? The default parser is called espree, and if you do what I suggested about you won't need to specify it :)

Nope. It's not. I just wanted to specify some parser to be sure `@typescript-eslint/parser` was not used.

**Closed** 2020-02-17 17:18 UTC
Labels: works as intended
