### ISSUE TITLE
The "strict": [2, "global"] rule doesn't parse

### ISSUE THREAD

**Issue by koistya** [eslint/eslint#1906] opened 2015-02-28 21:53 UTC
#### .eslintrc

```json
{
  "parser": "babel-eslint",
  "env": {
    "browser": true,
    "node": true
  },
  "rules": {
    "strict": [2, "global"]
  }
}
```

#### Error

```
.\node_modules\eslint\lib\rules\strict.js:33
    for (i = 0; i < statements.length; i++) {
                              ^
TypeError: Cannot read property 'length' of undefined
    at getUseStrictDirectives (.\eslint\lib\rules\strict.js:33:31)
    at EventEmitter.modes.global.FunctionExpression (.\eslint\lib\rules\strict.js:178:20)
    at EventEmitter.emit (events.js:129:20)
    at Controller.controller.traverse.enter (.\eslint\lib\eslint.js:683:25)
    at Controller.__execute (.\eslint\node_modules\estraverse\estraverse.js:397:31)
    at Controller.traverse (.\eslint\node_modules\estraverse\estraverse.js:495:28)
    at EventEmitter.module.exports.api.verify (.\eslint\lib\eslint.js:676:24)
    at processFile (.\eslint\lib\cli-engine.js:172:23)
    at .\eslint\lib\cli-engine.js:271:26
    at .\eslint\lib\util\traverse.js:61:17
```

Windows OS, ESLlint 0.15.1, babel-eslint 1.0.12

**Comment by btmills** [comment] 2015-02-28 22:01
What are the contents of the file you were linting when the error occurred? Without that information we can't reproduce the error. If there were multiple files being linted when ESLint crashed, enable debug logging by prefixing the command with `DEBUG=eslint:cli-engine`. For example: `DEBUG=eslint:cli-engine eslint src/`.

**Comment by koistya** [comment] 2015-02-28 22:11
I'm also using `babel-eslint`, maybe, that's somehow related?

**Comment by koistya** [comment] 2015-02-28 22:13
You can try this project to reproduce: https://github.com/kriasoft/react-starter-kit Just add `"strict": [2, "global"` to its `.eslintrc` config file.

**Comment by koistya** [comment] 2015-02-28 22:20
This error doesn't appear if I try to lint a single files, but only when I run `eslint src`.

**Comment by btmills** [comment] 2015-02-28 22:21
What version of ESLint are you using? `eslint -v`

**Comment by koistya** [comment] 2015-02-28 22:22
Windows OS, ESLlint 0.15.1, babel-eslint 1.0.12

**Comment by btmills** [comment] 2015-02-28 22:45
This is an issue with babel-eslint. Moved to babel/babel-eslint#20.

**Comment by nzakas** [comment] 2015-03-06 02:01
Closing since this is a compatibility issue with babel-eslint

**Closed by nzakas** 2015-03-06 02:01 UTC
Labels: question, rule
