### ISSUE TITLE
[BUG] max-len not working properly.

### ISSUE THREAD

**Issue by HRK44** [eslint/eslint#9293] opened 2017-09-12 13:32 UTC
**Tell us about your environment**

* **ESLint Version:** v4.6.1
* **Node Version:** v4.8.1
* **npm Version:** v2.15.11

**What parser (default, Babel-ESLint, etc.) are you using?**

default

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
{
	"env": {
		"node": true
	},
	"globals": {},
	"rules": {
		"no-bitwise": 2,
		"curly": [
			2,
			"all"
		],
		"eqeqeq": 2,
		"no-extend-native": 2,
		"wrap-iife": 2,
		"no-use-before-define": [
			2,
			{
				"functions": false
			}
		],
		"new-cap": 2,
		"no-caller": 2,
		"no-empty": 2,
		"no-irregular-whitespace": 2,
		"no-new": 2,
		"quotes": [
			2,
			"single"
		],
		"no-undef": 0,
		"no-unused-vars": 2,
		// "strict": [
		// 	2,
		// 	"safe"
		// ],
		"max-params": [
			2,
			6
		],
		"max-depth": [
			2,
			5
		],
		"max-statements": [
			2,
			70
		],
		"complexity": [
			2,
			15
		],
		"keyword-spacing": [
			2,
			{}
		],
		"space-before-function-paren": [
			2,
			"never"
		],
		"space-before-blocks": [
			2,
			"always"
		],
		"one-var": [
			2,
			"never"
		],
		"space-in-parens": [
			2,
			"never"
		],
		"space-unary-ops": [
			2,
			{
				"words": false,
				"nonwords": false
			}
		],
		"space-infix-ops": 2,
		"no-implicit-coercion": [
			2,
			{
				"boolean": true,
				"string": true,
				"number": true
			}
		],
		"linebreak-style": [
			2,
			"unix"
		],
		"indent": [
			2,
			4,
			{
				"SwitchCase": 1
			}
		],
		"no-multiple-empty-lines": 2,
		"no-mixed-spaces-and-tabs": 2,
		"no-trailing-spaces": 2,
		"eol-last": 2,
		"dot-notation": 2,
		"valid-jsdoc": [2,
			{
				"requireParamDescription": false,
				"requireReturn": false,
				"requireReturnDescription": false
			}
		],
		"operator-linebreak": [
			2,
			"after"
		],
		"camelcase": [
			2,
			{
				"properties": "always"
			}
		],
		"no-multi-str": 2,
		"brace-style": [
			2,
			"stroustrup",
			{
				"allowSingleLine": true
			}
		],
		"max-len": [
			2,
			{
				"code": 100,
				"ignoreStrings": true,
				"ignoreRegExpLiterals": true
			}
		]
	}
}
```

</details>

**What did you do? Please include the actual source code causing the issue.**

```js
                    $scope.overview.totalText =
                                $filter('translate')
                                ('settings.maintenance.license.overview.totalText',
                                {
                                    current : $scope.overview.features.cal.currentInstalledDevices,
                                    total : $scope.overview.features.cal.totalCalDevices
                                });
```
![eslint-issue-1](https://user-images.githubusercontent.com/7391040/30328327-4380549c-97cf-11e7-9eac-2c003582e20c.png)

As you can see, the vertical line on the right indicates the 100 character mark, so the line 31 is actually 99 characters long.

**What did you expect to happen?**

No error for rule 'max-len' since it is set at 100 and the line is 99 characters long.
Here is the Hexa from the file, 99bytes :

![eslint-issue-2](https://user-images.githubusercontent.com/7391040/30328386-7973342a-97cf-11e7-8595-31347d71f0d9.png)

**What actually happened? Please include the actual, raw output from ESLint.**

![eslint-issue-3](https://user-images.githubusercontent.com/7391040/30328305-3707b138-97cf-11e7-93cf-ab3115086f36.png)

**Comment by platinumazure** [comment] 2017-09-12 14:25
Hi @HRK44, thanks for the issue!

I [can't reproduce this](https://eslint.org/demo/#eyJ0ZXh0IjoiLyogZXNsaW50IG1heC1sZW46IFsyLCB7IFwiY29kZVwiOiAxMDAsIFwiaWdub3JlU3RyaW5nc1wiOiB0cnVlLCBcImlnbm9yZVJlZ0V4cExpdGVyYWxzXCI6IHRydWUgfV0gKi9cclxuXHJcbiAgICAgICAgICAgICAgICAgICAgJHNjb3BlLm92ZXJ2aWV3LnRvdGFsVGV4dCA9XHJcbiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgJGZpbHRlcigndHJhbnNsYXRlJylcclxuICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAoJ3NldHRpbmdzLm1haW50ZW5hbmNlLmxpY2Vuc2Uub3ZlcnZpZXcudG90YWxUZXh0JyxcclxuICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICB7XHJcbiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIGN1cnJlbnQgOiAkc2NvcGUub3ZlcnZpZXcuZmVhdHVyZXMuY2FsLmN1cnJlbnRJbnN0YWxsZWREZXZpY2VzLFxyXG4gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICB0b3RhbCA6ICRzY29wZS5vdmVydmlldy5mZWF0dXJlcy5jYWwudG90YWxDYWxEZXZpY2VzXHJcbiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgfSk7Iiwib3B0aW9ucyI6eyJwYXJzZXJPcHRpb25zIjp7ImVjbWFWZXJzaW9uIjo1LCJzb3VyY2VUeXBlIjoic2NyaXB0IiwiZWNtYUZlYXR1cmVzIjp7fX0sInJ1bGVzIjp7fSwiZW52Ijp7fX19) in the online demo... Am I missing something?

Maybe it might be worth running `path/to/eslint --print-config path/to/settings.maintenance.license.js` in order to double check that there isn't another configuration interfering with your specified configuration?

**Comment by HRK44** [comment] 2017-09-12 14:47
Ok I think I've found the issue, I was running ESLint through gulp :

![eslint-issue-5](https://user-images.githubusercontent.com/7391040/30332079-c529cd7a-97d9-11e7-9268-128165075bb6.png)

As you can see, it was running with the `--fix` option, so basically ESLint was fixing the indentation problem by adding 4 spaces (31:1   error  Expected indentation of 40 spaces but found 36  indent) which in return was breaking the other rule of 100 characters long line.

What best practice do you suggest for me in this case?

Thanks

**Comment by not-an-aardvark** [comment] 2017-09-17 01:59
One option would be to apply the autofixes to the original file in addition to the fixture location. That way, the errors wouldn't be confusing because the original source file would also have more than 100 characters.

**Comment by HRK44** [comment] 2017-09-18 10:11
Isn't that the default behavior of the `--fix` option (modify the original file)? Or am I missing something? Thanks for your answers

**Comment by ilyavolodin** [comment] 2017-09-27 03:26
@HRK44 Unfortunately, there is no autofixer for max-len rule, so you will have to fix those errors manually by hands. That's really the only option available.

**Comment by not-an-aardvark** [comment] 2017-10-24 08:30
Closing because this is working as intended.

**Closed by not-an-aardvark** 2017-10-24 08:30 UTC
Labels: question
