### ISSUE TITLE
prefer-const should autofix, but it didn't

### ISSUE THREAD

**Issue by Aladdin-ADD** [eslint/eslint#10582] opened 2018-07-09 14:57 UTC
```js
let acorn = require("acorn"),
    assert = require("chai").assert;
```
to
```js
const acorn = require("acorn"),
    assert = require("chai").assert;
```

**Comment by platinumazure** [comment] 2018-07-09 15:16
I think we [already have autofix](https://github.com/eslint/eslint/blob/master/lib/rules/prefer-const.js#L354) in this rule. There are some conditions that prevent autofix.

Is there a particular use case that you think should be autofixed, but that isn't being autofixed?

**Comment by kaicataldo** [comment] 2018-07-11 14:19
This feels more like an enhancement to me (the current behavior isn’t wrong—it could just be made smarter). But either way, seems like a good addition to make the change @platinumazure suggested.

**Comment by sstern6** [comment] 2018-10-15 04:38
Would it be ok to take a look at this?

**Comment by sstern6** [comment] 2018-10-15 18:12
Looking into this, as @platinumazure said the rule guards against autofixing multiple variable declarations found: https://github.com/eslint/eslint/blob/master/lib/rules/prefer-const.js#L324.  How does it sound to update the logic of the rule to if there are multiple declarations that are ALL require statements to allow autofixing?  To avoid changing the rule too much, and I think that in some situations having the dev decide how to split up the declarations is a good idea.

Does this sound ok?

**Comment by kaicataldo** [comment] 2018-10-15 18:16
@sstern6 Can you clarify how `require`s factor into this? I'd be hesitant to add functionality that only affects assignments that are `require`s, since this rule should really only care about reassignment.

**Comment by sstern6** [comment] 2018-10-15 18:33
Sure, maybe I misunderstood, but for example.  Currently this code errors out but isnt autofixed because the rule checks the length of the block and says if there are multiple declarations then let the dev decide how to handle and eslint will not autofix.

```
let acorn = require("acorn"),
    assert = require("chai").assert;
```

Here is where I am misunderstanding, for this ticket, we want to update the rule to autofix in all cases?

My propsal was to autofix the following because all var declarations were require statements.
```
let acorn = require("acorn"),
    assert = require("chai").assert;
```

and to continue to allow devs to decide how to handle examples like the following.

```
let acorn = require("acorn"),
    assert = require("chai").assert,
    foo = 'foo';
```
or 

```
let a ='a',
    b = 'b';
```

Maybe could you clarify what the intended behavior is?

Thanks @kaicataldo

**Comment by kaicataldo** [comment] 2018-10-15 18:55
@sstern6 I think the ask here is to autofix multiple declarators (not to specifically fix assignments that are `require`s). The rule doesn't currently differentiate whether the assigned value is a `require` or not, and I don't think it should.

**Comment by kaicataldo** [comment] 2018-10-15 18:57
To provide more context, I believe the ask is to add an autofixer for the following case:
```
let a = 1,
    b = 2;
```

to 

```
const a = 1,
    b = 2;
```

instead of just warning like it does now.

Check out the [demo link](https://eslint.org/demo/#eyJ0ZXh0IjoibGV0IGFjb3JuID0gcmVxdWlyZShcImFjb3JuXCIpLFxyXG4gICAgYXNzZXJ0ID0gcmVxdWlyZShcImNoYWlcIikuYXNzZXJ0OyIsIm9wdGlvbnMiOnsicGFyc2VyT3B0aW9ucyI6eyJlY21hVmVyc2lvbiI6OSwic291cmNlVHlwZSI6InNjcmlwdCIsImVjbWFGZWF0dXJlcyI6e319LCJydWxlcyI6eyJwcmVmZXItY29uc3QiOjJ9LCJlbnYiOnt9fX0=) @Aladdin-ADD provided above to see the warnings that are generated and how the autofix doesn't fix them (when we should be able to).

**Comment by sstern6** [comment] 2018-10-15 19:02
Kk working on this.  Will have a PR over the next few days.  Thanks for the clarification.

**Closed** 2018-11-09 18:18 UTC
Labels: Hacktoberfest, accepted, bug, good first issue, help wanted, rule
