### ISSUE TITLE
Indentation level of arguments

### ISSUE THREAD

**Issue by kyleholzinger** [eslint/eslint#8056] opened 2017-02-09 18:23 UTC
**Tell us about your environment**
Sublime text/gulp for eslint
* **ESLint Version:**
3.14
* **Node Version:**
6.9.2
* **npm Version:**
3.10.9

**What parser (default, Babel-ESLint, etc.) are you using?**
default

**Please show your full configuration:**

```
{
  "env": {
    "browser": true,
    "es6": true
  },
  "plugins": ["mocha"],
  "extends": "eslint:recommended",
  "rules": {
    "indent": [
      "error",
      2
    ],
    "linebreak-style": [
      2,
      "unix"
    ],
    "no-multiple-empty-lines": [
      2,
      {"max": 1}
    ],
    "quotes": [
      2,
      "double"
    ],
    "semi": [
      2,
      "always"
    ],
    "key-spacing": [
      2,
      {
        "beforeColon": false,
        "afterColon": true
      }
    ],
    "space-infix-ops": [
      2
    ],
    "no-var": [
      1
    ],
    "mocha/no-exclusive-tests": "error"
  },
  "globals": {
    "JST": true,
    "config": true,
    "angular": true,
    "d3": true,
    "_": true,
    "$": true,
    "sinon": true,
    "beforeEach": true,
    "afterEach": true,
    "describe": true,
    "it": true,
    "module": true,
    "inject": true,
    "expect": true,
    "context": true
  }
}
```

**What did you do? Please include the actual source code causing the issue.**

```js
function test(a, b, c) {
  return a
    .match(
      {
        b: c
      }
    );
}

test();
```

**What did you expect to happen?**
The linter should pass

**What actually happened? Please include the actual, raw output from ESLint.**
When you lint this file, it says that it expects the args to be aligned with the `.match()` call. This is unintuitive, as all arguments should either be 1. be one indent level greater than their caller, or 2. be aligned with the first arguent

**Comment by not-an-aardvark** [comment] 2017-02-09 19:24
Thanks for the report. However, I'm going to close this since it's a duplicate of https://github.com/eslint/eslint/issues/7320 -- please follow that issue instead.

**Closed by not-an-aardvark** 2017-02-09 19:24 UTC
Labels: triage

**Comment by kyleholzinger** [comment] 2017-02-09 19:26
Gotya, thanks!
