### ISSUE TITLE
I am able to Write in cloud Firebase database BUT not to Read

### ISSUE THREAD

**Issue by wlaa41** [eslint/eslint#10506] opened 2018-06-22 18:38 UTC
**The version of ESLint you are using.**

**I am able to Write in cloud Firebase database BUT NOT to Read.**

**I can Write and update

       var mrwill = db.collection('scc').doc('demo')
       mrwill.update({
       roomname: "true"
       })
       .then(function() {
          return console.log("Document successfully updated!");
       })
       .catch(function(error) {
     // The document probably doesn't exist.
        return console.error("Error updating document: ", error);
     });

     mrwill = db.collection('scc').doc('demo')
     mrwill.set({ any_data:"HELLOOOOOOOO ",roomname: "true"});
    

BUT When I want to read a punch of errors show up
This is how I write it

         var testtext ;
        db.collection('scc').doc('demo').get().then( (docu) => {
        if(doc1)
       {
        testtext = doc1.id;
        }
        }).catch((err) => {

        testtext = "Error";

         });

The rules in my firebase

     service cloud.firestore {
       match /databases/{database}/documents {
         match /{document=**} {
           allow read, write;
         }
       }
     }

I am getting...

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! functions@ lint: `eslint .`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the functions@ lint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ACER PC\AppData\Roaming\npm-cache\_logs\2018-06-22T17_52_01_281Z-debug.log

Error: functions predeploy error: Command terminated with non-zero exit code1

 .**

**Comment by platinumazure** [comment] 2018-06-22 18:52
Hi @wlaa41, thanks for the issue.

Can you please show the ESLint error? You're showing the npm error.

Try running `./node_modules/.bin/eslint .` and show that output. Thanks!

**Comment by platinumazure** [comment] 2018-06-22 20:32
How did you run ESLint exactly in your test?

**Comment by wlaa41** [comment] 2018-06-22 20:42
Hi @eslintbot  

I believe it is a bug. I am able to Write and Update my data in the cloud  But Unable to read

1 -  the version is 6.1.0
2- Attached

**Comment by wlaa41** [comment] 2018-06-22 20:45
@platinumazure 
I did not quit get you 
If you want me to run a command and send you back the output just let me know

**Comment by platinumazure** [comment] 2018-06-22 20:56
I had asked you to run `./node_modules/.bin/eslint .` (note the trailing dot). However, the output you sent back is what ESLint shows if you didn't supply any arguments (e.g., `./node_modules/.bin/eslint` with no trailing dot).

Please try running `./node_modules/.bin/eslint .`, with the trailing dot, and tell me what you see.

**Comment by wlaa41** [comment] 2018-06-22 20:59
@platinumazure  

This is it....


Oops! Something went wrong! :(

ESLint: 4.19.1.
ESLint couldn't find the plugin "eslint-plugin-promise". This can happen for a couple different reasons:

1. If ESLint is installed globally, then make sure eslint-plugin-promise is also installed globally. A globally-installed ESLint cannot find a locally-installed plugin.

2. If ESLint is installed locally, then it's likely that the plugin isn't installed correctly. Try reinstalling by running the following:

    npm i eslint-plugin-promise@latest --save-dev

If you still can't figure out the problem, please stop by https://gitter.im/eslint/eslint to chat with the team.

**Comment by platinumazure** [comment] 2018-06-22 21:04
Okay, now is where we need your ESLint config. You should have an .eslintrc
(or it might have an extension like .eslintrc.json). Please find that and
paste the contents here.

At this point, though, it looks like you're trying to use
eslint-plugin-promise but haven't installed it. If that's the case, you
should install it locally by following the command in the error message
(npm install eslint-plugin-promise --save-dev).

**Comment by wlaa41** [comment] 2018-06-22 21:05
{
  "parserOptions": {
    // Required for certain syntax usages
    "ecmaVersion": 6
  },
  "plugins": [
    "promise"
  ],
  "extends": "eslint:recommended",
  "rules": {
    // Removed rule "disallow the use of console" from recommended eslint rules
    "no-console": "off",

    // Removed rule "disallow multiple spaces in regular expressions" from recommended eslint rules
    "no-regex-spaces": "off",

    // Removed rule "disallow the use of debugger" from recommended eslint rules
    "no-debugger": "off",

    // Removed rule "disallow unused variables" from recommended eslint rules
    "no-unused-vars": "off",

    // Removed rule "disallow mixed spaces and tabs for indentation" from recommended eslint rules
    "no-mixed-spaces-and-tabs": "off",

    // Removed rule "disallow the use of undeclared variables unless mentioned in /*global */ comments" from recommended eslint rules
    "no-undef": "off",

    // Warn against template literal placeholder syntax in regular strings
    "no-template-curly-in-string": 1,

    // Warn if return statements do not either always or never specify values
    "consistent-return": 1,

    // Warn if no return statements in callbacks of array methods
    "array-callback-return": 1,

    // Require the use of === and !==
    "eqeqeq": 2,

    // Disallow the use of alert, confirm, and prompt
    "no-alert": 2,

    // Disallow the use of arguments.caller or arguments.callee
    "no-caller": 2,

    // Disallow null comparisons without type-checking operators
    "no-eq-null": 2,

    // Disallow the use of eval()
    "no-eval": 2,

    // Warn against extending native types
    "no-extend-native": 1,

    // Warn against unnecessary calls to .bind()
    "no-extra-bind": 1,

    // Warn against unnecessary labels    
    "no-extra-label": 1,

    // Disallow leading or trailing decimal points in numeric literals
    "no-floating-decimal": 2,

    // Warn against shorthand type conversions
    "no-implicit-coercion": 1,

    // Warn against function declarations and expressions inside loop statements
    "no-loop-func": 1,

    // Disallow new operators with the Function object
    "no-new-func": 2,

    // Warn against new operators with the String, Number, and Boolean objects
    "no-new-wrappers": 1,

    // Disallow throwing literals as exceptions
    "no-throw-literal": 2,

    // Require using Error objects as Promise rejection reasons
    "prefer-promise-reject-errors": 2,

    // Enforce “for” loop update clause moving the counter in the right direction
    "for-direction": 2,

    // Enforce return statements in getters
    "getter-return": 2,

    // Disallow await inside of loops
    "no-await-in-loop": 2,

    // Disallow comparing against -0
    "no-compare-neg-zero": 2,

    // Warn against catch clause parameters from shadowing variables in the outer scope
    "no-catch-shadow": 1,

    // Disallow identifiers from shadowing restricted names
    "no-shadow-restricted-names": 2,

    // Enforce return statements in callbacks of array methods
    "callback-return": 2,

    // Require error handling in callbacks
    "handle-callback-err": 2,

    // Warn against string concatenation with __dirname and __filename
    "no-path-concat": 1,

    // Prefer using arrow functions for callbacks
    "prefer-arrow-callback": 1,

    // Return inside each then() to create readable and reusable Promise chains.
    // Forces developers to return console logs and http calls in promises. 
    "promise/always-return": 2,

    //Enforces the use of catch() on un-returned promises
    "promise/catch-or-return": 2,

    // Warn against nested then() or catch() statements
    "promise/no-nesting": 1
  }
}

**Comment by wlaa41** [comment] 2018-06-22 21:08
I did the 
npm install eslint-plugin-promise --save-dev
But hasn't solve the issue

**Comment by platinumazure** [comment] 2018-06-22 21:18
What do you see now with `./node_modules/.bin/eslint .`? Same issue?

**Comment by wlaa41** [comment] 2018-06-22 21:22
@paazmaya  
The message now is different

     Cannot find module '@ljharb/eslint-config'
    Referenced from: D:\Firebase\rwkiawl\functions\node_modules\body-parser\node_modules\qs\.eslintrc
    Error: Cannot find module '@ljharb/eslint-config'
    Referenced from: D:\Firebase\rwkiawl\functions\node_modules\body-parser\node_modules\qs\.eslintrc
    at ModuleResolver.resolve (D:\Firebase\rwkiawl\node_modules\eslint\lib\util\module-resolver.js:74:19)
    at resolve (D:\Firebase\rwkiawl\node_modules\eslint\lib\config\config-file.js:479:28)
    at load (D:\Firebase\rwkiawl\node_modules\eslint\lib\config\config-file.js:551:26)
    at configExtends.reduceRight (D:\Firebase\rwkiawl\node_modules\eslint\lib\config\config-file.js:425:36)
    at Array.reduceRight (<anonymous>)
    at applyExtends (D:\Firebase\rwkiawl\node_modules\eslint\lib\config\config-file.js:403:26)
    at loadFromDisk (D:\Firebase\rwkiawl\node_modules\eslint\lib\config\config-file.js:523:22)
    at Object.load (D:\Firebase\rwkiawl\node_modules\eslint\lib\config\config-file.js:559:20)
    at Config.getLocalConfigHierarchy (D:\Firebase\rwkiawl\node_modules\eslint\lib\config.js:227:44)
    at Config.getConfigHierarchy (D:\Firebase\rwkiawl\node_modules\eslint\lib\config.js:179:43)

**Comment by wlaa41** [comment] 2018-06-22 21:54
When I place Return the error goes though the meth should not return any value

![untitled](https://user-images.githubusercontent.com/40356509/41800776-bd0ec912-767f-11e8-82e9-ec7fe99fc011.png)

This is .eslint.json is all fill with errors

![untitleed](https://user-images.githubusercontent.com/40356509/41800777-bd3ad96c-767f-11e8-8035-493f5ea6634a.png)

**Comment by ilyavolodin** [comment] 2018-06-23 17:08
@wlaa41 Why do you think this error is related to ESLint? Please try to create a very small reproduction case (by removing all of the unrelated code) and provide it here with the clear error message from ESLint (so far you only showed NPM error message) so we could try to figure out what the problem is.

**Comment by not-an-aardvark** [comment] 2018-07-22 06:55
Closing because this doesn't appear to be an error with ESLint.

**Closed by not-an-aardvark** 2018-07-22 06:55 UTC
Labels: needs info, triage
