### ISSUE TITLE
Adding ignore-path flag referencing a file in node_modules not respecting ignore config

### ISSUE THREAD

**Issue by kentcdodds** [eslint/eslint#9227] opened 2017-09-04 06:46 UTC
**Tell us about your environment**

* **ESLint Version:** 4.6.1 (latest)
* **Node Version:** 8.4.0 (latest)
* **npm Version:** 5.4.0 (latest)

**What parser (default, Babel-ESLint, etc.) are you using?** N/A

**Please show your full configuration:** N/A

<details>
<summary>Configuration</summary>

```js
{}
```

</details>

**What did you do? Please include the actual source code causing the issue.**

```
eslint --ignore-path node_modules/kcd-scripts/dist/config/eslintignore .
```

**What did you expect to happen?**

I expected the eslintignore to be applied

**What actually happened? Please include the actual, raw output from ESLint.**

It is not. I get an error indicating that eslint is processing files in `node_modules`.

Here's the contents of `node_modules/kcd-scripts/dist/config/eslintignore`:

```
node_modules
coverage
dist
build
out
.next
```

I think that the docs indicate that the patterns here will be relative to the `.eslintignore` file, so I changed the eslintignore file to various patterns (including `../../../node_modules/`, `**/node_modules/**`). None of those combinations seemed to work. I think there may be a bug here, but I'm uncertain... Happy to dig in more if someone can tell me I'm not missing something obvious.

To reproduce: https://github.com/kentcdodds/eslint-config-issue

Install deps and run `npm run broken` and `npm run working`.

Thanks!

**Comment by not-an-aardvark** [comment] 2017-09-05 21:29
Thanks for reporting, I can reproduce this.

**Comment by kentcdodds** [comment] 2017-09-05 21:41
How can I help fix this?

**Comment by not-an-aardvark** [comment] 2017-09-05 21:53
From investigating just now, I think the issue was introduced in https://github.com/eslint/eslint/commit/e3959199bc681ce2571fac55efa2eb0ba3d0c11a, where we switched to resolving ignore patterns from the location of the `.eslintignore` file rather than the CWD.

I think the problem is that in addition to resolving ignore patterns that appear in the `.eslintignore` file from the ignore file's location, we're also resolving the *default* ignore patterns (such as `/node_modules/*`) from the location of the ignore file, rather than the CWD. So when you use `eslint --ignore-path node_modules/kcd-scripts/dist/config/eslintignore`, it's effectively ignoring files in `node_modules/kcd-scripts/dist/config/node_modules` rather than `./node_modules`, which causes the rest of the files in `./node_modules` to get linted.

The cause of the issue seems to be [here](https://github.com/eslint/eslint/blob/c8bf687711eeb78bb3454f64fea891a788fcc187/lib/ignored-paths.js#L239). `this.baseDir` is currently always set to the location of the ignore file (or the CWD if no ignore file is being used), so we're using the same relative path for both the default ignore patterns and the custom ignore patterns. I *think* the issue will be fixed if we use different relative paths for each check there (a path relative to the CWD for default patterns, and a path relative to the ignore file location for custom patterns).

**Comment by kentcdodds** [comment] 2017-09-05 22:18
Thanks for that insight! So, if I understand you correctly, the fix would be changing this:

https://github.com/eslint/eslint/blob/c8bf687711eeb78bb3454f64fea891a788fcc187/lib/ignored-paths.js#L229-L251

to:

```diff
     contains(filepath, category) {
 
         let result = false;
         const absolutePath = path.resolve(this.options.cwd, filepath);
-        const relativePath = pathUtil.getRelativePath(absolutePath, this.baseDir);
+        const baseDir = category === "default" ? this.options.cwd : this.baseDir;
+        const relativePath = pathUtil.getRelativePath(absolutePath, baseDir);

         if ((typeof category === "undefined") || (category === "default")) {
             result = result || (this.ig.default.filter([relativePath]).length === 0);
         }

         if ((typeof category === "undefined") || (category === "custom")) {
             result = result || (this.ig.custom.filter([relativePath]).length === 0);
         }

         return result;

     }
```

Also, what's a good place to write tests for this changed behavior? in [`tests/lib/ignored-paths.js`](https://github.com/eslint/eslint/blob/e3959199bc681ce2571fac55efa2eb0ba3d0c11a/tests/lib/ignored-paths.js)?

**Comment by not-an-aardvark** [comment] 2017-09-05 23:37
I think that's almost right, although I think that would have the issue where `category` can also be `null`, in which case both the `default` and `custom` filters should be applied, so the `if` statements in that function aren't mutually exclusive.

Something like this should work:

```diff
     contains(filepath, category) {
 
         let result = false;
         const absolutePath = path.resolve(this.options.cwd, filepath);
-        const relativePath = pathUtil.getRelativePath(absolutePath, this.baseDir);

         if ((typeof category === "undefined") || (category === "default")) {
+            const relativePath = pathUtil.getRelativePath(absolutePath, this.options.cwd);
             result = result || (this.ig.default.filter([relativePath]).length === 0);
         }

         if ((typeof category === "undefined") || (category === "custom")) {
+            const relativePath = pathUtil.getRelativePath(absolutePath, this.baseDir);
             result = result || (this.ig.custom.filter([relativePath]).length === 0);
         }

         return result;

     }
```

Also, after I commented before I noticed [another place](https://github.com/eslint/eslint/blob/c8bf687711eeb78bb3454f64fea891a788fcc187/lib/ignored-paths.js#L276) that might also need to be changed in a similar way (to resolve default patterns from the `cwd` rather than `this.baseDir`).

> Also, what's a good place to write tests for this changed behavior? in [`tests/lib/ignored-paths.js`](https://github.com/eslint/eslint/blob/e3959199bc681ce2571fac55efa2eb0ba3d0c11a/tests/lib/ignored-paths.js)?

Yes, I think that's the right place to put them.

**Comment by pensierinmusica** [comment] 2018-05-13 20:09
Hi,

We have the same problem.

@not-an-aardvark @kentcdodds any chance of seeing this fixed?

**Comment by kentcdodds** [comment] 2018-05-13 21:13
I'd love for this to be fixed, but my pull request hit a wall and I don't have any more time for it.

**Comment by not-an-aardvark** [comment] 2018-07-21 03:50
Working on this.

**Closed** 2018-07-26 06:56 UTC
Labels: accepted, bug, core

**Comment by kentcdodds** [comment] 2018-07-26 12:51
Thank you! 👏

**Comment by not-an-aardvark** [comment] 2018-10-09 18:22
@cemremengu May you please [create a new issue](https://github.com/eslint/eslint/issues/new?template=BUG_REPORT.md)? It's possible that a different set of circumstances can lead to the same behavior, but it's hard to tell without more information.
