### ISSUE TITLE
Add "multiline-const", "multiline-let" and "multiline-var" STATEMENT_TYPEs to padding-line-between-statements rule

### ISSUE THREAD

**Issue by neemzy** [eslint/eslint#10721] opened 2018-08-02 12:09 UTC
**What rule do you want to change?** `padding-line-between-statements`

**Does this change cause the rule to produce more or fewer warnings?** More

**How will the change be implemented? (New option, new default behavior, etc.)?** New accepted values for `prev` and `next` configuration options

**Please provide some example code that this change will affect:**

```js
const bouya = { hey: "ho" };
const kasha = {
  tik: "tok",
  onda: "clock"
};
```

**What does the rule currently do for this code?** The rule is unable to differentiate single-line and multi-line `const`, `let` and `var` statements.

**What will the rule do after it's changed?** The rule will offer the possibility to treat aforementioned cases differently, e.g. enforce blank lines around a multi-line variable declaration but not around a single-line one.

**Comment by platinumazure** [comment] 2018-10-05 13:14
I'll champion this.

@eslint/eslint-team Can we get some :+1:s on this please?

**Comment by neemzy** [comment] 2018-10-30 13:43
@platinumazure @eslint/eslint-team Any news on this? :)

**Comment by platinumazure** [comment] 2018-10-30 16:12
@neemzy Thanks for following up. Trying to muster support again :smile: Hoping this might be accepted in a few days, otherwise we'll have to close per our issue backlog policy.

**Comment by platinumazure** [comment] 2018-10-30 19:29
@mysticatea @kaicataldo @not-an-aardvark Any thoughts on this proposal?

**Comment by not-an-aardvark** [comment] 2018-10-30 19:37
Is the intent that this should change the behavior of the existing `var`, `let`, and `const` STATEMENT_TYPEs to only match single-line statements? Based on skimming https://github.com/eslint/eslint/pull/10919 it seems like that is what's been implemented, but it seems like that would be a breaking change for users who rely on `var`, `let`, and `const` matching multiline statements.

**Comment by platinumazure** [comment] 2018-10-30 19:48
Thanks @not-an-aardvark, I didn't see the PR.

I would consider the PR as breaking at this point. I think we should support the multiline-only case in a semver-minor release and change the meaning of the existing types in a semver-major.

**Comment by not-an-aardvark** [comment] 2018-10-30 20:00
To me, it seems confusing to have a type called `var` that actually means "single-line var statement". What if we also added something like `singleline-var` and kept `var` as-is?

**Comment by neemzy** [comment] 2018-11-02 10:32
So `var` would match both single-line and multiline statements, and `singleline-var` and `multiline-var` would be added to allow for more specific targetting? That would be fine by me and would indeed avoid introducing a BC break. @platinumazure @not-an-aardvark Do you want me to update the PR accordingly?

**Comment by platinumazure** [comment] 2018-11-02 14:00
@neemzy Please do, thanks!

**Comment by neemzy** [comment] 2018-11-05 13:29
@platinumazure Should be good! I also added back the tests I had removed since they are passing again this way.

**Comment by platinumazure** [comment] 2018-11-05 13:46
@not-an-aardvark Given that the proposal and PR have both been tweaked to address your concerns, are you :+1: to this proposal now?

@kaicataldo @ilyavolodin Any thoughts on this proposal?

**Comment by kaicataldo** [comment] 2018-11-13 22:15
Sorry, I seemed to have missed this. I'm generally in favor of this proposal, but I do think it's a bit confusing  to be consistent between `expression`/`multiline-expression` and `var`/`singleline-var`/`multiline-var`, where `expression` is for a single-line expression and `multiline-expression` is for a multiline expression, whereas `var` is for both single-line and multiline `var` declarations, `singleline-var` is for only for single-line `var` declarations, and `multiline-var` is for multiline `var` declarations.

Also, what is the expected behavior when there is a conflict between, say, `vars` and `singleline-vars`?

**Comment by platinumazure** [comment] 2018-11-13 22:39
Thanks @kaicataldo for your feedback!

> Sorry, I seemed to have missed this. I'm generally in favor of this proposal, but I do think it's a bit confusing  to be consistent between `expression`/`multiline-expression` and `var`/`singleline-var`/`multiline-var`, where `expression` is for a single-line expression and `multiline-expression` is for a multiline expression, whereas `var` is for both single-line and multiline `var` declarations, `singleline-var` is for only for single-line `var` declarations, and `multiline-var` is for multiline `var` declarations.

I agree that would be confusing, but I don't think that's the case.

From the current version of the rule:

```
    expression: {
        test: (node, sourceCode) =>
            node.type === "ExpressionStatement" &&
            !isDirectivePrologue(node, sourceCode)
    }
```

So this proposal maintains consistency: `var` is any variable declaration, `multiline-var` is only multiple-line variable declaration statements, and `singleline-vars` would be only single-line variable declarations. (We don't currently have a `singleline-expression`, though.)

> Also, what is the expected behavior when there is a conflict between, say, `vars` and `singleline-vars`?

Good question.

It would be nice if we could say multi or single line always wins out as it's more specific. However, we could treat these the same as how the rule treats any other conflict: "If a statement pair matches multiple configurations, the last matched configuration will be used."

So we could optionally encourage users to specify the generic `var` configuration first, and then `singleline-var` or `multiline-var` second... But I think we also could just rely on the existing approach and documentation.

**Comment by not-an-aardvark** [comment] 2018-11-14 22:38
> I think it would be probably clearest if either `singleline-var` or `multiline-var` occur after `var` that `var` is ignored entirely, not just for the cases where the two overlap.

I disagree, I think that inconsistency would have the potential to create more confusion. It seems like the statement types in `padding-line-between-statements` are not designed with the goal of avoiding overlap -- for example, we already have the `block`, `block-like`, and `multiline-block-like` statement types  overlapping, as well as the `*` statement type which overlaps with everything else. The rule has a sound and documented way of avoiding conflicts caused by overlap (namely it use the last matching type), so I think it would be confusing if it used a different method of resolving conflicts for `singleline-var` and its variants.

**Comment by kaicataldo** [comment] 2018-11-14 22:45
I forgot about `*` - that's a great point. I retract my suggestion above. :+1:'d.

**Comment by neemzy** [comment] 2018-11-15 08:59
I reckon it means my PR's current implementation is OK for you? :)

**Closed** 2018-12-08 05:44 UTC
Labels: accepted, enhancement, rule
