### ISSUE TITLE
Bug: no-restricted-imports shows an error only on last element when using an array of different importNames and same name

### ISSUE THREAD

**Issue by saaaab1213** [eslint/eslint#15261] opened 2021-11-04 11:31 UTC
### Environment

Environment Info:

Node version: v15.10.0
npm version: v7.5.3
Local ESLint version: v7.27.0 (Currently used)
Global ESLint version: Not found
Operating System: darwin 20.6.0

### What parser are you using?

@typescript-eslint/parser

### What did you do?

<details>
<summary>Configuration</summary>

```
'use strict'

module.exports = {
  root: true,
  plugins: ['@typescript-eslint', 'react', 'jest', 'testing-library', 'prettier'],
  settings: {
    react: {
      pragma: 'React',
      version: '16.3'
    }
  },
  extends: [
    '@react-native-community',
    'eslint:recommended',
    'plugin:react/recommended',
    'plugin:jest/recommended',
    'plugin:testing-library/react',
    'prettier'
  ],
  env: {
    browser: true,
    commonjs: true,
    es6: true,
    node: true,
    jest: true
  },
  parser: '@typescript-eslint/parser',
  parserOptions: {
    ecmaVersion: 7,
    sourceType: 'module',
    ecmaFeatures: {
      jsx: true,
      generators: true,
      impliedStrict: true,
      experimentalObjectRestSpread: true
    }
  },
  rules: {
    'react/prop-types': [0],
    'prettier/prettier': 'error',
    '@typescript-eslint/explicit-member-accessibility': 'off',
    '@typescript-eslint/no-floating-promises': 'off',
    'jest/no-try-expect': 'off',
    'jest/no-conditional-expect': 'off',
    'react-hooks/exhaustive-deps': 'warn',
    'no-redeclare': 'warn',
    'testing-library/prefer-screen-queries': 'off', //https://github.com/testing-library/eslint-plugin-testing-library/blob/main/docs/rules/prefer-screen-queries.md
    'testing-library/await-async-query': 'warn',
    /* Temporally inactive rules to be changed ultimately little by little */
    'jest/no-mocks-import': 'warn',
    'react/display-name': 'warn',
    'react/no-did-update-set-state': 'warn',
    'no-console': 'error',
    'no-restricted-imports': [
      'error',
      {
        paths: [
          { name: 'react-native', importNames: ['Text'], message: 'import Text from ui/_components instead ' },
          {
            name: 'react-native',
            importNames: ['TextInput'],
            message: 'import TextInput from ui/_components instead '
          },
          { name: 'react-native', importNames: ['View'], message: 'import View from ui/_components instead ' },
          {
            name: 'react-native',
            importNames: ['ScrollView'],
            message: 'import ScrollView from ui/_components instead '
          },
          {
            name: 'react-native',
            importNames: ['KeyboardAvoidingView'],
            message: 'import KeyboardAvoidingView from ui/_components instead '
          },
          {
            name: 'react-native',
            importNames: ['ImageBackground'],
            message: 'import ImageBackground from ui/_components instead '
          },
          {
            name: 'react-native',
            importNames: ['Image'],
            message: 'import Image from ui/_components instead '
          }
        ]
      }
    ]
  },
  overrides: [
    {
      files: ['*.ts', '*.tsx'],
      rules: {
        '@typescript-eslint/explicit-member-accessibility': ['error', { accessibility: 'no-public' }],
        'no-unused-vars': 'off' //Causes duplicates with typescript-eslint/no-unused-vars
      }
    }
  ],
  globals: {
    process: true,
    fetchMock: true
  }
}

```
</details>

```js
import { Image , Text, ScrollView } from 'react-native'
```

Eslint only shows an error on Image as it is de last element of the array. If moving Text for example to the end of the array then it will show an error only on Text not on Image or ScrollView

### What did you expect to happen?

$ eslint --quiet --ext=js,jsx,ts,tsx ./src

/Users/user1/workspace/MyAPP/src/ui/_components/atoms/Icon/Icon.tsx
  2:10  error  'Image' import from 'react-native' is restricted. import Image from ui/_components instead        no-restricted-imports
  2:17  error  'ScrollView' import from 'react-native' is restricted. import ScrollView from ui/_components instead   no-restricted-imports
  2:29  error  'Text' import from 'react-native' is restricted. import Text from ui/_components instead         no-restricted-imports

✖ 3 problems (3 errors, 0 warnings)

error Command failed with exit code 1.

### What actually happened?

$ eslint --quiet --ext=js,jsx,ts,tsx ./src

/Users/user1/workspace/MyAPP/src/ui/_components/atoms/Icon/Icon.tsx
  2:10  error  'Image' import from 'react-native' is restricted. import Image from ui/_components instead   no-restricted-imports

✖ 1 problem (1 error, 0 warnings)

error Command failed with exit code 1.

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by nzakas** [comment] 2021-11-06 00:40
The problem is that you have multiple paths objects with the same name. Only the last “react-native” path is being checked because of that. The path objects are intended to have unique names.

**Comment by nzakas** [comment] 2021-11-06 00:41
@mdjermanovic you have a better handle of what this rule is supposed to do. Is this the intended behavior? (It appears so from the code.)

**Comment by ljharb** [comment] 2021-11-06 00:56
The use case of a custom message for each named import seems valuable; if it was meant to be unique names, I’d expect it to have been an object with paths as keys instead of an array.

**Comment by mdjermanovic** [comment] 2021-11-07 21:18
The rule expects unique `name` in `paths`. It is intended behavior. If there are multiple restricted named exports from same module, configuration should contain a single entry for that module, with all restricted names in `importNames`.

```js
{
    name: 'react-native',
    importNames: ['Text', 'TextInput' /*, .... */],
    message: 'import Text from ui/_components instead. import TextInput from ui/_components instead ...'
}
```

**Comment by ljharb** [comment] 2021-11-07 21:23
Should perhaps the rule error out eagerly then, when the config contains duplicate names?

**Comment by mdjermanovic** [comment] 2021-11-07 21:31
> Should perhaps the rule error out eagerly then, when the config contains duplicate names?

I think it should, as that seems better than silently overwriting previous entries.

However, there is a technical problem - JSON Schema doesn't support defining such contraints.

**Comment by ljharb** [comment] 2021-11-07 21:32
True - which is why an object with keys would have been a better schema, because it’s impossible to violate the constraint. It’d be fine now tho (altho potentially breaking / arguably patch) to throw a runtime error from the rule itself.

**Comment by mdjermanovic** [comment] 2021-11-08 10:32
> throw a runtime error from the rule itself

We try to avoid that contents of the files being linted can break linting.

Invalid configuration in a `/* eslint some-rule: ["error", ...] */` directive comment normally only produces a lint error ([demo example](https://eslint.org/demo#eyJ0ZXh0IjoiLyogZXNsaW50IG5vLXJlc3RyaWN0ZWQtaW1wb3J0czogW1wiZXJyb3JcIiwgMTIzNDVdICovXG5cbmZvbzsiLCJvcHRpb25zIjp7InBhcnNlck9wdGlvbnMiOnsiZWNtYVZlcnNpb24iOiJsYXRlc3QiLCJzb3VyY2VUeXBlIjoibW9kdWxlIiwiZWNtYUZlYXR1cmVzIjp7fX0sInJ1bGVzIjp7Im5vLXVuZGVmIjoyfSwiZW52Ijp7fX19)). Throwing an error would break the whole process.

**Comment by ljharb** [comment] 2021-11-08 17:30
Ah, interesting, I wasn't aware of that. That's not a constraint I believe I've followed in the eslint plugins i maintain - it seems like that's not a useful constraint if eslint isn't enforcing it (by converting runtime errors from parsing config comments to lint errors), and if it did so, then wouldn't eslint core rules be able to throw those runtime errors?

**Comment by nzakas** [comment] 2021-11-09 01:24
FYI: the test that ensures errors thrown in rules are bubbled up:

https://github.com/eslint/eslint/blob/04e91b615743cbb25cd9103e7329b056bd1572ad/tests/lib/linter/linter.js#L79

We can’t really convert thrown errors into linting errors because we don’t have any location information to associate with it (because the error isn’t in the file being linted but rather in the rule source).

On the other hand, it seems feasible to merge multiple path objects with the same name into one before running the rule. I’d argue that behavior is more expected than the current one.

**Comment by nzakas** [comment] 2022-01-08 00:28
> On the other hand, it seems feasible to merge multiple path objects with the same name into one before running the rule. I’d argue that behavior is more expected than the current one.

@eslint/eslint-tsc what do folks think about this?

**Comment by btmills** [comment] 2022-01-09 01:30
When you say merge multiple path objects, do you imagine it would take the union of all `importNames` and use just the last error message? From a quick skim of the source, it doesn't look too terribly impossible to key on `Tuple<name, importNames>` instead of just `name` so that each `importName` could have a distinct message as expected in the original report.

**Comment by nzakas** [comment] 2022-01-13 00:02
I was thinking we can allow multiple objects with the same “path” and treat importNames and message as a tuple under the “path”, so the messages still match up correctly. I’d argue that is the expected behavior.

**Comment by mdjermanovic** [comment] 2022-01-13 00:52
> I was thinking we can allow multiple objects with the same “path” and treat importNames and message as a tuple under the “path”, so the messages still match up correctly.

I think this is doable. There are some details to discuss (for example, what should be the message for `import *`), but I believe we could sort it out.

This, however, looks like a breaking change, because now-unused config entries will become used and can produce new lint errors, so it might be better to plan it for ESLint v9.0.0?

**Comment by btmills** [comment] 2022-01-14 01:19
> I’d argue that is the expected behavior.

Agreed, cool.

> This, however, looks like a breaking change, because now-unused config entries will become used and can produce new lint errors, so it might be better to plan it for ESLint v9.0.0?

You’re right, it would be. And it wouldn’t be a semver-minor bug fix because this wasn’t the intended behavior originally (just plausibly expectable).

**Comment by nzakas** [comment] 2022-01-15 00:22
Marking as breaking and added to the v9 board for us to review.

**Comment by mdjermanovic** [comment] 2023-04-06 10:22
Summary update on this issue:

* This issue is waiting for us to come up with a design. We should define a new behavior of this rule in cases where the configuration for this rule contains multiple entries with the same `name` like in the example from the original post.
* In the meantime, we received PR https://github.com/eslint/eslint/pull/16196 that proposes adding a new option `allowImportNames`. The PR was filed unrelated to this issue and it targets the current behavior of this rule. The team generally supports the proposal, and we see no problems with adding this option to the current behavior where effectively only one config entry applies to a given import declaration. However, we're not sure if and how the proposed option would fit into the new behavior where multiple config entries may apply to the same import declaration.
* Given the previous points, it seems best to hold off on adding the `allowImportNames` option at the moment, but include it in this design. Once we define the design that fixes this issue and includes (if possible) `allowImportNames` option altogether, we can proceed with https://github.com/eslint/eslint/pull/16196.

**Comment by nzakas** [comment] 2023-11-03 15:52
@mdjermanovic do you anticipate a design in time for v9.0.0?

**Comment by Tanujkanti4441** [comment] 2023-11-14 13:06
As a solution can we introduce a new option `importNameWithMessage` which will be an Array that will contain objects with the key `importName` and `message` something like this

```js
"rules": {
        "no-restricted-imports": ["error", 
        {
            paths: [
                {
                    name: "react-native",
                    importNamesWithMessage: [
                        {
                            importName: "TextInput",
                            message: "import TextInput from ui/_components instead"
                        },
                        {
                            importName: "Image",
                            message: "import Image from ui/_components instead"
                        },
                    ]
                }
            ]
        }
    ]
    }
```

**Comment by alexilyaev** [comment] 2023-11-20 17:44
Looking at the OP description setup, it looks like a common use case would be to have a similar message for multiple import names, with the only difference being the actual import name (using some kind of substitution)
e.g.
```js
{
  'no-restricted-imports': [
    'error',
    {
      paths: [
        {
          name: 'react-native',
          importNames: [
            'Text',
            'TextInput',
            'View',
            'ScrollView',
            'KeyboardAvoidingView',
            'ImageBackground',
            'Image',
          ],
          message: 'import ${importName} from ui/_components instead ',
        },
      ],
    },
  ],
}
```
Although considering a config in JavaScript, it would be easy to construct with the `importNamesWithMessage` solution above.

**Comment by mdjermanovic** [comment] 2024-01-22 18:21
`importNamesWithMessage` is a good idea, but after thinking about this more, I'd be in favor of the solution @nzakas suggested in https://github.com/eslint/eslint/issues/15261#issuecomment-1011561314 as it doesn't change the existing schema (except that we'll add option `allowImportNames` as a new feature proposed in https://github.com/eslint/eslint/pull/16196) and is more flexible. In particular, it allows for restricting the entire module and providing messages for some specific imports at the same time.

**Closed** 2024-01-24 17:58 UTC
Labels: bug, accepted, needs bikeshedding, breaking, repro:yes
