### ISSUE TITLE
spaced-comment report errors with /******* comments *******/

### ISSUE THREAD

**Issue by xcatliu** [eslint/eslint#9065] opened 2017-08-03 04:56 UTC
**Tell us about your environment**

* **ESLint Version:** v4.2.0
* **Node Version:** v8.1.2
* **npm Version:** 5.0.3

**What parser (default, Babel-ESLint, etc.) are you using?**
babel-eslint

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
        'spaced-comment': [
            'error',
            'always',
            {
                block: {
                    exceptions: [
                        '*'
                    ],
                    balanced: true
                }
            }
        ]
```

</details>

**What did you do? Please include the actual source code causing the issue.**

```js
/******* comments here *******/
```

**What did you expect to happen?**

No errors

**What actually happened? Please include the actual, raw output from ESLint.**

```bash
[eslint] Expected exception block, space or tab after '/**' in comment. (spaced-comment)
```

**Comment by not-an-aardvark** [comment] 2017-08-03 05:12
Thanks for the report -- however, this is working as intended. Your comment starts with `*`, which is not a space.

The rule has some [configuration options](http://eslint.org/docs/rules/spaced-comment) which might fulfill your use case if you'd like to allow `*` characters at the start of comments.

**Comment by Aladdin-ADD** [comment] 2017-08-03 08:55
I had a few tests:
```js
/* eslint spaced-comment: ["error", "always", { "exceptions": ["*"] }] */

// valid.
/******************
* comments here
******************/

// invalid
/**** comments here *******/
```

seems like comments like the second one are not supported now, maybe this can be an enhancement.

**Comment by AlexandreBonneau** [comment] 2017-08-26 07:56
On my end, I tried with `balanced: false` (cf. documentation : *If "balanced": false then balanced whitespace is not enforced.*), and I still cannot use:
```js
const bar = 'meh';
/*const foo = 42;
result = foo+bar;*/
return result;
```

This is annoying since I do want single line comments to always have a single space after `//`, but my IDE (PhpStorm) only wrap the block without spaces when using the block comment shortcut.

Is there a way to achieve that?
Thanks!

An extract of my configuration:
```js
"spaced-comment"        : [
    "error",
    "always",
    {
        "line" : {
            "markers"   : ["/", "TODO", "FIXME", "DEBUG", "XXX"],
            "exceptions": ["-", "+", "TODO", "FIXME", "DEBUG", "XXX"],
        },
        "block": {
            "markers"   : ["!"],
            "exceptions": ["*"],
            "balanced"  : false,
        }
    }
],
"padded-blocks"                : [
    "error",
    "never",
],
```

**Comment by not-an-aardvark** [comment] 2018-01-19 16:17
Thanks for your interest in improving ESLint. Unfortunately, it looks like this issue didn't get consensus from the team, so I'm closing it. We define [consensus](http://eslint.org/docs/maintainer-guide/issues.html#consensus) as having three :+1:s from team members, as well as a team member willing to champion the proposal. This is a high bar by design -- we can't realistically accept and maintain every feature request in the long term, so we only accept feature requests which are useful enough that there is consensus among the team that they're worth adding.

Since ESLint is pluggable and can load custom rules at runtime, the lack of consensus among the ESLint team doesn't need to be a blocker for you using this in your project, if you'd find it useful. It just means that you would need to [implement the rule](http://eslint.org/docs/developer-guide/working-with-rules) yourself, rather than using a bundled rule that is packaged with ESLint.

**Closed by not-an-aardvark** 2018-01-19 16:17 UTC
Labels: works as intended
