### ISSUE TITLE
<!-- style comments not recognized when parsing JSX

### ISSUE THREAD

**Issue by aaronshaf** [eslint/eslint#6964] opened 2016-08-23 22:30 UTC
Evidently `<!-- ...` single-line comments are valid in JavaScript. eslint doesn't seem to recognize this.

Source: https://twitter.com/bterlson/status/768211703314067457 and http://www.ecma-international.org/ecma-262/7.0/index.html#prod-annexB-SingleLineHTMLOpenComment

**Comment by ljharb** [comment] 2016-08-23 22:32
They're in annex B, which means non-web browsers don't have to implement parsing for it.

That said, it does seem useful for eslint to be able to parse them, if only so a rule can be created that forbids them :-)

**Comment by mysticatea** [comment] 2016-08-24 08:04
Thank you for this issue.

[Acorn](https://github.com/ternjs/acorn), the base of our parser, does not support HTML style comments, so it needs to implement in Acorn.

**Comment by aaronshaf** [comment] 2016-08-24 13:21
Thanks. I created the issue: https://github.com/ternjs/acorn/issues/454

**Comment by mysticatea** [comment] 2016-08-24 21:45
I re-confirmed that `<!--` seems to be handled as single line comment correctly.

![image](https://cloud.githubusercontent.com/assets/1937871/17949222/4f7966f8-6a8f-11e6-97a7-4c523059eb99.png)

**Comment by platinumazure** [comment] 2016-08-24 21:49
@mysticatea Do we need to do anything in espree, then, in order to get the comment to show up? Or maybe the problem is only in attaching the comments to code nodes? What's our next step here?

**Comment by mysticatea** [comment] 2016-08-24 21:58
Espree seems to handle the HTML comments as single line comments.
So, I think we don't need to do something for this.

![image](https://cloud.githubusercontent.com/assets/1937871/17949518/bf2993be-6a90-11e6-8165-6591c8fe6969.png)

(Probably I saw a ghost around this issue...)

**Comment by mysticatea** [comment] 2016-08-28 08:56
I got a fact that HTML comments trigger a syntax error if it's using JSX option.
I reopen this issue.

**Comment by mysticatea** [comment] 2016-08-28 09:29
I opened the issue: https://github.com/RReverser/acorn-jsx/issues/41

**Comment by mysticatea** [comment] 2017-05-18 03:09
`acorn-jsx`'s issue has been fixed now.
This issue will be fixed after `espree` upgrades `acorn-jsx` to `4.0.1`.

**Comment by mysticatea** [comment] 2018-10-04 12:06
Yes, it has been fixed. Thank you for pinging!

**Closed by mysticatea** 2018-10-04 12:06 UTC
Labels: accepted, blocked, bug
