### ISSUE TITLE
ESLint couldn't find the plugin @typescript-eslint

### ISSUE THREAD

**Issue by trigun539** [eslint/eslint#15629] opened 2022-02-21 16:29 UTC
### Environment

Node version: 16.1.0
npm version: 8.3.1
Local ESLint version: 8.9.0 
Global ESLint version: 8.9.0
Operating System: Mac

### What parser are you using?

@typescript-eslint/parser

### What did you do?

<details>

Run the command `eslint somefile.tsx`. Have removed and reinstalled `node_modules`.

<summary>Configuration</summary>

```
{
  "root": true,
  "env": {
    "browser": true,
    "es6": true
  },
  "parser": "@typescript-eslint/parser",
  "parserOptions": {
    "ecmaFeatures": {
      "jsx": true
    },
    "ecmaVersion": 2018,
    "sourceType": "module"
  },
  "plugins": ["@typescript-eslint,", "prettier"],
  "rules": {
    "semi": ["error", "never"],
    "quotes": ["error", "double"]
  },
  "extends": ["eslint:recommended", "plugin:@typescript-eslint/recommended"]
}
```

`package.json` file:
```

{
  "devDependencies": {
    "@typescript-eslint/eslint-plugin": "^5.12.0",
    "@typescript-eslint/parser": "^5.12.0",
    "eslint": "^8.9.0",
    "eslint-plugin-prettier": "^4.0.0",
    "prettier": "^2.3.2",
  }
}
```

</details>

### What did you expect to happen?

For eslint to run and find the issues with the file.

### What actually happened?

```
Oops! Something went wrong! :(

ESLint: 8.9.0

ESLint couldn't find the plugin "@typescript-eslint,/eslint-plugin".

(The package "@typescript-eslint,/eslint-plugin" was not found when loaded as a Node module from the directory "/Users/edwinperez/websites/goodshepherdmd.org".)

It's likely that the plugin isn't installed correctly. Try reinstalling by running the following:

    npm install @typescript-eslint,/eslint-plugin@latest --save-dev

The plugin "@typescript-eslint,/eslint-plugin" was referenced from the config file in ".eslintrc".

If you still can't figure out the problem, please stop by https://eslint.org/chat/help to chat with the team.

```

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by mdjermanovic** [comment] 2022-02-21 16:39
Hi @trigun539, thanks for the issue!

> "plugins": ["@typescript-eslint,", "prettier"]

It looks like you have an extra `,` after `@typescript-eslint` in the `"@typescript-eslint,"` string. Can you remove it and try again?

**Comment by trigun539** [comment] 2022-02-21 16:41
@mdjermanovic Thank you! 😅 Yep, that's the issue.

**Comment by mdjermanovic** [comment] 2022-02-21 20:19
Closing as the issue is resolved.

**Closed by mdjermanovic** 2022-02-21 20:19 UTC
Labels: bug, repro:needed
