### ISSUE TITLE
ESLint confuses string with missing quotes and new class instance without brackets

### ISSUE THREAD

**Issue by lukechilds** [eslint/eslint#7792] opened 2016-12-19 09:27 UTC
I posted this on the [standard repo](https://github.com/feross/standard/issues/725) but they said it belonged here.

If I have the code:

```js
const onionoo = new Onionoo()
```

to create a new instance of the `Onionoo` class but leave off the brackets:

```js
const onionoo = new Onionoo
```

standard says:

```
standard: Use JavaScript Standard Style (http://standardjs.com)
standard: Run `standard --fix` to automatically fix some problems.

/Users/lukechilds/Dev/oss/onionoo-node-client/test/unit.js
  18:19  error  Missing '
```

It seems like maybe it assumes `Onionoo` is a string without quotes. It would be better if it would warn that there are no parenthesis on the class (or not warn at all, not sure of the pros/cons of leaving off parenthesis). I'm guessing this would be fairly easy to fix by checking if the `new` keyword is directly before the string but I'm not sure.

* **ESLint Version: Standard 8.6.0 (ESLint 3.10.2)**
* **Node Version: 7.1.0**
* **npm Version: 3.10.9**

```
  ├─┬ standard@8.6.0
  │ ├── eslint@3.10.2
  │ ├── eslint-config-standard@6.2.1
  │ ├── eslint-config-standard-jsx@3.2.0
  │ ├── eslint-plugin-promise@3.4.0
  │ ├── eslint-plugin-react@6.7.1
  │ ├── eslint-plugin-standard@2.0.1
  │ └── standard-engine@5.2.0
```

Using the default `standard` config.

**Comment by not-an-aardvark** [comment] 2016-12-19 09:38
Thanks for the report. However, I think this might actually be an issue with `standard`, since it seems to work fine when just running ESLint. The output is:

```
1:17 - Missing '()' invoking a constructor. (new-parens)
```

**Comment by lukechilds** [comment] 2016-12-19 09:47
@not-an-aardvark Thanks, I've updated the `standard` issue.

**Comment by vitorbal** [comment] 2016-12-20 13:43
Thanks for the update, @lukechilds! Closing this as it seems you found the issue is related to snazzy.

**Closed by vitorbal** 2016-12-20 13:43 UTC
Labels: question
