### ISSUE TITLE
Suggestion to remove "no-console" from "recommended" rules

### ISSUE THREAD

**Issue by trevordmiller** [eslint/eslint#8544] opened 2017-05-05 03:53 UTC
_First off, thanks for eslint. It is an amazing tool that helps me catch issues in my code. I use it in every JS project I create. Much ❤️ to the team for all the bugs you've helped me prevent._

I enjoy using the `recommended` rules to help me catch issues, without adding stylistic or opinionated rules. However, I feel `no-console` should be removed from the `recommended` setting because I feel it is more commonly a feature and tool than a potential issue. It's true that leaving console output in production websites can be an issue, but this is a feature in other environments like node. It is extremely common to build node scripts and CLIs using console output as a feature. And even for websites, using console output is extremely common to aid in debugging - having console output show as a lint error while debugging is distracting. I understand that any rule can be negated with `rules` config, but in my opinion the `recommended` rules should stick to only potential issues in code, which I don't think console output is.

It seems some others agree. For example, create-react-app doesn't use `recommended` for a couple reasons - one of which is this issue - as Dan Abramov explained here: https://github.com/facebookincubator/create-react-app/issues/11#issuecomment-235543462. I would imagine if there was a poll given that the majority would agree and would encourage that be done if possible.

Another option would be to keep the `console.log` error in recommended but allow the more deliberate `console.info/warn/error` options by default:
```
    "no-console": [
      "error", 
      { 
        allow: ["info", "warn", "error"] 
      }
    ],
```

Anyways, my 2 cents. Will be interested in discussing and others opinions. Thank you for your time.

---

_Started because of twitter thread: https://twitter.com/geteslint/status/860270285047582720_

**Comment by Zyst** [comment] 2017-05-05 04:20
For me `no-console` is mildly annoying, specially since the context when I'm using default eslint config tends to be when writing random short scripts which use `console.log`. 

If I want to have a config specific to console we usually always have one in actual projects, so it's a bit weird to find it there.

That said, it isn't a particularly strong opinion, if it stays I'm not rioting anytime soon.

**Comment by juanpaco** [comment] 2017-05-05 05:29
I'll offer a contrary opinion.  I like having it in there, because I use `console.log` exclusively for print trace debugging during development, and I don't want those going into source control.  For things I want logged, I use something like morgan, which is easy to turn off for a given context.  When running tests I don't want to see any `console.log` output.  I find it distracting.

It is an easy fix in either direction, of course.

**Comment by jahed** [comment] 2017-05-05 09:00
The vast majority of direct console logging for me is for debugging which I don't want on commits, everything else goes through a wrapper so it can be tagged and filtered easily. So IMO it's a good default. Having arbritrary logging ends up becoming noise.

**Comment by not-an-aardvark** [comment] 2017-05-17 05:39
I'm mildly opposed to this for the same reasons as a few other people have mentioned (usually, I use `console.log` for debugging and I want to remove the statements afterwards.) However, I don't have a strong objection if another team member wants to champion the issue.

**Comment by ilyavolodin** [comment] 2017-05-21 18:06
I agree with @not-an-aardvark While not everyone writes javascript for browsers, in browsers I really think there should not be any `console` statements. I know I opened dev tools on more then one site and saw console statements, and it always makes me feel a lot more wary about the sites that do that. They feel unfinished.

**Comment by platinumazure** [comment] 2017-05-21 18:25
To play devil's advocate here: We've removed rules from `eslint:recommended` for less.

That said, I don't feel strongly either way.

**Comment by trevordmiller** [comment] 2017-05-21 19:07
Could the rule be conditionally removed if node is listed as the environment?

**Comment by not-an-aardvark** [comment] 2017-05-21 20:11
No, this wouldn't really be aligned with how preset configs normally work -- the rules in a preset config are currently independent of the environments.

For what it's worth, I think committing code with `console.log` can be equally disruptive in Node because it interferes with debugging. I often use `console.log` when debugging, but it's much harder to do that when there are unrelated things also being logged from a different part of the code. So I always want to remove logging statements before committing.

**Comment by trevordmiller** [comment] 2017-06-25 04:43
Great thoughts everyone! I'm going to close this as it seems to make sense for no-console to be left in recommended and to use dedicated logging libraries for apps that use logging explicitly (like in node).

**Comment by trevordmiller** [comment] 2017-06-28 16:32
Actually, I'm going to re-open this to consider a suggestion: what if the default for `no-console` were changed to:
```
    "no-console": [
      "error", 
      { 
        allow: ["info", "warn", "error"] 
      }
    ],
```
That way, `console.log`s still throw an error, but deliberate logging is allowed by default without an overriding `rules` required?

**Comment by juanpaco** [comment] 2017-06-28 17:19
I like that a lot.  I never use those 3 for print tracing and generally always intend those to go into source control.

**Comment by jahed** [comment] 2017-06-28 23:59
As I mentioned before, for me, having arbitrary logging isn't useful in the long run and any long-term logging should be tagged and organised for maintainability (which is usually what logging libraries provide).

Allowing info/warn/error will just make someone go into the habit of using `console.info` to easily bypass the linter.

**Comment by not-an-aardvark** [comment] 2018-03-05 17:51
Thanks for your interest in improving ESLint. Unfortunately, it looks like this issue didn't get consensus from the team, so I'm closing it. We define [consensus](http://eslint.org/docs/maintainer-guide/issues.html#consensus) as having three :+1:s from team members, as well as a team member willing to champion the proposal. This is a high bar by design -- we can't realistically accept and maintain every feature request in the long term, so we only accept feature requests which are useful enough that there is consensus among the team that they're worth adding.

Since ESLint is pluggable and can load custom rules at runtime, the lack of consensus among the ESLint team doesn't need to be a blocker for you using this in your project, if you'd find it useful. It just means that you would need to [implement the rule](http://eslint.org/docs/developer-guide/working-with-rules) yourself, rather than using a bundled rule that is packaged with ESLint.

**Closed by not-an-aardvark** 2018-03-05 17:51 UTC
Labels: breaking, core, evaluating
