### ISSUE TITLE
TypeError: Cannot read property 'value' of undefined

### ISSUE THREAD

**Issue by sosz** [eslint/eslint#6319] opened 2016-06-03 18:05 UTC
**What version of ESLint are you using?**
`eslint@2.11.1`

**What parser (default, Babel-ESLint, etc.) are you using?**
`babel-eslint@6.0.4`

**Please show your full configuration:**
[Link to Gist](https://gist.github.com/sosz/162703cc8df31b1be0bf566266d997ce)

**What did you do? Please include the actual source code causing the issue.**
Running `eslint Test.js`. Its source can be found in the [Gist](https://gist.github.com/sosz/162703cc8df31b1be0bf566266d997ce) above.

**What did you expect to happen?**
Receive an ESLint report.

**What actually happened? Please include the actual, raw output from ESLint.**
```console
Cannot read property 'value' of undefined
TypeError: Cannot read property 'value' of undefined
    at getStarToken (C:\Users\hesos\Projects\modules\ichi\node_modules\eslint\lib\rules\generator-star-spacing.js:68:25)
    at EventEmitter.checkFunction (C:\Users\hesos\Projects\modules\ichi\node_modules\eslint\lib\rules\generator-star-spacing.js:123:29)
    at emitOne (events.js:101:20)
    at EventEmitter.emit (events.js:188:7)
    at NodeEventGenerator.enterNode (C:\Users\hesos\Projects\modules\ichi\node_modules\eslint\lib\util\node-event-generator.js:40:22)
    at CodePathAnalyzer.enterNode (C:\Users\hesos\Projects\modules\ichi\node_modules\eslint\lib\code-path-analysis\code-path-analyzer.js:607:23)
    at CommentEventGenerator.enterNode (C:\Users\hesos\Projects\modules\ichi\node_modules\eslint\lib\util\comment-event-generator.js:97:23)
    at Controller.traverser.traverse.enter (C:\Users\hesos\Projects\modules\ichi\node_modules\eslint\lib\eslint.js:905:36)
    at Controller.__execute (C:\Users\hesos\Projects\modules\ichi\node_modules\estraverse\estraverse.js:397:31)
    at Controller.traverse (C:\Users\hesos\Projects\modules\ichi\node_modules\estraverse\estraverse.js:501:28)

```

**Comment by btmills** [comment] 2016-06-03 18:28
Thanks for the report, @sosz. This looks like it might be a duplicate of #6274. Can you confirm?

**Comment by sosz** [comment] 2016-06-04 08:11
Yes, that looks to be the case

**Comment by alberto** [comment] 2016-06-04 12:46
Closing then. Thanks!

**Closed by alberto** 2016-06-04 12:46 UTC
Labels: duplicate
