### ISSUE TITLE
Allow comment flags on scope level

### ISSUE THREAD

**Issue by zanona** [eslint/eslint#1830] opened 2015-02-12 14:30 UTC
Coming from JSLint, I do remember such behaviour was set by default:

```js
function foo() {
   /*global b*/
   more(b);
}

function bar() {
   more(b) // This would trigger an error since b was not defined on this scope
}
```

and the same for cases like:

```js
function foo() {
   /*eslint no-eval:0*/
   var result = eval('1 + 1');
}

function bar() {
   var result2 = eval('1 + 1'); //This would trigger an error since the flag was not set in this scope level.
}
```

However, on eslint every comment declaration  seems to take global effect over the file and not per the scoped it has been applied to?

**Comment by lo1tuma** [comment] 2015-02-12 14:41
Duplicate of #1766.

**Closed** 2015-02-12 16:10 UTC
