### ISSUE TITLE
line-comment-position and default-case exception comment

### ISSUE THREAD

**Issue by peet** [eslint/eslint#7154] opened 2016-09-14 14:15 UTC
**Tell us about your environment**
- **ESLint Version:** 3.5.0
- **Node Version:** 6.5.0
- **npm Version:** 3.10.3

**What parser (default, Babel-ESLint, etc.) are you using?** None

**Please show your full configuration:** 

``` javascript
module.exports = {
  env: {
    es6: true,
  },
  parserOptions: {
    ecmaVersion: 2015,
  },
  rules: {
    'line-comment-position': ['error', { position: 'beside' }],
    'default-case': ['error', { commentPattern: '^no default case$' }],
  },
};
```

**What did you do? Please include the actual source code causing the issue.**

``` javascript
switch (action) {
  case "OPEN":
    doOpen();
    break;

  // no default case
}
```

**What did you expect to happen?**
The `// no default case` comment, as specified by the `default-case` rule should be allowed by `line-comment-position` - it can't be 'beside' any code (except the previous `break`, which looks bad)

**What actually happened? Please include the actual, raw output from ESLint.**
`error  Expected comment to be beside code  line-comment-position`

Edited to add: `position: 'above'` works fine, only `beside` shows an issue.

**Comment by mysticatea** [comment] 2016-09-16 09:37
Thank you for this issue.

You can use [ignorePattern](http://eslint.org/docs/rules/line-comment-position#ignorepattern) option for this.

Anyway, since [`default-case` rule has the special comment "no default" by default](https://github.com/eslint/eslint/blob/master/lib/rules/default-case.js#L7), I think reasonable if we add `^%s*no default%s*$` to the default ignore pattern.

**Comment by peet** [comment] 2016-09-16 11:11
Ah yes, somehow missed that option. Thanks.
+1 to adding "no default" to the default ignore pattern.

**Comment by platinumazure** [comment] 2016-09-16 12:53
That's one approach, but personally I think there might be a false error report.

The `line-comment-position` is only supposed to check if a comment is above or beside the main line of code. My guess is that "beside" comments are implemented by checking for trailing comments. The problem is, a comment *below* a line of code, with no code below it such that the comment could be a leading comment, is also a trailing comment. So I would say line-comment-position shouldn't even report comments that are below the node, in either mode.

@mysticatea Thoughts? Am I missing something? (Haven't had time to dig into the code, this is just speculation)

**Comment by mysticatea** [comment] 2016-09-18 05:07
Sounds reasonable to me.

Though the implementation does not use attached comments of AST. The rule just checks the previous token of comments is on the same line as the comment.
Maybe, in `beside` mode, the rule should ignore comments if the next token of the comment satisfies any of the following conditions:

- does not exist on the next line of the comment.
- is one of `)`, `]`, and `}`.

**Comment by kaicataldo** [comment] 2017-01-09 05:20
I'm closing this issue because it looks like consensus couldn't be reached. While we wish we could accommodate all requests, we have limited resources and do need to prioritize. We've found that issues failing to reach consensus after 21 days tend to never reach consensus, and as a team have decided to close such issues. This doesn't mean the idea isn't interesting or valuable, only that it's not something the team can commit to at the moment.

**Closed by kaicataldo** 2017-01-09 05:20 UTC
Labels: enhancement, evaluating, rule
