### ISSUE TITLE
TypeError when using ES6 modules

### ISSUE THREAD

**Issue by feross** [eslint/eslint#2088] opened 2015-03-17 20:59 UTC
This code:

```js
import app from 'ampersand-app'

window.app = app.extend({
  init() {
    console.log('hi')
  }
})
```

With this config:

```json
{
    "env": {
        "es6": true
    },

    "ecmaFeatures": {
        "modules": true
    },

    "rules": {
        "no-func-assign": 2
    }
}
```

Throws this exception:

```
/Users/feross/code/standard/node_modules/eslint/lib/rules/no-func-assign.js:42
                if (def.name.name === name && def.type === "FunctionName") {
                            ^
TypeError: Cannot read property 'name' of undefined
    at checkIfIdentifierIsFunction (/Users/feross/code/standard/node_modules/eslint/lib/rules/no-func-assign.js:42:29)
    at EventEmitter.AssignmentExpression (/Users/feross/code/standard/node_modules/eslint/lib/rules/no-func-assign.js:73:17)
    at emitOne (events.js:82:20)
    at EventEmitter.emit (events.js:166:7)
    at Controller.controller.traverse.enter (/Users/feross/code/standard/node_modules/eslint/lib/eslint.js:735:25)
    at Controller.__execute (/Users/feross/code/standard/node_modules/eslint/node_modules/estraverse/estraverse.js:393:31)
    at Controller.traverse (/Users/feross/code/standard/node_modules/eslint/node_modules/estraverse/estraverse.js:491:28)
    at EventEmitter.module.exports.api.verify (/Users/feross/code/standard/node_modules/eslint/lib/eslint.js:728:24)
    at processFile (/Users/feross/code/standard/node_modules/eslint/lib/cli-engine.js:193:27)
    at /Users/feross/code/standard/node_modules/eslint/lib/cli-engine.js:293:26
```

I know ES6 module support isn't 100% there, but I wanted to share this crash, as it doesn't seem desirable :)

**Comment by ilyavolodin** [comment] 2015-03-17 21:14
Duplicate of #2060

**Closed by ilyavolodin** 2015-03-17 21:14 UTC
