### ISSUE TITLE
Bug: Long node_modules plugin paths cannot be found on Windows

### ISSUE THREAD

**Issue by karlhorky** [eslint/eslint#17763] opened 2023-11-15 11:55 UTC
### Environment

Node version: 20.9.0
npm version: 10.1.0
Local ESLint version: 8.53.0
Global ESLint version: --
Operating System: Microsoft Windows Server 2022 10.0.20348

### What parser are you using?

Default (Espree)

### What did you do?

<details>
<summary>Configuration (Flat Config)</summary>

```js
import eslintImport from 'eslint-plugin-import';

const config = [
  {
    plugins: {
      import: eslintImport,
    },
    rules: {
      'no-unused-vars': 'warn',
    },
  },
];

export default config;
```
</details>

```js
const a = 1;
```

### What did you expect to happen?

ESLint should run, also when the paths are deep and long (over 260 character `MAX_PATH` limit on Windows)

### What actually happened?

ESLint crashes on Windows when the paths are deep and long (over 260 character `MAX_PATH` limit on Windows)

```bash
$ npm install
$ npx eslint .  # In root, working
D:\a\eslint-max_path-windows-bug\eslint-max_path-windows-bug\index.js
Warning:   1:7  warning  'a' is assigned a value but never used  no-unused-vars

$ mkdir long-path\long-path\long-path\long-path\long-path\long-path\long-path\long-path\long-path\long-path\long-path\long-path\long-path\long-path\long-path\long-path\long-path\
$ cp eslint.config.js long-path\long-path\long-path\long-path\long-path\long-path\long-path\long-path\long-path\long-path\long-path\long-path\long-path\long-path\long-path\long-path\long-path\
$ cp index.js long-path\long-path\long-path\long-path\long-path\long-path\long-path\long-path\long-path\long-path\long-path\long-path\long-path\long-path\long-path\long-path\long-path\
$ cp package.json long-path\long-path\long-path\long-path\long-path\long-path\long-path\long-path\long-path\long-path\long-path\long-path\long-path\long-path\long-path\long-path\long-path\

$ cd long-path\long-path\long-path\long-path\long-path\long-path\long-path\long-path\long-path\long-path\long-path\long-path\long-path\long-path\long-path\long-path\long-path\
$ npm install
$ npx eslint .

Oops! Something went wrong! :(

ESLint: 8.53.0

Error: Cannot find package 'D:\a\eslint-max_path-windows-bug\eslint-max_path-windows-bug\long-path\long-path\long-path\long-path\long-path\long-path\long-path\long-path\long-path\long-path\long-path\long-path\long-path\long-path\long-path\long-path\long-path\node_modules\eslint-plugin-import\package.json' imported from D:\a\eslint-max_path-windows-bug\eslint-max_path-windows-bug\long-path\long-path\long-path\long-path\long-path\long-path\long-path\long-path\long-path\long-path\long-path\long-path\long-path\long-path\long-path\long-path\long-path\eslint.config.js
Did you mean to import eslint-plugin-import/lib/index.js?
    at legacyMainResolve (node:internal/modules/esm/resolve:189:26)
    at packageResolve (node:internal/modules/esm/resolve:[7](https://github.com/karlhorky/eslint-max_path-windows-bug/actions/runs/6876786397/job/18703094495#step:9:8)76:14)
    at moduleResolve (node:internal/modules/esm/resolve:[8](https://github.com/karlhorky/eslint-max_path-windows-bug/actions/runs/6876786397/job/18703094495#step:9:9)38:20)
    at defaultResolve (node:internal/modules/esm/resolve:1043:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:383:12)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:352:25)
    at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:228:38)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:85:3[9](https://github.com/karlhorky/eslint-max_path-windows-bug/actions/runs/6876786397/job/18703094495#step:9:10))
    at link (node:internal/modules/esm/module_job:84:36)
```

The `D:\a\eslint-max_path-windows-bug\eslint-max_path-windows-bug\long-path\long-path\long-path\long-path\long-path\long-path\long-path\long-path\long-path\long-path\long-path\long-path\long-path\long-path\long-path\long-path\long-path\node_modules\eslint-plugin-import\package.json` path is 277 characters long.

### Alternatives Considered

I was first thinking this may be a Windows configuration problem or a Node.js path resolution bug, but apparently both of these support 260+ character paths:

- Windows Server on GitHub Actions has long paths over 260 characters enabled https://github.com/actions/runner-images/issues/1052#issuecomment-644212560
- "Node uses [file namespace paths](https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file#win32-file-namespaces) for file access. We do that so we do not get hit by the 260 path limit," https://github.com/nodejs/node/issues/33829#issuecomment-641997122

### Link to Minimal Reproducible Example

https://github.com/karlhorky/eslint-max_path-windows-bug

### Participation

- [ ] I am willing to submit a pull request for this issue.

### Additional comments

This is a contrived example, but this can happen easily in normal projects with tools like `pnpm`, which creates long file paths:

- https://github.com/pnpm/pnpm/issues/6830

**Comment by mdjermanovic** [comment] 2023-11-15 20:06
I can reproduce this locally. However, it doesn't look like a problem in ESLint but rather in Node.js, and I'm not sure if there's anything we could do in ESLint to avoid this.

The error message says:

`Cannot find package ...\node_modules\eslint-plugin-import\package.json imported from ...\eslint.config.js`.

ESLint just calls [`import()`](https://github.com/eslint/eslint/blob/21ebf8a811be9f4b009cf70a10be5062d4fdc736/lib/eslint/flat-eslint.js#L299) with the path of the `eslint.config.js` file, which seems to be resolved successfully as it executes. ESLint doesn't resolve any paths inside `eslint.config.js`, it's Node.js that loads and executes it and resolves its imports. I'm getting the same error when I run the module directly (`node eslint.config.js`).

**Comment by karlhorky** [comment] 2023-11-16 09:47
Interesting, so maybe [the comment](https://github.com/nodejs/node/issues/33829#issuecomment-641997122) by @bzoz that Node.js is not affected by the 260 character path limit on Windows doesn't apply here or is outdated somehow - maybe Node.js has a limitation here...

Maybe time to open a Node.js bug.

**Comment by karlhorky** [comment] 2023-11-16 11:34
And I also opened an issue in Node.js:

- https://github.com/nodejs/node/issues/50753

**Comment by nzakas** [comment] 2023-11-17 21:45
To echo @mdjermanovic, this is an issue with Node.js rather than with ESLint, so closing.

**Closed by nzakas** 2023-11-17 21:45 UTC
Labels: bug, core, repro:yes

**Comment by karlhorky** [comment] 2024-04-05 13:25
These file/folder structures that have long paths are commonly created by pnpm as well - if you're running into this with pnpm and are looking for a workaround, here's what I'm currently using:

- https://github.com/nodejs/node/issues/50753#issuecomment-2039791858
