### ISSUE TITLE
eslint hangs after linting is complete

### ISSUE THREAD

**Issue by rhyst** [eslint/eslint#10239] opened 2018-04-18 12:27 UTC
Running on Windows 7
* **ESLint Version:** 4.19.1
* **Node Version:** 6.11.2
* **npm Version:** 3.10.10

**What parser (default, Babel-ESLint, etc.) are you using?**
Babel-ESLint,

**Please show your full configuration:**
<details>
<summary>Configuration</summary>

```js
{
  "extends": [
    "eslint:recommended",
    "airbnb",
    "plugin:react/recommended",
    "plugin:jsx-a11y/recommended",
    "plugin:import/errors",
    "plugin:import/warnings",
    "prettier",
    "prettier/react"
  ],
  "plugins": ["react", "jsx-a11y", "import", "prettier"],
  "parser": "babel-eslint",
  "env": {
    "es6": true,
    "node": true,
    "browser": true
  },
  "rules": {
    "prettier/prettier": [
      "error",
      {
        "singleQuote": true,
        "printWidth": 120
      }
    ],
    // This is just a ridiculous rule
    "no-console": 0,    
    // Don't enforce .jsx extension
    "react/jsx-filename-extension": 0,
    // These rules make if statements less logical
    "no-lonely-if": 0,
    "no-else-return": 0,
    // Allow imports from dev dependencies
    "import/no-extraneous-dependencies": [
      "error",
      {
        "devDependencies": true
      }
    ],
    // Allow importing with full file extension
    "import/extensions": 0,
    // At least allow properties of function arguments to be set:
    "no-param-reassign": [2, { "props": false }],    
    "consistent-return": 0,
    "linebreak-style": 0
  },
  "settings": {
    "import/ignore": ["node_modules"],
    "import/resolver": {
      "webpack": {
        "config": "webpack/dev.conf.js"
      }
    }
  }
}
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```bash
node_modules/.bin/eslint --debug src 
```

**What did you expect to happen?**
Eslint would evenutally finish linting and present a summary of linting issues,

**What actually happened? Please include the actual, raw output from ESLint.**
Debug output shows eslint finding each file. Final line it prints is:
```
eslint:cli-engine Linting complete in: 100222ms
```
And then the command hangs and I need to `crtl-c` to exit. There are no warnings or errors in the rest of the debug output.

**Comment by goliney** [comment] 2018-05-09 20:25
I have exactly the same issue. Running on `Ubuntu 16.04.4 LTS`:
- **ESLint Version:** 4.19.1
- **Node Version**: 8.7.0
- **npm Version:** 5.4.2

<details>
<summary>Configuration</summary>

```
{
  "parser": "babel-eslint",
  "root": true,
  "env": {
    "browser": true,
    "node": true
  },
  "extends": [
    "airbnb-base",
    "prettier"
  ],
  "plugins": [
    "flowtype",
    "json",
    "prettier"
  ],
  "rules": {
    "prettier/prettier": "error"
  },
  "globals": {
    "$Keys": true,
    "$Exact": true
  }
}

```

</details>

**Comment by goliney** [comment] 2018-05-09 20:39
I have a feeling that it's happening because of prettier, but I'm not sure,

**Comment by not-an-aardvark** [comment] 2018-05-09 20:55
Are you able to narrow down the problem by removing enabled rules until the problem goes away? My suspicion is that one of your enabled rules is preventing Node from exiting, but I'm not sure.

**Comment by lxe** [comment] 2018-05-15 19:37
I'm also observing this same exact behavior. Let's see if bumping versions of things helps.

**Comment by goliney** [comment] 2018-05-15 19:40
Once I deleted `coverage` folder that was created with `jest --coverage`, `eslint` has bounced back to normal.

**Comment by platinumazure** [comment] 2018-05-15 19:48
@goliney Maybe in your case, ESLint is trying to glob through the `coverage` folder to find files to lint. Try adding `coverage` to an .eslintignore file to avoid this in the future? (This assumes you haven't run with `--debug` to confirm that ESLint gets as far as linting before hanging-- if you know for sure it's post-linting, ignore this.)

**Comment by aqueiros** [comment] 2018-07-09 11:45
Removing this rule from my .eslintrc.js . file fixed it for me:
` 'prettier/prettier': ['error', prettierOptions],`

Also, using the --debug option, I found out that it was getting stuck in this message:
`eslint:linter Linting code for <huge file>`

So I narrowed it down to this very big file (51k lines) that I had in one of my test folders.  
So I guess It is unable to handle very big files.

**Comment by xiaofan2406** [comment] 2018-07-17 02:38
I ran into the exact same issue, and found out that it was caused by `eslint-plugin-webpack-resolver`.

End up switching to `eslint-import-resolver-alias`, everything works fine now.

Not sure if this would help with your case.

**Comment by SergioGeeK7** [comment] 2018-10-16 20:28
@goliney it worked... do not know why

**Comment by kaicataldo** [comment] 2018-10-28 03:51
It sounds like the instances described here were caused by ignoring unwanted directories (such as `coverage`).

Closing this issue as it looks like the question has been answered. Please feel free to visit us in the [ESLint Gitter](https://gitter.im/eslint/eslint) or open another issue if you have any other issues!

**Closed by kaicataldo** 2018-10-28 03:51 UTC
Labels: question
