### ISSUE TITLE
Rule Change: (no-multiple-empty-lines)

### ISSUE THREAD

**Issue by drackp2m** [eslint/eslint#16934] opened 2023-02-25 19:02 UTC
### What rule do you want to change?

no-multiple-empty-lines

### What change to do you want to make?

Implement autofix

### How do you think the change should be implemented?

A new default behavior

### Example code

```js
/*eslint no-multiple-empty-lines: ["warn", { "max": 1 }]*/

var foo = 5;


var bar = 3;
```

### What does the rule currently do for this code?

/*eslint no-multiple-empty-lines: ["warn", { "max": 1 }]*/

var foo = 5;
var bar = 3;

### What will the rule do after it's changed?

/*eslint no-multiple-empty-lines: ["warn", { "max": 1 }]*/

var foo = 5;

var bar = 3;

### Participation

- [ ] I am willing to submit a pull request to implement this change.

### Additional comments

Simply, comment that if in the rule I want to specify that the maximum is `n`, and for whatever reason, someone has decided to add `n + 1` changes, what I would expect is that this `+ 1` disappears, but not that it removes ALL the line breaks.

At least maybe, it would be nice to have a way to determine how we want the autofix behavior to be, because as it is right now, I don't see it quite right.

I don't know what the rest will think.

**Comment by fasttime** [comment] 2023-02-25 20:08
Hi @drackp2m, I can't seem to reproduce the behavior you describe. `no-multiple-empty-lines` already keeps `max` empty lines when the autofix is applied ([**repro link**](https://eslint.org/play/#eyJ0ZXh0IjoiLyplc2xpbnQgbm8tbXVsdGlwbGUtZW1wdHktbGluZXM6IFtcIndhcm5cIiwgeyBcIm1heFwiOiAxIH1dKi9cblxudmFyIGZvbyA9IDU7XG5cblxudmFyIGJhciA9IDM7Iiwib3B0aW9ucyI6eyJwYXJzZXJPcHRpb25zIjp7ImVjbWFWZXJzaW9uIjoibGF0ZXN0Iiwic291cmNlVHlwZSI6Im1vZHVsZSIsImVjbWFGZWF0dXJlcyI6e319LCJydWxlcyI6e30sImVudiI6eyJjb21tb25qcyI6dHJ1ZX19fQ==)). It is possible that another rule is also removing an empty line from the file, leaving none where there were two.

Could you show your config so we can better understand what's going on here? I'd also recommend that you include environment information and what parser you are using when filing a bug, as the template suggests.

**Comment by drackp2m** [comment] 2023-02-25 21:35
Wow!!! I've used it several times and have always encountered this problem, but I'm seeing that maybe it's from always using the same configuration.

I use it in a Typescript project assembled with NX, at the end, the rules that I have in my eslint are the following (I put the complete file).

<details>
  <summary>eslintrc.json</summary>
  
```
{
  "root": true,
  "ignorePatterns": ["**/*"],
  "plugins": ["@nrwl/nx"],
  "overrides": [
    {
      "files": ["*.ts", "*.tsx", "*.js", "*.jsx"],
      "rules": {
        "@nrwl/nx/enforce-module-boundaries": [
          "error",
          {
            "enforceBuildableLibDependency": true,
            "allow": [],
            "depConstraints": [
              {
                "sourceTag": "*",
                "onlyDependOnLibsWithTags": ["*"]
              }
            ]
          }
        ]
      }
    },
    {
      "files": ["*.ts", "*.tsx"],
      "plugins": ["import", "unused-imports"],
      "extends": ["plugin:@nrwl/nx/typescript", "plugin:prettier/recommended"],
      "rules": {
        "prettier/prettier": "warn",
        "unused-imports/no-unused-imports": "error",
        "@typescript-eslint/no-unused-vars": [
          "error",
          {
            "argsIgnorePattern": "^_",
            "varsIgnorePattern": "^_",
            "caughtErrorsIgnorePattern": "^_"
          }
        ],
        "import/newline-after-import": "warn",
        "import/order": [
          "warn",
          {
            "newlines-between": "always",
            "alphabetize": { "order": "asc" },
            "groups": ["external", "index", "internal"],
            "pathGroups": [
              {
                "pattern": "@lisa-service/**",
                "group": "internal",
                "position": "before"
              }
            ]
          }
        ],
        "sort-imports": [
          "warn",
          {
            "ignoreDeclarationSort": true
          }
        ],
        "no-duplicate-imports": "warn",
        "no-multiple-empty-lines": [
          "warn",
          { "max": 1, "maxEOF": 1, "maxBOF": 1 }
        ],
        "space-before-blocks": ["warn", "always"],
        "newline-before-return": ["warn"]
      }
    },
    {
      "files": ["*.js", "*.jsx"],
      "extends": ["plugin:@nrwl/nx/javascript"],
      "rules": {}
    },
    {
      "files": ["*.spec.ts", "*.spec.tsx", "*.spec.js", "*.spec.jsx"],
      "env": {
        "jest": true
      },
      "rules": {}
    }
  ]
}
```
</details>


The versions of the packages I have installed are:

<details>
  <summary>package.json</summary>
  
```
{
  "devDependencies": {
    "@angular-eslint/eslint-plugin": "~15.0.0",
    "@angular-eslint/eslint-plugin-template": "~15.0.0",
    "@angular-eslint/template-parser": "~15.0.0",
    "@nrwl/eslint-plugin-nx": "15.7.2",
    "@typescript-eslint/eslint-plugin": "^5.36.1",
    "@typescript-eslint/parser": "^5.36.1",
    "eslint": "~8.15.0",
    "eslint-config-prettier": "8.1.0",
    "eslint-import-resolver-typescript": "^3.5.3",
    "eslint-plugin-cypress": "^2.10.3",
    "eslint-plugin-import": "^2.27.5",
    "eslint-plugin-prettier": "^4.2.1",
    "eslint-plugin-unused-imports": "^2.0.0",
  }
}

```
</details>

I am doing some tests (now that I know it works in principle, as I have been wanting it to work for years, thank you very much for opening my eyes), I will comment again if I discover anything.

**Comment by drackp2m** [comment] 2023-02-25 23:35
Okay, it's all much more convoluted than I thought it would be.

I'm using VSCode, with the Eslint plugin (dbaeumer.vscode-eslint), with the settings that it can be used as a formatter, and that VSCode uses it by default in JS and TS files.

So, I'm seeing several strange things.

The first of all, and the one that may reassure the development team of this library is that if I run the command cli `eslint -fix path/to/file.ts` everything works perfectly.

But apart from this I have seen a quite strange behavior, and it is what all these years I have been thinking that it was the fault of how eslint corrected the problem automatically, and it is that.... when there are more than two lines, indeed, the correction is applied correctly and leaves the maximum number of jumps allowed by the `eslintrc` configuration.

It seems that the problem arises only when you exceed the limit of the `no-multiple-empty-lines` rule by one unit. For example, if I set it to 3 as warn and add four line breaks, I see the following in the editor (which indicates that prettier is crushing my eslint rule):

<img width="297" alt="image" src="https://user-images.githubusercontent.com/12443324/221384248-024d4c87-e7cb-4e50-b9f1-49fdf3a9c3bc.png">

If I format at this point, only one line break will remain, but if I add one more line, the error changes to.... (I have marked the eslint rule as error to make it clearer):

<img width="614" alt="image" src="https://user-images.githubusercontent.com/12443324/221384339-1791101f-7144-469b-a1f2-b9b6069aaf75.png">

It is when formatting at this point that the two rules are apparently applied on different lines, which ends up leaving a code without any line breaks.

I understand that this is a problem with `prettier` or the `eslint-config-prettier` plugin.

**Comment by fasttime** [comment] 2023-02-26 20:18
Thanks so much for the detailed information. Looking at your config, I can tell that the `no-multiple-empty-lines` rule is being explicitly enabled, and this setting overrides `prettier/prettier`, where many layout rules, including `no-multiple-empty-lines` are being disabled.

I don't know much about Prettier, specifically, I don't know how their VSCode plugin operates, so I can't really explain your observations. But it seems reasonable to me that Prettier does not expect you to have the `no-multiple-empty-lines` rule enabled in your code because it conflicts with their formatting (and so they disable it for you).

I'm going to close this issue because I think there is nothing we can do about it.

**Closed** 2023-02-26 20:19 UTC
Labels: enhancement, rule, works as intended
