### ISSUE TITLE
ESLint does not resolve plugin dependencies of a config when using npm link

### ISSUE THREAD

**Issue by gajus** [eslint/eslint#6222] opened 2016-05-19 13:25 UTC
I have a custom ESlint config:

```sh
cd ./eslint-config-foo
npm link
```

That config is using plugins, e.g. `eslint-plugin-import`.

Then I link this config in my project:

```sh
cd ./my-project
npm link eslint-config-foo
```

Then I try to lint the project:

```sh
./node_modules/.bin/eslint ./src
```

and I get the an error complaining that:

```
Oops! Something went wrong! :(

ESLint couldn't find the plugin "eslint-plugin-import". This can happen for a couple different reasons:

1. If ESLint is installed globally, then make sure eslint-plugin-import is also installed globally. A globally-installed ESLint cannot find a locally-installed plugin.

2. If ESLint is installed locally, then it's likely that the plugin isn't installed correctly. Try reinstalling by running the following:

    npm i eslint-plugin-import@latest --save-dev

If you still can't figure out the problem, please stop by https://gitter.im/eslint/eslint to chat with the team.
```

I can confirm that `eslint-plugin-import` is installed in the `eslint-config-foo`:

```sh
$ ls -lah ./node_modules/eslint-plugin-import
total 42k
drwxr-xr-x    1 kuizinag Administ     4.0k May 19 13:59 .
drwxr-xr-x    1 kuizinag Administ      48k May 19 14:15 ..
-rw-r--r--    1 kuizinag Administ      13k May 19 13:59 CHANGELOG.md
-rw-r--r--    1 kuizinag Administ     1.1k May 19 13:59 LICENSE
-rw-r--r--    1 kuizinag Administ      11k May 19 13:59 README.md
drwxr-xr-x    1 kuizinag Administ        0 May 19 13:59 config
drwxr-xr-x    1 kuizinag Administ        0 May 19 13:59 lib
drwxr-xr-x    1 kuizinag Administ        0 May 19 13:59 memo-parser
-rw-r--r--    1 kuizinag Administ     3.9k May 19 13:59 package.json
```

The only workaround that I have found is to install all config ESLint plugins in the project itself.

Expected behavior: ESLint should use plugins installed in the config directory.

**Comment by btmills** [comment] 2016-05-19 15:59
@gajus this looks like a duplicate of #3458. It's been open for a while, but we don't have a spec for what a fix would look like yet. Nobody's claimed it yet - any good ideas? You could probably pick it up and run with it.

**Closed by btmills** 2016-05-19 15:59 UTC
Labels: duplicate

**Comment by gajus** [comment] 2016-05-19 16:58
I have my hands full at the moment.

Thank you for referring to the correct issue.
