### ISSUE TITLE
Cannot read property 'ecmaFeatures' of undefined

### ISSUE THREAD

**Issue by bonesoul** [eslint/eslint#10623] opened 2018-07-18 15:26 UTC
Getting

`Parsing error: Cannot read property 'ecmaFeatures' of undefined`

**Tell us about your environment**

* **ESLint Version:** 5.1.0
* **Node Version:** 10.6.0
* **npm Version:**6.1.0"

my eslintrc

```
env:
  node: true
  es6: true
  jquery: false
  browser: false

extends:
  - eslint:recommended

rules:
  curly: off

```

**Comment by regseb** [comment] 2018-07-21 17:20
With this two files :

- _package.json_ :

  ```JSON
  {
      "dependencies": {
          "eslint": "5.2.0",
          "standard": "11.0.1"
      }
  }
  ```

- _testcase.js_ :

  ```JavaScript
  #!/usr/bin/env node

  const Linter = require("eslint").Linter;
  require("standard"); // Comment me !

  console.log(new Linter().verify("console.log('foo')"));
  ```

- and _node@v10.7.0_ / _npm@6.2.0_.

The function `verify()` returns :

```JavaScript
[ { ruleId: null,
    fatal: true,
    severity: 2,
    message:
     'Parsing error: Cannot read property \'ecmaFeatures\' of undefined',
    line: undefined,
    column: undefined } ]
```

**Comment by platinumazure** [comment] 2018-07-21 19:09
@regseb I don't think you're calling `Linter.verify` correctly. According to [the documentation](https://eslint.org/docs/developer-guide/nodejs-api#linterverify), a config argument is also necessary. (It's a bit weird that we return a lint result rather than throwing an exception, though.)

**Comment by regseb** [comment] 2018-07-21 20:45
@platinumazure There is the same problem with this example :

```JavaScript
#!/usr/bin/env node

const Linter = require("eslint").Linter;
require("standard"); // Comment me !

console.log(new Linter().verify("console.log('foo')",
                                { "rules": { "semi": 2 } }));
```

If you comment `require("standard");` or use _eslint@4.19.1_ :

- the first example (without config) returns a empty array ; 
- the example above returns :

  ```JavaScript
  [ { ruleId: 'semi',
      severity: 2,
      message: 'Missing semicolon.',
      line: 1,
      column: 19,
      nodeType: 'ExpressionStatement',
      fix: { range: [Array], text: ';' } } ]
  ```

**Comment by platinumazure** [comment] 2018-07-21 20:48
@regseb As the docs note, you need to pass in a fully hydrated config object to `Linter#verify`. If you need config normalization, you should use `CLIEngine#executeOnText`. (Make sure to specify `useEslintrc: false` if you don't need it to look for config files on the filesystem.)

**Comment by regseb** [comment] 2018-07-21 22:46
With this two examples got from the [documentation](https://eslint.org/docs/developer-guide/nodejs-api) where I just add `require("standard");` after the import of _eslint_, the same error is returned: `Parsing error: Cannot read property 'ecmaFeatures' of undefined`.

```JavaScript
#!/usr/bin/env node

var Linter = require("eslint").Linter;
require("standard"); ////////////////////
var linter = new Linter();

var messages = linter.verify("var foo;", {
    rules: {
        semi: 2
    }
}, { filename: "foo.js" });


console.log(messages);
```

```JavaScript
#!/usr/bin/env node

var CLIEngine = require("eslint").CLIEngine;
require("standard"); ////////////////////

var cli = new CLIEngine({
    envs: ["browser", "mocha"],
    useEslintrc: false,
    rules: {
        semi: 2
    }
});

// lint the supplied text and optionally set
// a filename that is displayed in the report
var report = cli.executeOnText("var foo = 'bar';", "foo.js");


console.log(report.results[0].messages);
```

Also with this case:

```JavaScript
#!/usr/bin/env node

var Linter = require("eslint").Linter;
require("standard"); ////////////////////
var linter = new Linter();

var messages = linter.verify("var foo;", {
    "parserOptions": {
        "ecmaVersion": 6,
        "sourceType": "module",
        "ecmaFeatures": {
            "jsx": true
        }
    },
    "rules": {
        "semi": 2
    }
}, { filename: "foo.js" });


console.log(messages);
```

The problem starts with the commit https://github.com/eslint/eslint/commit/f4b3af586d82768d3caf1ace77c5c42557a8e4a9#diff-b9cfc7f2cdf78a7f4b91a753d10865a2 (upgrade to Espree v4).

**Comment by sonnyprince** [comment] 2018-07-31 15:12
I've been getting the same error - seems to be something in Espree v4.0.0 thats breaking it.

Adding the following to my package.json seems to have fixed it.

`"resolutions": {
    "espree": "^3.5.4"
}`

**Comment by not-an-aardvark** [comment] 2018-08-01 01:29
Thanks for the reproducible example. I was able to reproduce this issue.

**Comment by not-an-aardvark** [comment] 2018-08-01 01:45
The root cause of this issue is that two different versions of `espree` are being loaded simultaneously with the same version of `acorn`. `espree` works by adding a plugin to the [`acorn`](https://www.npmjs.com/package/acorn) parser, and `acorn`'s plugin API seems to require setting global state on the `acorn` object. As a result, `espree@4` is setting some state by adding listeners to acorn, and then `espree@3` is getting loaded and is overriding the state that was set by `espree@4`. This is causing `espree@3`'s listeners to unexpectedly get called even though the running version of ESLint is using `espree@4`, which is causing `espree@3` to throw an error.

To me, it seems like the best way to fix this would be for `acorn` to allow registering a plugin without modifying global state on the `acorn` package. Another possibility would be for `espree` to include `acorn` as a bundled dependency to ensure that it never shares its version of `acorn` with any other packages.

**Comment by binarymist** [comment] 2018-08-28 12:26
Any updates on this?

**Comment by platinumazure** [comment] 2018-10-05 17:47
@not-an-aardvark 

> To me, it seems like the best way to fix this would be for `acorn` to allow registering a plugin without modifying global state on the `acorn` package. Another possibility would be for `espree` to include `acorn` as a bundled dependency to ensure that it never shares its version of `acorn` with any other packages.

I'm confused. Does espree not declare acorn as a dependency? Or do we have problems when npm dedupes the dependency tree, and you're referring to using bundled dependencies to get around the deduping behavior?

**Comment by not-an-aardvark** [comment] 2018-10-05 17:59
> Or do we have problems when npm dedupes the dependency tree, and you're referring to using bundled dependencies to get around the deduping behavior?

Yes, this is what I was referring to.

I haven't looked deeply into it, but based on the discussion in https://github.com/acornjs/acorn/issues/713, `acorn@6` apparently makes it possible to avoid this problem if we upgrade espree to use `acorn@6` instead.

**Comment by kaicataldo** [comment] 2018-10-15 19:47
Adding the blocked label until https://github.com/eslint/espree/pull/391 is merged and released.

**Closed** 2018-10-24 01:46 UTC
Labels: accepted, blocked, bug, core
