### ISSUE TITLE
Crash in no-unused-vars.js

### ISSUE THREAD

**Issue by DanLipsitt** [eslint/eslint#5494] opened 2016-03-07 03:26 UTC
Running eslint on the code below results in a crash. The testcase is pretty minimal. Maybe too minimal?

eslint 2.3.0
babel-eslint 5.0.0
babel 5.8.35
estraverse-fb 1.3.1

`.eslintrc.js`:
```js
module.exports = {
  env: {
    browser: true,
    node: true,
    es6: true,
    mocha: true,
  },
  extends: ['eslint:recommended', 'plugin:react/recommended'],
  parser: 'babel-eslint',
  parserOptions: {
    ecmaVersion: 6,
    ecmaFeatures: {
      experimentalObjectRestSpread: true,
      jsx: true,
    },
    sourceType: 'module',
  },
  plugins: [
    'react',
  ],
  rules: {
    indent: ['error', 4],
    'linebreak-style': ['error', 'unix'],
    quotes: ['error', 'single'],
    semi: ['error', 'always'],
    indent: ['warn', 2],
    'comma-dangle': ['warn', 'always-multiline'],
    'no-console': ['warn'],
  },
};
```

`failureCase.jsx`:
```js
import React, {Component} from 'react';
import {DragSource} from 'react-dnd';

const dragSource = {
  beginDrag(props) {
    return {id: props.file.id};
  },
};

@DragSource('FileItem', dragSource, (connect, monitor) => ({
  connectDragSource: connect.dragSource(),
  isDragging: monitor.isDragging()
}))
class FileItem extends Component {
  render() {}
};
```

To reproduce:
```sh-session
$ eslint failureCase.jsx
Cannot read property 'type' of undefined
TypeError: Cannot read property 'type' of undefined
    at collectUnusedVariables (/Users/dan/.node/lib/node_modules/eslint/lib/rules/no-unused-vars.js:166:44)
    at collectUnusedVariables (/Users/dan/.node/lib/node_modules/eslint/lib/rules/no-unused-vars.js:199:13)
    at collectUnusedVariables (/Users/dan/.node/lib/node_modules/eslint/lib/rules/no-unused-vars.js:199:13)
    at EventEmitter.Program:exit (/Users/dan/.node/lib/node_modules/eslint/lib/rules/no-unused-vars.js:255:30)
    at emitOne (events.js:82:20)
    at EventEmitter.emit (events.js:169:7)
    at NodeEventGenerator.leaveNode (/Users/dan/.node/lib/node_modules/eslint/lib/util/node-event-generator.js:51:22)
    at CodePathAnalyzer.leaveNode (/Users/dan/.node/lib/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:611:23)
    at CommentEventGenerator.leaveNode (/Users/dan/.node/lib/node_modules/eslint/lib/util/comment-event-generator.js:111:23)
    at Controller.controller.traverse.leave (/Users/dan/.node/lib/node_modules/eslint/lib/eslint.js:848:36)
```

**Comment by hzoo** [comment] 2016-03-07 03:35
Wondering why you aren't seeing https://github.com/eslint/eslint/issues/5476 - babel-eslint + eslint 2.3.0

**Comment by DanLipsitt** [comment] 2016-03-07 03:39
I have `estraverse-fb` installed as a workaround for #5476 and I still see the bug. Updated this issue to make that clear.

**Comment by hzoo** [comment] 2016-03-07 03:41
I see that's why. So just adding `estraverse-fb` doesn't work because the actual rules will be broken (ESLint 2.3.0 prevents babel-eslint from changing the visitorkeys so you will get those errors). Right now you'll have to pin to 2.2.x.

**Comment by DanLipsitt** [comment] 2016-03-07 03:46
Thanks for explaining. Feel free to close if this is a dupe.

**Comment by ilyavolodin** [comment] 2016-03-07 04:07
Closing as a dupe of #5476

**Closed by ilyavolodin** 2016-03-07 04:07 UTC
Labels: triage
