### ISSUE TITLE
Detect space before function arguments?

### ISSUE THREAD

**Issue by message** [eslint/eslint#1779] opened 2015-02-07 11:45 UTC
I want to make sure there will no be any spaces after `function` keyword, but with enabled `"space-after-keywords": [2, "always", { "checkFunctionKeyword": false }]` rule. `"space-after-function-name" : [2, "never"]` rule doesn't include that case. How to make that? 

Desired style:
```
"use strict";

module.exports = {
	key: function() {

	}
};
```
Warning must be issued:
```
"use strict";

module.exports = {
	key: function () {

	}
};
```

**Comment by nzakas** [comment] 2015-02-07 16:24
Duplicate of #1618.

**Closed by nzakas** 2015-02-07 16:24 UTC
