### ISSUE TITLE
feature request: relative directories to plugins/parsers/etc

### ISSUE THREAD

**Issue by devsnek** [eslint/eslint#9939] opened 2018-02-04 21:21 UTC
refs: https://github.com/nodejs/node/pull/18566

a fantastic alternative to what we did in that pr would be your resolving system allowing relative directories for plugins and parsers like
```js
plugins: ['markdown', './tools/node_modules/eslint-plugin-node'],
parser: './tools/node_modules/babel-eslint',
```

**Comment by not-an-aardvark** [comment] 2018-02-04 21:23
Closing as a duplicate of https://github.com/eslint/eslint/issues/6237

**Closed by not-an-aardvark** 2018-02-04 21:23 UTC
Labels: triage
