### ISSUE TITLE
Change Request: Support async parsers

### ISSUE THREAD

**Issue by btmills** [eslint/eslint#15558] opened 2022-02-01 06:13 UTC
### ESLint version

v8.8.0

### What problem do you want to solve?

Currently, the `parseForESLint()` method for custom parsers is synchronous. We're therefore unable to integrate parsers that have an asynchronous API.

### What do you think is the correct solution?

Intentionally deferring implementation details to @mdjermanovic, who will take point on this.

### Participation

- [ ] I am willing to submit a pull request for this change.

### Additional comments

We added this to the public roadmap in the 2022-01-27 TSC meeting.

**Comment by nzakas** [comment] 2022-02-24 01:49
Duplicate of https://github.com/eslint/eslint/issues/15475

**Closed by nzakas** 2022-02-24 01:49 UTC
Labels: enhancement, core, needs design
