### ISSUE TITLE
ESLint fails to find plugin in node_modules folder

### ISSUE THREAD

**Issue by acburdine** [eslint/eslint#7665] opened 2016-11-27 04:34 UTC
**Tell us about your environment**

* **ESLint Version:** 3.11.0
* **Node Version:** 4.6.0
* **npm Version:** 2.15.11

**What parser (default, Babel-ESLint, etc.) are you using?** 
Default parser through the command line - also experienced it through the atom plugin `linter-eslint`

**Please show your full configuration:**

```
module.exports = {
    root: true,
    parserOptions: {
        ecmaVersion: 6,
        sourceType: 'module'
    },
    extends: [
        'eslint:recommended',
        'plugin:ember-suave/recommended'
    ],
    env: {
        browser: true
    },
    rules: {
        indent: ['error', 4],
        'space-before-function-paren': ['error', {anonymous: 'ignore', named: 'never'}],
        'object-curly-spacing': ['error', 'never'],
        'array-bracket-spacing': ['error', 'never'],
        'key-spacing': ['error', {mode: 'minimum'}],
        'keyword-spacing': ['error', {overrides: {
            'catch': {'after': true}
        }}],
        'ember-suave/require-access-in-comments': 'off'
    },
    globals: {
        moment: false,
        validator: false
    }
};
```

**What did you do? Please include the actual source code causing the issue.**

Source code: master branch of https://github.com/TryGhost/Ghost-Admin

Steps to reproduce:
- clone the repo
- `npm install` (verify that the eslint-plugin-ember-suave is installed into node_modules)
- `eslint app`

**What did you expect to happen?**
I expected ESLint to run.

**What actually happened? Please include the actual, raw output from ESLint.**
Raw error output:
```
Cannot find module 'eslint-plugin-ember-suave'
Referenced from: /Users/acburdine/Sites/Ghost/eslint-bug-test/Ghost-Admin/.eslintrc.js
Error: Cannot find module 'eslint-plugin-ember-suave'
Referenced from: /Users/acburdine/Sites/Ghost/eslint-bug-test/Ghost-Admin/.eslintrc.js
    at Object.resolve (/Users/acburdine/.nvm/versions/node/v4.6.0/lib/node_modules/eslint/lib/util/module-resolver.js:74:19)
    at resolve (/Users/acburdine/.nvm/versions/node/v4.6.0/lib/node_modules/eslint/lib/config/config-file.js:473:33)
    at load (/Users/acburdine/.nvm/versions/node/v4.6.0/lib/node_modules/eslint/lib/config/config-file.js:495:26)
    at /Users/acburdine/.nvm/versions/node/v4.6.0/lib/node_modules/eslint/lib/config/config-file.js:391:36
    at Array.reduceRight (native)
    at applyExtends (/Users/acburdine/.nvm/versions/node/v4.6.0/lib/node_modules/eslint/lib/config/config-file.js:362:28)
    at Object.load (/Users/acburdine/.nvm/versions/node/v4.6.0/lib/node_modules/eslint/lib/config/config-file.js:529:22)
    at loadConfig (/Users/acburdine/.nvm/versions/node/v4.6.0/lib/node_modules/eslint/lib/config.js:63:33)
    at getLocalConfig (/Users/acburdine/.nvm/versions/node/v4.6.0/lib/node_modules/eslint/lib/config.js:130:29)
    at Config.options.env.globals.Config.getConfig (/Users/acburdine/.nvm/versions/node/v4.6.0/lib/node_modules/eslint/lib/config.js:256:22)
```

**Additional Information:**
I also experienced the same issue with https://github.com/jgwhite/ember-sortable (after adding the same config). Initially I thought this was because both depended indirectly on `eslint` through `ember-cli-eslint`, and that does fix the issue with atom-linter, but I think the issue is related to node's resolution process.

Potential related issue: #7083

**Comment by ilyavolodin** [comment] 2016-11-27 15:32
You are seeing this problem due to the way you are running ESLint. Instead of running `eslint app` try running `node_modules/.bin/eslint app` and see if that resolves the issue. `eslint app` will execute globally installed copy of ESLint, in order for that to work, your plugin also needs to be installed globally.

**Comment by acburdine** [comment] 2016-11-27 15:45
That's what I thought - however I do think there's room for improvement here. Something that ember-cli does to accomplish a similar task is check if there's a local ember-cli version and use that one if it exists rather than the global version.

Definitely a different use-case, but the same pattern should work here. Would be willing to make a PR if desired :smile:

**Comment by kaicataldo** [comment] 2016-11-29 02:31
@acburdine Thanks for the suggestion. A little background: the team [has discussed this before](https://github.com/eslint/eslint/issues/5874), and the conclusion then was not to include this behavior in ESLint at the time of making that issue. I'm not entirely against it, though I do think it could lead to some confusion (i.e. what happens if you forget to `npm install` and accidentally use the globally-installed version?).

For an immediately available solution, please check out https://github.com/mysticatea/eslint-cli

**Comment by acburdine** [comment] 2016-11-29 03:20
@kaicataldo that does make sense - although I definitely see a way to counteract the confusion.

Ideal flow (in my opinion)
- User runs global `eslint`
- eslint checks if there's eslint installed to the current working directory's node_modules folder
- If eslint is installed locally, run the local version (e.g. the end result would be the same as `./node_modules/.bin/eslint`)
- if not installed locally, default behavior applies

**Comment by kaicataldo** [comment] 2016-11-29 03:32
I believe that's what the `eslint-cli` plugin does, assuming default behavior means running the globally installed version of ESLint. I still think we run the risk of making it harder to know if you ran the right version of ESLint or not if you have local and global installations, but as I said, not personally completely against the idea!

For what it's worth, it looks like JSCS has this behavior - curious if members of the JSCS team have any thoughts?

**Comment by markelog** [comment] 2016-11-30 10:03
Not only JSCS, but others tools as well, from top of my head, grunt/gulp maybe even jshint. 

Worked as charm and you know, doing`./node_modules/.bin/eslint` is kinda ugly

**Comment by alberto** [comment] 2016-12-06 21:46
@markrelog the less ugly option is to add an eslint task to package.json and do `npm run eslint`

**Comment by markelog** [comment] 2016-12-06 21:59
Obviously, but that is much more confusing than ugliness of previous approach

**Comment by not-an-aardvark** [comment] 2016-12-06 22:09
I would be in favor of using the JSCS/grunt/gulp approach of having the global installation defer to the local installation if it exists. We can always have a `--use-global-eslint` option or something if people want to override the behavior.

**Comment by ilyavolodin** [comment] 2016-12-06 23:40
@not-an-aardvark In general I would support it, but before acting on this, I suggest digging through old threads. I'm pretty sure there has been multiple PRs that did just that (make global install fallback to local if one is found), and they were closed without being merged. I don't remember what were the reasons, but before putting in time into doing the work, I would check first.

**Comment by not-an-aardvark** [comment] 2016-12-07 04:23
Previous discussions that I've found:

https://github.com/eslint/eslint/issues/5874, https://github.com/eslint/eslint/issues/6732, https://github.com/eslint/eslint/issues/3993

Let me know if there are any others that you had in mind. For what it's worth, reading these discussions has not changed my opinion that we should use the JSCS/grunt/gulp approach.

**Comment by mysticatea** [comment] 2016-12-07 04:24
In that case, I'd like to check the difference of versions between global and local. If the versions are different then:

- it should print the warning.
- or it should print the error then fail.

----

Also, I have a concern about plugins. The same command `eslint` would choose global-installed plugins or local-installed plugins silently due to the installation condition of eslint. It might cause new confusing. I think better if people can distinguish which eslint is running visually.

----

Another option, I think good if we support `eslint-cli` officially.

**Comment by not-an-aardvark** [comment] 2016-12-07 04:31
@mysticatea I don't understand the issue with versions. Why would it be necessary to print a warning if the versions are different? The global version of `eslint` would pass everything to the local version, so running `eslint -v` would be the same as running `node_modules/.bin/eslint -v`.

I would be fine with officially supporting `eslint-cli`, but I think it would be better if we could solve the problem within ESLint itself. I think it would be annoying to require users to install two different modules.

**Comment by ilyavolodin** [comment] 2016-12-07 16:54
@not-an-aardvark That would only work if you are running global version of eslint from inside the directory that has local version installed. See this [post](https://github.com/eslint/eslint/issues/3993#issuecomment-145271298) for more context.

**Comment by markelog** [comment] 2016-12-07 17:14
I don't think we need to invent anything like print warnings, versions.... or even consider the edge cases at this point.

Just to follow already created path by other tools would be the best way forward in my opinion, there is subtle differences between them of course, so i would just propose to just choose one or the implementation.

We can even choose to use a module for that – https://github.com/js-cli/js-liftoff (/cc @tkellen).
In any case this problem was solved many times before, no need in new wheels and stuff

**Comment by not-an-aardvark** [comment] 2017-11-03 20:48
Closing because the current behavior is working as intended. There is more discussion about local/global installations in https://github.com/eslint/eslint/issues/6732.

**Closed by not-an-aardvark** 2017-11-03 20:48 UTC
Labels: question
