### ISSUE TITLE
bug(eslint@0.17.0): no-unused-vars throw TypeError on a ImportDefaultSpecifier node type

### ISSUE THREAD

**Issue by douglasduteil** [eslint/eslint#2066] opened 2015-03-16 12:21 UTC
Hi 

**no-unused-vars** seems to not support import nodes.

Example :

```js
// .eslintrc
{
    "ecmaFeatures": {
        "modules": true
    }
}
```

```js
// foo.js
import foo from 'foo';
```

I have a type error 

```
/bla/bla/bla/eslint/lib/rules/no-unused-vars.js:43
            if (definition.type === "VariableDeclarator") {
                          ^
TypeError: Cannot read property 'type' of undefined
    at isExported (/bla/bla/bla/eslint/lib/rules/no-unused-vars.js:43:27)
    at EventEmitter.Program:exit (/bla/bla/bla/eslint/lib/rules/no-unused-vars.js:127:70)
```

`definition` [L38](https://github.com/eslint/eslint/blob/v0.17.0/lib/rules/no-unused-vars.js#L38) is  an `ImportDefaultSpecifier` node (with no `definition.node`)

**Comment by ilyavolodin** [comment] 2015-03-16 14:09
Duplicate of #2042

**Closed by ilyavolodin** 2015-03-16 14:09 UTC
