### ISSUE TITLE
rules/no-use-before-define.js: TypeError: Cannot read property '1' of undefined

### ISSUE THREAD

**Issue by weijarz** [eslint/eslint#8630] opened 2017-05-20 07:58 UTC
**Tell us about your environment**

* **ESLint Version:**
3.19.0

* **Node Version:**
v7.10.0

* **npm Version:**
4.5.0

**What parser (default, Babel-ESLint, etc.) are you using?**
`Babel-ESLint`

**Please show your full configuration:**

FILE: .eslintrc.json
```json
{
  "parser": "babel-eslint",
  "extends": "standard"
}
```

**What did you do? Please include the actual source code causing the issue.**

```js
// @flow
type FieldOptions<T> = {| defaultValue: T |}
type DateFieldOptions = {| ...FieldOptions<Date> |}
```

**What did you expect to happen?**

**What actually happened? Please include the actual, raw output from ESLint.**
```
[eslintbug]$ node_modules/.bin/eslint fields.js 
Cannot read property '1' of undefined
TypeError: Cannot read property '1' of undefined
    at scope.references.forEach.reference (/tmp/eslintbug/node_modules/eslint/lib/rules/no-use-before-define.js:206:83)
    at Array.forEach (native)
    at findVariablesInScope (/tmp/eslintbug/node_modules/eslint/lib/rules/no-use-before-define.js:194:30)
    at EventEmitter.Program:exit (/tmp/eslintbug/node_modules/eslint/lib/rules/no-use-before-define.js:242:21)
    at emitOne (events.js:101:20)
    at EventEmitter.emit (events.js:191:7)
    at NodeEventGenerator.applySelector (/tmp/eslintbug/node_modules/eslint/lib/util/node-event-generator.js:265:26)
    at NodeEventGenerator.applySelectors (/tmp/eslintbug/node_modules/eslint/lib/util/node-event-generator.js:294:22)
    at NodeEventGenerator.leaveNode (/tmp/eslintbug/node_modules/eslint/lib/util/node-event-generator.js:317:14)
    at CodePathAnalyzer.leaveNode (/tmp/eslintbug/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:622:23)
```

**Comment by platinumazure** [comment] 2017-05-20 13:25
Guess I'll dig in. Thanks for the report!

**Comment by platinumazure** [comment] 2017-05-20 15:11
@weijarz I've written a defensive patch, which I'll have to figure out how to test properly. However, I think the root cause is that for whatever reason, babel-eslint and/or escope are not providing sufficient range information during parsing, so when we try to do a location compare (to see if a variable use is happening before its definition), we get the exception shown in your initial report.

Would you be able to try my patch out, so I know if the patch is at least directionally correct? If not, no worries, I'll figure out how to test this properly at some point.

**Comment by weijarz** [comment] 2017-05-20 15:22
@platinumazure  Thanks, your patch worked well.

**Comment by mysticatea** [comment] 2017-05-20 15:23
@platinumazure Thank you very much.

[This `Identifier` node](https://github.com/eslint/eslint/commit/d073ffe9839499deeb460eb98e9ace70be36a185#diff-c7be3a8e8fbaa5a588ac3485a8b8639fR829) looks to not have `range` property, so I think this is a bug of `babel-eslint`.

**Comment by platinumazure** [comment] 2017-05-20 15:28
Nice find, @mysticatea, knew it was something like that. Honestly I'd much prefer that `babel-eslint` fix this if possible, so I'm not 100% sure I actually want to submit this patch.

I'll open an issue over there later today. Thanks!

**Comment by platinumazure** [comment] 2017-05-20 18:53
Opened babel/babel-eslint#473 with my findings.

**Comment by ilyavolodin** [comment] 2017-05-21 18:20
Closing this issue, as it's a problem with babel-eslint.

**Closed by ilyavolodin** 2017-05-21 18:20 UTC
Labels: bug, evaluating, rule
