### ISSUE TITLE
Lint rules not showing up on terminal on Node7 and Webpack 1.13.3

### ISSUE THREAD

**Issue by HeberLZ** [eslint/eslint#7475] opened 2016-10-28 23:21 UTC
**Tell us about your environment**
macOS Sierra 10.12
- **ESLint Version:**
  3.9.0
- **Node Version:**
  7.0.0
- **npm Version:**
  3.10.9

**What parser (default, Babel-ESLint, etc.) are you using?**
eslint-loader
**Please show your full configuration:**

```
{
  "env": {
    "browser": true,
    "node": true,
    "es6": true,
    "mocha": true
  },

  "plugins": ["react"],

  "parserOptions": {
    "ecmaVersion": 6,
    "ecmaFeatures": {
      "jsx": true
    },
    "sourceType": "module"
  },

  "extends": [
    "eslint:recommended",
    "plugin:react/recommended"
  ],

  "rules": {
    // possible errors
    "no-console": 0,

    // best practice
    "no-alert": 2,
    "dot-notation": 2,
    "eqeqeq": 2,
    "guard-for-in": 2,
    "no-caller": 2,
    "no-eval": 2,
    "no-extend-native": 2,
    "no-extra-bind": 2,
    "no-extra-label": 2,
    "no-implicit-globals": 2,
    "no-implied-eval": 2,
    "no-invalid-this": 2,
    "no-labels": 2,
    "no-self-compare": 2,
    "no-unmodified-loop-condition": 2,
    "no-useless-call": 2,
    "no-void": 2,
    "no-with": 2,
    "radix": 2,
    "vars-on-top": 2,

    // variables
    "no-shadow": 2,
    "no-catch-shadow": 2,
    "no-undefined": 2,
    "no-use-before-define": 2,

    // stylistic
    "array-bracket-spacing": [2, "never"],
    "block-spacing": [2, "never"],
    "brace-style": [2, "1tbs"],
    "comma-dangle": [2, "never"],
    "indent": [2, 4],
    "jsx-quotes": [2, "prefer-single"],
    "key-spacing": 2,
    "keyword-spacing": 2,
    "max-len": [2, 120],
    "no-bitwise": 2,
    "no-continue": 2,
    "no-inline-comments": 2,
    "no-lonely-if": 2,
    "no-new-object": 2,
    "no-plusplus": 2,
    "no-whitespace-before-property": 2,
    "operator-assignment": [2, "always"],
    "quotes": [2, "single", {"avoidEscape": true, "allowTemplateLiterals": true}],
    "semi": [2, "always"],
    "quote-props": [2, "as-needed"],
    "space-before-blocks": 2,
    "space-before-function-paren": [2, "never"],
    "space-in-parens": [2, "never"],

    //es6
    "no-duplicate-imports": 2,
    "no-var": 2,
    "prefer-const": 2,
    "prefer-rest-params": 2,
    "prefer-spread": 2,
    "require-yield": 2,

  }
}

```

**What did you do? Please include the actual source code causing the issue.**
We have the lint task bound to the build so that it fails whenever there is a lint recommendation, the thing is that when we updated our dependencies new rules are being checked by default and were making our build fail, but we didn't know until we debugged webpack's code and noticed that eslint was the one exiting with code 1, because some lint rules failed but those failed rules never showed up on the terminal itself.

``` js

[a,
b,
c]

```

**What did you expect to happen?**
The terminal should have shown what the lint errors actually were in order to fix them

**What actually happened? Please include the actual, raw output from ESLint.**
It just exit with code 1 without generating any output

**Comment by not-an-aardvark** [comment] 2016-10-28 23:24
Thanks for the report. It looks like the code example you provided is supposed to cause a linting error (it previously didn't due to a bug; see https://github.com/eslint/eslint/pull/7237).

Just to confirm, what happens if you add some other code that is a linting error in both versions? Does it still produce output in 3.8 and not in 3.9?

**Comment by HeberLZ** [comment] 2016-10-28 23:46
Either old nor new rules are showing up on the terminal

**Comment by not-an-aardvark** [comment] 2016-10-29 04:34
Thanks for the info. Do you think you could provide a reproduction instructions for this? It's a bit difficult to assess and fix the issue at the moment, since I can't reproduce it locally.

**Comment by kaicataldo** [comment] 2016-10-30 01:27
It would be helpful to know what versions of `eslint-loader` and `webpack` you're using, as well as how you're running Webpack. I've seen issues with Webpack 2 + Gulp swallowing errors (though not with ESLint).

**Comment by HeberLZ** [comment] 2016-10-31 18:19
Sure, here are the dependencies.

"gulp": "^3.9.1",
"eslint": "^3.8.1",
"eslint-loader": "^1.6.0",
"eslint-plugin-react": "^6.4.1",
"webpack": "^1.13.3",

I've kept on checking to see why it's not working, and it seems to be related to node7. Tried downgrading all dependencies and the error description of eslint is still not shown. I've modified Webpack's source code locally to be able to see the errors on the terminal meanwhile while i try to find the source of the issue.

Reverted back to node6 on a docker image and the errors show up again :S

One other thing to note, gulp is executing webpack which is executing eslint. On other microservices we're calling eslint directly from gulp and it works as expected, it's just when webpack executes eslint on node7

**Comment by HeberLZ** [comment] 2016-10-31 18:21
Most likely this is an issue on eslint-loader with node7

**Comment by platinumazure** [comment] 2016-10-31 18:24
Hi @HeberLZ! Given [this comment](https://github.com/eslint/eslint/issues/7475#issuecomment-257054313), I don't think the title of this issue is accurate anymore. Could you please update the title to more closely reflect the issue you are experiencing?

And at this point, is there any evidence that ESLint 3.9.0 is actually causing any of your issues?

Thanks!

**Comment by HeberLZ** [comment] 2016-10-31 19:04
Title updated, still trying to figure out which layer is the one failing to close this issue, eslint-loader is exiting due to an intended uncaught error with the right data, so most likely the issue seems to be around webpack or one of it's dependencies on node7

**Comment by ilyavolodin** [comment] 2016-10-31 19:17
@HeberLZ We had some issues with node 7, I think we resolved them, but we are still not testing any of our code in node 7 yet (we really should start), so it's possible that it's ESLint's issue with Node 7 (or rather one of our dependencies).

**Comment by not-an-aardvark** [comment] 2016-10-31 19:18
I think it's unlikely that this is related to the issues we've had with Node 7; one of our devDependencies wasn't working with Node 7 (this is fixed in https://github.com/eslint/eslint/pull/7486), but the rest of our build works fine.

**Comment by HeberLZ** [comment] 2016-10-31 19:23
Based on everything i've checked so far, it seems like the issue is not on your layer, the error messages from eslint are being generated correctly, are being grabbed by eslint-loader, reformatted, and emitted as an error to webpack, but it's like if webpack were not handling the emitted error at all, throwing an error but without rendering the description emitted by eslint-loader. I'm going to close this issue for the time being as the lint messages are arriving correctly to the immediate external dependency, making this 99% not a bug on this layer

**Closed** 2016-10-31 19:24 UTC
Labels: bug, core, evaluating
