### ISSUE TITLE
Unable to disable es6 env inline

### ISSUE THREAD

**Issue by remko** [eslint/eslint#2604] opened 2015-05-23 09:37 UTC
I seem to be unable to disable an `env` for a single file. This feature isn't documented (the docs only mention enabling envs by doing `eslint-env es6` without any parameters), but according to #2072, the following should give a file that doesn't validate:

     /* eslint-env es6:false */
     const x = 1;

However, the above file validates, which it shouldn't. (removing the `es6: true` setting from my `.eslintrc` indeed makes the file no longer validate.

**Comment by ilyavolodin** [comment] 2015-05-23 14:29
This is a duplicate of #2134 Unfortunately, we do not currently have a fix for enabling/disabling es6 environment inline, as es6 environment is a special case and controls parser. #2134 is sill open to track this issue, so closing this.

**Closed by ilyavolodin** 2015-05-23 14:29 UTC
