### ISSUE TITLE
Bug: no-loss-of-precision incorrectly flags that number literal will lose precision at runtime

### ISSUE THREAD

**Issue by amayer42** [eslint/eslint#16989] opened 2023-03-15 18:51 UTC
### Environment

I included a demo site link in the "What did you do?" section. It's not tied to my local environment.

### What parser are you using?

Default (Espree)

### What did you do?

[Demo](https://eslint.org/play/#eyJ0ZXh0IjoiY29uc3QgYSA9IC05NzI2LjYyMjY4MDY2NDA2MjtcbiIsIm9wdGlvbnMiOnsicGFyc2VyT3B0aW9ucyI6eyJlY21hVmVyc2lvbiI6ImxhdGVzdCIsInNvdXJjZVR5cGUiOiJzY3JpcHQiLCJlY21hRmVhdHVyZXMiOnt9fSwicnVsZXMiOnsibm8tbG9zcy1vZi1wcmVjaXNpb24iOlsiZXJyb3IiXX0sImVudiI6eyJlczYiOnRydWV9fX0=)

### What did you expect to happen?

I received a `no-loss-of-precision` error for the literal `-9726.622680664062`, but do not think that this literal should be considered incorrect according to this rule. 

### What actually happened?

When I check the `Number` that `-9726.622680664062` resolves to at runtime, I do not see any loss of precision.

Firefox Output
![image](https://user-images.githubusercontent.com/5626443/225410298-37410fd3-3086-45be-92db-3fb4ab022ebd.png)

Node Output
![image](https://user-images.githubusercontent.com/5626443/225410772-22c39db9-cb13-4af9-87dc-acbd0537dae4.png)

### Participation

- [x] I am willing to submit a pull request for this issue.

### Additional comments

This isn't a terribly big deal but I just figured that if one of the random numbers I was using in a test case was failing this rule, there's a good chance that the logic for this rule must be slightly flawed (or I just don't understand something).

I'm willing to dabble with and submit a PR, but I've never contributed to this repo before, so any guidance would be welcome. If someone else is more familiar and has the time to look, I'd probably defer to them.

**Comment by Rec0iL99** [comment] 2023-03-16 05:19
@amayer42 thanks for opening the issue. The `no-loss-of-precision` checks if a number loses precision by doing, `"-9726.622680664062" === -9726.622680664062.toPrecision(16)` and the rule reports if this gives `false`.

The rule is working as intended as `"-9726.622680664062" === -9726.622680664062.toPrecision(16)` returns `false`.

The value is preserved in runtime only when it isn't manipulated in some form, but loses precision when it is (hence the rule is reported)! This https://github.com/eslint/eslint/issues/15767#issuecomment-1093041405 has examples for better understanding. 

Duplicate of #15767. The original [proposal](https://github.com/eslint/eslint/issues/11279) for the `no-loss-of-precision` rule.

Thanks for using ESLint.

**Closed by Rec0iL99** 2023-03-16 05:19 UTC
Labels: bug, repro:needed

**Comment by amayer42** [comment] 2023-03-16 17:41
That's so interesting, I had the same misunderstanding. This makes a bit more sense now. Really appreciate the link to that comment on that issue.

Sorry for posting a duplicate. I should have been more thorough when searching through the issues.
