### ISSUE TITLE
Error: Cannot find module 'through'

### ISSUE THREAD

**Issue by renanvaz** [eslint/eslint#5691] opened 2016-03-26 22:52 UTC
eslint installed today (v2.5.1). And i got this error on try to init:

`$ eslint --init`

> Cannot find module 'through'
> Error: Cannot find module 'through'
>     at Function.Module._resolveFilename (module.js:325:15)
>     at Function.Module._load (module.js:276:25)
>     at Module.require (module.js:353:17)
>     at require (internal/module.js:12:17)
>     at Object.<anonymous> (D:\www\labs\arduino-mqqt-api\node_modules\eslint\node_modules\inquirer\lib\ui\bottom-bar.js:6:15)
>     at Module._compile (module.js:409:26)
>     at Object.Module._extensions..js (module.js:416:10)
>     at Module.load (module.js:343:32)
>     at Function.Module._load (module.js:300:12)
>     at Module.require (module.js:353:17)
>     at require (internal/module.js:12:17)

**Comment by hzoo** [comment] 2016-03-26 23:27
Thanks for reporting! This is similar to https://github.com/eslint/eslint/issues/5687 and others. I think it's recommend to use v2.4.0 for `--init` right now

**Comment by ilyavolodin** [comment] 2016-03-26 23:37
This is a known issue. We've had trouble with npm with the latest release, and `--init` is currently broken. We'll be doing patch release sometime next week to fix it. Closing as a duplicate of #5687

**Closed by ilyavolodin** 2016-03-26 23:37 UTC
Labels: triage
