### ISSUE TITLE
Bug: (TypeError: Cannot read properties of undefined (reading 'loc'))

### ISSUE THREAD

**Issue by c10342** [eslint/eslint#16219] opened 2022-08-19 07:04 UTC
### Environment

Node version: v16.15.1
npm version: v8.17.0
Local ESLint version: v8.22.0
Global ESLint version: Not found
Operating System: win32 10.0.22000

### What parser are you using?

@typescript-eslint/parser

### What did you do?

<details>
<summary>Configuration</summary>

```
<!-- Paste your configuration here -->
```
</details>

```js
<!-- Paste your code here -->
```

### What did you expect to happen?

There should be no errors

### What actually happened?

when i input `const`,the following error will appear

![1660891456(1)](https://user-images.githubusercontent.com/32448454/185560786-286005af-0743-43af-89cd-b761fdaf5300.png)

### Participation

- [ ] I am willing to submit a pull request for this issue.

### Additional comments

I am using vscode and eslint. When I enter const in the TS file, an error will be reported。

The error occurred on the node_ modules\eslint\lib\rules\indent.js，line 1513

I tried to fix it

`
if (node.declarations[node.declarations.length - 1]?.loc.start.line > node.loc.start.line) {
} 
`

Then this error will not occur

**Comment by joaomaranhao** [comment] 2022-08-20 00:40
You can add a rule to your eslint configuration file that solves that issue.

rules: {
  "indent": "off"
}

**Comment by mdjermanovic** [comment] 2022-08-22 18:04
Duplicate of https://github.com/eslint/eslint/issues/14538

This is an issue with `@typescript-eslint/parser` that allows invalid syntax: https://github.com/typescript-eslint/typescript-eslint/issues/1852

@c10342 until this is fixed in `@typescript-eslint/parser`, you can configure the `indent` rule as described in https://github.com/eslint/eslint/issues/14538#issuecomment-862280037 to avoid these errors.

**Closed by mdjermanovic** 2022-08-22 18:04 UTC
Labels: 3rd party plugin
