### ISSUE TITLE
Ability to validate rules?

### ISSUE THREAD

**Issue by DylanPiercey** [eslint/eslint#2142] opened 2015-03-25 14:13 UTC
Is there a way to run a .eslintrc/config through a validator that would tell me if there are typo's in any of my rules?

Or at-least export the selected rules from the demo.

**Comment by gyandeeps** [comment] 2015-03-25 15:02
I like the idea. 
To add to it, it can also tell which rules are deprecated.

**Comment by DylanPiercey** [comment] 2015-03-25 15:23
It would also be nice if it could tell if the options are valid.

IE:
```javascript
   {"yoda": true}
   // should be
   {"yoda": [2, "always"]}
```

**Comment by nzakas** [comment] 2015-03-25 15:53
Duplicate of #967.

**Closed by nzakas** 2015-03-25 15:53 UTC
