### ISSUE TITLE
Upgrade to globals 15.x

### ISSUE THREAD

**Issue by fhanggi** [eslint/eslint#19209] opened 2024-12-03 19:30 UTC
### ESLint version

9.16

### What problem do you want to solve?

When i run eslint i get this error
TypeError: Key "languageOptions": Key "globals": Global "AudioWorkletGlobalScope " has leading or trailing whitespace.

### What do you think is the correct solution?

This issue was also posted in the globals git repo. They say they fixed  this with version 15.x
https://github.com/sindresorhus/globals/issues/239

however it seems eslint is still using globals version 14

├─┬ eslint@9.16.0
│ └─┬ @eslint/eslintrc@3.2.0
│   └── globals@14.0.0

can you please upgrade to the latest globals version?
Thank you

### Participation

- [ ] I am willing to submit a pull request for this change.

**Comment by mdjermanovic** [comment] 2024-12-03 20:37
Hi @fhanggi, thanks for the issue!

The `"AudioWorkletGlobalScope "` problem was fixed in globals [v13.12.1](https://github.com/sindresorhus/globals/releases/tag/v13.12.1).

Can you please provide a repro repo where this error occurs with ESLint v9.16.0?

**Comment by Xenope** [comment] 2024-12-04 11:28
Hi, I'm having the same issue today with eslint 9.16

**Comment by mdjermanovic** [comment] 2024-12-04 13:06
@Xenope, please provide a minimal reproducible example (StackBlitz or GitHub repo) so we can take a look.

**Comment by fhanggi** [comment] 2024-12-04 18:35
@mdjermanovic 

here you go
https://stackblitz.com/edit/stackblitz-starters-xcrnrt?file=package.json

please note this is not a working react app. I just copied the important files to reproduce this.
after I run npm install and then npm run lint I get that error

![Image](https://github.com/user-attachments/assets/818a034d-1698-410c-a965-1007dc1fe207)

**Comment by fhanggi** [comment] 2024-12-04 19:10
btw if you run npm ls globals you can see that eslint and other packages are still using a version of globals below 15.
so i assume everyone would need to go to 15.x for this issue to go away. that could take a long time

 i wonder if you could find another way to fix this issue on the eslint side?

~/projects/stackblitz-starters-xcrnrt 23s
❯ npm ls globals
cov-poc@1.2.2 /home/projects/stackblitz-starters-xcrnrt
+-- @vitejs/plugin-react@4.3.4
| `-- @babel/core@7.26.0
|   `-- @babel/traverse@7.25.9
|     `-- globals@11.12.0
+-- eslint@9.16.0
| `-- @eslint/eslintrc@3.2.0
|   `-- globals@14.0.0
`-- vite-plugin-pwa@0.21.1
  `-- workbox-build@7.3.0
    `-- @babel/preset-env@7.26.0
      `-- @babel/plugin-transform-classes@7.25.9
        `-- globals@11.12.0 deduped

**Comment by mdjermanovic** [comment] 2024-12-04 20:04
Since your project is using the `globals` package directly (it is not loaded by ESLint, but by your configuration file), you should install it as a dev dependency, and then you can use the latest version from your configuration file.

```diff
  "devDependencies": {
    "@vitejs/plugin-react": "4.3.4",
    "eslint": "9.16.0",
    "eslint-plugin-import": "2.31.0",
    "eslint-plugin-react": "7.37.2",
    "eslint-plugin-react-hooks": "5.0.0",
    "eslint-plugin-react-refresh": "0.4.16",
+   "globals": "^15.13.0",
    "vite": "6.0.2",
    "vite-plugin-pwa": "0.21.1"
  }
```

**Closed by mdjermanovic** 2024-12-04 20:04 UTC
Labels: enhancement, core, needs info

**Comment by anmiles** [comment] 2025-05-18 15:38
Another trick that helped me is re-installing the only dependency that contain outdated `globals`. In my case this was `@vitejs/plugin-react`.

I compared changes in package-lock.json file after reinstalling:
- `node_modules/@babel/traverse/node_modules/globals "version": "11.12.0",` disappeared
- `node_modules/@eslint/eslintrc/node_modules/globals "version": "14.0.0"` appeared
- `node_modules/globals` changed from 11.12.0 to 14.0.0.

This really depends on order of installing dependencies. I experienced this problem after cleanup and reinstalling everything.

**Comment by anmiles** [comment] 2025-05-18 15:46
Here is a trick that helped me.

1. Run `npm ls globals` to find out what dependency brings old `globals`. In my case this was `@vitejs/plugin-react`.
2. Remove `package-lock.json`, remove `node_modules`
3. Erase this dependency from the `package.json`
4. Run `npm install`. There won't be that dependency and there won't be old `globals` at all.
5. Install that dependency. It won't bring old `globals`!

I compared changes in package-lock.json file after reinstalling:
- `node_modules/@babel/traverse/node_modules/globals "version": "11.12.0",` disappeared
- `node_modules/@eslint/eslintrc/node_modules/globals "version": "14.0.0"` appeared
- `node_modules/globals` changed from 11.12.0 to 14.0.0.
