### ISSUE TITLE
Bug: when removing blank line between functions in ts interface, eslint is not working 

### ISSUE THREAD

**Issue by hkaraoglu** [eslint/eslint#17745] opened 2023-11-10 09:10 UTC
### Environment

Node version: v18.17.0
npm version: 9.8.1
Local ESLint version: v8.42.0
Global ESLint version: v8.49.0
Operating System:  Mac OS Venture 13.0 

### What parser are you using?

@typescript-eslint/parser

### What did you do?

<summary>
When I remove blank line between getExample and getExamples functions in an interface, eslint doesn't work. 
</summary>

```
"padding-line-between-statements": "off",
"@typescript-eslint/padding-line-between-statements": [
  "error",
  {
    "blankLine": "always",
    "prev": "*",
    "next": ["interface", "type"]
  }
],
```

```js
export interface IExampleService
{
  createExample(requestModel: CreateExampleRequestModel): Promise<CreateExampleResponseModel>;

  getExample(id: string): Promise<GetExampleResponseModel>;
  getExamples(requestModel: GetExamplesRequestModel): Promise<GetExamplesResponseModel>;

  updateExample(requestModel: UpdateExampleRequestModel): Promise<UpdateExampleResponseModel>;

  deleteExample(id: string): Promise<boolean>;
}
```

### What did you expect to happen?

```
export interface IExampleService
{
  createExample(requestModel: CreateExampleRequestModel): Promise<CreateExampleResponseModel>;

  getExample(id: string): Promise<GetExampleResponseModel>;

  getExamples(requestModel: GetExamplesRequestModel): Promise<GetExamplesResponseModel>;

  updateExample(requestModel: UpdateExampleRequestModel): Promise<UpdateExampleResponseModel>;

  deleteExample(id: string): Promise<boolean>;
}
```

### What actually happened?

```
export interface IExampleService
{
  createExample(requestModel: CreateExampleRequestModel): Promise<CreateExampleResponseModel>;

  getExample(id: string): Promise<GetExampleResponseModel>;
  getExamples(requestModel: GetExamplesRequestModel): Promise<GetExamplesResponseModel>;

  updateExample(requestModel: UpdateExampleRequestModel): Promise<UpdateExampleResponseModel>;

  deleteExample(id: string): Promise<boolean>;
}
```

### Link to Minimal Reproducible Example

.

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Rec0iL99** [comment] 2023-11-10 15:45
Hi @hkaraoglu, we require a reproducible example for bug reports as the template states. This is to better debug the issue and save time. 

I'm closing this since this is from a rule in [`typescript-eslint`](https://github.com/typescript-eslint/typescript-eslint) rather than ESLint itself. Please open an issue there.

**Closed by Rec0iL99** 2023-11-10 15:45 UTC
Labels: bug, repro:needed
