### ISSUE TITLE
RuleTester docs don't mention filename or settings being available

### ISSUE THREAD

**Issue by platinumazure** [eslint/eslint#6709] opened 2016-07-19 17:07 UTC
Per [discussion on Gitter chat](https://gitter.im/eslint/eslint?at=578e5db1ac85f2507acedd37), filename and settings are [valid RuleTester test options](https://github.com/eslint/eslint/blob/master/lib/testers/rule-tester.js#L69-L73), but this is not mentioned in the [Working with Rules](http://eslint.org/docs/developer-guide/working-with-rules) documentation.

It would be good to write (small) sections in the documentation to address this.

**Comment by nzakas** [comment] 2016-07-19 18:54
Partly a duplicate of #4810.

In the future, please provide more of a description so we don't have to jump between links. If you can provide the information directly in the comment, that's a lot more useful.

**Comment by platinumazure** [comment] 2016-07-19 19:00
@nzakas Apologies, I was only trying to provide citations for my claims. I had thought that the description was otherwise self-sufficient, but I will try to be more clear in the future.

**Closed** 2016-07-21 16:10 UTC
Labels: core, documentation, enhancement, evaluating
