### ISSUE TITLE
Failed to load plugin 'import' declared in '.eslintrc » eslint-config-airbnb > Cannot find module 'eslint/lib/util/source-code'

### ISSUE THREAD

**Issue by nicewaytodoit** [eslint/eslint#11990] opened 2019-07-15 06:54 UTC
I am getting following error when Eslint plugin is running:

[Info  - 07:43:14] ESLint library loaded from: c:\proj\node_modules\eslint\lib\api.js
[Error - 07:43:25] Failed to load plugin 'import' declared in '.eslintrc » eslint-config-airbnb » C:\proj\node_modules\eslint-config-airbnb-base\index.js » C:\proj\node_modules\eslint-config-airbnb-base\rules\imports.js': Cannot find module 'eslint/lib/util/source-code'
Happened while validating C:\proj\src\Game\Game.jsx

```
"devDependencies": {
    "eslint": "^6.0.1",
    "eslint-config-airbnb": "^17.1.1",
    "eslint-plugin-import": "^2.18.0",
    "eslint-plugin-jsx-a11y": "^6.2.3",
    "eslint-plugin-jest": "^22.7.2",
    "eslint-plugin-react": "^7.14.2",
    "node-sass": "^4.12.0"
  },
```

```
$ yarn -v 1.13.0
$ npm -v 6.10.1
$ node v10.15.0
```

Project is done in react, and all packages are updated globally to most recent version.

**Comment by ljharb** [comment] 2019-07-15 07:12
The airbnb config requires eslint 5 at this time. npm ls should show you that your dep graph is invalid.

**Comment by g-plane** [comment] 2019-07-15 07:13
So this issue should be from `eslint-config-airbnb`, not ESLint itself.

**Comment by ljharb** [comment] 2019-07-15 07:14
The issue is the user installing incompatible versions :-)

**Comment by nicewaytodoit** [comment] 2019-07-15 14:31
User issue :D, or lazy developer not implementing necessary things ?!

**Comment by platinumazure** [comment] 2019-07-15 14:42
Closing as this is not an issue with ESLint.

eslint-config-airbnb will presumably publish a new version when they reach compatibility with eslint@6.x. I'm sure there's an issue on the eslint-config-airbnb repository you could use for tracking that eventual release.

**Closed by platinumazure** 2019-07-15 14:42 UTC
Labels: question

**Comment by nicewaytodoit** [comment] 2019-07-15 19:39
I have reversed not to 
    "eslint": "5.16.0",
    "eslint-config-airbnb": "^17.1.1",
And still getting same issue ?!

**Comment by platinumazure** [comment] 2019-07-15 19:45
@nicewaytodoit Please open an [issue for the Airbnb folks](https://github.com/airbnb/javascript/issues/new). Thanks!
