### ISSUE TITLE
Change Request: Support setting multiple output formats, either in CLI or in Config

### ISSUE THREAD

**Issue by MWhite-22** [eslint/eslint#17260] opened 2023-06-09 14:02 UTC
### ESLint version

v8.42.0

### What problem do you want to solve?

Currently I have to install `eslint-output` and create an `.eslintoutputrc` file in order to get eslint to print multiple outputs. 

Our main reason for using this is so that during CI, we get the normal console output, but also a junit output for recording ongoing linting warnings, etc.

### What do you think is the correct solution?

It feels so silly to have to have a second dependency just to request two outputs. Building this functionality into eslint would be awesome. Making it a config option would also keep the cli command clean, but I would be happy with a cli flag as well.

### Participation

- [X] I am willing to submit a pull request for this change.

**Comment by Rec0iL99** [comment] 2023-06-12 23:48
duplicate of #14260.

**Closed by Rec0iL99** 2023-06-12 23:48 UTC
Labels: enhancement, core
