### ISSUE TITLE
  Odd indent error after updating to 1.4.1

### ISSUE THREAD

**Issue by pdehaan** [eslint/eslint#3799] opened 2015-09-14 16:29 UTC
Ref: https://github.com/eslint/eslint/issues/3591#issuecomment-139669222

---

I'm seeing some odd indenting rule behavior after updating to **eslint@1.4.1**.

```
$ ./node_modules/grunt-eslint/node_modules/.bin/eslint --version
v1.4.1

$ grunt eslint:tests
Running "eslint:tests" (eslint) task

/Users/pdehaan/dev/fxa-content-server/tests/functional/oauth_reset_password.js
  40:9  warning  Expected indentation of 6 space characters but found 8  indent

✖ 1 problem (0 errors, 1 warning)


Done, without errors.
```

And here's my code:
```js
37:      return client.signUp(email, PASSWORD, { preVerified: true })
38:        .then(function (result) {
39:          // do nothing
40:        })
41:        .then(function () {
42:          // clear localStorage to avoid polluting other tests.
43:          return FunctionalHelpers.clearBrowserState(self, {
44:            contentServer: true,
45:            '123done': true
46:          });
47:        });
```

And here's the code that ESLint expects:
```js
      return client.signUp(email, PASSWORD, { preVerified: true })
        .then(function (result) {
          // do nothing
      })  // <---------- THIS LINE RIGHT HERE
        .then(function () {
          // clear localStorage to avoid polluting other tests.
          return FunctionalHelpers.clearBrowserState(self, {
            contentServer: true,
            '123done': true
          });
        });
```

I think this is due to the fact that the only element in my function is a comment.

**Comment by nzakas** [comment] 2015-09-15 18:40
Possible duplicate of #3614

@gyandeeps ?

**Comment by gyandeeps** [comment] 2015-09-15 18:42
Its not a duplicate because the difference is empty body with comment vs non-empty body of function.

**Comment by nzakas** [comment] 2015-09-15 21:12
@pdehaan what version were you using prior to upgrading?

**Comment by pdehaan** [comment] 2015-09-15 21:23
@nzakas I believe it was **eslint@1.3.1**.

**Closed** 2015-09-18 15:51 UTC
Labels: accepted, bug, rule
