### ISSUE TITLE
Eslint is not catching noundef issue when variable is declared after first usage.

### ISSUE THREAD

**Issue by navalarya** [eslint/eslint#9034] opened 2017-07-29 06:19 UTC
MAC with VSCode

ESLint Version:2.2.0
Node Version:6.9.5
npm Version:5.0.4

What parser (default, Babel-ESLint, etc.) are you using? Babel - Eslint - 7.2.3
**Please show your full configuration:**

Eslint is not catching noundef issue when variable is declared below the usage.

e.g. 

foo.doSomething();

let foo = new Baz();

doesn't seem to throw any error.

**Comment by not-an-aardvark** [comment] 2017-07-29 06:22
Thanks for reporting. However, this is working as intended -- you should use the [`no-use-before-define`](http://eslint.org/docs/rules/no-use-before-define) rule instead.

**Comment by navalarya** [comment] 2017-07-29 10:56
I think this should be made compulsory. Since the code breaks during runtime but while development such issues are not caught.

**Comment by not-an-aardvark** [comment] 2017-07-29 11:00
"Compulsory" rules don't exist -- all rules are disabled by default. However, you can always enable it in a config file and make it a requirement for code in your projects.

**Comment by navalarya** [comment] 2017-07-29 11:09
doesn't no undef implicitly means no-use-before-define? documentation on no undef http://eslint.org/docs/rules/no-undef doesn't make it clear enough about use of 'no-use-before-define' rule.

I think a developer may believe that 'no-use-before-define' rule is automatically taken care of while using no undef -. To me both seems to be similar. Setting up both the flags seems to be counter intuitive.

**Comment by not-an-aardvark** [comment] 2017-07-29 11:16
`no-undef` reports using variables that are not declared anywhere. `no-use-before-define` reports variables that are used earlier in the source text than where they're declared.

I agree that this could be distinguished more clearly in the docs. Would you like to submit a PR?

One potential improvement would be to add `no-use-before-define` in a "Related Rules" section in the `no-undef` docs, and vice versa (similar to [this section](http://eslint.org/docs/rules/semi#related-rules) in the `semi` rule).

**Comment by not-an-aardvark** [comment] 2017-08-03 17:11
Closing because this is working as intended, but feel free to submit a PR if you'd like to clarify the docs.

**Closed by not-an-aardvark** 2017-08-03 17:11 UTC
Labels: works as intended

**Comment by navalarya** [comment] 2017-08-03 22:04
yes sure. I will. Can you guide me how do I go about doing it. PR process.

Thanks

**Comment by not-an-aardvark** [comment] 2017-08-03 23:59
We have a pull request guide [here](http://eslint.org/docs/developer-guide/contributing/pull-requests).
