### ISSUE TITLE
object-shorthand and rest operator

### ISSUE THREAD

**Issue by zallek** [eslint/eslint#2514] opened 2015-05-12 17:29 UTC
Eslint version: 0.21.0

`object-shorthand` might not handle ES6 rest operator properly

The following error is fired with these pieces of code
`Expected property shorthand  object-shorthand`

When Destructuring:
```
let { stacks, all, style, ...otherProps } = this.props;
```
When 'Restructuring' (what the proper name for that ?).
```
let group = {foo: 'bar'};
return {
   ...group,
   options: _.filter(group.options, (option) => !filterValue || filterOption(filterValue, option, group)),
};
```

**Comment by xjamundx** [comment] 2015-05-12 18:08
Looking into it...

**Comment by xjamundx** [comment] 2015-05-12 18:12
Okay, so thinking about this for a second. Object-rest params are an ES7 thing.

**Comment by ilyavolodin** [comment] 2015-05-12 18:15
Duplicate of #2486 We do not support object spread.

**Closed by ilyavolodin** 2015-05-12 18:15 UTC
Labels: question

**Comment by zallek** [comment] 2015-05-12 18:18
Ok right thx.
