### ISSUE TITLE
Get Cannot read property 'value' of null when i use arrow-function in the es6 class syntax (arrow-body-style)

### ISSUE THREAD

**Issue by MrKou47** [eslint/eslint#10514] opened 2018-06-25 04:11 UTC
**Tell us about your environment**

* **ESLint Version:** v4.17.0
* **Node Version:** v9.11.1
* **npm Version:** 5.6.0
* **vistual studio code Version:** 1.24.1

**What parser (default, Babel-ESLint, etc.) are you using?** babel-eslint

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
module.exports = {
  parser: 'babel-eslint',
  plugins: ['import', 'recommend-import'],
  extends: 'airbnb',
  env: {
    es6: true,
    browser: true,
    node: true,
  },
  rules: {
    'max-len': [2, 240, 2, { ignoreUrls: true, ignoreComments: false }],
    'no-underscore-dangle': 0,
    'no-mixed-operators': 0,
    'function-paren-newline': 0,
    'arrow-parens': 0,
    'object-curly-newline': 0,
    'prefer-destructuring': 0,
    'no-shadow': 1,
    'react/forbid-prop-types': 0,
    'react/jsx-boolean-value': 0,
    'react/jsx-filename-extension': 0,
    'react/jsx-no-bind': 0,
    'react/no-array-index-key': 0,
    'react/prefer-stateless-function': 0,
    'react/sort-comp': 0,
    'react/no-did-mount-set-state': 0,
    'react/require-default-props': 1,
    'react/no-unused-prop-types': 1,
    'jsx-a11y/click-events-have-key-events': 0,
    'jsx-a11y/heading-has-content': 0,
    'jsx-a11y/no-noninteractive-element-interactions': 0,
    'jsx-a11y/no-static-element-interactions': 0,
    'jsx-a11y/media-has-caption': 0,
    'jsx-a11y/no-autofocus': 0,
    'jsx-a11y/label-has-for': 1,
    'jsx-a11y/anchor-is-valid': 1,
    'jsx-a11y/alt-text': 1,
    'jsx-a11y/anchor-has-content': 1,
    'jsx-a11y/iframe-has-title': 1,
    'import/no-extraneous-dependencies': 0,
    'import/no-named-as-default': 0,
    'recommend-import/no-import-lib': 2,
    'react/require-default-props': 0,
    'react/prop-types': [2, { ignore: ['children', 'location'] }],
    camelcase: ['error'],
    'comma-dangle': [
      'error',
      {
        arrays: 'always-multiline',
        objects: 'always-multiline',
        imports: 'always-multiline',
        exports: 'always-multiline',
        functions: 'ignore',
      },
    ],
  },
  
  globals: {
    location: true,
    isFinite: true,
    window: true,
  },
};
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
class A extends React.Component {
  constructor(props){
     super(props);
  }
  
  customerFunc = item => {
     return // when i enter the 'return' code, the eslint is broken.
  }
}
```

**What did you expect to happen?**
no error
**What actually happened? Please include the actual, raw output from ESLint.**
I got the error stack from the VS code panel.
```bash
[Error - 12:06:23] ESLint stack trace:
[Error - 12:06:23] TypeError: Cannot read property 'value' of null
    at Object.isOpeningBraceToken (/User/workspace/node_modules/eslint/lib/ast-utils.js:354:17)
    at validate (/User/workspace/node_modules/eslint/lib/rules/arrow-body-style.js:127:41)
    at listeners.(anonymous function).forEach.listener (/User/workspace/node_modules/eslint/lib/util/safe-emitter.js:47:58)
    at Array.forEach (native)
    at Object.emit (/User/workspace/node_modules/eslint/lib/util/safe-emitter.js:47:38)
    at NodeEventGenerator.applySelector (/User/workspace/node_modules/eslint/lib/util/node-event-generator.js:251:26)
    at NodeEventGenerator.applySelectors (/User/workspace/node_modules/eslint/lib/util/node-event-generator.js:280:22)
    at NodeEventGenerator.leaveNode (/User/workspace/node_modules/eslint/lib/util/node-event-generator.js:303:14)
    at CodePathAnalyzer.leaveNode (/User/workspace/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:630:23)
    at Traverser.leave [as _leave] (/User/workspace/node_modules/eslint/lib/linter.js:1009:32)
```

**Comment by platinumazure** [comment] 2018-06-25 13:51
Hi @MrKou47, thanks for the issue.

I'm not sure this is an ESLint issue. ESLint does not support class properties at this point. It seems to me that babel-eslint should ensure they are outputting valid ESTree syntax if at all possible.

That said, it does look like class properties are stage 3, so if babel-eslint doesn't have a change to make here, we could consider accepting your PR to avoid the crash (per our [experimental syntax policy](https://github.com/eslint/eslint#what-about-experimental-features)).

**Comment by platinumazure** [comment] 2018-06-25 14:09
I tried to reproduce this with non-experimental syntax, but was unable to get the error. I think this suggests that babel-eslint isn't giving us a consistent token list (or the ranges are incorrect). ([Demo](https://eslint.org/demo/#eyJ0ZXh0IjoiLyogZXNsaW50IGFycm93LWJvZHktc3R5bGU6IFtlcnJvciwgJ2FzLW5lZWRlZCddICovXHJcblxyXG5jb25zdCBmdW5jID0gKCkgPT4geyByZXR1cm4gfSIsIm9wdGlvbnMiOnsicGFyc2VyT3B0aW9ucyI6eyJlY21hVmVyc2lvbiI6Niwic291cmNlVHlwZSI6InNjcmlwdCIsImVjbWFGZWF0dXJlcyI6e319LCJydWxlcyI6e30sImVudiI6e319fQ==))

Hopefully another team member can double-check and either confirm or let me know if I've misinterpreted something.

**Comment by MrKou47** [comment] 2018-06-26 03:59
@platinumazure Thanks for your reply! But it's seems hard to debug.. i will open an issue in the babel-eslint repo and relate this issue.

**Comment by MrKou47** [comment] 2018-06-26 06:32
@platinumazure Hello, i just tried to find some error message from the error stack. And i find that [arrow-body-style#L129](https://github.com/eslint/eslint/blob/master/lib/rules/arrow-body-style.js#L129) called `sourceCode.getFirstToken`, and [getFirstToken](https://github.com/eslint/eslint/blob/master/lib/token-store/cursor.js#L49) might return `null`. So `astUtils.isOpeningBraceToken` will borken. Is this insecure?

**Comment by not-an-aardvark** [comment] 2018-06-26 06:39
Closing as a duplicate of https://github.com/eslint/eslint/issues/10372

**Closed by not-an-aardvark** 2018-06-26 06:39 UTC
Labels: bug, evaluating, rule
