### ISSUE TITLE
Brace-style messes with spacing

### ISSUE THREAD

**Issue by CapacitorSet** [eslint/eslint#8373] opened 2017-03-31 06:58 UTC
**Tell us about your environment**

* **ESLint Version:** v3.18.0
* **Node Version:** v6.10.1
* **npm Version:** 3.10.10

**What parser (default, Babel-ESLint, etc.) are you using?** default

**Please show your full configuration:**

```
extends: 'eslint:recommended'
rules:
  curly: error
  dot-notation: warn
  indent:
    - error
    - 2
    - outerIIFEBody: 0
  brace-style:
    - error
    - 1tbs
```

**What did you do? Please include the actual source code causing the issue.**

I ran `eslint --fix test.js` on the following source code:

```js
if (true) a = 1;
else      a = 0;
```

**What did you expect to happen?**

I expected the file to be reformatted like this:

```js
if (true) {
  a = 1;
} else {
  a = 0;
}
```

**What actually happened? Please include the actual, raw output from ESLint.**

It was formatted like this, with "ugly" spacing:

```js
if (true) {
  a = 1;
}else      {
  a = 0;
}
```

**Comment by not-an-aardvark** [comment] 2017-03-31 20:18
Thansks for the report. This is a duplicate of https://github.com/eslint/eslint/issues/8043, so please follow that issue instead.

**Closed by not-an-aardvark** 2017-03-31 20:18 UTC
Labels: triage
