### ISSUE TITLE
package.jon "exports" option

### ISSUE THREAD

**Issue by heekyu** [eslint/eslint#13513] opened 2020-07-21 07:51 UTC
node 12.18.0, 14.5.0

./node_modules/.bin/eslint --env-info
Environment Info:

Node version: v14.5.0
npm version: v6.14.5
Local ESLint version: v7.4.0 (Currently used)
Global ESLint version: Not found

**What parser (default, Babel-ESLint, etc.) are you using?**
default

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```
module.exports = {
  env: {
    es2020: true,
    mocha: true,
  },
  extends: [
    'airbnb-base',
  ],
  parser: '@typescript-eslint/parser',
  plugins: [
    '@typescript-eslint',
  ],
  rules: {
    '@typescript-eslint/no-unused-vars': 'error',
    'import/no-extraneous-dependencies': ['error', { devDependencies: ['**/test.ts', 'src/common/test/**/*.ts'] }],
    'import/extensions': ['error', 'ignorePackages', {
      ts: 'never',
    }],
    'no-unused-vars': 'off',
  },
  settings: {
    'import/resolver': {
      node: {
        extensions: ['.ts'],
        paths: ['./src'],
      },
    },
  },
};

```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

in module A's package.json use "exports"
```
{
  ...
  "exports": {
    "./": "./lib/"
  }
   ...
}

```

```
eslint --ext .js,.ts src/
```

**What did you expect to happen?**
B's package.json
```
{
  "dependencies": {
    "A": "A's url"
  }
}
```
when source code is
```
import bar from 'A/foo/bar';
```
From module B
it runs well where bar.js is in "node_modules/A/lib/foo/bar"
but eslint fail with "Unable to resolve path to module"

**What actually happened? Please include the actual, raw output from ESLint.**
eslint failed

**Are you willing to submit a pull request to fix this bug?**

**Comment by mdjermanovic** [comment] 2020-07-21 11:35
Hi @heekyu, thanks for the issue!

Can you please post the raw output from ESLint?  I believe you're getting a linting error from `eslint-plugin-import`, but just to be sure.

**Comment by heekyu** [comment] 2020-07-22 03:00
Hi @mdjermanovic , thanks for reply!

error message is
**1:22  error  Unable to resolve path to module '***'  import/no-unresolved**

**Comment by mdjermanovic** [comment] 2020-07-22 10:08
Thanks for the additional details!

This is a linting error from a third-party rule [import/no-unresolved](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/no-unresolved.md).

Could you please open an issue in the plugin's repository:

https://github.com/benmosher/eslint-plugin-import

**Comment by plus-ultra-git** [comment] 2020-07-23 08:06
Thanks!

https://github.com/benmosher/eslint-plugin-import/issues/1810

same issue is in eslint-plugin-import

please close this issue.

**Comment by heekyu** [comment] 2020-07-23 08:27
Thanks!

benmosher/eslint-plugin-import#1810

same issue is in eslint-plugin-import

please close this issue.

**Comment by mdjermanovic** [comment] 2020-07-23 21:26
Closing since the problem isn't related to ESLint core rules.

**Closed by mdjermanovic** 2020-07-23 21:26 UTC
Labels: 3rd party plugin
