### ISSUE TITLE
Fixing autofix

### ISSUE THREAD

**Issue by nzakas** [eslint/eslint#5329] opened 2016-02-18 22:27 UTC
There have been a few issues recently with people asking to add more autofixing. This is definitely something we want to address, but we can't do it with the way autofixing works right now. This (unfortunately long) issue is meant to outline what we currently have, its limitations, and start towards thinking about how to fix autofix so we can use autofix in as many places as possible.
## Intro

When ESLint first implemented autofixing, our belief was that it was primarily useful for making small changes, mostly whitespace and anything that could be contained within a single token. Most of the complaints people had about ESLint rules was that they hated going through and fixing alignment or adding/removing semicolons but loved the error catches. So naturally, I thought if we could get the whitespace and other small autofixes in, that would make people happy. It did, it's just that then we started getting requests to autofix more rules and we realized that the current system doesn't scale well.
## How it Works Today

Today's autofix is based on text and is latched onto how ESLint has always worked: 
1. ESLint makes a single traversal through the AST of the file.
2. Rules listen for different nodes and evaluate the AST as it goes, producing messages when it finds something wrong.
3. Rules can optionally specify a way to fix each message it reports. The fix is indicated by range offsets (the same as used in the `range` object on AST nodes). This fix is _not_ guaranteed to be applied and will not even be attempted until after the complete traversal is finished.
4. After the traversal is complete, all of the proposed fixes are sorted in descending order of range location. So a fix at location 10 comes before a fix at 5.
5. The fixer attempts to apply the fixes in this order. If two fixes overlap in range, then only the first is applied. This continues until all potential fixes have been processed.
6. If a fix is applied, then that message is removed from the lint results of the file.
7. The remaining lint results are presented to the user.

Because of the single traversal, we can't apply the fixes as we go because it would affect other rules as it goes. For instance, if we changed a `let` to a `const`, that then pushes the ranges of everything in the tree by two, so when does that calculation happen? Also, each rule is triggered multiple times at different nodes, and many of the rules try to track things in between those triggers - the built-in assumption is that the tree looks the same as the first time the rule is triggered.
### Problems

Due the single traversal mode, we have several problems:
1. It's possible that not all fixes will be applied.
2. It's possible for a fix to be applied that violates a different rule. For instance, one rule could insert a comma while another requires a space after a comma. The rule requiring the space has no idea that a new comma was added because it's done after the rule has already executed.
3. It's possible for a fix to change scope evaluation. For instance, changing `var` to `const` has implications based on the functions or block statements using it. That can invalidate a whole host of rules because scope calculations are done once, before the traversal.
4. It's possible for a fix to introduce an error into the program by changing the meaning of the code.

As a result of these problems, we decided to limit what we'd allow as fixes in core rules to whitespace and other small changes. Semicolons were a big pain point, so even though they aren't whitespace, we determined the value of fixing these was high enough to be worth any potential other problems. The same with string literals. We actually removed autofixing for `===` after we realized it would change the meaning of the condition and cause a runtime error. We then decided that any new autofixes would just be whitespace to avoid any other complications.
## Where I Went Wrong

Looking back, I think I made several design decisions that were incorrect. These are the things I think I got wrong (and I use "I" here since I came up with the design):
1. Autofix mode should just do fixes and not worry about unfixable rules. Right now it acts just like linting, outputting any messages it didn't fix. That seems unnecessary.
2. The text-based fixes were a naive approach to autofixing that was targeted at whitespace fixes as a primary use case. It's clear text-based fixes aren't scaleable.
3. Trying to fit autofixing into the same single traversal system as the linting is too limiting.
## The Future

So now that I've explained the current state of stuff, I think we have an opportunity to fix it (no pun intended). This will likely be a big breaking change, but hopefully will be better for what people really want to use autofix for. I don't know the implementation details, but I have a high-level of idea of where I'd like to see autofix go.
### Requirements
1. Autofix mode just does fixes and does not do any unfixable rule linting at all. (That means `--fix` doesn't output any linting problems.)
2. Autofix logic for each rule is contained with the rule file that does linting, not it another file.
3. Autofix logic in rules is declarative and doesn't force rules to do something like `if (mode === "fix") { fix() }`. Basically, we can't throw away the way rules work today, there are too many core rules and plugins with rules to force everyone to rewrite in a dramatic way.
4. Multiple autofix passes can be done on the same file to ensure as many fixes as possible are applied.
5. Regardless of fixes, ESLint must never output a file with illegal syntax as the final result.
6. Autofix should work for custom nodes that aren't part of the ESTree spec (I'm thinking about Flow, TypeScript, and other derivatives that add custom nodes into an ESTree AST). 
### Ideas: Config

One of my ideas is that you should be able to specify which rules you want autofix to apply for, so in your config file, you'd do something like:

``` yaml
rules:
    semi: "fix"
    quotes: ["fix", "double"]
```

This would be an extension of the work done in https://github.com/eslint/eslint/issues/3626 to allow "off", "warn", and "error" as options instead of 0, 1, and 2. 

I think this would be a big win because it gives us a good idea about how to save time: during fixing, we just load the rules marked as "fix" and ignore the rest. That should cut down on the runtime (so long as not every rule is fixable!)

**Open Question:** When not running in fix mode, what does "fix" mean? Is it "warn" or "error"?
### Concerns

Some other concerns I have with changes are:
1. Is it possible to do multiple fixes in a single traversal? Or do we need to do one rule's fixes at a time?
2. Do we need to do nonwhitespace rules first and whitespace rules second? Or do we just bite the bullet and say we always need at least two passes per file to get as many fixes as possible? (Or just keep doing passes until all fixes are applied?)
3. How will this work with code path analysis? Changing nodes around affects code paths dramatically.
4. How will this work with escope and scope evaluation? Will we have to run scope analysis multiple times? How will that affect performance
## Next Steps

This is just the beginning of the conversation, there are a ton of details that need to be hashed out. I just wanted to share this to ensure everyone that we are thinking about it and we do want to make improvements.

**Comment by zxqfox** [comment] 2016-02-18 23:42
Guess, 'fix' should gracefully degrade to 'error' since user expects fixed error. But I still not sure we need 'fix' as severity since users want linting by default that means autofix should be under a flag. The last means we shouldn't mark rules in configuration as fixers. IMO.

**Comment by ilyavolodin** [comment] 2016-02-19 00:26
@zxqfox We had requests to allow fixing of just a few specific rules, and not everything.
I don't think I really like `fix`, due to the fact that it has a specific meaning, which is very confusing when you'd run in lint mode. Something like `fixOrError`, `fixOrWarn` might be clearer, although more verbose (and I don't like it either).
With multipass approach we have to watch out for rules conflicting with each other, or we can get into infinite loop situation.

**Comment by zxqfox** [comment] 2016-02-19 00:35
> Is it possible to do multiple fixes in a single traversal?

Good examples are:
```js
var a, b, c;
c = {x: 10};
// vs
var a, b, c = { x : 10 };
// vs
var a, b;
var c = {
  x: 10
};
// vs
var a;
var b;
var c = {x: 10};
```

Feels like it's possible with some kind of CST. All we need is fix tokens directly.

> Do we need to do nonwhitespace rules first and whitespace rules second?

Guess, the example should answer on this. Depends on what we have in tree.

> (Or just keep doing passes until all fixes are applied?)

That's how JSCS worked (before CST). It's not ideal solution.



> We had requests to allow fixing of just a few specific rules, and not everything.

Yeah, but... We can do more ;-)

**Comment by ilyavolodin** [comment] 2016-02-19 01:23
> Feels like it's possible with some kind of CST. All we need is fix tokens directly.
If you fix tokens directly (in CST or AST, doesn't matter), that invalidates the tree, and we have to re-run it though escope, and all of the rules. We have over 200 rules (and that's not counting plugins), we should be very careful about invalidating syntax tree, or autofixing will take forever, even on a single file.

**Comment by zxqfox** [comment] 2016-02-19 09:34
@ilyavolodin I don't see problem with invalidation since the bottleneck is CPU and we can clone original tree to the fixed one (or just put our meta-data to the original tree), right? Don't get why you trying to avoid using tokens btw. If you skipping information about whitespaces, last commas in arrays, you can't guarantee that you did all right.

**Comment by mikesherov** [comment] 2016-02-19 16:53
Perf on autofix shouldn't be a huge concern IMO because it's not the majority use case. Unless it's extremely slow (slow enough to be noticeable on one file), then the main use case is *run once* on entire codebase, then run a bunch of times (like on save) for individual files. Simplicity wins for me here personally.

With that said, whitespace fixes are a solved problem: as long as there is an interface for catching errors, that same interface can be used to fix the error. Add space, remove space, add new line, indent are all as trivial to detect as they are to fix. This solves the "no need for new code" desire that @nzakas has. Also, just keep doing passes until the number of remaining errors doesn't go down. There's a small chance the number can go up and ultimately end up going down, but the simplest, good enough solve is a dumb multipass as I described.

Non whitespace fixes is not an area I explored, so I'll defer to the rest there.

In this regard though, I think the intuition of separating the whitespace fix stage from the non whitespace fix stage is a good one.

**Comment by nzakas** [comment] 2016-02-19 18:47
@ilyavolodin we can always shorten to something line "wfix" for warning or fix and "efix" for error or fix. I agree with you, it seems like being explicit is the right way to go.

@zxqfox I don't think he's trying to avoid using tokens, it's just that changing tokens could result in a different AST from those tokens. Keeping around the original tree and a modified tree is an interesting idea.

**Comment by alberto** [comment] 2016-02-20 12:57
Ok, here are some ideas. Sorry if we already do any of this or if some idea is stupid or wrong:
- Just make eslint faster:
  - Run multiple parallel processes (assuming we are CPU bound).
  - Enable cache by default.
  - Cache eslint results per file and only rerun for modified files.

- Run fixable rules once, and run eslint without autofix to expose all fixes.

- Multipass:
  - Rerun only for the files that were modified.
  - Declare rules a fix could affect and rerun those. (risky, I know).
  - Allow users to opt-in into multipass, and set the maximum number of passes/time spent.

I would also to opt-out of autofixing for each rule instead of opt-in (only disable rules that mess up my code).

**Comment by nzakas** [comment] 2016-02-22 21:21
I had an "ah ha" moment this weekend. The reason why we care about conflicts is because we report linting errors during autofixing, and if two rules conflict, you're going to get a linting error reported that is inaccurate. To me, that's the cardinal sin of the current implementation - lying to the user. We should never lie, even by accident.

Then it occurred to me: we can remove this problem by just not printing linting errors in autofix mode. This is part of what I mentioned in the original description, but I believe this is the lowest-hanging fruit that would allow us to start including more fixes. By not showing the linting errors, we aren't lying to the user, and we will require them to re-run ESLint in lint mode to be shown the errors (which would then be accurate).

Instead, we could output something like this when in autofix mode:

```
Fixed 152 problems in 12 files.
```

So what I'd like to propose is that we do a small breaking release (3.0.0) in which the only breaking change is this. That would open us up to allow more fixes of rules without making architectural changes, and then we can continue to incrementally improve autofix to address some of the other problems I mentioned above.

Thoughts?

**Comment by platinumazure** [comment] 2016-02-22 21:29
Just speaking for myself, I think it's a much worse sin when we apply a fix and then that *introduces* a linting error. I don't think I've seen cases where lint errors were inaccurate as a result of a fix, unless you're referring to the omission of an error that should show up when you say we "lie to the user"?

**Comment by nzakas** [comment] 2016-02-22 21:44
> I think it's a much worse sin when we apply a fix and then that introduces a linting error.

I disagree. Lying about what's actually going on is much worse than introducing a linting error. If you're being lied to, you don't know what to fix.

**Comment by mikesherov** [comment] 2016-02-22 22:33
In JSCS, we kept number fixer until number of remaining errors didn't go down. Then we stopped and reported the remaining number of errors we couldn't auto fix. Does that sound right @nzakas?

**Comment by nzakas** [comment] 2016-02-22 23:06
@mikesherov are you asking me if you're correct or suggesting that ESLint might do that?

**Comment by mikesherov** [comment] 2016-02-22 23:08
Suggesting it should be the desired behavior.

**Comment by nzakas** [comment] 2016-02-22 23:18
Ah okay. That's basically what we're already doing (though we just do one pass), and that's why we have issues with creating conflicts and how we ultimately end up lying to the user. 

My original claim (in this issue) is that `--fix` shouldn't bother doing any work that cannot possibly result in a fix, because I'm not sure of the value of doing that other work. (We had a long-ish discussion about what `--fix` should output starting here: https://github.com/eslint/eslint/issues/3134#issuecomment-137253315). 

If we want to keep the current behavior, we can do so by separating out fixes from nonfixes (keying on "wfix" or "efix"), do multiple passes with things that should result in a fix until the number doesn't go down, then run the file through the linter and output that.

I think the question is: is the current behavior desirable and correct or not?

**Comment by platinumazure** [comment] 2016-02-23 00:42
> I disagree. Lying about what's actually going on is much worse than introducing a linting error. If you're being lied to, you don't know what to fix.

I seem to be missing something. Can you please give me an example of how we lie to the user in the current implementation? Thanks!

**Comment by platinumazure** [comment] 2016-02-23 03:48
Also @nzakas, unrelated to our other discussion, I'm wondering if I should hold off on implementing plugin autofix for a while? Unless you think the actual fix representation (range to replace, text to replace with) is highly unlikely to change, in which case I can press on. What do you think?

**Comment by nzakas** [comment] 2016-02-23 17:15
> I seem to be missing something. Can you please give me an example of how we lie to the user in the current implementation?

We *could* be lying. For instance, suppose someone has `comma-spacing` such that they require no space before the comma. If they also have `comma-dangle` set to "never", and there's code like this:

```js
var x = {
    foo: bar ,
};
```

We don't know which one of the rules will be executed first. If `comma-dangle` is fixable, and it's executed first, then `comma-spacing` will still report an error because fixes are only applied after the traversal completes, even though the comma would have been removed.

For bonus points, `no-trailing-spaces` should trigger in this case, because the space before the comma would not be removed. However, that issue will not be reported because `no-trailing-space` isn't running on the fixed code, it's running on the original code. So here we have a lie by omission.

**Comment by platinumazure** [comment] 2016-02-23 17:29
Thanks @nzakas, that's a great example.

I think the root cause of those issues is that the rules simply don't have
enough information and aren't designed around those possible collisions.
That said, I am :+1: for doing what we can to minimize impact to users
until we can find ways to improve the rule design. Thanks again for the
illumination.

**Comment by nzakas** [comment] 2016-02-23 20:53
@alberto sorry, I missed your comment somehow. 

Making ESLint faster is, of course, a great goal. The problem is that we can always be faster, so it's hard to know when we're making good progress vs. when we're trying to squeeze blood from a stone. The question is really when are we fast enough? And if people are willing to wait, how much does that matter?

I think multipass is the most rational way to go, and if we can limit the amount of work on each pass, then that will help the perf issue. For instance, if we consider having at least two phases, the fixing phase and the linting phase, then we can do multiple passes in the fixing phase (only with rules specified for fixing) and then do the linting phase on the result.

> I would also prefer to opt-out of autofixing for each rule instead of opt-in (only disable rules that mess up my code).

I'm not sure this is feasible. In general, I think we want users telling us specifically what we're allowed to touch in their code rather than being overly aggressive. Remember, we are modifying their code, and pretty much everything else in ESLint is explicitly opt-in at this point (our one big opt-out experiment, `--reset`, led us to realize that we were wrong).

**Comment by zxqfox** [comment] 2016-02-24 02:59
> We could be lying. For instance, suppose someone has comma-spacing such that they require no space before the comma. If they also have comma-dangle set to "never", and there's code like this

@nzakas If we have tokens, we could make a flag `disappear: true` that will hide these tokens in resulting code. In that way order doesn't matter anymore. Am I missing something?

**Comment by BYK** [comment] 2016-02-24 13:20
This may sound a bit too much but why don't we consider using [Operational Transformation](https://en.wikipedia.org/wiki/Operational_transformation) on the fix actions. We can assume each rule as an individual collaborator on the code and then use OT to generate a combined result.

**Comment by BYK** [comment] 2016-02-24 13:27
There's even an OT library in JS: https://operational-transformation.github.io/ot-for-javascript.html

**Comment by nzakas** [comment] 2016-02-24 19:57
@zxqfox that helps for this specific example, but what about the case where a token is inserted? What if removing or adding the token should result in a change to the AST? And keep in mind, we have 200 rules, what if they're all making different changes?

**Comment by zxqfox** [comment] 2016-02-24 20:05
@nzakas This means we need some declarative language? To split instructions and process. Rules which uses our language would be autofixable. I can't argue on why It's better that nothing, but for me it's like using `goto` or `try-catch` in javascript. For fixing code efficiently we need good abstraction.

**Comment by nzakas** [comment] 2016-02-24 21:04
@BYK OT is more designed for multiple simultaneous edits, where what we are doing is more sequential. I also think we need a bit more structure because we have a defined syntax we must create, so some of the guesses OT makes in certain circumstances could result in invalid syntax. If we're going to do anything more than what we're currently doing, I think we need something that is syntax-aware.

**Comment by SpadeAceman** [comment] 2016-02-27 04:04
Regarding "efix" and "wfix", they seem too cryptic to me. How about "error-fix" and "warn-fix"? That way, opting into fixing is as easy as appending "-fix" to what's already there. (Well, in most cases – I'm assuming "off-fix" wouldn't be allowed.)

**Comment by lencioni** [comment] 2016-04-01 16:05
What do you think about integrating a tool like [jscodeshift](https://github.com/facebook/jscodeshift) for autofixing?

**Comment by ilyavolodin** [comment] 2016-04-01 17:32
@lencioni jscodeshift doesn't keep track of whitespaces (at least I don't think it does), so it will actually reformat your code in a lot of ways.

**Comment by nzakas** [comment] 2016-04-14 20:59
Our informal Twitter poll (https://twitter.com/geteslint/status/713112461998628865) shows that people are overwhelmingly in favor of applying more fixes even if that means a slower experience. Given that, I'm going to experiment a bit with doing multiple passes of files. Doing multiple passes would, in the short term, allow us to fix more problems without needing to completely change the way we do fixes. I think this is a good small step to get better compatibility with JSCS 2.x.

**Comment by jamestalmage** [comment] 2016-04-23 17:51
> @lencioni jscodeshift doesn't keep track of whitespaces (at least I don't think it does), so it will actually reformat your code in a lot of ways.

Nope - that's wrong. It uses `recast` under the hood, which is specifically focused on not mucking with whitespace. It is basically guaranteed not to touch whitespace for nodes you do not modify. For entirely new AST nodes, it attempts to infer your whitespace rules from the surrounding code. It does a pretty good job at that, but it is not perfect. It should be possible to extend `recast`s pretty printer to honor whitespace rules from the core eslint plugins (creating an extensible system that allowed third party plugin authors to influence whitespace rules for the pretty printer might be difficult).

// @benjamn

**Comment by jamestalmage** [comment] 2016-04-23 18:29
`jscodeshift` probably isn't the best tool, since it really is designed to operate on collections of AST nodes. Instead it would probably be best just to use `recast` directly.

**Comment by sindresorhus** [comment] 2016-04-23 19:20
Using [`recast`](https://github.com/benjamn/recast) for autofixing would give us a much nicer API for modifying the AST ([example](https://github.com/jamestalmage/ava-codemods/blob/master/lib/utils.js)). The [current API](http://eslint.org/docs/developer-guide/working-with-rules#applying-fixes) is very limited. It would also enable code sharing of AST utilities between ESLint autofixing and [codemods](https://github.com/facebook/jscodeshift).

**Comment by mikesherov** [comment] 2016-04-23 19:31
Last time I used recast, which admittedly was a while ago, it screwed up whitespace for arrays of you modified a member. 

Also, does recast have an API to modify whitespace?

If not, ESLint would need to implement two separate APIs for code for fixing, one that is whitespace modifying, and one that isn't.

I'm not opposed to using recast if it's up for the task, but only if makes what we need to do inside ESLint easier for us and the devs using our plugin arch.

**Comment by jamestalmage** [comment] 2016-04-23 20:17
`recast` is really a full stack AST transform utility, similar to `babel-core`, in that it encompasses a parser, a AST visitor/transformation API, and a pretty printer.

What makes it unique is that when it reprints the AST, it honors the original whitespace, comments, single-quotes vs double-quotes, unnecessary parens, etc. From the docs:

> The magic of Recast is that it reprints only those parts of the syntax tree that you modify. In other words, the following identity is guaranteed:
>
>```
>recast.print(recast.parse(source)).code === source
>```

-- 

`recast` uses `esprima` as it's default parser, but [it's easy to swap that out](https://github.com/benjamn/recast/blob/master/lib/options.js#L5).

[`ast-types`](https://github.com/benjamn/ast-types) is used as the default visitor/transform solution. I love `ast-types`, it is far and above my favorite AST visitor / transform implementation (though it lacks an equivalent for [`babel-template`](https://www.npmjs.com/package/babel-template)). Still, you aren't tied to that, ESLint could continue to use `estraverse` without any problems.

I think the major value of `recast` in this situation is the pretty printer that combines the original source and the `loc` information from parsed nodes to honor the original formatting. It works very, very well. Most of that magic happens [here](https://github.com/benjamn/recast/blob/master/lib/patcher.js).

One thing `recast` is not set up to do is honor explicit formatting rules. It does allow you to specify a few formatting options (tabs, tab-width, single-quotes, etc). But not to the level ESLint would require.

Perhaps the best solution would be to fork [`printer.js`](https://github.com/benjamn/recast/blob/master/lib/printer.js) and [`patcher.js`](https://github.com/benjamn/recast/blob/master/lib/patcher.js) from `recast`, and extend `printer.js` to honor rule settings when printing unmodified nodes.

> Also, does recast have an API to modify whitespace?

No - but there's [talk of supporting that](https://github.com/benjamn/recast/issues/147)

**Comment by pmcelhaney** [comment] 2016-08-30 20:33
Catching up on this old thread, I see there are some suggestions to make "warn-fix" / "error-fix" (or something along those lines) configuration options. 

I'd like to suggest that you consider a rule available to the fixer by default. That's how it works now, and it seems to be working fine so far. 

Instead, allow the config to *opt out* of autofixing for particular rules, so the meaning of "warn" and "error" do not change, but another optional flag is added. 

```
rules:
    semi: "error",
    sort-keys: "error nofix",
    sort-vars: "warn nofix"
```

**Comment by alberto** [comment] 2017-03-11 19:25
Closing since this is a meta issue

**Closed by alberto** 2017-03-11 19:25 UTC
Labels: breaking, core, evaluating, needs bikeshedding
