### ISSUE TITLE
Change Request: Suggestion to update disable message from UX POV

### ISSUE THREAD

**Issue by krunalbad** [eslint/eslint#16220] opened 2022-08-19 12:26 UTC
### ESLint version

v7.5.0

### What problem do you want to solve?

I have a suggestion to update the disable camelcase message

### What do you think is the correct solution?

while disabling camelcase eslint gives the below message
`// eslint-disable-next-line camelcase`
but it should `// eslint-disable-next-line camelCase`

See below image from VSCode:
![Screenshot 2022-08-19 at 5 54 55 PM](https://user-images.githubusercontent.com/45413622/185617749-d45cd2f7-057b-4d83-9b14-e54c7974a67e.png)

### Participation

- [ ] I am willing to submit a pull request for this change.

**Comment by nzakas** [comment] 2022-08-19 20:16
Sorry, there's not enough information in this issue to know how to respond. Please explain exactly the change you want to make and why.

Please note, the ESLint VS Code extension is not maintained by this team.

**Comment by krunalbad** [comment] 2022-08-20 10:13
@nzakas Okay understood. I have opened it here. https://github.com/microsoft/vscode-eslint/issues/1513

**Comment by krunalbad** [comment] 2022-08-24 16:41
@nzakas WRT this [comment](https://github.com/microsoft/vscode-eslint/issues/1513#issuecomment-1221946785) I am guessing this is the rule change that is managed by this repo itself

**Comment by nzakas** [comment] 2022-08-25 21:02
@krunalbad once again, there's not enough information for me to respond. I don't understand what it is you're asking or what kind of change you're requesting. Please use some sentences to describe what you think the problem is and what you think the solution is.

**Comment by kecrily** [comment] 2022-08-26 07:44
I don't think rule name should use camelCase. and the wavy lines that appear in your diagram I think are caused by all your other extensions.

**Comment by krunalbad** [comment] 2022-08-27 07:32
Ok @kecrily It was just a suggestion.

**Comment by nzakas** [comment] 2022-09-05 17:41
Closing as we aren’t going to do anything here.

**Closed by nzakas** 2022-09-05 17:41 UTC
Labels: enhancement, triage, core, needs info
