### ISSUE TITLE
Plugins that are a dependency to a config package that aren't hoisted can't be loaded

### ISSUE THREAD

**Issue by freaktechnik** [eslint/eslint#13500] opened 2020-07-17 19:53 UTC
**Tell us about your environment**

Environment Info:

Node version: v13.11.0
npm version: v6.14.5
Local ESLint version: v7.4.0 (Currently used)
Global ESLint version: Not found

**What parser (default, Babel-ESLint, etc.) are you using?** I think default, but not relevant.

**Please show your full configuration:**

https://github.com/freaktechnik/transifex-loader/blob/master/src/.eslintrc.json

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

Run eslint (npx eslint or npm run lint:js in that project).

**What did you expect to happen?**

Eslint to happily lint the project.

**What actually happened? Please include the actual, raw output from ESLint.**

```
eslint:config-array-factory Loaded: @freaktechnik/eslint-config-webpack@7.2.0 (/home/martin/dev/transifex-loader/node_modules/@freaktechnik/eslint-config-webpack/index.js) +1ms
  eslint:config-array-factory Loading JS config file: /home/martin/dev/transifex-loader/node_modules/@freaktechnik/eslint-config-webpack/index.js +0ms
  eslint:config-array-factory Loading {extends:"plugin:import/errors"} relative to /home/martin/dev/transifex-loader/node_modules/@freaktechnik/eslint-config-webpack/index.js +0ms
  eslint:config-array-factory Loading plugin "import" from /home/martin/dev/transifex-loader/node_modules/@freaktechnik/eslint-config-webpack/index.js +0ms
  eslint:config-array-factory Failed to load plugin 'import' declared in 'src/.eslintrc.json » @freaktechnik/eslint-config-webpack'. +1ms

Oops! Something went wrong! :(

ESLint: 7.4.0

ESLint couldn't find the plugin "eslint-plugin-import".

(The package "eslint-plugin-import" was not found when loaded as a Node module from the directory "/home/martin/dev/transifex-loader".)

It's likely that the plugin isn't installed correctly. Try reinstalling by running the following:

    npm install eslint-plugin-import@latest --save-dev

The plugin "eslint-plugin-import" was referenced from the config file in "src/.eslintrc.json » @freaktechnik/eslint-config-webpack".
```

Having plugins as dependencies of configs is working fine - in fact eslint happily loads a bunch of them before this. However, those plugins were all hoisted, this plugin is not. It is in `/home/martin/dev/transifex-loader/node_modules/@freaktechnik/eslint-config-webpack/node_modules/eslint-plugin-import`.

In order for the non-hoisted plugin to work https://github.com/eslint/eslint/blob/ada2c891298382f82dfabf37cacd59a1057b2bb7/lib/cli-engine/config-array-factory.js#L864-L868 would have to set `pluginBasePath` to the dirname of the config. I've verified that that makes everything work as expected. However that might break configs that expect their extends/plugins to be peer dependencies, I guess?

**Are you willing to submit a pull request to fix this bug?**

Sure, if this behavior is deemed incorrect (which I hope it is, since it makes eslint configs much more useful and not accidentally broken in a weird edge case). However I would need guidance toward how to/what to test.

**Comment by mdjermanovic** [comment] 2020-07-27 21:47
Hi @freaktechnik, thanks for the issue.

I think this is a duplicate of  #3458. 

In short, having plugin as a dependency of a shareable config might work well in some cases, but it isn't actually supported. End users should install the plugin as a dev dependency. An alternative at the moment is to create a plugin instead of the shareable config, as described in https://github.com/eslint/eslint/issues/3458#issuecomment-257161846.

This will be changed in some of the future versions, per eslint/rfcs#9. With the new configuration file format, shareable configs will be able to specify plugins as direct dependencies.

**Comment by mdjermanovic** [comment] 2020-08-10 16:58
I'm closing this since it isn't a bug with the actual configuration system. Per our [documentation about shareable configs](https://eslint.org/docs/developer-guide/shareable-configs), end-users of a shareable config are required to specifiy all plugins as dev-dependecies:

> If your shareable config depends on a plugin, you should also specify it as a peerDependency (plugins will be loaded relative to the end user's project, so the end user is required to install the plugins they need).

We are working on a new configuration file format that will support plugins as dependencies in shareable configs.

You can follow the implementation progress here: #13481

**Closed by mdjermanovic** 2020-08-10 16:58 UTC
Labels: core, evaluating
