### ISSUE TITLE
Tabs used for indentation in comment not autofixed by `indent` rule

### ISSUE THREAD

**Issue by SimenB** [eslint/eslint#7337] opened 2016-10-10 19:53 UTC
**Tell us about your environment**

* **ESLint Version:** 3.7.1
* **Node Version:** 6.7.0
* **npm Version:** 3.10.8

**What parser (default, Babel-ESLint, etc.) are you using?**
default

**Please show your full configuration:**

```json
{
  "rules": {
    "no-tabs": "error",
    "indent": ["error", 2]
  }
}
```

**What did you do? Please include the actual source code causing the issue.**

Ran `node_modules/.bin/eslint file.js --fix`

```js
	// A comment
  var someVar;
```

(it's a tab character above, even if GH renders it as spaces... It's saved with space though, so you can edit this post to get it)

Alternative: `echo '\t// some comment\n  var someVar;' > file.js && node_modules/.bin/eslint file.js --fix`

**What did you expect to happen?**
That `indent` would autofix the tab indentation into spaces

**What actually happened? Please include the actual, raw output from ESLint.**
`1:2  error  Unexpected tab character  no-tabs`

**Comment by not-an-aardvark** [comment] 2016-10-10 20:06
Thanks for the report.

I think this is a duplicate of https://github.com/eslint/eslint/issues/6571. The issue is that the indent rule currently doesn't check the indentation of comments.

**Comment by SimenB** [comment] 2016-10-10 20:10
Probably a dupe yeah, just easier repro steps 😄 Feel free to close, the issues are linked now anyways

**Comment by SimenB** [comment] 2016-10-10 20:21
@not-an-aardvark Another case:

Not concerning tabs, but function arguments `echo 'someFunction(\n\tinvocation\n);' >file.js && node_modules/.bin/eslint file.js --fix`
Same result (tab not replaced). New issue for it?

**Comment by not-an-aardvark** [comment] 2016-10-10 20:29
At the moment, the `indent` rule doesn't report function parameters by default. (Also see: https://github.com/eslint/eslint/pull/7189, https://github.com/eslint/eslint/issues/5946)

For a collection of all the issues on `indent`, see https://github.com/eslint/eslint/issues/7274.

**Comment by not-an-aardvark** [comment] 2016-10-10 20:31
I'm going to close this issue as a duplicate, but please feel free to follow https://github.com/eslint/eslint/issues/7274 for updates!

**Closed by not-an-aardvark** 2016-10-10 20:31 UTC
Labels: triage

**Comment by SimenB** [comment] 2016-10-10 20:32
Wow, that's a lot of issues. Will be following that one!
Any update after the "90%" of 2 weeks ago? 😄

**Comment by not-an-aardvark** [comment] 2016-10-10 20:34
Still at around 90%, haven't had much of a chance to work on it lately.
