### ISSUE TITLE
.eslintrc is being read from more than just current directory

### ISSUE THREAD

**Issue by MikaAK** [eslint/eslint#6357] opened 2016-06-09 20:49 UTC
**What version of ESLint are you using?**
2.11.1
**What parser (default, Babel-ESLint, etc.) are you using?**
default
**Please show your full configuration:**
## Config in `project/client/.eslintrc`
```json
{
  "parserOptions": {
    "sourceType": "module",
    "ecmaVersion": "7",
    "ecmaFeatures": {
      "impliedStrict": true,
      "experimentalObjectRestSpread": true
    },
  },

  "env": {
    "es6": true,
    "browser": true,
    "jquery": true,
    "jasmine": true,
    "mocha": true,
    "commonjs": true,
    "phantomjs": true
  },
  "rules": {
    "semi": [2, "never"]
  }
}
```

## Config in `project/.eslintrc` - ESLINT v 1.x
```json
{
  "rules": {
    "strict": [2, "global"],
    "no-undef": 2,
    "no-use-before-define": 2,
    "new-cap": 0,
    "no-constant-condition": 2,
    "key-spacing": 0,
    "array-bracket-spacing": [2, "never"],
    "brace-style": 2,
    "camelcase": [2, {"properties": "always"}],
    "comma-spacing": [2, {"before": false, "after": true}],
    "no-debugger": 1,
    "no-trailing-spaces": 1,
    "eol-last": 0,
    "no-dupe-keys": 2,
    "no-dupe-args": 2,
    "no-duplicate-case": 2,
    "no-empty-character-class": 2,
    "no-ex-assign": 2,
    "no-empty": 2,
    "no-extra-boolean-cast": 1,
    "quote-props": [2, "as-needed"],
    "no-return-assign": 0,
    "no-underscore-dangle": 0,
    "max-nested-callbacks": [2, 4],
    "space-unary-ops": [1, {
      "words": true,
      "nonwords": false
    }],
    "space-infix-ops": 2,
    "space-before-keywords": [2, "always"],
    "space-in-parens": [2, "never"],
    "space-before-function-paren": [1, "never"],
    "max-depth": [2, 6],
    "linebreak-style": [2, "unix"],
    "space-before-blocks": [1, "always"],
    "space-return-throw-case": 1,
    "no-unused-vars": 2,
    "no-multi-spaces": 0,
    "no-multi-str": 2,
    "no-native-reassign": 2,
    "no-redeclare": 2,
    "no-self-compare": 2,
    "no-throw-literal": 2,
    "wrap-iife": [2, "inside"],
    "operator-linebreak": [2, "after"],
    "operator-assignment": [2, "always"],
    "object-curly-spacing": [2, "never"],
    "space-after-keywords": [2, "always"],
    "no-spaced-func": 2,
    "no-unneeded-ternary": 1,
    "padded-blocks": [2, "never"],
    "prefer-const": 0,
    "no-func-assign": 2,
    "no-inner-declarations": 2,
    "no-invalid-regexp": 2,
    "no-regex-spaces": 1,
    "no-sparse-arrays": 2,
    "valid-typeof": 2,
    "block-scoped-var": 2,
    "dot-location": [2, "property"],
    "dot-notation": 2,
    "eqeqeq": 2,
    "no-alert": 2,
    "no-case-declarations": 2,
    "no-empty-label": 2,
    "no-empty-pattern": 2,
    "no-eval": 2,
    "no-extra-bind": 1,
    "no-labels": 2,
    "no-lone-blocks": 2,
    "no-loop-func": 2,
    "use-isnan": 2,
    "no-irregular-whitespace": 1,
    "no-negated-in-lhs": 2,
    "no-obj-calls": 2,
    "prefer-spread": 2,
    "one-var": [2, {"uninitialized": "always"}],
    "curly": 0,
    "computed-property-spacing": [2, "never"],
    "comma-style": [2, "last"],
    "no-console": 1,
    "indent": [2, 2, {
      "SwitchCase": 1,
      "VariableDeclarator": {
        "var": 2,
        "let": 2,
        "const": 3
      }
    }],
    "quotes": [2, "single"],
    "semi": [2, "always"],
    "no-extra-semi": 2
  },
  "env": {
    "node": true,
    "mocha": true
  },
  "globals": {
  }
}
```
**What did you do? Please include the actual source code causing the issue.**
Run eslint in `project/client/testfile.js` on test file
```javascript
var a = function() {

}
```
**What did you expect to happen?**
Running eslint from `project/client` to use the .eslintrc from that folder and not give any errors
**What actually happened? Please include the actual, raw output from ESLint.**
It seems that it takes both configs from `project/.eslintrc` and `project/client/.eslintrc` when running from `client`. I've upgraded our client side to v2 but the backend is still in v1 meaning rules conflict. As  a result I'm getting errors like this 

```
/Users/mika/Documents/Edvisor/angular/client/loader/loader.js
  1:1  error    Rule 'space-before-keywords' was removed and replaced by: keyword-spacing    space-before-keywords
  1:1  warning  Rule 'space-return-throw-case' was removed and replaced by: keyword-spacing  space-return-throw-case
  1:1  error    Rule 'space-after-keywords' was removed and replaced by: keyword-spacing     space-after-keywords
  1:1  error    Rule 'no-empty-label' was removed and replaced by: no-labels                 no-empty-label

```

## Fix
Removing the rules from `project/.eslintrc` stops the errors

**Comment by gyandeeps** [comment] 2016-06-09 21:14
I think its working as expected.

You can use `root: true`, if you dont want to include any config files from above that folder.

**Comment by ilyavolodin** [comment] 2016-06-09 22:20
This is the default behavior of ESLint and have never been modified. ESLint will cascade configs from all of the parent directories. As @gyandeeps mentioned, you can add `"root": true` to your config file to stop ESLint from traversing to the parent directories.

Closing, as this is behaving as intended.

**Closed by ilyavolodin** 2016-06-09 22:20 UTC
Labels: question

**Comment by MikaAK** [comment] 2016-06-10 01:17
Oh I missed this! Thanks for the pointer.
