### ISSUE TITLE
Can we color issue labels to allow for grouping and reduce cognitive load?

### ISSUE THREAD

**Issue by platinumazure** [eslint/eslint#6299] opened 2016-05-31 16:37 UTC
This has nothing to do with ESLint as an application, just a repository management concern.

I'd like to see if we could group some issue labels together and use the same color, to make it easier for us to learn how an issue is scoped. For example, "build"/"cli"/"infrastructure"/"core"/"rule" could be grouped as a sort of "scope" label group, and they could all be the same color; then if I see a label that's (for example) blue then I know it's for scope and will be one of those five values.

I tried to do that in my eslint-plugin-qunit repository (see [here](https://github.com/platinumazure/eslint-plugin-qunit/labels), don't know if the page is viewable without being a collaborator), but the label space is much simpler there since it is assumed that pretty much all issues have to do with a rule.

Synopsis of what I'm doing in eslint-plugin-qunit:
* Scope: Colored blue, values are bug/build/chore/docs/enhancement/feature
* Evaluating: Colored light purple, values are evaluating/"needs bikeshedding"
* No further action: Colored white, values are duplicate/invalid/wontfix
* Don't process immediately: Colored red, values are blocked/breaking/"needs issue"
* Miscellaneous:
  * "accepted" is green
  * "question" is pink

I'm not suggesting that any labels be changed, just their colors for grouping purposes.

**Comment by platinumazure** [comment] 2016-06-10 21:13
@nzakas I know this sort of thing would be bottom priority for you, but I wanted to make sure this at least got onto the bottom of your radar. (As much as radars have bottoms, anyway.)

**Comment by nzakas** [comment] 2016-06-14 00:08
I'm personally 👎 On this. I use the colors to quickly scan, so I can easily tell what is a bug vs. not and what component it deals with. Changing all the components to be the same and all the severities to be the same would make it harder for me personally as I'd have to actually start reading the labels instead of scanning for color. 

That said, if everyone thinks making such a change is helpful, I'll go along, but my initial reaction is that I don't like it.

**Comment by platinumazure** [comment] 2016-07-08 04:49
Right now, some labels are the same color and are not obviously related (and some labels are close enough that it's hard for me to read them sometimes). So I can dig not wanting to have a bunch of labels be the same color, but right now they aren't even really unique. For example, rule and tsc agenda are basically the same, question and accepted are pretty close.

Anyway, these are just suggestions. I certainly don't everyone to mindlessly cater to my struggles :smile:

**Comment by gyandeeps** [comment] 2016-07-08 14:17
I am going to close this since we have reached a conclusion point.

**Comment by michaelficarra** [comment] 2016-07-08 14:46
Have we really? We have 4 contributor 👍s and 1 👎.

> That said, if everyone thinks making such a change is helpful, I'll go along, but my initial reaction is that I don't like it.

Sounds like just about everyone supports this.

**Comment by nzakas** [comment] 2016-07-08 14:58
@michaelficarra that's a bit of a stretch as there are 18 team members. 

I'm still very much against such homogenization. If we need to tweak some colors to avoid confusion, I'm fine with that, but recoloring build, cli, rule, etc. to be the same color seems like a horrible idea to me. I don't see any functional value.

**Comment by platinumazure** [comment] 2016-07-08 15:18
Thanks for reopening the discussion.

I can definitely understand that for me and others like me, a color could be useful as an indication of the label category, and that I can quickly read the label to know what the issue is about in that category; whereas for @nzakas and others like him, a color would be more useful as a unique representation of the label itself.

I don't mind things the way they are now, except for some of the similarly-colored labels that have nothing to do with each other. So I am not going to push strongly for coloring by category.

**Comment by ilyavolodin** [comment] 2016-07-08 16:18
I actually really like how [stylelint](https://github.com/stylelint/stylelint/labels) does their labels. Maybe we can do something similar? But if we leave labels as they are, I'm not sure I would want them colored in a proposed way.

**Comment by nzakas** [comment] 2016-07-08 19:23
@platinumazure can you share which labels currently give you the most trouble? Maybe we can solve that pain point by shifting some of their colors.

**Comment by alberto** [comment] 2016-08-26 17:22
ping @platinumazure

**Comment by platinumazure** [comment] 2016-08-28 23:53
Very sorry for losing track of this.

Actual problems (in my view):
* accepted and question are similar shades of blue (but not the same), also about the same length, so hard to distinguish
* invalid and roadmap are very close to same color, have opposite meanings, and are about the same length
* beginner and evaluating are the same color (cross purposes, and beginner should be easy to distinguish if feasible)

Quick wins (in my view):
* Make "accepted" a unique color (change either accepted or documentation to get there)
* Change "invalid" to white (like wontfix) to avoid confusion with roadmap
* Change "beginner" to a welcoming color, maybe a shade of green, to avoid confusion with evaluating

Possible problems:
* blocked/breaking/"do not merge" are same shade of red, bug is different shade of red
  * Maybe these could just be made the same-- I don't mind red being used as a general warning label
* rule and "tsc agenda" are same color
* "needs bikeshedding" and "needs prototype" are similar shades-- I'd be okay with just making them the same color since those are tags that indicate needing of something.
* core and feature are similar shades (but fairly distinguishable otherwise)
* documentation and question are same color (but fairly distinguishable otherwise)

Strengths of current labeling scheme:
* triage, needs info are unique colors
* Easy to distinguish between triage, evaluating, needs info, and accepted

**Comment by ilyavolodin** [comment] 2016-08-29 00:40
One note. We have no issues marked as "invalid", I think we should just remove that, as well as a few other tags that nobody ever uses ("duplicate", "needs prototype", "priority", etc.)
In general, label colors don't really bother me. I'm not opposed to changing them, but I also don't see a huge need either.

**Comment by nzakas** [comment] 2016-08-30 18:44
I think we can safely remove "duplicate" since I think you may be the only one who uses it and its redundant to what is hopefully the closing comment "Duplicate of #1234". Definitely can remove "invalid" and "priority".

"needs prototype" we just created for one issue - I think it's good to keep around and am not opposed to changing its color to the same "needs bikeshedding".

I'd like to avoid green labels if possible because the bounty label is green.

The labels I think should stay there current color: accepted, bug, do not merge, blocked. If you want to change others to avoid ambiguities, I'd say just do it and people will complain if it really bothers them.

In general, I think we just need to finish this issue up. We have way more important things to deal with. :)

**Comment by platinumazure** [comment] 2016-09-02 17:38
Okay, here's what I've done so far:

* I removed duplicate, invalid, and priority.
* I changed the color of "beginner" to `#006b75` (I believe that was the color "priority" was originally). It's a dark blue-green, let me know if you think it's too close to "bounty".
* I changed "needs prototype" to be same color as "needs bikeshedding".
* I changed "question" to be `#d4c5f9`, to get it away from "accepted". This is now the same as "website".

One last question:

* Can/should we remove "website", since we generally just try to redirect issues to [eslint.github.io](https://github.com/eslint/eslint.github.io)? Then "question"'s color choice is unique and also distinct from many other labels.

**Comment by nzakas** [comment] 2016-09-02 20:55
Sometimes people report website issues in this repo (site is down, etc.). Rather than forcing them to open an issue elsewhere, it's easier to just handle it here, so I'd keep that label.

**Comment by platinumazure** [comment] 2016-09-02 20:59
@nzakas Okay, sounds good. I've changed "website" to a color that was unused. Let me know if you want me to change or revert anything, otherwise one of us can close this issue.

**Comment by nzakas** [comment] 2016-09-03 00:38
Done!

**Closed by nzakas** 2016-09-03 00:38 UTC
Labels: question
