### ISSUE TITLE
[switch-case] space between colon and opening brace whend defining a case

### ISSUE THREAD

**Issue by lucendio** [eslint/eslint#5776] opened 2016-04-03 16:14 UTC
**What version of ESLint are you using?**
`2.6.0`

**What parser (default, Babel-ESLint, etc.) are you using?**
`Espree`

**Please show your full configuration:**
```js
parserOptions:
    ecmaVersion: 6
    sourceType: module
    ecmaFeatures: 
        globalReturn: true
        impliedStrict: true
        jsx: false

env:
    browser: true
    commonjs: true
    es6: true
    node: true
    mocha: true
    jasmine: true
    meteor: true

plugins: [ ]

rules:
    indent: [ 2, 4, { SwitchCase: 1 } ] 
    linebreak-style: [ 2, 'unix' ]
    quotes: [ 2, 'single', 'avoid-escape' ]
    semi: [ 2, always ]
    
    no-case-declarations: 2
    space-before-blocks: [
        2,
        {
            functions: 'never', 
            keywords: 'never', 
            classes: 'never'
        }
    ]
```
**What did you do? Please include the actual source code causing the issue.**
```js
switch( state ){
    case 'state1': {
        console.log( 'foo' );
        break;
    }
    case 'state2': {
        console.log( 'bar' );
        break;
    }    
    default: {
        throw new Error( 'unsupported state' );
    }
}
```

**What did you expect to happen?**
that the opening braces in the same line of each `case` wont get marked, because there is a space in front of them.

**What actually happened? Please include the actual, raw output from ESLint.**
`error  Unexpected space before opening brace  space-before-blocks`

**additional info and thoughts:**
When changing the the config to `keywords: 'always'` the mentioned braces dont get marked. Since this syntax looks a lot more like a simple field declatartion in an object literal, I think, it does make sense to put a space between colon and brace in this case. Imho this situation doesnt so great into the `keywords` group or in any other given group. What are your thoughts on this? Maybe an additional rule is needed for this?
NOTE: I have a lot more rules, but the combination of the last two seem to cause the error. (Tried the simplified config above - same problem)

**Comment by mysticatea** [comment] 2016-04-03 18:09
I think you need a space in the first line.

```js
switch( state ){
```

**Comment by platinumazure** [comment] 2016-04-03 18:51
@mysticatea If that fixes the issue, that means the error message is wrong. It should say a space is needed before the block.

@luciendo Could you please add the line and column number from the error message you're getting? Right now it's not clear if it is happening on the switch line or the case line. Also, you don't need braces for case statements- does the error go away if you remove the braces? It could be that this is a bug in space-before-blocks that is not accounted for simply because it assumes nobody will write blocks for case statements.

**Comment by platinumazure** [comment] 2016-04-03 18:52
@lucendio Oops, I typed your name wrong and can't edit. Please read the message above this one and please accept my apologies for getting your name wrong. Thanks!

**Comment by mysticatea** [comment] 2016-04-03 18:53
Ah!
Sorry, I was wrong.

**Comment by platinumazure** [comment] 2016-04-03 19:00
@mysticatea Not necessarily. The rule could have a bug and output the wrong error message. I just wanted to get the questions out there since I haven't had time to dig in. Sorry if I came off as rude.

**Comment by mysticatea** [comment] 2016-04-03 19:12
@platinumazure No worries. I had forgotten `"never"` option of `space-before-blocks` rule and I had focused on the number (1) of messages in the issue before I read it enough. I confirmed `space-before-blocks` is warning between `:` and `{`.

`no-case-declarations` enforce the blocks in switch-case in order to introduce block-scoping for each `case`.

Indeed, eslint does not have the rule to enforce/disallow spacing around colon of labels, `case`, and `default`.
So this issue can be a proposal of some new spacing rule.

**Comment by lucendio** [comment] 2016-04-03 20:07
@platinumazure no worries, all good :)
as you reqested:
```
   2:20  error  Unexpected space before opening brace  space-before-blocks
   6:20  error  Unexpected space before opening brace  space-before-blocks
  10:14  error  Unexpected space before opening brace  space-before-blocks
```
Becasue of the problems metioned in [no-case-declarations](http://eslint.org/docs/rules/no-case-declarations), I like the idea of enforcing braces for each case. But since there is no explicit rule for that, just configured `no-case-declarations`. 
Yes the errors goes away when I remove the braces, and thats only because my example does not contain a block scope declaration, otherwise it would throw.

So yes, maybe `space-before-blocks` has to make aware of such case. (And maybe a new rule, like *enforce braces on cases to create block scope*, could help as well)

thanks for your time guys.

**Comment by kaicataldo** [comment] 2016-08-25 21:14
Closing this because we haven't made any progress in months. Thanks for contributing!

**Closed by kaicataldo** 2016-08-25 21:14 UTC
Labels: enhancement, evaluating, rule
