### ISSUE TITLE
Autofix for no-duplicate-imports

### ISSUE THREAD

**Issue by Samuel-Beslogic** [eslint/eslint#14919] opened 2021-08-11 21:11 UTC
**What rule do you want to change?**
`no-duplicate-imports`

**Does this change cause the rule to produce more or fewer warnings?**
Fewer after autofixing

**How will the change be implemented? (New option, new default behavior, etc.)?**
New default behavior

**Please provide some example code that this change will affect:**
```js
import { Route } from 'react-router-dom'
import { Link as RouterLink, Switch, withRouter } from 'react-router-dom'
```

**What does the rule currently do for this code?**
Raise a linting issue when an import is duplicated

**What will the rule do after it's changed?**
Automatically merge duplicated imports, when possible (the example I gave looks feasible)

**Are you willing to submit a pull request to implement this change?**
Not at the moment as I don't yet know how to code ESLint rules and autofixes.

**Comment by nzakas** [comment] 2021-08-19 00:45
> Not at the moment as I don't yet know how to code ESLint rules and autofixes.

Would you be willing to learn? Proposals are more compelling with a prototype.

**Comment by bmish** [comment] 2021-08-19 01:43
In favor of adding a fixer and we might be able to borrow autofixing code from the third-party rule [import/no-duplicates](https://github.com/import-js/eslint-plugin-import/blob/master/docs/rules/no-duplicates.md).

**Comment by lextoc** [comment] 2021-09-22 16:22
I'm going to try to add this auto-fix feature. First time working on ESLint, will keep you posted on how it goes.

**Comment by mdjermanovic** [comment] 2021-09-22 21:35
I'm not sure if this rule should be auto-fixable, because two imports from the same source might be caused by a mistakenly specified source in one of them (e.g., after a copy-paste). This rule is classified as [`type: "problem"`](https://github.com/eslint/eslint/blob/e3cd1414489ceda460d593ac7e7b14f8ad45d4fc/lib/rules/no-duplicate-imports.js#L232), which means that the reported problems are possible errors in the code. Those rules, in my opinion, shouldn't be auto-fixable.

**Comment by lextoc** [comment] 2021-09-23 07:17
Maybe we can apply it on imports using object destructuring only and first check if the imports are actually exported in the file so that we know it's a valid import. And if it's a valid import, try to merge it with the other import that already exists. What do you think @mdjermanovic ?

**Comment by mdjermanovic** [comment] 2021-09-23 10:44
> first check if the imports are actually exported in the file so that we know it's a valid import

Core rules currently don't examine imported modules, that functionality would require additional parsing, caching, options to define custom resolvers, etc., so this autofix can only use the content of the file being linted.

**Comment by lextoc** [comment] 2021-09-23 14:54
In that case I think your point is really valid and we probably shouldn't implement it or people might end up frustrated using it. Thanks for the speedy comment/feedback.

**Comment by nzakas** [comment] 2021-09-24 00:27
Seems like there is agreement that it doesn’t make sense to pursue this, so closing.

**Closed by nzakas** 2021-09-24 00:27 UTC
Labels: enhancement, rule

**Comment by Samuel-Beslogic** [comment] 2021-10-05 22:48
> apply it on imports using object destructuring only

That would've been perfect, but

> Core rules currently don't examine imported modules

Unfortunate, but understandable :/
Well if anyone decides to implement a plugin/extension with a rule that attempts to solve this. Feel free to tag me!

**Comment by ljharb** [comment] 2021-10-05 23:52
@samuel-beslogic the only one i know of is https://github.com/import-js/eslint-plugin-import
