### ISSUE TITLE
Change: no-param-reassign exclude properties

### ISSUE THREAD

**Issue by PaulDejardin** [eslint/eslint#6032] opened 2016-05-01 18:14 UTC
**What version of ESLint are you using?**
1.10.3

**What parser (default, Babel-ESLint, etc.) are you using?**
default

Spinning this issue off [original comment](https://github.com/eslint/eslint/issues/1599#issuecomment-216058811)

I'm currently evaluating no-param-reassign for a fairly large code base, because it's easy to perpetuate a pattern of mutating a single large argument blob over time, but it makes the code quite difficult to read and debug. The rule matches over 400 times, 90% of which could be considered extraneous to the core logic (stuff like assigning things to the global object, or to a parameter called scope (this is an Angular app). In practice that means it is difficult to employ this rule because those few arguments are "OK" to modify for structural reasons which would be difficult to refactor.

I'd like to propose adding another parameter to this rule for excluding specific property paths.

```
{
  "error",
  {
    "props": true,
    "exclude": {
      "global": false,
      "global.library": true,
      "scope": true,
      "some.other.specific.path.two": false
    }
  }
}
```

**Comment by alberto** [comment] 2016-08-01 21:24
Duplicate of https://github.com/eslint/eslint/issues/6505

**Closed by alberto** 2016-08-01 21:24 UTC
Labels: enhancement, evaluating, rule
